### ISSUE TITLE
Can't understand this problem

### ISSUE THREAD

**Issue by devangmehta123** [aws/aws-cli#101]
Hi,

I am new to python but I managed to install awscli on version 2.7.4 on Windows (ActivePython).

Yesterday, everything was working fine. By everything, I mean, I could do "aws ec2 help" and "aws ec2 describe-instances" and see the JSON output.

Today, there is a problem and nothing has changed from my side. My internet is working fine.

Can you help?

Thanks.
Devang

PS D:\vvroot\workspace\main\trunk\scripts 22> aws ec2 help
Traceback (most recent call last):
  File "C:\Python27\Scripts\aws.cmd", line 58, in <module>
    main()
  File "C:\Python27\Scripts\aws.cmd", line 54, in main
    driver.main()
  File "C:\Python27\lib\site-packages\awscli\clidriver.py", line 366, in main
    self.create_main_parser()
  File "C:\Python27\lib\site-packages\awscli\clidriver.py", line 89, in create_main_parser
    self.cli_data = self.session.get_data('cli')
  File "C:\Python27\lib\site-packages\botocore\session.py", line 266, in get_data
    return botocore.base.get_data(self, data_path)
  File "C:\Python27\lib\site-packages\botocore\base.py", line 168, in get_data
    raise botocore.exceptions.DataNotFoundError(data_path=data_path)
botocore.exceptions.DataNotFoundError: Unable to load data for: cli

**Comment by MatthewRalston** [comment]
I'm having the same issue on `aws-cli/1.15.4 Python/2.7.8 Linux/2.6.32-504.el6.x86_64 botocore/1.10.4`

I am running a unit test for a function that invokes the cli `create_clidriver.main([args])`. When I run my script/module from the command line, the clidriver runs fine. But inside my test environment with identical `PYTHONPATH`, 'cli' is not found. 
```python
Traceback (most recent call last):
  File "/path/to/synchronize.py", line 31, in s3sync
    exit_code = create_clidriver().main(["s3", "sync", source, destination])
  File "/path/to/.venv/lib/python2.7/site-packages/awscli/clidriver.py", line 195, in main
    parser = self._create_parser(command_table)
  File "/path/to/.venv/lib/python2.7/site-packages/awscli/clidriver.py", line 175, in _create_parser
    command_table['help'] = self.create_help_command()
  File "/path/to/.venv/lib/python2.7/site-packages/awscli/clidriver.py", line 166, in create_help_command
    cli_data = self._get_cli_data()
  File "/path/to/.venv/lib/python2.7/site-packages/awscli/clidriver.py", line 98, in _get_cli_data
    self._cli_data = self.session.get_data('cli')
  File "/path/to/.venv/lib/python2.7/site-packages/botocore/session.py", line 519, in get_data
    return self.get_component('data_loader').load_data(data_path)
  File "/path/to/.venv/lib/python2.7/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/path/to/.venv/lib/python2.7/site-packages/botocore/loaders.py", line 424, in load_data
    raise DataNotFoundError(data_path=name)
DataNotFoundError: Unable to load data for: cli

```
