### ISSUE TITLE
Latest MSI install is broken on Windows 7 and 8.1 64-bit

### ISSUE THREAD

**Issue by lloydcotten** [aws/aws-cli#1053]
I installed the latest version of aws cli for Windows from the MSI available at https://s3.amazonaws.com/aws-cli/AWSCLI64.msi.

Tested this on separate Windows 7 and Windows 8.1 OS 64-bit.

I'm getting the following on every command, even `aws help` and `aws -version`.

```
Traceback (most recent call last):
  File "aws", line 23, in <module>
  File "aws", line 19, in main
  File "awscli\clidriver.pyc", line 49, in main
  File "awscli\clidriver.pyc", line 58, in create_clidriver
  File "awscli\plugin.pyc", line 44, in load_plugins
  File "awscli\plugin.pyc", line 61, in _import_plugins
  File "awscli\handlers.pyc", line 61, in <module>
  File "awscli\customizations\opsworks.pyc", line 24, in <module>
  File "six.pyc", line 89, in __get__

  File "six.pyc", line 153, in _resolve

  File "six.pyc", line 79, in _import_module
    ☺♥☺♫☺
ImportError: No module named pipes
```

**Comment by agadewar** [comment]
I installed the latest version of aws cli for Windows from the MSI available at https://s3.amazonaws.com/aws-cli/AWSCLI64.msi.
I am getting below error :
Traceback (most recent call last):
  File "aws", line 27, in <module>
  File "aws", line 23, in main
  File "awscli\clidriver.pyc", line 49, in main
  File "awscli\clidriver.pyc", line 58, in create_clidriver
  File "awscli\plugin.pyc", line 44, in load_plugins
  File "awscli\plugin.pyc", line 58, in _import_plugins
ImportError: No module named cwlog
