### ISSUE TITLE
'describe-image-attribute --attribute blockDeviceMapping' results in "Unauthorized attempt to access restricted resource"

### ISSUE THREAD

**Issue by DrStrangepork** [aws/aws-cli#1083]
When I attempt to use the "--attribute blockDeviceMapping" option on 'aws ec2 describe-image-attribute', I get an error "Unauthorized attempt to access restricted resource" (error code 255). This apparently has been a problem for quite some time: [this AWS Forums message](https://forums.aws.amazon.com/message.jspa?messageID=231972) has been open for almost 4 years. According to the [APIReference](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImageAttribute.html), the valid attributes are: "description | kernel | ramdisk | launchPermission | productCodes | blockDeviceMapping". All of these work for me except the last.

Here is my output using '--debug' of the same command with 'launchPermission' (working) and 'blockDeviceMapping' (not working):
```
# aws --debug ec2 describe-image-attribute --attribute launchPermission --image-id ami-cf8bd6ff
2015-01-06 13:53:45,356 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.6.10 Python/2.7.5 Linux/3.10.0-123.13.2.el7.x86_64, botocore version: 0.80.0
2015-01-06 13:53:45,356 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x1476410>
2015-01-06 13:53:45,356 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider at 0x1403758>
2015-01-06 13:53:45,357 - MainThread - botocore.service - DEBUG - Creating service object for: ec2
2015-01-06 13:53:45,499 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.ec2: calling handler <function register_retries_for_service at 0xfa2aa0>
2015-01-06 13:53:45,511 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: ec2
2015-01-06 13:53:45,511 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.ec2: calling handler <function signature_overrides at 0xfa2c08>
2015-01-06 13:53:45,512 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.ec2: calling handler <function register_retries_for_service at 0xfa2aa0>
2015-01-06 13:53:45,512 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: ec2
2015-01-06 13:53:45,513 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.ec2: calling handler <function signature_overrides at 0xfa2c08>
2015-01-06 13:53:45,513 - MainThread - botocore.service - DEBUG - Creating operation objects for: Service(ec2)
2015-01-06 13:53:45,542 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <functools.partial object at 0x147cb50>
2015-01-06 13:53:45,543 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-instance
2015-01-06 13:53:45,543 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-volume
2015-01-06 13:53:45,543 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <function add_waiters at 0x140f500>
2015-01-06 13:53:45,568 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'dry-run', <awscli.arguments.BooleanArgument object at 0x1b5bd10>), (u'no-dry-run', <awscli.arguments.BooleanArgument object at 0x1b5bed0>), (u'image-id', <awscli.arguments.CLIArgument object at 0x1b5bf10>), (u'attribute', <awscli.arguments.CLIArgument object at 0x1b5bf50>)])
2015-01-06 13:53:45,568 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-image-attribute: calling handler <function add_streaming_output_arg at 0x125e320>
2015-01-06 13:53:45,569 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-image-attribute: calling handler <function _rename_arg at 0x1480500>
2015-01-06 13:53:45,569 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-image-attribute: calling handler <function _rename_arg at 0x14805f0>
2015-01-06 13:53:45,569 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-image-attribute: calling handler <functools.partial object at 0x14815d0>
2015-01-06 13:53:45,569 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-image-attribute: calling handler <function add_cli_input_json at 0x1400848>
2015-01-06 13:53:45,570 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-image-attribute: calling handler <function unify_paging_params at 0x12650c8>
2015-01-06 13:53:45,571 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-image-attribute: calling handler <function add_generate_skeleton at 0x1400ed8>
2015-01-06 13:53:45,573 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.describe-image-attribute: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x148bc90>>
2015-01-06 13:53:45,573 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.describe-image-attribute: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x1b5bf90>>
2015-01-06 13:53:45,579 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.ec2.describe-image-attribute: calling handler <functools.partial object at 0x1a2fe68>
2015-01-06 13:53:45,579 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-image-attribute.dry-run: calling handler <function uri_param at 0x1248050>
2015-01-06 13:53:45,579 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-image-attribute.image-id: calling handler <function uri_param at 0x1248050>
2015-01-06 13:53:45,580 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.ec2.describe-image-attribute: calling handler <awscli.argprocess.ParamShorthand object at 0x1477590>
2015-01-06 13:53:45,580 - MainThread - awscli.argprocess - DEBUG - Detected structure: scalar
2015-01-06 13:53:45,580 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'ami-cf8bd6ff' for parameter "image_id": u'ami-cf8bd6ff'
2015-01-06 13:53:45,580 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-image-attribute.attribute: calling handler <function uri_param at 0x1248050>
2015-01-06 13:53:45,581 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.ec2.describe-image-attribute: calling handler <awscli.argprocess.ParamShorthand object at 0x1477590>
2015-01-06 13:53:45,581 - MainThread - awscli.argprocess - DEBUG - Detected structure: scalar
2015-01-06 13:53:45,581 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'launchPermission' for parameter "attribute": u'launchPermission'
2015-01-06 13:53:45,581 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-image-attribute.cli-input-json: calling handler <function uri_param at 0x1248050>
2015-01-06 13:53:45,581 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-image-attribute.generate-cli-skeleton: calling handler <function uri_param at 0x1248050>
2015-01-06 13:53:45,582 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.describe-image-attribute: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x1b5bf90>>
2015-01-06 13:53:45,582 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.describe-image-attribute: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x148bc90>>
2015-01-06 13:53:45,582 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2015-01-06 13:53:45,582 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2015-01-06 13:53:45,582 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2015-01-06 13:53:45,583 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: config-file
2015-01-06 13:53:45,583 - MainThread - botocore.credentials - INFO - Credentials found in config file: ~/.aws/config
2015-01-06 13:53:45,589 - MainThread - botocore.operation - DEBUG - Operation:DescribeImageAttribute called with kwargs: {u'Attribute': u'launchPermission', u'ImageId': u'ami-cf8bd6ff'}
2015-01-06 13:53:45,590 - MainThread - botocore.endpoint - DEBUG - Making request for <botocore.model.OperationModel object at 0x1b4cf50> (verify_ssl=True) with params: {'query_string': '', 'headers': {}, 'url_path': '/', 'body': {'Action': u'DescribeImageAttribute', u'Attribute': u'launchPermission', 'Version': u'2014-10-01', u'ImageId': u'ami-cf8bd6ff'}, 'method': u'POST'}
2015-01-06 13:53:45,591 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2015-01-06 13:53:45,591 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

host:ec2.us-west-2.amazonaws.com
user-agent:aws-cli/1.6.10 Python/2.7.5 Linux/3.10.0-123.13.2.el7.x86_64
x-amz-date:20150106T185345Z

host;user-agent;x-amz-date
7613a3ee53dedf4b962d065d6b4ed85ae055f6e228a4988e3ddecbe228f6173c
2015-01-06 13:53:45,592 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20150106T185345Z
20150106/us-west-2/ec2/aws4_request
ca4392713680f663af643c0a46b843c4edcf52d3ffd17b4223f30768fc981eb4
2015-01-06 13:53:45,592 - MainThread - botocore.auth - DEBUG - Signature:
3a093dd2f27ffea5b3fb9cffcac00604c6f99cf16002faed6a2fa10a6def501c
2015-01-06 13:53:45,619 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2015-01-06 13:53:45,620 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): ec2.us-west-2.amazonaws.com
2015-01-06 13:53:46,230 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "POST / HTTP/1.1" 200 None
2015-01-06 13:53:46,234 - MainThread - botocore.parsers - DEBUG - Response headers:
{'content-type': 'text/xml;charset=UTF-8',
 'date': 'Tue, 06 Jan 2015 18:53:45 GMT',
 'server': 'AmazonEC2',
 'transfer-encoding': 'chunked',
 'vary': 'Accept-Encoding'}
2015-01-06 13:53:46,234 - MainThread - botocore.parsers - DEBUG - Response body:
<?xml version="1.0" encoding="UTF-8"?>
<DescribeImageAttributeResponse xmlns="http://ec2.amazonaws.com/doc/2014-10-01/">
    <requestId>40c9fe90-29e0-4268-964f-e4e58fa784fa</requestId>
    <imageId>ami-cf8bd6ff</imageId>
    <launchPermission/>
</DescribeImageAttributeResponse>
2015-01-06 13:53:46,238 - MainThread - botocore.hooks - DEBUG - Event needs-retry.ec2.DescribeImageAttribute: calling handler <botocore.retryhandler.RetryHandler object at 0x1ab4750>
2015-01-06 13:53:46,238 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2015-01-06 13:53:46,239 - MainThread - botocore.hooks - DEBUG - Event after-call.ec2.DescribeImageAttribute: calling handler <awscli.errorhandler.ErrorHandler object at 0x14775d0>
2015-01-06 13:53:46,240 - MainThread - awscli.errorhandler - DEBUG - HTTP Response Code: 200
2015-01-06 13:53:46,240 - MainThread - awscli.formatter - DEBUG - RequestId: 40c9fe90-29e0-4268-964f-e4e58fa784fa
{
    "LaunchPermissions": [],
    "ImageId": "ami-cf8bd6ff"
}

# aws --debug ec2 describe-image-attribute --attribute blockDeviceMapping --image-id ami-cf8bd6ff
2015-01-06 13:54:23,270 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.6.10 Python/2.7.5 Linux/3.10.0-123.13.2.el7.x86_64, botocore version: 0.80.0
2015-01-06 13:54:23,270 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x204d410>
2015-01-06 13:54:23,271 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider at 0x1fdb758>
2015-01-06 13:54:23,273 - MainThread - botocore.service - DEBUG - Creating service object for: ec2
2015-01-06 13:54:23,468 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.ec2: calling handler <function register_retries_for_service at 0x1b79aa0>
2015-01-06 13:54:23,480 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: ec2
2015-01-06 13:54:23,481 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.ec2: calling handler <function signature_overrides at 0x1b79c08>
2015-01-06 13:54:23,482 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.ec2: calling handler <function register_retries_for_service at 0x1b79aa0>
2015-01-06 13:54:23,483 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: ec2
2015-01-06 13:54:23,485 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.ec2: calling handler <function signature_overrides at 0x1b79c08>
2015-01-06 13:54:23,485 - MainThread - botocore.service - DEBUG - Creating operation objects for: Service(ec2)
2015-01-06 13:54:23,526 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <functools.partial object at 0x2053b50>
2015-01-06 13:54:23,526 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-instance
2015-01-06 13:54:23,526 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-volume
2015-01-06 13:54:23,527 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <function add_waiters at 0x1fe7500>
2015-01-06 13:54:23,537 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'dry-run', <awscli.arguments.BooleanArgument object at 0x2732d10>), (u'no-dry-run', <awscli.arguments.BooleanArgument object at 0x2732ed0>), (u'image-id', <awscli.arguments.CLIArgument object at 0x2732f10>), (u'attribute', <awscli.arguments.CLIArgument object at 0x2732f50>)])
2015-01-06 13:54:23,538 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-image-attribute: calling handler <function add_streaming_output_arg at 0x1e35320>
2015-01-06 13:54:23,540 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-image-attribute: calling handler <function _rename_arg at 0x2057500>
2015-01-06 13:54:23,540 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-image-attribute: calling handler <function _rename_arg at 0x20575f0>
2015-01-06 13:54:23,540 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-image-attribute: calling handler <functools.partial object at 0x20585d0>
2015-01-06 13:54:23,541 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-image-attribute: calling handler <function add_cli_input_json at 0x1fd8848>
2015-01-06 13:54:23,542 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-image-attribute: calling handler <function unify_paging_params at 0x1e3c0c8>
2015-01-06 13:54:23,543 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-image-attribute: calling handler <function add_generate_skeleton at 0x1fd8ed8>
2015-01-06 13:54:23,544 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.describe-image-attribute: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x2062c90>>
2015-01-06 13:54:23,544 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.describe-image-attribute: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x2732f90>>
2015-01-06 13:54:23,548 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.ec2.describe-image-attribute: calling handler <functools.partial object at 0x2606e68>
2015-01-06 13:54:23,548 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-image-attribute.dry-run: calling handler <function uri_param at 0x1e1f050>
2015-01-06 13:54:23,549 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-image-attribute.image-id: calling handler <function uri_param at 0x1e1f050>
2015-01-06 13:54:23,550 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.ec2.describe-image-attribute: calling handler <awscli.argprocess.ParamShorthand object at 0x204e590>
2015-01-06 13:54:23,551 - MainThread - awscli.argprocess - DEBUG - Detected structure: scalar
2015-01-06 13:54:23,551 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'ami-cf8bd6ff' for parameter "image_id": u'ami-cf8bd6ff'
2015-01-06 13:54:23,551 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-image-attribute.attribute: calling handler <function uri_param at 0x1e1f050>
2015-01-06 13:54:23,552 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.ec2.describe-image-attribute: calling handler <awscli.argprocess.ParamShorthand object at 0x204e590>
2015-01-06 13:54:23,553 - MainThread - awscli.argprocess - DEBUG - Detected structure: scalar
2015-01-06 13:54:23,553 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'blockDeviceMapping' for parameter "attribute": u'blockDeviceMapping'
2015-01-06 13:54:23,553 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-image-attribute.cli-input-json: calling handler <function uri_param at 0x1e1f050>
2015-01-06 13:54:23,553 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-image-attribute.generate-cli-skeleton: calling handler <function uri_param at 0x1e1f050>
2015-01-06 13:54:23,554 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.describe-image-attribute: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x2732f90>>
2015-01-06 13:54:23,554 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.describe-image-attribute: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x2062c90>>
2015-01-06 13:54:23,554 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2015-01-06 13:54:23,555 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2015-01-06 13:54:23,555 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2015-01-06 13:54:23,555 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: config-file
2015-01-06 13:54:23,556 - MainThread - botocore.credentials - INFO - Credentials found in config file: ~/.aws/config
2015-01-06 13:54:23,582 - MainThread - botocore.operation - DEBUG - Operation:DescribeImageAttribute called with kwargs: {u'Attribute': u'blockDeviceMapping', u'ImageId': u'ami-cf8bd6ff'}
2015-01-06 13:54:23,583 - MainThread - botocore.endpoint - DEBUG - Making request for <botocore.model.OperationModel object at 0x2723f50> (verify_ssl=True) with params: {'query_string': '', 'headers': {}, 'url_path': '/', 'body': {'Action': u'DescribeImageAttribute', u'Attribute': u'blockDeviceMapping', 'Version': u'2014-10-01', u'ImageId': u'ami-cf8bd6ff'}, 'method': u'POST'}
2015-01-06 13:54:23,585 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2015-01-06 13:54:23,586 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

host:ec2.us-west-2.amazonaws.com
user-agent:aws-cli/1.6.10 Python/2.7.5 Linux/3.10.0-123.13.2.el7.x86_64
x-amz-date:20150106T185423Z

host;user-agent;x-amz-date
553d72f1c31210735dfbfe13f9a8d4bdcd503624b6b74ef213a0f19bb8f4068d
2015-01-06 13:54:23,586 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20150106T185423Z
20150106/us-west-2/ec2/aws4_request
60f624da4dcc6fce3f07afddc36c2ce76d06563aa69bbf8eba167d3bdda277dd
2015-01-06 13:54:23,587 - MainThread - botocore.auth - DEBUG - Signature:
427e4116d6c81ce66ceb22e8e416aa2447af5d06f20c27405c9c9b2bc65615c7
2015-01-06 13:54:23,619 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2015-01-06 13:54:23,621 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): ec2.us-west-2.amazonaws.com
2015-01-06 13:54:24,051 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "POST / HTTP/1.1" 400 None
2015-01-06 13:54:24,054 - MainThread - botocore.parsers - DEBUG - Response headers:
{'cneonction': 'close',
 'date': 'Tue, 06 Jan 2015 18:54:23 GMT',
 'server': 'AmazonEC2',
 'transfer-encoding': 'chunked'}
2015-01-06 13:54:24,055 - MainThread - botocore.parsers - DEBUG - Response body:
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>AuthFailure</Code><Message>Unauthorized attempt to access restricted resource</Message></Error></Errors><RequestID>af11b0de-c1ab-4b19-a2e5-71b372981715</RequestID></Response>
2015-01-06 13:54:24,055 - MainThread - botocore.hooks - DEBUG - Event needs-retry.ec2.DescribeImageAttribute: calling handler <botocore.retryhandler.RetryHandler object at 0x268b750>
2015-01-06 13:54:24,056 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2015-01-06 13:54:24,056 - MainThread - botocore.hooks - DEBUG - Event after-call.ec2.DescribeImageAttribute: calling handler <awscli.errorhandler.ErrorHandler object at 0x204e5d0>
2015-01-06 13:54:24,057 - MainThread - awscli.errorhandler - DEBUG - HTTP Response Code: 400
2015-01-06 13:54:24,057 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 197, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 357, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 492, in __call__
    self._operation_object, call_parameters, parsed_globals)
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 597, in invoke
    **parameters)
  File "/usr/lib/python2.7/site-packages/botocore/operation.py", line 98, in call
    parsed=response[1])
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 735, in emit
    return self._events.emit(event_name, **kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 182, in emit
    response = handler(**kwargs)
  File "/usr/lib/python2.7/site-packages/awscli/errorhandler.py", line 70, in __call__
    http_status_code=http_response.status_code)
ClientError: A client error (AuthFailure) occurred when calling the DescribeImageAttribute operation: Unauthorized attempt to access restricted resource
2015-01-06 13:54:24,060 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

A client error (AuthFailure) occurred when calling the DescribeImageAttribute operation: Unauthorized attempt to access restricted resource
```

**Comment by DrStrangepork** [comment]
Also the documentation page for [describe-instance-attribute](http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instance-attribute.html) contains the set of "Valid attribute values", but the documentation page for [describe-image-attribute](http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-image-attribute.html) does not

**Comment by jamesls** [comment]
To summarize what you're seeing in your debug logs, the issue is that the EC2 API is returning an error message stating that this is an unauthorized operation:

```

2015-01-06 13:54:24,055 - MainThread - botocore.parsers - DEBUG - Response body:
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>AuthFailure</Code><Message>Unauthorized attempt to access restricted resource</Message></Error></Errors><RequestID>af11b0de-c1ab-4b19-a2e5-71b372981715</RequestID></Response>
```

Because of this, there isn't really much we can do from the AWS CLI side of things.  This would need to be something that's updated on EC2's side (the EC2 forums would be the best place to report this).

Depending on what you're trying to do, you can potentially get this information from `describe-images`:

```
$ aws ec2 describe-images --image-ids ami-<myid> --query Images[].BlockDeviceMappings[]
[
    {
        "DeviceName": "/dev/sda1",
        "Ebs": {
            "DeleteOnTermination": true,
            "SnapshotId": "snap-<snapshot>",
            "VolumeSize": 8,
            "VolumeType": "standard",
            "Encrypted": false
        }
    },
    {
        "DeviceName": "/dev/sdb",
        "VirtualName": "ephemeral0"
    }
]
```

**Comment by boomshadow** [comment]
Hahaha. I can't believe this is still a problem 3 years later. I get the same exact error in the same eact scenario. Had to switch to describe-images

**Comment by satyam-sareen** [comment]
3 years later, still the error persists
used boto3 with same parametes as above and got this error!
