### ISSUE TITLE
cloudtrail create-subscription fails fetching policy template

### ISSUE THREAD

**Issue by redondos** [aws/aws-cli#1084]
**cloudtrail create-subscription** fails to retrieve the policy template from the "awscloudtrail" S3 bucket:

```
aws cloudtrail create-subscription --name "Default" --s3-use-bucket "com.s3bucket" --s3-prefix "s3prefix" --sns-new-topic "cloudtrail" --include-global-service-events "true"
Setting up new SNS topic cloudtrail...

A client error (AccessDenied) occurred when calling the GetObject operation: Access Denied
```

It seems to be failing on https://github.com/aws/aws-cli/blob/be380472a86452a1521c589d57de09af9987c83f/awscli/customizations/cloudtrail.py#L285, but 
the URL seems valid: https://awscloudtrail.s3.amazonaws.com/policy/SNS/AWSCloudTrail-SnsTopicPolicy-2013-11-01.json

Debug output:

```
2015-01-06 18:21:36,864 - MainThread - botocore.handlers - DEBUG - URI updated to: https://awscloudtrail.s3.amazonaws.com/policy/SNS/AWSCloudTrail-SnsTopicPolicy-2013-11-01.json
2015-01-06 18:21:36,864 - MainThread - botocore.auth - DEBUG - Calculating signature using hmacv1 auth.
2015-01-06 18:21:36,864 - MainThread - botocore.auth - DEBUG - HTTP request method: GET
2015-01-06 18:21:36,864 - MainThread - botocore.auth - DEBUG - StringToSign:
GET


Tue, 06 Jan 2015 23:21:36 GMT
/awscloudtrail/policy/SNS/AWSCloudTrail-SnsTopicPolicy-2013-11-01.json
2015-01-06 18:21:36,865 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [GET]>
2015-01-06 18:21:36,867 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): awscloudtrail.s3.amazonaws.com
2015-01-06 18:21:37,222 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "GET /policy/SNS/AWSCloudTrail-SnsTopicPolicy-2013-11-01.json HTTP/1.1" 403 None
2015-01-06 18:21:37,223 - MainThread - botocore.parsers - DEBUG - Response headers:
{'content-type': 'application/xml',
 'date': 'Tue, 06 Jan 2015 23:21:37 GMT',
 'server': 'AmazonS3',
 'transfer-encoding': 'chunked',
 'x-amz-id-2': 'f+K5FEXlFv4vi8yng71mD+Fib08UnCjAGmZUViOPjSL2yXIxlqadtm7MrlnfZ3y5F5UV6pKEtVQ=',
 'x-amz-request-id': '3EE36E3E9CDE7538'}
2015-01-06 18:21:37,224 - MainThread - botocore.parsers - DEBUG - Response body:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>3EE36E3E9CDE7538</RequestId><HostId>f+K5FEXlFv4vi8yng71mD+Fib08UnCjAGmZUViOPjSL2yXIxlqadtm7MrlnfZ3y5F5UV6pKEtVQ=</HostId></Error>
2015-01-06 18:21:37,224 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.GetObject: calling handler <botocore.retryhandler.RetryHandler object at 0x105cfb410>
2015-01-06 18:21:37,224 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2015-01-06 18:21:37,224 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.GetObject: calling handler <function enhance_error_msg at 0x10461d7d0>
2015-01-06 18:21:37,224 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.GetObject: calling handler <awscli.errorhandler.ErrorHandler object at 0x104675f90>
2015-01-06 18:21:37,224 - MainThread - awscli.errorhandler - DEBUG - HTTP Response Code: 403
2015-01-06 18:21:37,224 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 197, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 357, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/customizations/commands.py", line 181, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/customizations/cloudtrail.py", line 79, in _run_main
    self._call(args, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/customizations/cloudtrail.py", line 152, in _call
    options.sns_custom_policy)
  File "/usr/local/lib/python2.7/site-packages/awscli/customizations/cloudtrail.py", line 286, in setup_new_topic
    key=SNS_POLICY_TEMPLATE)
  File "/usr/local/lib/python2.7/site-packages/awscli/customizations/service.py", line 36, in __call__
    res, data = self._operation.call(self.endpoint, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/operation.py", line 98, in call
    parsed=response[1])
  File "/usr/local/lib/python2.7/site-packages/botocore/session.py", line 735, in emit
    return self._events.emit(event_name, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 182, in emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/awscli/errorhandler.py", line 70, in __call__
    http_status_code=http_response.status_code)
ClientError: A client error (AccessDenied) occurred when calling the GetObject operation: Access Denied
2015-01-06 18:21:37,233 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

A client error (AccessDenied) occurred when calling the GetObject operation: Access Denied
```

Thanks in advance.

**Comment by jamesls** [comment]
This appears to have been a temporary issue.  I've just confirmed that I'm able to call `create-subscription` and have it succeed.

Let us know if you're still seeing issues and we'll take another look.
