### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by murdz** [aws/aws-cli#1198]
Hi,

I cannot run an s3 synx command from my ec2 instance behind a proxy. If I assign a public IP, the command is able to complete, otherwise, it just times out. Output of the failure below:

http_proxy and https_proxy are set via /etc/environments

Version: aws-cli/1.2.9 Python/3.4.0 Linux/3.13.0-36-generic

Output:
2015-03-04 17:52:31,338 - awscli.clidriver - DEBUG - CLI version: aws-cli/1.2.9 Python/3.4.0 Linux/3.13.0-36-generic, botocore version: 0.29.0
2015-03-04 17:52:31,347 - botocore.hooks - DEBUG - Event building-parameter-table.s3.sync: calling handler <function add_cmd_params at 0x7fd0fa61fae8>
2015-03-04 17:52:31,349 - botocore.service - DEBUG - Creating service object for: s3
2015-03-04 17:52:31,349 - botocore.base - DEBUG - Attempting to load: aws/s3
2015-03-04 17:52:31,390 - botocore.base - DEBUG - Found data file: /usr/lib/python3/dist-packages/botocore/data/aws/s3.json
2015-03-04 17:52:31,390 - botocore.hooks - DEBUG - Event service-created: calling handler <function register_retries_for_service at 0x7fd0fa9d98c8>
2015-03-04 17:52:31,391 - botocore.handlers - DEBUG - Registering retry handlers for service: Service(s3)
2015-03-04 17:52:31,391 - botocore.hooks - DEBUG - Event creating-endpoint.s3: calling handler <function maybe_switch_to_s3sigv4 at 0x7fd0fa9d99d8>
2015-03-04 17:52:31,391 - botocore.credentials - INFO - Found credentials in config file.
2015-03-04 17:52:31,394 - botocore.service - DEBUG - Creating operation objects for: Service(s3)
2015-03-04 17:52:31,436 - botocore.operation - DEBUG - Operation:ListObjects called with kwargs: {'bucket': 'bauer-varnish-logs', 'prefix': 'Testing/'}
2015-03-04 17:52:31,436 - botocore.operation - DEBUG - Creating parameter objects for: Operation:ListObjects
2015-03-04 17:52:31,437 - botocore.endpoint - DEBUG - Making request for Operation:ListObjects (verify_ssl=True) with params: {'headers': {}, 'payload': <botocore.payload.XMLPayload object at 0x7fd0fa4a9278>, 'uri_params': {'Prefix': 'Testing/', 'Bucket': 'bauer-varnish-logs'}}
2015-03-04 17:52:31,437 - botocore.endpoint - DEBUG - Building URI for rest endpoint.
2015-03-04 17:52:31,437 - botocore.endpoint - DEBUG - Templated URI path: /{Bucket}
2015-03-04 17:52:31,437 - botocore.endpoint - DEBUG - Templated URI query_params: delimiter={Delimiter}&marker={Marker}&max-keys={MaxKeys}&prefix={Prefix}&encoding-type={EncodingType}
2015-03-04 17:52:31,438 - botocore.endpoint - DEBUG - Rendered path: /bauer-varnish-logs
2015-03-04 17:52:31,438 - botocore.endpoint - DEBUG - Rendered query_params: prefix=Testing/
2015-03-04 17:52:31,438 - botocore.hooks - DEBUG - Event before-auth.s3: calling handler <function fix_s3_host at 0x7fd0fa9d97b8>
2015-03-04 17:52:31,438 - botocore.handlers - DEBUG - Checking for DNS compatible bucket for: https://s3-ap-southeast-2.amazonaws.com/bauer-varnish-logs?prefix=Testing/
2015-03-04 17:52:31,438 - botocore.handlers - DEBUG - URI updated to: https://bauer-varnish-logs.s3.amazonaws.com?prefix=Testing/
2015-03-04 17:52:31,438 - botocore.auth - DEBUG - Calculating signature using hmacv1 auth.
2015-03-04 17:52:31,439 - botocore.auth - DEBUG - HTTP request method: GET
2015-03-04 17:52:31,439 - botocore.auth - DEBUG - StringToSign:
GET

Wed, 04 Mar 2015 06:52:31 GMT
/bauer-varnish-logs/
2015-03-04 17:52:31,441 - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [GET]>
2015-03-04 17:59:05,166 - botocore.hooks - DEBUG - Event needs-retry.s3.ListObjects: calling handler <botocore.retryhandler.RetryHandler object at 0x7f2cec412588>
2015-03-04 17:59:05,167 - botocore.retryhandler - DEBUG - retry needed, retryable exception caught: HTTPSConnectionPool(host='bauer-varnish-logs.s3.amazonaws.com', port=443): Max retries exceeded with url: /?prefix=Testing/ (Caused by <class 'TimeoutError'>: [Errno 110] Connection timed out)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 557, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1065, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1103, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1061, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 906, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 841, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 111, in connect
    timeout=self.timeout)
  File "/usr/lib/python3.4/socket.py", line 509, in create_connection
    raise err
  File "/usr/lib/python3.4/socket.py", line 500, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 330, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 607, in urlopen
    raise MaxRetryError(self, url, e)
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='bauer-varnish-logs.s3.amazonaws.com', port=443): Max retries exceeded with url: /?prefix=Testing/ (Caused by <class 'TimeoutError'>: [Errno 110] Connection timed out)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/botocore/retryhandler.py", line 270, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/lib/python3/dist-packages/botocore/retryhandler.py", line 318, in __call__
    caught_exception)
  File "/usr/lib/python3/dist-packages/botocore/retryhandler.py", line 227, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/usr/lib/python3/dist-packages/botocore/retryhandler.py", line 360, in _check_caught_exception
    raise caught_exception
  File "/usr/lib/python3/dist-packages/botocore/endpoint.py", line 114, in _get_response
    proxies=self.proxies)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='bauer-varnish-logs.s3.amazonaws.com', port=443): Max retries exceeded with url: /?prefix=Testing/ (Caused by <class 'TimeoutError'>: [Errno 110] Connection timed out)
2015-03-04 17:59:05,170 - botocore.retryhandler - DEBUG - Retry needed, action of: 0.2394720287427028
2015-03-04 17:59:05,170 - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.2394720287427028 seconds

Any help would be much appreciated

**Comment by jamesls** [comment]
Looks like you're on an old version of the CLI.  Can you try upgrading to the latest version of the CLI?  We've made a number of proxy related bug fixes since then.

**Comment by murdz** [comment]
Hi @jamesls, have upgraded to 1.7.2 but still get the same issue:

ubuntu@ec2-b02-i-02c4cacd:~$ sudo aws s3 sync  --region ap-southeast-2  /var/log/varnish/ s3://bauer-varnish-logs/Testing/ --debug
2015-03-05 09:44:48,210 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.7.12 Python/2.7.6 Linux/3.13.0-36-generic, botocore version: 0.93.0
2015-03-05 09:44:48,211 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7fce791f0b90>
2015-03-05 09:44:48,211 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider at 0x7fce794aec08>
2015-03-05 09:44:48,211 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3: calling handler <function add_waiters at 0x7fce7943b9b0>
2015-03-05 09:44:48,212 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.s3.anonymous: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,212 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sync: calling handler <function register_sync_strategies at 0x7fce795489b0>
2015-03-05 09:44:48,212 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sync: calling handler <function add_waiters at 0x7fce7943b9b0>
2015-03-05 09:44:48,212 - MainThread - botocore.hooks - DEBUG - Event building-arg-table.sync: calling handler <bound method SizeOnlySync.add_sync_argument of <awscli.customizations.s3.syncstrategy.sizeonly.SizeOnlySync object at 0x7fce791c2a90>>
2015-03-05 09:44:48,213 - MainThread - botocore.hooks - DEBUG - Event building-arg-table.sync: calling handler <bound method ExactTimestampsSync.add_sync_argument of <awscli.customizations.s3.syncstrategy.exacttimestamps.ExactTimestampsSync object at 0x7fce791c25d0>>
2015-03-05 09:44:48,213 - MainThread - botocore.hooks - DEBUG - Event building-arg-table.sync: calling handler <bound method DeleteSync.add_sync_argument of <awscli.customizations.s3.syncstrategy.delete.DeleteSync object at 0x7fce791c2810>>
2015-03-05 09:44:48,215 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.grants: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,215 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.content-language: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,215 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.page-size: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,215 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.anonymous: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,215 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.exact-timestamps: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,216 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.sync: calling handler <awscli.argprocess.ParamShorthand object at 0x7fce791f7890>
2015-03-05 09:44:48,216 - MainThread - awscli.argprocess - DEBUG - Detected structure: scalar
2015-03-05 09:44:48,216 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.paths: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,216 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.anonymous: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,216 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.source-region: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,216 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.content-encoding: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,217 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.content-disposition: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,217 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.cache-control: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,217 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.dryrun: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,217 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.sync: calling handler <awscli.argprocess.ParamShorthand object at 0x7fce791f7890>
2015-03-05 09:44:48,217 - MainThread - awscli.argprocess - DEBUG - Detected structure: scalar
2015-03-05 09:44:48,217 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.expires: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,217 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.content-type: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,217 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.sse: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,217 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.sync: calling handler <awscli.argprocess.ParamShorthand object at 0x7fce791f7890>
2015-03-05 09:44:48,218 - MainThread - awscli.argprocess - DEBUG - Detected structure: scalar
2015-03-05 09:44:48,218 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.only-show-errors: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,218 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.sync: calling handler <awscli.argprocess.ParamShorthand object at 0x7fce791f7890>
2015-03-05 09:44:48,218 - MainThread - awscli.argprocess - DEBUG - Detected structure: scalar
2015-03-05 09:44:48,226 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.size-only: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,226 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.sync: calling handler <awscli.argprocess.ParamShorthand object at 0x7fce791f7890>
2015-03-05 09:44:48,227 - MainThread - awscli.argprocess - DEBUG - Detected structure: scalar
2015-03-05 09:44:48,227 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.quiet: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,227 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.sync: calling handler <awscli.argprocess.ParamShorthand object at 0x7fce791f7890>
2015-03-05 09:44:48,227 - MainThread - awscli.argprocess - DEBUG - Detected structure: scalar
2015-03-05 09:44:48,227 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.acl: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,227 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.storage-class: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,227 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.website-redirect: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,228 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.follow-symlinks: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,228 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.sync: calling handler <awscli.argprocess.ParamShorthand object at 0x7fce791f7890>
2015-03-05 09:44:48,228 - MainThread - awscli.argprocess - DEBUG - Detected structure: scalar
2015-03-05 09:44:48,228 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.delete: calling handler <function uri_param at 0x7fce795c99b0>
2015-03-05 09:44:48,228 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.sync: calling handler <awscli.argprocess.ParamShorthand object at 0x7fce791f7890>
2015-03-05 09:44:48,228 - MainThread - awscli.argprocess - DEBUG - Detected structure: scalar
2015-03-05 09:44:48,228 - MainThread - botocore.service - DEBUG - Creating service object for: s3
2015-03-05 09:44:48,270 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.s3: calling handler <function register_retries_for_service at 0x7fce799867d0>
2015-03-05 09:44:48,273 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: s3
2015-03-05 09:44:48,273 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.s3: calling handler <function register_retries_for_service at 0x7fce799867d0>
2015-03-05 09:44:48,273 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: s3
2015-03-05 09:44:48,287 - MainThread - botocore.service - DEBUG - Creating service object for: s3
2015-03-05 09:44:48,287 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.s3: calling handler <function register_retries_for_service at 0x7fce799867d0>
2015-03-05 09:44:48,288 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: s3
2015-03-05 09:44:48,288 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.s3: calling handler <function register_retries_for_service at 0x7fce799867d0>
2015-03-05 09:44:48,288 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: s3
2015-03-05 09:44:48,289 - MainThread - awscli.customizations.s3.s3handler - DEBUG - Using a multipart threshold of 8388608 and a part size of 8388608
2015-03-05 09:44:48,289 - MainThread - awscli.customizations.s3.executor - DEBUG - Using max queue size for s3 tasks of: 1000
2015-03-05 09:44:48,289 - MainThread - awscli.customizations.s3.s3handler - DEBUG - Using a multipart threshold of 8388608 and a part size of 8388608
2015-03-05 09:44:48,289 - MainThread - awscli.customizations.s3.executor - DEBUG - Using max queue size for s3 tasks of: 2
2015-03-05 09:44:48,289 - MainThread - botocore.hooks - DEBUG - Event choosing-s3-sync-strategy: calling handler <bound method SizeOnlySync.use_sync_strategy of <awscli.customizations.s3.syncstrategy.sizeonly.SizeOnlySync object at 0x7fce791c2a90>>
2015-03-05 09:44:48,290 - MainThread - botocore.hooks - DEBUG - Event choosing-s3-sync-strategy: calling handler <bound method ExactTimestampsSync.use_sync_strategy of <awscli.customizations.s3.syncstrategy.exacttimestamps.ExactTimestampsSync object at 0x7fce791c25d0>>
2015-03-05 09:44:48,290 - MainThread - botocore.hooks - DEBUG - Event choosing-s3-sync-strategy: calling handler <bound method DeleteSync.use_sync_strategy of <awscli.customizations.s3.syncstrategy.delete.DeleteSync object at 0x7fce791c2810>>
2015-03-05 09:44:48,290 - MainThread - awscli.customizations.s3.executor - DEBUG - Using a threadpool size of: 10
2015-03-05 09:44:48,292 - MainThread - botocore.service - DEBUG - Creating operation objects for: Service(s3)
2015-03-05 09:44:48,306 - MainThread - botocore.operation - DEBUG - Operation:ListObjects called with kwargs: {'prefix': u'Testing/', 'bucket': u'bauer-varnish-logs', 'encoding_type': 'url'}
2015-03-05 09:44:48,307 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.s3: calling handler <function register_retries_for_service at 0x7fce799867d0>
2015-03-05 09:44:48,307 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: s3
2015-03-05 09:44:48,307 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2015-03-05 09:44:48,308 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2015-03-05 09:44:48,308 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2015-03-05 09:44:48,308 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: config-file
2015-03-05 09:44:48,308 - MainThread - botocore.credentials - INFO - Credentials found in config file: ~/.aws/config
2015-03-05 09:44:48,308 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.ListObjects: calling handler <function add_expect_header at 0x7fce799869b0>
2015-03-05 09:44:48,309 - MainThread - botocore.endpoint - DEBUG - Making request for <botocore.model.OperationModel object at 0x7fce78f4ca10> (verify_ssl=True) with params: {'query_string': {u'prefix': u'Testing/', u'encoding-type': 'url'}, 'headers': {}, 'url_path': u'/bauer-varnish-logs', 'body': '', 'method': u'GET'}
2015-03-05 09:44:48,309 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.ListObjects: calling handler <function request_created at 0x7fce79005488>
2015-03-05 09:44:48,309 - MainThread - botocore.hooks - DEBUG - Event before-sign.s3.ListObjects: calling handler <function fix_s3_host at 0x7fce79986668>
2015-03-05 09:44:48,309 - MainThread - botocore.handlers - DEBUG - Checking for DNS compatible bucket for: https://s3-ap-southeast-2.amazonaws.com/bauer-varnish-logs?prefix=Testing%2F&encoding-type=url
2015-03-05 09:44:48,309 - MainThread - botocore.handlers - DEBUG - URI updated to: https://bauer-varnish-logs.s3.amazonaws.com?prefix=Testing%2F&encoding-type=url
2015-03-05 09:44:48,309 - MainThread - botocore.auth - DEBUG - Calculating signature using hmacv1 auth.
2015-03-05 09:44:48,310 - MainThread - botocore.auth - DEBUG - HTTP request method: GET
2015-03-05 09:44:48,310 - MainThread - botocore.auth - DEBUG - StringToSign:
GET


Wed, 04 Mar 2015 22:44:48 GMT
/bauer-varnish-logs/
2015-03-05 09:44:48,315 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [GET]>
2015-03-05 09:44:48,315 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): bauer-varnish-logs.s3.amazonaws.com
2015-03-05 09:45:48,377 - MainThread - botocore.endpoint - DEBUG - Exception received when sending HTTP request.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 184, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/adapters.py", line 419, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPSConnectionPool(host='bauer-varnish-logs.s3.amazonaws.com', port=443): Max retries exceeded with url: /?prefix=Testing%2F&encoding-type=url (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPSConnection object at 0x7fce787051d0>, 'Connection to bauer-varnish-logs.s3.amazonaws.com timed out. (connect timeout=60)'))
2015-03-05 09:45:48,378 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListObjects: calling handler <botocore.retryhandler.RetryHandler object at 0x7fce78fc3490>
2015-03-05 09:45:48,378 - MainThread - botocore.retryhandler - DEBUG - retry needed, retryable exception caught: HTTPSConnectionPool(host='bauer-varnish-logs.s3.amazonaws.com', port=443): Max retries exceeded with url: /?prefix=Testing%2F&encoding-type=url (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPSConnection object at 0x7fce787051d0>, 'Connection to bauer-varnish-logs.s3.amazonaws.com timed out. (connect timeout=60)'))
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 262, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 310, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 219, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 352, in _check_caught_exception
    raise caught_exception
ConnectTimeout: HTTPSConnectionPool(host='bauer-varnish-logs.s3.amazonaws.com', port=443): Max retries exceeded with url: /?prefix=Testing%2F&encoding-type=url (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPSConnection object at 0x7fce787051d0>, 'Connection to bauer-varnish-logs.s3.amazonaws.com timed out. (connect timeout=60)'))
2015-03-05 09:45:48,378 - MainThread - botocore.retryhandler - DEBUG - Retry needed, action of: 0.898461302202
2015-03-05 09:45:48,378 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.898461302202 seconds
2015-03-05 09:45:49,278 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.ListObjects: calling handler <function request_created at 0x7fce79005488>
2015-03-05 09:45:49,278 - MainThread - botocore.hooks - DEBUG - Event before-sign.s3.ListObjects: calling handler <function fix_s3_host at 0x7fce79986668>
2015-03-05 09:45:49,278 - MainThread - botocore.handlers - DEBUG - Checking for DNS compatible bucket for: https://s3-ap-southeast-2.amazonaws.com/bauer-varnish-logs?prefix=Testing%2F&encoding-type=url
2015-03-05 09:45:49,278 - MainThread - botocore.handlers - DEBUG - URI updated to: https://bauer-varnish-logs.s3.amazonaws.com?prefix=Testing%2F&encoding-type=url
2015-03-05 09:45:49,278 - MainThread - botocore.auth - DEBUG - Calculating signature using hmacv1 auth.
2015-03-05 09:45:49,279 - MainThread - botocore.auth - DEBUG - HTTP request method: GET
2015-03-05 09:45:49,279 - MainThread - botocore.auth - DEBUG - StringToSign:
GET


Wed, 04 Mar 2015 22:45:49 GMT
/bauer-varnish-logs/
2015-03-05 09:45:49,279 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [GET]>
2015-03-05 09:45:49,280 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (2): bauer-varnish-logs.s3.amazonaws.com

**Comment by jamesls** [comment]
Ok, thanks for checking.  What kind of proxy are you using?  I'm going to try to spin up a test environment and see if I can repro.

**Comment by murdz** [comment]
Squid

**Comment by murdz** [comment]
Found a solution. It doesn't seem to read the environment variables by default.

Passing "-E" resolved this, i.e:

sudo -E aws s3 sync  --region ap-southeast-2  /var/log/varnish/ s3://bauer-varnish-logs/Testing/ --debug

**Comment by jamesls** [comment]
Ok, that makes sense.  Sudo may not preserve env vars without the -E, and the AWS CLI needs to see the HTTP(S)_PROXY env var in order to support proxies.  Glad you were able to figure out a solution.
