### ISSUE TITLE
IAM roles: 'NoneType' object has no attribute 'access_key'

### ISSUE THREAD

**Issue by jdub** [aws/aws-cli#12]
I have created an IAM role (using the VPC Full Access template, unedited, which includes `ec2:DescribeInstances`), launched an Ubuntu 12.04 LTS t1.micro with it attached, and installed aws-cli with easy_install...

```
ubuntu@ip-10-128-3-5:~$ curl http://169.254.169.254/latest/meta-data/iam/info && echo
{
  "Code" : "Success",
  "LastUpdated" : "2012-12-26T23:44:36Z",
  "InstanceProfileArn" : "arn:aws:iam::*REMOVED*:instance-profile/vpc-nat",
  "InstanceProfileId" : "*REMOVED*"
}
ubuntu@ip-10-128-3-5:~$ curl http://169.254.169.254/latest/meta-data/iam/security-credentials/vpc-nat && echo
{
  "Code" : "Success",
  "LastUpdated" : "2012-12-26T23:44:38Z",
  "Type" : "AWS-HMAC",
  "AccessKeyId" : "*REMOVED*",
  "SecretAccessKey" : "*REMOVED*",
  "Token" : "*REMOVED*",
  "Expiration" : "2012-12-27T06:07:57Z"
}
ubuntu@ip-10-128-3-5:~$ aws ec2 --region ap-southeast-2 describe-instances
'NoneType' object has no attribute 'access_key'
```

Per strace, two of the final things it tries to do is:

```
open("/etc/boto.cfg", O_RDONLY)         = -1 ENOENT (No such file or directory)
open("/home/ubuntu/.boto", O_RDONLY)    = -1 ENOENT (No such file or directory)
```

And the debug log:

```
ubuntu@ip-10-128-3-5:~$ aws --debug ec2 --region ap-southeast-2 describe-instances
2012-12-27 00:21:06,965 - botocore.base - DEBUG - Attempting to Load: aws/_services/ec2
2012-12-27 00:21:06,965 - botocore.base - DEBUG - Attempting to Load: aws
2012-12-27 00:21:06,965 - botocore.base - DEBUG - Attempting to Load: aws/_services
2012-12-27 00:21:06,966 - botocore.base - DEBUG - Found data file: /usr/local/lib/python2.7/dist-packages/botocore-0.4.1-py2.7.egg/botocore/data/aws/_services.json
2012-12-27 00:21:06,966 - botocore.base - DEBUG - Attempting to Load: aws/_services/ec2
2012-12-27 00:21:06,966 - botocore.base - DEBUG - Attempting to Load: aws/ec2
2012-12-27 00:21:06,996 - botocore.base - DEBUG - Found data file: /usr/local/lib/python2.7/dist-packages/botocore-0.4.1-py2.7.egg/botocore/data/aws/ec2.json
2012-12-27 00:21:07,064 - botocore.endpoint - DEBUG - {}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awscli-0.4.4-py2.7.egg/awscli/clidriver.py", line 296, in call
    **params)
  File "/usr/local/lib/python2.7/dist-packages/botocore-0.4.1-py2.7.egg/botocore/operation.py", line 42, in call
    return endpoint.make_request(self, params)
  File "/usr/local/lib/python2.7/dist-packages/botocore-0.4.1-py2.7.egg/botocore/endpoint.py", line 78, in make_request
    headers={'User-Agent': user_agent})
  File "/usr/local/lib/python2.7/dist-packages/requests-0.14.2-py2.7.egg/requests/api.py", line 98, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-0.14.2-py2.7.egg/requests/safe_mode.py", line 39, in wrapped
    return function(method, url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-0.14.2-py2.7.egg/requests/api.py", line 51, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-0.14.2-py2.7.egg/requests/sessions.py", line 228, in request
    args = dispatch_hook('args', args['hooks'], args)
  File "/usr/local/lib/python2.7/dist-packages/requests-0.14.2-py2.7.egg/requests/hooks.py", line 44, in dispatch_hook
    _hook_data = hook(hook_data)
  File "/usr/local/lib/python2.7/dist-packages/botocore-0.4.1-py2.7.egg/botocore/auth.py", line 77, in add_auth
    args['params']['AWSAccessKeyId'] = self.credentials.access_key
AttributeError: 'NoneType' object has no attribute 'access_key'
```

Note that if I supply AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables, it works as expected.

**Comment by davidfarinha** [comment]
Mentioned [here](https://stackoverflow.com/a/63051849/9387466), this can be caused by incorrect characters in your `~/.aws/credentials` file.

**Comment by KptnKMan** [comment]
As commented earlier, this is fixed by setting correct values for:
AWS_SHARED_CREDENTIALS_FILE=~/.aws/credentials
AWS_CONFIG_FILE=~/.aws/config

If you're using Windows, and getting this error with Git for Windows:
AWS_SHARED_CREDENTIALS_FILE=$HOME\.aws\credentials
AWS_CONFIG_FILE=$HOME\.aws\config
