### ISSUE TITLE
Wrong exit status when s3 cp download is cancelled by read timeout

### ISSUE THREAD

**Issue by bluekeyes** [aws/aws-cli#1217]
Version: `aws-cli/1.7.12 Python/2.6.6 Linux/2.6.32-504.8.1.el6.x86_64`

When downloading multiple files in parallel (by running multiple `aws s3 cp` commands in subshells), some operations may encounter a read timeout. When this happens, the download is cancelled but the CLI does not display any errors and still exits with status 0.

I was able to reproduce this on an EC2 instance by copying 3 files from S3 (2GB, 566MB, and 73MB) in parallel until one of them failed (the CLI exited but the file did not exist). Usually, the 2GB file was the one that failed, but I've seen failures with the smaller files as well.

From the debug log:

```
2015-03-10 20:29:33,721 - Thread-7 - awscli.customizations.s3.tasks - DEBUG - Exception caught downloading byte range: HTTPSConnectionPool(host='<bucket>.s3.amazonaws.com', port=443): Read timed out.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/awscli/customizations/s3/tasks.py", line 347, in __call__
    self._download_part()
  File "/usr/lib/python2.6/site-packages/awscli/customizations/s3/tasks.py", line 376, in _download_part
    self._queue_writes(body)
  File "/usr/lib/python2.6/site-packages/awscli/customizations/s3/tasks.py", line 407, in _queue_writes
    self._queue_writes_in_chunks(body, iterate_chunk_size)
  File "/usr/lib/python2.6/site-packages/awscli/customizations/s3/tasks.py", line 438, in _queue_writes_in_chunks
    current = body.read(iterate_chunk_size)
  File "/usr/lib/python2.6/site-packages/botocore/response.py", line 70, in read
    chunk = self._raw_stream.read(amt)
  File "/usr/lib/python2.6/site-packages/botocore/vendored/requests/packages/urllib3/response.py", line 210, in read
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: HTTPSConnectionPool(host='<bucket>.s3.amazonaws.com', port=443): Read timed out.
2015-03-10 20:29:33,735 - Thread-7 - awscli.customizations.s3.executor - DEBUG - Error calling task: HTTPSConnectionPool(host='<bucket>.s3.amazonaws.com', port=443): Read timed out.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/awscli/customizations/s3/executor.py", line 211, in run
    function()
  File "/usr/lib/python2.6/site-packages/awscli/customizations/s3/tasks.py", line 353, in __call__
    raise e
ReadTimeoutError: HTTPSConnectionPool(host='<bucket>.s3.amazonaws.com', port=443): Read timed out.
2015-03-10 20:29:33,735 - Thread-7 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2015-03-10 20:29:34,556 - Thread-12 - awscli.customizations.s3.executor - DEBUG - Error calling task: Download has been cancelled.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/awscli/customizations/s3/executor.py", line 211, in run
    function()
  File "/usr/lib/python2.6/site-packages/awscli/customizations/s3/tasks.py", line 310, in __call__
    self._context.wait_for_completion()
  File "/usr/lib/python2.6/site-packages/awscli/customizations/s3/tasks.py", line 733, in wait_for_completion
    "Download has been cancelled.")
DownloadCancelledError: Download has been cancelled.
2015-03-10 20:29:34,557 - Thread-12 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2015-03-10 20:29:39,422 - Thread-6 - awscli.customizations.s3.tasks - DEBUG - Exception caught downloading byte range: HTTPSConnectionPool(host='<bucket>.s3.amazonaws.com', port=443): Read timed out.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/awscli/customizations/s3/tasks.py", line 347, in __call__
    self._download_part()
  File "/usr/lib/python2.6/site-packages/awscli/customizations/s3/tasks.py", line 376, in _download_part
    self._queue_writes(body)
  File "/usr/lib/python2.6/site-packages/awscli/customizations/s3/tasks.py", line 407, in _queue_writes
    self._queue_writes_in_chunks(body, iterate_chunk_size)
  File "/usr/lib/python2.6/site-packages/awscli/customizations/s3/tasks.py", line 438, in _queue_writes_in_chunks
    current = body.read(iterate_chunk_size)
  File "/usr/lib/python2.6/site-packages/botocore/response.py", line 70, in read
    chunk = self._raw_stream.read(amt)
  File "/usr/lib/python2.6/site-packages/botocore/vendored/requests/packages/urllib3/response.py", line 210, in read
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: HTTPSConnectionPool(host='<bucket>.s3.amazonaws.com', port=443): Read timed out.
2015-03-10 20:29:39,423 - Thread-6 - awscli.customizations.s3.executor - DEBUG - Error calling task: HTTPSConnectionPool(host='<bucket>.s3.amazonaws.com', port=443): Read timed out.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/awscli/customizations/s3/executor.py", line 211, in run
    function()
  File "/usr/lib/python2.6/site-packages/awscli/customizations/s3/tasks.py", line 353, in __call__
    raise e
ReadTimeoutError: HTTPSConnectionPool(host='<bucket>.s3.amazonaws.com', port=443): Read timed out.
2015-03-10 20:29:39,423 - Thread-6 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2015-03-10 20:29:39,424 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-6, stopped daemon 140334164080384)>
2015-03-10 20:29:39,424 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-7, stopped daemon 140334264735488)>
2015-03-10 20:29:39,424 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-7, stopped daemon 140334264735488)>
2015-03-10 20:29:39,424 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-8, stopped daemon 140334147299072)>
2015-03-10 20:29:39,424 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-8, stopped daemon 140334147299072)>
2015-03-10 20:29:39,424 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-9, stopped daemon 140334130517760)>
2015-03-10 20:29:39,424 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-9, stopped daemon 140334130517760)>
2015-03-10 20:29:39,424 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-10, stopped daemon 140333828536064)>
2015-03-10 20:29:39,425 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-10, stopped daemon 140333828536064)>
2015-03-10 20:29:39,425 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-11, stopped daemon 140333811754752)>
2015-03-10 20:29:39,425 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-11, stopped daemon 140333811754752)>
2015-03-10 20:29:39,425 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-12, stopped daemon 140333794973440)>
2015-03-10 20:29:39,425 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-12, stopped daemon 140333794973440)>
2015-03-10 20:29:39,425 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-13, stopped daemon 140333627209472)>
2015-03-10 20:29:39,425 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-13, stopped daemon 140333627209472)>
2015-03-10 20:29:39,425 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-14, stopped daemon 140333610428160)>
2015-03-10 20:29:39,425 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-14, stopped daemon 140333610428160)>
2015-03-10 20:29:39,425 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for result thread.
2015-03-10 20:29:39,425 - Thread-1 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in print thread, shutting down print thread.
2015-03-10 20:29:39,425 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for IO thread.
2015-03-10 20:29:39,426 - Thread-2 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in IO thread, shutting down.
2015-03-10 20:29:39,426 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for result thread to shutdown.
2015-03-10 20:29:39,438 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for IO thread to shutdown.
```

I can provide more output if needed.

I saw that 1.7.13 retries operations on read timeout, so we'll be updating to that version soon. I'm mostly concerned about the successful exit status, because this prevented our error-handling logic from detecting that something was wrong until later in the process.

**Comment by jamesls** [comment]
This has been fixed via https://github.com/aws/aws-cli/pull/1897
