### ISSUE TITLE
`aws route53 change-resource-record-sets` returns `data must be a byte string`

### ISSUE THREAD

**Issue by RichardBronosky** [aws/aws-cli#1240]
Using version `aws-cli/1.7.16 Python/2.6.9 Linux/3.14.33-26.47.amzn1.x86_64` on EC2 this works, but on my local Mac OS 10.10.2 using version `aws-cli/1.7.16 Python/2.7.9 Darwin/14.1.0` it does not.

This command sequence...

```
cat>/tmp/ono<<EOF
{
        "Changes": [
            {
                "Action": "UPSERT",
                "ResourceRecordSet": {
                    "Name": "redis.local.",
                    "Type": "A",
                    "TTL": 20,
                    "ResourceRecords": [
                        {
                            "Value": "10.0.0.147"
                        }
                    ]
                }
            }
        ]
}
EOF

aws route53 change-resource-record-sets --change-batch file:///tmp/ono --hosted-zone-id Z17RPV5S42OLNB --debug
```

...gives this response.

```
2015-03-25 01:08:19,262 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.7.16 Python/2.7.9 Darwin/14.1.0, botocore version: 0.97.0
2015-03-25 01:08:19,262 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['route53', 'change-resource-record-sets', '--change-batch', 'file:///tmp/ono', '--hosted-zone-id', 'Z17RPV5S42OLNB', '--debug']
2015-03-25 01:08:19,262 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x10d76f230>
2015-03-25 01:08:19,262 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider at 0x10d72ede8>
2015-03-25 01:08:19,280 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.route53: calling handler <function register_retries_for_service at 0x10d0756e0>
2015-03-25 01:08:19,282 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: route53
2015-03-25 01:08:19,284 - MainThread - botocore.hooks - DEBUG - Event building-command-table.route53: calling handler <function add_waiters at 0x10d73ab90>
2015-03-25 01:08:19,285 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'hosted-zone-id', <awscli.arguments.CLIArgument object at 0x10d945e10>), (u'change-batch', <awscli.arguments.CLIArgument object at 0x10d945e50>)])
2015-03-25 01:08:19,285 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.route53.change-resource-record-sets: calling handler <function add_streaming_output_arg at 0x10d2f4b90>
2015-03-25 01:08:19,285 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.route53.change-resource-record-sets: calling handler <function add_cli_input_json at 0x10d72e0c8>
2015-03-25 01:08:19,285 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.route53.change-resource-record-sets: calling handler <function unify_paging_params at 0x10d30faa0>
2015-03-25 01:08:19,286 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.route53.change-resource-record-sets: calling handler <function add_generate_skeleton at 0x10d72e5f0>
2015-03-25 01:08:19,286 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.route53.change-resource-record-sets: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x10d945e90>>
2015-03-25 01:08:19,286 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.route53.change-resource-record-sets: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x10d945ed0>>
2015-03-25 01:08:19,288 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.route53.change-resource-record-sets.hosted-zone-id: calling handler <function uri_param at 0x10d2da488>
2015-03-25 01:08:19,288 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.route53.change-resource-record-sets: calling handler <awscli.argprocess.ParamShorthand object at 0x10d76df90>
2015-03-25 01:08:19,289 - MainThread - awscli.argprocess - DEBUG - Detected structure: scalar
2015-03-25 01:08:19,289 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'Z17RPV5S42OLNB' for parameter "hosted_zone_id": u'Z17RPV5S42OLNB'
2015-03-25 01:08:19,289 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.route53.change-resource-record-sets.change-batch: calling handler <function uri_param at 0x10d2da488>
2015-03-25 01:08:19,289 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.route53.change-resource-record-sets: calling handler <awscli.argprocess.ParamShorthand object at 0x10d76df90>
2015-03-25 01:08:19,289 - MainThread - awscli.argprocess - DEBUG - Param change_batch looks like JSON, not considered for param shorthand.
2015-03-25 01:08:19,289 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'{\n        "Changes": [\n            {\n                "Action": "UPSERT",\n                "ResourceRecordSet": {\n                    "Name": "redis.local.",\n                    "Type": "A",\n                    "TTL": 20,\n                    "ResourceRecords": [\n                        {\n                            "Value": "10.0.0.147"\n                        }\n                    ]\n                }\n            }\n        ]\n}\n' for parameter "change_batch": OrderedDict([(u'Changes', [OrderedDict([(u'Action', u'UPSERT'), (u'ResourceRecordSet', OrderedDict([(u'Name', u'redis.local.'), (u'Type', u'A'), (u'TTL', 20), (u'ResourceRecords', [OrderedDict([(u'Value', u'10.0.0.147')])])]))])])])
2015-03-25 01:08:19,289 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.route53.change-resource-record-sets.cli-input-json: calling handler <function uri_param at 0x10d2da488>
2015-03-25 01:08:19,290 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.route53.change-resource-record-sets.generate-cli-skeleton: calling handler <function uri_param at 0x10d2da488>
2015-03-25 01:08:19,290 - MainThread - botocore.hooks - DEBUG - Event calling-command.route53.change-resource-record-sets: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x10d945ed0>>
2015-03-25 01:08:19,290 - MainThread - botocore.hooks - DEBUG - Event calling-command.route53.change-resource-record-sets: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x10d945e90>>
2015-03-25 01:08:19,290 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2015-03-25 01:08:19,290 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2015-03-25 01:08:19,290 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2015-03-25 01:08:19,290 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2015-03-25 01:08:19,309 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: route53
2015-03-25 01:08:19,309 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: route53
2015-03-25 01:08:19,339 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.route53.ChangeResourceRecordSets: calling handler <function fix_route53_ids at 0x10d075c08>
2015-03-25 01:08:19,339 - MainThread - botocore.handlers - DEBUG - HostedZoneId Z17RPV5S42OLNB -> Z17RPV5S42OLNB
2015-03-25 01:08:19,341 - MainThread - botocore.endpoint - DEBUG - Making request for <botocore.model.OperationModel object at 0x10dac0990> (verify_ssl=True) with params: {'query_string': {}, 'headers': {}, 'url_path': u'/2013-04-01/hostedzone/Z17RPV5S42OLNB/rrset/', 'body': u'<ChangeResourceRecordSetsRequest xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><ChangeBatch><Changes><Change><Action>UPSERT</Action><ResourceRecordSet><Name>redis.local.</Name><Type>A</Type><TTL>20</TTL><ResourceRecords><ResourceRecord><Value>10.0.0.147</Value></ResourceRecord></ResourceRecords></ResourceRecordSet></Change></Changes></ChangeBatch></ChangeResourceRecordSetsRequest>', 'method': u'POST'}
2015-03-25 01:08:19,341 - MainThread - botocore.hooks - DEBUG - Event request-created.route53.ChangeResourceRecordSets: calling handler <bound method route53._sign_request of <botocore.client.route53 object at 0x10dac0350>>
2015-03-25 01:08:19,343 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2015-03-25 01:08:19,344 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): route53.amazonaws.com
2015-03-25 01:08:19,506 - MainThread - botocore.endpoint - DEBUG - Exception received when sending HTTP request.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 231, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/usr/local/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 518, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 330, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python2.7/site-packages/botocore/awsrequest.py", line 120, in _send_request
    self, method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python2.7/site-packages/botocore/awsrequest.py", line 172, in _send_output
    self.send(message_body)
  File "/usr/local/lib/python2.7/site-packages/botocore/awsrequest.py", line 232, in send
    return HTTPConnection.send(self, str)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 826, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python2.7/site-packages/botocore/vendored/requests/packages/urllib3/contrib/pyopenssl.py", line 220, in sendall
    sent = self._send_until_done(data)
  File "/usr/local/lib/python2.7/site-packages/botocore/vendored/requests/packages/urllib3/contrib/pyopenssl.py", line 210, in _send_until_done
    return self.connection.send(data)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 947, in send
    raise TypeError("data must be a byte string")
TypeError: data must be a byte string
2015-03-25 01:08:19,509 - MainThread - botocore.hooks - DEBUG - Event needs-retry.route53.ChangeResourceRecordSets: calling handler <botocore.retryhandler.RetryHandler object at 0x10d93f190>
2015-03-25 01:08:19,510 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 183, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 367, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 534, in __call__
    call_parameters, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 657, in invoke
    **parameters)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 187, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 231, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 173, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 203, in _send_request
    success_response, exception):
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 267, in _needs_retry
    caught_exception=caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 250, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 265, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
TypeError: data must be a byte string
2015-03-25 01:08:19,511 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

data must be a byte string
```

**Comment by RichardBronosky** [comment]
I get the same thing with:

    aws route53 change-resource-record-sets --hosted-zone-id Z17RPV5S42OLNB --debug --change-batch '
    {
            "Changes": [
                {
                    "Action": "UPSERT",
                    "ResourceRecordSet": {
                        "Name": "redis.local.",
                        "Type": "A",
                        "TTL": 20,
                        "ResourceRecords": [
                            {
                                "Value": "10.0.0.147"
                            }
                        ]
                    }
                }
            ]
    }
    '

**Comment by jamesls** [comment]
Appears the same as the what botocore users are seeing: https://github.com/boto/botocore/issues/494

To recap, this only occurs if you also have pyopenssl+ndg-httpclient+pyasn1 installed.  These are dependencies that are *not* pulled in by the AWS CLI, but are optionally supported by our underlying http library.  Unless you need to have pyopenssl installed for some reason, the workaround is to uninstall pyopenssl.

**Comment by joshunger** [comment]
This is also failing for me inside a docker without pyopenssl installed (from what I can tell).  What other information can I provide?

**Comment by sethwoodworth** [comment]
Updating pyOpenSSL to 0.15.1 fixed this issue for me (or a closely related one) on Debian Jessie

**Comment by wildinstinct** [comment]
facing same error as mentioned above

Here is my change resource record set batch file

`{
    "Changes": [
        {
            "Action": "CREATE",
            "ResourceRecordSet": {
                "AliasTarget": {
                    "DNSName": "dualstack.internal-react-flfmt-ofrs-elb-dev-blue-617313876.us-east-1.elb.amazonaws.com.",
                    "EvaluateTargetHealth": true,
                    "HostedZoneId": "Z3DZXE0Q79N41H"
                },
                "Failover": "PRIMARY",
                "Name": "reactive-pricing-offers.aws-card-dqa.capitalonegslbex.com.",
                "SetIdentifier": "reactive-pricing-offers-PRIMARY",
                "Type": "A"
            }
        },
        {
            "Action": "UPSERT",
            "ResourceRecordSet": [
                {
                    "AliasTarget": {
                        "DNSName": "dualstack.internal-react-flfmt-ofrs-elb-dev-green-1367806044.us-east-1.elb.amazonaws.com.",
                        "EvaluateTargetHealth": true,
                        "HostedZoneId": "Z3DZXE0Q79N41H"
                    },
                    "Failover": "SECONDARY",
                    "Name": "reactive-pricing-offers.aws-card-dqa.capitalonegslbex.com.",
                    "SetIdentifier": "reactive-pricing-offers-SECONDARY",
                    "Type": "A"
                }
            ]
        }
    ]
}`

`Parameter validation failed:
Invalid type for parameter ChangeBatch.Changes[1].ResourceRecordSet, value: [OrderedDict([(u'Type', u'A'), (u'Failover', u'SECONDARY'), (u'AliasTarget', OrderedDict([(u'HostedZoneId', u'Z3DZXE0Q79N41H'), (u'EvaluateTargetHealth', True), (u'DNSName', u'dualstack.internal-react-flfmt-ofrs-elb-dev-green-1367806044.us-east-1.elb.amazonaws.com.')])), (u'SetIdentifier', u'reactive-pricing-offers-SECONDARY'), (u'Name', u'reactive-pricing-offers.aws-card-dqa.capitalonegslbex.com.')])], type: <type 'list'>, valid types: <type 'dict'>
2016-07-24 22:10:26,715 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Parameter validation failed:
Invalid type for parameter ChangeBatch.Changes[1].ResourceRecordSet, value: [OrderedDict([(u'Type', u'A'), (u'Failover', u'SECONDARY'), (u'AliasTarget', OrderedDict([(u'HostedZoneId', u'Z3DZXE0Q79N41H'), (u'EvaluateTargetHealth', True), (u'DNSName', u'dualstack.internal-react-flfmt-ofrs-elb-dev-green-1367806044.us-east-1.elb.amazonaws.com.')])), (u'SetIdentifier', u'reactive-pricing-offers-SECONDARY'), (u'Name', u'reactive-pricing-offers.aws-card-dqa.capitalonegslbex.com.')])], type: <type 'list'>, valid types: <type 'dict'>`

**Comment by JordonPhillips** [comment]
We introduced a change a while back that disables our usage of pyopenssl, so this should no longer be an issue. Feel free to open a new issue if this behavior re-appears on the latest versions.

**Comment by svenkata** [comment]
aws route53 change-resource-record-sets --hosted-zone-id Z1P4WFA69I45C3 --change-batch file:///home/ec2-user/kafka_route53-1.json

{
    "Comment": "string",
    "Changes": [
        {
            "Action": "CREATE",
            "ResourceRecordSet":{
                "ResourceRecords": [
                    {
                        "Value": "MY_IP"
                    }
                ],
                "Type": "A",
                "Name": "kafka-training-1.us-east-1.n8-nonprod.aws.test",
                "TTL": 300
            }
        }
    ]
}

It was working fine until yesterday and today we are seeing...
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
