### ISSUE TITLE
aws s3 ls - can't ls bucket

### ISSUE THREAD

**Issue by pawelkilian** [aws/aws-cli#1256]
[jaffer@data-aw-prod ~]$ aws --version
aws-cli/1.7.18 Python/2.6.9 Linux/3.14.35-28.38.amzn1.x86_64
[jaffer@data-aw-prod ~]$

[jaffer@data-aw-prod ~]$ aws s3 ls --debug
2015-04-01 11:56:42,132 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.7.18 Python/2.6.9 Linux/3.14.35-28.38.amzn1.x86_64, botocore version: 0.99.0
2015-04-01 11:56:42,132 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3', 'ls', '--debug']
2015-04-01 11:56:42,132 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x14d69b0>
2015-04-01 11:56:42,132 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider at 0x14a9140>
2015-04-01 11:56:42,133 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3: calling handler <function add_waiters at 0x14afe60>
2015-04-01 11:56:42,134 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.s3.anonymous: calling handler <function uri_param at 0x12af848>
2015-04-01 11:56:42,134 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ls: calling handler <function add_waiters at 0x14afe60>
2015-04-01 11:56:42,135 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.paths: calling handler <function uri_param at 0x12af848>
2015-04-01 11:56:42,135 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.summarize: calling handler <function uri_param at 0x12af848>
2015-04-01 11:56:42,135 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.ls: calling handler <awscli.argprocess.ParamShorthand object at 0x15141d0>
2015-04-01 11:56:42,135 - MainThread - awscli.argprocess - DEBUG - Detected structure: scalar
2015-04-01 11:56:42,135 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.anonymous: calling handler <function uri_param at 0x12af848>
2015-04-01 11:56:42,135 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.human-readable: calling handler <function uri_param at 0x12af848>
2015-04-01 11:56:42,135 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.ls: calling handler <awscli.argprocess.ParamShorthand object at 0x15141d0>
2015-04-01 11:56:42,136 - MainThread - awscli.argprocess - DEBUG - Detected structure: scalar
2015-04-01 11:56:42,136 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.page-size: calling handler <function uri_param at 0x12af848>
2015-04-01 11:56:42,136 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2015-04-01 11:56:42,136 - MainThread - botocore.credentials - INFO - Found credentials in environment variables.
2015-04-01 11:56:42,215 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2015-04-01 11:56:42,215 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2015-04-01 11:56:42,221 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.ListBuckets: calling handler <function add_expect_header at 0x10155f0>
2015-04-01 11:56:42,221 - MainThread - botocore.endpoint - DEBUG - Making request for <botocore.model.OperationModel object at 0x152a350> (verify_ssl=True) with params: {'query_string': '', 'headers': {}, 'url_path': '/', 'body': '', 'method': u'GET'}
2015-04-01 11:56:42,221 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.ListBuckets: calling handler <bound method s3._sign_request of <botocore.client.s3 object at 0x17ee910>>
2015-04-01 11:56:42,221 - MainThread - botocore.hooks - DEBUG - Event before-sign.s3.ListBuckets: calling handler <function fix_s3_host at 0x10152a8>
2015-04-01 11:56:42,222 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2015-04-01 11:56:42,222 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
GET
/

host:s3.us-east.amazonaws.com
user-agent:aws-cli/1.7.18 Python/2.6.9 Linux/3.14.35-28.38.amzn1.x86_64
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20150401T155642Z

host;user-agent;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2015-04-01 11:56:42,222 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20150401T155642Z
20150401/us-east/s3/aws4_request
e0002ea5e32486a5cd7a2014cf22368b82951adb37d010bd31ffd4ec5a5c3b5b
2015-04-01 11:56:42,222 - MainThread - botocore.auth - DEBUG - Signature:
183a8b6e48fe85f9713139c4763e1af3ba68c8b5aa38fdb03d0fe38d65e8ee2c
2015-04-01 11:56:42,228 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [GET]>
2015-04-01 11:56:42,229 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): s3.us-east.amazonaws.com
2015-04-01 11:56:42,231 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListBuckets: calling handler <botocore.retryhandler.RetryHandler object at 0x1711b90>
2015-04-01 11:56:42,231 - MainThread - botocore.retryhandler - DEBUG - retry needed, retryable exception caught: Could not connect to the endpoint URL: "https://s3.us-east.amazonaws.com/"
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 265, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
EndpointConnectionError: Could not connect to the endpoint URL: "https://s3.us-east.amazonaws.com/"
2015-04-01 11:56:42,232 - MainThread - botocore.retryhandler - DEBUG - Retry needed, action of: 0.322988676199
2015-04-01 11:56:42,232 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.322988676199 seconds
2015-04-01 11:56:42,555 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.ListBuckets: calling handler <bound method s3._sign_request of <botocore.client.s3 object at 0x17ee910>>
2015-04-01 11:56:42,556 - MainThread - botocore.hooks - DEBUG - Event before-sign.s3.ListBuckets: calling handler <function fix_s3_host at 0x10152a8>
2015-04-01 11:56:42,556 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2015-04-01 11:56:42,556 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
GET
/

host:s3.us-east.amazonaws.com
user-agent:aws-cli/1.7.18 Python/2.6.9 Linux/3.14.35-28.38.amzn1.x86_64
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20150401T155642Z

host;user-agent;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2015-04-01 11:56:42,557 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20150401T155642Z
20150401/us-east/s3/aws4_request
e0002ea5e32486a5cd7a2014cf22368b82951adb37d010bd31ffd4ec5a5c3b5b
2015-04-01 11:56:42,557 - MainThread - botocore.auth - DEBUG - Signature:
183a8b6e48fe85f9713139c4763e1af3ba68c8b5aa38fdb03d0fe38d65e8ee2c
2015-04-01 11:56:42,557 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [GET]>
2015-04-01 11:56:42,558 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (2): s3.us-east.amazonaws.com
2015-04-01 11:56:42,559 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListBuckets: calling handler <botocore.retryhandler.RetryHandler object at 0x1711b90>
2015-04-01 11:56:42,559 - MainThread - botocore.retryhandler - DEBUG - retry needed, retryable exception caught: Could not connect to the endpoint URL: "https://s3.us-east.amazonaws.com/"
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 265, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
EndpointConnectionError: Could not connect to the endpoint URL: "https://s3.us-east.amazonaws.com/"
2015-04-01 11:56:42,559 - MainThread - botocore.retryhandler - DEBUG - Retry needed, action of: 0.75575215895
2015-04-01 11:56:42,559 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.75575215895 seconds
2015-04-01 11:56:43,316 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.ListBuckets: calling handler <bound method s3._sign_request of <botocore.client.s3 object at 0x17ee910>>
2015-04-01 11:56:43,317 - MainThread - botocore.hooks - DEBUG - Event before-sign.s3.ListBuckets: calling handler <function fix_s3_host at 0x10152a8>
2015-04-01 11:56:43,317 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2015-04-01 11:56:43,317 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
GET
/

host:s3.us-east.amazonaws.com
user-agent:aws-cli/1.7.18 Python/2.6.9 Linux/3.14.35-28.38.amzn1.x86_64
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20150401T155643Z

host;user-agent;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2015-04-01 11:56:43,317 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20150401T155643Z
20150401/us-east/s3/aws4_request
2b218ca18cc6f59827d9cc6ccc4c222ed77e7b2b9e1fd6aa4242e406e7e404ec
2015-04-01 11:56:43,318 - MainThread - botocore.auth - DEBUG - Signature:
1e99b5f508a30bfa547607d915aec56f9667e6c6db66dc65643202822314c377
2015-04-01 11:56:43,318 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [GET]>
2015-04-01 11:56:43,319 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (3): s3.us-east.amazonaws.com
2015-04-01 11:56:43,320 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListBuckets: calling handler <botocore.retryhandler.RetryHandler object at 0x1711b90>
2015-04-01 11:56:43,320 - MainThread - botocore.retryhandler - DEBUG - retry needed, retryable exception caught: Could not connect to the endpoint URL: "https://s3.us-east.amazonaws.com/"
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 265, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
EndpointConnectionError: Could not connect to the endpoint URL: "https://s3.us-east.amazonaws.com/"
2015-04-01 11:56:43,320 - MainThread - botocore.retryhandler - DEBUG - Retry needed, action of: 2.18930448654
2015-04-01 11:56:43,320 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 2.18930448654 seconds
2015-04-01 11:56:45,512 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.ListBuckets: calling handler <bound method s3._sign_request of <botocore.client.s3 object at 0x17ee910>>
2015-04-01 11:56:45,512 - MainThread - botocore.hooks - DEBUG - Event before-sign.s3.ListBuckets: calling handler <function fix_s3_host at 0x10152a8>
2015-04-01 11:56:45,513 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2015-04-01 11:56:45,513 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
GET
/

host:s3.us-east.amazonaws.com
user-agent:aws-cli/1.7.18 Python/2.6.9 Linux/3.14.35-28.38.amzn1.x86_64
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20150401T155645Z

host;user-agent;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2015-04-01 11:56:45,513 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20150401T155645Z
20150401/us-east/s3/aws4_request
48ccbdbf0fd162f787956abaeec2bcc73a92b5cd03e23bbfcf20f9721cd629cf
2015-04-01 11:56:45,513 - MainThread - botocore.auth - DEBUG - Signature:
715db569aa580b92850617e41db4d78d4a8eb5ccc51018bf3500272d98bb1502
2015-04-01 11:56:45,513 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [GET]>
2015-04-01 11:56:45,514 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (4): s3.us-east.amazonaws.com
2015-04-01 11:56:45,515 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListBuckets: calling handler <botocore.retryhandler.RetryHandler object at 0x1711b90>
2015-04-01 11:56:45,515 - MainThread - botocore.retryhandler - DEBUG - retry needed, retryable exception caught: Could not connect to the endpoint URL: "https://s3.us-east.amazonaws.com/"
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 265, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
EndpointConnectionError: Could not connect to the endpoint URL: "https://s3.us-east.amazonaws.com/"
2015-04-01 11:56:45,515 - MainThread - botocore.retryhandler - DEBUG - Retry needed, action of: 0.576300993129
2015-04-01 11:56:45,515 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.576300993129 seconds
2015-04-01 11:56:46,092 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.ListBuckets: calling handler <bound method s3._sign_request of <botocore.client.s3 object at 0x17ee910>>
2015-04-01 11:56:46,092 - MainThread - botocore.hooks - DEBUG - Event before-sign.s3.ListBuckets: calling handler <function fix_s3_host at 0x10152a8>
2015-04-01 11:56:46,093 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2015-04-01 11:56:46,093 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
GET
/

host:s3.us-east.amazonaws.com
user-agent:aws-cli/1.7.18 Python/2.6.9 Linux/3.14.35-28.38.amzn1.x86_64
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20150401T155646Z

host;user-agent;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2015-04-01 11:56:46,093 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20150401T155646Z
20150401/us-east/s3/aws4_request
18c5d85e0996b1ed77b2e06c0cc78b476cdb1a25d05a13f665c82a9066d61ef4
2015-04-01 11:56:46,093 - MainThread - botocore.auth - DEBUG - Signature:
d6c4ab22c43a2765e219ebe83cdebbbdae61c6b300445fec73f67ff0bc526507
2015-04-01 11:56:46,094 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [GET]>
2015-04-01 11:56:46,094 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (5): s3.us-east.amazonaws.com
2015-04-01 11:56:46,095 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListBuckets: calling handler <botocore.retryhandler.RetryHandler object at 0x1711b90>
2015-04-01 11:56:46,095 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/site-packages/awscli/clidriver.py", line 183, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.6/site-packages/awscli/customizations/commands.py", line 190, in __call__
    parsed_globals)
  File "/usr/local/lib/python2.6/site-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/usr/local/lib/python2.6/site-packages/awscli/customizations/s3/subcommands.py", line 324, in _run_main
    self._list_all_buckets()
  File "/usr/local/lib/python2.6/site-packages/awscli/customizations/s3/subcommands.py", line 383, in _list_all_buckets
    response_data = self.client.list_buckets()
  File "/usr/local/lib/python2.6/site-packages/botocore/client.py", line 187, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.6/site-packages/botocore/client.py", line 231, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.6/site-packages/botocore/endpoint.py", line 173, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.6/site-packages/botocore/endpoint.py", line 203, in _send_request
    success_response, exception):
  File "/usr/local/lib/python2.6/site-packages/botocore/endpoint.py", line 267, in _needs_retry
    caught_exception=caught_exception)
  File "/usr/local/lib/python2.6/site-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.6/site-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 250, in __call__
    caught_exception)
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 273, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/usr/local/lib/python2.6/site-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
EndpointConnectionError: Could not connect to the endpoint URL: "https://s3.us-east.amazonaws.com/"
2015-04-01 11:56:46,096 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Could not connect to the endpoint URL: "https://s3.us-east.amazonaws.com/"

Any idea what it's using https://s3.us-east.amazonaws.com/ instead of https://us-east-1.s3.amazonaws.com/

**Comment by pawelkilian** [comment]
[jaffer@data-aw-prod ~]$ aws s3 ls --debug --endpoint-url https://us-east-1.s3.amazonaws.com/
2015-04-02 10:00:53,814 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.7.18 Python/2.6.9 Linux/3.14.35-28.38.amzn1.x86_64, botocore version: 0.99.0
2015-04-02 10:00:53,814 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3', 'ls', '--debug', '--endpoint-url', 'https://us-east-1.s3.amazonaws.com/']
2015-04-02 10:00:53,814 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x15e49b0>
2015-04-02 10:00:53,815 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider at 0x15b7140>
2015-04-02 10:00:53,815 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3: calling handler <function add_waiters at 0x15bde60>
2015-04-02 10:00:53,816 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.s3.anonymous: calling handler <function uri_param at 0x13bd848>
2015-04-02 10:00:53,816 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ls: calling handler <function add_waiters at 0x15bde60>
2015-04-02 10:00:53,817 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.paths: calling handler <function uri_param at 0x13bd848>
2015-04-02 10:00:53,817 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.summarize: calling handler <function uri_param at 0x13bd848>
2015-04-02 10:00:53,817 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.ls: calling handler <awscli.argprocess.ParamShorthand object at 0x16221d0>
2015-04-02 10:00:53,817 - MainThread - awscli.argprocess - DEBUG - Detected structure: scalar
2015-04-02 10:00:53,817 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.anonymous: calling handler <function uri_param at 0x13bd848>
2015-04-02 10:00:53,817 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.human-readable: calling handler <function uri_param at 0x13bd848>
2015-04-02 10:00:53,817 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.ls: calling handler <awscli.argprocess.ParamShorthand object at 0x16221d0>
2015-04-02 10:00:53,818 - MainThread - awscli.argprocess - DEBUG - Detected structure: scalar
2015-04-02 10:00:53,818 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.page-size: calling handler <function uri_param at 0x13bd848>
2015-04-02 10:00:53,818 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2015-04-02 10:00:53,818 - MainThread - botocore.credentials - INFO - Found credentials in environment variables.
2015-04-02 10:00:53,896 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2015-04-02 10:00:53,896 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2015-04-02 10:00:53,901 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.ListBuckets: calling handler <function add_expect_header at 0x11235f0>
2015-04-02 10:00:53,901 - MainThread - botocore.endpoint - DEBUG - Making request for <botocore.model.OperationModel object at 0x1638350> (verify_ssl=True) with params: {'query_string': '', 'headers': {}, 'url_path': '/', 'body': '', 'method': u'GET'}
2015-04-02 10:00:53,901 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.ListBuckets: calling handler <bound method s3._sign_request of <botocore.client.s3 object at 0x193c910>>
2015-04-02 10:00:53,902 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2015-04-02 10:00:53,902 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
GET
/

host:us-east-1.s3.amazonaws.com
user-agent:aws-cli/1.7.18 Python/2.6.9 Linux/3.14.35-28.38.amzn1.x86_64
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20150402T140053Z

host;user-agent;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2015-04-02 10:00:53,902 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20150402T140053Z
20150402/us-east/s3/aws4_request
c2f10df0a6273531a1c59de88a43aa15d54e0ff0d4efb446bfc413f423a40b6e
2015-04-02 10:00:53,902 - MainThread - botocore.auth - DEBUG - Signature:
bbea77bb9355119c47ea3fb62edd0e3ffd32dab9733698f8f82ea7bebba32e99
2015-04-02 10:00:53,909 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [GET]>
2015-04-02 10:00:53,909 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): us-east-1.s3.amazonaws.com
2015-04-02 10:00:53,939 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "GET / HTTP/1.1" 400 None
2015-04-02 10:00:53,941 - MainThread - botocore.parsers - DEBUG - Response headers:
{'connection': 'close',
 'content-type': 'application/xml',
 'date': 'Thu, 02 Apr 2015 14:00:53 GMT',
 'server': 'AmazonS3',
 'transfer-encoding': 'chunked',
 'x-amz-id-2': '4YKK6iKMv28//rCRHQDedKvJsyuEXgvY=',
 'x-amz-request-id': ''}
2015-04-02 10:00:53,941 - MainThread - botocore.parsers - DEBUG - Response body:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east' is wrong; expecting 'us-east-1'</Message><Region>us-east-1</Region><RequestId>CCAA61953FE3FAD0</RequestId><HostId>4YKK6iKMv28/bEd3R50qcUidwIza8ckHiPcuVvrX2cZLWDPfx7nvqsz/rCRHQDedKvJsyuEXgvY=</HostId></Error>
2015-04-02 10:00:53,942 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListBuckets: calling handler <botocore.retryhandler.RetryHandler object at 0x181eb90>
2015-04-02 10:00:53,942 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2015-04-02 10:00:53,942 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.ListBuckets: calling handler <function enhance_error_msg at 0x15adc80>
2015-04-02 10:00:53,942 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.ListBuckets: calling handler <awscli.errorhandler.ErrorHandler object at 0x1622210>
2015-04-02 10:00:53,942 - MainThread - awscli.errorhandler - DEBUG - HTTP Response Code: 400
2015-04-02 10:00:53,942 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/site-packages/awscli/clidriver.py", line 183, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.6/site-packages/awscli/customizations/commands.py", line 190, in __call__
    parsed_globals)
  File "/usr/local/lib/python2.6/site-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/usr/local/lib/python2.6/site-packages/awscli/customizations/s3/subcommands.py", line 324, in _run_main
    self._list_all_buckets()
  File "/usr/local/lib/python2.6/site-packages/awscli/customizations/s3/subcommands.py", line 383, in _list_all_buckets
    response_data = self.client.list_buckets()
  File "/usr/local/lib/python2.6/site-packages/botocore/client.py", line 187, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.6/site-packages/botocore/client.py", line 238, in _make_api_call
    model=operation_model
  File "/usr/local/lib/python2.6/site-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.6/site-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.6/site-packages/awscli/errorhandler.py", line 70, in __call__
    http_status_code=http_response.status_code)
ClientError: A client error (AuthorizationHeaderMalformed) occurred when calling the ListBuckets operation: The authorization header is malformed; the region 'us-east' is wrong; expecting 'us-east-1'
2015-04-02 10:00:53,944 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

A client error (AuthorizationHeaderMalformed) occurred when calling the ListBuckets operation: The authorization header is malformed; the region 'us-east' is wrong; expecting 'us-east-1'

**Comment by joshunger** [comment]
Pro tip: likely coming from ~/.aws/config.  Move this file temporary and try again.  This helped me.

**Comment by manihere** [comment]
thanks @joshunger 
Go to ~/.aws/config
move the config file
go to terminal and type aws configure
Add the ID and Key
type aws s3 ls 
to see all the directories
