### ISSUE TITLE
unbound method __init__() must be called with HTTPConnection... python error when using any API call

### ISSUE THREAD

**Issue by catufunwa** [aws/aws-cli#1305]
I'm getting 

**Version:**
```
Chimas-Mac-mini:~ catufunwa$ aws --version
aws-cli/1.7.0 Python/2.7.6 Darwin/14.1.0
```

**Example:**
```
Chimas-Mac-mini:~ catufunwa$ aws iam list-users --debug
2015-04-23 12:34:40,422 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.7.0 Python/2.7.6 Darwin/14.1.0, botocore version: 0.81.0
2015-04-23 12:34:40,422 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x10314a848>
2015-04-23 12:34:40,422 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider at 0x1031088c0>
2015-04-23 12:34:40,423 - MainThread - botocore.service - DEBUG - Creating service object for: iam
2015-04-23 12:34:40,455 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.iam: calling handler <function register_retries_for_service at 0x102db7de8>
2015-04-23 12:34:40,457 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: iam
2015-04-23 12:34:40,457 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.iam: calling handler <function signature_overrides at 0x102db7f50>
2015-04-23 12:34:40,458 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.iam: calling handler <function register_retries_for_service at 0x102db7de8>
2015-04-23 12:34:40,458 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: iam
2015-04-23 12:34:40,458 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.iam: calling handler <function signature_overrides at 0x102db7f50>
2015-04-23 12:34:40,458 - MainThread - botocore.service - DEBUG - Creating operation objects for: Service(iam)
2015-04-23 12:34:40,467 - MainThread - botocore.hooks - DEBUG - Event building-command-table.iam: calling handler <function add_waiters at 0x103114668>
2015-04-23 12:34:40,468 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'path-prefix', <awscli.arguments.CLIArgument object at 0x103276810>), (u'marker', <awscli.arguments.CLIArgument object at 0x103276850>), (u'max-items', <awscli.arguments.CLIArgument object at 0x103276890>)])
2015-04-23 12:34:40,468 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.iam.list-users: calling handler <function add_streaming_output_arg at 0x103022938>
2015-04-23 12:34:40,468 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.iam.list-users: calling handler <function add_cli_input_json at 0x103104b18>
2015-04-23 12:34:40,468 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.iam.list-users: calling handler <function unify_paging_params at 0x1030267d0>
2015-04-23 12:34:40,469 - MainThread - awscli.customizations.paginate - DEBUG - Modifying paging parameters for operation: Operation:ListUsers
2015-04-23 12:34:40,469 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.iam.list-users: calling handler <function add_generate_skeleton at 0x1031080c8>
2015-04-23 12:34:40,469 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.iam.list-users: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x1032768d0>>
2015-04-23 12:34:40,469 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.iam.list-users: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x103276bd0>>
2015-04-23 12:34:40,470 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.iam.list-users: calling handler <functools.partial object at 0x103169788>
2015-04-23 12:34:40,470 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.iam.list-users.path-prefix: calling handler <function uri_param at 0x102ffe668>
2015-04-23 12:34:40,470 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.iam.list-users.marker: calling handler <function uri_param at 0x102ffe668>
2015-04-23 12:34:40,470 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.iam.list-users.max-items: calling handler <function uri_param at 0x102ffe668>
2015-04-23 12:34:40,471 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.iam.list-users.cli-input-json: calling handler <function uri_param at 0x102ffe668>
2015-04-23 12:34:40,471 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.iam.list-users.starting-token: calling handler <function uri_param at 0x102ffe668>
2015-04-23 12:34:40,471 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.iam.list-users.page-size: calling handler <function uri_param at 0x102ffe668>
2015-04-23 12:34:40,471 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.iam.list-users.generate-cli-skeleton: calling handler <function uri_param at 0x102ffe668>
2015-04-23 12:34:40,471 - MainThread - botocore.hooks - DEBUG - Event calling-command.iam.list-users: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x103276bd0>>
2015-04-23 12:34:40,471 - MainThread - botocore.hooks - DEBUG - Event calling-command.iam.list-users: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x1032768d0>>
2015-04-23 12:34:40,471 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2015-04-23 12:34:40,471 - MainThread - botocore.credentials - INFO - Found credentials in environment variables.
2015-04-23 12:34:41,606 - MainThread - botocore.operation - DEBUG - Operation:ListUsers called with kwargs: {}
2015-04-23 12:34:41,607 - MainThread - botocore.endpoint - DEBUG - Making request for <botocore.model.OperationModel object at 0x10326fe50> (verify_ssl=True) with params: {'query_string': '', 'headers': {}, 'url_path': '/', 'body': {'Action': u'ListUsers', 'Version': u'2010-05-08'}, 'method': u'POST'}
2015-04-23 12:34:41,608 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2015-04-23 12:34:41,608 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

host:iam.amazonaws.com
user-agent:aws-cli/1.7.0 Python/2.7.6 Darwin/14.1.0
x-amz-date:20150423T163441Z

host;user-agent;x-amz-date
b6359........085e2
2015-04-23 12:34:41,608 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20150423T163441Z
20150423/us-east-1/iam/aws4_request
27ac8b.......8ca8f2
2015-04-23 12:34:41,608 - MainThread - botocore.auth - DEBUG - Signature:
a34901........5cb7b
2015-04-23 12:34:41,615 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2015-04-23 12:34:41,615 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): iam.amazonaws.com
2015-04-23 12:34:41,615 - MainThread - botocore.endpoint - DEBUG - Exception received when sending HTTP request.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 192, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/usr/local/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 464, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py", line 321, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 466, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/local/lib/python2.7/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 217, in _get_conn
    return conn or self._new_conn()
  File "/usr/local/lib/python2.7/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 645, in _new_conn
    **extra_params)
  File "/usr/local/lib/python2.7/site-packages/botocore/awsrequest.py", line 64, in __init__
    HTTPConnection.__init__(self, *args, **kwargs)
TypeError: unbound method __init__() must be called with HTTPConnection instance as first argument (got AWSHTTPSConnection instance instead)
2015-04-23 12:34:41,686 - MainThread - botocore.hooks - DEBUG - Event needs-retry.iam.ListUsers: calling handler <botocore.retryhandler.RetryHandler object at 0x103206a50>
2015-04-23 12:34:41,686 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 197, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 357, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 492, in __call__
    self._operation_object, call_parameters, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 594, in invoke
    parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 607, in _display_response
    formatter(operation, response)
  File "/usr/local/lib/python2.7/site-packages/awscli/formatter.py", line 58, in __call__
    response_data = response.build_full_result()
  File "/usr/local/lib/python2.7/site-packages/botocore/paginate.py", line 215, in build_full_result
    for _, page in self:
  File "/usr/local/lib/python2.7/site-packages/botocore/paginate.py", line 70, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/paginate.py", line 390, in _make_request
    return self._operation.call(self._endpoint, **current_kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/operation.py", line 90, in call
    response = endpoint.make_request(self.model, request_dict)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 109, in make_request
    return self._send_request(prepared_request, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 172, in _send_request
    response, exception):
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 213, in _needs_retry
    caught_exception=caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 180, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 247, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 262, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 310, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 219, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 352, in _check_caught_exception
    raise caught_exception
TypeError: unbound method __init__() must be called with HTTPConnection instance as first argument (got AWSHTTPSConnection instance instead)
2015-04-23 12:34:41,731 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

unbound method __init__() must be called with HTTPConnection instance as first argument (got AWSHTTPSConnection instance instead)
```

**Comment by catufunwa** [comment]
This might still a problem, but I fixed it by removing the aws setup that was installed by PIP and compiled one straight from source. 

+1 for compiling from source.
