### ISSUE TITLE
CloudWatch Logs not respecting proxy configuration

### ISSUE THREAD

**Issue by philwill-nap** [aws/aws-cli#1308]
Version: aws-cli/1.7.23 Python/2.7.9 Linux/3.14.35-28.38.amzn1.x86_64

All calls to the internet from our VPC must pass through our ELB/ASG of proxy servers. To use CloudWatch Logs in this environment we were advised to patch awslogs-agent-launcher.sh as follows:

    #!/bin/sh
    # Version: 1.3.2
    echo -n $$ > /var/awslogs/state/awslogs.pid
    /usr/bin/env -i AWS_CONFIG_FILE=/var/awslogs/etc/aws.conf HOME=$HOME no_proxy=169.254.169.254 http_proxy=http://proxy:3128 https_proxy=http://proxy:3128 /bin/nice -n 4 /var/awslogs/bin/aws logs push --config-file /var/awslogs/etc/awslogs.conf >> /var/log/awslogs.log 2>&1

With these amendments the following appears in /var/log/awslogs.log:

    2015-04-27 09:15:40,742 - cwlogs.push.publisher - WARNING - 3011 - Thread-3 - Caught exception: hostname 'proxy' doesn't match 'logs.eu-west-1.amazonaws.com'
    2015-04-27 09:15:40,743 - cwlogs.threads - ERROR - 3011 - Thread-3 - Exception caught in <EventBatchPublisher(Thread-3, started daemon 140288008165120)>
    Traceback (most recent call last):
      File "/var/awslogs/local/lib/python2.7/site-packages/cwlogs/threads.py", line 58, in run
	self._run()
      File "/var/awslogs/local/lib/python2.7/site-packages/cwlogs/push.py", line 1235, in _run
	self._publish_event_batch()
      File "/var/awslogs/local/lib/python2.7/site-packages/cwlogs/push.py", line 1085, in _publish_event_batch
	self.sequence_token = self._put_log_events(self.event_batch)
      File "/var/awslogs/local/lib/python2.7/site-packages/cwlogs/push.py", line 1123, in _put_log_events
	response = self.logs_service.PutLogEvents(**params)
      File "/var/awslogs/local/lib/python2.7/site-packages/awscli/customizations/service.py", line 36, in __call__
	res, data = self._operation.call(self.endpoint, **kwargs)
      File "/var/awslogs/local/lib/python2.7/site-packages/botocore/operation.py", line 90, in call
	response = endpoint.make_request(self.model, request_dict)
      File "/var/awslogs/local/lib/python2.7/site-packages/botocore/endpoint.py", line 109, in make_request
	return self._send_request(prepared_request, operation_model)
      File "/var/awslogs/local/lib/python2.7/site-packages/botocore/endpoint.py", line 172, in _send_request
	response, exception):
      File "/var/awslogs/local/lib/python2.7/site-packages/botocore/endpoint.py", line 213, in _needs_retry
	caught_exception=caught_exception)
      File "/var/awslogs/local/lib/python2.7/site-packages/botocore/hooks.py", line 182, in emit
	response = handler(**kwargs)
      File "/var/awslogs/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 180, in __call__
	if self._checker(attempts, response, caught_exception):
      File "/var/awslogs/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 247, in __call__
	caught_exception)
      File "/var/awslogs/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 270, in _should_retry
	return self._checker(attempt_number, response, caught_exception)
      File "/var/awslogs/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 310, in __call__
	caught_exception)
      File "/var/awslogs/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 219, in __call__
	return self._check_caught_exception(attempt_number, caught_exception)
      File "/var/awslogs/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 352, in _check_caught_exception
	raise caught_exception
    SSLError: hostname 'proxy' doesn't match 'logs.eu-west-1.amazonaws.com'

I tried adding the `--no-verify-ssl` option to the `aws` invocation but it had no effect.

**Comment by philwill-nap** [comment]
Correction:
    /var/awslogs/bin/aws --version
    aws-cli/1.6.10 Python/2.7.9 Linux/3.14.35-28.38.amzn1.x86_64

**Comment by jamesls** [comment]
The cloudwatch logs plugin is maintained by the cloudwatch logs team.  I'd suggest opening an issue over in their [forums](https://forums.aws.amazon.com/forum.jspa?forumID=138).

I do want to verify that the AWS CLI works with a proxy though before closing out this issue.

**Comment by jamesls** [comment]
Closing out issue.  I've verified that the latest version of the cli (via `pip install --upgrade awscli`) honors the proxy settings as expected.  I'd suggest reaching out to cloudwatch logs on their forums to update to the latest version of the AWS CLI.
