### ISSUE TITLE
[1.7.26][windows][s3] Operation cannot be paginated: list_objects

### ISSUE THREAD

**Issue by konstantinvlasenko** [aws/aws-cli#1324]
Any operation that gets a list of files fails with the following error on windows:

**Operation cannot be paginated: list_objects**

So things like "aws s3 ls", "aws s3 sync", and "aws s3 cp --recursive" all fail with the above message. This was working in version 1.7.25.

The issue seems in underlying botocore library.

>2015-05-08 10:51:04,812 - MainThread - awscli.customizations.s3.s3handler - DEBUG - Exception caught during task execution: Operation cannot be paginated: list_objects
Traceback (most recent call last):
File "awscli\customizations\s3\s3handler.pyc", line 97, in call
File "awscli\customizations\s3\s3handler.pyc", line 175, in _enqueue_tasks
File "awscli\customizations\s3\fileinfobuilder.pyc", line 31, in call
File "awscli\customizations\s3\comparator.pyc", line 79, in call
File "awscli\customizations\s3\filegenerator.pyc", line 138, in call
File "awscli\customizations\s3\filegenerator.pyc", line 283, in list_objects
File "awscli\customizations\s3\utils.pyc", line 453, in list_objects
File "botocore\client.pyc", line 309, in get_paginator
OperationNotPageableError: Operation cannot be paginated: list_objects
2015-05-08 10:51:04,812 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 1)
2015-05-08 10:51:04,812 - Thread-1 - awscli.customizations.s3.executor - DEBUG - Received print task: PrintTask(message='Operation cannot be paginated: list_objects', error=True, total_parts=None, war
ning=None)
Operation cannot be paginated: list_objects

https://forums.aws.amazon.com/thread.jspa?threadID=180114&tstart=0

**Comment by kyleknap** [comment]
@konstantinvlasenko

I can confirm the issue. The issue is with how the MSI is packaged. If you need the latest version I would suggest trying to use pip or install the source code directly from GitHub. You can also download version 1.7.25 from https://s3.amazonaws.com/aws-cli/AWSCLI64-1.7.25.msi. Will update the issue once fixed.

**Comment by kyleknap** [comment]
I believe that the issue is now fixed. Try downloading the msi and see if the s3 commands work for you.

Let me know how it goes.

**Comment by konstantinvlasenko** [comment]
It works now.
Thank you!
