### ISSUE TITLE
describe-spot-price-history --cli-input-json

### ISSUE THREAD

**Issue by include** [aws/aws-cli#1366]
Hi,

I am running awscli version "aws-cli/1.7.31 Python/2.7.5 Darwin/13.4.0" and I am trying to list history price for instances using a json template generated with

```shell
aws ec2 describe-spot-price-history --generate-cli-skeleton > spot-price-history.json
```
I have edited just this section:

```json
    "ProductDescriptions": [
        "Linux/UNIX (Amazon VPC)"
    ],
```

and when I try to run and get those sweet prices, I get this error:

```shell
aws ec2 describe-spot-price-history --instance-type c3.large --cli-input-json file://spot-price-history.json --debug
2015-06-03 16:49:05,509 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.7.31 Python/2.7.5 Darwin/13.4.0, botocore version: 1.0.0a3
2015-06-03 16:49:05,509 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['ec2', 'describe-spot-price-history', '--instance-type', 'c3.large', '--cli-input-json', 'file://spot-price-history.json', '--debug']
2015-06-03 16:49:05,509 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x108f68050>
2015-06-03 16:49:05,510 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider at 0x108f149b0>
2015-06-03 16:49:05,593 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.ec2: calling handler <function register_retries_for_service at 0x108b92e60>
2015-06-03 16:49:05,594 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: ec2
2015-06-03 16:49:05,606 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <functools.partial object at 0x108f6a730>
2015-06-03 16:49:05,606 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-instance
2015-06-03 16:49:05,607 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-volume
2015-06-03 16:49:05,607 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <function add_waiters at 0x108f1bed8>
2015-06-03 16:49:05,611 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'dry-run', <awscli.arguments.BooleanArgument object at 0x1093c0350>), (u'no-dry-run', <awscli.arguments.BooleanArgument object at 0x1093c0210>), (u'start-time', <awscli.arguments.CLIArgument object at 0x1093c0690>), (u'end-time', <awscli.arguments.CLIArgument object at 0x1093c06d0>), (u'instance-types', <awscli.arguments.ListArgument object at 0x1093c0710>), (u'product-descriptions', <awscli.arguments.ListArgument object at 0x1093c0750>), (u'filters', <awscli.arguments.ListArgument object at 0x1093c0790>), (u'availability-zone', <awscli.arguments.CLIArgument object at 0x1093c07d0>), (u'max-results', <awscli.arguments.CLIArgument object at 0x1093c0810>), (u'next-token', <awscli.arguments.CLIArgument object at 0x1093c0850>)])
2015-06-03 16:49:05,611 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-spot-price-history: calling handler <function add_streaming_output_arg at 0x108e09aa0>
2015-06-03 16:49:05,611 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-spot-price-history: calling handler <function _rename_arg at 0x108f70500>
2015-06-03 16:49:05,612 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-spot-price-history: calling handler <function _rename_arg at 0x108f707d0>
2015-06-03 16:49:05,612 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-spot-price-history: calling handler <functools.partial object at 0x108f6a890>
2015-06-03 16:49:05,612 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-spot-price-history: calling handler <function add_cli_input_json at 0x108f14230>
2015-06-03 16:49:05,612 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-spot-price-history: calling handler <function unify_paging_params at 0x108e16b18>
2015-06-03 16:49:05,613 - MainThread - awscli.customizations.paginate - DEBUG - Modifying paging parameters for operation: DescribeSpotPriceHistory
2015-06-03 16:49:05,613 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-spot-price-history: calling handler <function add_generate_skeleton at 0x108f14500>
2015-06-03 16:49:05,613 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.describe-spot-price-history: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x10939e390>>
2015-06-03 16:49:05,613 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.describe-spot-price-history: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x1093c0d50>>
2015-06-03 16:49:05,615 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.ec2.describe-spot-price-history: calling handler <functools.partial object at 0x109340db8>
2015-06-03 16:49:05,615 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.ec2.describe-spot-price-history: calling handler <functools.partial object at 0x109340e10>
2015-06-03 16:49:05,615 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-spot-price-history.dry-run: calling handler <function uri_param at 0x108dddc08>
2015-06-03 16:49:05,615 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-spot-price-history.start-time: calling handler <function uri_param at 0x108dddc08>
2015-06-03 16:49:05,615 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-spot-price-history.end-time: calling handler <function uri_param at 0x108dddc08>
2015-06-03 16:49:05,616 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-spot-price-history.instance-types: calling handler <function uri_param at 0x108dddc08>
2015-06-03 16:49:05,616 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.ec2.describe-spot-price-history: calling handler <awscli.argprocess.ParamShorthand object at 0x108f67d50>
2015-06-03 16:49:05,616 - MainThread - awscli.argprocess - DEBUG - Detected structure: list-scalar
2015-06-03 16:49:05,616 - MainThread - awscli.arguments - DEBUG - Unpacked value of [u'c3.large'] for parameter "instance_types": [u'c3.large']
2015-06-03 16:49:05,616 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-spot-price-history.product-descriptions: calling handler <function uri_param at 0x108dddc08>
2015-06-03 16:49:05,616 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-spot-price-history.filters: calling handler <function uri_param at 0x108dddc08>
2015-06-03 16:49:05,616 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-spot-price-history.availability-zone: calling handler <function uri_param at 0x108dddc08>
2015-06-03 16:49:05,617 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-spot-price-history.max-results: calling handler <function uri_param at 0x108dddc08>
2015-06-03 16:49:05,617 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-spot-price-history.next-token: calling handler <function uri_param at 0x108dddc08>
2015-06-03 16:49:05,617 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-spot-price-history.cli-input-json: calling handler <function uri_param at 0x108dddc08>
2015-06-03 16:49:05,617 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-spot-price-history.starting-token: calling handler <function uri_param at 0x108dddc08>
2015-06-03 16:49:05,617 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-spot-price-history.page-size: calling handler <function uri_param at 0x108dddc08>
2015-06-03 16:49:05,617 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-spot-price-history.max-items: calling handler <function uri_param at 0x108dddc08>
2015-06-03 16:49:05,618 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-spot-price-history.generate-cli-skeleton: calling handler <function uri_param at 0x108dddc08>
2015-06-03 16:49:05,618 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.describe-spot-price-history: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x1093c0d50>>
2015-06-03 16:49:05,618 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.describe-spot-price-history: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x10939e390>>
2015-06-03 16:49:05,618 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2015-06-03 16:49:05,618 - MainThread - botocore.credentials - INFO - Found credentials in environment variables.
2015-06-03 16:49:05,619 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: ec2
2015-06-03 16:49:05,624 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.ec2: calling handler <function add_generate_presigned_url at 0x108b6dc80>
2015-06-03 16:49:05,639 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/Cellar/awscli/1.7.31/libexec/lib/python2.7/site-packages/awscli/clidriver.py", line 183, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/Cellar/awscli/1.7.31/libexec/lib/python2.7/site-packages/awscli/clidriver.py", line 369, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/Cellar/awscli/1.7.31/libexec/lib/python2.7/site-packages/awscli/clidriver.py", line 538, in __call__
    call_parameters, parsed_globals)
  File "/usr/local/Cellar/awscli/1.7.31/libexec/lib/python2.7/site-packages/awscli/clidriver.py", line 663, in invoke
    self._display_response(operation_name, response, parsed_globals)
  File "/usr/local/Cellar/awscli/1.7.31/libexec/lib/python2.7/site-packages/awscli/clidriver.py", line 672, in _display_response
    formatter(command_name, response)
  File "/usr/local/Cellar/awscli/1.7.31/libexec/lib/python2.7/site-packages/awscli/formatter.py", line 234, in __call__
    for page in response:
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/botocore/paginate.py", line 83, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/botocore/paginate.py", line 129, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/botocore/client.py", line 256, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/botocore/client.py", line 299, in _make_api_call
    api_params, operation_model)
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/botocore/client.py", line 340, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/botocore/validate.py", line 269, in serialize_to_request
    operation_model.input_shape)
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/botocore/validate.py", line 158, in validate
    self._validate(params, shape, errors, name='')
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/botocore/validate.py", line 162, in _validate
    getattr(self, '_validate_%s' % shape.type_name)(params, shape, errors, name)
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/botocore/validate.py", line 54, in _on_passes_type_check
    return func(self, param, shape, errors, name)
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/botocore/validate.py", line 183, in _validate_structure
    errors, '%s.%s' % (name, param))
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/botocore/validate.py", line 162, in _validate
    getattr(self, '_validate_%s' % shape.type_name)(params, shape, errors, name)
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/botocore/validate.py", line 246, in _validate_timestamp
    is_valid_type = self._type_check_datetime(param)
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/botocore/validate.py", line 254, in _type_check_datetime
    parse_to_aware_datetime(value)
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/botocore/utils.py", line 344, in parse_to_aware_datetime
    datetime_obj = parse_timestamp(value)
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/botocore/utils.py", line 306, in parse_timestamp
    return dateutil.parser.parse(value)
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/dateutil/parser.py", line 1008, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/dateutil/parser.py", line 392, in parse
    res = self._parse(timestr, **kwargs)
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/dateutil/parser.py", line 492, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/dateutil/parser.py", line 174, in split
    return list(cls(s))
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/dateutil/parser.py", line 171, in next
    return self.__next__()  # Python 2.x support
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/dateutil/parser.py", line 164, in __next__
    token = self.get_token()
  File "/usr/local/Cellar/awscli/1.7.31/libexec/vendor/lib/python2.7/site-packages/dateutil/parser.py", line 82, in get_token
    nextchar = self.instream.read(1)
AttributeError: 'NoneType' object has no attribute 'read'
2015-06-03 16:49:05,641 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

'NoneType' object has no attribute 'read'
```

some help would be appreciated :)

Cheers,
Francisco

**Comment by nmagee** [comment]
I can replicate this issue as well -- and end up with:

    'NoneType' object has no attribute 'read'

I am using "aws-cli/1.7.31 Python/2.7.3 Darwin/14.3.0"

**Comment by kyleknap** [comment]
Strange, I have not been able to reproduce what you are seeing. Does it work without using the ``--cli-input-json``? So instead does it work with just using ``--product-descriptions``?

Unfortunately, the debug logs are not helping too much here. It would be great to get the xml from the response somehow.

**Comment by jamesls** [comment]
@kyleknap I believe this is when you try to use it via `--cli-input-json`.

I think the issue is that we need to catch this in our validation logic and provide a better error message rather than letting the datetime parse error propogate, but the fix is straightforward.  All you need to do is just remove all the fields you don't want including StartTime/EndTime:

```
{
    "ProductDescriptions": [
	"Linux/UNIX (Amazon VPC)"
    ]
}
```

**Comment by kyleknap** [comment]
Ahh that makes sense why I was not able to reproduce it. I deleted all of the fields that I was not using in the json skeleton.

**Comment by include** [comment]
thanks guys :+1:
