### ISSUE TITLE
Feature req: retry if cmd fails because AWS throttling API calls

### ISSUE THREAD

**Issue by kallu** [aws/aws-cli#1376]
Sometimes when I run multiple scripts using aws -cli in parallel cmds fail because AWS API is throttling my calls, e.g. when calling cloudformation describe* -functions there is limit of 5 calls/s and if that is exceeded I get something similar to this

A client error (Throttling) occurred when calling the DescribeStacks operation: Rate exceeded

aws -cli should allow me to specify --retry-count and --retry-delay values on cmd-line. If there is throttling error, it should retry operation "--retry-count" times, sleeping a random time between 1s and "--retry-delay" seconds between retries.

**Comment by kyleknap** [comment]
The CLI has exponential back-off logic for retrying throttling errors. This logic should be applied for the situation that you are running into. Could you provide the debug logs for when it fails? You can do so by appending ``--debug`` to the command you ran.

This will tell me if the commands are failing on the retries or if the retries are not happening at all.

We will also consider adding the ability to customize retry count and delay.

**Comment by kallu** [comment]
It seems my problem was too old aws -cli version. After I did upgrade 1.7.4 -> 1.7.32 retry started working. With old version I got "maximum number of retry attempts" already at first call. Latest version didn't have this issue any longer and it was able retry until it succeed.

````
2015-06-11 06:20:35,057 - MainThread - botocore.retryhandler - DEBUG - retry needed: matching HTTP status and error code seen: 400, Throttling
2015-06-11 06:20:35,057 - MainThread - botocore.retryhandler - DEBUG - Reached the maximum number of retry attempts: 5
2015-06-11 06:20:35,057 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2015-06-11 06:20:35,058 - MainThread - botocore.hooks - DEBUG - Event after-call.cloudformation.DescribeStacks: calling handler <awscli.errorhandler.ErrorHandler object at 0x101afc050>
2015-06-11 06:20:35,058 - MainThread - awscli.errorhandler - DEBUG - HTTP Response Code: 400
2015-06-11 06:20:35,058 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 197, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 357, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 492, in __call__
    self._operation_object, call_parameters, parsed_globals)
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 594, in invoke
    parsed_globals)
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 607, in _display_response
    formatter(operation, response)
  File "/Library/Python/2.7/site-packages/awscli/formatter.py", line 58, in __call__
    response_data = response.build_full_result()
  File "/Library/Python/2.7/site-packages/botocore/paginate.py", line 215, in build_full_result
    for _, page in self:
  File "/Library/Python/2.7/site-packages/botocore/paginate.py", line 70, in __iter__
    response = self._make_request(current_kwargs)
  File "/Library/Python/2.7/site-packages/botocore/paginate.py", line 390, in _make_request
    return self._operation.call(self._endpoint, **current_kwargs)
  File "/Library/Python/2.7/site-packages/botocore/operation.py", line 98, in call
    parsed=response[1])
  File "/Library/Python/2.7/site-packages/botocore/session.py", line 735, in emit
    return self._events.emit(event_name, **kwargs)
  File "/Library/Python/2.7/site-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/Library/Python/2.7/site-packages/awscli/errorhandler.py", line 70, in __call__
    http_status_code=http_response.status_code)
ClientError: A client error (Throttling) occurred when calling the DescribeStacks operation: Rate exceeded
2015-06-11 06:20:35,059 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255
````
