### ISSUE TITLE
No support for Boto3

### ISSUE THREAD

**Issue by SamCyanide** [aws/aws-cli#1378]
When attempting to use this package with Boto3 the following error is returned upon running "aws" or any sub-command.

```python
sam@nonagon ~ $ aws
Traceback (most recent call last):
  File "/usr/bin/aws", line 23, in <module>
    sys.exit(main())
  File "/usr/bin/aws", line 19, in main
    return awscli.clidriver.main()
  File "/usr/share/awscli/awscli/clidriver.py", line 44, in main
    driver = create_clidriver()
  File "/usr/share/awscli/awscli/clidriver.py", line 53, in create_clidriver
    event_hooks=emitter)
  File "/usr/share/awscli/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/usr/share/awscli/awscli/plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "/usr/share/awscli/awscli/handlers.py", line 24, in <module>
    from awscli.customizations.ec2addcount import ec2_add_count
  File "/usr/share/awscli/awscli/customizations/ec2addcount.py", line 16, in <module>
    from botocore.parameters import StringParameter
ImportError: No module named 'botocore.parameters'

```

**Comment by kyleknap** [comment]
@SamCyanide 
How did you install boto3 and the CLI? Can you provide a set of steps to follow to reproduce what you are seeing?

**Comment by SamCyanide** [comment]
I installed boto3 via pip, and have had several reboots since then, and then I installed awscli via pip as well. It did not work, but after a reboot it seems to be running fine.

**Comment by jeffbrl** [comment]
I encountered the same issue. Doing a pip upgrade on awscli to the current version in PyPi fixed the issue.

**Comment by expl0ratory** [comment]
same issue, upgrade not working either
