### ISSUE TITLE
[BUG] [aws deploy] 'latin1' code character causes error when displaying data

### ISSUE THREAD

**Issue by virgofx** [aws/aws-cli#1386]
- `aws --version`: **aws-cli/1.7.34 Python/2.7.3 Linux/3.2.0-23-generic-pae**
- `cat /etc/*release`: **Ubuntu 12.04**

Command:

```
aws deploy get-deployment-instance --deployment-id d-H9QQE1GE9 --instance-id i-23a541eb
```

Results in the following error:

```
'latin-1' codec can't encode character u'\u2018' in position 156: ordinal not in range(256)
```

Full Output:

```
{
    "instanceSummary": {
        "instanceId": "arn:aws:ec2:us-west-2:886747006297:instance/i-23a541eb", 
        "status": "Failed", 
        "deploymentId": "d-H9QQE1GE9", 
        "lastUpdatedAt": 1434225478.471, 
        "lifecycleEvents": [
            {
                "endTime": 1434225473.806, 
                "status": "Succeeded", 
                "diagnostics": {
                    "errorCode": "Success", 
                    "scriptName": "", 
                    "logTail": "", 
                    "message": "Succeeded"
                }, 
                "startTime": 1434225473.71, 
                "lifecycleEventName": "ApplicationStop"
            }, 
            {
                "endTime": 1434225475.267, 
                "status": "Succeeded", 
                "diagnostics": {
                    "errorCode": "Success", 
                    "scriptName": "", 
                    "logTail": "", 
                    "message": "Succeeded"
                }, 
                "startTime": 1434225474.915, 
                "lifecycleEventName": "DownloadBundle"
            }, 
            {
                "endTime": 1434225476.555, 
                "status": "Failed", 
                "diagnostics": {
                    "errorCode": "ScriptFailed", 
                    "scriptName": "bin/deploy/before-install.sh", 
                    "logTail": 
'latin-1' codec can't encode character u'\u2018' in position 156: ordinal not in range(256)
```

Debug Output:

```
"logTail": 2015-06-13 13:37:13,158 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 183, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 369, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 538, in __call__
    call_parameters, parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 663, in invoke
    self._display_response(operation_name, response, parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 672, in _display_response
    formatter(command_name, response)
  File "/usr/local/lib/python2.7/dist-packages/awscli/formatter.py", line 76, in __call__
    self._format_response(command_name, response_data, stream)
  File "/usr/local/lib/python2.7/dist-packages/awscli/formatter.py", line 96, in _format_response
    ensure_ascii=False)
  File "/usr/lib/python2.7/json/__init__.py", line 182, in dump
    fp.write(chunk)
  File "/usr/lib/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
```

The actual contents of the log tail are as follows:

```
ScriptFailed
Script Namebin/deploy/before-install.sh
MessageScript at specified location: bin/deploy/before-install.sh run as user root failed with exit code 1
Log TailLifecycleEvent - BeforeInstall
Script - bin/deploy/before-install.sh
[stdout]Ensuring cache directory exists ...
[stderr]mkdir: cannot create directory ‘/opt/codedeploy-agent/deployment-root/9c5d25f7-4800-4384-b829-a5a10017adae/d-H9QQE1GE9/deployment-archive/cache’: File exists
```

**Comment by kyleknap** [comment]
We will look into this. What does your locale settings look like when you run ``locale``? Does this get fixed when you run ``export LC_CTYPE=en_US.UTF-8``?

It would be great to get of steps we can follow to reproduce this issue.

**Comment by ddarbyson** [comment]
Not sure if this is related, however I'm having issues with `aws s3 sync` command. The following errors are found:

```
warning: Skipping file '509ed632cdee5- Li-Cover Letter&R\xe9sum\xe9.doc'. There was an error trying to decode the the file '509ed632cdee5- Li-Cover Letter&R\xe9sum\xe9.doc' in directory "/var/www/html/mysite/public/media/uploads/". 

Please check your locale settings.  The filename was decoded as: UTF-8
On posix platforms, check the LC_CTYPE environment variable.
```
