### ISSUE TITLE
swf respond-decision-task-completed doesn't parse JSON argument

### ISSUE THREAD

**Issue by jwulf** [aws/aws-cli#1451]
```
$ aws --version
aws-cli/1.7.45 Python/2.7.6 Darwin/14.4.0
```

```
$ aws swf respond-decision-task-completed --task-token AAAAKgAAAAIAAAAAAAAAAqs1PulpbhYs5FrKGGPiQwo7mkmnfWC/shI2fWAmtAk9seLMIIRpRvbNWsaX87pEYIy+E11ghsFoay9XEuBy3yvy+b1TbMGBGtMO6VaeSpZ/i2OMsLE4MGafk+0JichPObCHJ1z7OMifoKN/XEi59f+sUZGuuTJ5sg5+vsBqCJkEjUgjOc+m1Sff2gDNyoHfKZg8pctsEVp+1qnDkLWWdUojKtacZprAt/Dcf0GQDJhTal6YuaYR9vPU6OJGYDaU5nU8rekiEyUYb0wpJ3I2AZGkXF2YoSLZz9TlSSLk9HX6RJAXorHrvwxgFpdYgWJ1Lexky9Yi5mOh2yPkQAfcfKg= --decisions [{"decisionType":"ScheduleLambdaFunction","scheduleLambdaFunctionDecisionAttributes":{"id":"2342313421", "name":"swf_poller_newCustomerConsumer"}}]

Error parsing parameter '--decisions': Invalid JSON:
[{decisionType:ScheduleLambdaFunction,scheduleLambdaFunctionDecisionAttributes:{id:2342313421,
```

```
$ aws swf respond-decision-task-completed --task-token AAAAKgAAAAIAAAAAAAAAAqs1PulpbhYs5FrKGGPiQwo7mkmnfWC/shI2fWAmtAk9seLMIIRpRvbNWsaX87pEYIy+E11ghsFoay9XEuBy3yvy+b1TbMGBGtMO6VaeSpZ/i2OMsLE4MGafk+0JichPObCHJ1z7OMifoKN/XEi59f+sUZGuuTJ5sg5+vsBqCJkEjUgjOc+m1Sff2gDNyoHfKZg8pctsEVp+1qnDkLWWdUojKtacZprAt/Dcf0GQDJhTal6YuaYR9vPU6OJGYDaU5nU8rekiEyUYb0wpJ3I2AZGkXF2YoSLZz9TlSSLk9HX6RJAXorHrvwxgFpdYgWJ1Lexky9Yi5mOh2yPkQAfcfKg= --decisions [{"decisionType":"ScheduleLambdaFunction","scheduleLambdaFunctionDecisionAttributes":{"id":"2342313421", "name":"swf_poller_newCustomerConsumer"}}] --debug
2015-08-16 02:54:44,076 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.7.45 Python/2.7.6 Darwin/14.4.0, botocore version: 1.1.8
2015-08-16 02:54:44,076 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['swf', 'respond-decision-task-completed', '--task-token', 'AAAAKgAAAAIAAAAAAAAAAqs1PulpbhYs5FrKGGPiQwo7mkmnfWC/shI2fWAmtAk9seLMIIRpRvbNWsaX87pEYIy+E11ghsFoay9XEuBy3yvy+b1TbMGBGtMO6VaeSpZ/i2OMsLE4MGafk+0JichPObCHJ1z7OMifoKN/XEi59f+sUZGuuTJ5sg5+vsBqCJkEjUgjOc+m1Sff2gDNyoHfKZg8pctsEVp+1qnDkLWWdUojKtacZprAt/Dcf0GQDJhTal6YuaYR9vPU6OJGYDaU5nU8rekiEyUYb0wpJ3I2AZGkXF2YoSLZz9TlSSLk9HX6RJAXorHrvwxgFpdYgWJ1Lexky9Yi5mOh2yPkQAfcfKg=', '--decisions', '[{decisionType:ScheduleLambdaFunction,scheduleLambdaFunctionDecisionAttributes:{id:2342313421,', 'name:swf_poller_newCustomerConsumer}}]', '--debug']
2015-08-16 02:54:44,076 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x109ef7758>
2015-08-16 02:54:44,076 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider at 0x109eb1140>
2015-08-16 02:54:44,120 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.swf: calling handler <function register_retries_for_service at 0x109b71758>
2015-08-16 02:54:44,121 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: swf
2015-08-16 02:54:44,123 - MainThread - botocore.hooks - DEBUG - Event building-command-table.swf: calling handler <function add_waiters at 0x109eb7668>
2015-08-16 02:54:44,124 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'task-token', <awscli.arguments.CLIArgument object at 0x10a14acd0>), (u'decisions', <awscli.arguments.ListArgument object at 0x10a14ad10>), (u'execution-context', <awscli.arguments.CLIArgument object at 0x10a14ad50>)])
2015-08-16 02:54:44,125 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.swf.respond-decision-task-completed: calling handler <function add_streaming_output_arg at 0x109db3aa0>
2015-08-16 02:54:44,125 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.swf.respond-decision-task-completed: calling handler <function add_cli_input_json at 0x109ea4848>
2015-08-16 02:54:44,125 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.swf.respond-decision-task-completed: calling handler <function unify_paging_params at 0x109dc85f0>
2015-08-16 02:54:44,127 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.swf.respond-decision-task-completed: calling handler <function add_generate_skeleton at 0x109ea4c08>
2015-08-16 02:54:44,128 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.swf.respond-decision-task-completed: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x10a14abd0>>
2015-08-16 02:54:44,128 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.swf.respond-decision-task-completed: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x10a11ad10>>
2015-08-16 02:54:44,129 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.swf.respond-decision-task-completed.task-token: calling handler <function uri_param at 0x109da7050>
2015-08-16 02:54:44,130 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.swf.respond-decision-task-completed: calling handler <awscli.argprocess.ParamShorthand object at 0x109f09210>
2015-08-16 02:54:44,130 - MainThread - awscli.argprocess - DEBUG - Detected structure: scalar
2015-08-16 02:54:44,130 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'AAAAKgAAAAIAAAAAAAAAAqs1PulpbhYs5FrKGGPiQwo7mkmnfWC/shI2fWAmtAk9seLMIIRpRvbNWsaX87pEYIy+E11ghsFoay9XEuBy3yvy+b1TbMGBGtMO6VaeSpZ/i2OMsLE4MGafk+0JichPObCHJ1z7OMifoKN/XEi59f+sUZGuuTJ5sg5+vsBqCJkEjUgjOc+m1Sff2gDNyoHfKZg8pctsEVp+1qnDkLWWdUojKtacZprAt/Dcf0GQDJhTal6YuaYR9vPU6OJGYDaU5nU8rekiEyUYb0wpJ3I2AZGkXF2YoSLZz9TlSSLk9HX6RJAXorHrvwxgFpdYgWJ1Lexky9Yi5mOh2yPkQAfcfKg=' for parameter "task_token": u'AAAAKgAAAAIAAAAAAAAAAqs1PulpbhYs5FrKGGPiQwo7mkmnfWC/shI2fWAmtAk9seLMIIRpRvbNWsaX87pEYIy+E11ghsFoay9XEuBy3yvy+b1TbMGBGtMO6VaeSpZ/i2OMsLE4MGafk+0JichPObCHJ1z7OMifoKN/XEi59f+sUZGuuTJ5sg5+vsBqCJkEjUgjOc+m1Sff2gDNyoHfKZg8pctsEVp+1qnDkLWWdUojKtacZprAt/Dcf0GQDJhTal6YuaYR9vPU6OJGYDaU5nU8rekiEyUYb0wpJ3I2AZGkXF2YoSLZz9TlSSLk9HX6RJAXorHrvwxgFpdYgWJ1Lexky9Yi5mOh2yPkQAfcfKg='
2015-08-16 02:54:44,130 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.swf.respond-decision-task-completed.decisions: calling handler <function uri_param at 0x109da7050>
2015-08-16 02:54:44,130 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.swf.respond-decision-task-completed: calling handler <awscli.argprocess.ParamShorthand object at 0x109f09210>
2015-08-16 02:54:44,131 - MainThread - awscli.argprocess - DEBUG - Param decisions looks like JSON, not considered for param shorthand.
2015-08-16 02:54:44,131 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 183, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 369, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 510, in __call__
    self.arg_table)
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 565, in _build_call_parameters
    arg_object.add_to_params(service_params, value)
  File "/Library/Python/2.7/site-packages/awscli/arguments.py", line 444, in add_to_params
    unpacked = self._unpack_argument(value)
  File "/Library/Python/2.7/site-packages/awscli/arguments.py", line 461, in _unpack_argument
    return unpack_cli_arg(self, value)
  File "/Library/Python/2.7/site-packages/awscli/argprocess.py", line 162, in unpack_cli_arg
    cli_argument.cli_name)
  File "/Library/Python/2.7/site-packages/awscli/argprocess.py", line 171, in _unpack_cli_arg
    argument_model, value, cli_name)
  File "/Library/Python/2.7/site-packages/awscli/argprocess.py", line 203, in _unpack_complex_cli_arg
    for v in value]
  File "/Library/Python/2.7/site-packages/awscli/argprocess.py", line 171, in _unpack_cli_arg
    argument_model, value, cli_name)
  File "/Library/Python/2.7/site-packages/awscli/argprocess.py", line 186, in _unpack_complex_cli_arg
    raise ParamError(cli_name, "Invalid JSON:\n%s" % value)
ParamError: Error parsing parameter '--decisions': Invalid JSON:
[{decisionType:ScheduleLambdaFunction,scheduleLambdaFunctionDecisionAttributes:{id:2342313421,
2015-08-16 02:54:44,134 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Error parsing parameter '--decisions': Invalid JSON:
[{decisionType:ScheduleLambdaFunction,scheduleLambdaFunctionDecisionAttributes:{id:2342313421,
```

**Comment by jwulf** [comment]
Is it the nested array?

https://github.com/aws/aws-cli/pull/1444

**Comment by jwulf** [comment]
Nested JSON: https://github.com/aws/aws-cli/issues/1450

**Comment by rayluo** [comment]
What if you put your json stuff into a file stuff.json, and then feed it to CLI by this?

    --decisions file://path/to/stuff.json

**Comment by jwulf** [comment]
[/tmp] $  aws swf respond-decision-task-completed --task-token {massive_task_token} --decisions file:/tmp/decisions.json

Error parsing parameter '--decisions': Invalid JSON:
file:/tmp/decisions.json

 [/tmp] $ cat decisions.json 
[{"decisionType":"ScheduleLambdaFunction","scheduleLambdaFunctionDecisionAttributes":{"id":"2342313421", "name":"swf_poller_newCustomerConsumer"}}]

**Comment by mtdowling** [comment]
`file:/tmp/decisions.json` is not a valid URI. You need to use `file://` followed by your path. So `--decisions file:///tmp/decisions.json` will work. Notice that there are three slashes -- two to delineate between the scheme and the path, and one to mark it as an absolute path.

**Comment by jwulf** [comment]
Yep, that works.

**Comment by mtdowling** [comment]
Good to hear.
