### ISSUE TITLE
aws ec2 terminate instance not working <python error>

### ISSUE THREAD

**Issue by gone-phishing** [aws/aws-cli#1456]
aws ec2 terminate-instances --instance-ids i-9d0b9a58 --debug
2015-08-19 07:16:13,954 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.7.45 Python/2.7.5+ Linux/3.11.0-12-generic, botocore version: 1.1.8
2015-08-19 07:16:13,955 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['ec2', 'terminate-instances', '--instance-ids', 'i-9d0b9a58', '--debug']
2015-08-19 07:16:13,955 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x2acd050>
2015-08-19 07:16:13,955 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider at 0x2a549b0>
2015-08-19 07:16:14,019 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.ec2: calling handler <function register_retries_for_service at 0x25e5578>
2015-08-19 07:16:14,020 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: ec2
2015-08-19 07:16:14,026 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <functools.partial object at 0x2ad6cb0>
2015-08-19 07:16:14,026 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-instance
2015-08-19 07:16:14,026 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-volume
2015-08-19 07:16:14,026 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <function add_waiters at 0x2a597d0>
2015-08-19 07:16:14,029 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'dry-run', <awscli.arguments.BooleanArgument object at 0x377b110>), (u'no-dry-run', <awscli.arguments.BooleanArgument object at 0x377b150>), (u'instance-ids', <awscli.arguments.ListArgument object at 0x36a2f50>)])
2015-08-19 07:16:14,029 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.terminate-instances: calling handler <function add_streaming_output_arg at 0x2878b18>
2015-08-19 07:16:14,029 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.terminate-instances: calling handler <function _rename_arg at 0x2ae4848>
2015-08-19 07:16:14,029 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.terminate-instances: calling handler <function _rename_arg at 0x2ae4b18>
2015-08-19 07:16:14,029 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.terminate-instances: calling handler <functools.partial object at 0x2ad6e10>
2015-08-19 07:16:14,029 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.terminate-instances: calling handler <function add_cli_input_json at 0x2a4dc08>
2015-08-19 07:16:14,030 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.terminate-instances: calling handler <function unify_paging_params at 0x2882aa0>
2015-08-19 07:16:14,030 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.terminate-instances: calling handler <function add_generate_skeleton at 0x2a541b8>
2015-08-19 07:16:14,030 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.terminate-instances: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x3675490>>
2015-08-19 07:16:14,030 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.terminate-instances: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x36a2e10>>
2015-08-19 07:16:14,031 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.ec2.terminate-instances: calling handler <functools.partial object at 0x3696578>
2015-08-19 07:16:14,031 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.terminate-instances.dry-run: calling handler <function uri_param at 0x2841e60>
2015-08-19 07:16:14,032 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.terminate-instances.instance-ids: calling handler <function uri_param at 0x2841e60>
2015-08-19 07:16:14,032 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.ec2.terminate-instances: calling handler <awscli.argprocess.ParamShorthand object at 0x2acef50>
2015-08-19 07:16:14,032 - MainThread - awscli.argprocess - DEBUG - Detected structure: list-scalar
2015-08-19 07:16:14,032 - MainThread - awscli.arguments - DEBUG - Unpacked value of [u'i-9d0b9a58'] for parameter "instance_ids": [u'i-9d0b9a58']
2015-08-19 07:16:14,032 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.terminate-instances.cli-input-json: calling handler <function uri_param at 0x2841e60>
2015-08-19 07:16:14,032 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.terminate-instances.generate-cli-skeleton: calling handler <function uri_param at 0x2841e60>
2015-08-19 07:16:14,032 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.terminate-instances: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x36a2e10>>
2015-08-19 07:16:14,032 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.terminate-instances: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x3675490>>
2015-08-19 07:16:14,032 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2015-08-19 07:16:14,032 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2015-08-19 07:16:14,032 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2015-08-19 07:16:14,032 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: config-file
2015-08-19 07:16:14,033 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: ec2-credentials-file
2015-08-19 07:16:14,033 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: boto-config
2015-08-19 07:16:14,033 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: iam-role
2015-08-19 07:16:14,039 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): 169.254.169.254
2015-08-19 07:16:14,040 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "GET /latest/meta-data/iam/security-credentials/ HTTP/1.1" 200 None
2015-08-19 07:16:14,042 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): 169.254.169.254
2015-08-19 07:16:14,045 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "GET /latest/meta-data/iam/security-credentials/%3CHTML%3E%3CHEAD%3E%3CTITLE%3EAccess%20Denied%3C/TITLE%3E%3Cscript%20language=%22JavaScript%22%3E%20var%20category='IPAddress';var%20categorylist%20=%20['Spyware','SPAMURL','P2P','DownloadFreewareAndShareware','Gambling','Weapons','Plagiarism','CrimeandSuicide','PhishingandFraud','URLTranslationSites','Nudity','AdultContent','Violence','Porn','MilitancyandExtremist','Drugs','HateAndRacism','IllegalUnethical'];window.onload%20=%20function%20()%20%7B%20for%20(var%20i%20=%200;%20i%20%3C%20categorylist.length;%20i++)%20%7B%20if(categorylist[i]==category)%7Bdocument.getElementById('cyberoamlink').style.display='none';break;%20%7D%7D%7D;%20var%20heightVar,widthVar,timeoutInterval=50;function%20setHeightWidth()%7B%20%20%20var%20diff,reducePer,tempVar;%20%20if(widthVar%20%3E%20700)%7B%20%20%20diff%20=%20widthVar%20-%20700;%20%20%20reducePer%20=%20100%20*%20diff%20/%20widthVar;%20%20%20tempVar%20=%20reducePer%20*%20widthVar%20/%20100;%20%20%20widthVar%20=%20widthVar%20-%20tempVar;%20%20%20tempVar%20=%20reducePer%20*%20heightVar%20/%20100;%20%20%20heightVar%20=%20heightVar%20-%20tempVar;%20%20%7D%20%20if(heightVar%20%3E%2080)%7B%20%20%20diff%20=%20%20heightVar%20-%2080;%20%20%20reducePer%20=%20100%20*%20diff%20/%20heightVar;%20%20%20tempVar%20=%20reducePer%20*%20heightVar%20/%20100;%20%20%20heightVar%20=%20heightVar%20-%20tempVar;%20%20%20tempVar%20=%20reducePer%20*%20widthVar%20/%20100;%20%20%20widthVar%20=%20widthVar%20-%20tempVar;%20%20%7D%20%7D%20function%20setImageSize(imgName)%7B%20%20if(document.getElementById(imgName)%20&&%20document.getElementById(imgName).offsetWidth%20!=%200%20&&%20document.getElementById(imgName).offsetHeight%20!=%200)%7B%20%20%20widthVar%20=%20document.getElementById(imgName).offsetWidth;%20%20%20heightVar%20=%20document.getElementById(imgName).offsetHeight;%20%20%20setHeightWidth();%20%20%20document.getElementById(imgName).width%20=%20widthVar;%20%20%20document.getElementById(imgName).height%20=%20heightVar;%20%20%20document.getElementById(imgName).style.visibility='';%20%20%7Delse%7B%20%20%20setTimeout('setImageSize()',timeoutInterval);%20%20%7D%20%7D%20function%20callToSetImageSize(obj)%20%7B%20if(navigator.appName.indexOf(%22Opera%22)%20!=%20-1)%7BtimeoutInterval%20=%20350;%7DsetTimeout('setImageSize(%22'+obj.name+'%22)',timeoutInterval);%20%20%20%7D%20%3C/script%3E%3Cscript%20language=%22JavaScript%22%3E%20function%20callReevaluationFunction()%7B%20var%20locationURL='http://csc.cyberoam.com/cyberoamsupport/webpages/webcat/webcathome.jsp?url='+location;%20var%20win=window.open(locationURL,%20'_blank');win.focus();%7D%20%3C/script%3E%20%3Cmeta%20http-equiv=%22Content-Type%22%20content=%22text/html;%20charset=UTF-8%22%20/%3E%3Cstyle%20type='text/css'%3E.accessdeniedtextfont%7BFONT-WEIGHT:%20bolder;FONT-SIZE:%2012px;COLOR:%20 HTTP/1.1" 200 None
2015-08-19 07:16:14,046 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 183, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 369, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 538, in __call__
    call_parameters, parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 655, in invoke
    verify=parsed_globals.verify_ssl)
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 753, in create_client
    credentials = self.get_credentials()
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 412, in get_credentials
    'credential_provider').load_credentials()
  File "/usr/local/lib/python2.7/dist-packages/botocore/credentials.py", line 589, in load_credentials
    creds = provider.load()
  File "/usr/local/lib/python2.7/dist-packages/botocore/credentials.py", line 268, in load
    metadata = fetcher.retrieve_iam_role_credentials()
  File "/usr/local/lib/python2.7/dist-packages/botocore/utils.py", line 195, in retrieve_iam_role_credentials
    'access_key': data[role_name]['AccessKeyId'],
TypeError: string indices must be integers
2015-08-19 07:16:14,047 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

string indices must be integers

**Comment by gone-phishing** [comment]
I hadn't configured the iam settings for the aws-cli responsible for this error message (In my defense, it wasn't mentioned anywhere explicitly :(
