### ISSUE TITLE
`cannot import name IncompleteRead` during Ubuntu 15.04 install

### ISSUE THREAD

**Issue by mfowlewebs** [aws/aws-cli#1463]
I have a fresh copy of Ubuntu 15.04. Here's what happens when I follow install instructions and run `pip install awscli`:

```
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
```
:grimacing: 

I'd far rather an actual Debian/Ubuntu repository exist that packages this project. There is one, but the published packages are all from a three year old release.

**Comment by kyleknap** [comment]
Hmm. I was not able to reproduce the issue, assuming your version of pip is 1.5.6:
```
$ virtualenv temp
$ . temp/bin/activate
$ pip install pip==1.5.6
$ pip install awscli
```
It looks like the installation fails in ``requests``. The CLI removed its dependency on requests a while ago. So, I do not think it is an issue with the CLI. Maybe your version of ``requests`` does not match up with what is required for your version of pip? Does pip work for installing other python packages? I feel like this should affect any package you try install with pip.

**Comment by mtdowling** [comment]
Closing due to inactivity.
