### ISSUE TITLE
SSL connection fails on big files (may be related to VPC S3 endpoint)

### ISSUE THREAD

**Issue by adq** [aws/aws-cli#1507]
Hi, we recently added a VPC S3 endpoint to our VPC. Since then uploads of large files are failing at around the 10GB mark, but it varies.

See http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-endpoints.html for details of VPC endpoints.

We then tried disabling SSL. The uploads now work, but at around the 10GB mark (and with debug turned on), we can see the awscli is getting (and auto retrying) socket.error exceptions, code 104, "Connection reset by peer".

So there are two probems:
1) awscli does not cope with connection reset by peer errors when using SSL.
2) The VPC s3 endpoint is somehow causing socket.error exceptions to appear.

In the logs, I've manually masked the filenames as they are client sensitive.  

We're using aws-cli/1.8.5 Python/2.7.9 Linux/3.19.0-25-generic on ubuntu 15.04 from an amazon VPC instance in eu-west-1a

**Comment by adq** [comment]
2015-09-17 09:37:20,469 - Thread-6 - awscli.customizations.s3.tasks - DEBUG - Uploading part 533 for filename: /tmp/mylargetestfile
2015-09-17 09:37:20,470 - Thread-6 - awscli.customizations.s3.tasks - DEBUG - Waiting for upload id.
2015-09-17 09:37:20,470 - Thread-6 - botocore.hooks - DEBUG - Event before-parameter-build.s3.UploadPart: calling handler <function sse_md5 at 0x7f4235242938>
2015-09-17 09:37:20,470 - Thread-6 - botocore.hooks - DEBUG - Event before-parameter-build.s3.UploadPart: calling handler <function validate_bucket_name at 0x7f42352428c0>
2015-09-17 09:37:20,471 - Thread-6 - botocore.hooks - DEBUG - Event before-call.s3.UploadPart: calling handler <function conditionally_calculate_md5 at 0x7f4235242848>
2015-09-17 09:37:20,490 - Thread-6 - botocore.hooks - DEBUG - Event before-call.s3.UploadPart: calling handler <function add_expect_header at 0x7f4235242c08>
2015-09-17 09:37:20,490 - Thread-6 - botocore.handlers - DEBUG - Adding expect 100 continue header to request.
2015-09-17 09:37:20,490 - Thread-6 - botocore.endpoint - DEBUG - Making request for <botocore.model.OperationModel object at 0x7f423451c5d0> (verify_ssl=True) with params: {'body': <awscli.customizations.s3.utils.ReadFileChunk object at 0x7f423018bc90>, 'url': u'https://s3-eu-west-1.amazonaws.com/mybucket/mylargetestfile?partNumber=533&uploadId=****MASKED****', 'headers': {'Content-MD5': u'qOv4naHww9Pl61/fi6JoFQ==', 'Expect': '100-continue', 'User-Agent': 'aws-cli/1.8.5 Python/2.7.9 Linux/3.19.0-25-generic'}, 'query_string': {u'partNumber': 533, u'uploadId': '****MASKED****'}, 'url_path': u'/mybucket/mylargetestfile', 'method': u'PUT'}
2015-09-17 09:37:20,490 - Thread-6 - botocore.hooks - DEBUG - Event request-created.s3.UploadPart: calling handler <bound method S3._sign_request of <botocore.client.S3 object at 0x7f423451c910>>
2015-09-17 09:37:20,490 - Thread-6 - botocore.hooks - DEBUG - Event before-sign.s3.UploadPart: calling handler <function fix_s3_host at 0x7f423534c8c0>
2015-09-17 09:37:20,491 - Thread-6 - botocore.utils - DEBUG - Checking for DNS compatible bucket for: https://s3-eu-west-1.amazonaws.com/mybucket/mylargetestfile?partNumber=533&uploadId=****MASKED****
2015-09-17 09:37:20,491 - Thread-6 - botocore.utils - DEBUG - URI updated to: https://mybucket.s3.amazonaws.com/mylargetestfile?partNumber=533&uploadId=****MASKED****
2015-09-17 09:37:20,491 - Thread-6 - botocore.auth - DEBUG - Calculating signature using hmacv1 auth.
2015-09-17 09:37:20,491 - Thread-6 - botocore.auth - DEBUG - HTTP request method: PUT
2015-09-17 09:37:20,491 - Thread-6 - botocore.auth - DEBUG - StringToSign:
2015-09-17 09:37:20,492 - Thread-6 - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [PUT]>
2015-09-17 09:37:20,493 - Thread-6 - botocore.awsrequest - DEBUG - Waiting for 100 Continue response.
2015-09-17 09:37:20,509 - Thread-6 - botocore.awsrequest - DEBUG - 100 Continue response seen, now sending request body.
2015-09-17 09:37:43,723 - Thread-6 - botocore.endpoint - DEBUG - Exception received when sending HTTP request.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 168, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 588, in urlopen
    conn.close()
  File "/usr/lib/python2.7/httplib.py", line 839, in close
    self.sock.close()   # close it manually... there may be other refs
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/packages/urllib3/contrib/pyopenssl.py", line 213, in close
    return self.connection.shutdown()
Error: []
2015-09-17 09:37:43,726 - Thread-6 - botocore.hooks - DEBUG - Event needs-retry.s3.UploadPart: calling handler <botocore.retryhandler.RetryHandler object at 0x7f4234595590>
2015-09-17 09:37:43,726 - Thread-6 - awscli.customizations.s3.tasks - DEBUG - Error during part upload: []
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/s3/tasks.py", line 235, in __call__
    response_data = self._filename.client.upload_part(**params)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 268, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 322, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 111, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 140, in _send_request
    success_response, exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 204, in _needs_retry
    caught_exception=caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 250, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 265, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
Error: []
2015-09-17 09:37:43,727 - Thread-6 - awscli.customizations.s3.executor - DEBUG - Worker thread invoking task: <awscli.customizations.s3.tasks.UploadPartTask object at 0x7f42301ac3d0>
2015-09-17 09:37:43,728 - Thread-6 - awscli.customizations.s3.tasks - DEBUG - Uploading part 861 for filename: /tmp/mylargetestfile
2015-09-17 09:37:43,728 - Thread-6 - awscli.customizations.s3.tasks - DEBUG - Waiting for upload id.
2015-09-17 09:37:43,728 - Thread-6 - awscli.customizations.s3.tasks - DEBUG - Not uploading part, task has been cancelled.
2015-09-17 09:37:43,728 - Thread-6 - awscli.customizations.s3.executor - DEBUG - Worker thread invoking task: <awscli.customizations.s3.tasks.UploadPartTask object at 0x7f42301ac410>

**Comment by kyleknap** [comment]
We will have to do some research into this. Let us know if you find anything else that may prove to be helpful in debugging and reproducing the issue.

**Comment by justnance** [comment]
@adq - Thank you again for reporting this issue but unfortunately we have not heard back.  The CLI version in use when this issue was reported was `aws-cli/1.8.5'.  The current CLI version is now [1.16.96](https://github.com/aws/aws-cli).  Please [upgrade to the latest version](https://docs.aws.amazon.com/codedeploy/latest/userguide/getting-started-configure-cli.html) and advise if this is still and issue or if there is any other information available for us to continue debugging this issue.
