### ISSUE TITLE
"aws ecs help" doesn't work?

### ISSUE THREAD

**Issue by tycho** [aws/aws-cli#1530]
Any idea what's up with this?

```
$ aws --debug ecs help
2015-09-25 11:37:30,265 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.8.7 Python/2.7.10 Linux/4.1.7-1-ec2, botocore version: 1.2.5
2015-09-25 11:37:30,265 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', 'ecs', 'help']
2015-09-25 11:37:30,266 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7fd9ea1c9320>
2015-09-25 11:37:30,266 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider at 0x7fd9ea5fde60>
2015-09-25 11:37:30,275 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.ecs: calling handler <function register_retries_for_service at 0x7fd9eae21e60>
2015-09-25 11:37:30,275 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: ecs
2015-09-25 11:37:30,276 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ecs: calling handler <function add_waiters at 0x7fd9ea608c80>
2015-09-25 11:37:30,277 - MainThread - botocore.hooks - DEBUG - Event doc-breadcrumbs.ecs: calling handler <bound method ServiceDocumentEventHandler.doc_breadcrumbs of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,277 - MainThread - botocore.hooks - DEBUG - Event doc-title.ecs: calling handler <bound method ServiceDocumentEventHandler.doc_title of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,277 - MainThread - botocore.hooks - DEBUG - Event doc-description.ecs: calling handler <bound method ServiceDocumentEventHandler.doc_description of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,278 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-start.ecs: calling handler <bound method ServiceDocumentEventHandler.doc_synopsis_start of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,278 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-end.ecs: calling handler <bound method ServiceDocumentEventHandler.doc_synopsis_end of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,278 - MainThread - botocore.hooks - DEBUG - Event doc-options-start.ecs: calling handler <bound method ServiceDocumentEventHandler.doc_options_start of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,278 - MainThread - botocore.hooks - DEBUG - Event doc-options-end.ecs: calling handler <bound method ServiceDocumentEventHandler.doc_options_end of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,278 - MainThread - botocore.hooks - DEBUG - Event doc-subitems-start.ecs: calling handler <bound method ServiceDocumentEventHandler.doc_subitems_start of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,278 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.create-cluster: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,278 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.create-service: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,278 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.delete-cluster: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,278 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.delete-service: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,278 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.deregister-container-instance: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,279 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.deregister-task-definition: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,279 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.describe-clusters: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,279 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.describe-container-instances: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,279 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.describe-services: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,279 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.describe-task-definition: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,279 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.describe-tasks: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,279 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.discover-poll-endpoint: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,279 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.help: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,279 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.list-clusters: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,279 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.list-container-instances: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,279 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.list-services: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,279 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.list-task-definition-families: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,279 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.list-task-definitions: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,280 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.list-tasks: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,280 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.register-container-instance: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,280 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.register-task-definition: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,280 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.run-task: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,280 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.start-task: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,280 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.stop-task: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,280 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.submit-container-state-change: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,280 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.submit-task-state-change: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,280 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.update-container-agent: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,280 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.update-service: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,280 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.ecs.wait: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x7fd9e9d8ac50>>
2015-09-25 11:37:30,280 - MainThread - botocore.hooks - DEBUG - Event building-command-table.wait: calling handler <function add_waiters at 0x7fd9ea608c80>
2015-09-25 11:37:30,284 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 183, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 369, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/lib/python2.7/site-packages/awscli/help.py", line 244, in __call__
    docevents.generate_events(self.session, self)
  File "/usr/lib/python2.7/site-packages/botocore/docs/bcdoc/docevents.py", line 87, in generate_events
    help_command=help_command)
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 653, in emit
    return self._events.emit(event_name, **kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/usr/lib/python2.7/site-packages/awscli/clidocs.py", line 288, in doc_subitem
    subcommand_table = getattr(subcommand, 'subcommand_table', {})
  File "/usr/lib/python2.7/site-packages/awscli/customizations/commands.py", line 278, in subcommand_table
    self._subcommand_table = self._build_subcommand_table()
  File "/usr/lib/python2.7/site-packages/awscli/customizations/waiters.py", line 73, in _build_subcommand_table
    self.waiter_cmd_builder.build_all_waiter_state_cmds(subcommand_table)
  File "/usr/lib/python2.7/site-packages/awscli/customizations/waiters.py", line 100, in build_all_waiter_state_cmds
    self._build_waiter_state_cmd(waiter_name)
  File "/usr/lib/python2.7/site-packages/awscli/customizations/waiters.py", line 128, in _build_waiter_state_cmd
    description = waiter_state_doc_builder.build_waiter_state_description()
  File "/usr/lib/python2.7/site-packages/awscli/customizations/waiters.py", line 154, in build_waiter_state_description
    for acceptor in self._waiter_config.acceptors:
  File "/usr/lib/python2.7/site-packages/botocore/waiter.py", line 153, in acceptors
    acceptor = AcceptorConfig(acceptor_config)
  File "/usr/lib/python2.7/site-packages/botocore/waiter.py", line 164, in __init__
    self.matcher_func = self._create_matcher_func()
  File "/usr/lib/python2.7/site-packages/botocore/waiter.py", line 176, in _create_matcher_func
    return self._create_path_matcher()
  File "/usr/lib/python2.7/site-packages/botocore/waiter.py", line 190, in _create_path_matcher
    expression = jmespath.compile(self.argument)
  File "/usr/lib/python2.7/site-packages/jmespath/__init__.py", line 7, in compile
    return parser.Parser().parse(expression)
  File "/usr/lib/python2.7/site-packages/jmespath/parser.py", line 79, in parse
    parsed_result = self._do_parse(expression)
  File "/usr/lib/python2.7/site-packages/jmespath/parser.py", line 87, in _do_parse
    return self._parse(expression)
  File "/usr/lib/python2.7/site-packages/jmespath/parser.py", line 102, in _parse
    parsed = self._expression(binding_power=0)
  File "/usr/lib/python2.7/site-packages/jmespath/parser.py", line 124, in _expression
    left = led(left)
  File "/usr/lib/python2.7/site-packages/jmespath/parser.py", line 195, in _token_led_pipe
    right = self._expression(self.BINDING_POWER['pipe'])
  File "/usr/lib/python2.7/site-packages/jmespath/parser.py", line 115, in _expression
    left = nud_function(left_token)
  File "/usr/lib/python2.7/site-packages/jmespath/parser.py", line 177, in _token_nud_lbracket
    return self._parse_multi_select_list()
  File "/usr/lib/python2.7/site-packages/jmespath/parser.py", line 286, in _parse_multi_select_list
    expression = self._expression()
  File "/usr/lib/python2.7/site-packages/jmespath/parser.py", line 115, in _expression
    left = nud_function(left_token)
  File "/usr/lib/python2.7/site-packages/jmespath/parser.py", line 378, in _error_nud_token
    token['type'], 'Invalid token.')
ParseError: Invalid token.: Parse error at column 12 near token "@" (CURRENT) for expression:
"services | [@[?length(deployments)!=`1`], @[?desiredCount!=runningCount]][] | length(@) == `0`"
             ^
2015-09-25 11:37:30,285 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Invalid token.: Parse error at column 12 near token "@" (CURRENT) for expression:
"services | [@[?length(deployments)!=`1`], @[?desiredCount!=runningCount]][] | length(@) == `0`"
             ^
```

**Comment by tycho** [comment]
Nevermind, it appears bcdoc was outdated.
