### ISSUE TITLE
[awscli-cwlogs] Trailing characters in datetime_format not being respected when %z is specified

### ISSUE THREAD

**Issue by univerio** [aws/aws-cli#1540]
Hope I'm filing this in the right place.

When `datetime_format` is configured to have `%z` and trailing characters, the pattern fails to match. Example:

```python
>>> DateTimeParser('"timestamp":"%Y-%m-%dT%H:%M:%S.%f"').parse('{"timestamp":"2015-10-01T23:30:18.248958"}')
datetime.datetime(2015, 10, 1, 23, 30, 18, 248958, tzinfo=tzlocal())
>>> DateTimeParser('"timestamp":"%Y-%m-%dT%H:%M:%S.%f%z').parse('{"timestamp":"2015-10-01T23:30:18.248958-0000"}')
datetime.datetime(2015, 10, 1, 23, 30, 18, 248958, tzinfo=tzoffset(None, 0))
>>> DateTimeParser('"timestamp":"%Y-%m-%dT%H:%M:%S.%f%z"').parse('{"timestamp":"2015-10-01T23:30:18.248958-0000"}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "parser.py", line 92, in parse
    tz = tzlocal()
  File "/home/jack/.pyenv/versions/2.7.10/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '"timestamp":"2015-10-01T23:30:18.248958' does not match format '"timestamp":"%Y-%m-%dT%H:%M:%S.%f"'
```

The fix:

```diff
--- parser.py.ORIGINAL	2015-10-01 17:07:56.621435783 -0700
+++ parser.py	2015-10-01 17:08:06.189588190 -0700
@@ -82,7 +82,7 @@
                 z = m.group('z')
                 # Remove offset from datetime str
                 dt_str = (message[m.start('dt'):m.start('z')] +
-                          dt_str[m.end('z'):m.end('dt')])
+                          message[m.end('z'):m.end('dt')])
                 # Convert [+-]HHMM offset to seconds
                 offset = int(z[1:3]) * 3600 + int(z[3:5]) * 60
                 if z.startswith('-'):
```

**Comment by rayluo** [comment]
Sorry can you elaborate how and where exactly did you observe the symptom? You can try to send out a pull request (with test cases) to the correct repo (awscli or botocore) so that we can communicate more efficiently.

**Comment by univerio** [comment]
This is for the CloudWatch Logs agent.

**Comment by rayluo** [comment]
In that case, perhaps you can find more relevant community in the [CloudWatch forum](https://forums.aws.amazon.com/forum.jspa?forumID=138&start=0).

**Comment by univerio** [comment]
Thanks for the pointer. I'll close this ticket.
