### ISSUE TITLE
lambda invoke can't handle large payloads

### ISSUE THREAD

**Issue by GerritJanssen2** [aws/aws-cli#1546]
Easily reproducible without any additional setup using AWS CLI version 1.8.7 on an EC2 instance:
aws lambda invoke --invocation-type RequestResponse --function-name nonexistentfunctionname --payload file://./payload.json output.out --debug

When the payload.json file contains the following, you will get the timeout:
{
	"key1": "value",
	"key2": "value",
	"key3": "value",
	"key4": "value",
	"key5": "value",
	"key6": "value",
	"key7": "value",
	"key8": "value",
	"key9": "value",
	"key10": "value"
}

The timeout occurs after one minute:
2015-10-06 10:05:58,728 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2015-10-06 10:05:58,728 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): lambda.eu-west-1.amazonaws.com
2015-10-06 10:06:58,806 - MainThread - botocore.endpoint - DEBUG - Exception received when sending HTTP request.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/botocore/endpoint.py", line 168, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/usr/lib/python2.7/dist-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/botocore/vendored/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='lambda.eu-west-1.amazonaws.com', port=443): Read timed out. (read timeout=60)

However, if you remove "key10" from payload.json, it will work just fine.

**Comment by JordonPhillips** [comment]
I'm having difficulty reproducing, could you tell me what environment you're running from?

**Comment by GerritJanssen2** [comment]
Can no longer reproduce it either.
