### ISSUE TITLE
aws s3 ls : __str__ returned non-string (type Error)

### ISSUE THREAD

**Issue by brendan-r** [aws/aws-cli#1572]
Any ideas what might be causing this? The cli was working fine for me a month or so ago. I've tried updating via `pip` and resetting my access keys. I'm getting the same error for all `s3`/`s3api` commands.
## Example Command

```
aws s3 ls s3://brendanrocks.com

__str__ returned non-string (type Error)

```
## Version

```
$ aws --version
aws-cli/1.8.13 Python/2.7.9 Linux/3.19.0-30-generic
```
## Debug

```
$ aws s3 ls s3://brendanrocks.com --debug
2015-10-19 18:58:07,960 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.8.13 Python/2.7.9 Linux/3.19.0-30-generic, botocore version: 1.2.11
2015-10-19 18:58:07,960 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3', 'ls', 's3://brendanrocks.com', '--debug']
2015-10-19 18:58:07,960 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7f3d97b31848>
2015-10-19 18:58:07,960 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider at 0x7f3d97d8e398>
2015-10-19 18:58:07,961 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3: calling handler <function add_waiters at 0x7f3d97d971b8>
2015-10-19 18:58:07,961 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.s3.anonymous: calling handler <function uri_param at 0x7f3d97f13140>
2015-10-19 18:58:07,961 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ls: calling handler <function add_waiters at 0x7f3d97d971b8>
2015-10-19 18:58:07,962 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.paths: calling handler <function uri_param at 0x7f3d97f13140>
2015-10-19 18:58:07,962 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.summarize: calling handler <function uri_param at 0x7f3d97f13140>
2015-10-19 18:58:07,962 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.ls: calling handler <awscli.argprocess.ParamShorthand object at 0x7f3d97b3bb10>
2015-10-19 18:58:07,962 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.anonymous: calling handler <function uri_param at 0x7f3d97f13140>
2015-10-19 18:58:07,962 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.human-readable: calling handler <function uri_param at 0x7f3d97f13140>
2015-10-19 18:58:07,962 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.ls: calling handler <awscli.argprocess.ParamShorthand object at 0x7f3d97b3bb10>
2015-10-19 18:58:07,962 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.page-size: calling handler <function uri_param at 0x7f3d97f13140>
2015-10-19 18:58:07,962 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2015-10-19 18:58:07,962 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2015-10-19 18:58:07,962 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2015-10-19 18:58:07,962 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2015-10-19 18:58:07,979 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2015-10-19 18:58:07,981 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f3d982b6050>
2015-10-19 18:58:07,981 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f3d98321f50>
2015-10-19 18:58:07,983 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2015-10-19 18:58:07,983 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <function validate_bucket_name at 0x7f3d982ca500>
2015-10-19 18:58:07,984 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.ListObjects: calling handler <function add_expect_header at 0x7f3d982ca848>
2015-10-19 18:58:07,984 - MainThread - botocore.endpoint - DEBUG - Making request for <botocore.model.OperationModel object at 0x7f3d97792b90> (verify_ssl=True) with params: {'body': '', 'url': u'https://s3-us-west-2.amazonaws.com/brendanrocks.com?prefix=&delimiter=%2F', 'headers': {'User-Agent': 'aws-cli/1.8.13 Python/2.7.9 Linux/3.19.0-30-generic'}, 'query_string': {u'prefix': '', u'delimiter': '/'}, 'url_path': u'/brendanrocks.com', 'method': u'GET'}
2015-10-19 18:58:07,984 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.ListObjects: calling handler <bound method S3._sign_request of <botocore.client.S3 object at 0x7f3d9779f890>>
2015-10-19 18:58:07,984 - MainThread - botocore.hooks - DEBUG - Event before-sign.s3.ListObjects: calling handler <function fix_s3_host at 0x7f3d983ce938>
2015-10-19 18:58:07,984 - MainThread - botocore.utils - DEBUG - Checking for DNS compatible bucket for: https://s3-us-west-2.amazonaws.com/brendanrocks.com?prefix=&delimiter=%2F
2015-10-19 18:58:07,984 - MainThread - botocore.utils - DEBUG - Not changing URI, bucket is not DNS compatible: brendanrocks.com
2015-10-19 18:58:07,985 - MainThread - botocore.auth - DEBUG - Calculating signature using hmacv1 auth.
2015-10-19 18:58:07,985 - MainThread - botocore.auth - DEBUG - HTTP request method: GET
2015-10-19 18:58:07,985 - MainThread - botocore.auth - DEBUG - StringToSign:
GET


Tue, 20 Oct 2015 01:58:07 GMT
/brendanrocks.com
2015-10-19 18:58:07,986 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [GET]>
2015-10-19 18:58:07,986 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): s3-us-west-2.amazonaws.com
2015-10-19 18:58:08,072 - MainThread - botocore.endpoint - DEBUG - Exception received when sending HTTP request.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 168, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
2015-10-19 18:58:08,073 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListObjects: calling handler <botocore.retryhandler.RetryHandler object at 0x7f3d9752ae10>
2015-10-19 18:58:08,073 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 183, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/commands.py", line 190, in __call__
    parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/s3/subcommands.py", line 336, in _run_main
    self._list_all_objects(bucket, key, parsed_args.page_size)
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/s3/subcommands.py", line 358, in _list_all_objects
    for response_data in iterator:
  File "/usr/local/lib/python2.7/dist-packages/botocore/paginate.py", line 83, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/paginate.py", line 155, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 301, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 375, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 111, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 140, in _send_request
    success_response, exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 206, in _needs_retry
    caught_exception=caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 250, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 265, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
TypeError: __str__ returned non-string (type Error)
2015-10-19 18:58:08,074 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

__str__ returned non-string (type Error)

```

**Comment by mtdowling** [comment]
I noticed this in the debug output: `if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6`. Are you able to connect to s3-us-west-2.amazonaws.com using something like cURL?

We will also look to see why the `__str__` error was raised.

**Comment by brendan-R** [comment]
Hm. I can cURL to other URLs fine, but for some reason I'm getting a 405...

```
$ curl -I -L http://s3-us-west-2.amazonaws.com                                     
HTTP/1.1 405 Method Not Allowed                                                         
x-amz-request-id: F59D170D6951BA64                                                      
x-amz-id-2: F5PCNBKEwqssl14wq4BW1plnSvC73jDFbMQ/PRTjw0XENk9sL1lSZcG4a6afqX+2r14/pk3VSuo= 
Allow: GET                                                                           
Content-Type: application/xml                                                          
Transfer-Encoding: chunked                                                             
Date: Tue, 20 Oct 2015 22:50:29 GMT                                                     
Server: AmazonS3         
```

**Comment by maksudi** [comment]
I'm having exactly the same problem on my Ubuntu
aws-cli/1.8.13 Python/2.7.9 Linux/3.19.0-31-generic

**Comment by brendan-R** [comment]
This may be entirely unrelated, but I've only encountered this problem after installing the anaconda Python distribution for scientific computing. @maksudi, your μ image hints at that sort of thing, are you also using anaconda?

**Comment by maksudi** [comment]
no, I'm installing all my python packages manually without anaconda. You're right I'm using all kinds of scientific packages. aws stopped working after another update through pip.

**Comment by brendan-R** [comment]
@mtdowling I understand that this may be difficult to diagnose. Can you recommend any general workarounds that I might use in the meantime?

**Comment by patanachai** [comment]
My current workaround is using install it using bundled installer instead of `pip`
http://docs.aws.amazon.com/cli/latest/userguide/installing.html#install-bundle-other-os

**Comment by brendan-R** [comment]
@patanachai, thank you! 🙆

**Comment by yzou** [comment]
I encountered the same issue and ssl certifacate verify failed issue, by review boto3 code, I found the REQUESTS_CA_BUNDLE is not set, so I fixed the both issue by setting it manually:

from boto3.session import Session
import os

# debian
os.environ['REQUESTS_CA_BUNDLE'] = os.path.join(
    '/etc/ssl/certs/',
    'ca-certificates.crt')
# centos
#   'ca-bundle.crt')

For aws-cli, I guess setting REQUESTS_CA_BUNDLE in ~/.bashrc will fix this issue (not tested because my aws-cli works without it)
REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt # ca-bundle.crt
export REQUESTS_CA_BUNDLE

**Comment by yangqch** [comment]
I have same issue on ubuntu 15.04
with awsebcli 3.6

**Comment by jolexa** [comment]
Just leaving a note here that I had the same error because the date was wrong on my system (sigh)

**Comment by rekhajoshm** [comment]
Hi, 
I do not have REQUESTS_CA_BUNDLE set, but normal flow works fine with latest aws-cli/botocore without __str__ error

```
$echo $REQUESTS_CA_BUNDLE

$aws s3 ls s3://<masked> --profile <masked> --debug
2016-01-23 12:27:22,402 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [GET]>
2016-01-23 12:27:22,402 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): <masked>.s3.amazonaws.com
2016-01-23 12:27:23,099 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "GET /?delimiter=%2F&prefix=20150604%2F&encoding-type=url HTTP/1.1" 200 None
…
2016-01-23 12:27:23,102 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListObjects: calling handler <botocore.retryhandler.RetryHandler object at 0x109dbf750>
2016-01-23 12:27:23,102 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2016-01-23 12:27:23,102 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.ListObjects: calling handler <function decode_list_object at 0x1094bcb18>
2016-01-23 12:27:23,102 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.ListObjects: calling handler <function enhance_error_msg at 0x1098ddf50>
2016-01-23 12:27:23,102 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.ListObjects: calling handler <awscli.errorhandler.ErrorHandler object at 0x10992e610>
2016-01-23 12:27:23,102 - MainThread - awscli.errorhandler - DEBUG - HTTP Response Code: 200

```

Updated date to a past date, but this time get more clear error message of RequestTimeTooSkewed, no __str__ error

```
$ date
Mon Jan  4 12:31:33 PST 2016

$aws s3 ls s3://<masked> --profile <masked> --debug
2016-01-04 12:31:36,645 - MainThread - botocore.parsers - DEBUG - Response body:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the request time and the current time is too large.</Message><RequestTime>Mon, 04 Jan 2016 20:31:36 GMT</RequestTime><ServerTime>2016-01-23T20:30:32Z</ServerTime><MaxAllowedSkewMilliseconds>900000</MaxAllowedSkewMilliseconds><RequestId><masked></RequestId><HostId><masked></HostId></Error>
2016-01-04 12:31:36,645 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListObjects: calling handler <botocore.retryhandler.RetryHandler object at 0x1043c1750>
2016-01-04 12:31:36,646 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2016-01-04 12:31:36,646 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.ListObjects: calling handler <function decode_list_object at 0x103abeb18>
2016-01-04 12:31:36,646 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.ListObjects: calling handler <function enhance_error_msg at 0x103edff50>
2016-01-04 12:31:36,646 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.ListObjects: calling handler <awscli.errorhandler.ErrorHandler object at 0x103f30610>
2016-01-04 12:31:36,646 - MainThread - awscli.errorhandler - DEBUG - HTTP Response Code: 403
2016-01-04 12:31:36,646 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
…
ClientError: A client error (RequestTimeTooSkewed) occurred when calling the ListObjects operation: The difference between the request time and the current time is too large.
2016-01-04 12:31:36,648 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255
```

Hence think it could be an older botocore issue, or some scientific package conflict as suggested earlier.thanks.

**Comment by JordonPhillips** [comment]
@brendan-r is this still an issue for you if you install outside of the bundled installer?

**Comment by brendan-r** [comment]
I'm afraid this was at least one computer ago! Thank you for your diligence. No need to keep the issue open for me.

**Comment by JordonPhillips** [comment]
If anybody is still having this issue, feel free to open a new issue report.
