### ISSUE TITLE
`apigateway::put-integration` command results in KeyError: u'http_method'

### ISSUE THREAD

**Issue by quiver** [aws/aws-cli#1595]
API http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-integration.html

There's no example code in the documentation, so my usage might be wrong. Anyway, this error occurs in client-side(AWS-CLI) before requesting to the server. 

```
$ aws apigateway put-integration --rest-api-id a --resource-id b --http-method GET --type AWS --uri c --debug
...
2015-10-28 01:25:07,764 - MainThread - botocore.endpoint - DEBUG - Setting apigateway timeout as (60, 60)
2015-10-28 01:25:07,764 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 184, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 369, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 538, in __call__
    call_parameters, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 662, in invoke
    **parameters)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 382, in _make_api_call
    api_params, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 423, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/validate.py", line 275, in serialize_to_request
    operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/serialize.py", line 404, in serialize_to_request
    partitioned['uri_path_kwargs'])
  File "/usr/local/lib/python2.7/site-packages/botocore/serialize.py", line 429, in _render_uri_template
    params[template_param])
KeyError: u'http_method'
2015-10-28 01:25:07,766 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255
```

**Comment by JordonPhillips** [comment]
Interesting. Looks like `http-method` isn't being passed along correctly. Thanks for reporting, we'll take a look

**Comment by JordonPhillips** [comment]
It looks like this is a bug in our model for API Gateway, which is generated upstream. I'll update the ticket when a fix is in the pipes.

**Comment by bradmurray** [comment]
I am seeing the same problem. I can put a method, but then I am stuck putting an integration so I have to do that via the web.

**Comment by bradmurray** [comment]
Any update on this? I have a bunch of deployment stuff to do and right now my only option is to do a create-resource, put-method and put-method-response for each node and http-method, but then I have to go into the web interface to do all what should be covered in the put-integration call. That goes across a couple of different pages in the UI and I have to do it for all 4 http methods. This bug is the one thing between me and fully scripted goodness.

**Comment by JordonPhillips** [comment]
We had a bug in our models that we get upstream, it will be fixed in the next release.

**Comment by bradmurray** [comment]
I installed the developer branch and the code that should be working is giving me the following error now:

A client error (BadRequestException) occurred when calling the PutIntegration operation: Enumeration value for HttpMethod must be non-empty

My call is:

```
aws apigateway put-integration --cli-input-json '{ "restApiId": "j7p2wzzb", "resourceId": "ueaxs", "httpMethod": "GET", "type": "AWS", "uri": "rn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:486357763964:function:servicetest/invocations", "requestTemplates": { "SessionID": "$input.params().header.SessionID", "URL": "$input.params().path.Res0/$input.params().path.ID0/$input.params().path.Res1/$input.params().path.ID1/$input.params().path.Res2", "HTTPMethod": "$context.httpMethod" }, "cacheNamespace": "ueaxs", "cacheKeyParameters": [] }'
```
