### ISSUE TITLE
datapipelines list-runs doesn't support comma-separated status

### ISSUE THREAD

**Issue by adamv** [aws/aws-cli#1644]
http://docs.aws.amazon.com/cli/latest/reference/datapipeline/list-runs.html

`You can combine statuses as a comma-separated list.`

Trying this gives me:

`A client error (InvalidRequestException) occurred when calling the QueryObjects operation: The request is missing a required value: Missing single value for field: @status in query`

I'm using version 1.9.7

**Comment by adamv** [comment]
I'm on Ubuntu, latest version of aws-cli:

```
$ aws datapipeline list-runs  --pipeline-id <my-pipeline-id> --status pending,waiting_on_dependencies --debug
2015-11-17 16:41:55,573 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.9.7 Python/3.4.3 Linux/3.13.0-68-generic botocore/1.3.7
2015-11-17 16:41:55,574 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['datapipeline', 'list-runs', '--pipeline-id', 'df-08548952JELMH7QAY869', '--status', 'pending,waiting_on_dependencies', '--debug']
2015-11-17 16:41:55,574 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7fa51ef8c598>
2015-11-17 16:41:55,574 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider at 0x7fa51f1d6950>
2015-11-17 16:41:55,574 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2015-11-17 16:41:55,578 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.datapipeline: calling handler <function register_retries_for_service at 0x7fa51fb56b70>
2015-11-17 16:41:55,578 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: datapipeline
2015-11-17 16:41:55,579 - MainThread - botocore.hooks - DEBUG - Event building-command-table.datapipeline: calling handler <function register_commands at 0x7fa51f27f730>
2015-11-17 16:41:55,579 - MainThread - botocore.hooks - DEBUG - Event building-command-table.datapipeline: calling handler <function add_waiters at 0x7fa51f1e8730>
2015-11-17 16:41:55,579 - MainThread - botocore.hooks - DEBUG - Event building-command-table.list-runs: calling handler <function add_waiters at 0x7fa51f1e8730>
2015-11-17 16:41:55,580 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.list-runs.status: calling handler <function uri_param at 0x7fa51f367d08>
2015-11-17 16:41:55,580 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.list-runs: calling handler <awscli.argprocess.ParamShorthand object at 0x7fa51f37b898>
2015-11-17 16:41:55,580 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.list-runs.schedule-interval: calling handler <function uri_param at 0x7fa51f367d08>
2015-11-17 16:41:55,580 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.list-runs.start-interval: calling handler <function uri_param at 0x7fa51f367d08>
2015-11-17 16:41:55,581 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.list-runs.pipeline-id: calling handler <function uri_param at 0x7fa51f367d08>
2015-11-17 16:41:55,581 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.list-runs: calling handler <awscli.argprocess.ParamShorthand object at 0x7fa51f37b898>
2015-11-17 16:41:55,581 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2015-11-17 16:41:55,581 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2015-11-17 16:41:55,581 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2015-11-17 16:41:55,582 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2015-11-17 16:41:55,584 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: datapipeline
2015-11-17 16:41:55,585 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.datapipeline: calling handler <function add_generate_presigned_url at 0x7fa51fba8400>
2015-11-17 16:41:55,587 - MainThread - botocore.endpoint - DEBUG - Setting datapipeline timeout as (60, 60)
2015-11-17 16:41:55,588 - MainThread - botocore.endpoint - DEBUG - Making request for <botocore.model.OperationModel object at 0x7fa51ed82c18> (verify_ssl=True) with params: {'query_string': '', 'body': b'{"sphere": "INSTANCE", "query": {"selectors": [{"fieldName": "@actualStartTime", "operator": {"type": "BETWEEN", "values": ["2015-11-14T00:41:55", "2015-11-18T00:41:55"]}}, {"fieldName": "@status", "operator": {"type": "EQ", "values": ["PENDING", "WAITING_ON_DEPENDENCIES"]}}]}, "pipelineId": "df-08548952JELMH7QAY869"}', 'method': 'POST', 'headers': {'X-Amz-Target': 'DataPipeline.QueryObjects', 'Content-Type': 'application/x-amz-json-1.1', 'User-Agent': 'aws-cli/1.9.7 Python/3.4.3 Linux/3.13.0-68-generic botocore/1.3.7'}, 'url_path': '/', 'url': 'https://datapipeline.us-east-1.amazonaws.com/'}
2015-11-17 16:41:55,588 - MainThread - botocore.hooks - DEBUG - Event request-created.datapipeline.QueryObjects: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fa51ed82e48>>
2015-11-17 16:41:55,588 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2015-11-17 16:41:55,588 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-amz-json-1.1
host:datapipeline.us-east-1.amazonaws.com
user-agent:aws-cli/1.9.7 Python/3.4.3 Linux/3.13.0-68-generic botocore/1.3.7
x-amz-date:20151118T004155Z
x-amz-target:DataPipeline.QueryObjects

content-type;host;user-agent;x-amz-date;x-amz-target
77a26825e5799fffb3231f426b47223c8583f6f769528e0d6caf703c7ff4f3cd
2015-11-17 16:41:55,588 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20151118T004155Z
20151118/us-east-1/datapipeline/aws4_request
45f23214f9778ff272d61ca199d6fd4a4929035c5ae62b409b3f48366f8a6840
2015-11-17 16:41:55,588 - MainThread - botocore.auth - DEBUG - Signature:
db048312d406e345c1e8f5b700848aa6d9e163ff9d7086cea899c06e8dda2214
2015-11-17 16:41:55,590 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2015-11-17 16:41:55,590 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): datapipeline.us-east-1.amazonaws.com
2015-11-17 16:41:56,150 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "POST / HTTP/1.1" 400 138
2015-11-17 16:41:56,150 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-requestid': '2d6f6b86-8d8d-11e5-8dff-e9c402366506', 'content-length': '138', 'nncoection': 'close', 'date': 'Wed, 18 Nov 2015 00:41:58 GMT', 'content-type': 'application/x-amz-json-1.1'}
2015-11-17 16:41:56,150 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"__type":"InvalidRequestException","message":"The request is missing a required value: Missing single value for field: @status in query"}'
2015-11-17 16:41:56,151 - MainThread - botocore.hooks - DEBUG - Event needs-retry.datapipeline.QueryObjects: calling handler <botocore.retryhandler.RetryHandler object at 0x7fa51ed6b438>
2015-11-17 16:41:56,151 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2015-11-17 16:41:56,151 - MainThread - botocore.hooks - DEBUG - Event after-call.datapipeline.QueryObjects: calling handler <awscli.errorhandler.ErrorHandler object at 0x7fa51f37b6d8>
2015-11-17 16:41:56,151 - MainThread - awscli.errorhandler - DEBUG - HTTP Response Code: 400
2015-11-17 16:41:56,151 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/awscli/clidriver.py", line 185, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python3.4/dist-packages/awscli/clidriver.py", line 376, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python3.4/dist-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/usr/local/lib/python3.4/dist-packages/awscli/customizations/datapipeline/__init__.py", line 347, in _run_main
    self._list_runs(parsed_args)
  File "/usr/local/lib/python3.4/dist-packages/awscli/customizations/datapipeline/__init__.py", line 383, in _list_runs
    object_ids = self._query_objects(parsed_args.pipeline_id, query)
  File "/usr/local/lib/python3.4/dist-packages/awscli/customizations/datapipeline/__init__.py", line 401, in _query_objects
    parsed = paginator.build_full_result()
  File "/usr/local/lib/python3.4/dist-packages/botocore/paginate.py", line 271, in build_full_result
    for response in self:
  File "/usr/local/lib/python3.4/dist-packages/botocore/paginate.py", line 85, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/botocore/paginate.py", line 157, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.4/dist-packages/botocore/client.py", line 391, in _make_api_call
    model=operation_model
  File "/usr/local/lib/python3.4/dist-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.4/dist-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/awscli/errorhandler.py", line 70, in __call__
    http_status_code=http_response.status_code)
awscli.errorhandler.ClientError: A client error (InvalidRequestException) occurred when calling the QueryObjects operation: The request is missing a required value: Missing single value for field: @status in query
2015-11-17 16:41:56,152 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

A client error (InvalidRequestException) occurred when calling the QueryObjects operation: The request is missing a required value: Missing single value for field: @status in query
```

**Comment by jamesls** [comment]
Interesting, we have a test case for this: https://github.com/aws/aws-cli/blame/develop/tests/unit/customizations/datapipeline/test_arg_serialize.py#L180-L204.  Let me follow up with the service team and track down what's going on.

**Comment by rajasaurus** [comment]
not sure why this would still be an issue. my query_objects method call succeeds with a single status ['FINISHED'] but throws the exception below when specifying more than one in comma separated list.  this is with boto3 haven't tested CLI.
awscli                    1.24.1
boto3                     1.23.1
botocore                  1.26.1

QUERY: {'selectors': [{'fieldName': '@actualStartTime', 'operator': {'type': 'BETWEEN', 'values': ['2022-05-17T00:55:14', '2022-05-17T03:55:14']}}, {'fieldName': '@status', 'operator': {'type': 'EQ', 'values': ['FINISHED', 'FAILED']}}]}

botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the QueryObjects operation: The request is missing a required value: Missing single value for field: @status in query
