### ISSUE TITLE
'CredentialResolver' object has no attribute 'get_provider'

### ISSUE THREAD

**Issue by dpicky** [aws/aws-cli#1709]
Since 1.9.15 get the following message on any AWS command even just 'aws help'

'CredentialResolver' object has no attribute 'get_provider'

**Comment by JordonPhillips** [comment]
I'm unable to reproduce, could you try adding in `--debug` and paste the response here?

**Comment by dpicky** [comment]
davidsmbpretina:~ David$ aws help --debug
2016-01-12 16:22:44,817 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.9.17 Python/2.7.10 Darwin/15.3.0 botocore/1.3.12
2016-01-12 16:22:44,817 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['help', '--debug']
2016-01-12 16:22:44,817 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x10f3e88c0>
2016-01-12 16:22:44,817 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x10f3bc0c8>
2016-01-12 16:22:44,817 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2016-01-12 16:22:44,818 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/Cellar/awscli/1.9.17/libexec/lib/python2.7/site-packages/awscli/clidriver.py", line 185, in main
    self._emit_session_event()
  File "/usr/local/Cellar/awscli/1.9.17/libexec/lib/python2.7/site-packages/awscli/clidriver.py", line 221, in _emit_session_event
    self.session.emit('session-initialized', session=self.session)
  File "/Library/Python/2.7/site-packages/botocore-1.3.12-py2.7.egg/botocore/session.py", line 675, in emit
    return self._events.emit(event_name, **kwargs)
  File "/Library/Python/2.7/site-packages/botocore-1.3.12-py2.7.egg/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore-1.3.12-py2.7.egg/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/usr/local/Cellar/awscli/1.9.17/libexec/lib/python2.7/site-packages/awscli/customizations/assumerole.py", line 39, in inject_assume_role_provider_cache
    provider = cred_chain.get_provider('assume-role')
AttributeError: 'CredentialResolver' object has no attribute 'get_provider'
2016-01-12 16:22:44,821 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

'CredentialResolver' object has no attribute 'get_provider'

**Comment by dpicky** [comment]
Found problem - it was using an older version of Boto, which updating sorting it out

**Comment by JordonPhillips** [comment]
@dpicky glad it worked out in the end, thanks for updating!
