### ISSUE TITLE
Exception when pulling file using --sse-c after it was uploaded with --sse

### ISSUE THREAD

**Issue by rhasson** [aws/aws-cli#1820]
First, upload a file to S3 with the --sse flag so that key generation is done by S3.  Second, if the user forgets they did that and tries to download the same file but this time supplies a customer specific key with the --sse-c flag, the CLI throws an exception and gives a very generic error message.

Ideally, the error message should be more intuitive.

mymac$ aws --profile me s3 cp test.js s3://mystuff/test4.js --sse AES256
upload: ./test.js to s3://royon-mystuff/test4.js
mymac$ aws --profile me s3 cp s3://mystuff/test4.js /tmp --sse-c AES256 --sse-c-key MTXnoA+709moo4b6iVFtXXY681NR2yFo --debug
2016-03-01 09:23:12,813 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.10.2 Python/2.7.10 Darwin/15.3.0 botocore/1.3.24
<omitted some output>
2016-03-01 09:23:13,013 - MainThread - botocore.parsers - DEBUG - Response body:
2016-03-01 09:23:13,013 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.HeadObject: calling handler <botocore.retryhandler.RetryHandler object at 0x104d161d0>
2016-03-01 09:23:13,013 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2016-03-01 09:23:13,013 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.HeadObject: calling handler <function enhance_error_msg at 0x1047569b0>
2016-03-01 09:23:13,013 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.HeadObject: calling handler <awscli.errorhandler.ErrorHandler object at 0x1047ce490>
2016-03-01 09:23:13,014 - MainThread - awscli.errorhandler - DEBUG - HTTP Response Code: 400
2016-03-01 09:23:13,014 - MainThread - awscli.customizations.s3.s3handler - DEBUG - Exception caught during task execution: A client error (400) occurred when calling the HeadObject operation: Bad Request
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/awscli/customizations/s3/s3handler.py", line 101, in call
    total_files, total_parts = self._enqueue_tasks(files)
  File "/Library/Python/2.7/site-packages/awscli/customizations/s3/s3handler.py", line 179, in _enqueue_tasks
    for filename in files:
  File "/Library/Python/2.7/site-packages/awscli/customizations/s3/fileinfobuilder.py", line 31, in call
    for file_base in files:
  File "/Library/Python/2.7/site-packages/awscli/customizations/s3/filegenerator.py", line 142, in call
    for src_path, extra_information in file_iterator:
  File "/Library/Python/2.7/site-packages/awscli/customizations/s3/filegenerator.py", line 314, in list_objects
    yield self._list_single_object(s3_path)
  File "/Library/Python/2.7/site-packages/awscli/customizations/s3/filegenerator.py", line 343, in _list_single_object
    response = self._client.head_object(**params)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 403, in _make_api_call
    model=operation_model, context=request_context
  File "/Library/Python/2.7/site-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/Library/Python/2.7/site-packages/awscli/errorhandler.py", line 70, in __call__
    http_status_code=http_response.status_code)
ClientError: A client error (400) occurred when calling the HeadObject operation: Bad Request

**Comment by kyleknap** [comment]
I am not sure if there is much the CLI can do. The 400 BadRequest is what S3 is sending back to us. The issue is that the only way we could improve the error message is by adding logic where if you provided sse-c related parameters and a 400 was received back then we add suggestions on what may have went wrong. The issue with this approach is that it is merely a guess. We do not know for sure why the request was bad and we cannot always assume it is because the user mistook sse-c for sse. Only the server can tell us why the request was bad. I would recommend reaching out to the developer forums to see if s3 can improve the error message: https://forums.aws.amazon.com/forum.jspa?forumID=24. Let us know if you have any more questions.

**Comment by rhasson** [comment]
@kyleknap Thanks for the response.  I agree if the error back from S3 is a 400 with no other detail there is not much that can be done.  I'm closing this issue and will check through the aws forums to see if there is a way to improve the API response details.
