### ISSUE TITLE
cli error EOF occurred in violation of protocol (_ssl.c:590)

### ISSUE THREAD

**Issue by amitmawkin** [aws/aws-cli#1831]
aws cli version

aws-cli/1.10.10 Python/2.7.11 Darwin/15.3.0 botocore/1.4.1

Debug trace

aws ec2 describe-instances --debug
2016-03-04 06:36:39,759 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.10.10 Python/2.7.11 Darwin/15.3.0 botocore/1.4.1
2016-03-04 06:36:39,760 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['ec2', 'describe-instances', '--debug']
2016-03-04 06:36:39,760 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x103b64578>
2016-03-04 06:36:39,760 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x103b36cf8>
2016-03-04 06:36:39,760 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2016-03-04 06:36:39,830 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.ec2: calling handler <function register_retries_for_service at 0x10320a410>
2016-03-04 06:36:39,830 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: ec2
2016-03-04 06:36:39,835 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <functools.partial object at 0x103bbbd60>
2016-03-04 06:36:39,835 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-instance
2016-03-04 06:36:39,835 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-volume
2016-03-04 06:36:39,835 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <function add_waiters at 0x103b3e410>
2016-03-04 06:36:39,838 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'dry-run', <awscli.arguments.BooleanArgument object at 0x104afb290>), (u'no-dry-run', <awscli.arguments.BooleanArgument object at 0x104afb2d0>), (u'instance-ids', <awscli.arguments.ListArgument object at 0x104afb310>), (u'filters', <awscli.arguments.ListArgument object at 0x104afb350>), (u'next-token', <awscli.arguments.CLIArgument object at 0x104afb390>), (u'max-results', <awscli.arguments.CLIArgument object at 0x104afb3d0>)])
2016-03-04 06:36:39,838 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler <function add_streaming_output_arg at 0x1035b87d0>
2016-03-04 06:36:39,838 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler <function _rename_arg at 0x103bc5c08>
2016-03-04 06:36:39,838 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler <function _rename_arg at 0x103bc5cf8>
2016-03-04 06:36:39,838 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler <functools.partial object at 0x103bbbe10>
2016-03-04 06:36:39,838 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler <function add_cli_input_json at 0x103b367d0>
2016-03-04 06:36:39,838 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler <function unify_paging_params at 0x1035e0a28>
2016-03-04 06:36:39,839 - MainThread - awscli.customizations.paginate - DEBUG - Modifying paging parameters for operation: DescribeInstances
2016-03-04 06:36:39,839 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler <function add_generate_skeleton at 0x103b36aa0>
2016-03-04 06:36:39,839 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.describe-instances: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x1035cfc10>>
2016-03-04 06:36:39,839 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.describe-instances: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x104afb850>>
2016-03-04 06:36:39,840 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.ec2.describe-instances: calling handler <functools.partial object at 0x104a52520>
2016-03-04 06:36:39,840 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.ec2.describe-instances: calling handler <functools.partial object at 0x104a52730>
2016-03-04 06:36:39,840 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-instances.dry-run: calling handler <function uri_param at 0x1034a29b0>
2016-03-04 06:36:39,841 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-instances.instance-ids: calling handler <function uri_param at 0x1034a29b0>
2016-03-04 06:36:39,841 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-instances.filters: calling handler <function uri_param at 0x1034a29b0>
2016-03-04 06:36:39,841 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-instances.next-token: calling handler <function uri_param at 0x1034a29b0>
2016-03-04 06:36:39,841 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-instances.max-results: calling handler <function uri_param at 0x1034a29b0>
2016-03-04 06:36:39,841 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-instances.cli-input-json: calling handler <function uri_param at 0x1034a29b0>
2016-03-04 06:36:39,841 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-instances.starting-token: calling handler <function uri_param at 0x1034a29b0>
2016-03-04 06:36:39,841 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-instances.page-size: calling handler <function uri_param at 0x1034a29b0>
2016-03-04 06:36:39,841 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-instances.max-items: calling handler <function uri_param at 0x1034a29b0>
2016-03-04 06:36:39,841 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-instances.generate-cli-skeleton: calling handler <function uri_param at 0x1034a29b0>
2016-03-04 06:36:39,841 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.describe-instances: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x104afb850>>
2016-03-04 06:36:39,841 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.describe-instances: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x1035cfc10>>
2016-03-04 06:36:39,842 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2016-03-04 06:36:39,842 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2016-03-04 06:36:39,842 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2016-03-04 06:36:39,842 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2016-03-04 06:36:39,848 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: ec2
2016-03-04 06:36:39,854 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.ec2: calling handler <function add_generate_presigned_url at 0x1031e61b8>
2016-03-04 06:36:39,856 - MainThread - botocore.client - DEBUG - Assuming an endpoint for ec2, us-east-1f: https://ec2.us-east-1f.amazonaws.com
2016-03-04 06:36:39,857 - MainThread - botocore.endpoint - DEBUG - Setting ec2 timeout as (60, 60)
2016-03-04 06:36:39,858 - MainThread - botocore.endpoint - DEBUG - Making request for <botocore.model.OperationModel object at 0x104bf5e10> (verify_ssl=True) with params: {'body': {'Action': u'DescribeInstances', 'Version': u'2015-10-01'}, 'url': 'https://ec2.us-east-1f.amazonaws.com/', 'headers': {'User-Agent': 'aws-cli/1.10.10 Python/2.7.11 Darwin/15.3.0 botocore/1.4.1'}, 'query_string': '', 'url_path': '/', 'method': u'POST'}
2016-03-04 06:36:39,858 - MainThread - botocore.hooks - DEBUG - Event request-created.ec2.DescribeInstances: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x104c2a690>>
2016-03-04 06:36:39,859 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2016-03-04 06:36:39,859 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

host:ec2.us-east-1f.amazonaws.com
user-agent:aws-cli/1.10.10 Python/2.7.11 Darwin/15.3.0 botocore/1.4.1
x-amz-date:20160304T113639Z

host;user-agent;x-amz-date
7371039207d67c4be2f6abbb39dcd980a6861eef125be9b5437a5f5308278f8c
2016-03-04 06:36:39,859 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20160304T113639Z
20160304/us-east-1f/ec2/aws4_request
1e9c9111149832001733433255f5c4a36007eead31e46aa625ff98ceb25d9e74
2016-03-04 06:36:39,859 - MainThread - botocore.auth - DEBUG - Signature:
936e6eeb52031dc22326f271cc48ae657c44bbd90d8ac83e86fba39d930de768
2016-03-04 06:36:39,861 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2016-03-04 06:36:39,861 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): ec2.us-east-1f.amazonaws.com
2016-03-04 06:36:40,083 - MainThread - botocore.endpoint - DEBUG - ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/endpoint.py", line 174, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
2016-03-04 06:36:40,083 - MainThread - botocore.hooks - DEBUG - Event needs-retry.ec2.DescribeInstances: calling handler <botocore.retryhandler.RetryHandler object at 0x1035cfcd0>
2016-03-04 06:36:40,083 - MainThread - botocore.retryhandler - DEBUG - retry needed, retryable exception caught: EOF occurred in violation of protocol (_ssl.c:590)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 265, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
2016-03-04 06:36:40,084 - MainThread - botocore.retryhandler - DEBUG - Retry needed, action of: 0.691270257442
2016-03-04 06:36:40,084 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.691270257442 seconds
2016-03-04 06:36:40,779 - MainThread - botocore.hooks - DEBUG - Event request-created.ec2.DescribeInstances: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x104c2a690>>
2016-03-04 06:36:40,780 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2016-03-04 06:36:40,780 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

host:ec2.us-east-1f.amazonaws.com
user-agent:aws-cli/1.10.10 Python/2.7.11 Darwin/15.3.0 botocore/1.4.1
x-amz-date:20160304T113640Z

host;user-agent;x-amz-date
7371039207d67c4be2f6abbb39dcd980a6861eef125be9b5437a5f5308278f8c
2016-03-04 06:36:40,781 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20160304T113640Z
20160304/us-east-1f/ec2/aws4_request
30d46ad67dfc0778abbc23e58f64df211441443bbd0720bd71e19908b23aacee
2016-03-04 06:36:40,781 - MainThread - botocore.auth - DEBUG - Signature:
eebfb253e2dc0e37cf6da43bda49e2e7587f7a9106ca42591e6b5421ed5a435f
2016-03-04 06:36:40,781 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2016-03-04 06:36:40,782 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (2): ec2.us-east-1f.amazonaws.com
2016-03-04 06:36:41,050 - MainThread - botocore.endpoint - DEBUG - ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/endpoint.py", line 174, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
2016-03-04 06:36:41,051 - MainThread - botocore.hooks - DEBUG - Event needs-retry.ec2.DescribeInstances: calling handler <botocore.retryhandler.RetryHandler object at 0x1035cfcd0>
2016-03-04 06:36:41,051 - MainThread - botocore.retryhandler - DEBUG - retry needed, retryable exception caught: EOF occurred in violation of protocol (_ssl.c:590)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 265, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
2016-03-04 06:36:41,051 - MainThread - botocore.retryhandler - DEBUG - Retry needed, action of: 0.273502392849
2016-03-04 06:36:41,061 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.273502392849 seconds
2016-03-04 06:36:41,340 - MainThread - botocore.hooks - DEBUG - Event request-created.ec2.DescribeInstances: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x104c2a690>>
2016-03-04 06:36:41,341 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2016-03-04 06:36:41,341 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

host:ec2.us-east-1f.amazonaws.com
user-agent:aws-cli/1.10.10 Python/2.7.11 Darwin/15.3.0 botocore/1.4.1
x-amz-date:20160304T113641Z

host;user-agent;x-amz-date
7371039207d67c4be2f6abbb39dcd980a6861eef125be9b5437a5f5308278f8c
2016-03-04 06:36:41,341 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20160304T113641Z
20160304/us-east-1f/ec2/aws4_request
99c6dd3550929e7f0cf1f3a79b7202bba2de3ac783b6e877912860fc046114b1
2016-03-04 06:36:41,341 - MainThread - botocore.auth - DEBUG - Signature:
9eca6e75cfc75e381de168a9bafec1fedda39c97f08160ae2ab3cd8b3293378b
2016-03-04 06:36:41,341 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2016-03-04 06:36:41,342 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (3): ec2.us-east-1f.amazonaws.com
2016-03-04 06:36:41,562 - MainThread - botocore.endpoint - DEBUG - ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/endpoint.py", line 174, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
2016-03-04 06:36:41,562 - MainThread - botocore.hooks - DEBUG - Event needs-retry.ec2.DescribeInstances: calling handler <botocore.retryhandler.RetryHandler object at 0x1035cfcd0>
2016-03-04 06:36:41,562 - MainThread - botocore.retryhandler - DEBUG - retry needed, retryable exception caught: EOF occurred in violation of protocol (_ssl.c:590)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 265, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
2016-03-04 06:36:41,562 - MainThread - botocore.retryhandler - DEBUG - Retry needed, action of: 0.897072821114
2016-03-04 06:36:41,572 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.897072821114 seconds
2016-03-04 06:36:42,470 - MainThread - botocore.hooks - DEBUG - Event request-created.ec2.DescribeInstances: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x104c2a690>>
2016-03-04 06:36:42,471 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2016-03-04 06:36:42,471 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

host:ec2.us-east-1f.amazonaws.com
user-agent:aws-cli/1.10.10 Python/2.7.11 Darwin/15.3.0 botocore/1.4.1
x-amz-date:20160304T113642Z

host;user-agent;x-amz-date
7371039207d67c4be2f6abbb39dcd980a6861eef125be9b5437a5f5308278f8c
2016-03-04 06:36:42,471 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20160304T113642Z
20160304/us-east-1f/ec2/aws4_request
b3c06df804541355711dd0ed35db2d839fcc6b09d1f8ce52dcf543b09f080d24
2016-03-04 06:36:42,472 - MainThread - botocore.auth - DEBUG - Signature:
84979a5d707016b6844209d429cb10e47d95699fde45b41b80b242c547f80c47
2016-03-04 06:36:42,473 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2016-03-04 06:36:42,473 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (4): ec2.us-east-1f.amazonaws.com
2016-03-04 06:36:42,721 - MainThread - botocore.endpoint - DEBUG - ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/endpoint.py", line 174, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
2016-03-04 06:36:42,721 - MainThread - botocore.hooks - DEBUG - Event needs-retry.ec2.DescribeInstances: calling handler <botocore.retryhandler.RetryHandler object at 0x1035cfcd0>
2016-03-04 06:36:42,721 - MainThread - botocore.retryhandler - DEBUG - retry needed, retryable exception caught: EOF occurred in violation of protocol (_ssl.c:590)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 265, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
2016-03-04 06:36:42,721 - MainThread - botocore.retryhandler - DEBUG - Retry needed, action of: 5.87429841519
2016-03-04 06:36:42,724 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 5.87429841519 seconds
2016-03-04 06:36:48,599 - MainThread - botocore.hooks - DEBUG - Event request-created.ec2.DescribeInstances: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x104c2a690>>
2016-03-04 06:36:48,600 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2016-03-04 06:36:48,600 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

host:ec2.us-east-1f.amazonaws.com
user-agent:aws-cli/1.10.10 Python/2.7.11 Darwin/15.3.0 botocore/1.4.1
x-amz-date:20160304T113648Z

host;user-agent;x-amz-date
7371039207d67c4be2f6abbb39dcd980a6861eef125be9b5437a5f5308278f8c
2016-03-04 06:36:48,600 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20160304T113648Z
20160304/us-east-1f/ec2/aws4_request
96f04407292d45d8eb72c059b1e1493c79681cda06bcef7cd8964b6d2d99a512
2016-03-04 06:36:48,600 - MainThread - botocore.auth - DEBUG - Signature:
22c5051a5cd099ba57caaca7dc6a5188158f3dc2a47de54e6b09ea95b259b86e
2016-03-04 06:36:48,601 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2016-03-04 06:36:48,601 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (5): ec2.us-east-1f.amazonaws.com
2016-03-04 06:36:48,836 - MainThread - botocore.endpoint - DEBUG - ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/endpoint.py", line 174, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
2016-03-04 06:36:48,836 - MainThread - botocore.hooks - DEBUG - Event needs-retry.ec2.DescribeInstances: calling handler <botocore.retryhandler.RetryHandler object at 0x1035cfcd0>
2016-03-04 06:36:48,837 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/awscli/clidriver.py", line 186, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/awscli/clidriver.py", line 377, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/awscli/clidriver.py", line 546, in __call__
    call_parameters, parsed_globals)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/awscli/clidriver.py", line 671, in invoke
    self._display_response(operation_name, response, parsed_globals)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/awscli/clidriver.py", line 680, in _display_response
    formatter(command_name, response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/awscli/formatter.py", line 68, in __call__
    response_data = response.build_full_result()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/paginate.py", line 287, in build_full_result
    for response in self:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/paginate.py", line 99, in __iter__
    response = self._make_request(current_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/paginate.py", line 171, in _make_request
    return self._method(**current_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/client.py", line 228, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/client.py", line 475, in _make_api_call
    operation_model, request_dict)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/endpoint.py", line 117, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/endpoint.py", line 146, in _send_request
    success_response, exception):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/endpoint.py", line 219, in _needs_retry
    caught_exception=caught_exception)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 250, in __call__
    caught_exception)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 273, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
2016-03-04 06:36:48,838 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

EOF occurred in violation of protocol (_ssl.c:590)

**Comment by amitmawkin** [comment]
wrong region..
