### ISSUE TITLE
ImportError: cannot import name StringShape

### ISSUE THREAD

**Issue by jingpengwu** [aws/aws-cli#1880]
After updating the awscli using `pip install --upgrade awscli`
I ran the following command to login
`aws ecr get-login --region us-east-1`

error:
```
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 32, in <module>
    from awscli.help import ProviderHelpCommand
  File "/usr/local/lib/python2.7/dist-packages/awscli/help.py", line 26, in <module>
    from awscli.clidocs import ProviderDocumentEventHandler
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidocs.py", line 17, in <module>
    from botocore.model import StringShape
ImportError: cannot import name StringShape
```

**Comment by jamesls** [comment]
Looks like botocore didn't update for some reason.  What's the output of `aws --version`?

You can also try upgrading botocore as well (though it shouldn't be needed): `pip install --upgrade botocore`.

**Comment by jingpengwu** [comment]
probabely, the upgrade of botocore has some errors in the end.

```
pip install --upgrade botocore
Downloading/unpacking botocore from https://pypi.python.org/packages/py2.py3/b/botocore/botocore-1.4.8-py2.py3-none-any.whl#md5=d0acd7cdb84c82541a618e08959a4cba
  Downloading botocore-1.4.8-py2.py3-none-any.whl (2.3MB): 2.3MB downloaded
Requirement already up-to-date: docutils>=0.10 in ./libs/anaconda/lib/python2.7/site-packages (from botocore)
Downloading/unpacking jmespath>=0.7.1,<1.0.0 from https://pypi.python.org/packages/py2.py3/j/jmespath/jmespath-0.9.0-py2.py3-none-any.whl#md5=1befa189c91def5afa50606647535881 (from botocore)
  Downloading jmespath-0.9.0-py2.py3-none-any.whl
Downloading/unpacking python-dateutil>=2.1,<3.0.0 from https://pypi.python.org/packages/any/p/python-dateutil/python_dateutil-2.5.2-py2.py3-none-any.whl#md5=50283d17f1a5c5919886af456afe4db1 (from botocore)
  Downloading python_dateutil-2.5.2-py2.py3-none-any.whl (201kB): 201kB downloaded
Downloading/unpacking six>=1.5 from https://pypi.python.org/packages/py2.py3/s/six/six-1.10.0-py2.py3-none-any.whl#md5=3ab558cf5d4f7a72611d59a81a315dc8 (from python-dateutil>=2.1,<3.0.0->botocore)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: botocore, jmespath, python-dateutil, six
  Found existing installation: botocore 1.1.0
    Uninstalling botocore:
      Successfully uninstalled botocore
  Rolling back uninstall of botocore
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 671, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 901, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 200, in clobber
    shutil.move(srcfile, destfile)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/botocore/endpoint.pyc'

Storing debug log for failure in /tmp/tmpTayXj9
```

```
aws --version
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 32, in <module>
    from awscli.help import ProviderHelpCommand
  File "/usr/local/lib/python2.7/dist-packages/awscli/help.py", line 26, in <module>
    from awscli.clidocs import ProviderDocumentEventHandler
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidocs.py", line 17, in <module>
    from botocore.model import StringShape
ImportError: cannot import name StringShape
```

I did my work in an mac laptop, and it works. So, should be my local update problem.

**Comment by jamesls** [comment]
Can you show the complete output of `sudo pip install --upgrade awscli`?  It will show us exactly where it's failing in the install.

**Comment by jingpengwu** [comment]
the install of awscli looks good though.
```
sudo pip install --upgrade awscli
Downloading/unpacking awscli
  Downloading awscli-1.10.17-py2.py3-none-any.whl (919kB): 919kB downloaded
Requirement already up-to-date: docutils>=0.10 in /usr/local/lib/python2.7/dist-packages (from awscli)
Requirement already up-to-date: botocore==1.4.8 in /usr/local/lib/python2.7/dist-packages (from awscli)
Requirement already up-to-date: rsa>=3.1.2,<=3.3.0 in /usr/local/lib/python2.7/dist-packages (from awscli)
Requirement already up-to-date: colorama>=0.2.5,<=0.3.3 in /usr/local/lib/python2.7/dist-packages (from awscli)
Requirement already up-to-date: s3transfer==0.0.1 in /usr/local/lib/python2.7/dist-packages (from awscli)
Installing collected packages: awscli
Successfully installed awscli
Cleaning up...

```

**Comment by jingpengwu** [comment]
all of the aws command are not functional...
```
aws
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 32, in <module>
    from awscli.help import ProviderHelpCommand
  File "/usr/local/lib/python2.7/dist-packages/awscli/help.py", line 26, in <module>
    from awscli.clidocs import ProviderDocumentEventHandler
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidocs.py", line 17, in <module>
    from botocore.model import StringShape
ImportError: cannot import name StringShape
```

**Comment by jingpengwu** [comment]
I fixed this issue by downloading the source and build.
