### ISSUE TITLE
Getting: "A client error (InvalidParameters) occurred when calling the CreateAssociation operation: None"

### ISSUE THREAD

**Issue by sawarkarma** [aws/aws-cli#1903]
Hi,

I am trying to run below command:
`aws ssm create-association --instance-id i-2aaaiiiii --name "My_Custom_Config_File" --region us-east-1 --debug`

and getting below error,

```
2016-04-11 13:33:03,164 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.9.15 Python/2.7.9 Windows/2012Server botocore/1.3.15

2016-04-11 13:33:03,165 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['ssm', 'create-association', '--instance-id', 'i-2aXXXXX', '--name', 'My_Custom_Config_File1', '--region', 'us-east-1', '--debug']

2016-04-11 13:33:03,165 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler 

2016-04-11 13:33:03,167 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler 

2016-04-11 13:33:03,167 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.

2016-04-11 13:33:03,178 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.ssm: calling handler
 
2016-04-11 13:33:03,180 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: ssm

2016-04-11 13:33:03,181 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ssm: calling handler
 
2016-04-11 13:33:03,183 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'name', ), (u'instance-id', ments.CLIArgument object at 0x0000000003C2C4E0>), (u'parameters', )])

2016-04-11 13:33:03,186 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ssm.create-association: calling handler 0003146518>

2016-04-11 13:33:03,191 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ssm.create-association: calling handler 3AC8>

2016-04-11 13:33:03,197 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ssm.create-association: calling handler 713C8>

2016-04-11 13:33:03,197 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ssm.create-association: calling handler 3773E48>

2016-04-11 13:33:03,200 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ssm.create-association: calling handler nt.override_required_args of >

2016-04-11 13:33:03,201 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ssm.create-association: calling handler >

2016-04-11 13:33:03,204 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ssm.create-association.name: calling handler

2016-04-11 13:33:03,206 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.ssm.create-association: calling handler 031682E8>

2016-04-11 13:33:03,207 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'My_Custom_Config_File1' for parameter "name": u'My_Custom_Config_File1'

2016-04-11 13:33:03,207 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ssm.create-association.instance-id: calling handler 

2016-04-11 13:33:03,209 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.ssm.create-association: calling handler 031682E8>

2016-04-11 13:33:03,210 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'i-2aXXXXX' for parameter "instance_id": u'i-XXXXXX'
2016-04-11 13:33:03,211 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ssm.create-association.parameters: calling handler 
2016-04-11 13:33:03,211 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ssm.create-association.cli-input-json: calling handler

2016-04-11 13:33:03,213 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ssm.create-association.generate-cli-skeleton: calling handler 12BDD8>

2016-04-11 13:33:03,214 - MainThread - botocore.hooks - DEBUG - Event calling-command.ssm.create-association: calling handler n_skeleton of >

2016-04-11 13:33:03,221 - MainThread - botocore.hooks - DEBUG - Event calling-command.ssm.create-association: calling handler ers of >

2016-04-11 13:33:03,226 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env

2016-04-11 13:33:03,226 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role

2016-04-11 13:33:03,227 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file

2016-04-11 13:33:03,229 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials

2016-04-11 13:33:03,230 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: ssm

2016-04-11 13:33:03,233 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.ssm: calling handler 

2016-04-11 13:33:03,239 - MainThread - botocore.endpoint - DEBUG - Setting ssm timeout as (60, 60)

2016-04-11 13:33:03,240 - MainThread - botocore.endpoint - DEBUG - Making request for (verify_ssl=True) with params: {'

body': '{"InstanceId": "i-2aXXXXX", "Name": "My_Custom_Config_File1"}', 'url': u'https://ssm.us-east-1.amazonaws.com/', 'headers': {'User-Agent': 'aws-cli/1.9.15 Python/2.7.9 Wind

ows/2012Server botocore/1.3.15', 'Content-Type': u'application/x-amz-json-1.1', 'X-Amz-Target': u'AmazonSSM.CreateAssociation'}, 'query_string': '', 'url_path': '/', 'method': u'PO
ST'}
2016-04-11 13:33:03,242 - MainThread - botocore.hooks - DEBUG - Event request-created.ssm.CreateAssociation: calling handler s.RequestSigner object at 0x0000000003C74390>>

2016-04-11 13:33:03,243 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.


2016-04-11 13:33:03,244 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/
content-type:application/x-amz-json-1.1
host:ssm.us-east-1.amazonaws.com
user-agent:aws-cli/1.9.15 Python/2.7.9 Windows/2012Server botocore/1.3.15
x-amz-date:20160411T133303Z`enter code here`
x-amz-target:AmazonSSM.CreateAssociation

content-type;host;user-agent;x-amz-date;x-amz-target
32b499e84990d7dfa350311f574db29b7f6b8ab18624cedddde38ec3e236a763
2016-04-11 13:33:03,263 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20160411T133303Z
20160411/us-east-1/ssm/aws4_request
5794f606f60fd7b3e645718d31c3e107c215125e7014e6c6e982dbb137db966a

2016-04-11 13:33:03,267 - MainThread - botocore.auth - DEBUG - Signature:
62986027983e9234120f41367beb87af3bf131eee07de9a8228f8ff8ea9e3e1d

2016-04-11 13:33:03,270 - MainThread - botocore.endpoint - DEBUG - Sending http request: 

2016-04-11 13:33:03,272 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): ssm.us-east-1.amazonaws.com

2016-04-11 13:33:03,979 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "POST / HTTP/1.1" 400 30

2016-04-11 13:33:03,980 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-requestid': 'ec72fe60-ffe9-11e5-bd45-09ebb6aa3b78', 'date': 'Mon, 11 Apr 2016 13:33:06
GMT', 'content-length': '30', 'content-type': 'application/x-amz-json-1.1', 'nncoection': 'close'}
2016-04-11 13:33:03,980 - MainThread - botocore.parsers - DEBUG - Response body:
{"type":"InvalidParameters"}

2016-04-11 13:33:03,982 - MainThread - botocore.hooks - DEBUG - Event needs-retry.ssm.CreateAssociation: calling handler 506D8>

2016-04-11 13:33:03,983 - MainThread - botocore.retryhandler - DEBUG - No retry needed.

2016-04-11 13:33:03,984 - MainThread - botocore.hooks - DEBUG - Event after-call.ssm.CreateAssociation: calling handler 20>

2016-04-11 13:33:03,986 - MainThread - awscli.errorhandler - DEBUG - HTTP Response Code: 400

2016-04-11 13:33:03,986 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
File "awscli\clidriver.pyc", line 186, in main
File "awscli\clidriver.pyc", line 377, in __call
File "awscli\clidriver.pyc", line 546, in call
File "awscli\clidriver.pyc", line 670, in invoke
File "botocore\client.pyc", line 310, in api_call
File "botocore\client.pyc", line 392, in make_api_call
File "botocore\hooks.pyc", line 226, in emit
File "botocore\hooks.pyc", line 209, in _emit
File "awscli\errorhandler.pyc", line 70, in __call
ClientError: A client error (InvalidParameters) occurred when calling the CreateAssociation operation: None
2016-04-11 13:33:03,999 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

A client error (InvalidParameters) occurred when calling the CreateAssociation operation: None
```

Please suggest solution, i am trying to find which parameter i am missing........

Thanks and Regards,
Mahendra

**Comment by kyleknap** [comment]
Maybe your document requires some runtime parameters as provided by ``--parameters``? The error returned by the service is not too informative. I would recommend reaching out to the [forums](https://forums.aws.amazon.com/tags/ssm) to see what may possibly be going wrong and see if the error message can be improved.

**Comment by sawarkarma** [comment]
How to know which parameter is missing in this command

**Comment by jamesls** [comment]
The best course of action would be to ask on the [AWS forums](https://forums.aws.amazon.com/forum.jspa?forumID=30&start=0).  The service team will be better able to help you out with API questions.  As Kyle mentioned, the CLI is echoing back the error message from the service, so the CLI doesn't now what information is missing.  Someone on the service team will be able to help you with this.  Closing in favor of forum issue.
