### ISSUE TITLE
[Bug] Cannot Assume Role from EC2 IAM Role

### ISSUE THREAD

**Issue by mvastola** [aws/aws-cli#1919]
Theoretically, it should be entirely possible to use `aws-cli` on an EC2 instance with an assigned IAM role/instance profile and, from this assigned IAM role, assume an entirely different role (specified by name in the `credentials` file).

For example, I have `aws-cli` configured thusly:
##### `~/.aws/config`:
```
[default]
region = us-east-1
output = table

[profile ec2-role]
region = us-east-1
output = text
```
##### `~/.aws/credentials`:
```
[default]
role_arn = arn:aws:iam::XXXXXXXXXXXX:role/SpecialRole
source_profile = ec2-role

[ec2-role]
; This Space Intentionally Left Blank
```

The profile `ec2-role`, as would be expected, works perfectly and assumes the role from the instance metadata. For example:
```
user@server:~$ aws --profile ec2-role --query Arn sts get-caller-identity 
arn:aws:sts::XXXXXXXXXXXX:assumed-role/EC2AssignedRole/i-YYYYYYYY
```

When I try to use the default profile though (for ***any*** command), I immediately run into trouble:
```
user@server:~$ aws sts get-caller-identity 

'aws_access_key_id'
```
This output -- a blank line followed by `aws_access_key_id` in single quotes -- is consistent no matter what CLI command I run, as long the command (and all parameters, if required) parse correctly, without regard to the permissions of the permissions delegated to the `role_arn` set for the default profile.

When adding the debug switch to the above command, the output is as follows:

```
user@server:~$ aws --debug sts get-caller-identity 
2016-04-14 23:50:33,784 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.10.20 Python/3.4.3+ Linux/4.2.0-35-generic botocore/1.4.11
2016-04-14 23:50:33,784 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', 'sts', 'get-caller-identity']
2016-04-14 23:50:33,785 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7fe91ab067b8>
2016-04-14 23:50:33,785 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7fe91aadc510>
2016-04-14 23:50:33,785 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2016-04-14 23:50:33,789 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.sts: calling handler <function register_retries_for_service at 0x7fe91b4442f0>
2016-04-14 23:50:33,789 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: sts
2016-04-14 23:50:33,790 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sts: calling handler <function add_waiters at 0x7fe91aadc950>
2016-04-14 23:50:33,791 - MainThread - awscli.clidriver - DEBUG - OrderedDict()
2016-04-14 23:50:33,792 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function add_streaming_output_arg at 0x7fe91ac679d8>
2016-04-14 23:50:33,792 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function add_cli_input_json at 0x7fe91ab2de18>
2016-04-14 23:50:33,792 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function unify_paging_params at 0x7fe91ac85d90>
2016-04-14 23:50:33,793 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function add_generate_skeleton at 0x7fe91aadc1e0>
2016-04-14 23:50:33,794 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sts.get-caller-identity: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7fe91a6152e8>>
2016-04-14 23:50:33,794 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sts.get-caller-identity: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fe91a6153c8>>
2016-04-14 23:50:33,794 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sts.get-caller-identity.cli-input-json: calling handler <function uri_param at 0x7fe91ac51510>
2016-04-14 23:50:33,795 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sts.get-caller-identity.generate-cli-skeleton: calling handler <function uri_param at 0x7fe91ac51510>
2016-04-14 23:50:33,795 - MainThread - botocore.hooks - DEBUG - Event calling-command.sts.get-caller-identity: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fe91a6153c8>>
2016-04-14 23:50:33,795 - MainThread - botocore.hooks - DEBUG - Event calling-command.sts.get-caller-identity: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7fe91a6152e8>>
2016-04-14 23:50:33,795 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2016-04-14 23:50:33,795 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2016-04-14 23:50:33,795 - MainThread - botocore.credentials - DEBUG - Retrieving credentials via AssumeRole.
2016-04-14 23:50:33,795 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/awscli/clidriver.py", line 186, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python3.4/dist-packages/awscli/clidriver.py", line 379, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python3.4/dist-packages/awscli/clidriver.py", line 548, in __call__
    call_parameters, parsed_globals)
  File "/usr/local/lib/python3.4/dist-packages/awscli/clidriver.py", line 665, in invoke
    verify=parsed_globals.verify_ssl)
  File "/usr/local/lib/python3.4/dist-packages/botocore/session.py", line 805, in create_client
    credentials = self.get_credentials()
  File "/usr/local/lib/python3.4/dist-packages/botocore/session.py", line 439, in get_credentials
    'credential_provider').load_credentials()
  File "/usr/local/lib/python3.4/dist-packages/botocore/credentials.py", line 1012, in load_credentials
    creds = provider.load()
  File "/usr/local/lib/python3.4/dist-packages/botocore/credentials.py", line 779, in load
    return self._load_creds_via_assume_role()
  File "/usr/local/lib/python3.4/dist-packages/botocore/credentials.py", line 798, in _load_creds_via_assume_role
    creds, response = self._retrieve_temp_credentials()
  File "/usr/local/lib/python3.4/dist-packages/botocore/credentials.py", line 900, in _retrieve_temp_credentials
    client = self._create_client_from_config(config)
  File "/usr/local/lib/python3.4/dist-packages/botocore/credentials.py", line 891, in _create_client_from_config
    'sts', aws_access_key_id=source_cred_values['aws_access_key_id'],
KeyError: 'aws_access_key_id'
2016-04-14 23:50:33,796 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

'aws_access_key_id'

```

**Comment by kyleknap** [comment]
We have an open issue tracking this: https://github.com/aws/aws-cli/issues/1390. In short, we do not support the ability to declare an ec2 instance role as the source profile, but it is something we would like to add as it has been requested by many people in the linked thread.

Closing issue. Let's track the conversation in the issue I linked.

**Comment by mvastola** [comment]
Oops. Didn't know this was already requested. Good call.
Normally I'd argue that this should still be considered a bug at least in that this error condition isn't handled gracefully, but as I see a PR has already been made that implements the feature, this would be superflouous.
