### ISSUE TITLE
aws-cli fails to install from tarbar due to AssertionError : assert len(cli_tarball) == 1

### ISSUE THREAD

**Issue by ssbarnea** [aws/aws-cli#1920]
On Ubuntu 15.04 (vivid), if you try to install awscli using the tarbal you may endup getting a failure
```
curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
unzip -o awscli-bundle.zip
./awscli-bundle/install -b ~/bin/aws
```
Here is the error:
```
+ curl https://s3.amazonaws.com/aws-cli/awscli-bundle.zip -o awscli-bundle.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6680k  100 6680k    0     0  1174k      0  0:00:05  0:00:05 --:--:-- 1518k
+ unzip -o awscli-bundle.zip
Archive:  awscli-bundle.zip
  inflating: awscli-bundle/install
  inflating: awscli-bundle/packages/jmespath-0.9.0.tar.gz
  inflating: awscli-bundle/packages/rsa-3.3.tar.gz
  inflating: awscli-bundle/packages/python-dateutil-2.5.2.tar.gz
  inflating: awscli-bundle/packages/simplejson-3.3.0.tar.gz
  inflating: awscli-bundle/packages/s3transfer-0.0.1.tar.gz
  inflating: awscli-bundle/packages/ordereddict-1.1.tar.gz
  inflating: awscli-bundle/packages/futures-3.0.5.tar.gz
  inflating: awscli-bundle/packages/colorama-0.3.3.tar.gz
  inflating: awscli-bundle/packages/docutils-0.12.tar.gz
  inflating: awscli-bundle/packages/argparse-1.2.1.tar.gz
  inflating: awscli-bundle/packages/awscli-1.10.20.tar.gz
  inflating: awscli-bundle/packages/botocore-1.4.11.tar.gz
  inflating: awscli-bundle/packages/pyasn1-0.1.9.tar.gz
  inflating: awscli-bundle/packages/virtualenv-13.0.3.tar.gz
  inflating: awscli-bundle/packages/six-1.10.0.tar.gz
+ ./awscli-bundle/install -b /root/bin/aws
Running cmd: /usr/bin/python virtualenv.py --python /usr/bin/python /root/.local/lib/aws
Traceback (most recent call last):
  File "./awscli-bundle/install", line 138, in <module>
    main()
  File "./awscli-bundle/install", line 129, in main
    pip_install_packages(opts.install_dir)
  File "./awscli-bundle/install", line 92, in pip_install_packages
    assert len(cli_tarball) == 1
AssertionError
```

**Comment by kyleknap** [comment]
That is strange. I tried it on an ubuntu EC2 instance and I had no issues installing it. According to the [line](https://github.com/aws/aws-cli/blob/develop/scripts/install#L92) that it is erroring out on, it cannot find the awscli tarball, but in your output, I see the tarball getting extracted when you unzip it.

Could you possibly tell me if  ``awscli-1.10.20.tar.gz`` exists in ``awscli-bundle/packages/``? Also what version of python are you using?

**Comment by ssbarnea** [comment]
I am not sure what happened as I decided to switch to the pip installation method which worked. I tried to replicate the problem today in order to provide you with more information but I don't get the error anymore.

I am sure that if someone will face the same problem, they will be able to find this thread and revive the bug. With no way to reproduce yet, it makes sense to close it.

**Comment by ssbarnea** [comment]
```
uname -a
Linux ubuntu-clean 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
python --version
Python 2.7.10
python3 --version
Python 3.4.3+
```

**Comment by JordonPhillips** [comment]
So the issue is reproducible with that configuration?

**Comment by JordonPhillips** [comment]
Closing due to inactivity, still unable to reproduce.

**Comment by zvikagart** [comment]
I just hit this issue.
I found out I had more than one package in the `packages` subdirectory.
```
$ curl -sSL https://s3.amazonaws.com/aws-cli/awscli-bundle.zip -o /tmp/awscli-bundle.zip
$ cd /tmp
$ unzip -quo awscli-bundle.zip
$ ... added debug breakpoint in install script ...
$ sudo -E sh -c './awscli-bundle/install -i /usr/lib/aws -b /usr/bin/aws'
Running cmd: /bin/python virtualenv.py --python /bin/python /usr/lib/aws
> /tmp/awscli-bundle/install(93)pip_install_packages()
-> assert len(cli_tarball) == 1
(Pdb) cli_tarball
['awscli-1.10.46.tar.gz', 'awscli-1.10.48.tar.gz']
(Pdb) PACKAGES_DIR
'/tmp/awscli-bundle/packages'
```
Workaround was to remove the extracted folder (`/tmp/awscli-bundle` in my case) before unzipping

**Comment by mitin001** [comment]
Here's how to reproduce this error.

Download `https://s3.amazonaws.com/aws-cli/awscli-bundle.zip` and unzip.
Wait for a new release of aws-cli.
Redownload `https://s3.amazonaws.com/aws-cli/awscli-bundle.zip` and unzip into the same directory.

The sample of resulting files:

```
PyYAML-3.12.tar.gz
argparse-1.2.1.tar.gz
awscli-1.15.26.tar.gz
awscli-1.15.35.tar.gz
botocore-1.10.26.tar.gz
botocore-1.10.35.tar.gz
colorama-0.3.9.tar.gz
docutils-0.14.tar.gz
futures-3.2.0.tar.gz
jmespath-0.9.3.tar.gz
ordereddict-1.1.tar.gz
pyasn1-0.4.2.tar.gz
pyasn1-0.4.3.tar.gz
python-dateutil-2.6.1.tar.gz
python-dateutil-2.7.3.tar.gz
rsa-3.4.2.tar.gz
s3transfer-0.1.13.tar.gz
setup
simplejson-3.3.0.tar.gz
six-1.11.0.tar.gz
virtualenv-15.1.0.tar.gz
```

The unzip did not remove the packages from the previous download (e.g. `awscli-1.15.26.tar.gz`) and now we have a newer "duplicate" (e.g. `awscli-1.15.35.tar.gz`). That's where the installation breaks because `len(cli_tarball) > 1`. That's why emptying this directory, as @zvikagart suggested, works.

**Comment by DaveTSG** [comment]
For what it's worth, I can confirm @mitin001's explanation. It turns out I had accidentally downloaded and unzipped the ZIP file twice (the first time several months ago). rm -rf awscli-bundle/ and then unzipping it again solved the issue.
