### ISSUE TITLE
Exception: Traceback (most recent call last):   File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main

### ISSUE THREAD

**Issue by reggi** [aws/aws-cli#1980]
```
thomasreggi@project$ pip install --upgrade awsebcli
Collecting awsebcli
Requirement already up-to-date: cement==2.8.2 in /usr/local/lib/python2.7/site-packages (from awsebcli)
Requirement already up-to-date: docker-py<=1.7.2,>=1.1.0 in /usr/local/lib/python2.7/site-packages (from awsebcli)
Requirement already up-to-date: texttable<0.9,>=0.8.1 in /usr/local/lib/python2.7/site-packages (from awsebcli)
Collecting colorama==0.3.7 (from awsebcli)
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting websocket-client<1.0,>=0.11.0 (from awsebcli)
Requirement already up-to-date: pathspec==0.3.4 in /usr/local/lib/python2.7/site-packages (from awsebcli)
Requirement already up-to-date: requests<=2.9.1,>=2.6.1 in /usr/local/lib/python2.7/site-packages (from awsebcli)
Requirement already up-to-date: dockerpty<=0.4.1,>=0.3.2 in /usr/local/lib/python2.7/site-packages (from awsebcli)
Collecting botocore>=1.0.1 (from awsebcli)
  Using cached botocore-1.4.20-py2.py3-none-any.whl
Requirement already up-to-date: semantic-version==2.5.0 in /usr/local/lib/python2.7/site-packages (from awsebcli)
Requirement already up-to-date: docopt<0.7,>=0.6.1 in /usr/local/lib/python2.7/site-packages (from awsebcli)
Collecting setuptools>=20.0 (from awsebcli)
  Using cached setuptools-21.0.0-py2.py3-none-any.whl
Requirement already up-to-date: pyyaml>=3.11 in /Library/Python/2.7/site-packages (from awsebcli)
Requirement already up-to-date: blessed==1.9.5 in /usr/local/lib/python2.7/site-packages (from awsebcli)
Requirement already up-to-date: six>=1.4.0 in /usr/local/lib/python2.7/site-packages (from docker-py<=1.7.2,>=1.1.0->awsebcli)
Requirement already up-to-date: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python2.7/site-packages (from botocore>=1.0.1->awsebcli)
Requirement already up-to-date: docutils>=0.10 in /usr/local/lib/python2.7/site-packages (from botocore>=1.0.1->awsebcli)
Collecting python-dateutil<3.0.0,>=2.1 (from botocore>=1.0.1->awsebcli)
  Using cached python_dateutil-2.5.3-py2.py3-none-any.whl
Requirement already up-to-date: wcwidth>=0.1.0 in /usr/local/lib/python2.7/site-packages (from blessed==1.9.5->awsebcli)
Installing collected packages: colorama, websocket-client, python-dateutil, botocore, setuptools, awsebcli
  Found existing installation: colorama 0.3.3
    Uninstalling colorama-0.3.3:
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/colorama-0.3.3.dist-info/DESCRIPTION.rst'
```

```
pip --version
pip 8.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)
```

**Comment by reggi** [comment]
fixed

```
sudo pip install awscli --ignore-installed six
```

**Comment by mahieddine-ichir** [comment]
Thanks for the tip ... fixed my install and saved me hours of headlock 👍

**Comment by shinde-prasad** [comment]
hi @reggi, 

I am running my project inside docker, with ubuntu image 14.04, i am getting following error,




`Step 14/21 : RUN pip install -r $DOCKYARD_SRVPROJ/requirements.txt
 ---> Running in b0df06660d98
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 262, in run
    for req in parse_requirements(filename, finder=finder, options=options, session=session):
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1632, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 145, in from_line
    elif os.path.isdir(path) and (os.path.sep in name or name.startswith('.')):
  File "/usr/lib/python2.7/genericpath.py", line 41, in isdir
    st = os.stat(s)
TypeError: must be encoded string without NULL bytes, not str

Storing debug log for failure in /root/.pip/pip.log
The command '/bin/sh -c pip install -r $DOCKYARD_SRVPROJ/requirements.txt' returned a non-zero code: 2`

**Comment by Albertchieng** [comment]
thanks

**Comment by Albertchieng** [comment]
pip install -r requirements.txt
Collecting git+https://github.com/pytorch/text.git@master#wheel=torchtext (from -r requirements.txt (line 4))
  Cloning https://github.com/pytorch/text.git (to master) to /tmp/pip-9QuL2s-build
Collecting six (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting tqdm==4.30.* (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/76/4c/103a4d3415dafc1ddfe6a6624333971756e2d3dd8c6dc0f520152855f040/tqdm-4.30.0-py2.py3-none-any.whl
Collecting torch>=1.1 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/0f/ff/92aea60792d3b45c44ded21d6248690f69a6153af9685aad1424507ffe84/torch-1.1.0-cp27-cp27mu-manylinux1_x86_64.whl (676.9MB)
    99% |████████████████████████████████| 676.9MB 1.7MB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/lib/python2.7/dist-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py", line 436, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py", line 384, in read
    data = self._fp.read(amt)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 63, in read
    self._close()
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/serialize.py", line 55, in dumps
    "body": _b64_encode_bytes(body),
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/serialize.py", line 12, in _b64_encode_bytes
    return base64.b64encode(b).decode("ascii")
  File "/usr/lib/python2.7/base64.py", line 54, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
MemoryError






how can i fix this
