### ISSUE TITLE
ImportError: No module named pyasn1.error

### ISSUE THREAD

**Issue by glaksmono** [aws/aws-cli#2042]
Any ideas what may caused this?

```
➜  ~ aws help
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 49, in main
    driver = create_clidriver()
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 58, in create_clidriver
    event_hooks=emitter)
  File "/Library/Python/2.7/site-packages/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/Library/Python/2.7/site-packages/awscli/plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "/Library/Python/2.7/site-packages/awscli/handlers.py", line 30, in <module>
    from awscli.customizations.cloudtrail import initialize as cloudtrail_init
  File "/Library/Python/2.7/site-packages/awscli/customizations/cloudtrail/__init__.py", line 14, in <module>
    from .validation import CloudTrailValidateLogs
  File "/Library/Python/2.7/site-packages/awscli/customizations/cloudtrail/validation.py", line 25, in <module>
    from pyasn1.error import PyAsn1Error
ImportError: No module named pyasn1.error
➜  ~
```

I tried to upgrade:
```
➜  ~ pip install --upgrade awscli
Requirement already up-to-date: awscli in /Library/Python/2.7/site-packages
Cleaning up...
```

Thoughts?

**Comment by glaksmono** [comment]
I figured:

Upgrade PIP
```
➜  Documents sudo pip install --upgrade pip
Password:
Downloading/unpacking pip from https://pypi.python.org/packages/9c/32/004ce0852e0a127f07f358b715015763273799bd798956fa930814b60f39/pip-8.1.2-py2.py3-none-any.whl#md5=0570520434c5b600d89ec95393b2650b
  Downloading pip-8.1.2-py2.py3-none-any.whl (1.2MB): 1.2MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.4
    Uninstalling pip:
      Successfully uninstalled pip
Successfully installed pip
Cleaning up...
```

Then upgrade the `aws cli`

```
➜  Documents sudo pip install awscli --ignore-installed six
The directory '/Users/glaksmono/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/glaksmono/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting awscli
  Downloading awscli-1.10.43-py2.py3-none-any.whl (969kB)
    100% |████████████████████████████████| 972kB 413kB/s
Collecting six
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting docutils>=0.10 (from awscli)
  Downloading docutils-0.12.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 179kB/s
Collecting colorama<=0.3.3,>=0.2.5 (from awscli)
  Downloading colorama-0.3.3.tar.gz
Collecting s3transfer==0.0.1 (from awscli)
  Downloading s3transfer-0.0.1-py2.py3-none-any.whl
Collecting rsa<=3.5.0,>=3.1.2 (from awscli)
  Downloading rsa-3.4.2-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 860kB/s
Collecting botocore==1.4.33 (from awscli)
  Downloading botocore-1.4.33-py2.py3-none-any.whl (2.4MB)
    100% |████████████████████████████████| 2.4MB 360kB/s
Collecting futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" (from s3transfer==0.0.1->awscli)
  Downloading futures-3.0.5-py2-none-any.whl
Collecting pyasn1>=0.1.3 (from rsa<=3.5.0,>=3.1.2->awscli)
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Collecting python-dateutil<3.0.0,>=2.1 (from botocore==1.4.33->awscli)
  Downloading python_dateutil-2.5.3-py2.py3-none-any.whl (201kB)
    100% |████████████████████████████████| 204kB 464kB/s
Collecting jmespath<1.0.0,>=0.7.1 (from botocore==1.4.33->awscli)
  Downloading jmespath-0.9.0-py2.py3-none-any.whl
Installing collected packages: docutils, colorama, futures, six, python-dateutil, jmespath, botocore, s3transfer, pyasn1, rsa, awscli
  Running setup.py install for docutils ... done
  Running setup.py install for colorama ... done
Successfully installed awscli-1.10.42 botocore-1.4.32 colorama-0.3.3 docutils-0.12 futures-3.0.5 jmespath-0.9.0 pyasn1-0.1.9 python-dateutil-1.5 rsa-3.4.2 s3transfer-0.0.1 six-1.4.1
➜  Documents aws --help
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: too few arguments
➜  Documents aws --version
aws-cli/1.10.43 Python/2.7.10 Darwin/15.5.0 botocore/1.4.33
➜  Documents
```

**Comment by dshweta** [comment]
Works, Thanks !!

**Comment by jazlopez** [comment]
Just tested it ; I can confirm solution is working as of Aug. 2017.

**Comment by SkBalaDRG** [comment]
Thanks a lot, i had the same issue. It worked after upgrading pip.

**Comment by rickkuilman** [comment]
Still the solution as of March 2018

**Comment by rodnaph** [comment]
Still the solution as of January 2019

**Comment by saurabhdaga1** [comment]
Still the solution as of April 2019

**Comment by temunix2** [comment]
Still the solution as of May 2019

**Comment by aejb** [comment]
Still the solution as of September 2019

**Comment by pku-wuwei** [comment]
Still the solution as of October 2019

**Comment by jouellnyc** [comment]
This worked for me:

`pip3 install awscli --upgrade --user` 

from [aws doc](https://docs.aws.amazon.com/cli/latest/userguide/install-linux.html)

**Comment by jkparuchuri** [comment]
Still the solution as of May 2020

**Comment by marrakchino** [comment]
@glaksmono I executed the commands you listed but it didn't fix the issue:

```
$ sudo pip install --upgrade pip
WARNING: The directory '/home/marrakchino/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: pip in /home/marrakchino/.local/lib/python3.6/site-packages (20.2.4)
$ sudo pip install awscli --use-feature=2020-resolver --ignore-installed six
WARNING: The directory '/home/marrakchino/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting awscli
  Downloading awscli-1.18.175.tar.gz (1.3 MB)
     |████████████████████████████████| 1.3 MB 2.3 MB/s 
Collecting six
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting botocore==1.19.15
  Downloading botocore-1.19.15-py2.py3-none-any.whl (6.7 MB)
     |████████████████████████████████| 6.7 MB 10.2 MB/s 
Collecting docutils<0.16,>=0.10
  Downloading docutils-0.15.2-py3-none-any.whl (547 kB)
     |████████████████████████████████| 547 kB 13.7 MB/s 
Collecting s3transfer<0.4.0,>=0.3.0
  Downloading s3transfer-0.3.3-py2.py3-none-any.whl (69 kB)
     |████████████████████████████████| 69 kB 11.7 MB/s 
Collecting PyYAML<5.4,>=3.10
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
     |████████████████████████████████| 269 kB 14.1 MB/s 
Collecting colorama<0.4.4,>=0.2.5
  Downloading colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Collecting rsa<=4.5.0,>=3.1.2
  Downloading rsa-4.5-py2.py3-none-any.whl (36 kB)
Collecting urllib3<1.26,>=1.25.4
  Downloading urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 11.8 MB/s 
Collecting python-dateutil<3.0.0,>=2.1
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 16.0 MB/s 
Collecting jmespath<1.0.0,>=0.7.1
  Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting pyasn1>=0.1.3
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
     |████████████████████████████████| 77 kB 25.2 MB/s 
Building wheels for collected packages: awscli, PyYAML
  Building wheel for awscli (setup.py) ... done
  Created wheel for awscli: filename=awscli-1.18.175-py2.py3-none-any.whl size=3400548 sha256=8be0eed247341f622891ec6347ddd9c9c6d7776398c7621dbefeef5fcf493b61
  Stored in directory: /tmp/pip-ephem-wheel-cache-kba7m64j/wheels/bb/37/23/89914a44d6301574db7fde41a21f9c9bf348c7379e56521f5c
  Building wheel for PyYAML (setup.py) ... done
  Created wheel for PyYAML: filename=PyYAML-5.3.1-cp36-cp36m-linux_x86_64.whl size=44621 sha256=204dd27a1c296f10a819535d19149874ec873f2c7756f9730d8f7215248041c2
  Stored in directory: /tmp/pip-ephem-wheel-cache-kba7m64j/wheels/e5/9d/ad/2ee53cf262cba1ffd8afe1487eef788ea3f260b7e6232a80fc
Successfully built awscli PyYAML
Installing collected packages: six, urllib3, python-dateutil, jmespath, pyasn1, botocore, s3transfer, rsa, PyYAML, docutils, colorama, awscli
Successfully installed PyYAML-5.3.1 awscli-1.18.175 botocore-1.19.15 colorama-0.4.3 docutils-0.15.2 jmespath-0.10.0 pyasn1-0.4.8 python-dateutil-2.8.1 rsa-4.5 s3transfer-0.3.3 six-1.15.0 urllib3-1.25.11
$ aws --help
Traceback (most recent call last):
  File "/usr/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 68, in main
    driver = create_clidriver()
  File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 78, in create_clidriver
    event_hooks=session.get_component('event_emitter'))
  File "/usr/lib/python3/dist-packages/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/usr/lib/python3/dist-packages/awscli/plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "/usr/lib/python3/dist-packages/awscli/handlers.py", line 31, in <module>
    from awscli.customizations.cloudtrail import initialize as cloudtrail_init
  File "/usr/lib/python3/dist-packages/awscli/customizations/cloudtrail/__init__.py", line 14, in <module>
    from .validation import CloudTrailValidateLogs
  File "/usr/lib/python3/dist-packages/awscli/customizations/cloudtrail/validation.py", line 25, in <module>
    from pyasn1.error import PyAsn1Error
ImportError: No module named 'pyasn1'
$ 
```

Can anyone help ?
Best,

**Comment by cleggypdc** [comment]
Still solution as of May 2021 👍

**Comment by dwrolvink** [comment]
Still the solution as of August 2024
