### ISSUE TITLE
aws ec2 attach-network-interface UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 13: ordinal not in range(128)

### ISSUE THREAD

**Issue by winston-tong-SFDC** [aws/aws-cli#2050]
When I try to run this command on aws-cli for mac:
`aws ec2 attach-network-interface --network-interface-id <network-interface-id> --instance-id <instance-id> --device-index 1`

I get the following error:

> Traceback (most recent call last):
>   File "/usr/local/Cellar/awscli/1.10.43/libexec/bin/aws", line 27, in <module>
>     sys.exit(main())
>   File "/usr/local/Cellar/awscli/1.10.43/libexec/bin/aws", line 23, in main
>     return awscli.clidriver.main()
>   File "/usr/local/Cellar/awscli/1.10.43/libexec/lib/python2.7/site-packages/awscli/clidriver.py", line 50, in main
>     return driver.main()
>   File "/usr/local/Cellar/awscli/1.10.43/libexec/lib/python2.7/site-packages/awscli/clidriver.py", line 178, in main
>     parsed_args, remaining = parser.parse_known_args(args)
>   File "/usr/local/Cellar/awscli/1.10.43/libexec/lib/python2.7/site-packages/awscli/argparser.py", line 62, in parse_known_args
>     parsed, remaining = super(CLIArgParser, self).parse_known_args(args, namespace)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1733, in parse_known_args
>     namespace, args = self._parse_known_args(args, namespace)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1774, in _parse_known_args
>     option_tuple = self._parse_optional(arg_string)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 2082, in _parse_optional
>     option_tuples = self._get_option_tuples(arg_string)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 2125, in _get_option_tuples
>     if option_string.startswith(option_prefix):
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 13: ordinal not in range(128)

**Comment by jamesls** [comment]
Given the error appears to happen when parsing command line args, it's hard to help without seeing exactly what you're running.  I'd suggest double checking that the actual values of `<network-interace-id>` and `<instance-id>` don't contain any non-ascii chars.  Sometimes even an accidental unicode smart quotes surrounding the values can trigger this issue.

**Comment by jamesls** [comment]
Closing due to inactivity.  If you're still having issues, come chat with us on [gitter](https://gitter.im/aws/aws-cli) and we can help you troubleshoot.
