### ISSUE TITLE
skeleton produces Unknown parameter in ChangeBatch: "ChangeBatch", must be one of: Comment, Changes

### ISSUE THREAD

**Issue by cloudkitsch** [aws/aws-cli#2071]
Sorry if my comments on my gist are verbose, but I'd really like to get this sorted out eventually if not sooner then later, lots of debugging info towards the end of the comments, maybe start there:

https://gist.github.com/cloudkitsch/2253116db1f684377a466b2e37887a3c

**Comment by cloudkitsch** [comment]
let me try the python HEAD revision and see if anything is different....

**Comment by cloudkitsch** [comment]
looks like the skeleton format is just off a bit, the example in this page has a different result but still not the intended result and I don't know why: 

http://docs.aws.amazon.com/cli/latest/reference/route53/change-resource-record-sets.html

however,
```
ec2-user@ip-172-31-21-83 ~
0 % cat test.json 
{
  "Comment": "dyndns",
  "Changes": [
    {
      "Action": "UPSERT",
      "ResourceRecordSet": {
        "Name": "dank.memes.paigeat.info",
        "Type": "A",
        "Region": "us-west-2",
        "TTL": 10,
        "ResourceRecords": [
          {
            "Value": "63.225.191.41"
          }
        ]
      }
    }
  ]
}

ec2-user@ip-172-31-21-83 ~
0 % ~/.local/bin/aws route53 change-resource-record-sets --hosted-zone-id ZMOU19261H7AW --change-batch=file://test.json

An error occurred (InvalidInput) when calling the ChangeResourceRecordSets operation: Invalid request

ec2-user@ip-172-31-21-83 ~
255 % 

```

**Comment by cloudkitsch** [comment]
heres some debugging output if its any help 
```
���  ~./route53_dyndns.sh    
2016-07-17 20:54:49,533 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.10.47 Python/2.7.10 Linux/4.4.11-23.53.amzn1.x86_64 botocore/1.4.37
2016-07-17 20:54:49,533 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['route53', 'change-resource-record-sets', '--hosted-zone-id', 'ZMOU19261H7AW', '--debug', '--change-batch=\n{\n  "Comment": "dyndns",\n  "Changes": [\n    {\n      "Action": "UPSERT",\n      "ResourceRecordSet": {\n        "Name": "dank.memes.paigeat.info",\n        "Type": "A",\n        "Region": "us-west-2",\n        "TTL": 10,\n        "ResourceRecords": [\n          {\n            "Value": "63.225.191.41"\n          }\n        ]\n      }\n    }\n  ]\n}\n\n']
2016-07-17 20:54:49,533 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7fb5ebbc9500>
2016-07-17 20:54:49,533 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7fb5ec1d09b0>
2016-07-17 20:54:49,534 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2016-07-17 20:54:49,535 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /home/ec2-user/.local/lib/python2.7/site-packages/botocore-1.4.37-py2.7.egg/botocore/data/route53/2013-04-01/service-2.json
2016-07-17 20:54:49,559 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.route53: calling handler <function register_retries_for_service at 0x7fb5ec8ce758>
2016-07-17 20:54:49,559 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: route53
2016-07-17 20:54:49,562 - MainThread - botocore.hooks - DEBUG - Event building-command-table.route53: calling handler <function add_waiters at 0x7fb5ebbde6e0>
2016-07-17 20:54:49,564 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /home/ec2-user/.local/lib/python2.7/site-packages/botocore-1.4.37-py2.7.egg/botocore/data/route53/2013-04-01/waiters-2.json
2016-07-17 20:54:49,565 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'hosted-zone-id', <awscli.arguments.CLIArgument object at 0x7fb5eb67d350>), (u'change-batch', <awscli.arguments.CLIArgument object at 0x7fb5eb67d3d0>)])
2016-07-17 20:54:49,565 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.route53.change-resource-record-sets: calling handler <function add_streaming_output_arg at 0x7fb5ebbc9758>
2016-07-17 20:54:49,565 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.route53.change-resource-record-sets: calling handler <function add_cli_input_json at 0x7fb5ec1d97d0>
2016-07-17 20:54:49,565 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.route53.change-resource-record-sets: calling handler <function unify_paging_params at 0x7fb5ebe6c8c0>
2016-07-17 20:54:49,567 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /home/ec2-user/.local/lib/python2.7/site-packages/botocore-1.4.37-py2.7.egg/botocore/data/route53/2013-04-01/paginators-1.json
2016-07-17 20:54:49,567 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.route53.change-resource-record-sets: calling handler <function add_generate_skeleton at 0x7fb5ebe5be60>
2016-07-17 20:54:49,568 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.route53.change-resource-record-sets: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7fb5eb67d410>>
2016-07-17 20:54:49,568 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.route53.change-resource-record-sets: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fb5eb67d450>>
2016-07-17 20:54:49,569 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.route53.change-resource-record-sets.hosted-zone-id: calling handler <function uri_param at 0x7fb5ec274398>
2016-07-17 20:54:49,569 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.route53.change-resource-record-sets: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fb5ebbdcb90>
2016-07-17 20:54:49,569 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'ZMOU19261H7AW' for parameter "hosted_zone_id": u'ZMOU19261H7AW'
2016-07-17 20:54:49,569 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.route53.change-resource-record-sets.change-batch: calling handler <function uri_param at 0x7fb5ec274398>
2016-07-17 20:54:49,569 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.route53.change-resource-record-sets: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fb5ebbdcb90>
2016-07-17 20:54:49,569 - MainThread - awscli.argprocess - DEBUG - Param change_batch looks like JSON, not considered for param shorthand.
2016-07-17 20:54:49,569 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'\n{\n  "Comment": "dyndns",\n  "Changes": [\n    {\n      "Action": "UPSERT",\n      "ResourceRecordSet": {\n        "Name": "dank.memes.paigeat.info",\n        "Type": "A",\n        "Region": "us-west-2",\n        "TTL": 10,\n        "ResourceRecords": [\n          {\n            "Value": "63.225.191.41"\n          }\n        ]\n      }\n    }\n  ]\n}\n\n' for parameter "change_batch": OrderedDict([(u'Comment', u'dyndns'), (u'Changes', [OrderedDict([(u'Action', u'UPSERT'), (u'ResourceRecordSet', OrderedDict([(u'Name', u'dank.memes.paigeat.info'), (u'Type', u'A'), (u'Region', u'us-west-2'), (u'TTL', 10), (u'ResourceRecords', [OrderedDict([(u'Value', u'63.225.191.41')])])]))])])])
2016-07-17 20:54:49,569 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.route53.change-resource-record-sets.cli-input-json: calling handler <function uri_param at 0x7fb5ec274398>
2016-07-17 20:54:49,570 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.route53.change-resource-record-sets.generate-cli-skeleton: calling handler <function uri_param at 0x7fb5ec274398>
2016-07-17 20:54:49,570 - MainThread - botocore.hooks - DEBUG - Event calling-command.route53.change-resource-record-sets: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fb5eb67d450>>
2016-07-17 20:54:49,570 - MainThread - botocore.hooks - DEBUG - Event calling-command.route53.change-resource-record-sets: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7fb5eb67d410>>
2016-07-17 20:54:49,570 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2016-07-17 20:54:49,570 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2016-07-17 20:54:49,570 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2016-07-17 20:54:49,570 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2016-07-17 20:54:49,571 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /home/ec2-user/.local/lib/python2.7/site-packages/botocore-1.4.37-py2.7.egg/botocore/data/endpoints.json
2016-07-17 20:54:49,582 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: route53
2016-07-17 20:54:49,585 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.route53: calling handler <function add_generate_presigned_url at 0x7fb5ec8ac1b8>
2016-07-17 20:54:49,602 - MainThread - botocore.regions - DEBUG - Using partition endpoint for route53, us-west-2: aws-global
2016-07-17 20:54:49,602 - MainThread - botocore.client - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2016-07-17 20:54:49,603 - MainThread - botocore.endpoint - DEBUG - Setting route53 timeout as (60, 60)
2016-07-17 20:54:49,603 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.route53.ChangeResourceRecordSets: calling handler <function fix_route53_ids at 0x7fb5ec8ceed8>
2016-07-17 20:54:49,603 - MainThread - botocore.handlers - DEBUG - HostedZoneId ZMOU19261H7AW -> ZMOU19261H7AW
2016-07-17 20:54:49,605 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=ChangeResourceRecordSets) (verify_ssl=True) with params: {'body': '<ChangeResourceRecordSetsRequest xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><ChangeBatch><Comment>dyndns</Comment><Changes><Change><Action>UPSERT</Action><ResourceRecordSet><Name>dank.memes.paigeat.info</Name><Type>A</Type><Region>us-west-2</Region><TTL>10</TTL><ResourceRecords><ResourceRecord><Value>63.225.191.41</Value></ResourceRecord></ResourceRecords></ResourceRecordSet></Change></Changes></ChangeBatch></ChangeResourceRecordSetsRequest>', 'url': u'https://route53.amazonaws.com/2013-04-01/hostedzone/ZMOU19261H7AW/rrset/', 'headers': {'User-Agent': 'aws-cli/1.10.47 Python/2.7.10 Linux/4.4.11-23.53.amzn1.x86_64 botocore/1.4.37'}, 'context': {'client_region': u'aws-global', 'has_streaming_input': False, 'client_config': <botocore.config.Config object at 0x7fb5eb9e3ad0>}, 'query_string': {}, 'url_path': u'/2013-04-01/hostedzone/ZMOU19261H7AW/rrset/', 'method': u'POST'}
2016-07-17 20:54:49,605 - MainThread - botocore.hooks - DEBUG - Event request-created.route53.ChangeResourceRecordSets: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fb5ebb995d0>>
2016-07-17 20:54:49,606 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2016-07-17 20:54:49,606 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/2013-04-01/hostedzone/ZMOU19261H7AW/rrset/

host:route53.amazonaws.com
x-amz-date:20160717T205449Z

host;x-amz-date
23b9749fbb4308ab3ec54cb2a8b53406620c2d5fdca9fae7267af7e6f12c9548
2016-07-17 20:54:49,606 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20160717T205449Z
20160717/us-east-1/route53/aws4_request
5333c382096a7028b02a26a1dc33ee28d776b2e847cf921a8c478288408a6b9a
2016-07-17 20:54:49,606 - MainThread - botocore.auth - DEBUG - Signature:
15c4c713f144b1fbb1ce46d9d3ae4607c0b99224317620409178dece5a215f79
2016-07-17 20:54:49,608 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2016-07-17 20:54:49,608 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): route53.amazonaws.com
2016-07-17 20:54:49,938 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "POST /2013-04-01/hostedzone/ZMOU19261H7AW/rrset/ HTTP/1.1" 400 259
2016-07-17 20:54:49,939 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-requestid': 'b3d152ee-4c60-11e6-b37d-d531c61ec201', 'date': 'Sun, 17 Jul 2016 20:54:49 GMT', 'content-length': '259', 'content-type': 'text/xml', 'connection': 'close'}
2016-07-17 20:54:49,940 - MainThread - botocore.parsers - DEBUG - Response body:
<?xml version="1.0"?>
<ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>InvalidInput</Code><Message>Invalid request</Message></Error><RequestId>b3d152ee-4c60-11e6-b37d-d531c61ec201</RequestId></ErrorResponse>
2016-07-17 20:54:49,940 - MainThread - botocore.hooks - DEBUG - Event needs-retry.route53.ChangeResourceRecordSets: calling handler <botocore.retryhandler.RetryHandler object at 0x7fb5eb656510>
2016-07-17 20:54:49,940 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2016-07-17 20:54:49,940 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python2.7/site-packages/awscli-1.10.47-py2.7.egg/awscli/clidriver.py", line 186, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/awscli-1.10.47-py2.7.egg/awscli/clidriver.py", line 379, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/awscli-1.10.47-py2.7.egg/awscli/clidriver.py", line 549, in __call__
    call_parameters, parsed_globals)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/awscli-1.10.47-py2.7.egg/awscli/clidriver.py", line 673, in invoke
    **parameters)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/botocore-1.4.37-py2.7.egg/botocore/client.py", line 278, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/botocore-1.4.37-py2.7.egg/botocore/client.py", line 572, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (InvalidInput) when calling the ChangeResourceRecordSets operation: Invalid request
2016-07-17 20:54:49,941 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

An error occurred (InvalidInput) when calling the ChangeResourceRecordSets operation: Invalid request
���  ~  
```

**Comment by cloudkitsch** [comment]
'x-amzn-requestid': 'b3d152ee-4c60-11e6-b37d-d531c61ec201', this might be of some use, if not i can try the command again, i cant really see what its complaint is client side..

**Comment by cloudkitsch** [comment]
To better summarize this the doc suggested a format that was different from generate skeleton. Skeleton doesnt validate client side, doc format doesnt validate server side (see last 1-2 comments in gist link above.)

**Comment by JordonPhillips** [comment]
The skeleton is intended to provide ALL the params for a command, not just a subset, so you will need to pick out the specific parameters you want if you'd like to provide them separately. I'll need to look into it more, but I think your changebatch is not quite right. You can also ask on the [service forum](https://forums.aws.amazon.com/forum.jspa?forumID=87) where they'll know more of the specifics.

**Comment by cloudkitsch** [comment]
Ill check again tomorrow i gotta sleep

**Comment by kyleknap** [comment]
Closing due to inactivity. Please reopen if you have any further information.
