### ISSUE TITLE
Invalid request error when using aws cli with s3

### ISSUE THREAD

**Issue by nmb007** [aws/aws-cli#2112]
I am using the following command to use AWS codedeploy to push code on s3

aws deploy push --application-name aws_test_application --description "My First Deployment" --s3-location s3://mybucketname/test_project.zip

But I am getting the following error and I am stuck at this for a long time now, unable to determine whats causing this and how to fix this :(

ERROR: "An error occurred (InvalidRequest) when calling the PutObject operation: Missing required header for this request: x-amz-content-sha256"

aws cli version installed: aws-cli/1.10.56 Python/2.7.12 Linux/4.4.0-31-generic botocore/1.4.46

**Comment by nmb007** [comment]
The following is with  --debug:

2016-08-17 10:33:55,938 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.10.56 Python/2.7.12 Linux/4.4.0-31-generic botocore/1.4.46
2016-08-17 10:33:55,939 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['deploy', 'push', '--debug', '--application-name', 'aws_test_application', '--description', 'My First Deployment', '--s3-location', 's3://nmbbucket006/test_project.zip']
2016-08-17 10:33:55,939 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7fccc904faa0>
2016-08-17 10:33:55,939 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7fccc65e9230>
2016-08-17 10:33:55,939 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2016-08-17 10:33:55,940 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python2.7/dist-packages/botocore/data/codedeploy/2014-10-06/service-2.json
2016-08-17 10:33:55,951 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.codedeploy: calling handler <function register_retries_for_service at 0x7fccc6a31140>
2016-08-17 10:33:55,951 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: codedeploy
2016-08-17 10:33:55,952 - MainThread - botocore.hooks - DEBUG - Event building-command-table.deploy: calling handler <function inject_commands at 0x7fccc6553410>
2016-08-17 10:33:55,952 - MainThread - botocore.hooks - DEBUG - Event building-command-table.deploy: calling handler <function add_waiters at 0x7fccc9056f50>
2016-08-17 10:33:55,954 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python2.7/dist-packages/botocore/data/codedeploy/2014-10-06/waiters-2.json
2016-08-17 10:33:55,955 - MainThread - botocore.hooks - DEBUG - Event building-command-table.push: calling handler <function add_waiters at 0x7fccc9056f50>
2016-08-17 10:33:55,955 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.push.description: calling handler <function uri_param at 0x7fccc6610b18>
2016-08-17 10:33:55,956 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.push: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fccc65c7bd0>
2016-08-17 10:33:55,956 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.push.s3-location: calling handler <function uri_param at 0x7fccc6610b18>
2016-08-17 10:33:55,956 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.push: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fccc65c7bd0>
2016-08-17 10:33:55,956 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.push.no-ignore-hidden-files: calling handler <function uri_param at 0x7fccc6610b18>
2016-08-17 10:33:55,956 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.push: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fccc65c7bd0>
2016-08-17 10:33:55,956 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.push.source: calling handler <function uri_param at 0x7fccc6610b18>
2016-08-17 10:33:55,956 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.push: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fccc65c7bd0>
2016-08-17 10:33:55,956 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.push.application-name: calling handler <function uri_param at 0x7fccc6610b18>
2016-08-17 10:33:55,956 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.push: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fccc65c7bd0>
2016-08-17 10:33:55,956 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.push.ignore-hidden-files: calling handler <function uri_param at 0x7fccc6610b18>
2016-08-17 10:33:55,956 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.push: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fccc65c7bd0>
2016-08-17 10:33:55,957 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2016-08-17 10:33:55,957 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2016-08-17 10:33:55,957 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2016-08-17 10:33:55,957 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2016-08-17 10:33:55,957 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python2.7/dist-packages/botocore/data/endpoints.json
2016-08-17 10:33:55,964 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: codedeploy
2016-08-17 10:33:55,965 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.codedeploy: calling handler <function add_generate_presigned_url at 0x7fccc69ff848>
2016-08-17 10:33:55,966 - MainThread - botocore.client - DEBUG - Assuming an endpoint for codedeploy, us-west-2b: https://codedeploy.us-west-2b.amazonaws.com
2016-08-17 10:33:55,966 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2016-08-17 10:33:55,970 - MainThread - botocore.endpoint - DEBUG - Setting codedeploy timeout as (60, 60)
2016-08-17 10:33:55,972 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python2.7/dist-packages/botocore/data/s3/2006-03-01/service-2.json
2016-08-17 10:33:56,021 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2016-08-17 10:33:56,023 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7fccc6a02140>
2016-08-17 10:33:56,023 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7fccc69ff848>
2016-08-17 10:33:56,023 - MainThread - botocore.client - DEBUG - Assuming an endpoint for s3, us-west-2b: https://s3.us-west-2b.amazonaws.com
2016-08-17 10:33:56,023 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2016-08-17 10:33:56,025 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2016-08-17 10:33:56,029 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function validate_ascii_metadata at 0x7fccc6a31848>
2016-08-17 10:33:56,030 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function sse_md5 at 0x7fccc6a2eed8>
2016-08-17 10:33:56,030 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function convert_body_to_file_like_object at 0x7fccc6a31de8>
2016-08-17 10:33:56,030 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function validate_bucket_name at 0x7fccc6a2ee60>
2016-08-17 10:33:56,030 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x7fccc57689d0>>
2016-08-17 10:33:56,031 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.PutObject: calling handler <function conditionally_calculate_md5 at 0x7fccc6a2ede8>
2016-08-17 10:33:56,032 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.PutObject: calling handler <function add_expect_header at 0x7fccc6a31320>
2016-08-17 10:33:56,032 - MainThread - botocore.handlers - DEBUG - Adding expect 100 continue header to request.
2016-08-17 10:33:56,032 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.PutObject: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x7fccc57689d0>>
2016-08-17 10:33:56,032 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=PutObject) (verify_ssl=True) with params: {'body': <open file '<fdopen>', mode 'w+b' at 0x7fccc57e2150>, 'url': u'https://s3.us-west-2b.amazonaws.com/nmbbucket006/test_project.zip', 'headers': {'Content-MD5': u'26seK41ezMxGjIYpTN9+HQ==', 'Expect': '100-continue', 'User-Agent': 'aws-cli/1.10.56 Python/2.7.12 Linux/4.4.0-31-generic botocore/1.4.46'}, 'context': {'client_region': 'us-west-2b', 'signing': {'bucket': 'nmbbucket006'}, 'has_streaming_input': True, 'client_config': <botocore.config.Config object at 0x7fccc5768290>}, 'query_string': {}, 'url_path': u'/nmbbucket006/test_project.zip', 'method': u'PUT'}
2016-08-17 10:33:56,032 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.PutObject: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fccc5768250>>
2016-08-17 10:33:56,032 - MainThread - botocore.hooks - DEBUG - Event before-sign.s3.PutObject: calling handler <function fix_s3_host at 0x7fccc6f830c8>
2016-08-17 10:33:56,032 - MainThread - botocore.utils - DEBUG - Checking for DNS compatible bucket for: https://s3.us-west-2b.amazonaws.com/nmbbucket006/test_project.zip
2016-08-17 10:33:56,032 - MainThread - botocore.utils - DEBUG - URI updated to: https://nmbbucket006.s3.amazonaws.com/test_project.zip
2016-08-17 10:33:56,033 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2016-08-17 10:33:56,033 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
PUT
/test_project.zip

content-md5:26seK41ezMxGjIYpTN9+HQ==
host:nmbbucket006.s3.amazonaws.com
x-amz-date:20160817T053356Z

content-md5;host;x-amz-date
57d89d6e7d3ded20eb2b918158f972cac6ef9daa440c32c58bb7e80fb1f6d284
2016-08-17 10:33:56,033 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20160817T053356Z
20160817/us-west-2b/s3/aws4_request
b47c100e64dbe7f0f2e6da5c2bd01eaf8a62f3e0605cbd9db11c3e8be4366439
2016-08-17 10:33:56,033 - MainThread - botocore.auth - DEBUG - Signature:
1387ced69ed521dbfed635b1bc5db43f33a31ac40ecc58ddcc29d61875213171
2016-08-17 10:33:56,037 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [PUT]>
2016-08-17 10:33:56,038 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): nmbbucket006.s3.amazonaws.com
2016-08-17 10:33:57,148 - MainThread - botocore.awsrequest - DEBUG - Waiting for 100 Continue response.
2016-08-17 10:33:57,452 - MainThread - botocore.awsrequest - DEBUG - Received a non 100 Continue response from the server, NOT sending request body.
2016-08-17 10:33:57,453 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "PUT /test_project.zip HTTP/1.1" 400 None
2016-08-17 10:33:57,455 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amz-id-2': '/KDEb/bZrJ7MlFzYlfRnOqCaQXmcnKpyStApGv48eVTMw5KbE2bKcMXDhxWkQjccLFJ3/YWbvCY=', 'server': 'AmazonS3', 'transfer-encoding': 'chunked', 'connection': 'close', 'x-amz-request-id': 'D0E2D67AB7ADE4C5', 'date': 'Wed, 17 Aug 2016 05:35:12 GMT', 'content-type': 'application/xml'}
2016-08-17 10:33:57,456 - MainThread - botocore.parsers - DEBUG - Response body:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>Missing required header for this request: x-amz-content-sha256</Message><RequestId>D0E2D67AB7ADE4C5</RequestId><HostId>/KDEb/bZrJ7MlFzYlfRnOqCaQXmcnKpyStApGv48eVTMw5KbE2bKcMXDhxWkQjccLFJ3/YWbvCY=</HostId></Error>
2016-08-17 10:33:57,456 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.PutObject: calling handler <botocore.retryhandler.RetryHandler object at 0x7fccc57e9c90>
2016-08-17 10:33:57,456 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2016-08-17 10:33:57,456 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.PutObject: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x7fccc57689d0>>
2016-08-17 10:33:57,456 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.PutObject: calling handler <function enhance_error_msg at 0x7fccc904f758>
2016-08-17 10:33:57,456 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 186, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 379, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/codedeploy/push.py", line 121, in _run_main
    self._push(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/codedeploy/push.py", line 153, in _push
    str(e))
RuntimeError: Failed to upload '.' to 's3://nmbbucket006/test_project.zip': An error occurred (InvalidRequest) when calling the PutObject operation: Missing required header for this request: x-amz-content-sha256
2016-08-17 10:33:57,457 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Failed to upload '.' to 's3://nmbbucket006/test_project.zip': An error occurred (InvalidRequest) when calling the PutObject operation: Missing required header for this request: x-amz-content-sha256

**Comment by jamesls** [comment]
> https://s3.us-west-2b.amazonaws.com/nmbbucket006/test_project.zip

You have a region configured of `us-west-2b`, which is an AZ.  Your region value should be `us-west-2`.  Double check in your `~/.aws/config` that you have `region = us-west-2`.

**Comment by nmb007** [comment]
thank you so much :)
