### ISSUE TITLE
InvalidRequest when calling the PutObject operation

### ISSUE THREAD

**Issue by minafa** [aws/aws-cli#2134]
I'm using the following command to verify if my user could access to S3 bucket:
**$ aws s3api put-object --bucket bymspsbucket --key AWS.png --body Desktop/AWS.png --profile spsadmin**

But I've faced with the following error and stuck on it and no idea what's wrong...
**An error occurred (InvalidRequest) when calling the PutObject operation: Missing required header for this request: x-amz-content-sha256**

Running command with --debug:
$ aws s3api put-object --bucket bymspsbucket --key AWS.png --body Desktop/AWS.png --profile spsadmin --debug
2016-08-24 20:48:24,349 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.10.59 Python/2.7.10 Darwin/15.0.0 botocore/1.4.49
2016-08-24 20:48:24,349 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3api', 'put-object', '--bucket', 'bymspsbucket', '--key', 'AWS.png', '--body', 'Desktop/AWS.png', '--profile', 'spsadmin', '--debug']
2016-08-24 20:48:24,350 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x1044409b0>
2016-08-24 20:48:24,350 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x1042502a8>
2016-08-24 20:48:24,354 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Library/Python/2.7/site-packages/botocore/data/s3/2006-03-01/service-2.json
2016-08-24 20:48:24,383 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.s3: calling handler <function register_retries_for_service at 0x103e4d578>
2016-08-24 20:48:24,385 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: s3
2016-08-24 20:48:24,388 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3api: calling handler <function add_waiters at 0x104447b90>
2016-08-24 20:48:24,393 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Library/Python/2.7/site-packages/botocore/data/s3/2006-03-01/waiters-2.json
2016-08-24 20:48:24,399 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'acl', <awscli.arguments.CLIArgument object at 0x104940790>), (u'body', <awscli.arguments.CLIArgument object at 0x1049407d0>), (u'bucket', <awscli.arguments.CLIArgument object at 0x104940810>), (u'cache-control', <awscli.arguments.CLIArgument object at 0x104940850>), (u'content-disposition', <awscli.arguments.CLIArgument object at 0x104940890>), (u'content-encoding', <awscli.arguments.CLIArgument object at 0x1049408d0>), (u'content-language', <awscli.arguments.CLIArgument object at 0x104940910>), (u'content-length', <awscli.arguments.CLIArgument object at 0x104940950>), (u'content-md5', <awscli.arguments.CLIArgument object at 0x104940990>), (u'content-type', <awscli.arguments.CLIArgument object at 0x1049409d0>), (u'expires', <awscli.arguments.CLIArgument object at 0x104940a10>), (u'grant-full-control', <awscli.arguments.CLIArgument object at 0x104940a50>), (u'grant-read', <awscli.arguments.CLIArgument object at 0x104940a90>), (u'grant-read-acp', <awscli.arguments.CLIArgument object at 0x104940ad0>), (u'grant-write-acp', <awscli.arguments.CLIArgument object at 0x104940b10>), (u'key', <awscli.arguments.CLIArgument object at 0x104940b50>), (u'metadata', <awscli.arguments.CLIArgument object at 0x104940b90>), (u'server-side-encryption', <awscli.arguments.CLIArgument object at 0x104940bd0>), (u'storage-class', <awscli.arguments.CLIArgument object at 0x104940c10>), (u'website-redirect-location', <awscli.arguments.CLIArgument object at 0x104940c50>), (u'sse-customer-algorithm', <awscli.arguments.CLIArgument object at 0x104940c90>), (u'sse-customer-key', <awscli.arguments.CLIArgument object at 0x104940cd0>), (u'sse-customer-key-md5', <awscli.arguments.CLIArgument object at 0x104940d10>), (u'ssekms-key-id', <awscli.arguments.CLIArgument object at 0x104940d50>), (u'request-payer', <awscli.arguments.CLIArgument object at 0x104940d90>)])
2016-08-24 20:48:24,399 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-object: calling handler <function add_streaming_output_arg at 0x104440ed8>
2016-08-24 20:48:24,399 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-object: calling handler <function add_cli_input_json at 0x1042570c8>
2016-08-24 20:48:24,399 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-object: calling handler <function unify_paging_params at 0x1043ad320>
2016-08-24 20:48:24,405 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Library/Python/2.7/site-packages/botocore/data/s3/2006-03-01/paginators-1.json
2016-08-24 20:48:24,405 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-object: calling handler <function add_generate_skeleton at 0x104394848>
2016-08-24 20:48:24,406 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.put-object: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x104940dd0>>
2016-08-24 20:48:24,406 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.put-object: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x104940e50>>
2016-08-24 20:48:24,409 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.acl: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,409 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.body: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,410 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.s3.put-object: calling handler <awscli.argprocess.ParamShorthandParser object at 0x10444c8d0>
2016-08-24 20:48:24,410 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'Desktop/AWS.png' for parameter "body": <open file u'Desktop/AWS.png', mode 'rb' at 0x10454af60>
2016-08-24 20:48:24,410 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.bucket: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,410 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.s3.put-object: calling handler <awscli.argprocess.ParamShorthandParser object at 0x10444c8d0>
2016-08-24 20:48:24,410 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'bymspsbucket' for parameter "bucket": u'bymspsbucket'
2016-08-24 20:48:24,411 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.cache-control: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,411 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.content-disposition: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,411 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.content-encoding: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,411 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.content-language: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,411 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.content-length: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,412 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.content-md5: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,412 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.content-type: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,412 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.expires: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,412 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.grant-full-control: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,412 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.grant-read: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,412 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.grant-read-acp: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,413 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.grant-write-acp: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,413 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.key: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,413 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.s3.put-object: calling handler <awscli.argprocess.ParamShorthandParser object at 0x10444c8d0>
2016-08-24 20:48:24,413 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'AWS.png' for parameter "key": u'AWS.png'
2016-08-24 20:48:24,413 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.metadata: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,413 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.server-side-encryption: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,413 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.storage-class: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,414 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.website-redirect-location: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,414 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.sse-customer-algorithm: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,414 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.sse-customer-key: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,414 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.sse-customer-key-md5: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,414 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.ssekms-key-id: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,414 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.request-payer: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,415 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.cli-input-json: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,415 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.generate-cli-skeleton: calling handler <function uri_param at 0x1040f29b0>
2016-08-24 20:48:24,415 - MainThread - botocore.hooks - DEBUG - Event calling-command.s3api.put-object: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x104940e50>>
2016-08-24 20:48:24,415 - MainThread - botocore.hooks - DEBUG - Event calling-command.s3api.put-object: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x104940dd0>>
2016-08-24 20:48:24,415 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2016-08-24 20:48:24,416 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2016-08-24 20:48:24,416 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2016-08-24 20:48:24,418 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Library/Python/2.7/site-packages/botocore/data/endpoints.json
2016-08-24 20:48:24,431 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2016-08-24 20:48:24,433 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x103e22320>
2016-08-24 20:48:24,433 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x103e1fa28>
2016-08-24 20:48:24,434 - MainThread - botocore.client - DEBUG - Assuming an endpoint for s3, Ireland: https://s3.Ireland.amazonaws.com
2016-08-24 20:48:24,434 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2016-08-24 20:48:24,484 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2016-08-24 20:48:24,490 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function validate_ascii_metadata at 0x103e4dc80>
2016-08-24 20:48:24,491 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function sse_md5 at 0x103e4d398>
2016-08-24 20:48:24,491 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function convert_body_to_file_like_object at 0x103e4e2a8>
2016-08-24 20:48:24,491 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function validate_bucket_name at 0x103e4d320>
2016-08-24 20:48:24,491 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x104a66e10>>
2016-08-24 20:48:24,493 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.PutObject: calling handler <function conditionally_calculate_md5 at 0x103e4d2a8>
2016-08-24 20:48:24,494 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.PutObject: calling handler <function add_expect_header at 0x103e4d758>
2016-08-24 20:48:24,494 - MainThread - botocore.handlers - DEBUG - Adding expect 100 continue header to request.
2016-08-24 20:48:24,494 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.PutObject: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x104a66e10>>
2016-08-24 20:48:24,495 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=PutObject) (verify_ssl=True) with params: {'body': <open file u'Desktop/AWS.png', mode 'rb' at 0x10454af60>, 'url': u'https://s3.Ireland.amazonaws.com/bymspsbucket/AWS.png', 'headers': {'Content-MD5': u'AD9ZSLXKAhZ+/WomszsmPg==', 'Expect': '100-continue', 'User-Agent': 'aws-cli/1.10.59 Python/2.7.10 Darwin/15.0.0 botocore/1.4.49'}, 'context': {'client_region': 'Ireland', 'signing': {'bucket': u'bymspsbucket'}, 'has_streaming_input': True, 'client_config': <botocore.config.Config object at 0x104a667d0>}, 'query_string': {}, 'url_path': u'/bymspsbucket/AWS.png', 'method': u'PUT'}
2016-08-24 20:48:24,495 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.PutObject: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x104a66750>>
2016-08-24 20:48:24,496 - MainThread - botocore.hooks - DEBUG - Event before-sign.s3.PutObject: calling handler <function fix_s3_host at 0x103cd0320>
2016-08-24 20:48:24,496 - MainThread - botocore.utils - DEBUG - Checking for DNS compatible bucket for: https://s3.Ireland.amazonaws.com/bymspsbucket/AWS.png
2016-08-24 20:48:24,496 - MainThread - botocore.utils - DEBUG - URI updated to: https://bymspsbucket.s3.amazonaws.com/AWS.png
2016-08-24 20:48:24,499 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2016-08-24 20:48:24,499 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
PUT
/AWS.png

content-md5:AD9ZSLXKAhZ+/WomszsmPg==
host:bymspsbucket.s3.amazonaws.com
x-amz-date:20160824T184824Z

content-md5;host;x-amz-date
6e8bd6c513968675f792bca809906b7ca58f5cf876cb87cdfb424773f5c99607
2016-08-24 20:48:24,499 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20160824T184824Z
20160824/Ireland/s3/aws4_request
4d6bfe2f2646030e05367ad33723774c40a06946408c466a13405a4c9f71db81
2016-08-24 20:48:24,500 - MainThread - botocore.auth - DEBUG - Signature:
d17a07b8dc9dadc7d7b054a60d5678de067c5a59536f650a3e6a242738f870c2
2016-08-24 20:48:24,513 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [PUT]>
2016-08-24 20:48:24,514 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): bymspsbucket.s3.amazonaws.com
2016-08-24 20:48:25,089 - MainThread - botocore.awsrequest - DEBUG - Waiting for 100 Continue response.
2016-08-24 20:48:25,136 - MainThread - botocore.awsrequest - DEBUG - Received a non 100 Continue response from the server, NOT sending request body.
2016-08-24 20:48:25,137 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "PUT /AWS.png HTTP/1.1" 400 None
2016-08-24 20:48:25,142 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amz-id-2': 'E8uxqxQxl3lk8V/lB+X2zX1kz3kloDVvnwNmrs4DfSOxJIHBgiaovylO0SvDcoC2xlSZS2NIhNE=', 'server': 'AmazonS3', 'transfer-encoding': 'chunked', 'connection': 'close', 'x-amz-request-id': 'C3BCE4CB6D1B1761', 'date': 'Wed, 24 Aug 2016 18:48:24 GMT', 'content-type': 'application/xml'}
2016-08-24 20:48:25,142 - MainThread - botocore.parsers - DEBUG - Response body:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>Missing required header for this request: x-amz-content-sha256</Message><RequestId>C3BCE4CB6D1B1761</RequestId><HostId>E8uxqxQxl3lk8V/lB+X2zX1kz3kloDVvnwNmrs4DfSOxJIHBgiaovylO0SvDcoC2xlSZS2NIhNE=</HostId></Error>
2016-08-24 20:48:25,143 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.PutObject: calling handler <botocore.retryhandler.RetryHandler object at 0x1048739d0>
2016-08-24 20:48:25,143 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2016-08-24 20:48:25,143 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.PutObject: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x104a66e10>>
2016-08-24 20:48:25,144 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.PutObject: calling handler <function enhance_error_msg at 0x1044406e0>
2016-08-24 20:48:25,144 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 186, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 381, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 551, in __call__
    call_parameters, parsed_globals)
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 675, in invoke
    **parameters)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 494, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (InvalidRequest) when calling the PutObject operation: Missing required header for this request: x-amz-content-sha256
2016-08-24 20:48:25,148 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

An error occurred (InvalidRequest) when calling the PutObject operation: Missing required header for this request: x-amz-content-sha256

_$ aws --version
aws-cli/1.10.59 Python/2.7.10 Darwin/15.0.0 botocore/1.4.49_

Any help would be appreciated.

**Comment by jamesls** [comment]
We're sending a request to: `https://s3.Ireland.amazonaws.com` which means you have your region configured for `Ireland`.  For the Ireland region, you should set your region value in your `~/.aws/config` file to `eu-west-1`:

```
[profile spsadmin]
region = eu-west-1
```

**Comment by JordonPhillips** [comment]
Closing due to inactivity

**Comment by glaksmono** [comment]
Can someone help on this?
