### ISSUE TITLE
ImportError: No module named code_commit_awscli_plugin

### ISSUE THREAD

**Issue by ashishtilara** [aws/aws-cli#2159]
Uninstalled and installed SDK and whenever I try to run any command, it keeps throwing following exception:

```
>aws configure
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/local/Cellar/awscli/1.10.61/libexec/lib/python2.7/site-packages/awscli/clidriver.py", line 49, in main
    driver = create_clidriver()
  File "/usr/local/Cellar/awscli/1.10.61/libexec/lib/python2.7/site-packages/awscli/clidriver.py", line 58, in create_clidriver
    event_hooks=emitter)
  File "/usr/local/Cellar/awscli/1.10.61/libexec/lib/python2.7/site-packages/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/usr/local/Cellar/awscli/1.10.61/libexec/lib/python2.7/site-packages/awscli/plugin.py", line 58, in _import_plugins
    plugins.append(__import__(path))
ImportError: No module named code_commit_awscli_plugin
```

**Comment by JordonPhillips** [comment]
It appears you installed a cli plugin and it got removed at some point. There's probably an entry in your `~/.aws/config` file describing its location. You'll need to remove that.

**Comment by ashishtilara** [comment]
Thank you @JordonPhillips, That works 👍 , not sure how that plugin got in there...
