### ISSUE TITLE
ExecutableNotFoundError: Could not find executable named "groff"

### ISSUE THREAD

**Issue by enricostano** [aws/aws-cli#2188]
I just installed `awscli` package in a Ubuntu 14.04 LXC container using:
```
sudo apt-get install awscli
```
Version is:
```
$ aws --version
aws-cli/1.2.9 Python/3.4.3 Linux/4.7.4-1-ARCH
```
But running the `help` command I get the following output and error:
```
$ aws --debug help
2016-09-21 11:26:36,913 - awscli.clidriver - DEBUG - CLI version: aws-cli/1.2.9 Python/3.4.3 Linux/4.7.4-1-ARCH, botocore version: 0.29.0
2016-09-21 11:26:36,915 - botocore.hooks - DEBUG - Event doc-title.Provider.aws: calling handler <bound method ProviderDocumentEventHandler.doc_title of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,915 - botocore.hooks - DEBUG - Event doc-description.Provider.aws: calling handler <bound method ProviderDocumentEventHandler.doc_description of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,915 - botocore.hooks - DEBUG - Event doc-synopsis-start.Provider.aws: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_start of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,915 - botocore.hooks - DEBUG - Event doc-synopsis-option.Provider.aws.debug: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,915 - botocore.hooks - DEBUG - Event doc-synopsis-option.Provider.aws.endpoint-url: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,916 - botocore.hooks - DEBUG - Event doc-synopsis-option.Provider.aws.no-verify-ssl: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,916 - botocore.hooks - DEBUG - Event doc-synopsis-option.Provider.aws.no-paginate: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,916 - botocore.hooks - DEBUG - Event doc-synopsis-option.Provider.aws.output: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,916 - botocore.hooks - DEBUG - Event doc-synopsis-option.Provider.aws.query: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,916 - botocore.hooks - DEBUG - Event doc-synopsis-option.Provider.aws.profile: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,916 - botocore.hooks - DEBUG - Event doc-synopsis-option.Provider.aws.region: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,916 - botocore.hooks - DEBUG - Event doc-synopsis-option.Provider.aws.version: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,916 - botocore.hooks - DEBUG - Event doc-synopsis-option.Provider.aws.color: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,916 - botocore.hooks - DEBUG - Event doc-synopsis-end.Provider.aws: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_end of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,916 - botocore.hooks - DEBUG - Event doc-options-start.Provider.aws: calling handler <bound method ProviderDocumentEventHandler.doc_options_start of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,916 - botocore.hooks - DEBUG - Event doc-option.Provider.aws.debug: calling handler <bound method ProviderDocumentEventHandler.doc_option of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,916 - botocore.hooks - DEBUG - Event doc-option-example.Provider.aws.debug: calling handler <bound method ParamShorthand.add_example_fn of <awscli.argprocess.ParamShorthand object at 0x7f0a540216a0>>
2016-09-21 11:26:36,916 - botocore.hooks - DEBUG - Event doc-option.Provider.aws.endpoint-url: calling handler <bound method ProviderDocumentEventHandler.doc_option of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,916 - botocore.hooks - DEBUG - Event doc-option-example.Provider.aws.endpoint-url: calling handler <bound method ParamShorthand.add_example_fn of <awscli.argprocess.ParamShorthand object at 0x7f0a540216a0>>
2016-09-21 11:26:36,917 - botocore.hooks - DEBUG - Event doc-option.Provider.aws.no-verify-ssl: calling handler <bound method ProviderDocumentEventHandler.doc_option of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,917 - botocore.hooks - DEBUG - Event doc-option-example.Provider.aws.no-verify-ssl: calling handler <bound method ParamShorthand.add_example_fn of <awscli.argprocess.ParamShorthand object at 0x7f0a540216a0>>
2016-09-21 11:26:36,917 - botocore.hooks - DEBUG - Event doc-option.Provider.aws.no-paginate: calling handler <bound method ProviderDocumentEventHandler.doc_option of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,917 - botocore.hooks - DEBUG - Event doc-option-example.Provider.aws.no-paginate: calling handler <bound method ParamShorthand.add_example_fn of <awscli.argprocess.ParamShorthand object at 0x7f0a540216a0>>
2016-09-21 11:26:36,917 - botocore.hooks - DEBUG - Event doc-option.Provider.aws.output: calling handler <bound method ProviderDocumentEventHandler.doc_option of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,917 - botocore.hooks - DEBUG - Event doc-option-example.Provider.aws.output: calling handler <bound method ParamShorthand.add_example_fn of <awscli.argprocess.ParamShorthand object at 0x7f0a540216a0>>
2016-09-21 11:26:36,917 - botocore.hooks - DEBUG - Event doc-option.Provider.aws.query: calling handler <bound method ProviderDocumentEventHandler.doc_option of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,917 - botocore.hooks - DEBUG - Event doc-option-example.Provider.aws.query: calling handler <bound method ParamShorthand.add_example_fn of <awscli.argprocess.ParamShorthand object at 0x7f0a540216a0>>
2016-09-21 11:26:36,917 - botocore.hooks - DEBUG - Event doc-option.Provider.aws.profile: calling handler <bound method ProviderDocumentEventHandler.doc_option of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,917 - botocore.hooks - DEBUG - Event doc-option-example.Provider.aws.profile: calling handler <bound method ParamShorthand.add_example_fn of <awscli.argprocess.ParamShorthand object at 0x7f0a540216a0>>
2016-09-21 11:26:36,917 - botocore.hooks - DEBUG - Event doc-option.Provider.aws.region: calling handler <bound method ProviderDocumentEventHandler.doc_option of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,917 - botocore.hooks - DEBUG - Event doc-option-example.Provider.aws.region: calling handler <bound method ParamShorthand.add_example_fn of <awscli.argprocess.ParamShorthand object at 0x7f0a540216a0>>
2016-09-21 11:26:36,918 - botocore.hooks - DEBUG - Event doc-option.Provider.aws.version: calling handler <bound method ProviderDocumentEventHandler.doc_option of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,918 - botocore.hooks - DEBUG - Event doc-option-example.Provider.aws.version: calling handler <bound method ParamShorthand.add_example_fn of <awscli.argprocess.ParamShorthand object at 0x7f0a540216a0>>
2016-09-21 11:26:36,918 - botocore.hooks - DEBUG - Event doc-option.Provider.aws.color: calling handler <bound method ProviderDocumentEventHandler.doc_option of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,918 - botocore.hooks - DEBUG - Event doc-option-example.Provider.aws.color: calling handler <bound method ParamShorthand.add_example_fn of <awscli.argprocess.ParamShorthand object at 0x7f0a540216a0>>
2016-09-21 11:26:36,918 - botocore.hooks - DEBUG - Event doc-options-end.Provider.aws: calling handler <bound method ProviderDocumentEventHandler.doc_options_end of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,918 - botocore.hooks - DEBUG - Event doc-subitems-start.Provider.aws: calling handler <bound method ProviderDocumentEventHandler.doc_subitems_start of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,918 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.autoscaling: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,918 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.cloudformation: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,918 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.cloudtrail: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,918 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.cloudwatch: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,918 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.configure: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,918 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.directconnect: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,918 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.dynamodb: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,919 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.ec2: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,919 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.elasticache: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,919 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.elasticbeanstalk: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,919 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.elastictranscoder: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,919 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.elb: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,919 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.help: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,919 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.iam: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,919 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.importexport: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,919 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.kinesis: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,919 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.opsworks: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,919 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.rds: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,919 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.redshift: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,919 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.route53: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,919 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.s3: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,919 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.s3api: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,919 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.ses: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,919 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.sns: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,920 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.sqs: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,920 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.storagegateway: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,920 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.sts: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,920 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.support: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,920 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.swf: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <awscli.clidocs.ProviderDocumentEventHandler object at 0x7f0a53d57c50>>
2016-09-21 11:26:36,920 - botocore.hooks - DEBUG - Event doc-examples.Provider.aws: calling handler <function add_examples at 0x7f0a54025400>
2016-09-21 11:26:36,920 - awscli.customizations.addexamples - DEBUG - Looking for example file at: /usr/share/awscli/awscli/examples/Provider/aws.rst
2016-09-21 11:26:36,988 - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/share/awscli/awscli/clidriver.py", line 187, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/share/awscli/awscli/help.py", line 233, in __call__
    self.renderer.render(self.doc.getvalue())
  File "/usr/share/awscli/awscli/help.py", line 88, in render
    raise ExecutableNotFoundError('groff')
awscli.help.ExecutableNotFoundError: Could not find executable named "groff"
2016-09-21 11:26:36,988 - awscli.clidriver - DEBUG - Exiting with rc 255
Could not find executable named "groff"
```
I could find other similar issues related to missing `less` command, but this seems to be another issue.

**Comment by jamesls** [comment]
What happens when you run `groff --version`?  Just trying to understand if this is because the CLI can't figure out where `groff` is installed or if you don't have `groff` installed.  If it's the later you'll need to manually install that.  It might even be worth having this as a dependency of the CLI in the APT package (we don't maintain any ubuntu packages so I'm not sure who to reach out to for that).

**Comment by enricostano** [comment]
> If it's the later you'll need to manually install that. It might even be worth having this as a dependency of the CLI in the APT package (we don't maintain any ubuntu packages so I'm not sure who to reach out to for that).

Yep, I guess that's issue. The version for `trusty` is really old also :disappointed: 

Will install using `pip`. Is that OK for a production environment?

Thanks for your help :smiley:

**Comment by jamesls** [comment]
No problem.  Installing with `pip` is a fully supported way of installing the AWS CLI.

Let us know if you're still running into issues.

**Comment by jhbez** [comment]
My solution was install groff  `sudo apt-get install groff`
