### ISSUE TITLE
1.11.0 requires s3transfer >= 0.1.5

### ISSUE THREAD

**Issue by mixja** [aws/aws-cli#2216]
The `setup.py` for version 1.11.0 currently specifies the following version requirements for `s3transfer`:

`s3transfer>=0.1.0,<0.2.0`

If you have s3transfer 0.1.4 or earlier from an earlier installation, the following exception will be thrown:

```
$ pip list | grep s3transfer
s3transfer (0.1.4)

$ aws --version
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 49, in main
    driver = create_clidriver()
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 58, in create_clidriver
    event_hooks=emitter)
  File "/usr/local/lib/python2.7/site-packages/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/usr/local/lib/python2.7/site-packages/awscli/plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "/usr/local/lib/python2.7/site-packages/awscli/handlers.py", line 66, in <module>
    from awscli.customizations.s3.s3 import s3_plugin_initialize
  File "/usr/local/lib/python2.7/site-packages/awscli/customizations/s3/s3.py", line 15, in <module>
    from awscli.customizations.s3.subcommands import ListCommand, WebsiteCommand, \
  File "/usr/local/lib/python2.7/site-packages/awscli/customizations/s3/subcommands.py", line 30, in <module>
    from awscli.customizations.s3.s3handler import S3Handler
  File "/usr/local/lib/python2.7/site-packages/awscli/customizations/s3/s3handler.py", line 27, in <module>
    from awscli.customizations.s3.results import UploadResultSubscriber
  File "/usr/local/lib/python2.7/site-packages/awscli/customizations/s3/results.py", line 19, in <module>
    from s3transfer.exceptions import CancelledError
ImportError: cannot import name CancelledError

$ pip install s3transfer --upgrade
Collecting s3transfer
...
Successfully installed s3transfer-0.1.5

$ aws --version
aws-cli/1.11.0 Python/2.7.12 Darwin/16.0.0 botocore/1.4.58
```

**Comment by kyleknap** [comment]
I can confirm the issue. I sent a PR to fix the dependency range.
