### ISSUE TITLE
Glacier upload-multipart-part fail to upload the last part

### ISSUE THREAD

**Issue by benjah1** [aws/aws-cli#2252]
According to the doc([1](http://docs.aws.amazon.com/amazonglacier/latest/dev/uploading-archive-mpu.html#qfacts), [2](http://docs.aws.amazon.com/cli/latest/userguide/cli-using-glacier.html#cli-using-glacier-initiate)), the last part can be < 1 MB, and the last part command is the same as the previous parts.

Error message,
```
An error occurred (InvalidParameterValueException) when calling the UploadMultipartPart operation: Content-Range: bytes 2793406464-2797600767/* is incompatible with Content-Length: 177964
```

Detail of the last part,
```
$ stat partzaaq
  File: 'partzaaq'
  Size: 177964          Blocks: 352        IO Block: 4096   regular file
Device: 70h/112d        Inode: 7631        Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-10-25 18:07:46.658959161 +0000
Modify: 2016-10-25 17:50:55.410413967 +0000
Change: 2016-10-25 17:50:55.410413967 +0000
 Birth: -
```

Full debug log,
```
2016-10-25 19:21:09,055 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.11.9 Python/2.7.12 Linux/3.13.0-93-generic botocore/1.4.66
2016-10-25 19:21:09,057 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['glacier', 'upload-multipart-part', '--region', 'us-east-1', '--body', 'partzaaq', '--range', 'bytes 2793406464-2797600767/*', '--account-id', '-', '--vault-name', 'bk_ben', '--upload-id', 'Enx5Yz9Q41T_ECesOqXfKfiwuDwJbP6Fp_XcCkf9TvY5rJwc9wIgNqKCiMAQl4jDBSvC2BcYmc-KbFIm9MXjNudnl6H7', '--debug']
2016-10-25 19:21:09,057 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7f1058fa2668>
2016-10-25 19:21:09,058 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f10593fe8c0>
2016-10-25 19:21:09,059 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2016-10-25 19:21:09,061 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python2.7/dist-packages/botocore/data/glacier/2012-06-01/service-2.json
2016-10-25 19:21:09,077 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.glacier: calling handler <function register_retries_for_service at 0x7f1059855758>
2016-10-25 19:21:09,077 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: glacier
2016-10-25 19:21:09,079 - MainThread - botocore.hooks - DEBUG - Event building-command-table.glacier: calling handler <function add_waiters at 0x7f1058faaa28>
2016-10-25 19:21:09,088 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'account-id', <awscli.arguments.CLIArgument object at 0x7f1058b7a710>), (u'vault-name', <awscli.arguments.CLIArgument object at 0x7f1058b7a750>), (u'upload-id', <awscli.arguments.CLIArgument object at 0x7f1058b7a790>), (u'checksum', <awscli.arguments.CLIArgument object at 0x7f1058b7a7d0>), (u'range', <awscli.arguments.CLIArgument object at 0x7f1058b7a810>), (u'body', <awscli.arguments.CLIArgument object at 0x7f1058b7a490>)])
2016-10-25 19:21:09,088 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.glacier.upload-multipart-part: calling handler <function add_streaming_output_arg at 0x7f1058fa2c80>
2016-10-25 19:21:09,089 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.glacier.upload-multipart-part: calling handler <function add_cli_input_json at 0x7f10594077d0>
2016-10-25 19:21:09,090 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.glacier.upload-multipart-part: calling handler <function unify_paging_params at 0x7f10590c6cf8>
2016-10-25 19:21:09,095 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python2.7/dist-packages/botocore/data/glacier/2012-06-01/paginators-1.json
2016-10-25 19:21:09,095 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.glacier.upload-multipart-part: calling handler <function add_generate_skeleton at 0x7f10590c02a8>
2016-10-25 19:21:09,095 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.glacier.upload-multipart-part: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7f1058b7a850>>
2016-10-25 19:21:09,096 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.glacier.upload-multipart-part: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f1058b7a8d0>>
2016-10-25 19:21:09,097 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.glacier.upload-multipart-part.account-id: calling handler <function uri_param at 0x7f1059425230>
2016-10-25 19:21:09,098 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.glacier.upload-multipart-part: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f105945a290>
2016-10-25 19:21:09,098 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'-' for parameter "account_id": u'-'
2016-10-25 19:21:09,098 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.glacier.upload-multipart-part.vault-name: calling handler <function uri_param at 0x7f1059425230>
2016-10-25 19:21:09,098 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.glacier.upload-multipart-part: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f105945a290>
2016-10-25 19:21:09,099 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'bk_ben' for parameter "vault_name": u'bk_ben'
2016-10-25 19:21:09,099 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.glacier.upload-multipart-part.upload-id: calling handler <function uri_param at 0x7f1059425230>
2016-10-25 19:21:09,100 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.glacier.upload-multipart-part: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f105945a290>
2016-10-25 19:21:09,100 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'Enx5Yz9Q41T_ECesOqXfKfiwuDwJbP6Fp_XcCkf9TvY5rJwc9wIgNqKCiMAQl4jDBSvC2BcYmc-KbFIm9MXjNudnl6H7' for parameter "upload_id": u'Enx5Yz9Q41T_ECesOqXfKfiwuDwJbP6Fp_XcCkf9TvY5rJwc9wIgNqKCiMAQl4jDBSvC2BcYmc-KbFIm9MXjNudnl6H7'
2016-10-25 19:21:09,100 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.glacier.upload-multipart-part.checksum: calling handler <function uri_param at 0x7f1059425230>
2016-10-25 19:21:09,100 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.glacier.upload-multipart-part.range: calling handler <function uri_param at 0x7f1059425230>
2016-10-25 19:21:09,101 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.glacier.upload-multipart-part: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f105945a290>
2016-10-25 19:21:09,101 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'bytes 2793406464-2797600767/*' for parameter "range": u'bytes 2793406464-2797600767/*'
2016-10-25 19:21:09,101 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.glacier.upload-multipart-part.body: calling handler <function uri_param at 0x7f1059425230>
2016-10-25 19:21:09,101 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.glacier.upload-multipart-part: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f105945a290>
2016-10-25 19:21:09,102 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'partzaaq' for parameter "body": <open file u'partzaaq', mode 'rb' at 0x7f105946adb0>
2016-10-25 19:21:09,102 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.glacier.upload-multipart-part.cli-input-json: calling handler <function uri_param at 0x7f1059425230>
2016-10-25 19:21:09,103 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.glacier.upload-multipart-part.generate-cli-skeleton: calling handler <function uri_param at 0x7f1059425230>
2016-10-25 19:21:09,103 - MainThread - botocore.hooks - DEBUG - Event calling-command.glacier.upload-multipart-part: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f1058b7a8d0>>
2016-10-25 19:21:09,104 - MainThread - botocore.hooks - DEBUG - Event calling-command.glacier.upload-multipart-part: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7f1058b7a850>>
2016-10-25 19:21:09,104 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2016-10-25 19:21:09,104 - MainThread - botocore.credentials - INFO - Found credentials in environment variables.
2016-10-25 19:21:09,105 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python2.7/dist-packages/botocore/data/endpoints.json
2016-10-25 19:21:09,130 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: glacier
2016-10-25 19:21:09,132 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.glacier: calling handler <function add_generate_presigned_url at 0x7f10598a7c08>
2016-10-25 19:21:09,133 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2016-10-25 19:21:09,140 - MainThread - botocore.endpoint - DEBUG - Setting glacier timeout as (60, 60)
2016-10-25 19:21:09,141 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.glacier.UploadMultipartPart: calling handler <function inject_account_id at 0x7f1059855f50>
2016-10-25 19:21:09,142 - MainThread - botocore.hooks - DEBUG - Event before-call.glacier.UploadMultipartPart: calling handler <function add_glacier_checksums at 0x7f1059856140>
2016-10-25 19:21:09,146 - MainThread - botocore.hooks - DEBUG - Event before-call.glacier.UploadMultipartPart: calling handler <function add_glacier_version at 0x7f1059856050>
2016-10-25 19:21:09,146 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=UploadMultipartPart) (verify_ssl=True) with params: {'body': <open file u'partzaaq', mode 'rb' at 0x7f105946adb0>, 'url': u'https://glacier.us-east-1.amazonaws.com/-/vaults/bk_ben/multipart-uploads/Enx5Yz9Q41T_ECesOqXfKfiwuDwJbP6Fp_XcCkf9TvY5rJwc9wIgNqKCiMAQl4jDBSvC2BcYmc-KbFIm9MXjNudnl6H7', 'headers': {'x-amz-glacier-version': u'2012-06-01', 'x-amz-content-sha256': 'ef26c4b0d55aeba4e0f63613e2aa0e278827ed6da6f6387cecac9e9ef69869f5', u'Content-Range': 'bytes 2793406464-2797600767/*', 'x-amz-sha256-tree-hash': u'ef26c4b0d55aeba4e0f63613e2aa0e278827ed6da6f6387cecac9e9ef69869f5', 'User-Agent': 'aws-cli/1.11.9 Python/2.7.12 Linux/3.13.0-93-generic botocore/1.4.66'}, 'context': {'client_region': u'us-east-1', 'has_streaming_input': True, 'client_config': <botocore.config.Config object at 0x7f1058a2ad10>}, 'query_string': {}, 'url_path': u'/-/vaults/bk_ben/multipart-uploads/Enx5Yz9Q41T_ECesOqXfKfiwuDwJbP6Fp_XcCkf9TvY5rJwc9wIgNqKCiMAQl4jDBSvC2BcYmc-KbFIm9MXjNudnl6H7', 'method': u'PUT'}
2016-10-25 19:21:09,147 - MainThread - botocore.hooks - DEBUG - Event request-created.glacier.UploadMultipartPart: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f1058a2ac90>>
2016-10-25 19:21:09,148 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2016-10-25 19:21:09,148 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
PUT
/-/vaults/bk_ben/multipart-uploads/Enx5Yz9Q41T_ECesOqXfKfiwuDwJbP6Fp_XcCkf9TvY5rJwc9wIgNqKCiMAQl4jDBSvC2BcYmc-KbFIm9MXjNudnl6H7

content-range:bytes 2793406464-2797600767/*
host:glacier.us-east-1.amazonaws.com
x-amz-content-sha256:ef26c4b0d55aeba4e0f63613e2aa0e278827ed6da6f6387cecac9e9ef69869f5
x-amz-date:20161025T192109Z
x-amz-glacier-version:2012-06-01
x-amz-sha256-tree-hash:ef26c4b0d55aeba4e0f63613e2aa0e278827ed6da6f6387cecac9e9ef69869f5

content-range;host;x-amz-content-sha256;x-amz-date;x-amz-glacier-version;x-amz-sha256-tree-hash
ef26c4b0d55aeba4e0f63613e2aa0e278827ed6da6f6387cecac9e9ef69869f5
2016-10-25 19:21:09,149 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20161025T192109Z
20161025/us-east-1/glacier/aws4_request
6dcbccc4a2d6c8a6f05776f89cbd27c885beb965578219245773ef3a4f999a8f
2016-10-25 19:21:09,149 - MainThread - botocore.auth - DEBUG - Signature:
f3085e2084e7fec468bd4ff87f694d4a57071ec5f148724c2df56a115b3677da
2016-10-25 19:21:09,157 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [PUT]>
2016-10-25 19:21:09,158 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): glacier.us-east-1.amazonaws.com
2016-10-25 19:21:09,545 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "PUT /-/vaults/bk_ben/multipart-uploads/Enx5Yz9Q41T_ECesOqXfKfiwuDwJbP6Fp_XcCkf9TvY5rJwc9wIgNqKCiMAQl4jDBSvC2BcYmc-KbFIm9MXjNudnl6H7 HTTP/1.1" 400 158
2016-10-25 19:21:09,549 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-requestid': '1WiyXdidrkPNO-D1DHbf4JCIlrzSpBPuBzagZZ9kgnzF5uc', 'date': 'Tue, 25 Oct 2016 19:21:07 GMT', 'content-length': '158', 'content-type': 'application/json', 'connection': 'close'}
2016-10-25 19:21:09,550 - MainThread - botocore.parsers - DEBUG - Response body:
{"code":"InvalidParameterValueException","message":"Content-Range: bytes 2793406464-2797600767/* is incompatible with Content-Length: 177964","type":"Client"}
2016-10-25 19:21:09,551 - MainThread - botocore.hooks - DEBUG - Event needs-retry.glacier.UploadMultipartPart: calling handler <botocore.retryhandler.RetryHandler object at 0x7f1058c117d0>
2016-10-25 19:21:09,552 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2016-10-25 19:21:09,552 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 186, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 381, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 551, in __call__
    call_parameters, parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 675, in invoke
    **parameters)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (InvalidParameterValueException) when calling the UploadMultipartPart operation: Content-Range: bytes 2793406464-2797600767/* is incompatible with Content-Length: 177964
2016-10-25 19:21:09,554 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

An error occurred (InvalidParameterValueException) when calling the UploadMultipartPart operation: Content-Range: bytes 2793406464-2797600767/* is incompatible with Content-Length: 177964
```

**Comment by JordonPhillips** [comment]
I'm not sure, it looks like the CLI is sending everything correctly. I would recommend asking about it on the [service forum](), they should be able to help you out. If you give them the request id (`1WiyXdidrkPNO-D1DHbf4JCIlrzSpBPuBzagZZ9kgnzF5uc`) they might be able to give you specifics on the particular request.

**Comment by freehot** [comment]
I notice that the file size of the the last multipart should be different to all others. So that, I have amended the scripts as below, hope this can help:

# Get info of the last file
MyLastFile=$(du ./part* -hab | sort -n -r |tail -n 1)
MyCursorLocation=$(expr index "$MyLastFile" './')
MyLastFileName=echo ${MyLastFile:MyCursorLocation+1}
MyLastFileSize=echo ${MyLastFile::MyCursorLocation-2}

# create upload commands to be run in parallel and store in commands.txt
i=0
for f in $files
  do
     byteStart=$((i*byteSize))
        if [ $f == $MyLastFileName ] ; then
             byteEnd=$((i*byteSize+MyLastFileSize-1))
        else
             byteEnd=$((i*byteSize+byteSize-1))
        fi
     echo aws glacier upload-multipart-part --body $f --range "'"'bytes '"$byteStart"'-'"$byteEnd"'/*'"'" --account-id - --vault-name myvault1 --up$
     i=$(($i+1))

  done

**Comment by freehot** [comment]
I have noticed that the size of the the last multipart upload file should be different to all others. So that, I have amended the scripts as below, hope this can help:

#Get info of the last file
MyLastFile=$(du ./part* -hab | sort -n -r |tail -n 1)
MyCursorLocation=$(expr index "$MyLastFile" './')
MyLastFileName=${MyLastFile:MyCursorLocation+1}
MyLastFileSize=${MyLastFile::MyCursorLocation-2}

#create upload commands to be run in parallel and store in commands.txt
i=0
for f in $files
do
byteStart=$((ibyteSize))
if [ $f == $MyLastFileName ] ; then
byteEnd=$((ibyteSize+MyLastFileSize-1))
else
byteEnd=$((ibyteSize+byteSize-1))
fi
echo aws glacier upload-multipart-part --body $f --range "'"'bytes '"$byteStart"'-'"$byteEnd"'/'"'" --account-id - --vault-name myvault1 --up$
i=$(($i+1))

done
