### ISSUE TITLE
Improve "region" validation

### ISSUE THREAD

**Issue by mrenoch** [aws/aws-cli#2266]
HI, 

I got stuck in a pretty bad debugging loop based on a very misleading error message. 

I had set my region as us-east-1d, not us-east-1. Somehow this resulted in an SSL Protocol Unknown exception (requests.exceptions.args SSL UNKNOWN_PROTOCOL). This led me down a rabbit hole of installing certifi, wondering if the python3 vs python2 version was an issue, etc etc. 

I see there is even a stub which is supposed to do some region validation, but it only checks that the region exists:

https://github.com/aws/aws-cli/blob/develop/awscli/customizations/codedeploy/utils.py#L48

Is there a way to make this more robust? I don't know what patterns are valid regions, or if there is a way to check at runtime, but there must be a better way to handle an error like mine. 

I'm game to try to help improve this so others don't get stuck like I do, but I am not certain how.

tnx

**Comment by stealthycoin** [comment]
We do have some region validation available in botocore and boto3 which currently isn't used in the cli. Might be worth looking into moving that over.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by phgogo** [comment]
Any Updates on this? This is definetly still an error running `aws-cli/2.0.4 Python/3.7.3 Linux/3.10.0-1062.12.1.el7.x86_64 botocore/2.0.0dev8` on `Red Hat Enterprise Linux Server release 7.7 (Maipo)`

Using a fresh aws-cli install behind a proxy with the following command:
`aws  --no-verify-ssl s3 cp s3://any-given-bucket/example.txt .`

Even if Proxy Env-Vars are configured correctly, you'll get the following error:
`Failed to connect to proxy URL: "http://proxyuser:PROXYPASS@A.B.C.D:8080"`

Or with Debug:
```

2020-03-20 16:25:23,597 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): A.B.C.D:8080
2020-03-20 16:25:23,605 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 672, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 421, in _make_request
  File "<string>", line 3, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 416, in _make_request
  File "http/client.py", line 1321, in getresponse
  File "http/client.py", line 296, in begin
  File "http/client.py", line 265, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/botocore/httpsession.py", line 263, in send
  File "site-packages/urllib3/connectionpool.py", line 720, in urlopen
  File "site-packages/urllib3/util/retry.py", line 376, in increment
  File "site-packages/urllib3/packages/six.py", line 734, in reraise
  File "site-packages/urllib3/connectionpool.py", line 672, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 421, in _make_request
  File "<string>", line 3, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 416, in _make_request
  File "http/client.py", line 1321, in getresponse
  File "http/client.py", line 296, in begin
  File "http/client.py", line 265, in _read_status
urllib3.exceptions.ProxyError: ('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/awscli/clidriver.py", line 335, in main
  File "site-packages/awscli/customizations/commands.py", line 197, in __call__
  File "site-packages/awscli/customizations/commands.py", line 190, in __call__
  File "site-packages/awscli/customizations/s3/subcommands.py", line 709, in _run_main
  File "site-packages/awscli/customizations/s3/subcommands.py", line 480, in _run_main
  File "site-packages/awscli/customizations/s3/subcommands.py", line 473, in get_client
  File "site-packages/botocore/session.py", line 775, in create_client
  File "site-packages/botocore/session.py", line 824, in _resolve_region_name
  File "site-packages/botocore/session.py", line 234, in get_config_variable
  File "site-packages/botocore/configprovider.py", line 281, in get_config_variable
  File "site-packages/botocore/configprovider.py", line 378, in provide
  File "site-packages/awscli/utils.py", line 59, in provide
  File "site-packages/awscli/utils.py", line 64, in _get_instance_metadata_region
  File "site-packages/awscli/utils.py", line 104, in retrieve_region
  File "site-packages/awscli/utils.py", line 115, in _get_region
  File "site-packages/botocore/utils.py", line 264, in _get_request
  File "site-packages/botocore/httpsession.py", line 285, in send
botocore.exceptions.ProxyConnectionError: Failed to connect to proxy URL: "http://proxyuser:PROXYPASS@A.B.C.D:8080"
2020-03-20 16:25:23,606 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Failed to connect to proxy URL: "http://proxyuser:PROXYPASS@A.B.C.D:8080"

```

The actual problem (in my case) was a missing `--region "eu-central-1" `

**Comment by domjoseph-flg** [comment]
I am getting this error while trying to run this in cli

`aws ecr get-login-password --region ap-southeast-2`

`Could not connect to the endpoint URL: "https://api.ecr.ap-southeast-2.amazonaws.com/"`

I cannot ping the domain as well as NS lookup is timing out.

**Comment by tim-finnigan** [comment]
Checking in as there hasn't been any activity on this issue in a while. The original issue referenced CodeDeploy and included a link to a line in code which is no longer valid as it wasn't a permalink. Also I think a couple of the comments here may not be related to the original issue. Can anyone provide an updated link to the problem in the code or a reproducible example of the issue?

**Comment by tstibbs** [comment]
@tim-finnigan I believe this issue is wider than codedeploy.

To reproduce (could be any API call, this one chosen for a simple example):
```
aws --region eu-wets-2 sts get-caller-identity
```
Actual output:
```
Could not connect to the endpoint URL: "https://sts.eu-wets-2.amazonaws.com/"
```
Ideal output:
```
Region 'eu-wets-2' does not exist.
```

The reason I care about this issue is that you can easily typo the region names in a way that isn't easy to spot, and then waste a bunch of time looking at networking settings trying to work out what it can't contact that URL. If it told you that this was because the region name you'd given was invalid, you'd fix it and move on in a matter of seconds.

**Comment by tim-finnigan** [comment]
Thanks @tstibbs for following up and expanding on the problem here. I see what you're saying and also think there could be a better mechanism in place for validating regions and communicating issues to users in scenarios like the one you described.
