### ISSUE TITLE
s3 mv exits with 0 status when it fails to actually remove local file

### ISSUE THREAD

**Issue by gpaszkowski-rmn** [aws/aws-cli#2282]
The s3 mv command exits with status 0 even though it wasn't able to remove the local file due to a permission issue.  I can only replicate this with a large (~5GB ~700 part) file. The command exits with a '1' when trying to replicate with a small non multi-part upload.  

Some debug logs:

`aws s3 mv /path/to/somefile.zip s3://mybucket/`
```2016-11-11 19:14:21,407 - Thread-11 - awscli.customizations.s3.tasks - DEBUG - Removing local file: /path/to/somefile.zip
2016-11-11 19:14:21,407 - Thread-11 - awscli.customizations.s3.executor - DEBUG - Error calling task: [Errno 13] Permission denied: '/path/to/somefile.zip'
Traceback (most recent call last):
  File "/usr/share/awscli/awscli/customizations/s3/executor.py", line 226, in run
    function()
  File "/usr/share/awscli/awscli/customizations/s3/tasks.py", line 549, in __call__
    os.remove(self._local_filename)
PermissionError: [Errno 13] Permission denied: '/path/to/somefile.zip'
2016-11-11 19:14:21,407 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-7, stopped daemon 140104425260800)>
2016-11-11 19:14:21,407 - Thread-1 - awscli.customizations.s3.executor - DEBUG - Received print task: PrintTask(message='move: ../..//path/to/somefile.zip to s3://mybucket/somefile.zip', error=False, total_parts=None, warning=None)
move: ../../path/to/somefile.zip to s3://mybucket/somefile.zip
2016-11-11 19:14:21,411 - Thread-11 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-11-11 19:14:21,411 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-7, stopped daemon 140104425260800)>
2016-11-11 19:14:21,411 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-8, stopped daemon 140104416868096)>
2016-11-11 19:14:21,411 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-8, stopped daemon 140104416868096)>
2016-11-11 19:14:21,411 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-9, stopped daemon 140104408475392)>
2016-11-11 19:14:21,411 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-9, stopped daemon 140104408475392)>
2016-11-11 19:14:21,411 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-10, stopped daemon 140104400082688)>
2016-11-11 19:14:21,412 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-10, stopped daemon 140104400082688)>
2016-11-11 19:14:21,412 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-11, stopped daemon 140103913568000)>
2016-11-11 19:14:21,412 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-11, stopped daemon 140103913568000)>
2016-11-11 19:14:21,412 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-12, stopped daemon 140103905175296)>
2016-11-11 19:14:21,412 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-12, stopped daemon 140103905175296)>
2016-11-11 19:14:21,412 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-13, stopped daemon 140103896782592)>
2016-11-11 19:14:21,412 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-13, stopped daemon 140103896782592)>
2016-11-11 19:14:21,412 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-14, stopped daemon 140103888389888)>
2016-11-11 19:14:21,412 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-14, stopped daemon 140103888389888)>
2016-11-11 19:14:21,412 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for result thread.
2016-11-11 19:14:21,412 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for IO thread.
2016-11-11 19:14:21,412 - Thread-1 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in print thread, shutting down print thread.
2016-11-11 19:14:21,412 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for result thread to shutdown.
2016-11-11 19:14:21,413 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for IO thread to shutdown.
2016-11-11 19:14:21,413 - Thread-2 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in IO thread, shutting down.
2016-11-11 19:14:21,413 - MainThread - awscli.customizations.s3.executor - DEBUG - All threads have been shutdown.
root@my-server:/home/myuser# echo $?
0
```
Expected behavior seen for small non-multipart file:
`aws s3 mv /tmp/deleteme s3://mybucket/`
```
2016-11-11 19:16:08,500 - Thread-5 - awscli.customizations.s3.tasks - DEBUG - [Errno 1] Operation not permitted: '/tmp/deleteme'
Traceback (most recent call last):
  File "/usr/share/awscli/awscli/customizations/s3/tasks.py", line 95, in _execute_task
    getattr(filename, filename.operation_name)(**kwargs)
  File "/usr/share/awscli/awscli/customizations/s3/fileinfo.py", line 346, in move
    self.delete()
  File "/usr/share/awscli/awscli/customizations/s3/fileinfo.py", line 330, in delete
    os.remove(self.src)
PermissionError: [Errno 1] Operation not permitted: '/tmp/deleteme'
2016-11-11 19:16:08,502 - Thread-5 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-11-11 19:16:08,502 - Thread-1 - awscli.customizations.s3.executor - DEBUG - Received print task: PrintTask(message="move failed: ../../tmp/deleteme to s3://mybucket/deleteme [Errno 1] Operation not permitted: '/tmp/deleteme'", error=True, total_parts=None, warning=None)
move failed: ../../tmp/deleteme to s3://mybucket/deleteme [Errno 1] Operation not permitted: '/tmp/deleteme'
2016-11-11 19:16:08,502 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-5, stopped daemon 140619703904000)>
2016-11-11 19:16:08,503 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-6, stopped daemon 140619695511296)>
2016-11-11 19:16:08,503 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-6, stopped daemon 140619695511296)>
2016-11-11 19:16:08,503 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-7, stopped daemon 140619687118592)>
2016-11-11 19:16:08,503 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-7, stopped daemon 140619687118592)>
2016-11-11 19:16:08,503 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-8, stopped daemon 140619678725888)>
2016-11-11 19:16:08,503 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-8, stopped daemon 140619678725888)>
2016-11-11 19:16:08,503 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-9, stopped daemon 140619670333184)>
2016-11-11 19:16:08,503 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-9, stopped daemon 140619670333184)>
2016-11-11 19:16:08,504 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-10, stopped daemon 140619661940480)>
2016-11-11 19:16:08,504 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-10, stopped daemon 140619661940480)>
2016-11-11 19:16:08,504 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-11, stopped daemon 140619175425792)>
2016-11-11 19:16:08,504 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-11, stopped daemon 140619175425792)>
2016-11-11 19:16:08,504 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-12, stopped daemon 140619167033088)>
2016-11-11 19:16:08,504 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-12, stopped daemon 140619167033088)>
2016-11-11 19:16:08,504 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-13, stopped daemon 140619158640384)>
2016-11-11 19:16:08,504 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-13, stopped daemon 140619158640384)>
2016-11-11 19:16:08,505 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-14, stopped daemon 140619150247680)>
2016-11-11 19:16:08,505 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-14, stopped daemon 140619150247680)>
2016-11-11 19:16:08,505 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for result thread.
2016-11-11 19:16:08,505 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for IO thread.
2016-11-11 19:16:08,505 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for result thread to shutdown.
2016-11-11 19:16:08,505 - Thread-2 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in IO thread, shutting down.
2016-11-11 19:16:08,505 - Thread-1 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in print thread, shutting down print thread.
2016-11-11 19:16:08,506 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for IO thread to shutdown.
2016-11-11 19:16:08,506 - MainThread - awscli.customizations.s3.executor - DEBUG - All threads have been shutdown.
root@myserver:/# echo $?
1
```

**Comment by jamesls** [comment]
What version of the CLI are you using?  This should be fixed in later versions.  When I try this on a large file on `1.11.14` I get a non zero RC as expected.

**Comment by gpaszkowski-rmn** [comment]
```aws-cli/1.10.1 Python/3.5.2 Linux/4.4.0-31-generic botocore/1.3.23``` which looks to be the latest on Ubuntu but I can grab 1.11 via pip.  Thank you!

**Comment by kyleknap** [comment]
It looks like this issue is resolved by upgrading. Please reopen if you are still seeing the issue.
