### ISSUE TITLE
Error parsing parameter '--logins': Expected: '=', received: '/'

### ISSUE THREAD

**Issue by simoami** [aws/aws-cli#2298]
[get-credentials-for-identity](http://docs.aws.amazon.com/cli/latest/reference/cognito-identity/get-credentials-for-identity.html) is failing because the `--login` map key contains a forward '/':
```
aws cognito-identity get-credentials-for-identity --profile serverless-admin --region us-east-1  --identity-id us-east-1:80ca1eea-3d5a-40c5-837f-1cc3863ecda6 --logins cognito-idp.us-east-1.amazonaws.com/us-east-1_k8yIVRHKG=eyJraW...
```

```
aws --version
aws-cli/1.11.21 Python/2.7.10 Darwin/15.6.0 botocore/1.4.78
```

**Comment by JordonPhillips** [comment]
I'm unable to repro with that snippet, could you please append `--debug 2>&1 | grep "Arguments entered"`? That should grab the arguments post shell processing so we can see what's actually going on. The url should be a single string.

**Comment by simoami** [comment]
```
2016-11-28 15:29:23,357 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['cognito-identity', 'get-credentials-for-identity', '--profile', 'serverless-admin', '--region', 'us-east-1', '--identity-id', 'us-east-1:80ca1eea-3d5a-40c5-837f-1cc3863ecda6', '--logins', 'cognito-idp.us-east-1.amazonaws.com/us-east-1_k8yIVRHKG=eyJraW...', '--debug']
```

**Comment by simoami** [comment]
more verbose log:
```
2016-11-28 15:31:38,062 - MainThread - awscli.argprocess - DEBUG - Parsing param --logins as shorthand
2016-11-28 15:31:38,062 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 186, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 381, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 522, in __call__
    parsed_args, self.arg_table)
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 578, in _build_call_parameters
    arg_object.add_to_params(service_params, value)
  File "/Library/Python/2.7/site-packages/awscli/arguments.py", line 453, in add_to_params
    unpacked = self._unpack_argument(value)
  File "/Library/Python/2.7/site-packages/awscli/arguments.py", line 463, in _unpack_argument
    cli_argument=self, value=value)
  File "/Library/Python/2.7/site-packages/awscli/arguments.py", line 476, in _emit_first_response
    responses = self._emit(name, **kwargs)
  File "/Library/Python/2.7/site-packages/awscli/arguments.py", line 473, in _emit
    return self._event_emitter.emit(name, **kwargs)
  File "/Library/Python/2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Library/Python/2.7/site-packages/awscli/argprocess.py", line 317, in __call__
    cli_argument, value, service_name, operation_name)
  File "/Library/Python/2.7/site-packages/awscli/argprocess.py", line 341, in _parse_as_shorthand
    raise ParamError(cli_argument.cli_name, str(e))
ParamError: Error parsing parameter '--logins': Expected: '=', received: '/' for input:
cognito-idp.us-east-1.amazonaws.com/us-east-1_k8yIVRHKG=eyJraW...
                                   ^
2016-11-28 15:31:38,063 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Error parsing parameter '--logins': Expected: '=', received: '/' for input:
cognito-idp.us-east-1.amazonaws.com/us-east-1_k8yIVRHKG=eyJraW...
```

**Comment by stealthycoin** [comment]
Looks like --logins takes key=value pairs whereas you are just providing a URL.

From `aws cognito-identity get-credentials-for-identity help`
 Shorthand Syntax:
          KeyName1=string,KeyName2=string

A set of optional name-value pairs that map provider names to provider tokens.

**Comment by simoami** [comment]
Hi @stealthycoin The key is exactly what I posted in the command:
key: cognito-idp.us-east-1.amazonaws.com/us-east-1_k8yIVRHKG
value: eyJraW... (truncated)

If you read the error, it is complaining that the key contains a forward '/'. it is not complaining that it's a url. Moreover, the key "graph.facebook.com" works for a different identity and it is a url as you can see. 

I think the issue is with the AWS command not properly allowing certain characters like '/' in the key but unfortunately that is how it got generated.

**Comment by simoami** [comment]
Here's a reference to the identity key which is in par with the one used in the aws command: 
http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-integrating-user-pools-with-identity-pools.html
```
Logins: {
  'cognito-idp.<region>.amazonaws.com/<YOUR_USER_POOL_ID>': result.getIdToken().getJwtToken()
}
```

**Comment by rosenk** [comment]
Any progress, I'm having the same problem: 
`'--logins': Expected: '=', received: '/' for input:`
The problem is that the providerName contains '/' and I don't know how to escape it

**Comment by simoami** [comment]
@JordonPhillips Any progress? This has been open since November and not even acknowledged as an issue, despite it being straightforward. The Cognito team wants the KEY to be a URL. I did point out the official docs confirming it. Do you want to consult with the cognito team please and confirm it internally?

**Comment by simoami** [comment]
@behrooziAWS Can you please confirm the cli command has a limitation of not being able to take urls as valid keys for the `--logins` argument? Cognito by design requires it.

Demo:
```
aws cognito-identity get-credentials-for-identity --profile serverless-admin --region us-east-1  --identity-id us-east-1:80ca1eea-3d5a-40c5-837f-1cc3863ecda1 --logins cognito-idp.us-east-1.amazonaws.com/us-east-1_k8yIVRHKG=eyJraWQiOiJ6TUJuMHU3a0licXNVQk51WDVtZmpmR3Vwb3dXUzFVN2tsYXRZR2JNcE9NPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJhNmUwZjRhOS1hZDFhLTRjNTktOWYzMi1lZDg5MmJhYzEwZWUiLCJhdWQiOiIxMnUzMTRycWo1dm5rcTViaDhhamE2dmJudSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE0Nzg3MjQ2OTIsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX2s4eUlWUkhLRyIsImNvZ25pdG86dXNlcm5hbWUiOiJzaW1vQHdlYmludmVudGluYy5jb20iLCJleHAiOjE0Nzg3MjgyOTIsImlhdCI6MTQ3ODcyNDY5MiwiZW1haWwiOiJzaW1vQHdlYmludmVudGluYy5jb20ifQ.L5SbBmiVi9n9aHsS_7163_OezNfh7UdSKdT9MmMQpl4q51uqspTL5az0a1AtGGbXApOrVmfd7eEooEz4HgsQGk3lC-g-ReS0qcwKeB74f-vLbMcjRdhdg9Clmj7ohTuchCxT3WMweonmsTcjj6WCmeKUTmzJSXrIL8pNS4FkLQTWr8n6VMOKabYMC0JY0mmPa_gnHm9oQjmSwwmndKXyRYElICai4pXrLt6WW_wRidQMPsoUTiW_wBAl7Hnzgm0fKY0va21a6fs-TJ4cufBL9rsKgSxHUPsMdxNQl3WVa0x6oGDCA3Izz5Go4cQsHmcTlaSGX0DZGi20Xgry1qNY0a

Error parsing parameter '--logins': Expected: '=', received: '/' for input:
cognito-idp.us-east-1.amazonaws.com/us-east-1_k8yIVRHKG=eyJraWQiOiJ6TUJuMHU3a0licXNVQk51WDVtZmpmR3Vwb3dXUzFVN2tsYXRZR2JNcE9NPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJhNmUwZjRhOS1hZDFhLTRjNTktOWYzMi1lZDg5MmJhYzEwZWUiLCJhdWQiOiIxMnUzMTRycWo1dm5rcTViaDhhamE2dmJudSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE0Nzg3MjQ2OTIsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX2s4eUlWUkhLRyIsImNvZ25pdG86dXNlcm5hbWUiOiJzaW1vQHdlYmludmVudGluYy5jb20iLCJleHAiOjE0Nzg3MjgyOTIsImlhdCI6MTQ3ODcyNDY5MiwiZW1haWwiOiJzaW1vQHdlYmludmVudGluYy5jb20ifQ.L5SbBmiVi9n9aHsS_7163_OezNfh7UdSKdT9MmMQpl4q51uqspTL5az0a1AtGGbXApOrVmfd7eEooEz4HgsQGk3lC-g-ReS0qcwKeB74f-vLbMcjRdhdg9Clmj7ohTuchCxT3WMweonmsTcjj6WCmeKUTmzJSXrIL8pNS4FkLQTWr8n6VMOKabYMC0JY0mmPa_gnHm9oQjmSwwmndKXyRYElICai4pXrLt6WW_wRidQMPsoUTiW_wBAl7Hnzgm0fKY0va21a6fs-TJ4cufBL9rsKgSxHUPsMdxNQl3WVa0x6oGDCA3Izz5Go4cQsHmcTlaSGX0DZGi20Xgry1qNY0a
```

**Comment by simoami** [comment]
Checking again for any updates?

**Comment by kyleknap** [comment]
To unblock yourself, could you use the JSON syntax?

```
aws cognito-identity get-credentials-for-identity --region us-east-1  --identity-id us-east-1:80ca1eea-3d5a-40c5-837f-1cc3863ecda1 --logins='{"cognito-idp.us-east-1.amazonaws.com/us-east-1_k8yIVRHKG":"eyJraWQiOiJ6TUJuMHU3a0licXNVQk51WDVtZmpmR3Vwb3dXUzFVN2tsYXRZR2JNcE9NPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJhNmUwZjRhOS1hZDFhLTRjNTktOWYzMi1lZDg5MmJhYzEwZWUiLCJhdWQiOiIxMnUzMTRycWo1dm5rcTViaDhhamE2dmJudSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE0Nzg3MjQ2OTIsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX2s4eUlWUkhLRyIsImNvZ25pdG86dXNlcm5hbWUiOiJzaW1vQHdlYmludmVudGluYy5jb20iLCJleHAiOjE0Nzg3MjgyOTIsImlhdCI6MTQ3ODcyNDY5MiwiZW1haWwiOiJzaW1vQHdlYmludmVudGluYy5jb20ifQ.L5SbBmiVi9n9aHsS_7163_OezNfh7UdSKdT9MmMQpl4q51uqspTL5az0a1AtGGbXApOrVmfd7eEooEz4HgsQGk3lC-g-ReS0qcwKeB74f-vLbMcjRdhdg9Clmj7ohTuchCxT3WMweonmsTcjj6WCmeKUTmzJSXrIL8pNS4FkLQTWr8n6VMOKabYMC0JY0mmPa_gnHm9oQjmSwwmndKXyRYElICai4pXrLt6WW_wRidQMPsoUTiW_wBAl7Hnzgm0fKY0va21a6fs-TJ4cufBL9rsKgSxHUPsMdxNQl3WVa0x6oGDCA3Izz5Go4cQsHmcTlaSGX0DZGi20Xgry1qNY0a"}'
```
That works for me.

I am still trying to figure out how to escape properly for the shorthand syntax and a map type.

**Comment by didac-pf** [comment]
I got here by searching my problem, so I leave my solution here for future visitors.

On Windows the JSON needs to be written like this:
`--expression-attribute-values "{\":id\":{\"S\":\"231fef-23f2\"}}"`

Note the **\"** escape. Hope it helps someone.

**Comment by makuraso123** [comment]
> Llegué buscando mi problema, así que dejo mi solución aquí para futuros visitantes.
> 
> En Windows, el JSON debe escribirse así:
> `--expression-attribute-values "{\":id\":{\"S\":\"231fef-23f2\"}}"`
> 
> Tenga en cuenta el `\"`escape. Espero que ayude a alguien.

Thanks you bro
