### ISSUE TITLE
SSL Error - [Errno 8] EOF occurred in violation of protocol when specifying endpoint

### ISSUE THREAD

**Issue by tylerhartley** [aws/aws-cli#2299]
I recently upgraded my machine from awscli 1.9.13 to 1.11.20. This box is running Ubuntu 14.04 and Python 2.7.6. Previously, this command was working just fine (note the use of an endpoint proxy):

```
aws --endpoint https://my-endpoint.com s3 sync --sse AES256 directory s3://my.bucket
```

After upgrading to 1.11.20, however, I get `fatal error: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol`. Running with --debug, I get:

```
2016-11-28 17:29:16,011 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): my-endpoint
2016-11-28 17:29:16,080 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "GET /my.bucket?prefix=&encoding-type=url HTTP/1.1" 301 185
2016-11-28 17:29:16,082 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): my-endpoint
2016-11-28 17:29:16,164 - MainThread - botocore.endpoint - DEBUG - ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 204, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/sessions.py", line 594, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/sessions.py", line 196, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
```

Removing the endpoint flag results in a successful operation. 

Output of `aws --version` is `aws-cli/1.11.20 Python/2.7.6 Linux/4.4.0-47-generic botocore/1.4.77`

I've tried a variety of things, including [upgrading `requests`](https://github.com/kennethreitz/requests/issues/3006), though [this issue](https://github.com/aws/aws-cli/issues/1094) made me feel like that wasn't necessary. Simply getting the proxy url with `requests` also succeeds ala `requests.get('https://my-endpoint.com')` [200]

**Comment by tylerhartley** [comment]
In further testing, I discovered that an upgrade to python 2.7.9 from 2.7.6 resolved this problem. However, I want to find a solution that doesn't require me to do this for my production machines. What's the underlying issue here? Thanks.

**Comment by tylerhartley** [comment]
Further investigation shows that the breaking change occurs in awscli version 1.10.8. 1.10.7 works fine. None of the [additions to the changelog for .8](https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst#1108) seem relevant to this underlying ssl issue. .8 does include a bump in botocore from 1.3.29 to 1.3.30, which also has no red flags.

**Comment by JordonPhillips** [comment]
This is possibly related to boto/botocore#803. We deliberately disable pyopenssl because it uses a non-standard implementation that causes fairly frequent errors across python versions when interacting with a number of our services (particularly s3).

The disadvantage of doing that is that pyopenssl provided a few backports, namely SNI support. It seems that it may also patch out this particular bug as well.

The bug in question seems to be that, prior to 2.7.9, python defaults to using TLSv2 and doesn't properly detect TLSv1. This hasn't been a problem for AWS because our services all support TLSv2.

I don't think we would want to re-enable pyopenssl since it causes far more problems for us than it solves. So to move forward, you can do one of the following:

* Upgrade python to 2.7.9
* Use http instead of https (do not recommend)

It's also worth noting that we don't yet officially support proxies.

**Comment by tylerhartley** [comment]
Ok. It sounds like this won't be resolved via awscli so I'll need to either a) adjust my proxy or b) upgrade to 2.7.9 as per your comment. 

Closing unless anyone has any ideas that don't require a) or b).

**Comment by ricoli** [comment]
This also occurs when using python 2.7.10 by the way
