### ISSUE TITLE
No module named 'yaml'

### ISSUE THREAD

**Issue by chgangaraju** [aws/aws-cli#2315]
aws cli working till yesterday and facing this issue today. I run a `dnf upgrade` which might upgraded aws-cli package.

```
➜  ~ aws ecr get-login
Traceback (most recent call last):
  File "/usr/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/lib/python3.5/site-packages/awscli/clidriver.py", line 53, in main
    driver = create_clidriver()
  File "/usr/lib/python3.5/site-packages/awscli/clidriver.py", line 62, in create_clidriver
    event_hooks=emitter)
  File "/usr/lib/python3.5/site-packages/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/usr/lib/python3.5/site-packages/awscli/plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "/usr/lib/python3.5/site-packages/awscli/handlers.py", line 27, in <module>
    from awscli.customizations.cloudformation import initialize as cloudformation_init
  File "/usr/lib/python3.5/site-packages/awscli/customizations/cloudformation/__init__.py", line 13, in <module>
    from awscli.customizations.cloudformation.package import PackageCommand
  File "/usr/lib/python3.5/site-packages/awscli/customizations/cloudformation/package.py", line 21, in <module>
    from awscli.customizations.cloudformation.artifact_exporter import Template
  File "/usr/lib/python3.5/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 25, in <module>
    from awscli.customizations.cloudformation.yamlhelper import yaml_dump, \
  File "/usr/lib/python3.5/site-packages/awscli/customizations/cloudformation/yamlhelper.py", line 14, in <module>
    import yaml
ImportError: No module named 'yaml'
```

```
➜  ~ sudo dnf install awscli       
Package awscli-1.11.24-1.fc25.noarch is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
 ~ sudo pip install pyyaml            
Requirement already satisfied: pyyaml in /usr/lib64/python2.7/site-packages
```

**Comment by chgangaraju** [comment]
I resolved it by running
`sudo dnf install python3-PyYAML   `

**Comment by kyleknap** [comment]
@chgangaraju 
It looks like there may be an issue with the way the linux distro is packaging the ``awscli``. We recently introduced ``PyYaml`` as a dependency so it may not have been included when it got packaged? I would recommend contacting the maintainers of the distro to get this updated as we do not manage any of the CLI  packages in the various Linux distros; those are maintained by the individuals who maintain the distros. If you install the CLI via any of the methods listed [here](http://docs.aws.amazon.com/cli/latest/userguide/installing.html), you should have no issues as these are the installation methods that we actively manage/maintain.

Let us know if you have anymore questions.

**Comment by chgangaraju** [comment]
@kyleknap , You can close this issue now. Thanks for the clarification. 

I thought you guys were maintaining this rpm package. Hope RPM maintainers will add `python3-PyYAML` dependency.

**Comment by sivasadhu** [comment]
@chgangaraju  related: https://bugzilla.redhat.com/show_bug.cgi?id=1448936
