### ISSUE TITLE
exception after installing to Ubuntu 14.04 through apt

### ISSUE THREAD

**Issue by vitaly-zdanevich** [aws/aws-cli#2353]
```
$ aws
Traceback (most recent call last):
  File "/usr/bin/aws", line 23, in <module>
    sys.exit(main())
  File "/usr/bin/aws", line 19, in main
    return awscli.clidriver.main()
  File "/usr/share/awscli/awscli/clidriver.py", line 44, in main
    driver = create_clidriver()
  File "/usr/share/awscli/awscli/clidriver.py", line 53, in create_clidriver
    event_hooks=emitter)
  File "/usr/share/awscli/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/usr/share/awscli/awscli/plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "/usr/share/awscli/awscli/handlers.py", line 24, in <module>
    from awscli.customizations.ec2addcount import ec2_add_count
  File "/usr/share/awscli/awscli/customizations/ec2addcount.py", line 16, in <module>
    from botocore.parameters import StringParameter
ImportError: No module named 'botocore.parameters'

```

```
$ sudo apt install awscli
[sudo] password for vitaly: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  docutils-common python3-bcdoc python3-botocore python3-chardet
  python3-colorama python3-dateutil python3-docutils python3-jmespath
  python3-pil python3-ply python3-pygments python3-requests python3-roman
  python3-rsa python3-six python3-urllib3
Suggested packages:
  texlive-latex-recommended texlive-latex-base texlive-lang-french
  fonts-linuxlibertine ttf-linux-libertine docutils-doc python-pil-doc
  python3-pil-dbg python-ply-doc
The following NEW packages will be installed:
  awscli docutils-common python3-bcdoc python3-botocore python3-chardet
  python3-colorama python3-dateutil python3-docutils python3-jmespath
  python3-pil python3-ply python3-pygments python3-requests python3-roman
  python3-rsa python3-six python3-urllib3
0 upgraded, 17 newly installed, 0 to remove and 0 not upgraded.
Need to get 2,215 kB of archives.
After this operation, 19.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://by.archive.ubuntu.com/ubuntu/ trusty-updates/main python3-six all 1.5.2-1ubuntu1 [8,310 B]
Get:2 http://by.archive.ubuntu.com/ubuntu/ trusty/main python3-ply all 3.4-3ubuntu2 [44.8 kB]
Get:3 http://by.archive.ubuntu.com/ubuntu/ trusty/universe python3-jmespath all 0.2.1-1 [8,296 B]
Get:4 http://by.archive.ubuntu.com/ubuntu/ trusty/universe python3-dateutil all 2.0+dfsg1-1 [49.3 kB]
Get:5 http://by.archive.ubuntu.com/ubuntu/ trusty-updates/main python3-chardet all 2.2.1-2~ubuntu1 [96.5 kB]
Get:6 http://by.archive.ubuntu.com/ubuntu/ trusty-updates/main python3-urllib3 all 1.7.1-1ubuntu4 [39.6 kB]
Get:7 http://by.archive.ubuntu.com/ubuntu/ trusty-updates/main python3-requests all 2.2.1-1ubuntu0.3 [43.0 kB]
Get:8 http://by.archive.ubuntu.com/ubuntu/ trusty-updates/universe python3-botocore all 0.29.0+repack-2ubuntu0.1 [506 kB]
Get:9 http://by.archive.ubuntu.com/ubuntu/ trusty/main python3-roman all 2.0.0-1 [7,836 B]
Get:10 http://by.archive.ubuntu.com/ubuntu/ trusty/main docutils-common all 0.11-3 [143 kB]
Get:11 http://by.archive.ubuntu.com/ubuntu/ trusty/main python3-docutils all 0.11-3 [347 kB]
Get:12 http://by.archive.ubuntu.com/ubuntu/ trusty/universe python3-rsa all 3.1.2-1 [26.9 kB]
Get:13 http://by.archive.ubuntu.com/ubuntu/ trusty-updates/universe python3-colorama all 0.2.5-0.1ubuntu2 [12.0 kB]
Get:14 http://by.archive.ubuntu.com/ubuntu/ trusty/universe python3-bcdoc all 0.12.0-2 [10.5 kB]
Get:15 http://by.archive.ubuntu.com/ubuntu/ trusty/universe awscli all 1.2.9-2 [128 kB]
Get:16 http://by.archive.ubuntu.com/ubuntu/ trusty-updates/main python3-pil i386 2.3.0-1ubuntu3.3 [279 kB]
Get:17 http://by.archive.ubuntu.com/ubuntu/ trusty-updates/main python3-pygments all 1.6+dfsg-1ubuntu1.1 [465 kB]
Fetched 2,215 kB in 6s (344 kB/s)                                              
Selecting previously unselected package python3-six.
(Reading database ... 690104 files and directories currently installed.)
Preparing to unpack .../python3-six_1.5.2-1ubuntu1_all.deb ...
Unpacking python3-six (1.5.2-1ubuntu1) ...
Selecting previously unselected package python3-ply.
Preparing to unpack .../python3-ply_3.4-3ubuntu2_all.deb ...
Unpacking python3-ply (3.4-3ubuntu2) ...
Selecting previously unselected package python3-jmespath.
Preparing to unpack .../python3-jmespath_0.2.1-1_all.deb ...
Unpacking python3-jmespath (0.2.1-1) ...
Selecting previously unselected package python3-dateutil.
Preparing to unpack .../python3-dateutil_2.0+dfsg1-1_all.deb ...
Unpacking python3-dateutil (2.0+dfsg1-1) ...
Selecting previously unselected package python3-chardet.
Preparing to unpack .../python3-chardet_2.2.1-2~ubuntu1_all.deb ...
Unpacking python3-chardet (2.2.1-2~ubuntu1) ...
Selecting previously unselected package python3-urllib3.
Preparing to unpack .../python3-urllib3_1.7.1-1ubuntu4_all.deb ...
Unpacking python3-urllib3 (1.7.1-1ubuntu4) ...
Selecting previously unselected package python3-requests.
Preparing to unpack .../python3-requests_2.2.1-1ubuntu0.3_all.deb ...
Unpacking python3-requests (2.2.1-1ubuntu0.3) ...
Selecting previously unselected package python3-botocore.
Preparing to unpack .../python3-botocore_0.29.0+repack-2ubuntu0.1_all.deb ...
Unpacking python3-botocore (0.29.0+repack-2ubuntu0.1) ...
Selecting previously unselected package python3-roman.
Preparing to unpack .../python3-roman_2.0.0-1_all.deb ...
Unpacking python3-roman (2.0.0-1) ...
Selecting previously unselected package docutils-common.
Preparing to unpack .../docutils-common_0.11-3_all.deb ...
Unpacking docutils-common (0.11-3) ...
Selecting previously unselected package python3-docutils.
Preparing to unpack .../python3-docutils_0.11-3_all.deb ...
Unpacking python3-docutils (0.11-3) ...
Selecting previously unselected package python3-rsa.
Preparing to unpack .../python3-rsa_3.1.2-1_all.deb ...
Unpacking python3-rsa (3.1.2-1) ...
Selecting previously unselected package python3-colorama.
Preparing to unpack .../python3-colorama_0.2.5-0.1ubuntu2_all.deb ...
Unpacking python3-colorama (0.2.5-0.1ubuntu2) ...
Selecting previously unselected package python3-bcdoc.
Preparing to unpack .../python3-bcdoc_0.12.0-2_all.deb ...
Unpacking python3-bcdoc (0.12.0-2) ...
Selecting previously unselected package awscli.
Preparing to unpack .../awscli_1.2.9-2_all.deb ...
Unpacking awscli (1.2.9-2) ...
Selecting previously unselected package python3-pil.
Preparing to unpack .../python3-pil_2.3.0-1ubuntu3.3_i386.deb ...
Unpacking python3-pil (2.3.0-1ubuntu3.3) ...
Selecting previously unselected package python3-pygments.
Preparing to unpack .../python3-pygments_1.6+dfsg-1ubuntu1.1_all.deb ...
Unpacking python3-pygments (1.6+dfsg-1ubuntu1.1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for shared-mime-info (1.2-0ubuntu3) ...
Unknown media type in type 'all/all'
Unknown media type in type 'all/allfiles'
Unknown media type in type 'uri/mms'
Unknown media type in type 'uri/mmst'
Unknown media type in type 'uri/mmsu'
Unknown media type in type 'uri/pnm'
Unknown media type in type 'uri/rtspt'
Unknown media type in type 'uri/rtspu'
Processing triggers for sgml-base (1.26+nmu4ubuntu1) ...
Setting up python3-six (1.5.2-1ubuntu1) ...
Setting up python3-ply (3.4-3ubuntu2) ...
Setting up python3-jmespath (0.2.1-1) ...
Setting up python3-dateutil (2.0+dfsg1-1) ...
Setting up python3-chardet (2.2.1-2~ubuntu1) ...
Setting up python3-urllib3 (1.7.1-1ubuntu4) ...
Setting up python3-requests (2.2.1-1ubuntu0.3) ...
Setting up python3-botocore (0.29.0+repack-2ubuntu0.1) ...
Setting up python3-roman (2.0.0-1) ...
Setting up docutils-common (0.11-3) ...
Setting up python3-rsa (3.1.2-1) ...
Setting up python3-colorama (0.2.5-0.1ubuntu2) ...
Setting up python3-pil (2.3.0-1ubuntu3.3) ...
Setting up python3-pygments (1.6+dfsg-1ubuntu1.1) ...
Processing triggers for sgml-base (1.26+nmu4ubuntu1) ...
Setting up python3-docutils (0.11-3) ...
update-alternatives: using /usr/share/docutils/scripts/python3/rst-buildhtml to provide /usr/bin/rst-buildhtml (rst-buildhtml) in auto mode
update-alternatives: using /usr/share/docutils/scripts/python3/rst2html to provide /usr/bin/rst2html (rst2html) in auto mode
update-alternatives: using /usr/share/docutils/scripts/python3/rst2latex to provide /usr/bin/rst2latex (rst2latex) in auto mode
update-alternatives: using /usr/share/docutils/scripts/python3/rst2man to provide /usr/bin/rst2man (rst2man) in auto mode
update-alternatives: using /usr/share/docutils/scripts/python3/rst2odt to provide /usr/bin/rst2odt (rst2odt) in auto mode
update-alternatives: using /usr/share/docutils/scripts/python3/rst2odt_prepstyles to provide /usr/bin/rst2odt_prepstyles (rst2odt_prepstyles) in auto mode
update-alternatives: using /usr/share/docutils/scripts/python3/rst2pseudoxml to provide /usr/bin/rst2pseudoxml (rst2pseudoxml) in auto mode
update-alternatives: using /usr/share/docutils/scripts/python3/rst2s5 to provide /usr/bin/rst2s5 (rst2s5) in auto mode
update-alternatives: using /usr/share/docutils/scripts/python3/rst2xetex to provide /usr/bin/rst2xetex (rst2xetex) in auto mode
update-alternatives: using /usr/share/docutils/scripts/python3/rst2xml to provide /usr/bin/rst2xml (rst2xml) in auto mode
update-alternatives: using /usr/share/docutils/scripts/python3/rstpep2html to provide /usr/bin/rstpep2html (rstpep2html) in auto mode
Setting up python3-bcdoc (0.12.0-2) ...
Setting up awscli (1.2.9-2) ...
```

**Comment by stealthycoin** [comment]
We recommend you use `pip` to install the cli on linux.
[installation guide](http://docs.aws.amazon.com/cli/latest/userguide/installing.html)

We have no control over and can't maintain the cli package across all the different flavors of Linux and their packages mangers.

**Comment by kyleknap** [comment]
Closing due to inactivity
