### ISSUE TITLE
MalformedXML when calling the PutBucketMetricsConfiguration operation

### ISSUE THREAD

**Issue by henrysher** [aws/aws-cli#2355]
$ aws s3api put-bucket-metrics-configuration --endpoint http://s3-us-west-2.amazonaws.com --bucket demo-hhenry --id metrics-config-id --metrics-configuration '{"Id":" metrics-config-id ","Filter":{"Prefix":"prefix1"}}' --profile anti-gfw --debug

2017-01-03 13:51:27,133 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.11.35 Python/2.7.10 Darwin/14.5.0 botocore/1.4.92
2017-01-03 13:51:27,133 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3api', 'put-bucket-metrics-configuration', '--endpoint', 'http://s3-us-west-2.amazonaws.com', '--bucket', 'demo-hhenry', '--id', 'metrics-config-id', '--metrics-configuration', '{"Id":" metrics-config-id ","Filter":{"Prefix":"prefix1"}}', '--profile', 'anti-gfw', '--debug']
2017-01-03 13:51:27,134 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x105f179b0>
2017-01-03 13:51:27,134 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x105c7b410>
2017-01-03 13:51:27,134 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2017-01-03 13:51:27,135 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Library/Python/2.7/site-packages/botocore/data/s3/2006-03-01/service-2.json
2017-01-03 13:51:27,159 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.s3: calling handler <function register_retries_for_service at 0x1058850c8>
2017-01-03 13:51:27,160 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: s3
2017-01-03 13:51:27,162 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3api: calling handler <function add_waiters at 0x105f1db90>
2017-01-03 13:51:27,165 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Library/Python/2.7/site-packages/botocore/data/s3/2006-03-01/waiters-2.json
2017-01-03 13:51:27,166 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'bucket', <awscli.arguments.CLIArgument object at 0x106508610>), (u'id', <awscli.arguments.CLIArgument object at 0x106508650>), (u'metrics-configuration', <awscli.arguments.CLIArgument object at 0x106508690>)])
2017-01-03 13:51:27,166 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-bucket-metrics-configuration: calling handler <function add_streaming_output_arg at 0x105f17ed8>
2017-01-03 13:51:27,167 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-bucket-metrics-configuration: calling handler <function add_cli_input_json at 0x105c86230>
2017-01-03 13:51:27,167 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-bucket-metrics-configuration: calling handler <function unify_paging_params at 0x105e9cf50>
2017-01-03 13:51:27,170 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Library/Python/2.7/site-packages/botocore/data/s3/2006-03-01/paginators-1.json
2017-01-03 13:51:27,170 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-bucket-metrics-configuration: calling handler <function add_generate_skeleton at 0x105e98398>
2017-01-03 13:51:27,170 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.put-bucket-metrics-configuration: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x106508510>>
2017-01-03 13:51:27,170 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.put-bucket-metrics-configuration: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x106508850>>
2017-01-03 13:51:27,171 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-bucket-metrics-configuration.bucket: calling handler <function uri_param at 0x105b1d050>
2017-01-03 13:51:27,171 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.s3.put-bucket-metrics-configuration: calling handler <awscli.argprocess.ParamShorthandParser object at 0x105f2a050>
2017-01-03 13:51:27,171 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'demo-hhenry' for parameter "bucket": u'demo-hhenry'
2017-01-03 13:51:27,171 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-bucket-metrics-configuration.id: calling handler <function uri_param at 0x105b1d050>
2017-01-03 13:51:27,171 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.s3.put-bucket-metrics-configuration: calling handler <awscli.argprocess.ParamShorthandParser object at 0x105f2a050>
2017-01-03 13:51:27,171 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'metrics-config-id' for parameter "id": u'metrics-config-id'
2017-01-03 13:51:27,171 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-bucket-metrics-configuration.metrics-configuration: calling handler <function uri_param at 0x105b1d050>
2017-01-03 13:51:27,171 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.s3.put-bucket-metrics-configuration: calling handler <awscli.argprocess.ParamShorthandParser object at 0x105f2a050>
2017-01-03 13:51:27,171 - MainThread - awscli.argprocess - DEBUG - Param metrics_configuration looks like JSON, not considered for param shorthand.
2017-01-03 13:51:27,171 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'{"Id":" metrics-config-id ","Filter":{"Prefix":"prefix1"}}' for parameter "metrics_configuration": OrderedDict([(u'Id', u' metrics-config-id '), (u'Filter', OrderedDict([(u'Prefix', u'prefix1')]))])
2017-01-03 13:51:27,172 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-bucket-metrics-configuration.cli-input-json: calling handler <function uri_param at 0x105b1d050>
2017-01-03 13:51:27,172 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-bucket-metrics-configuration.generate-cli-skeleton: calling handler <function uri_param at 0x105b1d050>
2017-01-03 13:51:27,172 - MainThread - botocore.hooks - DEBUG - Event calling-command.s3api.put-bucket-metrics-configuration: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x106508850>>
2017-01-03 13:51:27,172 - MainThread - botocore.hooks - DEBUG - Event calling-command.s3api.put-bucket-metrics-configuration: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x106508510>>
2017-01-03 13:51:27,172 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2017-01-03 13:51:27,172 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2017-01-03 13:51:27,172 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2017-01-03 13:51:27,173 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Library/Python/2.7/site-packages/botocore/data/endpoints.json
2017-01-03 13:51:27,185 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2017-01-03 13:51:27,188 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x105850d70>
2017-01-03 13:51:27,188 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x105850500>
2017-01-03 13:51:27,189 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2017-01-03 13:51:27,195 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2017-01-03 13:51:27,196 - MainThread - botocore.client - DEBUG - Using S3 path style addressing.
2017-01-03 13:51:27,196 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutBucketMetricsConfiguration: calling handler <function validate_bucket_name at 0x105881de8>
2017-01-03 13:51:27,196 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutBucketMetricsConfiguration: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x1066c82d0>>
2017-01-03 13:51:27,196 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutBucketMetricsConfiguration: calling handler <function generate_idempotent_uuid at 0x105881aa0>
2017-01-03 13:51:27,197 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.PutBucketMetricsConfiguration: calling handler <function add_expect_header at 0x1058852a8>
2017-01-03 13:51:27,197 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.PutBucketMetricsConfiguration: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x1066c82d0>>
2017-01-03 13:51:27,197 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=PutBucketMetricsConfiguration) (verify_ssl=True) with params: {'body': '<MetricsConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Id> metrics-config-id </Id><Filter><Prefix>prefix1</Prefix></Filter></MetricsConfiguration>', 'url': u'http://s3-us-west-2.amazonaws.com/demo-hhenry?metrics&id=metrics-config-id', 'headers': {'User-Agent': 'aws-cli/1.11.35 Python/2.7.10 Darwin/14.5.0 botocore/1.4.92'}, 'context': {'client_region': None, 'signing': {'bucket': u'demo-hhenry'}, 'has_streaming_input': False, 'client_config': <botocore.config.Config object at 0x10667fe90>}, 'query_string': {u'id': u'metrics-config-id'}, 'url_path': u'/demo-hhenry?metrics', 'method': u'PUT'}
2017-01-03 13:51:27,197 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.PutBucketMetricsConfiguration: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x10667fe10>>
2017-01-03 13:51:27,197 - MainThread - botocore.auth - DEBUG - Calculating signature using hmacv1 auth.
2017-01-03 13:51:27,197 - MainThread - botocore.auth - DEBUG - HTTP request method: PUT
2017-01-03 13:51:27,197 - MainThread - botocore.auth - DEBUG - StringToSign:
PUT

Tue, 03 Jan 2017 05:51:27 GMT
/demo-hhenry?metrics
2017-01-03 13:51:27,199 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [PUT]>
2017-01-03 13:51:27,200 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): s3-us-west-2.amazonaws.com
2017-01-03 13:51:28,025 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "PUT /demo-hhenry?metrics&id=metrics-config-id HTTP/1.1" 400 None
2017-01-03 13:51:28,026 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amz-id-2': 'dctxBEQU4+/ojGVLb4cTMudjCBxY03urHVDl5iJpS+2zRgAq6x4xHWnBWh5s3YHAp7UWsXA2WBw=', 'server': 'AmazonS3', 'transfer-encoding': 'chunked', 'connection': 'close', 'x-amz-request-id': '8EFC7E3C30F3C635', 'date': 'Tue, 03 Jan 2017 05:51:24 GMT', 'content-type': 'application/xml'}
2017-01-03 13:51:28,026 - MainThread - botocore.parsers - DEBUG - Response body:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed or did not validate against our published schema</Message><RequestId>8EFC7E3C30F3C635</RequestId><HostId>dctxBEQU4+/ojGVLb4cTMudjCBxY03urHVDl5iJpS+2zRgAq6x4xHWnBWh5s3YHAp7UWsXA2WBw=</HostId></Error>
2017-01-03 13:51:28,026 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.PutBucketMetricsConfiguration: calling handler <botocore.retryhandler.RetryHandler object at 0x10630fd50>
2017-01-03 13:51:28,026 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2017-01-03 13:51:28,026 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.PutBucketMetricsConfiguration: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x1066c82d0>>
2017-01-03 13:51:28,027 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.PutBucketMetricsConfiguration: calling handler <function enhance_error_msg at 0x105f176e0>
2017-01-03 13:51:28,027 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 197, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 333, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 503, in __call__
    call_parameters, parsed_globals)
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 622, in invoke
    client, operation_name, parameters, parsed_globals)
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 634, in _make_client_call
    **parameters)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (MalformedXML) when calling the PutBucketMetricsConfiguration operation: The XML you provided was not well-formed or did not validate against our published schema
2017-01-03 13:51:28,028 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

An error occurred (MalformedXML) when calling the PutBucketMetricsConfiguration operation: The XML you provided was not well-formed or did not validate against our published schema

**Comment by stealthycoin** [comment]
You have extra spaces around metric-config-id `" metric-config-id "`

**Comment by toderesa97** [comment]
For those arriving here and using boto3 on python, check that both `Id` parameters are the same.

```
{
  "MetricConfigurations": [
    {
      "Bucket": "foo-dev",
      "Id": "SAME",
      "MetricsConfiguration": {
        "Id": "SAME"
      }
    }
  ]
}
```

This will insert a metric configuration on the whole bucket.

**Comment by nuclearpidgeon** [comment]
In case it helps anyone else, another reason that this `PutBucketMetricsConfiguration` operation can return `MalformedXML` is if the `Id` on the config is too long (>64 chars). Doesn't seem like any other part of the response body gives any specific indication that this is the specific issue if it's what's causing the failure.

As per Request Body `Id` field info in the docs:
> The ID has a 64 character limit and can only contain letters, numbers, periods, dashes, and underscores.

https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketMetricsConfiguration.html#API_PutBucketMetricsConfiguration_RequestBody
