### ISSUE TITLE
ssm send-command returning "InvalidInstanceId" error

### ISSUE THREAD

**Issue by gkiar** [aws/aws-cli#2412]
Hi,

I have started instances using the `aws ec2 run-instance` command (though this behaviour holds for instances launched through the web console), and wish to send jobs to this container via the cli. Following the tutorial [here](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/walkthrough-cli.html), I am running into trouble, despite instances being online (I can verify this in my console and can `ssh` into them).

The first command giving a suspicious result is the following. I currently have 3 instances running with status `OK` and all checks passed, but get an empty list when looking for instances that can accept commands.

Command:
```
aws ssm describe-instance-information --output text --query "InstanceInformationList[*]"
```
Output: 
```
[]
```

I presume as a downstream artefact of the problem above, when I try to send a command to my specific instance, I get the following:

Command:
```
aws ssm send-command --instance-ids "i-450e624b" --document-name "AWS-RunShellScript" --comment "IP config" --parameters commands=ifconfig --output text
```

Output:
```
DEBUG:awscli.clidriver:OrderedDict([(u'instance-ids', <awscli.arguments.ListArgument object at 0x108d62190>), (u'targets', <awscli.arguments.ListArgument object at 0x108d621d0>), (u'document-name', <awscli.arguments.CLIArgument object at 0x108d62210>), (u'document-hash', <awscli.arguments.CLIArgument object at 0x108d62250>), (u'document-hash-type', <awscli.arguments.CLIArgument object at 0x108d62290>), (u'timeout-seconds', <awscli.arguments.CLIArgument object at 0x108d622d0>), (u'comment', <awscli.arguments.CLIArgument object at 0x108d62310>), (u'parameters', <awscli.arguments.CLIArgument object at 0x108d62350>), (u'output-s3-region', <awscli.arguments.CLIArgument object at 0x108d62390>), (u'output-s3-bucket-name', <awscli.arguments.CLIArgument object at 0x108d623d0>), (u'output-s3-key-prefix', <awscli.arguments.CLIArgument object at 0x108d62410>), (u'max-concurrency', <awscli.arguments.CLIArgument object at 0x108d62450>), (u'max-errors', <awscli.arguments.CLIArgument object at 0x108d62490>), (u'service-role-arn', <awscli.arguments.CLIArgument object at 0x108d624d0>), (u'notification-config', <awscli.arguments.CLIArgument object at 0x108d62510>)])
DEBUG:awscli.arguments:Unpacked value of [u'i-450e624b'] for parameter "instance_ids": [u'i-450e624b']
DEBUG:awscli.arguments:Unpacked value of u'AWS-RunShellScript' for parameter "document_name": u'AWS-RunShellScript'
DEBUG:awscli.arguments:Unpacked value of u'IP config' for parameter "comment": u'IP config'
DEBUG:awscli.argprocess:Parsing param --parameters as shorthand
DEBUG:awscli.arguments:Unpacked value of u'commands=ifconfig' for parameter "parameters": {u'commands': [u'ifconfig']}
DEBUG:awscli.clidriver:Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 197, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 333, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 503, in __call__
    call_parameters, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 622, in invoke
    client, operation_name, parameters, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 634, in _make_client_call
    **parameters)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (InvalidInstanceId) when calling the SendCommand operation:
DEBUG:awscli.clidriver:Exiting with rc 255

An error occurred (InvalidInstanceId) when calling the SendCommand operation:
```

Any idea how I can move forward from here? Thanks!

**Comment by JordonPhillips** [comment]
I'm not seeing any error on the CLI side of things, everything seems to be sent along correctly. One thing that stood out is that you're using the short instance id format, but that should still be supported. I would probably recommend opening a [support ticket](https://console.aws.amazon.com/support/home#/) in this case so that the service team can have a look.
