### ISSUE TITLE
aws cloudformation deploy  'list' object has no attribute 'split'

### ISSUE THREAD

**Issue by Jormundir** [aws/aws-cli#2435]
```
aws --version
aws-cli/1.11.45 Python/2.7.13 Darwin/15.6.0 botocore/1.5.8
```

After creating a cloudformation template, when I attempt to deploy it, I get the python error in the title:
```
aws cloudformation deploy --template-file _build/cloudformation.yaml --stack-name lambda

'list' object has no attribute 'split'
```

**Comment by stealthycoin** [comment]
Can you run this command again with `--debug`. That will help track it down.

**Comment by Jormundir** [comment]
Huh, with no changes, this is working today. I'm guessing something must have changed with an API response?

**Comment by flaub** [comment]
Just ran into this:
```
$ aws --version
aws-cli/1.11.47 Python/2.7.13 Darwin/16.4.0 botocore/1.5.10
```

```
$ aws --debug cloudformation deploy --template-file stack-uat.yml --stack-name portal-uat --capabilities CAPABILITY_IAM help
2017-02-12 03:48:41,568 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.11.47 Python/2.7.13 Darwin/16.4.0 botocore/1.5.10
2017-02-12 03:48:41,568 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', 'cloudformation', 'deploy', '--template-file', 'stack-uat.yml', '--stack-name', 'portal-uat', '--capabilities', 'CAPABILITY_IAM', 'help']
2017-02-12 03:48:41,568 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x105a75050>
2017-02-12 03:48:41,568 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x10577cc08>
2017-02-12 03:48:41,569 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python2.7/site-packages/botocore/data/cloudformation/2010-05-15/service-2.json
2017-02-12 03:48:41,583 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.cloudformation: calling handler <function register_retries_for_service at 0x1053a37d0>
2017-02-12 03:48:41,583 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: cloudformation
2017-02-12 03:48:41,584 - MainThread - botocore.hooks - DEBUG - Event building-command-table.cloudformation: calling handler <function inject_commands at 0x1058ae9b0>
2017-02-12 03:48:41,584 - MainThread - botocore.hooks - DEBUG - Event building-command-table.cloudformation: calling handler <function add_waiters at 0x105a7e410>
2017-02-12 03:48:41,589 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python2.7/site-packages/botocore/data/cloudformation/2010-05-15/waiters-2.json
2017-02-12 03:48:41,590 - MainThread - botocore.hooks - DEBUG - Event building-command-table.deploy: calling handler <function inject_commands at 0x10595aa28>
2017-02-12 03:48:41,590 - MainThread - botocore.hooks - DEBUG - Event building-command-table.deploy: calling handler <function add_waiters at 0x105a7e410>
2017-02-12 03:48:41,592 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.deploy.template-file: calling handler <function uri_param at 0x10561aa28>
2017-02-12 03:48:41,592 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.deploy: calling handler <awscli.argprocess.ParamShorthandParser object at 0x1057605d0>
2017-02-12 03:48:41,592 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.deploy.stack-name: calling handler <function uri_param at 0x10561aa28>
2017-02-12 03:48:41,592 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.deploy: calling handler <awscli.argprocess.ParamShorthandParser object at 0x1057605d0>
2017-02-12 03:48:41,592 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.deploy.anonymous: calling handler <function uri_param at 0x10561aa28>
2017-02-12 03:48:41,592 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.deploy.anonymous: calling handler <function uri_param at 0x10561aa28>
2017-02-12 03:48:41,592 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.deploy.capabilities: calling handler <function uri_param at 0x10561aa28>
2017-02-12 03:48:41,592 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.deploy: calling handler <awscli.argprocess.ParamShorthandParser object at 0x1057605d0>
2017-02-12 03:48:41,592 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.deploy.parameter-overrides: calling handler <function uri_param at 0x10561aa28>
2017-02-12 03:48:41,593 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.deploy: calling handler <awscli.argprocess.ParamShorthandParser object at 0x1057605d0>
2017-02-12 03:48:41,593 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2017-02-12 03:48:41,593 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2017-02-12 03:48:41,593 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2017-02-12 03:48:41,593 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2017-02-12 03:48:41,593 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python2.7/site-packages/botocore/data/endpoints.json
2017-02-12 03:48:41,610 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: cloudformation
2017-02-12 03:48:41,611 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.cloudformation: calling handler <function add_generate_presigned_url at 0x105373848>
2017-02-12 03:48:41,611 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2017-02-12 03:48:41,805 - MainThread - botocore.endpoint - DEBUG - Setting cloudformation timeout as (60, 60)
2017-02-12 03:48:41,861 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 197, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 333, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/customizations/cloudformation/deploy.py", line 153, in _run_main
    template_dict = yaml_parse(template_str)
  File "/usr/local/lib/python2.7/site-packages/awscli/customizations/cloudformation/yamlhelper.py", line 68, in yaml_parse
    return yaml.safe_load(yamlstr)
  File "/usr/local/lib/python2.7/site-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 133, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 90, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/usr/local/lib/python2.7/site-packages/awscli/customizations/cloudformation/yamlhelper.py", line 38, in intrinsics_multi_constructor
    value = node.value.split(".", 1)
AttributeError: 'list' object has no attribute 'split'
2017-02-12 03:48:41,862 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

'list' object has no attribute 'split'
```

**Comment by flaub** [comment]
Some old templates use the apparently deprecated `!GetAtt [resource, attribute]` shorthand. Once I changed these all to `!GetAtt resource.attribute`, everything was OK.

**Comment by mbp** [comment]
Same experience for me with `aws-cli/1.11.51 Python/2.7.9 Windows/8 botocore/1.5.14`

Changing to `!GetAtt resource.attribute` fixed it.
