### ISSUE TITLE
pkg_resources.DistributionNotFound error when running 'eb' after fresh install

### ISSUE THREAD

**Issue by Flavien** [aws/aws-cli#2475]
I just tried installing the awsebcli on a fresh Ubuntu 14.04 (on Linux subsystem for Windows) using ``sudo pip install awsebcli``, and now, launching the ``eb`` command just returns the following error:

```
flavien@XPS-FLAVIEN:~$ eb
Traceback (most recent call last):
  File "/usr/local/bin/eb", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'termcolor==1.1.0' distribution was not found and is required by awsebcli
```

``eb`` used to work just fine a couple of hours ago, before I tried upgrading.

**Comment by Flavien** [comment]
I eventually got it working.

**Comment by JordonPhillips** [comment]
Sorry you were having trouble. In future, eb cli questions should go to the [elastic beanstalk forum](https://forums.aws.amazon.com/forum.jspa?forumID=86) as this is the repo for the generalized aws cli.

**Comment by kevin-cantwell** [comment]
@Flavien How did you get it working? Running intot h same problem.

**Comment by vinay-vissh** [comment]
Faced this issue yesterday - on `Ubuntu 16.04 | EB CLI 3.12.3 (Python 2.7.1)`.
Installed pip and awscli in ~/.local _(without any errors)_ -> Tried to use 'eb' cli and got greeted by above error.

Luckily, found [Blessan Kurien's](https://stackoverflow.com/users/4225893/blessan-kurien) answer on [this](https://stackoverflow.com/questions/42598399/unable-to-install-the-elastic-beanstalk-cli-on-ubuntu#answer-42778888) stackoverflow post.
Ran `pip install --upgrade --user awsebcli` '**twice**'  and the issue got resolved.
Still surprised how that worked o.O

**Comment by mxdi9i7** [comment]
@vinay-vissh  thanks for the tips, i only had to run it once for it to work.
