### ISSUE TITLE
Association ID does not mean instance id?

### ISSUE THREAD

**Issue by ryanwetzelberger** [aws/aws-cli#2570]
trying to use aws ec2 ReplaceIamInstanceProfileAssociation.  When using the option "associationId" like it is documented, meaning using the instance id, it does not work.  I need to be able to replace an IAM instance profile on an instance that already has an IAM instance profile associated to it.  I cannot remove it and add a new one.  It has permissions that it needs to remain in place.  

Debug: 
```
aws --region us-west-2 ec2 replace-iam-instance-profile-association --association-id=i-XXXXXXXXX --iam-instance-profile Name=XXXXX --debug
2017-04-27 14:07:13,286 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.11.81 Python/2.7.10 Darwin/16.5.0 botocore/1.5.44
2017-04-27 14:07:13,286 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--region', 'us-west-2', 'ec2', 'replace-iam-instance-profile-association', '--association-id=i-XXXXXXXXX', '--iam-instance-profile', 'Name=XXXXXX', '--debug']
2017-04-27 14:07:13,286 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x10a17f5f0>
2017-04-27 14:07:13,287 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x109ed5a28>
2017-04-27 14:07:13,291 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Library/Python/2.7/site-packages/botocore/data/ec2/2016-11-15/service-2.json
2017-04-27 14:07:13,375 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.ec2: calling handler <function register_retries_for_service at 0x109ac6758>
2017-04-27 14:07:13,376 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: ec2
2017-04-27 14:07:13,382 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <functools.partial object at 0x10a1950a8>
2017-04-27 14:07:13,382 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-instance
2017-04-27 14:07:13,382 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-volume
2017-04-27 14:07:13,382 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <function add_waiters at 0x10a1827d0>
2017-04-27 14:07:13,386 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Library/Python/2.7/site-packages/botocore/data/ec2/2016-11-15/waiters-2.json
2017-04-27 14:07:13,389 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'iam-instance-profile', <awscli.arguments.CLIArgument object at 0x10af392d0>), (u'association-id', <awscli.arguments.CLIArgument object at 0x10af39310>)])
2017-04-27 14:07:13,389 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.replace-iam-instance-profile-association: calling handler <function add_streaming_output_arg at 0x10a17fed8>
2017-04-27 14:07:13,389 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.replace-iam-instance-profile-association: calling handler <function _rename_arg at 0x10a1a5050>
2017-04-27 14:07:13,389 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.replace-iam-instance-profile-association: calling handler <function _rename_arg at 0x10a1a5578>
2017-04-27 14:07:13,389 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.replace-iam-instance-profile-association: calling handler <functools.partial object at 0x10a195158>
2017-04-27 14:07:13,389 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.replace-iam-instance-profile-association: calling handler <function add_cli_input_json at 0x109eda848>
2017-04-27 14:07:13,390 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.replace-iam-instance-profile-association: calling handler <function unify_paging_params at 0x10a106848>
2017-04-27 14:07:13,393 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Library/Python/2.7/site-packages/botocore/data/ec2/2016-11-15/paginators-1.json
2017-04-27 14:07:13,394 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.replace-iam-instance-profile-association: calling handler <function add_generate_skeleton at 0x10a0eec08>
2017-04-27 14:07:13,394 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.replace-iam-instance-profile-association: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x10ad83f10>>
2017-04-27 14:07:13,394 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.replace-iam-instance-profile-association: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x10af39550>>
2017-04-27 14:07:13,395 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.ec2.replace-iam-instance-profile-association: calling handler <functools.partial object at 0x10af0d1b0>
2017-04-27 14:07:13,395 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.replace-iam-instance-profile-association.iam-instance-profile: calling handler <function uri_param at 0x109d76410>
2017-04-27 14:07:13,395 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.ec2.replace-iam-instance-profile-association: calling handler <awscli.argprocess.ParamShorthandParser object at 0x10a187610>
2017-04-27 14:07:13,395 - MainThread - awscli.argprocess - DEBUG - Parsing param --iam-instance-profile as shorthand
2017-04-27 14:07:13,395 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'Name=XXXXXX' for parameter "iam_instance_profile": {u'Name': u'XXXXXX'}
2017-04-27 14:07:13,395 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.replace-iam-instance-profile-association.association-id: calling handler <function uri_param at 0x109d76410>
2017-04-27 14:07:13,395 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.ec2.replace-iam-instance-profile-association: calling handler <awscli.argprocess.ParamShorthandParser object at 0x10a187610>
2017-04-27 14:07:13,395 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'i-XXXXXXXX' for parameter "association_id": u'i-XXXXXXXXX'
2017-04-27 14:07:13,396 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.replace-iam-instance-profile-association.cli-input-json: calling handler <function uri_param at 0x109d76410>
2017-04-27 14:07:13,396 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.replace-iam-instance-profile-association.generate-cli-skeleton: calling handler <function uri_param at 0x109d76410>
2017-04-27 14:07:13,396 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.replace-iam-instance-profile-association: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x10ad83f10>>
2017-04-27 14:07:13,396 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.replace-iam-instance-profile-association: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x10af39550>>
2017-04-27 14:07:13,396 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2017-04-27 14:07:13,396 - MainThread - botocore.credentials - INFO - Found credentials in environment variables.
2017-04-27 14:07:13,396 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Library/Python/2.7/site-packages/botocore/data/endpoints.json
2017-04-27 14:07:13,412 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: ec2
2017-04-27 14:07:13,421 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.ec2: calling handler <function add_generate_presigned_url at 0x109a8fc08>
2017-04-27 14:07:13,421 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2017-04-27 14:07:13,455 - MainThread - botocore.endpoint - DEBUG - Setting ec2 timeout as (60, 60)
2017-04-27 14:07:13,457 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.ec2.ReplaceIamInstanceProfileAssociation: calling handler <bound method ParameterAlias.alias_parameter_in_call of <botocore.handlers.ParameterAlias object at 0x109ac3610>>
2017-04-27 14:07:13,457 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.ec2.ReplaceIamInstanceProfileAssociation: calling handler <function generate_idempotent_uuid at 0x109ac61b8>
2017-04-27 14:07:13,458 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=ReplaceIamInstanceProfileAssociation) (verify_ssl=True) with params: {'body': {'Action': u'ReplaceIamInstanceProfileAssociation', u'AssociationId': u'i-XXXXXXXXXX', 'Version': u'2016-11-15', u'IamInstanceProfile.Name': u'XXXXX'}, 'url': u'https://ec2.us-west-2.amazonaws.com/', 'headers': {'User-Agent': 'aws-cli/1.11.81 Python/2.7.10 Darwin/16.5.0 botocore/1.5.44'}, 'context': {'auth_type': None, 'client_region': u'us-west-2', 'has_streaming_input': False, 'client_config': <botocore.config.Config object at 0x10b10d590>}, 'query_string': '', 'url_path': '/', 'method': u'POST'}
2017-04-27 14:07:13,458 - MainThread - botocore.hooks - DEBUG - Event request-created.ec2.ReplaceIamInstanceProfileAssociation: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x10b10d510>>
2017-04-27 14:07:13,458 - MainThread - botocore.hooks - DEBUG - Event choose-signer.ec2.ReplaceIamInstanceProfileAssociation: calling handler <function set_operation_specific_signer at 0x109ac60c8>
2017-04-27 14:07:13,459 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2017-04-27 14:07:13,459 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

host:ec2.us-west-2.amazonaws.com
x-amz-date:20170427T180713Z

host;x-amz-date
2017-04-27 14:07:13,459 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20170427T180713Z
20170427/us-west-2/ec2/aws4_request
2017-04-27 14:07:13,459 - MainThread - botocore.auth - DEBUG - Signature:
2017-04-27 14:07:13,462 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2017-04-27 14:07:13,463 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): ec2.us-west-2.amazonaws.com
2017-04-27 14:07:13,905 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "POST / HTTP/1.1" 400 None
2017-04-27 14:07:13,909 - MainThread - botocore.parsers - DEBUG - Response headers: {'transfer-encoding': 'chunked', 'date': 'Thu, 27 Apr 2017 18:07:13 GMT', 'connection': 'close', 'server': 'AmazonEC2'}
2017-04-27 14:07:13,909 - MainThread - botocore.parsers - DEBUG - Response body:
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Invalid value for associationId.</Message></Error></Errors><RequestID>8c6dabcb-bed8-47db-a1e0-89d7b525ba32</RequestID></Response>
2017-04-27 14:07:13,909 - MainThread - botocore.hooks - DEBUG - Event needs-retry.ec2.ReplaceIamInstanceProfileAssociation: calling handler <botocore.retryhandler.RetryHandler object at 0x10ad83e90>
2017-04-27 14:07:13,909 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2017-04-27 14:07:13,916 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 200, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 338, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 508, in __call__
    call_parameters, parsed_globals)
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 627, in invoke
    client, operation_name, parameters, parsed_globals)
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 639, in _make_client_call
    **parameters)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 557, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (InvalidParameterValue) when calling the ReplaceIamInstanceProfileAssociation operation: Invalid value for associationId.
2017-04-27 14:07:13,920 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

An error occurred (InvalidParameterValue) when calling the ReplaceIamInstanceProfileAssociation operation: Invalid value for associationId.
```

version:
```
aws --version
aws-cli/1.11.81 Python/2.7.10 Darwin/16.5.0 botocore/1.5.44
```

**Comment by ryanwetzelberger** [comment]
Closing this issue.  Worked with AWS support.  Found that there is an ip-assoc id that defines the linkage object between the ec2 instance and iam-instance-profile.  This is what should be used for option ``` association-id ```

**Comment by netmailgopi** [comment]
How did you get the ip-assoc id? I can;t find that key from describe_instances call

**Comment by netmailgopi** [comment]
Alright have to make this call to get describe_iam_instance_profile_associations
