### ISSUE TITLE
Rekognition DetectModerationLabels operation fails on aws-cli/1.11.82

### ISSUE THREAD

**Issue by annaxli** [aws/aws-cli#2579]
I am trying to follow this exercise, [Exercise 4: Moderate Images (API)](http://docs.aws.amazon.com/rekognition/latest/dg/get-started-exercise-moderate-images.html). 

When I call the detect-moderation-labels operation, it returns an error message:

> Traceback (most recent call last):
>   File "/Users/horsepower/.local/bin/aws", line 27, in <module>
>     sys.exit(main())
>   File "/Users/horsepower/.local/bin/aws", line 23, in main
>     return awscli.clidriver.main()
>   File "/Users/horsepower/.local/lib/python2.7/site-packages/awscli/clidriver.py", line 56, in main
>     return driver.main()
>   File "/Users/horsepower/.local/lib/python2.7/site-packages/awscli/clidriver.py", line 203, in main
>     sys.stderr.write(str(e))
> UnicodeEncodeError: 'ascii' codec can't encode character u'\u2028' in position 17: ordinal not in range(128)

Here's my version of CLI:

> 
> $ aws --version
> aws-cli/1.11.82 Python/2.7.11 Darwin/16.5.0 botocore/1.5.45
> 

Here's the debug message:
```
aws rekognition detect-moderation-labels --debug --image '{"S3Object":{"Bucket":"semarchy-tutorials","Name":"10001-MAIN.jpg"}}' 
2017-05-03 15:56:15,250 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.11.82 Python/2.7.11 Darwin/16.5.0 botocore/1.5.45
2017-05-03 15:56:15,250 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['rekognition', 'detect-moderation-labels', '--debug', '--image', '{"S3Object":{"Bucket":"semarchy-tutorials","Name":"10001-MAIN.jpg"}}', '\xe2\x80\xa8--debug']
2017-05-03 15:56:15,250 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x103f09f50>
2017-05-03 15:56:15,251 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x103b28b18>
2017-05-03 15:56:15,254 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/horsepower/.local/lib/python2.7/site-packages/botocore/data/rekognition/2016-06-27/service-2.json
2017-05-03 15:56:15,261 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.rekognition: calling handler <function register_retries_for_service at 0x103426f50>
2017-05-03 15:56:15,262 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: rekognition
2017-05-03 15:56:15,262 - MainThread - botocore.hooks - DEBUG - Event building-command-table.rekognition: calling handler <function add_waiters at 0x103f170c8>
2017-05-03 15:56:15,268 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'image', <awscli.arguments.CLIArgument object at 0x104201c90>), (u'min-confidence', <awscli.arguments.CLIArgument object at 0x104201cd0>)])
2017-05-03 15:56:15,268 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.rekognition.detect-moderation-labels: calling handler <function add_streaming_output_arg at 0x103f0e230>
2017-05-03 15:56:15,268 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.rekognition.detect-moderation-labels: calling handler <function add_cli_input_json at 0x103b30938>
2017-05-03 15:56:15,269 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.rekognition.detect-moderation-labels: calling handler <function unify_paging_params at 0x103e965f0>
2017-05-03 15:56:15,276 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/horsepower/.local/lib/python2.7/site-packages/botocore/data/rekognition/2016-06-27/paginators-1.json
2017-05-03 15:56:15,277 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.rekognition.detect-moderation-labels: calling handler <function add_generate_skeleton at 0x103e837d0>
2017-05-03 15:56:15,277 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.rekognition.detect-moderation-labels: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x104201d10>>
2017-05-03 15:56:15,277 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.rekognition.detect-moderation-labels: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x104201e90>>
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Traceback (most recent call last):
  File "/Users/horsepower/.local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/Users/horsepower/.local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/Users/horsepower/.local/lib/python2.7/site-packages/awscli/clidriver.py", line 56, in main
    return driver.main()
  File "/Users/horsepower/.local/lib/python2.7/site-packages/awscli/clidriver.py", line 203, in main
    sys.stderr.write(str(e))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2028' in position 17: ordinal not in range(128)

```

I know that the detect-labels operation works successfully when I use the same image so Rekognition is working on my computer and with my IAM user. It's just not working for detect-moderation-labels operation.

Thanks for all your hard work.

**Comment by annaxli** [comment]
Discovered this might be a problem with my local environment as my boss is able to get this working on aws-cli/1.11.82. Please close this issue.

**Comment by kyleknap** [comment]
It is interesting that you are getting a unicode error though. It strange that it is getting thrown there as there really isn't any unicode in what you are providing. Have you got this working yet?

**Comment by annaxli** [comment]
Hi kyleknap, Yes I did. I got it working by typing each character into the command line by hand instead of manually copying and pasting the sample request. I figured there might be some kind of hidden character that wasn't visible. In the end, I am not sure what's wrong but it is now working for me. Thanks for following up. Feel free to close the ticket.

**Comment by JordonPhillips** [comment]
In that case it must have been some weird unicode in the example that you linked. I wasn't able to get that to fail myself though. Can you confirm that if you manually copy from that site it breaks?

**Comment by annaxli** [comment]
Hi JordonPhillips, I was able to manually copy and paste from another computer so I think my laptop might just have some weird settings. We can chalk it up to user error. Thanks to Stealthycoin for closing the ticket.
