### ISSUE TITLE
S3 cp input pipe is broken

### ISSUE THREAD

**Issue by alexrovner** [aws/aws-cli#2625]
Piping into S3 cp used to work on 1.11.82, and no longer works on 1.3.16 

$ echo "test" | aws s3 --debug cp - s3://dev.magnetic.data.archive/catalog-export/test
2017-05-30 19:04:52,738 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.3.16 Python/2.7.12 Linux/2.6.32-642.4.2.el6.x86_64, botocore version: 0.50.0
2017-05-30 19:04:52,740 - MainThread - botocore.service - DEBUG - Creating service object for: s3
2017-05-30 19:04:52,770 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.s3: calling handler <function signature_overrides at 0x7f030b533578>
2017-05-30 19:04:52,770 - MainThread - botocore.hooks - DEBUG - Event service-created: calling handler <function register_retries_for_service at 0x7f030b533398>
2017-05-30 19:04:52,770 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: Service(s3)
2017-05-30 19:04:52,771 - MainThread - botocore.hooks - DEBUG - Event creating-endpoint.s3: calling handler <function maybe_switch_to_s3sigv4 at 0x7f030b533488>
2017-05-30 19:04:52,771 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2017-05-30 19:04:52,771 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2017-05-30 19:04:52,771 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: config-file
2017-05-30 19:04:52,771 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: ec2-credentials-file
2017-05-30 19:04:52,772 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: boto-config
2017-05-30 19:04:52,772 - MainThread - botocore.credentials - INFO - Found credentials in boto config file: /etc/boto.cfg
2017-05-30 19:04:52,776 - MainThread - awscli.customizations.s3.s3handler - DEBUG - Exception caught during task execution: [Errno 2] No such file or directory: '/home/jobs-staging/-'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awscli/customizations/s3/s3handler.py", line 76, in call
    total_files, total_parts = self._enqueue_tasks(files)
  File "/usr/lib/python2.7/site-packages/awscli/customizations/s3/s3handler.py", line 154, in _enqueue_tasks
    for filename in files:
  File "/usr/lib/python2.7/site-packages/awscli/customizations/s3/filegenerator.py", line 76, in call
    for src_path, size, last_update in file_list:
  File "/usr/lib/python2.7/site-packages/awscli/customizations/s3/filegenerator.py", line 107, in list_files
    size, last_update = get_file_stat(path)
  File "/usr/lib/python2.7/site-packages/awscli/customizations/s3/utils.py", line 116, in get_file_stat
    stats = os.stat(path)
OSError: [Errno 2] No such file or directory: '/home/jobs-staging/-'
2017-05-30 19:04:52,794 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 1)
2017-05-30 19:04:52,795 - Thread-1 - awscli.customizations.s3.executor - DEBUG - Received print task: {'message': "[Errno 2] No such file or directory: '/home/jobs-staging/-'", 'error': True}
[Errno 2] No such file or directory: '/home/jobs-staging/-'
2017-05-30 19:04:52,795 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 1)
2017-05-30 19:04:52,795 - Thread-3 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2017-05-30 19:04:52,795 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 1)
2017-05-30 19:04:52,796 - Thread-4 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2017-05-30 19:04:52,796 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 1)
2017-05-30 19:04:52,796 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 1)
2017-05-30 19:04:52,796 - Thread-6 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2017-05-30 19:04:52,797 - Thread-5 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2017-05-30 19:04:52,797 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 1)
2017-05-30 19:04:52,797 - Thread-7 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2017-05-30 19:04:52,797 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 1)
2017-05-30 19:04:52,797 - Thread-8 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2017-05-30 19:04:52,797 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 1)
2017-05-30 19:04:52,798 - Thread-9 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2017-05-30 19:04:52,798 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 1)
2017-05-30 19:04:52,798 - Thread-10 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2017-05-30 19:04:52,798 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 1)
2017-05-30 19:04:52,798 - Thread-11 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2017-05-30 19:04:52,799 - Thread-12 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2017-05-30 19:04:52,799 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-3, stopped daemon 139651019544320)>
2017-05-30 19:04:52,799 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-3, stopped daemon 139651019544320)>
2017-05-30 19:04:52,799 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-4, stopped daemon 139651009054464)>
2017-05-30 19:04:52,799 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-4, stopped daemon 139651009054464)>
2017-05-30 19:04:52,799 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-5, stopped daemon 139650794518272)>
2017-05-30 19:04:52,799 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-5, stopped daemon 139650794518272)>
2017-05-30 19:04:52,799 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-6, stopped daemon 139650784028416)>
2017-05-30 19:04:52,799 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-6, stopped daemon 139650784028416)>
2017-05-30 19:04:52,800 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-7, stopped daemon 139650773538560)>
2017-05-30 19:04:52,800 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-7, stopped daemon 139650773538560)>
2017-05-30 19:04:52,800 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-8, stopped daemon 139650763048704)>
2017-05-30 19:04:52,800 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-8, stopped daemon 139650763048704)>
2017-05-30 19:04:52,800 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-9, stopped daemon 139650752558848)>
2017-05-30 19:04:52,800 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-9, stopped daemon 139650752558848)>
2017-05-30 19:04:52,800 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-10, stopped daemon 139650742068992)>
2017-05-30 19:04:52,800 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-10, stopped daemon 139650742068992)>
2017-05-30 19:04:52,800 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-11, stopped daemon 139650324756224)>
2017-05-30 19:04:52,800 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-11, stopped daemon 139650324756224)>
2017-05-30 19:04:52,800 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-12, stopped daemon 139650314266368)>
2017-05-30 19:04:52,800 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-12, stopped daemon 139650314266368)>
2017-05-30 19:04:52,800 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for result thread.
2017-05-30 19:04:52,800 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for IO thread.

2017-05-30 19:04:52,801 - Thread-1 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in print thread, shutting down print thread.
2017-05-30 19:04:52,801 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for result thread to shutdown.
2017-05-30 19:04:52,801 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for IO thread to shutdown.
2017-05-30 19:04:52,801 - Thread-2 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in IO thread, shutting down.
2017-05-30 19:04:52,801 - MainThread - awscli.customizations.s3.executor - DEBUG - All threads have been shutdown.

**Comment by alexrovner** [comment]
Just realized that .11 is the newer version and not older :-(
