### ISSUE TITLE
--no-verify-ssl doesnt work when using role_arn

### ISSUE THREAD

**Issue by trevorndodds** [aws/aws-cli#2648]
aws-cli/1.11.83 Python/2.7.5 Linux/3.10.0-514.21.1.el7.x86_64 botocore/1.5.46

when using --no-verify-ssl with a role_arn profile I get an SSL Error.
aws ec2 describe-regions --profile PowerUser --no-verify-ssl
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)

If I use my standard default profile without the role_arn the --no-verify-ssl works fine.

I assume it's trying to create two connections, perhaps the --no-verify-ssl is not being passed when it changes role?

**Comment by trevorndodds** [comment]
Debug Output
```
2017-06-07 13:19:40,045 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.11.83 Python/2.7.5 Linux/3.10.0-514.21.1.el7.x86_64 botocore/1.5.46
2017-06-07 13:19:40,045 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['ec2', 'describe-regions', '--profile', 'PowerUser', '--no-verify-ssl', '--debug']
2017-06-07 13:19:40,045 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x29b81b8>
2017-06-07 13:19:40,045 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x25ba1b8>
2017-06-07 13:19:40,046 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2017-06-07 13:19:40,049 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python2.7/site-packages/botocore/data/ec2/2016-11-15/service-2.json
2017-06-07 13:19:40,130 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.ec2: calling handler <function register_retries_for_service at 0x2141410>
2017-06-07 13:19:40,130 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: ec2
2017-06-07 13:19:40,137 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <functools.partial object at 0x29bbcb0>
2017-06-07 13:19:40,137 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-instance
2017-06-07 13:19:40,137 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-volume
2017-06-07 13:19:40,137 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <function add_waiters at 0x29bf398>
2017-06-07 13:19:40,138 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python2.7/site-packages/botocore/data/ec2/2016-11-15/waiters-2.json
2017-06-07 13:19:40,141 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'dry-run', <awscli.arguments.BooleanArgument object at 0x371f310>), (u'no-dry-run', <awscli.arguments.BooleanArgument object at 0x371f350>), (u'region-names', <awscli.arguments.ListArgument object at 0x371f390>), (u'filters', <awscli.arguments.ListArgument object at 0x371f3d0>)])
2017-06-07 13:19:40,141 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-regions: calling handler <function add_streaming_output_arg at 0x29b86e0>
2017-06-07 13:19:40,141 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-regions: calling handler <function _rename_arg at 0x29c2b90>
2017-06-07 13:19:40,141 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-regions: calling handler <function _rename_arg at 0x29cd140>
2017-06-07 13:19:40,141 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-regions: calling handler <functools.partial object at 0x29bbd60>
2017-06-07 13:19:40,142 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-regions: calling handler <function add_cli_input_json at 0x25baf50>
2017-06-07 13:19:40,142 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-regions: calling handler <function unify_paging_params at 0x29277d0>
2017-06-07 13:19:40,143 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python2.7/site-packages/botocore/data/ec2/2016-11-15/paginators-1.json
2017-06-07 13:19:40,144 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-regions: calling handler <function add_generate_skeleton at 0x28d4b90>
2017-06-07 13:19:40,144 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.describe-regions: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x3593b50>>
2017-06-07 13:19:40,144 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.describe-regions: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x371f710>>
2017-06-07 13:19:40,145 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.ec2.describe-regions: calling handler <functools.partial object at 0x3720050>
2017-06-07 13:19:40,145 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-regions.dry-run: calling handler <function uri_param at 0x23eab18>
2017-06-07 13:19:40,145 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-regions.region-names: calling handler <function uri_param at 0x23eab18>
2017-06-07 13:19:40,145 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-regions.filters: calling handler <function uri_param at 0x23eab18>
2017-06-07 13:19:40,145 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-regions.cli-input-json: calling handler <function uri_param at 0x23eab18>
2017-06-07 13:19:40,145 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-regions.generate-cli-skeleton: calling handler <function uri_param at 0x23eab18>
2017-06-07 13:19:40,145 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.describe-regions: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x3593b50>>
2017-06-07 13:19:40,145 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.describe-regions: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x371f710>>
2017-06-07 13:19:40,146 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2017-06-07 13:19:40,146 - MainThread - botocore.credentials - DEBUG - Retrieving credentials via AssumeRole.
2017-06-07 13:19:40,146 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python2.7/site-packages/botocore/data/endpoints.json
2017-06-07 13:19:40,158 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python2.7/site-packages/botocore/data/sts/2011-06-15/service-2.json
2017-06-07 13:19:40,162 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: sts
2017-06-07 13:19:40,163 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.sts: calling handler <function add_generate_presigned_url at 0x21018c0>
2017-06-07 13:19:40,163 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2017-06-07 13:19:40,166 - MainThread - botocore.endpoint - DEBUG - Setting sts timeout as (60, 60)
2017-06-07 13:19:40,166 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.sts.AssumeRole: calling handler <function generate_idempotent_uuid at 0x213fde8>
2017-06-07 13:19:40,166 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=AssumeRole) (verify_ssl=True) with params: {'body': {'Action': u'AssumeRole', 'RoleArn': 'arn:aws:iam::xxxxxxxx:role/PowerUser', 'Version': u'2011-06-15', 'RoleSessionName': 'AWS-CLI-session-1496855980'}, 'url': u'https://sts.amazonaws.com/', 'headers': {'User-Agent': 'aws-cli/1.11.83 Python/2.7.5 Linux/3.10.0-514.21.1.el7.x86_64 botocore/1.5.46'}, 'context': {'auth_type': None, 'client_region': u'aws-global', 'has_streaming_input': False, 'client_config': <botocore.config.Config object at 0x3977610>}, 'query_string': '', 'url_path': '/', 'method': u'POST'}
2017-06-07 13:19:40,167 - MainThread - botocore.hooks - DEBUG - Event request-created.sts.AssumeRole: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x3977590>>
2017-06-07 13:19:40,167 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sts.AssumeRole: calling handler <function set_operation_specific_signer at 0x213fcf8>
2017-06-07 13:19:40,167 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2017-06-07 13:19:40,167 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

host:sts.amazonaws.com
x-amz-date:20170607T171940Z

host;x-amz-date
fb042db93df1a7f041dd6feaa54ba59476aa8925365571e6d9e9d16edebf2c47
2017-06-07 13:19:40,167 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20170607T171940Z
20170607/us-east-1/sts/aws4_request
a4df2bec0edfd3f8d66139156f59a5cc9a238a8266a6eec46019be5d2cce1199
2017-06-07 13:19:40,167 - MainThread - botocore.auth - DEBUG - Signature:
b57c26c6258f3c20b4b9a8e3302971add0a9185bcad05d5a16df42e75b002be4
2017-06-07 13:19:40,172 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2017-06-07 13:19:40,172 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): sts.amazonaws.com
2017-06-07 13:19:40,493 - MainThread - botocore.endpoint - DEBUG - ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/botocore/endpoint.py", line 204, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/usr/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
2017-06-07 13:19:40,493 - MainThread - botocore.hooks - DEBUG - Event needs-retry.sts.AssumeRole: calling handler <botocore.retryhandler.RetryHandler object at 0x3977190>
2017-06-07 13:19:40,494 - MainThread - botocore.retryhandler - DEBUG - retry needed, retryable exception caught: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
2017-06-07 13:19:40,494 - MainThread - botocore.retryhandler - DEBUG - Retry needed, action of: 0.964243817624
2017-06-07 13:19:40,494 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.964243817624 seconds
2017-06-07 13:19:41,460 - MainThread - botocore.hooks - DEBUG - Event request-created.sts.AssumeRole: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x3977590>>
2017-06-07 13:19:41,460 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sts.AssumeRole: calling handler <function set_operation_specific_signer at 0x213fcf8>
2017-06-07 13:19:41,460 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2017-06-07 13:19:41,460 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

host:sts.amazonaws.com
x-amz-date:20170607T171941Z

host;x-amz-date
fb042db93df1a7f041dd6feaa54ba59476aa8925365571e6d9e9d16edebf2c47
2017-06-07 13:19:41,460 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20170607T171941Z
20170607/us-east-1/sts/aws4_request
4e1a363feebb0b6afe4dbdd149ecbee0e1bb5c54c81d027d10a6e532b749f3d9
2017-06-07 13:19:41,460 - MainThread - botocore.auth - DEBUG - Signature:
eb2f15a5ea0aa143ed348bf11a9bd40990c1e38767f6ecab2c4d87c306e5eefa
2017-06-07 13:19:41,461 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2017-06-07 13:19:41,461 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (2): sts.amazonaws.com
2017-06-07 13:19:41,659 - MainThread - botocore.endpoint - DEBUG - ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/botocore/endpoint.py", line 204, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/usr/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
2017-06-07 13:19:41,659 - MainThread - botocore.hooks - DEBUG - Event needs-retry.sts.AssumeRole: calling handler <botocore.retryhandler.RetryHandler object at 0x3977190>
2017-06-07 13:19:41,659 - MainThread - botocore.retryhandler - DEBUG - retry needed, retryable exception caught: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
2017-06-07 13:19:41,660 - MainThread - botocore.retryhandler - DEBUG - Retry needed, action of: 0.596339996713
2017-06-07 13:19:41,660 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.596339996713 seconds
2017-06-07 13:19:42,256 - MainThread - botocore.hooks - DEBUG - Event request-created.sts.AssumeRole: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x3977590>>
2017-06-07 13:19:42,256 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sts.AssumeRole: calling handler <function set_operation_specific_signer at 0x213fcf8>
2017-06-07 13:19:42,257 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2017-06-07 13:19:42,257 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

host:sts.amazonaws.com
x-amz-date:20170607T171942Z

host;x-amz-date
fb042db93df1a7f041dd6feaa54ba59476aa8925365571e6d9e9d16edebf2c47
2017-06-07 13:19:42,257 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20170607T171942Z
20170607/us-east-1/sts/aws4_request
36a0808a5fbfdd3993c0cb78a5c7c3a771bcf92fe1429deddfb22ca6326b309f
2017-06-07 13:19:42,257 - MainThread - botocore.auth - DEBUG - Signature:
480ba091f6b18b00a17d860fa0d08d14dbc52d56162861dd34ff196805c58a66
2017-06-07 13:19:42,257 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2017-06-07 13:19:42,258 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (3): sts.amazonaws.com
2017-06-07 13:19:42,440 - MainThread - botocore.endpoint - DEBUG - ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/botocore/endpoint.py", line 204, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/usr/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
2017-06-07 13:19:42,440 - MainThread - botocore.hooks - DEBUG - Event needs-retry.sts.AssumeRole: calling handler <botocore.retryhandler.RetryHandler object at 0x3977190>
2017-06-07 13:19:42,440 - MainThread - botocore.retryhandler - DEBUG - retry needed, retryable exception caught: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
2017-06-07 13:19:42,441 - MainThread - botocore.retryhandler - DEBUG - Retry needed, action of: 2.20274255245
2017-06-07 13:19:42,441 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 2.20274255245 seconds
2017-06-07 13:19:44,646 - MainThread - botocore.hooks - DEBUG - Event request-created.sts.AssumeRole: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x3977590>>
2017-06-07 13:19:44,647 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sts.AssumeRole: calling handler <function set_operation_specific_signer at 0x213fcf8>
2017-06-07 13:19:44,647 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2017-06-07 13:19:44,647 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

host:sts.amazonaws.com
x-amz-date:20170607T171944Z

host;x-amz-date
fb042db93df1a7f041dd6feaa54ba59476aa8925365571e6d9e9d16edebf2c47
2017-06-07 13:19:44,647 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20170607T171944Z
20170607/us-east-1/sts/aws4_request
78a585e980c71b9d53b803655ecdd0f2c1375ad8f4d9a7644d6703ac965bafc6
2017-06-07 13:19:44,647 - MainThread - botocore.auth - DEBUG - Signature:
28fb9ed306cb6a4c2f0eff925d483c5c8fd22dee7667dbb52f32ba53f5885aaa
2017-06-07 13:19:44,648 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2017-06-07 13:19:44,648 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (4): sts.amazonaws.com
2017-06-07 13:19:44,841 - MainThread - botocore.endpoint - DEBUG - ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/botocore/endpoint.py", line 204, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/usr/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
2017-06-07 13:19:44,841 - MainThread - botocore.hooks - DEBUG - Event needs-retry.sts.AssumeRole: calling handler <botocore.retryhandler.RetryHandler object at 0x3977190>
2017-06-07 13:19:44,841 - MainThread - botocore.retryhandler - DEBUG - retry needed, retryable exception caught: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
2017-06-07 13:19:44,841 - MainThread - botocore.retryhandler - DEBUG - Retry needed, action of: 1.84024851131
2017-06-07 13:19:44,842 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 1.84024851131 seconds
2017-06-07 13:19:46,684 - MainThread - botocore.hooks - DEBUG - Event request-created.sts.AssumeRole: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x3977590>>
2017-06-07 13:19:46,684 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sts.AssumeRole: calling handler <function set_operation_specific_signer at 0x213fcf8>
2017-06-07 13:19:46,684 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2017-06-07 13:19:46,684 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

host:sts.amazonaws.com
x-amz-date:20170607T171946Z

host;x-amz-date
fb042db93df1a7f041dd6feaa54ba59476aa8925365571e6d9e9d16edebf2c47
2017-06-07 13:19:46,684 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20170607T171946Z
20170607/us-east-1/sts/aws4_request
7e7e9a4ca2df06653f7008d6fd48666eb1b2df57da4da758b16eeefe74b97776
2017-06-07 13:19:46,685 - MainThread - botocore.auth - DEBUG - Signature:
c08a99eae31dffe1948d84bb025d323a6597577bd0a1f0f33f8814eebbe93819
2017-06-07 13:19:46,685 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2017-06-07 13:19:46,685 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (5): sts.amazonaws.com
2017-06-07 13:19:46,890 - MainThread - botocore.endpoint - DEBUG - ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/botocore/endpoint.py", line 204, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/usr/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
2017-06-07 13:19:46,890 - MainThread - botocore.hooks - DEBUG - Event needs-retry.sts.AssumeRole: calling handler <botocore.retryhandler.RetryHandler object at 0x3977190>
2017-06-07 13:19:46,890 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 200, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 338, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 508, in __call__
    call_parameters, parsed_globals)
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 625, in invoke
    verify=parsed_globals.verify_ssl)
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 825, in create_client
    credentials = self.get_credentials()
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 449, in get_credentials
    'credential_provider').load_credentials()
  File "/usr/lib/python2.7/site-packages/botocore/credentials.py", line 1100, in load_credentials
    creds = provider.load()
  File "/usr/lib/python2.7/site-packages/botocore/credentials.py", line 796, in load
    return self._load_creds_via_assume_role()
  File "/usr/lib/python2.7/site-packages/botocore/credentials.py", line 815, in _load_creds_via_assume_role
    creds, response = self._retrieve_temp_credentials()
  File "/usr/lib/python2.7/site-packages/botocore/credentials.py", line 924, in _retrieve_temp_credentials
    response = client.assume_role(**assume_role_kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 544, in _make_api_call
    operation_model, request_dict)
  File "/usr/lib/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/lib/python2.7/site-packages/botocore/endpoint.py", line 170, in _send_request
    success_response, exception):
  File "/usr/lib/python2.7/site-packages/botocore/endpoint.py", line 249, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
2017-06-07 13:19:46,891 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
```

**Comment by JordonPhillips** [comment]
Why would your SSL verify be failing on contacting STS? It seems pretty dangerous to let a connection to STS go unverified.

**Comment by trevorndodds** [comment]
@JordonPhillips that's very true and I understand the risks. Never the less the option exists --no-verify-ssl. Anyways I imported our own certs to work around this.  Just thought it may be a "bug" since you allow for no-verify-ssl yet it doesn't work in all cases.

**Comment by anshuld** [comment]
Why does the option -no-ssl-verify exist?
