### ISSUE TITLE
get-bucket-notification with json output dies with Circular reference detected 

### ISSUE THREAD

**Issue by groner** [aws/aws-cli#2808]
```
: kai@cakepile; aws --version   
aws-cli/1.11.144 Python/2.7.13 Linux/4.10.0-28-generic botocore/1.7.2
: kai@cakepile; aws s3api get-bucket-notification --bucket xxx
{
    "TopicConfiguration": {
        "Topic": "arn:aws:sns:us-east-1:123:xxx", 
        "Id": "xxx", 
        "Event": [
            
Circular reference detected
```

Here is the xml response (formatted with xmllint --format) and the stack trace.

```xml
<?xml version="1.0"?>
<NotificationConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <TopicConfiguration>
    <Id>xxx</Id>
    <Topic>arn:aws:sns:us-east-1:123:xxx</Topic>
    <Event>s3:ObjectCreated:*</Event>
    <Event>s3:ObjectRemoved:*</Event>
    <Filter>
      <S3Key>
        <FilterRule>
          <Name>Prefix</Name>
          <Value>trout/</Value>
        </FilterRule>
      </S3Key>
    </Filter>
  </TopicConfiguration>
</NotificationConfiguration>
```

```
Traceback (most recent call last):                   
  File "/home/kai/.local/lib/python2.7/site-packages/awscli/clidriver.py", line 200, in main              
    return command_table[parsed_args.command](remaining, parsed_args)                                     
  File "/home/kai/.local/lib/python2.7/site-packages/awscli/clidriver.py", line 338, in __call__          
    return command_table[parsed_args.operation](remaining, parsed_globals)                                
  File "/home/kai/.local/lib/python2.7/site-packages/awscli/clidriver.py", line 508, in __call__          
    call_parameters, parsed_globals)                 
  File "/home/kai/.local/lib/python2.7/site-packages/awscli/clidriver.py", line 628, in invoke            
    self._display_response(operation_name, response, parsed_globals)                                      
  File "/home/kai/.local/lib/python2.7/site-packages/awscli/clidriver.py", line 648, in _display_response 
    formatter(command_name, response)                
  File "/home/kai/.local/lib/python2.7/site-packages/awscli/formatter.py", line 76, in __call__           
    self._format_response(command_name, response_data, stream)                                            
  File "/home/kai/.local/lib/python2.7/site-packages/awscli/formatter.py", line 96, in _format_response   
    ensure_ascii=False)                              
  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump                                           
    for chunk in iterable:                           
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode                                     
    for chunk in _iterencode_dict(o, _current_indent_level):                                              
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict                                
    for chunk in chunks:                             
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict                                
    for chunk in chunks:                             
  File "/usr/lib/python2.7/json/encoder.py", line 332, in _iterencode_list                                
    for chunk in chunks:                             
  File "/usr/lib/python2.7/json/encoder.py", line 443, in _iterencode                                     
    for chunk in _iterencode(o, _current_indent_level):                                                   
  File "/usr/lib/python2.7/json/encoder.py", line 440, in _iterencode                                     
    raise ValueError("Circular reference detected")  
```

**Comment by groner** [comment]
The text and table output formats don't crash, but the events data seem to appear twice as both EVENT and EVENTS.  The EVENT fields appears to be just the repr of an etree element.
```
: kai@cakepile; aws s3api get-bucket-notification --bucket xxx --output text                                                                                                         
TOPICCONFIGURATION      dev userdata    arn:aws:sns:us-east-1:123:xxx
EVENT   <Element '{http://s3.amazonaws.com/doc/2006-03-01/}Event' at 0x7ff3b229a9c0>
EVENT   <Element '{http://s3.amazonaws.com/doc/2006-03-01/}Event' at 0x7ff3b229a9f0>
EVENTS  s3:ObjectCreated:*
EVENTS  s3:ObjectRemoved:*
```

**Comment by jamesls** [comment]
Thanks for reporting.  Just a heads up, the `get-bucket-notification` command is deprecated and has been replaced by `get-bucket-notification-configuration`.  We only keep this command for backwards compatibility.

I'll check to see what we can do to fix this, but in the meantime let me know if using `get-bucket-notification-configuration` doesn't work for you.

**Comment by groner** [comment]
`get-bucket-notification-configuration` works for me.  Thanks for the tip.

**Comment by KaibaLopez** [comment]
Hi,
I'm doing cleanup of old issues, and this one seems to have been responded so I'll close it.
Please open a new issue if you still have problems with this.
