### ISSUE TITLE
Error while switching to a role

### ISSUE THREAD

**Issue by abdulqadir2017** [aws/aws-cli#2822]
Version info for aws cli:

aws-cli/1.11.149 Python/2.7.9 Windows/8 botocore/1.7.7

While trying to switch to a role, I got an error. As suggested in the error description, reporting here.

```
C:\Users\Test12345>awslogs groups --profile prod-onlinedeveloper

================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.10.0
Python: 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]
boto3 version: 1.4.7
Platform: Windows-10-10.0.15063-SP0
Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': None, 'log_group_prefix': None, 'func': 'list_groups'}
Args: ['C:\\Users\\Test12345\\AppData\\Local\\Programs\\Python\\Python36\\Scripts\\awslogs', 'groups', '--profile', 'prod-onlinedeveloper']

Traceback (most recent call last):
  File "c:\users\Test12345\appdata\local\programs\python\python36\lib\site-packages\awslogs\bin.py", line 168, in main
    logs = AWSLogs(**vars(options))
  File "c:\users\Test12345\appdata\local\programs\python\python36\lib\site-packages\awslogs\core.py", line 62, in __init__
    region_name=self.aws_region
  File "c:\users\Test12345\appdata\local\programs\python\python36\lib\site-packages\boto3\__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "c:\users\Test12345\appdata\local\programs\python\python36\lib\site-packages\boto3\session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "c:\users\Test12345\appdata\local\programs\python\python36\lib\site-packages\botocore\session.py", line 836, in create_client
    client_config=config, api_version=api_version)
  File "c:\users\Test12345\appdata\local\programs\python\python36\lib\site-packages\botocore\client.py", line 71, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "c:\users\Test12345\appdata\local\programs\python\python36\lib\site-packages\botocore\client.py", line 283, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "c:\users\Test12345\appdata\local\programs\python\python36\lib\site-packages\botocore\args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "c:\users\Test12345\appdata\local\programs\python\python36\lib\site-packages\botocore\args.py", line 111, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "c:\users\Test12345\appdata\local\programs\python\python36\lib\site-packages\botocore\client.py", line 356, in resolve
    service_name, region_name)
  File "c:\users\Test12345\appdata\local\programs\python\python36\lib\site-packages\botocore\regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "c:\users\Test12345\appdata\local\programs\python\python36\lib\site-packages\botocore\regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
================================================================================
```

**Comment by stealthycoin** [comment]
I would suggest you open a ticket at the repository mentioned in the error trace. That tool has nothing to do with the AWS CLI and I don't have any familiarity with it so I can't be of any help.

https://github.com/jorgebastida/awslogs/issues/new

Though for what its worth it looks like you aren't providing a region and don't have the environment variable defined: https://github.com/jorgebastida/awslogs/blob/master/awslogs/bin.py#L55.
