### ISSUE TITLE
New wheel (0.30.0) breaks pip install of aws-cli

### ISSUE THREAD

**Issue by shaunbrady** [aws/aws-cli#2827]
Using this script:  https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py

we receive the following error:
```
(foo) [user@host foo]# pip list
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
pip (9.0.1)
setuptools (36.4.0)
wheel (0.30.0)
(foo) [user@host foo]# awscli-cwlogs==1.4.2                                                                                                                            
-bash: awscli-cwlogs==1.4.2: command not found
(foo) [user@host foo]# pip install awscli-cwlogs==1.4.2
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Collecting awscli-cwlogs==1.4.2
/home/user/foo/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/user/foo/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/home/user/foo/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/home/user/foo/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/home/user/foo/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading https://files.pythonhosted.org/packages/d2/2a/a6c8238279e374f9d72da8945b9a6233c8685145bc7099ddac96047d8c6e/awscli-cwlogs-1.4.2.tar.gz
Collecting awscli==1.11.41 (from awscli-cwlogs==1.4.2)
  Downloading https://files.pythonhosted.org/packages/fb/4f/99e5d4d1bc889cf9ffa5d598d270f266e6380aaf036bb7088f85f65ed3f0/awscli-1.11.41-py2.py3-none-any.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 1.1MB/s
Collecting six>=1.1.0 (from awscli-cwlogs==1.4.2)
  Downloading https://files.pythonhosted.org/packages/c8/0a/b6723e1bc4c516cb687841499455a8505b44607ab535be01091c0f24f079/six-1.10.0-py2.py3-none-any.whl
Collecting python-dateutil>=2.1 (from awscli-cwlogs==1.4.2)
  Downloading https://files.pythonhosted.org/packages/4b/0d/7ed381ab4fe80b8ebf34411d14f253e1cf3e56e2820ffa1d8844b23859a2/python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 5.4MB/s
Collecting botocore==1.5.4 (from awscli==1.11.41->awscli-cwlogs==1.4.2)
  Downloading https://files.pythonhosted.org/packages/f2/ee/26d41fd7c901a491c5f9d5b4687295ccde57a5781b03e08b82ef80700485/botocore-1.5.4-py2.py3-none-any.whl (3.1MB)
    100% |████████████████████████████████| 3.1MB 385kB/s
Collecting rsa<=3.5.0,>=3.1.2 (from awscli==1.11.41->awscli-cwlogs==1.4.2)
  Downloading https://files.pythonhosted.org/packages/e1/ae/baedc9cb175552e95f3395c43055a6a5e125ae4d48a1d7a924baca83e92e/rsa-3.4.2-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 9.0MB/s
Collecting s3transfer<0.2.0,>=0.1.9 (from awscli==1.11.41->awscli-cwlogs==1.4.2) 
  Downloading https://files.pythonhosted.org/packages/53/a8/dbee2c13508a4f1060ec44a0889d6766508912905a16edb593f628e92db1/s3transfer-0.1.11-py2.py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 9.8MB/s
Collecting argparse>=1.1; python_version == "2.6" (from awscli==1.11.41->awscli-cwlogs==1.4.2)
  Downloading https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
Collecting docutils>=0.10 (from awscli==1.11.41->awscli-cwlogs==1.4.2)
  Downloading https://files.pythonhosted.org/packages/50/09/c53398e0005b11f7ffb27b7aa720c617aba53be4fb4f4f3f06b9b5c60f28/docutils-0.14-py2-none-any.whl (543kB)
    100% |████████████████████████████████| 552kB 2.2MB/s
Collecting colorama<=0.3.7,>=0.2.5 (from awscli==1.11.41->awscli-cwlogs==1.4.2)
  Downloading https://files.pythonhosted.org/packages/b7/8e/ddb32ddaabd431813e180ca224e844bab8ad42fbb47ee07553f0ec44cd86/colorama-0.3.7-py2.py3-none-any.whl
Collecting PyYAML<=3.12,>=3.10 (from awscli==1.11.41->awscli-cwlogs==1.4.2)
  Downloading https://files.pythonhosted.org/packages/4a/85/db5a2df477072b2902b0eb892feb37d88ac635d36245a72a6a69b23b383a/PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 4.4MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6fivNt/PyYAML/setup.py", line 83, in <module>
        from wheel.bdist_wheel import bdist_wheel                                                                                                                      
      File "/home/user/foo/lib/python2.6/site-packages/wheel/bdist_wheel.py", line 407
        ignore=lambda x, y: {'PKG-INFO', 'requires.txt', 'SOURCES.txt',
                                       ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6fivNt/PyYAML/
```

This is RHEL6 running Python 2.6.6 (which still claims to be supported).  From the `pip list` at the top, one can see the recently released 0.30.0 wheel removes support for Python 2.6.  I believe the best course of action would be to pin wheel to <0.30.0.

If aws-cli opted to drop support for Python 2.6, it would be good if the script detect that and complained early.

Let me know how I can help further.

Thanks!

**Comment by stealthycoin** [comment]
This should be fixed now with https://github.com/aws/aws-cli/commit/c04df1f1779fe3785302debf296166cc763f767f.

Please reopen this if that did not resolve your issue.

**Comment by shaunbrady** [comment]
@stealthycoin Thanks!  Do you have any control of or know any one who does over the  https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py ?  It still references 1.4.2.

**Comment by isuftin** [comment]
@shaunbrady Good question. I've been scouring the net and am unable to find who owns that script.

**Comment by shaunbrady** [comment]
Our work around was just to move to using Python 2.7 (it was already installed else where on the machine).  Maybe this is just the incentive we need, as it looks like Python (the project) itself is wanting to EOL 2.6.

**Comment by stealthycoin** [comment]
2.6 has been EOL since 2013, so I would suggest upgrading to python 2.7 at the very least.
