### ISSUE TITLE
cloudsearchdomain - unable to upload , Problem accessing /collection1/2013-01-01/documents/batch

### ISSUE THREAD

**Issue by jimyjohny** [aws/aws-cli#2872]
Following error when trying to upload, any idea what could be wrong ?

2017-10-05 17:04:03,930 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2017-10-05 17:04:03,931 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): doc-pad-xxxxxxxc6lzey3uly.us-east-1.cloudsearch.amazonaws.com

2017-10-05 17:04:55,064 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "POST /2013-01-01/documents/batch?format=sdk HTTP/1.1" 404 1403
2017-10-05 17:04:55,064 - MainThread - botocore.parsers - DEBUG - Response headers: {'content-length': '1403', 'content-type': 'text/html;charset=ISO-8859-1', 'connection': 'keep-alive', 'cache-control': 'must-revalidate,no-cache,no-store'}
2017-10-05 17:04:55,064 - MainThread - botocore.parsers - DEBUG - Response body:
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /collection1/2013-01-01/documents/batch. Reason:
<pre>    Not Found</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>

**Comment by kyleknap** [comment]
Not too sure what the issue may be. Could you post the CLI command you are using and the complete debug logs? Going to need both to be able to look into this.

**Comment by jimyjohny** [comment]
[centos@ip-172-31-48-34 ~]$ aws cloudsearchdomain --endpoint-url https://doc-parker-xxxxxxxxxxxxxxxx.us-east-1.cloudsearch.amazonaws.com upload-documents --content-type application/json --documents parker.json --debug
2017-10-07 04:14:13,775 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.11.165 Python/2.6.6 Linux/2.6.32-642.13.1.el6.x86_64 botocore/1.7.23
2017-10-07 04:14:13,776 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['cloudsearchdomain', '--endpoint-url', 'https://doc-parker-xxxxxxxxxxxxxxxx.us-east-1.cloudsearch.amazonaws.com', 'upload-documents', '--content-type', 'application/json', '--documents', 'parker.json', '--debug']
2017-10-07 04:14:13,776 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x3289230>
2017-10-07 04:14:13,776 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-10-07 04:14:13,776 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x2edbaa0>
2017-10-07 04:14:13,776 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-10-07 04:14:13,776 - MainThread - botocore.session - DEBUG - Loading variable credentials_file from defaults.
2017-10-07 04:14:13,776 - MainThread - botocore.session - DEBUG - Loading variable config_file from defaults.
2017-10-07 04:14:13,776 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-10-07 04:14:13,776 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_timeout from defaults.
2017-10-07 04:14:13,776 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-10-07 04:14:13,776 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_num_attempts from defaults.
2017-10-07 04:14:13,777 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-10-07 04:14:13,777 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-10-07 04:14:13,777 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2017-10-07 04:14:13,778 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python2.6/site-packages/botocore/data/cloudsearchdomain/2013-01-01/service-2.json
2017-10-07 04:14:13,785 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.cloudsearchdomain: calling handler <function register_retries_for_service at 0x2a0a668>
2017-10-07 04:14:13,786 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: cloudsearchdomain
2017-10-07 04:14:13,787 - MainThread - botocore.hooks - DEBUG - Event building-command-table.cloudsearchdomain: calling handler <function add_waiters at 0x32ca0c8>
2017-10-07 04:14:13,790 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'documents', <awscli.arguments.CLIArgument object at 0x33ff810>), (u'content-type', <awscli.arguments.CLIArgument object at 0x33ff850>)])
2017-10-07 04:14:13,790 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudsearchdomain.upload-documents: calling handler <function add_streaming_output_arg at 0x32901b8>
2017-10-07 04:14:13,790 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudsearchdomain.upload-documents: calling handler <function add_cli_input_json at 0x2edf9b0>
2017-10-07 04:14:13,790 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudsearchdomain.upload-documents: calling handler <function unify_paging_params at 0x32029b0>
2017-10-07 04:14:13,793 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudsearchdomain.upload-documents: calling handler <function add_generate_skeleton at 0x31ef7d0>
2017-10-07 04:14:13,793 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cloudsearchdomain.upload-documents: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x33ff910>>
2017-10-07 04:14:13,793 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cloudsearchdomain.upload-documents: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x33ff990>>
2017-10-07 04:14:13,794 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudsearchdomain.upload-documents.documents: calling handler <function uri_param at 0x2e57230>
2017-10-07 04:14:13,794 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.cloudsearchdomain.upload-documents: calling handler <awscli.argprocess.ParamShorthandParser object at 0x32d04d0>
2017-10-07 04:14:13,794 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'parker.json' for parameter "documents": <open file u'parker.json', mode 'rb' at 0x32655d0>
2017-10-07 04:14:13,795 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudsearchdomain.upload-documents.content-type: calling handler <function uri_param at 0x2e57230>
2017-10-07 04:14:13,795 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.cloudsearchdomain.upload-documents: calling handler <awscli.argprocess.ParamShorthandParser object at 0x32d04d0>
2017-10-07 04:14:13,795 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'application/json' for parameter "content_type": u'application/json'
2017-10-07 04:14:13,795 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudsearchdomain.upload-documents.cli-input-json: calling handler <function uri_param at 0x2e57230>
2017-10-07 04:14:13,795 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudsearchdomain.upload-documents.generate-cli-skeleton: calling handler <function uri_param at 0x2e57230>
2017-10-07 04:14:13,795 - MainThread - botocore.hooks - DEBUG - Event calling-command.cloudsearchdomain.upload-documents: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x33ff910>>
2017-10-07 04:14:13,795 - MainThread - botocore.hooks - DEBUG - Event calling-command.cloudsearchdomain.upload-documents: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x33ff990>>
2017-10-07 04:14:13,795 - MainThread - botocore.hooks - DEBUG - Event calling-command.cloudsearchdomain.upload-documents: calling handler <function validate_endpoint_url at 0x30a3398>
2017-10-07 04:14:13,795 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-10-07 04:14:13,795 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-10-07 04:14:13,795 - MainThread - botocore.session - DEBUG - Loading variable region from config file with value 'us-east-1'.
2017-10-07 04:14:13,796 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-10-07 04:14:13,796 - MainThread - botocore.session - DEBUG - Loading variable ca_bundle from defaults.
2017-10-07 04:14:13,796 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-10-07 04:14:13,796 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2017-10-07 04:14:13,796 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2017-10-07 04:14:13,796 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2017-10-07 04:14:13,796 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2017-10-07 04:14:13,796 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2017-10-07 04:14:13,797 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python2.6/site-packages/botocore/data/endpoints.json
2017-10-07 04:14:13,827 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-10-07 04:14:13,828 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.cloudsearchdomain: calling handler <function add_generate_presigned_url at 0x29a9b90>
2017-10-07 04:14:13,828 - MainThread - botocore.regions - DEBUG - Creating a regex based endpoint for cloudsearchdomain, us-east-1
2017-10-07 04:14:13,828 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2017-10-07 04:14:13,832 - MainThread - botocore.endpoint - DEBUG - Setting cloudsearchdomain timeout as (60, 60)
2017-10-07 04:14:13,833 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: cloudsearchdomain
2017-10-07 04:14:13,833 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.cloudsearchdomain.UploadDocuments: calling handler <function generate_idempotent_uuid at 0x2a0a0c8>
2017-10-07 04:14:13,834 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=UploadDocuments) (verify_ssl=True) with params: {'body': <open file u'parker.json', mode 'rb' at 0x32655d0>, 'url': u'https://doc-parker-xxxxxxxxxxxxxxxx.us-east-1.cloudsearch.amazonaws.com/2013-01-01/documents/batch?format=sdk', 'headers': {u'Content-Type': 'application/json', 'User-Agent': 'aws-cli/1.11.165 Python/2.6.6 Linux/2.6.32-642.13.1.el6.x86_64 botocore/1.7.23'}, 'context': {'auth_type': None, 'client_region': 'us-east-1', 'has_streaming_input': True, 'client_config': <botocore.config.Config object at 0x3403790>}, 'query_string': {}, 'url_path': u'/2013-01-01/documents/batch?format=sdk', 'method': u'POST'}
2017-10-07 04:14:13,834 - MainThread - botocore.hooks - DEBUG - Event request-created.cloudsearchdomain.UploadDocuments: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x34036d0>>
2017-10-07 04:14:13,834 - MainThread - botocore.hooks - DEBUG - Event choose-signer.cloudsearchdomain.UploadDocuments: calling handler <function set_operation_specific_signer at 0x2a05758>
2017-10-07 04:14:13,976 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2017-10-07 04:14:13,976 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/2013-01-01/documents/batch
format=sdk
content-type:application/json
host:doc-parker-xxxxxxxxxxxxxxxx.us-east-1.cloudsearch.amazonaws.com
x-amz-date:20171007T041413Z

content-type;host;x-amz-date
512f52d9c9d0483389947d36fb71a9d9419ad0a15807fdec64a324df671c5741
2017-10-07 04:14:13,976 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20171007T041413Z
20171007/us-east-1/cloudsearch/aws4_request
8a27839f9dcb2e680d1c0df7bb20e516b504970973cbda0cedd527737f47c248
2017-10-07 04:14:13,976 - MainThread - botocore.auth - DEBUG - Signature:
ba3d2720d213825f9b0b67698efcc785a68197c28b4c1c9fb5ecd903b4a4a089
2017-10-07 04:14:13,982 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2017-10-07 04:14:13,982 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): doc-parker-xxxxxxxxxxxxxxxx.us-east-1.cloudsearch.amazonaws.com


2017-10-07 04:15:05,035 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "POST /2013-01-01/documents/batch?format=sdk HTTP/1.1" 404 1403
2017-10-07 04:15:05,036 - MainThread - botocore.parsers - DEBUG - Response headers: {'content-length': '1403', 'content-type': 'text/html;charset=ISO-8859-1', 'connection': 'keep-alive', 'cache-control': 'must-revalidate,no-cache,no-store'}
2017-10-07 04:15:05,036 - MainThread - botocore.parsers - DEBUG - Response body:
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /collection1/2013-01-01/documents/batch. Reason:
<pre>    Not Found</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                

</body>
</html>

2017-10-07 04:15:05,036 - MainThread - botocore.hooks - DEBUG - Event needs-retry.cloudsearchdomain.UploadDocuments: calling handler <botocore.retryhandler.RetryHandler object at 0x33ff090>
2017-10-07 04:15:05,036 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2017-10-07 04:15:05,037 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/awscli/clidriver.py", line 200, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/lib/python2.6/site-packages/awscli/clidriver.py", line 338, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/lib/python2.6/site-packages/awscli/clidriver.py", line 508, in __call__
    call_parameters, parsed_globals)
  File "/usr/lib/python2.6/site-packages/awscli/clidriver.py", line 627, in invoke
    client, operation_name, parameters, parsed_globals)
  File "/usr/lib/python2.6/site-packages/awscli/clidriver.py", line 639, in _make_client_call
    **parameters)
  File "/usr/lib/python2.6/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.6/site-packages/botocore/client.py", line 601, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (404) when calling the UploadDocuments operation: <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /collection1/2013-01-01/documents/batch. Reason:
<pre>    Not Found</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                

</body>
</html>

2017-10-07 04:15:05,038 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

An error occurred (404) when calling the UploadDocuments operation: <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /collection1/2013-01-01/documents/batch. Reason:
<pre>    Not Found</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                

</body>
</html>

[centos@ip-172-31-48-34 ~]$

**Comment by JordonPhillips** [comment]
It's possible that the domain you're trying to access is an older version than `2013-01-01`. Aside from that I'm unsure what the issue might be. I would recommend reaching out to AWS Support or asking on StackOverflow to see if anybody else has run into this issue.
