### ISSUE TITLE
Weird zip behavior during "aws deploy push"

### ISSUE THREAD

**Issue by ylmrx** [aws/aws-cli#2893]
1. **the process fails harshly when zipping a folder > 4GB.**

It shows this debug trace : 
`10 error: 'L' format requires 0 <= number <= 4294967295`

That is, despite : `zf = zipfile.ZipFile(tf, 'w', allowZip64=True)` (allowZip64 flag **should** allow very large archive) [1]

2. **the tmpfile is deleted at creation (but its FD is still being written to).**

This gave us a hard time when debugging this as we couldn't easily find the temporary file.
I tried to zip a file with the relevant python lib and mimic the options you use : i couldn't reproduce this behavior.
I feel the temporary file should be held visible.

[1] -- `awscli/customizations/codedeploy/push.py` line 187

Current awscli : `aws-cli/1.11.170 Python/2.7.3 Linux/3.14.79-cerberhost-0.11.0deb7+nbs20161028-grsec botocore/1.7.28`

**Comment by jamesls** [comment]
I'm not sure why you're getting the zip error, because as you mention we're setting `allowZip64=True`.  Can you share the full stack trace (and/or debug log)?  I'm curious where exactly in the zipfile module that message originates.

**Comment by ylmrx** [comment]
Sure , here you go ! 
```
2017-10-13 11:16:44,862 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2017-10-13 11:16:44,867 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python2.7/dist-packages/botocore/data/endpoints.json
2017-10-13 11:16:44,879 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: codedeploy
2017-10-13 11:16:44,880 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.codedeploy: calling handler <function add_generate_presigned_url at 0x4437b18>
2017-10-13 11:16:44,880 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2017-10-13 11:16:44,883 - MainThread - botocore.endpoint - DEBUG - Setting codedeploy timeout as (60, 60)
2017-10-13 11:16:44,891 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python2.7/dist-packages/botocore/data/s3/2006-03-01/service-2.json
2017-10-13 11:16:44,931 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2017-10-13 11:16:44,933 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x4437cf8>
2017-10-13 11:16:44,933 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x4437b18>
2017-10-13 11:16:44,933 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2017-10-13 11:16:44,935 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2017-10-13 11:16:44,936 - MainThread - botocore.client - DEBUG - Defaulting to S3 virtual host style addressing with path style addressing fallback.
2017-10-13 11:20:11,742 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 200, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 338, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/codedeploy/push.py", line 121, in _run_main
    self._push(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/codedeploy/push.py", line 141, in _push
    params.ignore_hidden_files
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/codedeploy/push.py", line 202, in _compress
    zf.write(filename, arcname, ZIP_COMPRESSION_MODE)
  File "/usr/lib/python2.7/zipfile.py", line 1118, in write
    zinfo.file_size))
error: 'L' format requires 0 <= number <= 4294967295
2017-10-13 11:20:11,806 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

'L' format requires 0 <= number <= 4294967295
```

**Comment by JordonPhillips** [comment]
@ylmrx that looks like it's a [python bug](https://bugs.python.org/issue9720). Unfortunately it looks like you'll need to upgrade your python version to work around it. It looks like that made it into python 2.7.4+ on the python 2 branch.

**Comment by ylmrx** [comment]
Hi :)
I didn’t check that part. And the distribution we use is kinda outdated,
didn’t take the time to check the behavior on a fresher setup.
Thanks a lot for your time anyway.

**Comment by JordonPhillips** [comment]
Sorry we couldn't do more
