### ISSUE TITLE
Installing aws-cli on Amazon Linux fails

### ISSUE THREAD

**Issue by bdichter** [aws/aws-cli#2902]
Installing via chef recipe that works fine for CentOS and RHEL but is failing on Amazon Linux 7. Also tried 'pip install awscli' without success. 

Existing OS:
Linux ip-10-26-2-103 4.9.38-16.35.amzn1.x86_64 #1 SMP Sat Aug 5 01:39:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Existing installed version of awscli:
aws --version
aws-cli/1.11.166 Python/2.7.12 Linux/4.9.38-16.35.amzn1.x86_64 botocore/1.7.24

**Output from chef run**
* execute[install awscli bundle] action run
    [execute] Running cmd: /usr/bin/python virtualenv.py --no-download --python /usr/bin/python /usr/local/aws
              Traceback (most recent call last):
                File "./tmp/awscli-bundle/install", line 139, in <module>
                  main()
                File "./tmp/awscli-bundle/install", line 130, in main
                  pip_install_packages(opts.install_dir)
                File "./tmp/awscli-bundle/install", line 93, in pip_install_packages
                  assert len(cli_tarball) == 1
              AssertionError

    ================================================================================
    Error executing action `run` on resource 'execute[install awscli bundle]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of ./tmp/awscli-bundle/install  -i /usr/local/aws -b /usr/bin/aws ----
    STDOUT: Running cmd: /usr/bin/python virtualenv.py --no-download --python /usr/bin/python /usr/local/aws
    STDERR: Traceback (most recent call last):
      File "./tmp/awscli-bundle/install", line 139, in <module>
        main()
      File "./tmp/awscli-bundle/install", line 130, in main
        pip_install_packages(opts.install_dir)
      File "./tmp/awscli-bundle/install", line 93, in pip_install_packages
        assert len(cli_tarball) == 1
    AssertionError
    ---- End output of ./tmp/awscli-bundle/install  -i /usr/local/aws -b /usr/bin/aws ----
    Ran ./tmp/awscli-bundle/install  -i /usr/local/aws -b /usr/bin/aws returned 1

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/icfolson_base_role/recipes/awscli-install.rb

     25: execute 'install awscli bundle' do
     26:   command "./tmp/awscli-bundle/install  -i /usr/local/aws -b /usr/bin/aws"
     27: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/icfolson_base_role/recipes/awscli-install.rb:25:in `from_file'

    execute("install awscli bundle") do
      action [:run]
      retries 0
      retry_delay 2
      default_guard_interpreter :execute
      command "./tmp/awscli-bundle/install  -i /usr/local/aws -b /usr/bin/aws"
      backup 5
      returns 0
      user nil
      declared_type :execute
      cookbook_name "icfolson_base_role"
      recipe_name "awscli-install"
    end

    Platform:
    ---------
    x86_64-linux

Running handlers:
Running handlers complete

**Output from pip install awscli**
pip install awscli
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3020, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 616, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 629, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 807, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pip==7.1.0

**Comment by JordonPhillips** [comment]
The first error means that you've got multiple cli tarballs in your unzipped installer directory in the 'packages' folder. The second error seems to be related to pip itself. I would recommend trying `pip install --upgrade pip` to resolve that.

**Comment by JordonPhillips** [comment]
To expand a bit:

With the first issue, you've got a directory where you've extracted multiple versions of the CLI. The installer doesn't know which one you want, so it fails. You should check to see why there's extra files laying about. You may want to clean up that directory if you have no need for them. That should solve your issue there.

The second issue is a pip upgrade issue. Somewhere along the line pip was installed with setuptools pointing to that specific pip version. It was then later upgraded, but your user binary wasn't. Your user bin then errors out when it can't find the version it expects. `pip install --upgrade pip` should fix that. If it still doesn't work you might try `pip install --upgrade --force-reinstall pip`.

**Comment by JordonPhillips** [comment]
Closing due to inactivity. If you're still having issues, feel free to open up a new github issue!

**Comment by bdichter** [comment]
Thanks Jordon! This helped to resolve my issue.
