### ISSUE TITLE
An error occurred (InvalidInstanceID.NotLinkable) when calling the AttachClassicLinkVpc operation

### ISSUE THREAD

**Issue by ZadeAnant** [aws/aws-cli#2917]
Hi All

I am getting below error while attaching Classic Link EC2 instance to Custom VPC

aws ec2 attach-classic-link-vpc --groups sg-05fe4d77 --instance-id i-0b01cce3e9092465a --vpc-id vpc-2d78b355 --region us-east-1 --debug
2017-10-21 22:40:27,737 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.11.117 Python/2.7.9 Windows/8 botocore/1.5.80
2017-10-21 22:40:27,737 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['ec2', 'attach-classic-link-vpc', '--groups', 'sg-05fe4d77', '--instance-id', 'i-0b01cce3e9092465a', '--vpc-id', 'vpc-2d78b355', '--region', 'us-east-1', '--debug']
2017-10-21 22:40:27,737 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x0000000003E3ADD8>
2017-10-21 22:40:27,737 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x0000000003B55208>
2017-10-21 22:40:27,737 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLI\botocore\data\ec2\2016-11-15\service-2.json
2017-10-21 22:40:27,846 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.ec2: calling handler <function register_retries_for_service at 0x0000000003369978>
2017-10-21 22:40:27,846 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: ec2
2017-10-21 22:40:27,846 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <functools.partial object at 0x0000000003E64908>
2017-10-21 22:40:27,846 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-instance
2017-10-21 22:40:27,846 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-volume
2017-10-21 22:40:27,846 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <function add_waiters at 0x0000000003E3FD68>
2017-10-21 22:40:27,878 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLI\botocore\data\ec2\2016-11-15\waiters-2.json
2017-10-21 22:40:27,894 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'dry-run', <awscli.arguments.BooleanArgument object at 0x0000000004C46D30>), (u'no-dry-run', <awscli.arguments.BooleanArgument object at 0x0000000004C46D68>), (u'groups', <awscli.arguments.ListArgument object at 0x0000000004C46DA0>), (u'instance-id', <awscli.arguments.CLIArgument object at 0x0000000004C46DD8>), (u'vpc-id', <awscli.arguments.CLIArgument object at 0x0000000004C46E10>)])
2017-10-21 22:40:27,894 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.attach-classic-link-vpc: calling handler <function add_streaming_output_arg at 0x0000000003E3F2E8>
2017-10-21 22:40:27,894 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.attach-classic-link-vpc: calling handler <function _rename_arg at 0x0000000003E83198>
2017-10-21 22:40:27,894 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.attach-classic-link-vpc: calling handler <function _rename_arg at 0x0000000003E83C18>
2017-10-21 22:40:27,894 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.attach-classic-link-vpc: calling handler <functools.partial object at 0x0000000003E649F8>
2017-10-21 22:40:27,894 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.attach-classic-link-vpc: calling handler <function add_cli_input_json at 0x0000000003B55EB8>
2017-10-21 22:40:27,894 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.attach-classic-link-vpc: calling handler <function unify_paging_params at 0x0000000003D9B208>
2017-10-21 22:40:27,926 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLI\botocore\data\ec2\2016-11-15\paginators-1.json
2017-10-21 22:40:27,926 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.attach-classic-link-vpc: calling handler <function add_generate_skeleton at 0x0000000003D8B908>
2017-10-21 22:40:27,926 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.attach-classic-link-vpc: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x0000000004C46E80>>
2017-10-21 22:40:27,926 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.attach-classic-link-vpc: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x0000000004C46F28>>
2017-10-21 22:40:27,926 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.ec2.attach-classic-link-vpc: calling handler <functools.partial object at 0x0000000004BC6B38>
2017-10-21 22:40:27,926 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.attach-classic-link-vpc.dry-run: calling handler <function uri_param at 0x00000000035E5CF8>
2017-10-21 22:40:27,926 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.attach-classic-link-vpc.groups: calling handler <function uri_param at 0x00000000035E5CF8>
2017-10-21 22:40:27,926 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.ec2.attach-classic-link-vpc: calling handler <awscli.argprocess.ParamShorthandParser object at 0x0000000003649898>
2017-10-21 22:40:27,926 - MainThread - awscli.arguments - DEBUG - Unpacked value of [u'sg-05fe4d77'] for parameter "groups": [u'sg-05fe4d77']
2017-10-21 22:40:27,926 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.attach-classic-link-vpc.instance-id: calling handler <function uri_param at 0x00000000035E5CF8>
2017-10-21 22:40:27,926 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.ec2.attach-classic-link-vpc: calling handler <awscli.argprocess.ParamShorthandParser object at 0x0000000003649898>
2017-10-21 22:40:27,926 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'i-0b01cce3e9092465a' for parameter "instance_id": u'i-0b01cce3e9092465a'
2017-10-21 22:40:27,926 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.attach-classic-link-vpc.vpc-id: calling handler <function uri_param at 0x00000000035E5CF8>
2017-10-21 22:40:27,926 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.ec2.attach-classic-link-vpc: calling handler <awscli.argprocess.ParamShorthandParser object at 0x0000000003649898>
2017-10-21 22:40:27,926 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'vpc-2d78b355' for parameter "vpc_id": u'vpc-2d78b355'
2017-10-21 22:40:27,926 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.attach-classic-link-vpc.cli-input-json: calling handler <function uri_param at 0x00000000035E5CF8>
2017-10-21 22:40:27,926 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.attach-classic-link-vpc.generate-cli-skeleton: calling handler <function uri_param at 0x00000000035E5CF8>
2017-10-21 22:40:27,926 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.attach-classic-link-vpc: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x0000000004C46E80>>
2017-10-21 22:40:27,926 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.attach-classic-link-vpc: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x0000000004C46F28>>
2017-10-21 22:40:27,926 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2017-10-21 22:40:27,926 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2017-10-21 22:40:27,926 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2017-10-21 22:40:27,926 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2017-10-21 22:40:27,940 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLI\botocore\data\endpoints.json
2017-10-21 22:40:27,957 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: ec2
2017-10-21 22:40:27,957 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.ec2: calling handler <function add_generate_presigned_url at 0x000000000332F438>
2017-10-21 22:40:27,957 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2017-10-21 22:40:27,971 - MainThread - botocore.endpoint - DEBUG - Setting ec2 timeout as (60, 60)
2017-10-21 22:40:27,971 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.ec2.AttachClassicLinkVpc: calling handler <bound method ParameterAlias.alias_parameter_in_call of <botocore.handlers.ParameterAlias object at 0x000000000336E3C8>>
2017-10-21 22:40:27,971 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.ec2.AttachClassicLinkVpc: calling handler <function generate_idempotent_uuid at 0x0000000003369438>
2017-10-21 22:40:27,971 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=AttachClassicLinkVpc) (verify_ssl=True) with params: {'body': {'Action': u'AttachClassicLinkVpc', u'InstanceId': u'i-0b01cce3e9092465a', 'Version': u'2016-11-15', u'VpcId': u'vpc-2d78b355', u'SecurityGroupId.1': u'sg-05fe4d77'}, 'url': u'https://ec2.us-east-1.amazonaws.com/', 'headers': {'User-Agent': 'aws-cli/1.11.117 Python/2.7.9 Windows/8 botocore/1.5.80'}, 'context': {'auth_type': None, 'client_region': u'us-east-1', 'has_streaming_input': False, 'client_config': <botocore.config.Config object at 0x0000000004F2AB38>}, 'query_string': '', 'url_path': '/', 'method': u'POST'}
2017-10-21 22:40:27,971 - MainThread - botocore.hooks - DEBUG - Event request-created.ec2.AttachClassicLinkVpc: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x0000000004F2ABA8>>
2017-10-21 22:40:27,971 - MainThread - botocore.hooks - DEBUG - Event choose-signer.ec2.AttachClassicLinkVpc: calling handler <function set_operation_specific_signer at 0x0000000003369358>
2017-10-21 22:40:27,971 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2017-10-21 22:40:27,971 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

host:ec2.us-east-1.amazonaws.com
x-amz-date:20171021T171027Z

host;x-amz-date
699ab9d00243355bf3a4f04bec034f10aba1bc8d301a7570e310edc292a05043
2017-10-21 22:40:27,971 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20171021T171027Z
20171021/us-east-1/ec2/aws4_request
ba83de29cca4923543a120b499f6432fbf32b898dcb786a61dc48c39463c945d
2017-10-21 22:40:27,971 - MainThread - botocore.auth - DEBUG - Signature:
d144be26c378597ee577ce8e2210b7a667b8ba36e263fdae8f9b67660a43144b
2017-10-21 22:40:27,971 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2017-10-21 22:40:27,971 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
2017-10-21 22:40:30,325 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "POST / HTTP/1.1" 400 None
2017-10-21 22:40:30,325 - MainThread - botocore.parsers - DEBUG - Response headers: {'transfer-encoding': 'chunked', 'date': 'Sat, 21 Oct 2017 17:10:28 GMT', 'connection': 'close', 'server': 'AmazonEC2'}
2017-10-21 22:40:30,325 - MainThread - botocore.parsers - DEBUG - Response body:
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidInstanceID.NotLinkable</Code><Message>Only EC2-Classic instances may be linked.</Message></Error></Errors><RequestID>8ecbf318-7182-4c2a-9ec8-e1df32d91974</RequestID></Response>
2017-10-21 22:40:30,325 - MainThread - botocore.hooks - DEBUG - Event needs-retry.ec2.AttachClassicLinkVpc: calling handler <botocore.retryhandler.RetryHandler object at 0x000000000381ADD8>
2017-10-21 22:40:30,325 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2017-10-21 22:40:30,341 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli\clidriver.pyc", line 200, in main
  File "awscli\clidriver.pyc", line 338, in __call__
  File "awscli\clidriver.pyc", line 508, in __call__
  File "awscli\clidriver.pyc", line 627, in invoke
  File "awscli\clidriver.pyc", line 639, in _make_client_call
  File "botocore\client.pyc", line 310, in _api_call
  File "botocore\client.pyc", line 599, in _make_api_call
ClientError: An error occurred (InvalidInstanceID.NotLinkable) when calling the AttachClassicLinkVpc operation: Only EC2-Classic instances may be linked.
2017-10-21 22:40:30,341 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

An error occurred (InvalidInstanceID.NotLinkable) when calling the AttachClassicLinkVpc operation: Only EC2-Classic instances may be linked.

aws --version
aws-cli/1.11.117 Python/2.7.9 Windows/8 botocore/1.5.80

**Comment by JordonPhillips** [comment]
> Only EC2-Classic instances may be linked.

Basically, this is only valid for older instance types. Newer instances connect to VPCs differently. If that isn't enough detail, I'd recommend asking on the service forums or StackOverflow to get more details.

**Comment by ZadeAnant** [comment]
Hi
Thanks for reply, I am trying to enable communication between EC2 instance of Default VPC and custom VPC via ClassicLink. enabled classiclink for custom vpc by # aws ec2 enable-vpc-classic-link --vpc-id xxxxx
It added route 10.0.0.0/8 in route table for custom vpc as well. but while attaching(linking EC2 instance ) of default vpc it gives error for InvalidInstanceID.NotLinkable. As per Amazon error docs did not help much. Please shed more detail about configuration if something missing.
