### ISSUE TITLE
PaginationError when running aws logs filter-log-events cmd

### ISSUE THREAD

**Issue by nguyentienlong** [aws/aws-cli#3022]
**I run this command to get the log from aws**

`aws logs filter-log-events --log-group-name API-Gateway-Execution-Logs_xxx/production --start-time $START_DATE_TIME --end-time $END_DATE_TIME --output text --debug`

**I got this error:**
`PaginationError: Error during pagination: The same next token was received twice:`

**aws-cli information:**
`aws-cli/1.14.3 Python/2.7.12 Linux/4.9.41-moby botocore/1.8.7`

**This is full debug**
```
EVENTS  33720918012672652287176153475475898958554590560263274504        1512098260147   07e1cd7dca89a1678042477183b7ac3f        (3010794d-d646-11e7-b323-f56f63e49834) Method request headers: {Accept=application/json, CloudFront-Viewer-Country=KR, CloudFront-Forwarded-Proto=https, CloudFront-Is-Tablet-Viewer=false, CloudFront-Is-Mobile-Viewer=false, User-Agent=Jakarta Commons-HttpClient/3.1, X-Forwarded-Proto=https, CloudFront-Is-SmartTV-Viewer=false, Host=api.ipricegroup.com, X-Forwarded-Port=443, X-Amzn-Trace-Id=Root=1-5a20c9d4-7f88305c7acc00ff469537bc, Via=1.1 19570722ae30f74e73f59fbd42a269be.cloudfront.net (CloudFront), Access-Control-Allow-Credentials=true, x-api-key=**********************************0QD6Cf, X-Amz-Cf-Id=Igkpu7vr5QyUPhQtUgxEq4psBPEXdZOR-m2axCoXRzBzs7R9Mf-WFQ==, X-Forwarded-For=52.78.14.180, 54.182.204.62, CloudFront-Is-Desktop-Viewer=true} 1512098260057
SEARCHEDLOGSTREAMS      07e1cd7dca89a1678042477183b7ac3f        False
SEARCHEDLOGSTREAMS      07e1cd7dca89a1678042477183b7ac3f        False
SEARCHEDLOGSTREAMS      07e1cd7dca89a1678042477183b7ac3f        False
SEARCHEDLOGSTREAMS      07e1cd7dca89a1678042477183b7ac3f        False
...skipping...
sGUccstGXlW2WVcmCN9RlJQKTTKX2nMmVCTw6OA3ZY6_Iq5ssGSy8QwwHHpxwDShsrGLDXH1AnIeSlfF-ngL8btiQzxiJDuUOXgPmRr9cE0p4M_6lcFFLhUSxJnZDORpUqkreOZaC2FkaKoiRes5UzPxGsqNwI5RBSyl4WVEjDZv_ohfqAOuCwrx2tosGhXaCga4yYIJGaaggTL-0yZQNpvkocPxiFV31pzOKRmSuqvY5vrOoCHQ9lD79n60tPx2hl2K7HpdLhbJ_qZDqm018svZZ124ijGuwLBz3U7Ray_pRKkRXq-Vm22kv8GvyZ2gNuOPcqyGl-xvdVjl36CDb5ERp_KJCRGLs9dlPisbdo7d_mhTCfeQxBavybGvPBTa1Nt-QdVGvzl51zhwsD_yzNusqxkIzsjglhkcKA9DZ4aripdsau0jTi2m_aW7NdXjz_J5jdz8ACZq6IegZTAjfu9O25QQ_EzdX64BG6bTjN80QB8U-RrAPEAlOWJAQhYF9nPc18e8F8o-6t6dbH3FAwi066LRnu9YvTxxHtTmpzbFPtGkxrGLuzRAPD6b4egbLhXtLivyvd7EeAjZo1hqaH3R4hstfc_TvFVkVZhtM3ILDpOV6t-pC0obadnpY7upK0vso8v8LaKwz8cMIreQeeyqvcq2ez8TQGlraTqPo6f_0Oc95tOFsiGQs3eXo93uiaeep1ZFs6rnAOBP6Sog_ho1-CTRW0zPb9NfjryxhIVL5kpl7gRQHfeRoLL7vuN5b4B37GMgPikAYpZhom01LlaFSn5KQgTaZZX70SShl891IPm1stDeEIt4n3Bv1U3YP9b-kcY0pl8MQeO7Zp4oPqE2d5X9nAMeb0xd1J6ykDdGVeOm_MEDKExhRshqS2yZHeGzkFF--Goq1f8iHMvAp9KbfRl3zn5j6dN42th-ArR47H0laQFXNFofjLfIjk-M7FxS0xNkiQPDP0CLFn9pjZmMCLBqKEEVnQWHlED5_dIOI0l0z0T1booy68cCjFsk5EvYRDOxLRyH20xvNtvt66eZS1RmJF8FUTwStpgw6bmyq_uZo-lzvAOBMJiBS8QYAL81VOTHjRIFdlNHEfyOpwvX3hwcTrNNDfDqD9hu9CB0Nqtvn17BpLJOlwZN7RZGGX4KXn-MAxoXrPeqkrQRM7vNzygQhP18250DGMG2-AVsuZyQ7N5ifKr75SbwUKVgVQOV6Ottpmu3v2GqziKuGSC-mCNxLRTFoxOsnrpdbCAC_G47Ehm-ZaRtDDUE7E831sQOTDDj_jgyC77wM4tApK-ifL_lG2LSGKdBy5ZdfRTsr7qi-iejVxz9ZNF5KSaUCx2McmNxpFRYSRGi9xfKigmd-oJ-Xbv6Np7sxWXsYPgTf61jWpsZsw9GkNwcPQLxNSqf9kT2Aq3vWaxl2LGMsmpBlFN0TnBKvakgGbfcvg-BplgDBPEoLUo-PNWpyVulSavvvQIhcxy6zM4JSPjgUU1BGljvzmyyO51EpXGnBlCO8ilPbSfU4o1qAy4E4v3Hsyz2rOaQh5q0Ow67FlX1ycxxQV_soZ9E-15dHk00tTXhGxSRNxg8OrxRZmIaWMXj0NvJ0XkBT5be9ljjSNPDqhfrd65415f1bCdAqaPuYd9m_Nb5_6k0hQjLfhruMhlCSwGSujNHb-HyZyYGK3RvdUrOqqa0Na8LYgNhwGldo4q6KBDuNUe_6jYaBG21vBTfHnfQR_QX-8HlJBKgZaT0vvkWdgnazdF2s-w4dbPiox-YsO1sku_0ltyZOUDieH2C7ADN0OjBnI64RsC7iM9JaygfjPUoilQkkUxVc9b6_OUYjCQrF7QmNRHFeamHRUth_K8v-dViV-hHkhEZX8qEnPx2Ft5qWtpNGBVwyTP1HyH5thmpzNYLRdN3vYCsuSVMJcK035TyaNl-tQ84PmPhPaCZLZrvFN68","searchStatistics":{"approximateTotalLogStreamCount":300,"completedLogStreamCount":18},"searchedLogStreams":[{"lastScannedEventTimestamp":1.512098260057E9,"logStreamName":"07e1cd7dca89a1678042477183b7ac3f","searchedCompletely":false}]}
2017-12-07 06:08:16,587 - MainThread - botocore.hooks - DEBUG - Event needs-retry.logs.FilterLogEvents: calling handler <botocore.retryhandler.RetryHandler object at 0x7f03013ff7d0>
2017-12-07 06:08:16,588 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2017-12-07 06:08:16,589 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 207, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 347, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 519, in __call__
    call_parameters, parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 640, in invoke
    self._display_response(operation_name, response, parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 660, in _display_response
    formatter(command_name, response)
  File "/usr/local/lib/python2.7/dist-packages/awscli/formatter.py", line 234, in __call__
    for page in response:
  File "/usr/local/lib/python2.7/dist-packages/botocore/paginate.py", line 301, in __iter__
    raise PaginationError(message=message)
PaginationError: Error during pagination: The same next token was received twice: {u'nextToken': u'zpUlahi1iz0r54spQh9r4VQzoXIQkGD23iR8pvetnUhp1_qLeuepXCOfNMhr9nAZ7TkvWroNd69mM1mf7jIEqrWckUgwsEy7JysAIxP86yFVN8gnDiFlUEg2b-nzoGguTNt_GW6xL5K7TsicMhb7aalB0JeZ5guTeSCn3mFfFvujo1p0aeAniFr1wCz56HjAsNwQqtUjg6OsGUccstGXlW2WVcmCN9RlJQKTTKX2nMmVCTw6OA3ZY6_Iq5ssGSy8QwwHHpxwDShsrGLDXH1AnIeSlfF-ngL8btiQzxiJDuUOXgPmRr9cE0p4M_6lcFFLhUSxJnZDORpUqkreOZaC2FkaKoiRes5UzPxGsqNwI5RBSyl4WVEjDZv_ohfqAOuCwrx2tosGhXaCga4yYIJGaaggTL-0yZQNpvkocPxiFV31pzOKRmSuqvY5vrOoCHQ9lD79n60tPx2hl2K7HpdLhbJ_qZDqm018svZZ124ijGuwLBz3U7Ray_pRKkRXq-Vm22kv8GvyZ2gNuOPcqyGl-xvdVjl36CDb5ERp_KJCRGLs9dlPisbdo7d_mhTCfeQxBavybGvPBTa1Nt-QdVGvzl51zhwsD_yzNusqxkIzsjglhkcKA9DZ4aripdsau0jTi2m_aW7NdXjz_J5jdz8ACZq6IegZTAjfu9O25QQ_EzdX64BG6bTjN80QB8U-RrAPEAlOWJAQhYF9nPc18e8F8o-6t6dbH3FAwi066LRnu9YvTxxHtTmpzbFPtGkxrGLuzRAPD6b4egbLhXtLivyvd7EeAjZo1hqaH3R4hstfc_TvFVkVZhtM3ILDpOV6t-pC0obadnpY7upK0vso8v8LaKwz8cMIreQeeyqvcq2ez8TQGlraTqPo6f_0Oc95tOFsiGQs3eXo93uiaeep1ZFs6rnAOBP6Sog_ho1-CTRW0zPb9NfjryxhIVL5kpl7gRQHfeRoLL7vuN5b4B37GMgPikAYpZhom01LlaFSn5KQgTaZZX70SShl891IPm1stDeEIt4n3Bv1U3YP9b-kcY0pl8MQeO7Zp4oPqE2d5X9nAMeb0xd1J6ykDdGVeOm_MEDKExhRshqS2yZHeGzkFF--Goq1f8iHMvAp9KbfRl3zn5j6dN42th-ArR47H0laQFXNFofjLfIjk-M7FxS0xNkiQPDP0CLFn9pjZmMCLBqKEEVnQWHlED5_dIOI0l0z0T1booy68cCjFsk5EvYRDOxLRyH20xvNtvt66eZS1RmJF8FUTwStpgw6bmyq_uZo-lzvAOBMJiBS8QYAL81VOTHjRIFdlNHEfyOpwvX3hwcTrNNDfDqD9hu9CB0Nqtvn17BpLJOlwZN7RZGGX4KXn-MAxoXrPeqkrQRM7vNzygQhP18250DGMG2-AVsuZyQ7N5ifKr75SbwUKVgVQOV6Ottpmu3v2GqziKuGSC-mCNxLRTFoxOsnrpdbCAC_G47Ehm-ZaRtDDUE7E831sQOTDDj_jgyC77wM4tApK-ifL_lG2LSGKdBy5ZdfRTsr7qi-iejVxz9ZNF5KSaUCx2McmNxpFRYSRGi9xfKigmd-oJ-Xbv6Np7sxWXsYPgTf61jWpsZsw9GkNwcPQLxNSqf9kT2Aq3vWaxl2LGMsmpBlFN0TnBKvakgGbfcvg-BplgDBPEoLUo-PNWpyVulSavvvQIhcxy6zM4JSPjgUU1BGljvzmyyO51EpXGnBlCO8ilPbSfU4o1qAy4E4v3Hsyz2rOaQh5q0Ow67FlX1ycxxQV_soZ9E-15dHk00tTXhGxSRNxg8OrxRZmIaWMXj0NvJ0XkBT5be9ljjSNPDqhfrd65415f1bCdAqaPuYd9m_Nb5_6k0hQjLfhruMhlCSwGSujNHb-HyZyYGK3RvdUrOqqa0Na8LYgNhwGldo4q6KBDuNUe_6jYaBG21vBTfHnfQR_QX-8HlJBKgZaT0vvkWdgnazdF2s-w4dbPiox-YsO1sku_0ltyZOUDieH2C7ADN0OjBnI64RsC7iM9JaygfjPUoilQkkUxVc9b6_OUYjCQrF7QmNRHFeamHRUth_K8v-dViV-hHkhEZX8qEnPx2Ft5qWtpNGBVwyTP1HyH5thmpzNYLRdN3vYCsuSVMJcK035TyaNl-tQ84PmPhPaCZLZrvFN68'}
2017-12-07 06:08:16,593 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Error during pagination: The same next token was received twice: {u'nextToken': u'zpUlahi1iz0r54spQh9r4VQzoXIQkGD23iR8pvetnUhp1_qLeuepXCOfNMhr9nAZ7TkvWroNd69mM1mf7jIEqrWckUgwsEy7JysAIxP86yFVN8gnDiFlUEg2b-nzoGguTNt_GW6xL5K7TsicMhb7aalB0JeZ5guTeSCn3mFfFvujo1p0aeAniFr1wCz56HjAsNwQqtUjg6OsGUccstGXlW2WVcmCN9RlJQKTTKX2nMmVCTw6OA3ZY6_Iq5ssGSy8QwwHHpxwDShsrGLDXH1AnIeSlfF-ngL8btiQzxiJDuUOXgPmRr9cE0p4M_6lcFFLhUSxJnZDORpUqkreOZaC2FkaKoiRes5UzPxGsqNwI5RBSyl4WVEjDZv_ohfqAOuCwrx2tosGhXaCga4yYIJGaaggTL-0yZQNpvkocPxiFV31pzOKRmSuqvY5vrOoCHQ9lD79n60tPx2hl2K7HpdLhbJ_qZDqm018svZZ124ijGuwLBz3U7Ray_pRKkRXq-Vm22kv8GvyZ2gNuOPcqyGl-xvdVjl36CDb5ERp_KJCRGLs9dlPisbdo7d_mhTCfeQxBavybGvPBTa1Nt-QdVGvzl51zhwsD_yzNusqxkIzsjglhkcKA9DZ4aripdsau0jTi2m_aW7NdXjz_J5jdz8ACZq6IegZTAjfu9O25QQ_EzdX64BG6bTjN80QB8U-RrAPEAlOWJAQhYF9nPc18e8F8o-6t6dbH3FAwi066LRnu9YvTxxHtTmpzbFPtGkxrGLuzRAPD6b4egbLhXtLivyvd7EeAjZo1hqaH3R4hstfc_TvFVkVZhtM3ILDpOV6t-pC0obadnpY7upK0vso8v8LaKwz8cMIreQeeyqvcq2ez8TQGlraTqPo6f_0Oc95tOFsiGQs3eXo93uiaeep1ZFs6rnAOBP6Sog_ho1-CTRW0zPb9NfjryxhIVL5kpl7gRQHfeRoLL7vuN5b4B37GMgPikAYpZhom01LlaFSn5KQgTaZZX70SShl891IPm1stDeEIt4n3Bv1U3YP9b-kcY0pl8MQeO7Zp4oPqE2d5X9nAMeb0xd1J6ykDdGVeOm_MEDKExhRshqS2yZHeGzkFF--Goq1f8iHMvAp9KbfRl3zn5j6dN42th-ArR47H0laQFXNFofjLfIjk-M7FxS0xNkiQPDP0CLFn9pjZmMCLBqKEEVnQWHlED5_dIOI0l0z0T1booy68cCjFsk5EvYRDOxLRyH20xvNtvt66eZS1RmJF8FUTwStpgw6bmyq_uZo-lzvAOBMJiBS8QYAL81VOTHjRIFdlNHEfyOpwvX3hwcTrNNDfDqD9hu9CB0Nqtvn17BpLJOlwZN7RZGGX4KXn-MAxoXrPeqkrQRM7vNzygQhP18250DGMG2-AVsuZyQ7N5ifKr75SbwUKVgVQOV6Ottpmu3v2GqziKuGSC-mCNxLRTFoxOsnrpdbCAC_G47Ehm-ZaRtDDUE7E831sQOTDDj_jgyC77wM4tApK-ifL_lG2LSGKdBy5ZdfRTsr7qi-iejVxz9ZNF5KSaUCx2McmNxpFRYSRGi9xfKigmd-oJ-Xbv6Np7sxWXsYPgTf61jWpsZsw9GkNwcPQLxNSqf9kT2Aq3vWaxl2LGMsmpBlFN0TnBKvakgGbfcvg-BplgDBPEoLUo-PNWpyVulSavvvQIhcxy6zM4JSPjgUU1BGljvzmyyO51EpXGnBlCO8ilPbSfU4o1qAy4E4v3Hsyz2rOaQh5q0Ow67FlX1ycxxQV_soZ9E-15dHk00tTXhGxSRNxg8OrxRZmIaWMXj0NvJ0XkBT5be9ljjSNPDqhfrd65415f1bCdAqaPuYd9m_Nb5_6k0hQjLfhruMhlCSwGSujNHb-HyZyYGK3RvdUrOqqa0Na8LYgNhwGldo4q6KBDuNUe_6jYaBG21vBTfHnfQR_QX-8HlJBKgZaT0vvkWdgnazdF2s-w4dbPiox-YsO1sku_0ltyZOUDieH2C7ADN0OjBnI64RsC7iM9JaygfjPUoilQkkUxVc9b6_OUYjCQrF7QmNRHFeamHRUth_K8v-dViV-hHkhEZX8qEnPx2Ft5qWtpNGBVwyTP1HyH5thmpzNYLRdN3vYCsuSVMJcK035TyaNl-tQ84PmPhPaCZLZrvFN68'}
```
I think this issue related to [this](https://github.com/aws/aws-cli/issues/1485)

Can you give me a hint how to resolve this? Thank you.

**Comment by nguyentienlong** [comment]
It's weird, I can not reproduce this issue from my end today.
I'll keep observing on this issue from my end.

**Comment by dstufft** [comment]
If I understand correctly, you're no longer able to reproduce this issue? If that's the case then there's unlikely going to be anything we can do on this issue unless we find a way to reproduce it.

**Comment by nguyentienlong** [comment]
yes, this issue can not reproduce from our side. I'll close this
