### ISSUE TITLE
aws configure fails with [Errno 13] Permission denied

### ISSUE THREAD

**Issue by ShaneMiller** [aws/aws-cli#3032]
I installed AWS CLI using the 64-bit MSI installer for Windows on 12/11/17. I'm trying to run the `aws configure` command (CMD window/**run as administrator**) for the initial setup, and am running into a permissions error. 

Below is the debug output of the command (credentials replaced with asterisks). Any ideas on how to resolve this problem would be appreciated.

```
C:\WINDOWS\system32>aws configure --debug
2017-12-08 19:07:37,513 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.14.7 Python/2.7.9 Windows/8 botocore/1.8.11
2017-12-08 19:07:37,513 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['configure', '--debug']
2017-12-08 19:07:37,513 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x0000000004350208>
2017-12-08 19:07:37,515 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-08 19:07:37,515 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x000000000397DAC8>
2017-12-08 19:07:37,515 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-08 19:07:37,515 - MainThread - botocore.session - DEBUG - Loading variable credentials_file from defaults.
2017-12-08 19:07:37,515 - MainThread - botocore.session - DEBUG - Loading variable config_file from defaults.
2017-12-08 19:07:37,515 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-08 19:07:37,516 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_timeout from defaults.
2017-12-08 19:07:37,516 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-08 19:07:37,516 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_num_attempts from defaults.
2017-12-08 19:07:37,516 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-08 19:07:37,516 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x00000000042213C8>
2017-12-08 19:07:37,516 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-08 19:07:37,516 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure: calling handler <function add_waiters at 0x0000000004358198>
2017-12-08 19:07:37,516 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.configure.anonymous: calling handler <function uri_param at 0x000000000391A438>
2017-12-08 19:07:37,516 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
AWS Access Key ID [None]: ********************
AWS Secret Access Key [None]: ****************************************
Default region name [None]: us-east-1
Default output format [None]: json
2017-12-08 19:07:59,470 - MainThread - botocore.session - DEBUG - Loading variable config_file from defaults.
2017-12-08 19:07:59,470 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-08 19:07:59,470 - MainThread - botocore.session - DEBUG - Loading variable credentials_file from defaults.
2017-12-08 19:07:59,471 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli\clidriver.pyc", line 207, in main
  File "awscli\customizations\commands.pyc", line 187, in __call__
  File "awscli\customizations\configure\configure.pyc", line 116, in _run_main
  File "awscli\customizations\configure\configure.pyc", line 141, in _write_out_creds_file_values
  File "awscli\customizations\configure\writer.pyc", line 56, in update_config
  File "awscli\customizations\configure\writer.pyc", line 76, in _create_file
OSError: [Errno 13] Permission denied: 'C:\\Users\\Shane/.aws/credentials'
2017-12-08 19:07:59,473 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

[Errno 13] Permission denied: 'C:\\Users\\Shane/.aws/credentials'
```

**Comment by dstufft** [comment]
Are you able to create a file in ``C:\Users\Shane/.aws`` from the run as administrator CMD?

**Comment by stealthycoin** [comment]
Closing due to inactivity.

**Comment by Mejato** [comment]
Just delete the credentials file and try again.

**Comment by ed3899** [comment]
> Just delete the credentials file and try again.

Worked like a charm
