### ISSUE TITLE
unknown encoding: cp65001

### ISSUE THREAD

**Issue by MrHaCkEr** [aws/aws-cli#3035]
Retrieving a string from DynamoDB that contain Unicode chars, requieres to change the codepage from cp850(ibm850) to cp65001(UTF-8) to prevent an encoding error.

But doing so results in `LookupError: unknown encoding: cp65001`.

Command used: `aws dynamodb scan --table-name NovelupdateInfo --region eu-west-1 --endpoint-url http://localhost:8000`

Windows 10

**Comment by dstufft** [comment]
How have you installed the CLI? If you're using Python 2.x then there is no ``cp65001`` encoding in the list of standard encodings and you'll need to use a different encoding (you can see the list of them at https://docs.python.org/2/library/codecs.html#standard-encodings) or you can upgrade to using Python 3.3+, which does have ``cp65001`` in its standard encodings.

**Comment by MrHaCkEr** [comment]
Yes I have the CLI installed and used Python 3.6.3.

**Comment by stealthycoin** [comment]
Did you try Donald's suggestion of using python 3 or using a different encoding?

**Comment by MrHaCkEr** [comment]
I did not try to use python. I used lambda to generate a new database on aws and used the web gui to get the info. Using a different encoding resulted in an encoding error if I recall correctly.

**Comment by JordonPhillips** [comment]
If you're using lambda, they offer python 3 these days. Unfortunately there's not anything we can do about the shortcomings of the older python versions.

**Comment by rrusson** [comment]
This is a problem I'm still suffering through. [SO has a smart workaround](https://stackoverflow.com/questions/39301253/can-i-force-aws-cli-to-use-utf-encoding) that may work for some (see answer and first comment), but since the CLI ships with Python 2.7 which doesn't have Unicode support (so I'm told), it hasn't fixed all my issues.

**Comment by joguSD** [comment]
We've recently started publishing MSIs with Python 3. You can get them [here](https://docs.aws.amazon.com/cli/latest/userguide/awscli-install-windows.html#python3-msis). Let me know if these help!

**Comment by joguSD** [comment]
Closing due to inactivity

**Comment by kyeonghopark** [comment]
This bug is still alive on Windows 10 64 bit with the latest version: `aws-cli/1.15.63 Python/2.7.9 Windows/8 botocore/1.10.62` .

A decent workaround here: https://stackoverflow.com/questions/39301253/can-i-force-aws-cli-to-use-utf-encoding#comment69929145_41344733 
* "... in the AWSCLI\encodings directory, copy utf_8.pyc to cp65001.pyc ..."

**Comment by kenorb** [comment]
Reinstalling [AWSCLI64 ](https://docs.aws.amazon.com/cli/latest/userguide/awscli-install-windows.html#python3-msis)and restarting terminal helped.

**Comment by kyeonghopark** [comment]
@kenorb 
Thank you for sharing the Python3 version of installer.

This version should replace the official version,
* here: https://aws.amazon.com/cli/ 
or, provided with it as an option at least.

**Comment by oliversalzburg** [comment]
Why even offer the broken version? I don't get it.

**Comment by elliot-nelson** [comment]
An update: the latest Windows installer (https://docs.aws.amazon.com/cli/latest/userguide/install-windows.html) has now corrected this problem.

The version I get from the latest installer is `aws-cli/1.16.169 Python/3.6.0 Windows/10 botocore/1.12.159`, and it no longer exhibits the crash when I upload a file with that encoding.

**Comment by marcoXbresciani** [comment]
Still present:

```
C:\Users\marco.bresciani>aws ssm get-parameter --name '/this/is/my/parameter/name' --with-decryption
Traceback (most recent call last):
  File "aws", line 27, in <module>
  File "aws", line 23, in main
  File "awscli\clidriver.pyc", line 69, in main
  File "awscli\clidriver.pyc", line 206, in main
  File "awscli\argparser.pyc", line 110, in parse_known_args
LookupError: unknown encoding: cp65001
```

Windows 10
```
C:\Users\marco.bresciani>aws --version
aws-cli/1.19.18 Python/2.7.18 Windows/10 botocore/1.20.18
```
I have Python 3.8.1 (64), Python 3.8.2 (32) and Python 3.9.1 (64) installed.

**Comment by marcoXbresciani** [comment]
AWSCLI2 is required.

**Comment by justinasfour04** [comment]
Is there a fix for this coming?
I have the issue still

**Comment by Fydon** [comment]
For anyone ending up here while looking for a solution to a similar problem with AWS CLI v2, see [this comment](https://github.com/aws/aws-cli/issues/4778#issuecomment-667439727).
