### ISSUE TITLE
InvalidAccessKeyId using instance profile role

### ISSUE THREAD

**Issue by felipe-vvoosh** [aws/aws-cli#3045]
Hi, I have a new instance with the newest amazon ami for eu-west-1 (ami-1a962263) and fully updated.

This instance has an instance profile role which has full access to 2 buckets.

When I try to sync those buckets with each other, after some time I get this message:
**fatal error: An error occurred (InvalidAccessKeyId) when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.**

I'm not using .aws/credentials as I'm using the instance role for everything, which ALWAYS worked.

Can someone help me please?

Thanks

**Comment by felipe-vvoosh** [comment]
aws-cli/1.11.132 Python/2.7.12 Linux/4.9.62-21.56.amzn1.x86_64 botocore/1.8.14

**Comment by joguSD** [comment]
Could you provide debug logs for the operation that's failing by adding `--debug`?

**Comment by stealthycoin** [comment]
Closing due to inactivity.

**Comment by felipe-vvoosh** [comment]
```2018-02-05 11:31:03,252 - MainThread - awscli.customizations.s3.results - DEBUG - Exception caught during command execution: An error occurred (InvalidAccessKeyId) when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/awscli/customizations/s3/s3handler.py", line 173, in call
    for fileinfo in fileinfos:
  File "/usr/lib/python2.7/dist-packages/awscli/customizations/s3/fileinfobuilder.py", line 31, in call
    for file_base in files:
  File "/usr/lib/python2.7/dist-packages/awscli/customizations/s3/comparator.py", line 79, in call
    src_file = advance_iterator(src_files)
  File "/usr/lib/python2.7/dist-packages/awscli/customizations/s3/filegenerator.py", line 142, in call
    for src_path, extra_information in file_iterator:
  File "/usr/lib/python2.7/dist-packages/awscli/customizations/s3/filegenerator.py", line 322, in list_objects
    page_size=self.page_size):
  File "/usr/lib/python2.7/dist-packages/awscli/customizations/s3/utils.py", line 367, in list_objects
    for page in pages:
  File "/usr/local/lib/python2.7/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 317, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 615, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.
fatal error: An error occurred (InvalidAccessKeyId) when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.
2018-02-05 11:31:03,253 - Thread-1 - awscli.customizations.s3.results - DEBUG - Shutdown request received in result processing thread, shutting down result thread.```

**Comment by felipe-vvoosh** [comment]
Can you, @stealthycoin, reopen this please?

**Comment by felipe-vvoosh** [comment]
I can list both buckets...

**Comment by felipe-vvoosh** [comment]
@joguSD ^^^

**Comment by felipe-vvoosh** [comment]
It seems I will be just ignored then... I will open a duplicate of this then.
