### ISSUE TITLE
aws cloudformation validate-template fails with ImportError: cannot import name 'JSONFileCache'

### ISSUE THREAD

**Issue by strus38** [aws/aws-cli#3082]
Hi

```
$ aws cloudformation validate-template --template-body file:///some.json --region eu-west-1
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/local/lib/python3.6/site-packages/awscli/clidriver.py", line 57, in main
    driver = create_clidriver()
  File "/usr/local/lib/python3.6/site-packages/awscli/clidriver.py", line 68, in create_clidriver
    event_hooks=emitter)
  File "/usr/local/lib/python3.6/site-packages/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/usr/local/lib/python3.6/site-packages/awscli/plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "/usr/local/lib/python3.6/site-packages/awscli/handlers.py", line 24, in <module>
    from awscli.customizations.assumerole import register_assume_role_provider
  File "/usr/local/lib/python3.6/site-packages/awscli/customizations/assumerole.py", line 5, in <module>
    from botocore.credentials import JSONFileCache
ImportError: cannot import name 'JSONFileCache'
```
Python3.6 is compiled from the source on an AWS Linux AMI, then pushed to the AWS ECR and run on ECS on an ECS AMI.... which I guess is the issue (Debian like build on top of RedHat like OS for the container)

```
$ pip3.6 freeze
alabaster==0.7.10
argcomplete==1.9.3
arghandler==1.2.0
astroid==1.6.0
attrs==17.4.0
awscli==1.14.23
Babel==2.5.1
boto==2.48.0
boto3==1.4.7
botocore==1.7.48
certifi==2017.11.5
chardet==3.0.4
colorama==0.3.7
docutils==0.14
idna==2.6
imagesize==0.7.1
isort==4.2.15
Jinja2==2.10
jmespath==0.9.3
lazy-object-proxy==1.3.1
MarkupSafe==1.0
mccabe==0.6.1
pluggy==0.6.0
py==1.5.2
pyasn1==0.4.2
Pygments==2.2.0
pylint==1.8.1
pytest==3.3.2
pytest-pylint==0.7.1
python-dateutil==2.6.1
pytz==2017.3
PyYAML==3.12
requests==2.18.4
rsa==3.4.2
s3transfer==0.1.12
six==1.11.0
snowballstemmer==1.2.1
Sphinx==1.6.6
sphinx-rtd-theme==0.2.4
sphinxcontrib-websupport==1.0.1
urllib3==1.22
wrapt==1.10.11
```

**Comment by strus38** [comment]
The botocore requirement was overwritten by some other software we use. Thus no more issue.
Thanks.
