### ISSUE TITLE
"ConnectionRefusedError: [Errno 61] Connection refused" --endpoint-url with s3  with zsh

### ISSUE THREAD

**Issue by s0c131y** [aws/aws-cli#3085]
When I run `aws s3api --endpoint-url https://xxx.com list-buckets` there' s no problems and succeeded to list all the buckets 
However when I run `aws s3 --endpoint-url http://xxx.com ls`in zsh, it comes out with error `('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))`

The detail is 
```➜  ~ aws s3 --endpoint-url http://xxx.com --debug ls
2018-01-16 17:51:31,867 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.14.24 Python/3.6.1 Darwin/16.7.0 botocore/1.8.28
2018-01-16 17:51:31,868 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3', '--endpoint-url', 'http://xxx.com', '--debug', 'ls']
2018-01-16 17:51:31,868 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x1040489d8>
2018-01-16 17:51:31,868 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-01-16 17:51:31,868 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x103b3f268>
2018-01-16 17:51:31,868 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-01-16 17:51:31,869 - MainThread - botocore.session - DEBUG - Loading variable credentials_file from defaults.
2018-01-16 17:51:31,869 - MainThread - botocore.session - DEBUG - Loading variable config_file from defaults.
2018-01-16 17:51:31,869 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-01-16 17:51:31,869 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_timeout from defaults.
2018-01-16 17:51:31,869 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-01-16 17:51:31,869 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_num_attempts from defaults.
2018-01-16 17:51:31,869 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-01-16 17:51:31,870 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x103f370d0>
2018-01-16 17:51:31,870 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-01-16 17:51:31,870 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3: calling handler <function add_waiters at 0x10404fbf8>
2018-01-16 17:51:31,871 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.s3.anonymous: calling handler <function uri_param at 0x103ad67b8>
2018-01-16 17:51:31,871 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ls: calling handler <function add_waiters at 0x10404fbf8>
2018-01-16 17:51:31,871 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.paths: calling handler <function uri_param at 0x103ad67b8>
2018-01-16 17:51:31,871 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.anonymous: calling handler <function uri_param at 0x103ad67b8>
2018-01-16 17:51:31,872 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.page-size: calling handler <function uri_param at 0x103ad67b8>
2018-01-16 17:51:31,872 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.human-readable: calling handler <function uri_param at 0x103ad67b8>
2018-01-16 17:51:31,872 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.ls: calling handler <awscli.argprocess.ParamShorthandParser object at 0x103b181d0>
2018-01-16 17:51:31,872 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.summarize: calling handler <function uri_param at 0x103ad67b8>
2018-01-16 17:51:31,872 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.ls: calling handler <awscli.argprocess.ParamShorthandParser object at 0x103b181d0>
2018-01-16 17:51:31,872 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.request-payer: calling handler <function uri_param at 0x103ad67b8>
2018-01-16 17:51:31,872 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-01-16 17:51:31,872 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-01-16 17:51:31,873 - MainThread - botocore.session - DEBUG - Loading variable region from config file with value 'us-east-1'.
2018-01-16 17:51:31,873 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-01-16 17:51:31,873 - MainThread - botocore.session - DEBUG - Loading variable ca_bundle from defaults.
2018-01-16 17:51:31,873 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-01-16 17:51:31,873 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2018-01-16 17:51:31,873 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2018-01-16 17:51:31,873 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2018-01-16 17:51:31,873 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2018-01-16 17:51:31,874 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2018-01-16 17:51:31,874 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/data/endpoints.json
2018-01-16 17:51:31,877 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-01-16 17:51:31,877 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x103697730>
2018-01-16 17:51:31,877 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/data/s3/2006-03-01/service-2.json
2018-01-16 17:51:31,886 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x10366f400>
2018-01-16 17:51:31,886 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x10366f1e0>
2018-01-16 17:51:31,887 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2018-01-16 17:51:31,899 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2018-01-16 17:51:31,900 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2018-01-16 17:51:31,901 - MainThread - botocore.client - DEBUG - Using S3 path style addressing.
2018-01-16 17:51:31,901 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListBuckets: calling handler <function validate_bucket_name at 0x1036acea0>
2018-01-16 17:51:31,901 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListBuckets: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x1043e0048>>
2018-01-16 17:51:31,901 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListBuckets: calling handler <function generate_idempotent_uuid at 0x1036acae8>
2018-01-16 17:51:31,901 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.ListBuckets: calling handler <function add_expect_header at 0x1036ae400>
2018-01-16 17:51:31,901 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.ListBuckets: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x1043e0048>>
2018-01-16 17:51:31,954 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=ListBuckets) (verify_ssl=True) with params: {'url_path': '/', 'query_string': '', 'method': 'GET', 'headers': {'User-Agent': 'aws-cli/1.14.24 Python/3.6.1 Darwin/16.7.0 botocore/1.8.28'}, 'body': b'', 'url': 'http://xxx.com/', 'context': {'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x104395898>, 'has_streaming_input': False, 'auth_type': None, 'signing': {'bucket': None}}}
2018-01-16 17:51:31,955 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.ListBuckets: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x1043957b8>>
2018-01-16 17:51:31,955 - MainThread - botocore.hooks - DEBUG - Event choose-signer.s3.ListBuckets: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x1041089b0>>
2018-01-16 17:51:31,955 - MainThread - botocore.hooks - DEBUG - Event choose-signer.s3.ListBuckets: calling handler <function set_operation_specific_signer at 0x1036ac9d8>
2018-01-16 17:51:31,956 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2018-01-16 17:51:31,956 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
GET
/

host:xxx.com
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20180116T085131Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2018-01-16 17:51:31,956 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20180116T085131Z
20180116/us-east-1/s3/aws4_request
ebf54bbb4184d6a2907a75d597eb61affa3c57eb3a9e2f578c4298abdbc14b39
2018-01-16 17:51:31,956 - MainThread - botocore.auth - DEBUG - Signature:
456f5f93be4312b2ef44f64a32cb6621cc097a93cfd8f4ea4e0be22218afb212
2018-01-16 17:51:31,958 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [GET]>
2018-01-16 17:51:31,959 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): xxx.com
2018-01-16 17:51:55,946 - MainThread - botocore.endpoint - DEBUG - ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/awsrequest.py", line 130, in _send_request
    self, method, url, body, headers, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/awsrequest.py", line 157, in _send_output
    self.send(msg)
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/awsrequest.py", line 242, in send
    return HTTPConnection.send(self, str)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/packages/urllib3/packages/six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/awsrequest.py", line 130, in _send_request
    self, method, url, body, headers, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/awsrequest.py", line 157, in _send_output
    self.send(msg)
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/awsrequest.py", line 242, in send
    return HTTPConnection.send(self, str)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
botocore.vendored.requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/endpoint.py", line 213, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
botocore.vendored.requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))
2018-01-16 17:51:55,949 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListBuckets: calling handler <botocore.retryhandler.RetryHandler object at 0x104395d30>
2018-01-16 17:51:55,949 - MainThread - botocore.retryhandler - DEBUG - retry needed, retryable exception caught: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))
Traceback (most recent call last):
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/awsrequest.py", line 130, in _send_request
    self, method, url, body, headers, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/awsrequest.py", line 157, in _send_output
    self.send(msg)
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/awsrequest.py", line 242, in send
    return HTTPConnection.send(self, str)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/Users/toshiki.inami/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
```

**Comment by stealthycoin** [comment]
Is this an aws endpoint you are hitting? If it isn't there isn't much we can do here, the remote host is refusing the connection.

**Comment by joguSD** [comment]
Closing due to inactivity.

**Comment by brando90** [comment]
was a soln found?

**Comment by brando90** [comment]
was a soln found?
