### ISSUE TITLE
aws rds create-db-instance UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 25: ordinal not in range(128)

### ISSUE THREAD

**Issue by coreygans** [aws/aws-cli#3089]
Trying to create a db from command line, which worked a week ago, but now getting the following:

```
$ aws rds create-db-instance --db-name staging --db-instance-class db.t2.small --db-instance-identifier stagingdb --allocated-storage 30 --engine mysql --master-username dbuser --master-user-password supersecretpw --multi-az --storage-type gp2 --no-publicly-accessible --storage-encrypted --vpc-security-group-ids sg-2281d257 --backup-retention-period 15
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/Users/coreyganser/Library/Python/2.7/lib/python/site-packages/awscli/clidriver.py", line 58, in main
    rc = driver.main()
  File "/Users/coreyganser/Library/Python/2.7/lib/python/site-packages/awscli/clidriver.py", line 196, in main
    parsed_args, remaining = parser.parse_known_args(args)
  File "/Users/coreyganser/Library/Python/2.7/lib/python/site-packages/awscli/argparser.py", line 91, in parse_known_args
    parsed, remaining = super(CLIArgParser, self).parse_known_args(args, namespace)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1774, in _parse_known_args
    option_tuple = self._parse_optional(arg_string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 2082, in _parse_optional
    option_tuples = self._get_option_tuples(arg_string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 2125, in _get_option_tuples
    if option_string.startswith(option_prefix):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 25: ordinal not in range(128)
```

Version: aws-cli/1.14.27 Python/2.7.10 Darwin/17.3.0 botocore/1.8.31 
MacOS 10.13.1 and 10.13.2 (tested before and after upgrade)

Used the command above exactly as it is. Made sure I scrubbed it so it isn't sensitive.  Appreciate help if this isn't a bug.

**Comment by coreygans** [comment]
There must have been a hidden character. I rewrote the command and it worked.
