### ISSUE TITLE
ModuleNotFound Error: no module named 'botocore.vendored'

### ISSUE THREAD

**Issue by meganpetroski** [aws/aws-cli#3092]
Using Python3.6 on Windows 10, I installed `awscli` using the following command:

`pip install --upgrade boto3 awscli`

It seems to install successfully, and then whenever I try to run any AWS cli command, I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\me013pe\AppData\Local\Programs\Python\Python36-32\Scripts\aws.cmd", line 50, in <module>
    import awscli.clidriver
  File "C:\Users\me013pe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\awscli\clidriver.py", line 17, in <module>
    import botocore.session
  File "C:\Users\me013pe\AppData\Roaming\Python\Python36\site-packages\botocore\session.py", line 25, in <module>
    import botocore.configloader
  File "C:\Users\me013pe\AppData\Roaming\Python\Python36\site-packages\botocore\configloader.py", line 19, in <module>
    from botocore.compat import six
  File "C:\Users\me013pe\AppData\Roaming\Python\Python36\site-packages\botocore\compat.py", line 24, in <module>
    from botocore.vendored import six
ModuleNotFoundError: No module named 'botocore.vendored'
```

**Comment by dstufft** [comment]
What version of botocore do you have installed? Can you run ``pip check`` and see if it reports any issues?

**Comment by joguSD** [comment]
Closing due to inactivity.

**Comment by neoacevedo** [comment]
Good, I have installed aws-cli in openSUSE Tumbleweed, but suddenly I got the same issue.

**Comment by mpapis** [comment]
seeing the same error on OpenSUSE with botocore `1.10.4` and python `3.6` ,could you reopen?

**Comment by rombert** [comment]
Same problem here (openSUSE TW). The complete output is 

```/usr/lib/python3.6/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.16) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/lib/python3.6/site-packages/awscli/clidriver.py", line 35, in <module>
    from awscli.help import ProviderHelpCommand
  File "/usr/lib/python3.6/site-packages/awscli/help.py", line 27, in <module>
    from awscli.clidocs import ProviderDocumentEventHandler
  File "/usr/lib/python3.6/site-packages/awscli/clidocs.py", line 21, in <module>
    from awscli.argprocess import ParamShorthandDocGen
  File "/usr/lib/python3.6/site-packages/awscli/argprocess.py", line 21, in <module>
    from awscli.paramfile import get_paramfile, ResourceLoadingError
  File "/usr/lib/python3.6/site-packages/awscli/paramfile.py", line 16, in <module>
    from botocore.vendored import requests
ModuleNotFoundError: No module named 'botocore.vendored'```

**Comment by mdunc** [comment]
Same.  Installed aws-cli on Tumbleweed today and get the same error.  @dstufft @joguSD

**Comment by rombert** [comment]
For the Tumbleweed problem please see https://bugzilla.opensuse.org/show_bug.cgi?id=1092493

**Comment by eromoe** [comment]
OK, the problem is first time install with --user . It install to windows user folder,  I stop the installation and reinstall without --user cause this error.

**Comment by Dmitry1987** [comment]
same happens for me with python3 (3.6.7-1~18.04)
```
python3-botocore (1.8.48+repack-1) ...
python3-s3transfer (0.1.13-1) ...
awscli (1.14.44-1ubuntu1) ...
```

**Comment by terorie** [comment]
Seems to happen if you both have `apt install python3-botocore` and `pip3 install botocore`.

**Comment by KaiserKkaiser** [comment]
Same problem.
```
Python 3.8.5
python3-botocore: 1.16.19+repack-1ubuntu0.20.04.1
awscli: 1.18.208
```

**Comment by holisticode** [comment]
`sudo apt remove python3-botocore` then `pip3 install botocore` fixed it for me

**Comment by skilfoy** [comment]
> In my case, it works for me.
> 
> `sudo apt remove python3-botocore` `pip3 uninstall botocore` `sudo apt install python3-botocore` `sudo apt install awscli` `pip install --upgrade boto3 awscli`

This worked for me! Thank you
