### ISSUE TITLE
Not able to add application reference data source from cli for AWS Kinesis Analytics

### ISSUE THREAD

**Issue by Rishi74744** [aws/aws-cli#3103]
I am using following command to add application reference data -

aws kinesisanalytics add-application-reference-data-source  --endpoint https://kinesisanalytics.us-east-1.amazonaws.com --region us-east-1 --application-name alerts --reference-data-source '{"TableName":"DeviceData","S3ReferenceDataSource":{"BucketARN":"arn: aws: s3: : : bucket-name","FileKey":"device.csv","ReferenceRoleARN":"arn: aws: iam: : account-id: role/role-name"},"ReferenceSchema":{"RecordFormat":{"RecordFormatType":"CSV","MappingParameters":{"CSVMappingParameters":{"RecordRowDelimiter":"\n","RecordColumnDelimiter":", "}}},"RecordEncoding":"UTF-8","RecordColumns":[{"Name":"key1","SqlType":"VARCHAR(64)"},{"Name":"key2","SqlType":"VARCHAR(64)"}]}}' --current-application-version-id 2

But it always give following error -

Error parsing parameter '--reference-data-source': Expected: '=', received: ''' for input:
'{TableName:DeviceData,S3ReferenceDataSource:{BucketARN:arn: aws: s3: : : bucket-name,FileKey:device.csv,ReferenceRoleARN:arn: aws: iam: : account-id: role/role-name},ReferenceSchema:{RecordFormat:{RecordFormatType:CSV,MappingParameters:{CSVMappingParameters:{RecordRowDelimiter:\n,RecordColumnDelimiter:, }}},RecordEncoding:UTF-8,RecordColumns:[{Name:key1,SqlType:VARCHAR(64)},{Name:key2,SqlType:VARCHAR(64)}]}}'

**Comment by joguSD** [comment]
Can you provide debug logs for this by adding `--debug`? Copying and pasting this command I wasn't able to reproduce the issue.

**Comment by Rishi74744** [comment]
2018-01-30 21:09:07,453 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.11.147 Python/2.7.9 Windows/8 botocore/1.7.5
2018-01-30 21:09:07,453 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['kinesisanalytics', 'add-application-reference-data-source', '--endpoint', 'https://kinesisanalytics.us-east-1.amazonaws.com', '--region', 'us-east-1', '--application-name', 'alerts', '--debug', '--reference-data-source', "'{TableName:DeviceData,S3ReferenceDataSource:{BucketARN:arn: aws: s3: : : bucket-name,FileKey:device.csv,ReferenceRoleARN:arn: aws: iam: : account-id: role/role-name},ReferenceSchema:{RecordFormat:{RecordFormatType:CSV,MappingParameters:{CSVMappingParameters:{RecordRowDelimiter:\\n,RecordColumnDelimiter:, }}},RecordEncoding:UTF-8,RecordColumns:[{Name:key1,SqlType:VARCHAR(64)},{Name:key2,SqlType:VARCHAR(64)}]}}'", '--current-application-version-id', '2']
2018-01-30 21:09:07,454 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x0000000006104A58>
2018-01-30 21:09:07,456 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x0000000005DDFDD8>
2018-01-30 21:09:07,482 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLI\botocore\data\kinesisanalytics\2015-08-14\service-2.json
2018-01-30 21:09:07,507 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.kinesisanalytics: calling handler <function register_retries_for_service at 0x00000000055FA048>
2018-01-30 21:09:07,510 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: kinesisanalytics
2018-01-30 21:09:07,515 - MainThread - botocore.hooks - DEBUG - Event building-command-table.kinesisanalytics: calling handler <function add_waiters at 0x000000000610A9E8>
2018-01-30 21:09:07,582 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'application-name', <awscli.arguments.CLIArgument object at 0x00000000065CD828>), (u'current-application-version-id', <awscli.arguments.CLIArgument object at 0x00000000065CD860>), (u'reference-data-source', <awscli.arguments.CLIArgument object at 0x00000000065CD898>)])
2018-01-30 21:09:07,594 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.kinesisanalytics.add-application-reference-data-source: calling handler <function add_streaming_output_arg at 0x0000000006104F28>
2018-01-30 21:09:07,595 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.kinesisanalytics.add-application-reference-data-source: calling handler <function add_cli_input_json at 0x0000000005DE6AC8>
2018-01-30 21:09:07,598 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.kinesisanalytics.add-application-reference-data-source: calling handler <function unify_paging_params at 0x0000000006031E48>
2018-01-30 21:09:07,667 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLI\botocore\data\kinesisanalytics\2015-08-14\paginators-1.json
2018-01-30 21:09:07,671 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.kinesisanalytics.add-application-reference-data-source: calling handler <function add_generate_skeleton at 0x000000000602C588>
2018-01-30 21:09:07,671 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.kinesisanalytics.add-application-reference-data-source: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x00000000065CD908>>
2018-01-30 21:09:07,674 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.kinesisanalytics.add-application-reference-data-source: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x00000000065CDB00>>
2018-01-30 21:09:07,677 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.kinesisanalytics.add-application-reference-data-source.application-name: calling handler <function uri_param at 0x000000000588C908>
2018-01-30 21:09:07,681 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.kinesisanalytics.add-application-reference-data-source: calling handler <awscli.argprocess.ParamShorthandParser object at 0x0000000005DC4630>
2018-01-30 21:09:07,686 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'alerts' for parameter "application_name": u'alerts'
2018-01-30 21:09:07,687 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.kinesisanalytics.add-application-reference-data-source.current-application-version-id: calling handler <function uri_param at 0x000000000588C908>
2018-01-30 21:09:07,690 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.kinesisanalytics.add-application-reference-data-source: calling handler <awscli.argprocess.ParamShorthandParser object at 0x0000000005DC4630>
2018-01-30 21:09:07,696 - MainThread - awscli.arguments - DEBUG - Unpacked value of 2 for parameter "current_application_version_id": 2
2018-01-30 21:09:07,700 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.kinesisanalytics.add-application-reference-data-source.reference-data-source: calling handler <function uri_param at 0x000000000588C908>
2018-01-30 21:09:07,701 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.kinesisanalytics.add-application-reference-data-source: calling handler <awscli.argprocess.ParamShorthandParser object at 0x0000000005DC4630>
2018-01-30 21:09:07,703 - MainThread - awscli.argprocess - DEBUG - Parsing param --reference-data-source as shorthand
2018-01-30 21:09:07,713 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli\clidriver.pyc", line 200, in main
  File "awscli\clidriver.pyc", line 338, in __call__
  File "awscli\clidriver.pyc", line 479, in __call__
  File "awscli\clidriver.pyc", line 535, in _build_call_parameters
  File "awscli\arguments.pyc", line 453, in add_to_params
  File "awscli\arguments.pyc", line 463, in _unpack_argument
  File "awscli\arguments.pyc", line 476, in _emit_first_response
  File "awscli\arguments.pyc", line 473, in _emit
  File "botocore\hooks.pyc", line 227, in emit
  File "botocore\hooks.pyc", line 210, in _emit
  File "awscli\argprocess.pyc", line 337, in __call__
  File "awscli\argprocess.pyc", line 361, in _parse_as_shorthand
ParamError: Error parsing parameter '--reference-data-source': Expected: '=', received: ''' for input:
'{TableName:DeviceData,S3ReferenceDataSource:{BucketARN:arn: aws: s3: : : bucket-name,FileKey:device.csv,ReferenceRoleARN:arn: aws: iam: : account-id: role/role-name},ReferenceSchema:{RecordFormat:{RecordFormatType:CSV,MappingParameters:{CSVMappingParameters:{RecordRowDelimiter:\n,RecordColumnDelimiter:, }}},RecordEncoding:UTF-8,RecordColumns:[{Name:key1,SqlType:VARCHAR(64)},{Name:key2,SqlType:VARCHAR(64)}]}}'
^
2018-01-30 21:09:07,713 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Error parsing parameter '--reference-data-source': Expected: '=', received: ''' for input:
'{TableName:DeviceData,S3ReferenceDataSource:{BucketARN:arn: aws: s3: : : bucket-name,FileKey:device.csv,ReferenceRoleARN:arn: aws: iam: : account-id: role/role-name},ReferenceSchema:{RecordFormat:{RecordFormatType:CSV,MappingParameters:{CSVMappingParameters:{RecordRowDelimiter:\n,RecordColumnDelimiter:, }}},RecordEncoding:UTF-8,RecordColumns:[{Name:key1,SqlType:VARCHAR(64)},{Name:key2,SqlType:VARCHAR(64)}]}}'

**Comment by joguSD** [comment]
Ah you're on Windows. Quoting rules for the command line on windows are different, and passing JSON can be fairly unwieldy. I would suggest using the `--cli-input-json` parameter and writing the input as a json file like so:

`input.json`:
```
{
"ApplicationName": "alerts",
"CurrentApplicationVersionId": 2,
"ReferenceDataSource": {"TableName":"DeviceData","S3ReferenceDataSource":{"BucketARN":"arn:aws:s3:::bucket-name","FileKey":"device.csv","ReferenceRoleARN":"arn:aws:iam::account-id:role/role-name"},"ReferenceSchema":{"RecordFormat":{"RecordFormatType":"CSV","MappingParameters":{"CSVMappingParameters":{"RecordRowDelimiter":"\n","RecordColumnDelimiter":", "}}},"RecordEncoding":"UTF-8","RecordColumns":[{"Name":"key1","SqlType":"VARCHAR(64)"},{"Name":"key2","SqlType":"VARCHAR(64)"}]}}
}
```

And give this file as input like so:
```
aws kinesisanalytics add-application-reference-data-source --endpoint https://kinesisanalytics.us-east-1.amazonaws.com --region us-east-1 --cli-input-json file://input.json
```

Let me know if that works for you!

**Comment by Rishi74744** [comment]
I got it to work as -

aws kinesisanalytics add-application-reference-data-source --endpoint https://kinesisanalytics.us-east-1.amazonaws.com --region us-east-1 --application-name alerts --reference-data-source "{\"TableName\":\"DeviceData\",\"S3ReferenceDataSource\":{\"BucketARN\":\"arn: aws: s3: : : bucket-name\",\"FileKey\":\"device.csv\",\"ReferenceRoleARN\":\"arn: aws: iam: : account-id: role/role-name\"},\"ReferenceSchema\":{\"RecordFormat\":{\"RecordFormatType\":\"CSV\",\"MappingParameters\":{\"CSVMappingParameters\":{\"RecordRowDelimiter\":\"\n\",\"RecordColumnDelimiter\":\", \"}}},\"RecordEncoding\":\"UTF-8\",\"RecordColumns\":[{\"Name\":\"key1\",\"SqlType\":\"VARCHAR(64)\"},{\"Name\":\"key2\",\"SqlType\":\"VARCHAR(64)\"}]}}" --current-application-version-id 2

But this should be mentioned in the documentation.

**Comment by joguSD** [comment]
Glad you got this working. Closing out the issue.
