### ISSUE TITLE
`codec can't decode byte` issues on all s3 commands

### ISSUE THREAD

**Issue by rgoldiez** [aws/aws-cli#3119]
I'm stumped by this issue... I'm getting the following errors (the first is a simple `aws s3 ls` and the second is `aws s3 help`) only around the s3 service.  Any help is greatly appreciated!

```
pi@hireboticspi:~ $ aws --debug s3 ls
2018-02-01 14:26:18,816 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.11.112 Python/2.7.9 Linux/4.4.50-v7+ botocore/1.5.75
2018-02-01 14:26:18,817 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', 's3', 'ls']
2018-02-01 14:26:18,818 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x75f690f0>
2018-02-01 14:26:18,818 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7626e030>
2018-02-01 14:26:18,821 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3: calling handler <function add_waiters at 0x75f69ab0>
2018-02-01 14:26:18,824 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.s3.anonymous: calling handler <function uri_param at 0x762a9930>
2018-02-01 14:26:18,825 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ls: calling handler <function add_waiters at 0x75f69ab0>
2018-02-01 14:26:18,828 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.paths: calling handler <function uri_param at 0x762a9930>
2018-02-01 14:26:18,829 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.human-readable: calling handler <function uri_param at 0x762a9930>
2018-02-01 14:26:18,830 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.ls: calling handler <awscli.argprocess.ParamShorthandParser object at 0x762bbb90>
2018-02-01 14:26:18,830 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.page-size: calling handler <function uri_param at 0x762a9930>
2018-02-01 14:26:18,831 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.anonymous: calling handler <function uri_param at 0x762a9930>
2018-02-01 14:26:18,831 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.request-payer: calling handler <function uri_param at 0x762a9930>
2018-02-01 14:26:18,832 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.summarize: calling handler <function uri_param at 0x762a9930>
2018-02-01 14:26:18,832 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.ls: calling handler <awscli.argprocess.ParamShorthandParser object at 0x762bbb90>
2018-02-01 14:26:18,833 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2018-02-01 14:26:18,833 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2018-02-01 14:26:18,834 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2018-02-01 14:26:18,835 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2018-02-01 14:26:18,837 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /home/pi/.local/lib/python2.7/site-packages/botocore/data/endpoints.json
2018-02-01 14:26:18,927 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/home/pi/.local/lib/python2.7/site-packages/awscli/clidriver.py", line 200, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/home/pi/.local/lib/python2.7/site-packages/awscli/customizations/commands.py", line 190, in __call__
    parsed_globals)
  File "/home/pi/.local/lib/python2.7/site-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/home/pi/.local/lib/python2.7/site-packages/awscli/customizations/s3/subcommands.py", line 455, in _run_main
    super(ListCommand, self)._run_main(parsed_args, parsed_globals)
  File "/home/pi/.local/lib/python2.7/site-packages/awscli/customizations/s3/subcommands.py", line 441, in _run_main
    parsed_globals.verify_ssl)
  File "/home/pi/.local/lib/python2.7/site-packages/awscli/customizations/s3/subcommands.py", line 434, in get_client
    config=config)
  File "/home/pi/.local/lib/python2.7/site-packages/botocore/session.py", line 836, in create_client
    client_config=config, api_version=api_version)
  File "/home/pi/.local/lib/python2.7/site-packages/botocore/client.py", line 64, in create_client
    service_model = self._load_service_model(service_name, api_version)
  File "/home/pi/.local/lib/python2.7/site-packages/botocore/client.py", line 96, in _load_service_model
    api_version=api_version)
  File "/home/pi/.local/lib/python2.7/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/botocore/loaders.py", line 383, in load_service_model
    model = self.load_data(full_path)
  File "/home/pi/.local/lib/python2.7/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/botocore/loaders.py", line 420, in load_data
    found = self.file_loader.load_file(possible_path)
  File "/home/pi/.local/lib/python2.7/site-packages/botocore/loaders.py", line 173, in load_file
    payload = fp.read().decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfb in position 38916: invalid start byte
2018-02-01 14:26:18,933 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

'utf8' codec can't decode byte 0xfb in position 38916: invalid start byte
```

```
pi@hireboticspi:~ $ aws --debug s3 help
2018-02-01 14:27:23,797 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.11.112 Python/2.7.9 Linux/4.4.50-v7+ botocore/1.5.75
2018-02-01 14:27:23,798 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', 's3', 'help']
2018-02-01 14:27:23,798 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x75fe30f0>
2018-02-01 14:27:23,798 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x762e8030>
2018-02-01 14:27:23,801 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3: calling handler <function add_waiters at 0x75fe3ab0>
2018-02-01 14:27:23,804 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.s3.anonymous: calling handler <function uri_param at 0x76323930>
2018-02-01 14:27:23,806 - MainThread - botocore.hooks - DEBUG - Event doc-breadcrumbs.s3: calling handler <bound method BasicDocHandler.doc_breadcrumbs of <awscli.customizations.commands.BasicDocHandler object at 0x75f8d370>>
2018-02-01 14:27:23,807 - MainThread - botocore.hooks - DEBUG - Event doc-title.s3: calling handler <bound method BasicDocHandler.doc_title of <awscli.customizations.commands.BasicDocHandler object at 0x75f8d370>>
2018-02-01 14:27:23,807 - MainThread - botocore.hooks - DEBUG - Event doc-description.s3: calling handler <bound method BasicDocHandler.doc_description of <awscli.customizations.commands.BasicDocHandler object at 0x75f8d370>>
2018-02-01 14:27:23,808 - MainThread - botocore.hooks - DEBUG - Event doc-description.s3: calling handler <function add_paging_description at 0x7619a1f0>
2018-02-01 14:27:23,809 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-start.s3: calling handler <bound method BasicDocHandler.doc_synopsis_start of <awscli.customizations.commands.BasicDocHandler object at 0x75f8d370>>
2018-02-01 14:27:23,809 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-end.s3: calling handler <bound method BasicDocHandler.doc_synopsis_end of <awscli.customizations.commands.BasicDocHandler object at 0x75f8d370>>
2018-02-01 14:27:23,810 - MainThread - botocore.hooks - DEBUG - Event doc-options-start.s3: calling handler <bound method BasicDocHandler.doc_options_start of <awscli.customizations.commands.BasicDocHandler object at 0x75f8d370>>
2018-02-01 14:27:23,811 - MainThread - botocore.hooks - DEBUG - Event doc-subitems-start.s3: calling handler <bound method BasicDocHandler.doc_subitems_start of <awscli.customizations.commands.BasicDocHandler object at 0x75f8d370>>
2018-02-01 14:27:23,811 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.s3.cp: calling handler <bound method BasicDocHandler.doc_subitem of <awscli.customizations.commands.BasicDocHandler object at 0x75f8d370>>
2018-02-01 14:27:23,812 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.s3.ls: calling handler <bound method BasicDocHandler.doc_subitem of <awscli.customizations.commands.BasicDocHandler object at 0x75f8d370>>
2018-02-01 14:27:23,813 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.s3.mb: calling handler <bound method BasicDocHandler.doc_subitem of <awscli.customizations.commands.BasicDocHandler object at 0x75f8d370>>
2018-02-01 14:27:23,813 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.s3.mv: calling handler <bound method BasicDocHandler.doc_subitem of <awscli.customizations.commands.BasicDocHandler object at 0x75f8d370>>
2018-02-01 14:27:23,814 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.s3.presign: calling handler <bound method BasicDocHandler.doc_subitem of <awscli.customizations.commands.BasicDocHandler object at 0x75f8d370>>
2018-02-01 14:27:23,814 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.s3.rb: calling handler <bound method BasicDocHandler.doc_subitem of <awscli.customizations.commands.BasicDocHandler object at 0x75f8d370>>
2018-02-01 14:27:23,815 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.s3.rm: calling handler <bound method BasicDocHandler.doc_subitem of <awscli.customizations.commands.BasicDocHandler object at 0x75f8d370>>
2018-02-01 14:27:23,815 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.s3.sync: calling handler <bound method BasicDocHandler.doc_subitem of <awscli.customizations.commands.BasicDocHandler object at 0x75f8d370>>
2018-02-01 14:27:23,816 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.s3.website: calling handler <bound method BasicDocHandler.doc_subitem of <awscli.customizations.commands.BasicDocHandler object at 0x75f8d370>>
2018-02-01 14:27:23,816 - MainThread - botocore.hooks - DEBUG - Event doc-subitems-end.s3: calling handler <bound method BasicDocHandler.doc_subitems_end of <awscli.customizations.commands.BasicDocHandler object at 0x75f8d370>>
2018-02-01 14:27:23,817 - MainThread - botocore.hooks - DEBUG - Event doc-examples.s3: calling handler <bound method BasicDocHandler.doc_examples of <awscli.customizations.commands.BasicDocHandler object at 0x75f8d370>>
2018-02-01 14:27:23,817 - MainThread - botocore.hooks - DEBUG - Event doc-output.s3: calling handler <bound method BasicDocHandler.doc_output of <awscli.customizations.commands.BasicDocHandler object at 0x75f8d370>>
2018-02-01 14:27:23,817 - MainThread - botocore.hooks - DEBUG - Event doc-relateditems-start.s3: calling handler <bound method BasicDocHandler.doc_relateditems_start of <awscli.customizations.commands.BasicDocHandler object at 0x75f8d370>>
2018-02-01 14:27:23,818 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/home/pi/.local/lib/python2.7/site-packages/awscli/clidriver.py", line 200, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/home/pi/.local/lib/python2.7/site-packages/awscli/customizations/commands.py", line 181, in __call__
    self._display_help(parsed_args, parsed_globals)
  File "/home/pi/.local/lib/python2.7/site-packages/awscli/customizations/commands.py", line 227, in _display_help
    help_command(parsed_args, parsed_globals)
  File "/home/pi/.local/lib/python2.7/site-packages/awscli/customizations/commands.py", line 359, in __call__
    self.renderer.render(self.doc.getvalue())
  File "/home/pi/.local/lib/python2.7/site-packages/botocore/docs/bcdoc/restdoc.py", line 78, in getvalue
    return ''.join(self._writes).encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa0 in position 4182: ordinal not in range(128)
2018-02-01 14:27:23,820 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

'ascii' codec can't decode byte 0xa0 in position 4182: ordinal not in range(128)
```

**Comment by rgoldiez** [comment]
Seems that the services-2.json file got corrupted with non-ascii characters.  I was able to copy a version from another machine and get this going again. 🤷‍♂️

**Comment by rsshilli** [comment]
I had the same problem here, just now. I downloaded the latest AWS CLI from [here](https://aws.amazon.com/cli/) and then installed overtop of my existing AWS CLI2 install and it seemed to fix it.
