### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte...  --registry-ids using in aws ecr

### ISSUE THREAD

**Issue by applerom** [aws/aws-cli#3124]
I am trying to pull ecr-image from my other AWS account:

`/home/ec2-user # aws ecr get-login –-registry-ids 111111111 --region us-east-1`

> Traceback (most recent call last):
>   File "/bin/aws", line 27, in <module>
>     sys.exit(main())
>   File "/bin/aws", line 23, in main
>     return awscli.clidriver.main()
>   File "/usr/local/aws/lib/python2.7/site-packages/awscli/clidriver.py", line 59, in main
>     rc = driver.main()
>   File "/usr/local/aws/lib/python2.7/site-packages/awscli/clidriver.py", line 233, in main
>     write_exception(e, outfile=get_stderr_text_writer())
>   File "/usr/local/aws/lib/python2.7/site-packages/awscli/utils.py", line 194, in write_exception
>     outfile.write(six.text_type(ex))
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 17: ordinal not in range(128)

`/home/ec2-user # aws --version`

> aws-cli/1.14.32 Python/2.7.5 Linux/4.9.76-38.79.amzn2.x86_64 botocore/1.8.36

It's on AmazonLinux2, Debian8/9 and some other.

**Comment by applerom** [comment]
I am sorry, i found my error - first dash in option "--registry" was Unicode dash character (apparently, I copied this code example from some site).
