### ISSUE TITLE
AWS S3 download error: "Max Retries Exceeded"

### ISSUE THREAD

**Issue by theghaazi** [aws/aws-cli#3148]
Getting this error when running the below command in a shell script to download a file from S3. 
`aws s3 cp --cli-read-timeout 1200 --cli-connect-timeout 1200 s3://Full/path/to/file.csv myfile.csv` 

`download failed: s3://<path/to/myCSVFile>.csv to ./<LocalFileName>.csv Max Retries Exceeded`

the files are of varying size, from 100 MB t o22 GB, getting this at random. Working with 11 files at a time using multiple threads. Cannot Figure out that is causing this error in AWS CLI

```
aws --version
aws-cli/1.12.2 Python/2.7.5 Linux/3.10.0-693.el7.x86_64 botocore/1.8.2
```

**Comment by jamesls** [comment]
You can add the `--debug` option to get more info about what's going wrong.  There shouldn't be any issues uploading files of those sizes with `aws s3 cp`.  If you can post a sanitized debug log, we can take a look at what's going on.

**Comment by theghaazi** [comment]
I got the error again with the --debug on this time. below are the logs.

```
2018-02-22 14:12:01,134 - Thread-6 - botocore.auth - DEBUG - CanonicalRequest:
GET
/<bucketName>/<filename>.csv

host:s3.us-west-2.amazonaws.com
range:bytes=25165824-33554431
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20180222T141201Z
x-amz-security-token:<token>

host;range;x-amz-content-sha256;x-amz-date;x-amz-security-token
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2018-02-22 14:12:01,134 - Thread-6 - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20180222T141201Z
20180222/us-west-2/s3/aws4_request
5efb3763e8ac37d0a0d3f1b344f713dc8020f33a578ff08dec5518a6e749f08a
2018-02-22 14:12:01,134 - Thread-6 - botocore.auth - DEBUG - Signature:
48ff4d12a8b29da9eaee6e127c536d3229035ac459c5bfeb721f0a60fb9584bb
2018-02-22 14:12:01,135 - Thread-6 - botocore.hooks - DEBUG - Event request-created.s3.GetObject: calling handler <function enable_upload_callbacks at 0x1dbf8c0>
2018-02-22 14:12:01,135 - Thread-6 - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [GET]>
2018-02-22 14:12:01,135 - Thread-6 - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (34): s3.us-west-2.amazonaws.com
2018-02-22 14:12:02,638 - Thread-6 - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "GET /<bucketName>/<filename>.csv HTTP/1.1" 206 8388608
2018-02-22 14:12:02,639 - Thread-6 - botocore.parsers - DEBUG - Response headers: {'content-length': '8388608', 'x-amz-id-2': '4F7bELuGkPCnZyrbmruVbxBFA6wwHRh3FaJIBh8m6rID3V8b/kYEtYSpu98BQDUzMRz+red3tXA=', 'accept-ranges': 'bytes', 'server': 'AmazonS3', 'last-modified': 'Wed, 21 Feb 2018 20:36:00 GMT', 'content-range': 'bytes 25165824-33554431/5063586350', 'x-amz-request-id': 'E667494768BE5C46', 'etag': '"5eed7368089da1f82ba6010c8ecf76a5-966"', 'date': 'Thu, 22 Feb 2018 14:12:03 GMT', 'content-type': 'application/x-www-form-urlencoded'}
2018-02-22 14:12:02,639 - Thread-6 - botocore.parsers - DEBUG - Response body:
<botocore.response.StreamingBody object at 0x7f71ec10c4d0>
2018-02-22 14:12:02,639 - Thread-6 - botocore.hooks - DEBUG - Event needs-retry.s3.GetObject: calling handler <botocore.retryhandler.RetryHandler object at 0x28e71d0>
2018-02-22 14:12:02,640 - Thread-6 - botocore.retryhandler - DEBUG - No retry needed.
2018-02-22 14:12:02,640 - Thread-6 - botocore.hooks - DEBUG - Event needs-retry.s3.GetObject: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x28e7250>>
2018-02-22 14:12:02,640 - Thread-6 - botocore.hooks - DEBUG - Event after-call.s3.GetObject: calling handler <function enhance_error_msg at 0x2090938>
2018-02-22 14:12:08,429 - Thread-6 - s3transfer.utils - DEBUG - Releasing acquire 0/None
2018-02-22 14:22:32,292 - Thread-4 - s3transfer.download - DEBUG - Retrying exception caught (HTTPSConnectionPool(host='s3.us-west-2.amazonaws.com', port=443): Read timed out.), retrying request, (attempt 2 / 5)
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python2.7/site-packages/s3transfer/download.py", line 518, in _main
    for chunk in chunks:
  File "/home/ec2-user/.local/lib/python2.7/site-packages/s3transfer/download.py", line 646, in __next__
    chunk = self._body.read(self._chunksize)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/s3transfer/utils.py", line 491, in read
    value = self._stream.read(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/botocore/response.py", line 74, in read
    chunk = self._raw_stream.read(amt)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/botocore/vendored/requests/packages/urllib3/response.py", line 267, in read
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: HTTPSConnectionPool(host='s3.us-west-2.amazonaws.com', port=443): Read timed out.
2018-02-22 14:22:32,293 - Thread-4 - botocore.hooks - DEBUG - Event before-parameter-build.s3.GetObject: calling handler <function sse_md5 at 0x17d5cf8>
2018-02-22 14:22:32,293 - Thread-4 - botocore.hooks - DEBUG - Event before-parameter-build.s3.GetObject: calling handler <function validate_bucket_name at 0x17d5c80>
2018-02-22 14:22:32,293 - Thread-4 - botocore.hooks - DEBUG - Event before-parameter-build.s3.GetObject: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x28e7250>>
2018-02-22 14:22:32,294 - Thread-4 - botocore.hooks - DEBUG - Event before-parameter-build.s3.GetObject: calling handler <function generate_idempotent_uuid at 0x17d5938>
2018-02-22 14:22:32,294 - Thread-4 - botocore.hooks - DEBUG - Event before-call.s3.GetObject: calling handler <function add_expect_header at 0x17d6140>
2018-02-22 14:22:32,294 - Thread-4 - botocore.hooks - DEBUG - Event before-call.s3.GetObject: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x28e7250>>
2018-02-22 14:22:32,294 - Thread-4 - botocore.endpoint - DEBUG - Making request for OperationModel(name=GetObject) (verify_ssl=True) with params: {'body': '', 'url': u'https://s3.us-west-2.amazonaws.com/<bucketName>/<filename>.csv', 'headers': {u'Range': 'bytes=8388608-16777215', 'User-Agent': 'aws-cli/1.12.2 Python/2.7.5 Linux/3.10.0-693.el7.x86_64 botocore/1.8.2'}, 'context': {'auth_type': None, 'client_region': 'us-west-2', 'signing': {'bucket': u'<bucketName>'}, 'has_streaming_input': False, 'client_config': <botocore.config.Config object at 0x28d3250>}, 'query_string': {}, 'url_path': u'/<bucketName>/<filename>.csv', 'method': u'GET'}
2018-02-22 14:22:32,295 - Thread-4 - botocore.hooks - DEBUG - Event request-created.s3.GetObject: calling handler <function disable_upload_callbacks at 0x1dbf848>
2018-02-22 14:22:32,295 - Thread-4 - botocore.hooks - DEBUG - Event request-created.s3.GetObject: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x28d31d0>>
2018-02-22 14:22:32,295 - Thread-4 - botocore.hooks - DEBUG - Event choose-signer.s3.GetObject: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x27f8a10>>
2018-02-22 14:22:32,295 - Thread-4 - botocore.hooks - DEBUG - Event choose-signer.s3.GetObject: calling handler <function set_operation_specific_signer at 0x17d5848>
2018-02-22 14:22:32,295 - Thread-4 - botocore.hooks - DEBUG - Event before-sign.s3.GetObject: calling handler <function fix_s3_host at 0x159fd70>
2018-02-22 14:22:32,295 - Thread-4 - botocore.credentials - DEBUG - Credentials need to be refreshed.
2018-02-22 14:22:32,296 - Thread-4 - botocore.credentials - DEBUG - Credentials need to be refreshed.
2018-02-22 14:22:32,296 - Thread-4 - botocore.credentials - DEBUG - Credentials need to be refreshed.
2018-02-22 14:22:32,297 - Thread-4 - botocore.credentials - DEBUG - Credentials for role retrieved from cache.
2018-02-22 14:22:32,298 - Thread-4 - botocore.credentials - DEBUG - Retrieved credentials will expire at: 2018-02-22 15:15:58+00:00
2018-02-22 14:22:32,298 - Thread-4 - botocore.auth - DEBUG - Calculating signature using v4 auth.
2018-02-22 14:22:32,299 - Thread-4 - botocore.auth - DEBUG - CanonicalRequest:
GET
/<bucketName>/<filename>.csv

host:s3.us-west-2.amazonaws.com
range:bytes=8388608-16777215
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20180222T142232Z
x-amz-security-token:<token>

host;range;x-amz-content-sha256;x-amz-date;x-amz-security-token
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2018-02-22 14:22:32,299 - Thread-4 - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20180222T142232Z
20180222/us-west-2/s3/aws4_request
6c63b3584b6286389d5ed2f76e6aad10d1868702135dc64a36386f1cbfb1e39c
2018-02-22 14:22:32,299 - Thread-4 - botocore.auth - DEBUG - Signature:
9c4c00f9373073e414fea30426047c04755b72afa5670ea54994ea37d0de6561
2018-02-22 14:22:32,299 - Thread-4 - botocore.hooks - DEBUG - Event request-created.s3.GetObject: calling handler <function enable_upload_callbacks at 0x1dbf8c0>
2018-02-22 14:22:32,300 - Thread-4 - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [GET]>
2018-02-22 14:22:32,300 - Thread-4 - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (35): s3.us-west-2.amazonaws.com
2018-02-22 14:22:32,998 - Thread-4 - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "GET /<bucketName>/<filename>.csv HTTP/1.1" 206 8388608
2018-02-22 14:22:32,999 - Thread-4 - botocore.parsers - DEBUG - Response headers: {'content-length': '8388608', 'x-amz-id-2': '7CCVn4rL/SikeCNtFUKcQQrwM6jvH346639U+/xydBHbWaPyWJY58CX46+ey5UX0F3VDV5zLMDc=', 'accept-ranges': 'bytes', 'server': 'AmazonS3', 'last-modified': 'Wed, 21 Feb 2018 20:36:00 GMT', 'content-range': 'bytes 8388608-16777215/5063586350', 'x-amz-request-id': '8CB571F4B3B4690F', 'etag': '"5eed7368089da1f82ba6010c8ecf76a5-966"', 'date': 'Thu, 22 Feb 2018 14:22:33 GMT', 'content-type': 'application/x-www-form-urlencoded'}
2018-02-22 14:22:32,999 - Thread-4 - botocore.parsers - DEBUG - Response body:
<botocore.response.StreamingBody object at 0x7f71ec10c8d0>
2018-02-22 14:22:33,000 - Thread-4 - botocore.hooks - DEBUG - Event needs-retry.s3.GetObject: calling handler <botocore.retryhandler.RetryHandler object at 0x28e71d0>
2018-02-22 14:22:33,000 - Thread-4 - botocore.retryhandler - DEBUG - No retry needed.
2018-02-22 14:22:33,000 - Thread-4 - botocore.hooks - DEBUG - Event needs-retry.s3.GetObject: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x28e7250>>
2018-02-22 14:22:33,000 - Thread-4 - botocore.hooks - DEBUG - Event after-call.s3.GetObject: calling handler <function enhance_error_msg at 0x2090938>
2018-02-22 14:22:34,846 - Thread-4 - s3transfer.futures - DEBUG - Submitting task IORenameFileTask(transfer_id=0, {'final_filename': u'/path/to/the/move/script//<filename>.csv'}) to executor <s3transfer.futures.BoundedExecutor object at 0x29d8350> for transfer request: 0.
2018-02-22 14:22:34,847 - Thread-4 - s3transfer.utils - DEBUG - Acquiring 0
2018-02-22 14:22:34,847 - Thread-4 - s3transfer.utils - DEBUG - Releasing acquire 0/None
2018-02-22 14:22:34,848 - Thread-13 - s3transfer.tasks - DEBUG - IORenameFileTask(transfer_id=0, {'final_filename': u'/path/to/the/file/<filename>.csv'}) about to wait for the following futures []
2018-02-22 14:22:34,848 - Thread-13 - s3transfer.tasks - DEBUG - IORenameFileTask(transfer_id=0, {'final_filename': u'/path/to/the/file/<filename>.csv'}) done waiting for dependent futures
download failed: s3://<bucketName>/<filename>.csv to ./<FileName>.csv Max Retries Exceeded
2018-02-22 14:22:34,850 - Thread-13 - s3transfer.utils - DEBUG - Releasing acquire 0/None
2018-02-22 14:22:34,887 - Thread-1 - awscli.customizations.s3.results - DEBUG - Shutdown request received in result processing thread, shutting down result thread.
```

**Comment by theghaazi** [comment]
@jamesls This happens at random, I see all my threads getting shut down last night because of this error.

**Comment by KaibaLopez** [comment]
Hi @theghaazi ,
Sorry for the lack of response here, I'm looking into older issues and came across this one, from the logs it looks like the error message was confusing but the problem was a timeout (probably network problem).
Can you let me know if you're still having this problem?

**Comment by jianguozhouzunyimedicaluniversity** [comment]
Dear all, @jamesls 
````
(base) [zhou@localhost GSEA]$ aws s3 cp s3://dbgapjgz/ ~/raid/ncbi/dbGaP-24835/RNA_phs001623/cram  --recursive

download failed: s3://dbgapjgz/SRR13977491/013_tram1_xenograft_rna_H_VO_2233_tram_1_RNA_v2_xenome.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977491/013_tram1_xenograft_rna_H_VO_2233_tram_1_RNA_v2_xenome.cram Max Retries Exceeded
download failed: s3://dbgapjgz/SRR13977497/013_tram3_xenograft_rna_H_VO_2233_tram_3_RNA_v2_xenome.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977497/013_tram3_xenograft_rna_H_VO_2233_tram_3_RNA_v2_xenome.cram Max Retries Exceeded
download failed: s3://dbgapjgz/SRR13977494/013_tram2_xenograft_rna_H_VO_2233_tram_2_RNA_v2_xenome.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977494/013_tram2_xenograft_rna_H_VO_2233_tram_2_RNA_v2_xenome.cram Max Retries Exceeded
download failed: s3://dbgapjgz/SRR13977499/013_vehicle1_xenograft_rna_H_VO_2233_vehicle_1_RNA_v2_xenome.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977499/013_vehicle1_xenograft_rna_H_VO_2233_vehicle_1_RNA_v2_xenome.cram Max Retries Exceeded
download failed: s3://dbgapjgz/SRR13977488/013_posttreatment_tumor_rna_H_VO_2233_M1501254.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977488/013_posttreatment_tumor_rna_H_VO_2233_M1501254.cram Max Retries Exceeded
download failed: s3://dbgapjgz/SRR13977484/012_posttreatment_tumor_rna_H_VO_1978_M1501261.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977484/012_posttreatment_tumor_rna_H_VO_1978_M1501261.cram Max Retries Exceeded
download failed: s3://dbgapjgz/SRR13977503/013_vehicle3_xenograft_rna_H_VO_2233_vehicle_3_RNA_v2_xenome.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977503/013_vehicle3_xenograft_rna_H_VO_2233_vehicle_3_RNA_v2_xenome.cram Max Retries Exceeded
download failed: s3://dbgapjgz/SRR13977550/020_baseline_tumor_rna_H_VB_Merck004_m4_d0_RNA.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977550/020_baseline_tumor_rna_H_VB_Merck004_m4_d0_RNA.cram Max Retries Exceeded
download failed: s3://dbgapjgz/SRR13977501/013_vehicle2_xenograft_rna_H_VO_2233_vehicle_2_RNA_v2_xenome.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977501/013_vehicle2_xenograft_rna_H_VO_2233_vehicle_2_RNA_v2_xenome.cram Max Retries Exceeded
download failed: s3://dbgapjgz/SRR13977547/019_posttreatment_tumor_rna_H_VB_Merck003_M1503397.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977547/019_posttreatment_tumor_rna_H_VB_Merck003_M1503397.cram Max Retries Exceeded
download failed: s3://dbgapjgz/SRR13977505/014_posttreatment_tumor_rna_H_VO_6788_M1501257.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977505/014_posttreatment_tumor_rna_H_VO_6788_M1501257.cram Max Retries Exceeded
download failed: s3://dbgapjgz/SRR13977555/020_posttreatment_tumor_rna_H_VB_Merck004_m4_d14_RNA.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977555/020_posttreatment_tumor_rna_H_VB_Merck004_m4_d14_RNA.cram Max Retries Exceeded
download failed: s3://dbgapjgz/SRR13977513/015_posttreatment_tumor_rna_H_VO_7497_M1501274.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977513/015_posttreatment_tumor_rna_H_VO_7497_M1501274.cram Max Retries Exceeded
download failed: s3://dbgapjgz/SRR13977577/040_baseline_tumor_rna_H_VB_Merck024_M1508073.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977577/040_baseline_tumor_rna_H_VB_Merck024_M1508073.cram Max Retries Exceeded
download failed: s3://dbgapjgz/SRR13977594/043_baseline_tumor_rna_H_VO_2899_M1501267.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977594/043_baseline_tumor_rna_H_VO_2899_M1501267.cram Max Retries Exceeded
download failed: s3://dbgapjgz/SRR13977597/043_posttreatment_tumor_rna_H_VO_2899_M1501268.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977597/043_posttreatment_tumor_rna_H_VO_2899_M1501268.cram Max Retries Exceeded
download failed: s3://dbgapjgz/SRR13977602/044_posttreatment_tumor_rna_H_VO_3296_M1501898.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977602/044_posttreatment_tumor_rna_H_VO_3296_M1501898.cram Max Retries Exceeded
download failed: s3://dbgapjgz/SRR13977610/047_baseline_tumor_rna_H_VO_4671_M1501902.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977610/047_baseline_tumor_rna_H_VO_4671_M1501902.cram Max Retries Exceeded
download failed: s3://dbgapjgz/SRR13977605/046_baseline_tumor_rna_H_VO_3833_M1501269.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977605/046_baseline_tumor_rna_H_VO_3833_M1501269.cram Max Retries Exceeded
download failed: s3://dbgapjgz/SRR13977615/048_baseline_tumor_rna_H_VO_5150_M1501904.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977615/048_baseline_tumor_rna_H_VO_5150_M1501904.cram Max Retries Exceeded
download failed: s3://dbgapjgz/SRR13977621/049_baseline_tumor_rna_H_VO_5997_M1501264.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977621/049_baseline_tumor_rna_H_VO_5997_M1501264.cram Max Retries Exceeded
download failed: s3://dbgapjgz/SRR13977618/048_posttreatment_tumor_rna_H_VO_5150_M1501168_1.cram to ../../../../raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977618/048_posttreatment_tumor_rna_H_VO_5150_M1501168_1.cram Max Retries Exceeded
Completed 254.7 GiB/~318.2 GiB (333.9 KiB/s) with ~5 file(s) remaining (calculating...)
````
Best,
JG
