### ISSUE TITLE
aws kms encrypt not using credentials from environment variables 

### ISSUE THREAD

**Issue by peterburlakov** [aws/aws-cli#3170]
I have correct aws credentials in environment variables like this:
``` 
✗ env
AWS_ACCESS_KEY_ID=AAAABBBBCCCDDD
AWS_SECRET_ACCESS_KEY=xxx1111ccc111
AWS_REGION=us-east-2
```

but "aws kms encrypt" works only after I run "aws configure" and fill the same data in local file config(.aws/config)

**Debug info:**
```
✗ aws --version
aws-cli/1.14.47 Python/2.7.14 Linux/4.13.0-36-generic botocore/1.9.0
 
 ✗ aws kms encrypt \
  --key-id alias/key \              
  --plaintext testtext \
  --output text --query CiphertextBlob --debug
2018-02-28 15:27:57,478 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.14.47 Python/2.7.14 Linux/4.13.0-36-generic botocore/1.9.0
2018-02-28 15:27:57,478 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['kms', 'encrypt', '--key-id', 'alias/key', '--plaintext', 'testtext', '--output', 'text', '--query', 'CiphertextBlob', '--debug']
2018-02-28 15:27:57,478 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7f981e867500>
2018-02-28 15:27:57,478 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-02-28 15:27:57,478 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f981b831848>
2018-02-28 15:27:57,478 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-02-28 15:27:57,478 - MainThread - botocore.session - DEBUG - Loading variable credentials_file from defaults.
2018-02-28 15:27:57,478 - MainThread - botocore.session - DEBUG - Loading variable config_file from defaults.
2018-02-28 15:27:57,478 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-02-28 15:27:57,479 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_timeout from defaults.
2018-02-28 15:27:57,479 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-02-28 15:27:57,479 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_num_attempts from defaults.
2018-02-28 15:27:57,479 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-02-28 15:27:57,479 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f981af682a8>
2018-02-28 15:27:57,479 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-02-28 15:27:57,479 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-02-28 15:27:57,479 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2018-02-28 15:27:57,480 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python2.7/dist-packages/botocore/data/kms/2014-11-01/service-2.json
2018-02-28 15:27:57,487 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.kms: calling handler <function register_retries_for_service at 0x7f981c53c140>
2018-02-28 15:27:57,487 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: kms
2018-02-28 15:27:57,488 - MainThread - botocore.hooks - DEBUG - Event building-command-table.kms: calling handler <function add_waiters at 0x7f981e86c938>
2018-02-28 15:27:57,491 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'key-id', <awscli.arguments.CLIArgument object at 0x7f981aa02310>), (u'plaintext', <awscli.arguments.CLIArgument object at 0x7f981aa02350>), (u'encryption-context', <awscli.arguments.CLIArgument object at 0x7f981aa02390>), (u'grant-tokens', <awscli.arguments.ListArgument object at 0x7f981aa023d0>)])
2018-02-28 15:27:57,492 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.kms.encrypt: calling handler <function add_streaming_output_arg at 0x7f981e867b18>
2018-02-28 15:27:57,492 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.kms.encrypt: calling handler <function add_cli_input_json at 0x7f981b7ba500>
2018-02-28 15:27:57,492 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.kms.encrypt: calling handler <function unify_paging_params at 0x7f981aefa050>
2018-02-28 15:27:57,494 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python2.7/dist-packages/botocore/data/kms/2014-11-01/paginators-1.json
2018-02-28 15:27:57,494 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.kms.encrypt: calling handler <function add_generate_skeleton at 0x7f981aee6410>
2018-02-28 15:27:57,495 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.kms.encrypt: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7f981aa02410>>
2018-02-28 15:27:57,495 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.kms.encrypt: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f981a9f7210>>
2018-02-28 15:27:57,496 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.kms.encrypt.key-id: calling handler <function uri_param at 0x7f981b85c230>
2018-02-28 15:27:57,496 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.kms.encrypt: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f981b8171d0>
2018-02-28 15:27:57,496 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'alias/key' for parameter "key_id": u'alias/key'
2018-02-28 15:27:57,496 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.kms.encrypt.plaintext: calling handler <function uri_param at 0x7f981b85c230>
2018-02-28 15:27:57,496 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.kms.encrypt: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f981b8171d0>
2018-02-28 15:27:57,496 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'testtext' for parameter "plaintext": u'testtext'
2018-02-28 15:27:57,496 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.kms.encrypt.encryption-context: calling handler <function uri_param at 0x7f981b85c230>
2018-02-28 15:27:57,496 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.kms.encrypt.grant-tokens: calling handler <function uri_param at 0x7f981b85c230>
2018-02-28 15:27:57,496 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.kms.encrypt.cli-input-json: calling handler <function uri_param at 0x7f981b85c230>
2018-02-28 15:27:57,496 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.kms.encrypt.generate-cli-skeleton: calling handler <function uri_param at 0x7f981b85c230>
2018-02-28 15:27:57,496 - MainThread - botocore.hooks - DEBUG - Event calling-command.kms.encrypt: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7f981aa02410>>
2018-02-28 15:27:57,496 - MainThread - botocore.hooks - DEBUG - Event calling-command.kms.encrypt: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f981a9f7210>>
2018-02-28 15:27:57,496 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-02-28 15:27:57,496 - MainThread - botocore.session - DEBUG - Loading variable region from defaults.
2018-02-28 15:27:57,497 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-02-28 15:27:57,497 - MainThread - botocore.session - DEBUG - Loading variable ca_bundle from defaults.
2018-02-28 15:27:57,497 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-02-28 15:27:57,497 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2018-02-28 15:27:57,497 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2018-02-28 15:27:57,497 - MainThread - botocore.credentials - INFO - Found credentials in environment variables.
2018-02-28 15:27:57,497 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python2.7/dist-packages/botocore/data/endpoints.json
2018-02-28 15:27:57,508 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-02-28 15:27:57,508 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f981c5b88c0>
2018-02-28 15:27:57,510 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.kms: calling handler <function add_generate_presigned_url at 0x7f981c582c80>
2018-02-28 15:27:57,510 - MainThread - awscli.clidriver - DEBUG - You must specify a region. You can also configure your region by running "aws configure".
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 208, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 345, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 517, in __call__
    call_parameters, parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 635, in invoke
    verify=parsed_globals.verify_ssl)
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 861, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 76, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 285, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python2.7/dist-packages/botocore/args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/local/lib/python2.7/dist-packages/botocore/args.py", line 111, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 358, in resolve
    service_name, region_name)
  File "/usr/local/lib/python2.7/dist-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/local/lib/python2.7/dist-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
NoRegionError: You must specify a region.
You must specify a region. You can also configure your region by running "aws configure".
```

**Comment by stealthycoin** [comment]
The variable is `AWS_DEFAULT_REGION`
https://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html

**Comment by peterburlakov** [comment]
@stealthycoin ty, that works, closing
