### ISSUE TITLE
aws emr create-cluster fails at json file input from s3 for instance-groups

### ISSUE THREAD

**Issue by jubinsanghvitbw** [aws/aws-cli#3228]
I am running the following command (I've changed the bucket name for anonymity):

`aws emr create-cluster --release-label emr-5.9.0 --instance-groups s3://my-bucket/outbound-data-delivery/instance-groups.json --auto-terminate --use-default-roles --log-uri s3://my-bucket/logs/outbound-data-delivery/ --ec2-attributes KeyName=backend,SubnetId=subnet-be494996,EmrManagedMasterSecurityGroup=sg-03c3837c,EmrManagedSlaveSecurityGroup=sg-d3c484ac,AdditionalMasterSecurityGroups=sg-4bff1a37,AdditionalSlaveSecurityGroups=sg-4bff1a37 --name Outbound-Data-Delivery --no-termination-protected --visible-to-all-users --applications Name=Spark`

I am trying to use the json file I have up at s3 for --instance-groups and it fails saying

`Error parsing parameter '--instance-groups': Expected: '=', received: ':' for input:
s3://tbw-analytics/outbound-data-delivery/instance-groups.json`

The same works fine if I use a local file like `file://instance-groups.json`
Below are the debug logs:

2018-03-29 16:18:48,071 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.11.13 Python/3.5.2 Linux/4.4.0-1022-aws botocore/1.9.11
2018-03-29 16:18:48,072 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['emr', 'create-cluster', '--release-label', 'emr-5.9.0', '--instance-groups', 's3://my-bucket/outbound-data-delivery/instance-groups.json', '--auto-terminate', '--use-default-roles', '--log-uri', 's3://my-bucket/logs/outbound-data-delivery/', '--ec2-attributes', 'KeyName=backend,SubnetId=subnet-be493996,EmrManagedMasterSecurityGroup=sg-03c3847c,EmrManagedSlaveSecurityGroup=sg-d4c484ac,AdditionalMasterSecurityGroups=sg-4bff1a47,AdditionalSlaveSecurityGroups=sg-4bff1a47', '--name', 'Outbound-Data-Delivery', '--no-termination-protected', '--visible-to-all-users', '--applications', 'Name=Spark', '--debug']
2018-03-29 16:18:48,072 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7f4f2f06e158>
2018-03-29 16:18:48,072 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f4f2dfd1e18>
2018-03-29 16:18:48,072 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-03-29 16:18:48,073 - MainThread - botocore.session - DEBUG - Loading variable credentials_file from defaults.
2018-03-29 16:18:48,073 - MainThread - botocore.session - DEBUG - Loading variable config_file from defaults.
2018-03-29 16:18:48,073 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-03-29 16:18:48,073 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_timeout from defaults.
2018-03-29 16:18:48,073 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-03-29 16:18:48,073 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_num_attempts from defaults.
2018-03-29 16:18:48,073 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-03-29 16:18:48,074 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-03-29 16:18:48,074 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2018-03-29 16:18:48,074 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python3.5/dist-packages/botocore/data/emr/2009-03-31/service-2.json
2018-03-29 16:18:48,079 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.emr: calling handler <function register_retries_for_service at 0x7f4f2e4e11e0>
2018-03-29 16:18:48,080 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: emr
2018-03-29 16:18:48,081 - MainThread - botocore.hooks - DEBUG - Event building-command-table.emr: calling handler functools.partial(<function _remove_commands at 0x7f4f2dc69268>, commands_to_remove=['run-job-flow', 'describe-job-flows', 'add-job-flow-steps', 'terminate-job-flows', 'list-bootstrap-actions', 'list-instance-groups', 'set-termination-protection', 'set-visible-to-all-users'])
2018-03-29 16:18:48,081 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: run-job-flow
2018-03-29 16:18:48,081 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: describe-job-flows
2018-03-29 16:18:48,082 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: add-job-flow-steps
2018-03-29 16:18:48,082 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: terminate-job-flows
2018-03-29 16:18:48,082 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: list-bootstrap-actions
2018-03-29 16:18:48,082 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: list-instance-groups
2018-03-29 16:18:48,082 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: set-termination-protection
2018-03-29 16:18:48,082 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: set-visible-to-all-users
2018-03-29 16:18:48,082 - MainThread - botocore.hooks - DEBUG - Event building-command-table.emr: calling handler <function register_commands at 0x7f4f2dc40ae8>
2018-03-29 16:18:48,082 - MainThread - botocore.hooks - DEBUG - Event building-command-table.emr: calling handler <function add_waiters at 0x7f4f2f075510>
2018-03-29 16:18:48,086 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python3.5/dist-packages/botocore/data/emr/2009-03-31/waiters-2.json
2018-03-29 16:18:48,087 - MainThread - botocore.hooks - DEBUG - Event building-command-table.create-cluster: calling handler <function add_waiters at 0x7f4f2f075510>
2018-03-29 16:18:48,088 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.emr.create-cluster: calling handler <function override_args_required_option at 0x7f4f2dc9bae8>
2018-03-29 16:18:48,088 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-03-29 16:18:48,090 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.create-cluster.instance-groups: calling handler <function uri_param at 0x7f4f2e007950>
2018-03-29 16:18:48,090 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.create-cluster: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f4f2dfb2160>
2018-03-29 16:18:48,091 - MainThread - awscli.argprocess - DEBUG - Parsing param --instance-groups as shorthand
2018-03-29 16:18:48,091 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/awscli/argprocess.py", line 334, in _parse_as_shorthand
    parsed = [self._parser.parse(v) for v in value]
  File "/usr/lib/python3/dist-packages/awscli/argprocess.py", line 334, in <listcomp>
    parsed = [self._parser.parse(v) for v in value]
  File "/usr/lib/python3/dist-packages/awscli/shorthand.py", line 146, in parse
    return self._parameter()
  File "/usr/lib/python3/dist-packages/awscli/shorthand.py", line 151, in _parameter
    params.update(self._keyval())
  File "/usr/lib/python3/dist-packages/awscli/shorthand.py", line 160, in _keyval
    self._expect('=', consume_whitespace=True)
  File "/usr/lib/python3/dist-packages/awscli/shorthand.py", line 320, in _expect
    actual, self._index)
awscli.shorthand.ShorthandParseError: Expected: '=', received: ':' for input:
s3://my-bucket/outbound-data-delivery/instance-groups.json
  ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 186, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 381, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/lib/python3/dist-packages/awscli/customizations/commands.py", line 166, in __call__
    cli_argument=cli_argument, value=value, operation=None)
  File "/usr/local/lib/python3.5/dist-packages/botocore/session.py", line 722, in emit_first_non_none_response
    responses = self._events.emit(event_name, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/lib/python3/dist-packages/awscli/argprocess.py", line 317, in __call__
    cli_argument, value, service_name, operation_name)
  File "/usr/lib/python3/dist-packages/awscli/argprocess.py", line 341, in _parse_as_shorthand
    raise ParamError(cli_argument.cli_name, str(e))
awscli.argprocess.ParamError: Error parsing parameter '--instance-groups': Expected: '=', received: ':' for input:
s3://my-bucket/outbound-data-delivery/instance-groups.json
  ^
2018-03-29 16:18:48,092 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Error parsing parameter '--instance-groups': Expected: '=', received: ':' for input:
s3://my-bucket/outbound-data-delivery/instance-groups.json
  ^

**Comment by kyleknap** [comment]
@jubinsanghvitbw thanks for the debug logs that helps a lot. So unfortunately the CLI does not support that ability. That notation can only be used in the `s3` command set. You will instead need to use `https://` or `file://` to get the contents of the file. But I will mark this as a feature request.

**Comment by MonikaCon** [comment]
I still got this, it hasn't been fixed?
The documentation says otherwise.

**Comment by sp3107** [comment]
Anybody managed to solve this?

Also for file:// , what if my files are in a different directory?

file::///tmp/abc.json does not work. https:// also does not work.
