### ISSUE TITLE
xml.sax._exceptions.SAXParseException: <unknown>:1:0: no element found

### ISSUE THREAD

**Issue by lixiong4788** [aws/aws-cli#3232]
```python
import boto
import boto.s3.connection
access_key = 'redacted'
secret_key = 'redacted'
host = 'www.abc.com'
port = 7480

#connect s3
conn = boto.connect_s3(
        aws_access_key_id = access_key,
        aws_secret_access_key = secret_key,
        host = host  ,port = port ,
        is_secure=False,               # uncomment if you are not using ssl
        calling_format = boto.s3.connection.OrdinaryCallingFormat(),
        )

**conn.create_bucket('abc')**
**conn.create_bucket('abc/cdef')**

bucket = conn.get_bucket('abc/cdef')
object_key = '1433368/14012368_1521781178_1521782794_9010.mp4'
object_file = '141523468_1521781178_1521782794_9010.mp4'

key = bucket.new_key(object_key)
key.set_contents_from_filename(object_file)

for key in bucket.list():
        print "{name}\t{size}\t{modified}".format(
                name = key.name,
                size = key.size,
                modified = key.last_modified,
                )
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/boto/s3/bucketlistresultset.py", line 34, in bucket_lister
    encoding_type=encoding_type)
  File "/usr/lib/python2.7/site-packages/boto/s3/bucket.py", line 474, in get_all_keys
    '', headers, **params)
  File "/usr/lib/python2.7/site-packages/boto/s3/bucket.py", line 408, in _get_all
    xml.sax.parseString(body, h)
  File "/usr/lib64/python2.7/xml/sax/__init__.py", line 49, in parseString
    parser.parse(inpsrc)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.7/xml/sax/xmlreader.py", line 125, in parse
    self.close()
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 220, in close
    self.feed("", isFinal = 1)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 214, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib64/python2.7/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:1:0: no element found
```

**Comment by lixiong4788** [comment]
the only different is that:
i create bucket 'abc', and then create bucket 'abc/cdef'

the error appear

**Comment by JordonPhillips** [comment]
This is the repo for the aws cli, not for boto 2. Unfortunately I'm not sure what the problem here is. I would recommend upgrading to boto3.
