### ISSUE TITLE
pip install awscli breaks the cli

### ISSUE THREAD

**Issue by jonatversprite** [aws/aws-cli#3246]
$ pip install awscli
upgraded to 1.15.2. next I ran 'aws --version', received the following error messages, and the cli went totally unusable

[ec2-user@ip-172-31-35-202 Scout2]$ aws --version
Traceback (most recent call last):
  File "/usr/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/lib/python2.7/dist-packages/awscli/clidriver.py", line 58, in main
    rc = driver.main()
  File "/usr/lib/python2.7/dist-packages/awscli/clidriver.py", line 193, in main
    command_table = self._get_command_table()
  File "/usr/lib/python2.7/dist-packages/awscli/clidriver.py", line 102, in _get_command_table
    self._command_table = self._build_command_table()
  File "/usr/lib/python2.7/dist-packages/awscli/clidriver.py", line 122, in _build_command_table
    command_object=self)
  File "/usr/local/lib/python2.7/site-packages/botocore/session.py", line 719, in emit
    return self._events.emit(event_name, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/lib/python2.7/dist-packages/awscli/customizations/sagemaker.py", line 27, in alias_sagemaker_runtime_command
    alias_name='runtime.sagemaker',
  File "/usr/lib/python2.7/dist-packages/awscli/customizations/utils.py", line 106, in make_hidden_command_alias
    new = _copy_argument(command_table, existing_name, alias_name)
  File "/usr/lib/python2.7/dist-packages/awscli/customizations/utils.py", line 31, in _copy_argument
    current = argument_table[current_name]
KeyError: 'sagemaker-runtime'

I downgraded to 1.14.36 and the problem went away

**Comment by ferschubert** [comment]
Same issue here, but it broke after a yum update on a Cloud9 Instance. Solution was also to downgrade:
---> Package aws-cli.noarch 0:1.11.132-1.47.amzn1 will be a downgrade
**---> Package aws-cli.noarch 0:1.14.9-1.48.amzn1 will be erased**
---> Package python27-botocore.noarch 0:1.5.95-1.65.amzn1 will be a downgrade
---> Package python27-botocore.noarch 0:1.8.13-1.66.amzn1 will be erased

To fix the dependencies I issued the following command, just in case someone needs it:

`sudo yum downgrade aws-cli.noarch python27-botocore`

**Comment by stealthycoin** [comment]
Is this installing into your global environment? This doesn't mix well with the linux distro's installation methods which we do not support and I would not recommend using them. `pip install --user awscli` as per https://docs.aws.amazon.com/cli/latest/userguide/installing.html.

**Comment by kyleknap** [comment]
Closing due to inactivity
