### ISSUE TITLE
aws opsworks register throws ValidationException

### ISSUE THREAD

**Issue by Junkern** [aws/aws-cli#3255]
version: `aws-cli/1.14.32 Python/3.5.2 Linux/4.4.0-1049-aws botocore/1.8.36`

I have spun up an instance with the help of terraform and after that I want to register it in an opsworks stack:

`aws opsworks register --infrastructure-class ec2 --region eu-west-1 --stack-id some_id --override-ssh "ssh-command" instance_id`

Running the command connects to the instance and starts executing. It downloads the opsworks-agent-ruby and then after `opsworks-init: Starting the installer` it crashes. It worked perfectly two weeks ago with the same AMI.

```

/opt/aws/opsworks/releases/20170402215230_4023-20170402215230/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.26/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Aws::OpsWorks::Errors::ValidationException
	from /opt/aws/opsworks/releases/20170402215230_4023-20170402215230/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.26/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /opt/aws/opsworks/releases/20170402215230_4023-20170402215230/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.26/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /opt/aws/opsworks/releases/20170402215230_4023-20170402215230/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.26/lib/seahorse/client/request.rb:70:in `send_request'
	from /opt/aws/opsworks/releases/20170402215230_4023-20170402215230/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.26/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /tmp/opsworks-agent-installer.mt36KnGoq7krLznv/opsworks-agent-installer/opsworks-agent/lib/bootstrap/registration.rb:136:in `register_instance'
	from /tmp/opsworks-agent-installer.mt36KnGoq7krLznv/opsworks-agent-installer/opsworks-agent/lib/bootstrap/registration.rb:55:in `merge_agent_config'
	from /tmp/opsworks-agent-installer.mt36KnGoq7krLznv/opsworks-agent-installer/opsworks-agent/lib/bootstrap/registration.rb:14:in `block in generate_agent_config'
	from /tmp/opsworks-agent-installer.mt36KnGoq7krLznv/opsworks-agent-installer/opsworks-agent/lib/bootstrap/registration.rb:13:in `open'
	from /tmp/opsworks-agent-installer.mt36KnGoq7krLznv/opsworks-agent-installer/opsworks-agent/lib/bootstrap/registration.rb:13:in `generate_agent_config'
	from /tmp/opsworks-agent-installer.mt36KnGoq7krLznv/opsworks-agent-installer/opsworks-agent/lib/bootstrap/instance_agent_registration_installer.rb:29:in `block in run'
	from /tmp/opsworks-agent-installer.mt36KnGoq7krLznv/opsworks-agent-installer/opsworks-agent/lib/bootstrap/log.rb:96:in `measure'
	from /tmp/opsworks-agent-installer.mt36KnGoq7krLznv/opsworks-agent-installer/opsworks-agent/lib/bootstrap/instance_agent_registration_installer.rb:29:in `run'
	from /tmp/opsworks-agent-installer.mt36KnGoq7krLznv/opsworks-agent-installer/opsworks-agent/lib/bootstrap/instance_agent_registration_installer.rb:11:in `run'
	from /tmp/opsworks-agent-installer.mt36KnGoq7krLznv/opsworks-agent-installer/opsworks-agent/bin/opsworks-agent-registration-installer.rb:8:in `<main>'
```

**Comment by stealthycoin** [comment]
Hi, I would suggest reaching out to [AWS Support](https://console.aws.amazon.com/support/home#/) for opsworks since it looks like the error is in the `opsworks-agent-ruby` which they maintain. I don't know anything about it, all the CLI does here is call their API, which it looks like it did correctly if it kicked off their build script.

**Comment by Junkern** [comment]
Thanks for the response, I will contact them :)
