### ISSUE TITLE
DataNotFoundError for 'cli' with 1.15.4 and botocore 1.10.4

### ISSUE THREAD

**Issue by MatthewRalston** [aws/aws-cli#3258]
I'm having a similar issue to #101 with `aws-cli/1.15.4 Python/2.7.8 Linux/2.6.32-504.el6.x86_64 botocore/1.10.4`

I am running a unit test for a function that invokes the cli `create_clidriver.main([args])`. When I run my script/module from the command line, the clidriver runs fine. But inside my test environment (with identical `PYTHONPATH`), 'cli' is not found. 
```python
Traceback (most recent call last):
  File "/path/to/synchronize.py", line 31, in s3sync
    exit_code = create_clidriver().main(["s3", "sync", source, destination])
  File "/path/to/.venv/lib/python2.7/site-packages/awscli/clidriver.py", line 195, in main
    parser = self._create_parser(command_table)
  File "/path/to/.venv/lib/python2.7/site-packages/awscli/clidriver.py", line 175, in _create_parser
    command_table['help'] = self.create_help_command()
  File "/path/to/.venv/lib/python2.7/site-packages/awscli/clidriver.py", line 166, in create_help_command
    cli_data = self._get_cli_data()
  File "/path/to/.venv/lib/python2.7/site-packages/awscli/clidriver.py", line 98, in _get_cli_data
    self._cli_data = self.session.get_data('cli')
  File "/path/to/.venv/lib/python2.7/site-packages/botocore/session.py", line 519, in get_data
    return self.get_component('data_loader').load_data(data_path)
  File "/path/to/.venv/lib/python2.7/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/path/to/.venv/lib/python2.7/site-packages/botocore/loaders.py", line 424, in load_data
    raise DataNotFoundError(data_path=name)
DataNotFoundError: Unable to load data for: cli

```

Can someone tell me what file/module this is referring to and how I can help debug/troubleshoot?

**Comment by stealthycoin** [comment]
This is a private interface and is not intended to be publicly consumed so I would suggest not doing this as we can change it or rip it out at any time. That being said you can just see what we do in our own tests.

https://github.com/aws/aws-cli/blob/develop/awscli/testutils.py#L229

**Comment by MatthewRalston** [comment]
I'll close. 

For posterity's sake though I've noticed that my os.environ is reset on each invocation while playing around in the REPL. It looks like you're wiping out this variable at some point after retrieving information from it. 

```python
>os.environ
{}
>os.environ['AWS_DATA_PATH'] = "/path/to/site-packages/awscli/data" # As per __init__.py
>os.environ
{'AWS_DATA_PATH': "/path/to/site-packages/awscli/data"}
>p=create_clidriver().main("s3 sync mybucket directory".split())
# works
>os.environ
{}
>p=create_clidriver().main("s3 sync mybucket directory".split())
...
DataNotFoundError: Unable to load data for: cli
```
