### ISSUE TITLE
ssl 509 with aws secretsmanager create-secret

### ISSUE THREAD

**Issue by wallnerryan** [aws/aws-cli#3327]
```
(awssso) ➜  ecs-testing aws --debug secretsmanager create-secret --name development/co-example-secret
2018-05-16 16:02:27,839 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.15.22 Python/2.7.10 Darwin/16.7.0 botocore/1.10.22
2018-05-16 16:02:27,839 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', 'secretsmanager', 'create-secret', '--name', 'development/co-example-secret']
2018-05-16 16:02:27,840 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x1021b29b0>
2018-05-16 16:02:27,840 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'saml'.
2018-05-16 16:02:27,840 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x101aae7d0>
2018-05-16 16:02:27,840 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'saml'.
2018-05-16 16:02:27,840 - MainThread - botocore.session - DEBUG - Loading variable credentials_file from defaults.
2018-05-16 16:02:27,840 - MainThread - botocore.session - DEBUG - Loading variable config_file from defaults.
2018-05-16 16:02:27,840 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'saml'.
2018-05-16 16:02:27,840 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_timeout from defaults.
2018-05-16 16:02:27,840 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'saml'.
2018-05-16 16:02:27,840 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_num_attempts from defaults.
2018-05-16 16:02:27,840 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-05-16 16:02:27,841 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x1020ba500>
2018-05-16 16:02:27,841 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'saml'.
2018-05-16 16:02:27,841 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'saml'.
2018-05-16 16:02:27,854 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2018-05-16 16:02:27,855 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/data/secretsmanager/2017-10-17/service-2.json
2018-05-16 16:02:27,861 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.secretsmanager: calling handler <function register_retries_for_service at 0x10174ad70>
2018-05-16 16:02:27,862 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: secretsmanager
2018-05-16 16:02:27,863 - MainThread - botocore.hooks - DEBUG - Event building-command-table.secretsmanager: calling handler <function add_waiters at 0x1021b8b18>
2018-05-16 16:02:27,876 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'name', <awscli.arguments.CLIArgument object at 0x1023b4490>), (u'client-request-token', <awscli.arguments.CLIArgument object at 0x1023b44d0>), (u'description', <awscli.arguments.CLIArgument object at 0x1023b4510>), (u'kms-key-id', <awscli.arguments.CLIArgument object at 0x1023b4550>), (u'secret-binary', <awscli.arguments.CLIArgument object at 0x1023b4590>), (u'secret-string', <awscli.arguments.CLIArgument object at 0x1023b45d0>), (u'tags', <awscli.arguments.ListArgument object at 0x1023b4610>)])
2018-05-16 16:02:27,876 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.secretsmanager.create-secret: calling handler <function add_streaming_output_arg at 0x1021b2c08>
2018-05-16 16:02:27,876 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.secretsmanager.create-secret: calling handler <function add_cli_input_json at 0x101ab4398>
2018-05-16 16:02:27,877 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.secretsmanager.create-secret: calling handler <function unify_paging_params at 0x102134de8>
2018-05-16 16:02:27,893 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/data/secretsmanager/2017-10-17/paginators-1.json
2018-05-16 16:02:27,894 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.secretsmanager.create-secret: calling handler <function add_generate_skeleton at 0x10212f230>
2018-05-16 16:02:27,894 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.secretsmanager.create-secret: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x1023b4650>>
2018-05-16 16:02:27,894 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.secretsmanager.create-secret: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x1023b47d0>>
2018-05-16 16:02:27,895 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.secretsmanager.create-secret.name: calling handler <function uri_param at 0x1019440c8>
2018-05-16 16:02:27,895 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.secretsmanager.create-secret: calling handler <awscli.argprocess.ParamShorthandParser object at 0x1021bbf90>
2018-05-16 16:02:27,895 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'development/co-example-secret' for parameter "name": u'development/co-example-secret'
2018-05-16 16:02:27,895 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.secretsmanager.create-secret.client-request-token: calling handler <function uri_param at 0x1019440c8>
2018-05-16 16:02:27,896 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.secretsmanager.create-secret.description: calling handler <function uri_param at 0x1019440c8>
2018-05-16 16:02:27,896 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.secretsmanager.create-secret.kms-key-id: calling handler <function uri_param at 0x1019440c8>
2018-05-16 16:02:27,896 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.secretsmanager.create-secret.secret-binary: calling handler <function uri_param at 0x1019440c8>
2018-05-16 16:02:27,906 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.secretsmanager.create-secret.secret-string: calling handler <function uri_param at 0x1019440c8>
2018-05-16 16:02:27,906 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.secretsmanager.create-secret.tags: calling handler <function uri_param at 0x1019440c8>
2018-05-16 16:02:27,906 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.secretsmanager.create-secret.cli-input-json: calling handler <function uri_param at 0x1019440c8>
2018-05-16 16:02:27,906 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.secretsmanager.create-secret.generate-cli-skeleton: calling handler <function uri_param at 0x1019440c8>
2018-05-16 16:02:27,906 - MainThread - botocore.hooks - DEBUG - Event calling-command.secretsmanager.create-secret: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x1023b4650>>
2018-05-16 16:02:27,907 - MainThread - botocore.hooks - DEBUG - Event calling-command.secretsmanager.create-secret: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x1023b47d0>>
2018-05-16 16:02:27,907 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'saml'.
2018-05-16 16:02:27,907 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'saml'.
2018-05-16 16:02:27,907 - MainThread - botocore.session - DEBUG - Loading variable region from config file with value 'us-east-1'.
2018-05-16 16:02:27,907 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'saml'.
2018-05-16 16:02:27,907 - MainThread - botocore.session - DEBUG - Loading variable ca_bundle from defaults.
2018-05-16 16:02:27,907 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'saml'.
2018-05-16 16:02:27,907 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2018-05-16 16:02:27,907 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2018-05-16 16:02:27,907 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2018-05-16 16:02:27,907 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2018-05-16 16:02:27,908 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2018-05-16 16:02:27,908 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/data/endpoints.json
2018-05-16 16:02:27,947 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'saml'.
2018-05-16 16:02:27,947 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x10174a578>
2018-05-16 16:02:27,948 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.secretsmanager: calling handler <function add_generate_presigned_url at 0x101709500>
2018-05-16 16:02:27,948 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2018-05-16 16:02:27,958 - MainThread - botocore.endpoint - DEBUG - Setting secretsmanager timeout as (60, 60)
2018-05-16 16:02:27,959 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: secretsmanager
2018-05-16 16:02:27,960 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.secretsmanager.CreateSecret: calling handler <function generate_idempotent_uuid at 0x10174a7d0>
2018-05-16 16:02:27,960 - MainThread - botocore.handlers - DEBUG - injecting idempotency token (43553447-f25c-4aa4-8a86-d225c09ec9b6) into param 'ClientRequestToken'.
2018-05-16 16:02:27,960 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=CreateSecret) (verify_ssl=True) with params: {'body': '{"Name": "development/co-example-secret", "ClientRequestToken": "43553447-f25c-4aa4-8a86-d225c09ec9b6"}', 'url': u'https://secretsmanager.us-east-1.amazonaws.com/', 'headers': {'User-Agent': 'aws-cli/1.15.22 Python/2.7.10 Darwin/16.7.0 botocore/1.10.22', 'Content-Type': u'application/x-amz-json-1.1', 'X-Amz-Target': u'secretsmanager.CreateSecret'}, 'context': {'auth_type': None, 'client_region': 'us-east-1', 'has_streaming_input': False, 'client_config': <botocore.config.Config object at 0x1023b4b90>}, 'query_string': '', 'url_path': '/', 'method': u'POST'}
2018-05-16 16:02:27,961 - MainThread - botocore.hooks - DEBUG - Event request-created.secretsmanager.CreateSecret: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x1022c5a10>>
2018-05-16 16:02:27,961 - MainThread - botocore.hooks - DEBUG - Event choose-signer.secretsmanager.CreateSecret: calling handler <function set_operation_specific_signer at 0x10174a6e0>
2018-05-16 16:02:27,962 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2018-05-16 16:02:27,962 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-amz-json-1.1
host:secretsmanager.us-east-1.amazonaws.com
x-amz-date:20180516T200227Z
x-amz-security-token:<removed>
x-amz-target:secretsmanager.CreateSecret

content-type;host;x-amz-date;x-amz-security-token;x-amz-target
71550e8dba1fb6f052f3b62b3494da16814fe6e8f46041e097f73a17152b690c
2018-05-16 16:02:27,962 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20180516T200227Z
20180516/us-east-1/secretsmanager/aws4_request
e75494c9aa1fa54ee7e952e8549ba1e629442625f9c702f227b770d3efb80079
2018-05-16 16:02:27,963 - MainThread - botocore.auth - DEBUG - Signature:
9039b2db541a880fd210a2451d7e1c48a97e27200facf7a6daf22defb018bf03
2018-05-16 16:02:27,963 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2018-05-16 16:02:27,964 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): secretsmanager.us-east-1.amazonaws.com
2018-05-16 16:02:28,063 - MainThread - botocore.endpoint - DEBUG - ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/endpoint.py", line 222, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
2018-05-16 16:02:28,066 - MainThread - botocore.hooks - DEBUG - Event needs-retry.secretsmanager.CreateSecret: calling handler <botocore.retryhandler.RetryHandler object at 0x1023b0250>
2018-05-16 16:02:28,066 - MainThread - botocore.retryhandler - DEBUG - retry needed, retryable exception caught: EOF occurred in violation of protocol (_ssl.c:590)
Traceback (most recent call last):
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
2018-05-16 16:02:28,067 - MainThread - botocore.retryhandler - DEBUG - Retry needed, action of: 0.436920881447
2018-05-16 16:02:28,067 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.436920881447 seconds
2018-05-16 16:02:28,505 - MainThread - botocore.hooks - DEBUG - Event request-created.secretsmanager.CreateSecret: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x1022c5a10>>
2018-05-16 16:02:28,505 - MainThread - botocore.hooks - DEBUG - Event choose-signer.secretsmanager.CreateSecret: calling handler <function set_operation_specific_signer at 0x10174a6e0>
2018-05-16 16:02:28,505 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2018-05-16 16:02:28,505 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-amz-json-1.1
host:secretsmanager.us-east-1.amazonaws.com
x-amz-date:20180516T200228Z
x-amz-security-token:<removed>
x-amz-target:secretsmanager.CreateSecret

content-type;host;x-amz-date;x-amz-security-token;x-amz-target
71550e8dba1fb6f052f3b62b3494da16814fe6e8f46041e097f73a17152b690c
2018-05-16 16:02:28,506 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20180516T200228Z
20180516/us-east-1/secretsmanager/aws4_request
416eddc753331bfd67e82b40b8e1a9d7ea2e18ece30f2a7b6c467e51db7f49dd
2018-05-16 16:02:28,506 - MainThread - botocore.auth - DEBUG - Signature:
a7ec7a42a41821a8592d8b03dae5dec4cecd3e8a25e79d4ae2cd569960faff47
2018-05-16 16:02:28,506 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2018-05-16 16:02:28,506 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (2): secretsmanager.us-east-1.amazonaws.com
2018-05-16 16:02:28,587 - MainThread - botocore.endpoint - DEBUG - ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/endpoint.py", line 222, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
2018-05-16 16:02:28,587 - MainThread - botocore.hooks - DEBUG - Event needs-retry.secretsmanager.CreateSecret: calling handler <botocore.retryhandler.RetryHandler object at 0x1023b0250>
2018-05-16 16:02:28,588 - MainThread - botocore.retryhandler - DEBUG - retry needed, retryable exception caught: EOF occurred in violation of protocol (_ssl.c:590)
Traceback (most recent call last):
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
2018-05-16 16:02:28,588 - MainThread - botocore.retryhandler - DEBUG - Retry needed, action of: 1.48528953993
2018-05-16 16:02:28,588 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 1.48528953993 seconds
2018-05-16 16:02:30,074 - MainThread - botocore.hooks - DEBUG - Event request-created.secretsmanager.CreateSecret: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x1022c5a10>>
2018-05-16 16:02:30,074 - MainThread - botocore.hooks - DEBUG - Event choose-signer.secretsmanager.CreateSecret: calling handler <function set_operation_specific_signer at 0x10174a6e0>
2018-05-16 16:02:30,075 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2018-05-16 16:02:30,075 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-amz-json-1.1
host:secretsmanager.us-east-1.amazonaws.com
x-amz-date:20180516T200230Z
x-amz-security-token:<removed>
x-amz-target:secretsmanager.CreateSecret

content-type;host;x-amz-date;x-amz-security-token;x-amz-target
71550e8dba1fb6f052f3b62b3494da16814fe6e8f46041e097f73a17152b690c
2018-05-16 16:02:30,075 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20180516T200230Z
20180516/us-east-1/secretsmanager/aws4_request
8906052c89b70c3d4aec24614bb19b68b791b42985d7fd05870428fa032d2caf
2018-05-16 16:02:30,076 - MainThread - botocore.auth - DEBUG - Signature:
b774233d1cdb41f5724f957b5969500b113336e15aa6552a10505b2e06301a6c
2018-05-16 16:02:30,076 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2018-05-16 16:02:30,076 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (3): secretsmanager.us-east-1.amazonaws.com
2018-05-16 16:02:30,160 - MainThread - botocore.endpoint - DEBUG - ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/endpoint.py", line 222, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
2018-05-16 16:02:30,160 - MainThread - botocore.hooks - DEBUG - Event needs-retry.secretsmanager.CreateSecret: calling handler <botocore.retryhandler.RetryHandler object at 0x1023b0250>
2018-05-16 16:02:30,160 - MainThread - botocore.retryhandler - DEBUG - retry needed, retryable exception caught: EOF occurred in violation of protocol (_ssl.c:590)
Traceback (most recent call last):
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
2018-05-16 16:02:30,161 - MainThread - botocore.retryhandler - DEBUG - Retry needed, action of: 0.084531660132
2018-05-16 16:02:30,161 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.084531660132 seconds
2018-05-16 16:02:30,248 - MainThread - botocore.hooks - DEBUG - Event request-created.secretsmanager.CreateSecret: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x1022c5a10>>
2018-05-16 16:02:30,248 - MainThread - botocore.hooks - DEBUG - Event choose-signer.secretsmanager.CreateSecret: calling handler <function set_operation_specific_signer at 0x10174a6e0>
2018-05-16 16:02:30,249 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2018-05-16 16:02:30,249 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-amz-json-1.1
host:secretsmanager.us-east-1.amazonaws.com
x-amz-date:20180516T200230Z
x-amz-security-token:<removed>
x-amz-target:secretsmanager.CreateSecret

content-type;host;x-amz-date;x-amz-security-token;x-amz-target
71550e8dba1fb6f052f3b62b3494da16814fe6e8f46041e097f73a17152b690c
2018-05-16 16:02:30,249 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20180516T200230Z
20180516/us-east-1/secretsmanager/aws4_request
8906052c89b70c3d4aec24614bb19b68b791b42985d7fd05870428fa032d2caf
2018-05-16 16:02:30,249 - MainThread - botocore.auth - DEBUG - Signature:
b774233d1cdb41f5724f957b5969500b113336e15aa6552a10505b2e06301a6c
2018-05-16 16:02:30,249 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2018-05-16 16:02:30,250 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (4): secretsmanager.us-east-1.amazonaws.com
2018-05-16 16:02:30,332 - MainThread - botocore.endpoint - DEBUG - ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/endpoint.py", line 222, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
2018-05-16 16:02:30,332 - MainThread - botocore.hooks - DEBUG - Event needs-retry.secretsmanager.CreateSecret: calling handler <botocore.retryhandler.RetryHandler object at 0x1023b0250>
2018-05-16 16:02:30,332 - MainThread - botocore.retryhandler - DEBUG - retry needed, retryable exception caught: EOF occurred in violation of protocol (_ssl.c:590)
Traceback (most recent call last):
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
2018-05-16 16:02:30,333 - MainThread - botocore.retryhandler - DEBUG - Retry needed, action of: 0.39363622315
2018-05-16 16:02:30,333 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.39363622315 seconds
2018-05-16 16:02:30,728 - MainThread - botocore.hooks - DEBUG - Event request-created.secretsmanager.CreateSecret: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x1022c5a10>>
2018-05-16 16:02:30,728 - MainThread - botocore.hooks - DEBUG - Event choose-signer.secretsmanager.CreateSecret: calling handler <function set_operation_specific_signer at 0x10174a6e0>
2018-05-16 16:02:30,729 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2018-05-16 16:02:30,729 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-amz-json-1.1
host:secretsmanager.us-east-1.amazonaws.com
x-amz-date:20180516T200230Z
x-amz-security-token:<removed>
x-amz-target:secretsmanager.CreateSecret

content-type;host;x-amz-date;x-amz-security-token;x-amz-target
71550e8dba1fb6f052f3b62b3494da16814fe6e8f46041e097f73a17152b690c
2018-05-16 16:02:30,729 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20180516T200230Z
20180516/us-east-1/secretsmanager/aws4_request
8906052c89b70c3d4aec24614bb19b68b791b42985d7fd05870428fa032d2caf
2018-05-16 16:02:30,729 - MainThread - botocore.auth - DEBUG - Signature:
b774233d1cdb41f5724f957b5969500b113336e15aa6552a10505b2e06301a6c
2018-05-16 16:02:30,730 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2018-05-16 16:02:30,730 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (5): secretsmanager.us-east-1.amazonaws.com
2018-05-16 16:02:30,810 - MainThread - botocore.endpoint - DEBUG - ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/endpoint.py", line 222, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
2018-05-16 16:02:30,811 - MainThread - botocore.hooks - DEBUG - Event needs-retry.secretsmanager.CreateSecret: calling handler <botocore.retryhandler.RetryHandler object at 0x1023b0250>
2018-05-16 16:02:30,811 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/awscli/clidriver.py", line 208, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/awscli/clidriver.py", line 345, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/awscli/clidriver.py", line 517, in __call__
    call_parameters, parsed_globals)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/awscli/clidriver.py", line 637, in invoke
    client, operation_name, parameters, parsed_globals)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/awscli/clidriver.py", line 649, in _make_client_call
    **parameters)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/endpoint.py", line 148, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/endpoint.py", line 177, in _send_request
    success_response, exception):
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/endpoint.py", line 273, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/rwallner/Envs/awssso/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
2018-05-16 16:02:30,814 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

EOF occurred in violation of protocol (_ssl.c:590)
➜  ecs-testing
➜  python
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 0.9.8zh 14 Jan 2016'

aws --version
aws-cli/1.15.22 Python/2.7.10 Darwin/16.7.0 botocore/1.10.22
```

no proxy, can execute other aws cli commands without any issue.

**Comment by joguSD** [comment]
This API might require newer versions of openssl due to TLS requirements. Try installing a newer version of openssl & python using something like [brew](https://brew.sh/).

**Comment by kyleknap** [comment]
Closing due to inactivity
