### ISSUE TITLE
AWS cognito-idp method does not work with User registered via External Provider in Cognito

### ISSUE THREAD

**Issue by ramitsurana** [aws/aws-cli#3348]
Observing this error:

User is not authorized to get auth details

I am currently using the following method -

```
cognito_client = boto3.client('cognito-idp')
response = cognito_client.initiate_auth(AuthFlow='USER_PASSWORD_AUTH',
```

```
2018-05-30 11:32:09,958 botocore.endpoint [DEBUG] Sending http request: <PreparedRequest [POST]>
2018-05-30 11:32:09,959 botocore.vendored.requests.packages.urllib3.connectionpool [INFO] Starting new HTTPS connection (1): cognito-idp.ap-southeast-1.amazonaws.com
2018-05-30 11:32:15,690 botocore.vendored.requests.packages.urllib3.connectionpool [DEBUG] "POST / HTTP/1.1" 400 91
2018-05-30 11:32:15,692 botocore.parsers [DEBUG] Response headers: {'content-type': 'application/x-amz-json-1.1', 'date': 'Wed, 30 May 2018 06:02:15 GMT', 'x-amzn-errormessage': 'User is not authorized to get auth details.', 'x-amzn-errortype': 'NotAuthorizedException:', 'x-amzn-requestid': '00bb3975-63cf-11e8-bed7-f10627fb8d9d', 'content-length': '91', 'connection': 'keep-alive'}
2018-05-30 11:32:15,692 botocore.parsers [DEBUG] Response body:
b'{"__type":"NotAuthorizedException","message":"User is not authorized to get auth details."}'
2018-05-30 11:32:15,693 botocore.hooks [DEBUG] Event needs-retry.cognito-idp.InitiateAuth: calling handler <botocore.retryhandler.RetryHandler object at 0x7f4336742be0>
2018-05-30 11:32:15,693 botocore.retryhandler [DEBUG] No retry needed.
Traceback (most recent call last):
  File "sample3.py", line 38, in authenticate_user
    'PASSWORD':password})
  File "/home/ramit/.local/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ramit/.local/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NotAuthorizedException: An error occurred (NotAuthorizedException) when calling the InitiateAuth operation: User is not authorized to get auth details.
```

**Comment by kyleknap** [comment]
@ramitsurana I am not too familiar with the various in's and out's of Cognito's API so I'm not too sure why your are getting that response. As stated in our [README](https://github.com/aws/aws-cli#getting-help), I would recommend reaching out to AWS Support, StackOverflow, or the AWS Developer Forums with this question. We try to reserve GitHub issues to CLI bugs and feature requests and you should be able to find someone at one of the resources with the knowledge to help you troubleshoot this issue.

**Comment by jan-wizeline** [comment]
Hi @ramitsurana Did you figure the way out for this problem. I am encountering the same issue as you. I would appreciate any further ideas to move forward.

**Comment by ramitsurana** [comment]
hi @jan-wizeline , It's been a while, I don't recall the fix at the moment, but can you check the settings of the Cognito user pool id once and try changing the permissions given to the users belonging to the pool?
