### ISSUE TITLE
cloudformation package fails if content size gets bigger (Permission denied)

### ISSUE THREAD

**Issue by adrai** [aws/aws-cli#3351]
When calling `aws cloudformation package --template-file app-sam.yaml --s3-bucket my-bucket --output-template-file app-output_sam.yaml --debug`

I get this output:
```
018-05-31 12:38:49,961 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.15.30 Python/2.7.11 Darwin/16.7.0 botocore/1.10.30
2018-05-31 12:38:49,961 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['cloudformation', 'package', '--template-file', 'app-sam.yaml', '--s3-bucket', 'my-bucket', '--output-template-file', 'app-output_sam.yaml', '--debug']
2018-05-31 12:38:49,961 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x10f61e050>
2018-05-31 12:38:49,961 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'dkd'.
2018-05-31 12:38:49,961 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x10efa6a28>
2018-05-31 12:38:49,962 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'dkd'.
2018-05-31 12:38:49,962 - MainThread - botocore.session - DEBUG - Loading variable credentials_file from defaults.
2018-05-31 12:38:49,962 - MainThread - botocore.session - DEBUG - Loading variable config_file from defaults.
2018-05-31 12:38:49,962 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'dkd'.
2018-05-31 12:38:49,962 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_timeout from defaults.
2018-05-31 12:38:49,962 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'dkd'.
2018-05-31 12:38:49,962 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_num_attempts from defaults.
2018-05-31 12:38:49,962 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-05-31 12:38:49,962 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x10f220b18>
2018-05-31 12:38:49,962 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'dkd'.
2018-05-31 12:38:49,963 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'dkd'.
2018-05-31 12:38:49,963 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2018-05-31 12:38:49,965 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/usr/Library/Python/2.7/lib/python/site-packages/botocore/data/cloudformation/2010-05-15/service-2.json
2018-05-31 12:38:49,984 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.cloudformation: calling handler <function register_retries_for_service at 0x10eaec578>
2018-05-31 12:38:49,985 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: cloudformation
2018-05-31 12:38:49,987 - MainThread - botocore.hooks - DEBUG - Event building-command-table.cloudformation: calling handler <function inject_commands at 0x10f12aa28>
2018-05-31 12:38:49,987 - MainThread - botocore.hooks - DEBUG - Event building-command-table.cloudformation: calling handler <function add_waiters at 0x10f6271b8>
2018-05-31 12:38:49,998 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/usr/Library/Python/2.7/lib/python/site-packages/botocore/data/cloudformation/2010-05-15/waiters-2.json
2018-05-31 12:38:50,001 - MainThread - botocore.hooks - DEBUG - Event building-command-table.package: calling handler <function add_waiters at 0x10f6271b8>
2018-05-31 12:38:50,002 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.package.template-file: calling handler <function uri_param at 0x10ee481b8>
2018-05-31 12:38:50,002 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.package: calling handler <awscli.argprocess.ParamShorthandParser object at 0x10f62bd50>
2018-05-31 12:38:50,002 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.package.s3-bucket: calling handler <function uri_param at 0x10ee481b8>
2018-05-31 12:38:50,002 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.package: calling handler <awscli.argprocess.ParamShorthandParser object at 0x10f62bd50>
2018-05-31 12:38:50,002 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.package.kms-key-id: calling handler <function uri_param at 0x10ee481b8>
2018-05-31 12:38:50,002 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.package.s3-prefix: calling handler <function uri_param at 0x10ee481b8>
2018-05-31 12:38:50,003 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.package.output-template-file: calling handler <function uri_param at 0x10ee481b8>
2018-05-31 12:38:50,003 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.package: calling handler <awscli.argprocess.ParamShorthandParser object at 0x10f62bd50>
2018-05-31 12:38:50,003 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.package.use-json: calling handler <function uri_param at 0x10ee481b8>
2018-05-31 12:38:50,003 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.package: calling handler <awscli.argprocess.ParamShorthandParser object at 0x10f62bd50>
2018-05-31 12:38:50,003 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.package.force-upload: calling handler <function uri_param at 0x10ee481b8>
2018-05-31 12:38:50,003 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.package: calling handler <awscli.argprocess.ParamShorthandParser object at 0x10f62bd50>
2018-05-31 12:38:50,003 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'dkd'.
2018-05-31 12:38:50,003 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'dkd'.
2018-05-31 12:38:50,003 - MainThread - botocore.session - DEBUG - Loading variable region from config file with value 'eu-central-1'.
2018-05-31 12:38:50,004 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'dkd'.
2018-05-31 12:38:50,004 - MainThread - botocore.session - DEBUG - Loading variable ca_bundle from defaults.
2018-05-31 12:38:50,004 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'dkd'.
2018-05-31 12:38:50,004 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2018-05-31 12:38:50,004 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2018-05-31 12:38:50,004 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2018-05-31 12:38:50,004 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2018-05-31 12:38:50,004 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2018-05-31 12:38:50,005 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/usr/Library/Python/2.7/lib/python/site-packages/botocore/data/endpoints.json
2018-05-31 12:38:50,032 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'dkd'.
2018-05-31 12:38:50,032 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x10eae6cf8>
2018-05-31 12:38:50,034 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/usr/Library/Python/2.7/lib/python/site-packages/botocore/data/s3/2006-03-01/service-2.json
2018-05-31 12:38:50,097 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x10ea94d70>
2018-05-31 12:38:50,098 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x10ea94b90>
2018-05-31 12:38:50,098 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2018-05-31 12:38:50,175 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2018-05-31 12:38:50,177 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2018-05-31 12:38:50,177 - MainThread - botocore.client - DEBUG - Defaulting to S3 virtual host style addressing with path style addressing fallback.
2018-05-31 12:39:21,888 - MainThread - awscli.customizations.cloudformation.artifact_exporter - DEBUG - Unable to export
Traceback (most recent call last):
  File "/Users/usr/Library/Python/2.7/lib/python/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 253, in export
    self.do_export(resource_id, resource_dict, parent_dir)
  File "/Users/usr/Library/Python/2.7/lib/python/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 274, in do_export
    parent_dir, self.uploader)
  File "/Users/usr/Library/Python/2.7/lib/python/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 142, in upload_local_artifacts
    return zip_and_upload(local_path, uploader)
  File "/Users/usr/Library/Python/2.7/lib/python/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 156, in zip_and_upload
    return uploader.upload_with_dedup(zipfile)
  File "/Users/usr/Library/Python/2.7/lib/python/site-packages/awscli/customizations/s3uploader.py", line 125, in upload_with_dedup
    filemd5 = self.file_checksum(file_name)
  File "/Users/usr/Library/Python/2.7/lib/python/site-packages/awscli/customizations/s3uploader.py", line 156, in file_checksum
    with open(file_name, "rb") as file_handle:
IOError: [Errno 13] Permission denied: '/var/folders/dr/b24tydtn4dq1qfzd2347f_400000gn/T/data-ddd185b6f09846f6a5a028b269ea946e.zip'
2018-05-31 12:39:21,938 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/Users/usr/Library/Python/2.7/lib/python/site-packages/awscli/clidriver.py", line 208, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/Users/usr/Library/Python/2.7/lib/python/site-packages/awscli/clidriver.py", line 345, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/Users/usr/Library/Python/2.7/lib/python/site-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/Users/usr/Library/Python/2.7/lib/python/site-packages/awscli/customizations/cloudformation/package.py", line 138, in _run_main
    exported_str = self._export(template_path, use_json)
  File "/Users/usr/Library/Python/2.7/lib/python/site-packages/awscli/customizations/cloudformation/package.py", line 154, in _export
    exported_template = template.export()
  File "/Users/usr/Library/Python/2.7/lib/python/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 455, in export
    exporter.export(resource_id, resource_dict, self.template_dir)
  File "/Users/usr/Library/Python/2.7/lib/python/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 261, in export
    ex=ex)
ExportFailedError: Unable to upload artifact None referenced by CodeUri parameter of MyLambdaFn resource.
[Errno 13] Permission denied: '/var/folders/dr/b24tydtn4dq1qfzd2347f_400000gn/T/data-ddd185b6f09846f6a5a028b269ea946e.zip'
2018-05-31 12:39:21,943 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Unable to upload artifact None referenced by CodeUri parameter of MyLambdaFn resource.
[Errno 13] Permission denied: '/var/folders/dr/b24tydtn4dq1qfzd2347f_400000gn/T/data-ddd185b6f09846f6a5a028b269ea946e.zip'
```

If I remove some node modules... It works...

Any suggestion what could cause the problem?

**Comment by adrai** [comment]
Works on an other machine...
