### ISSUE TITLE
aws cli cp hangs after a few GB downloading from a public data set

### ISSUE THREAD

**Issue by duanegris** [aws/aws-cli#3400]
Hi,

I unsuccessfully tried several times to download the 5-gram dataset from the public dataset repository at amazon. This is a 90 GB file. (Previously, i have been able to transfer a 3 GB file (3-gram)).

I am running 
aws s3 cp s3://datasets.elasticmapreduce/ngrams/books/20090715/eng-us-all/5gram/data ./5gram

which hangs after it downloaded 4.7GB in about 1h30.
I have checked i have enough disk space to hold the whole file, and the file destination is not a NFS-mounted disk.

At my last try, i logged  the stderr output with --debug, redirecting stderr to a file.
 
Here is the start (with version of was cli)  of the debug log, and the end where 1 of the error (Traceback)  appear.
There is a total of 19 such Traceback lines, i guess one per thread (this is a 12 core computer). 

===== start of debug output ========
2018-06-22 14:30:37,835 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.11.13 Python/3.5.2 Linux/4.4.0-128-generic botocore/1.4.70
2018-06-22 14:30:37,836 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', 's3', 'cp', 's3://datasets.elasticmapreduce/ngrams/books/20090715/eng-us-all/5gram/data', './5gram']

[....]

2018-06-22 15:41:29,509 - Thread-13 - s3transfer.tasks - DEBUG - IOWriteTask(transfer_id=0, {'offset': 4920967168}) about to wait for the following futures []
2018-06-22 15:41:29,509 - Thread-13 - s3transfer.tasks - DEBUG - IOWriteTask(transfer_id=0, {'offset': 4920967168}) done waiting for dependent futures
2018-06-22 15:41:29,509 - Thread-13 - s3transfer.tasks - DEBUG - Executing task IOWriteTask(transfer_id=0, {'offset': 4920967168}) with kwargs {'fileobj': <s3transfer.utils.DeferredOpenFile object at 0x7f76647d45c0>, 'offset': 4920967168}
2018-06-22 15:41:29,509 - Thread-13 - s3transfer.utils - DEBUG - Releasing acquire 0/None
2018-06-22 15:41:29,656 - Thread-4 - s3transfer.futures - DEBUG - Submitting task IOWriteTask(transfer_id=0, {'offset': 5041815552}) to executor <s3transfer.futures.BoundedExecutor object at 0x7f76650b36d8> for transfer request: 0.
2018-06-22 15:41:29,656 - Thread-4 - s3transfer.utils - DEBUG - Acquiring 0
2018-06-22 15:41:29,657 - Thread-1 - awscli.customizations.s3.results - DEBUG - Error processing result ProgressResult(transfer_type='download', src='s3://datasets.elasticmapreduce/ngrams/books/20090715/eng-us-all/5gram/data', dest='./5gram', bytes_transferred=262144, total_transfer_size=96846205123) with handler <awscli.customizations.s3.results.ResultPrinter object at 0x7f76650b3908>: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/awscli/customizations/s3/results.py", line 582, in _process_result
    result_handler(result)
  File "/usr/lib/python3/dist-packages/awscli/customizations/s3/results.py", line 393, in __call__
    result=result)
  File "/usr/lib/python3/dist-packages/awscli/customizations/s3/results.py", line 502, in _print_progress
    self._print_to_out_file(progress_statement)
  File "/usr/lib/python3/dist-packages/awscli/customizations/s3/results.py", line 522, in _print_to_out_file
    uni_print(statement, self._out_file)
  File "/usr/lib/python3/dist-packages/awscli/customizations/s3/utils.py", line 284, in uni_print
    out_file.write(statement)
OSError: [Errno 5] Input/output error
2018-06-22 15:41:29,658 - Thread-13 - s3transfer.tasks - DEBUG - IOWriteTask(transfer_id=0, {'offset': 5041815552}) about to wait for the following futures []
2018-06-22 15:41:29,658 - Thread-13 - s3transfer.tasks - DEBUG - IOWriteTask(transfer_id=0, {'offset': 5041815552}) done waiting for dependent futures
2018-06-22 15:41:29,658 - Thread-13 - s3transfer.tasks - DEBUG - Executing task IOWriteTask(transfer_id=0, {'offset': 5041815552}) with kwargs {'fileobj': <s3transfer.utils.DeferredOpenFile object at 0x7f76647d45c0>, 'offset': 5041815552}
2018-06-22 15:41:29,658 - Thread-13 - s3transfer.utils - DEBUG - Releasing acquire 0/None
================ end of file =================

**Comment by JordonPhillips** [comment]
What operating system and file system are you using?

**Comment by duanegris** [comment]
I am using a Linux OS (Ubuntu 16.04) and writing on an ext4 file system.
The directory i am writing to is mounted directly onto an IDE disk
/dev/sda1 on / type ext4 (rw,relatime,errors=remount-ro,data=ordered)

**Comment by zeniri** [comment]
Do you have enough permissions to write over the disk. I had an the same issue of hanging with the s3 bucket but wasn't able to do the same. I changed the permissions to write i.e. root and it solved my issue. 

The other errors as the  **[Errno 5] Input/output error** means there maybe bad sectors in the disk for checking and getting sure of it use **fsck -c /dev/sda1** for sda1. Linux fsck simply marks such blocks as unusable in the current file system.

You could try switching to the pip version of aws-cli if you haven't done it still. I founded it at #3073.

$ aws --version
aws-cli/1.14.19 Python/2.7.12 Linux/4.4.0-1013-aws botocore/1.8.2

**Comment by justnance** [comment]
@zeniri - Thanks for the post.  
@duanegris - please reply again if this is still an issue.
