### ISSUE TITLE
Doesn't handle ini files with UTF-8 Byte Order Mark (BOM)

### ISSUE THREAD

**Issue by MetalMichael** [aws/aws-cli#3419]
**System:** Windows 10 Pro N x64
**CLI Version:** aws-cli/1.15.48 Python/2.7.14 Windows/10 botocore/1.10.48

### Observed Result:
If ~/.aws/config or ~/aws/credentials are encoded with UTF-8-BOM then a ConfigParseError is given when running aws cli.

```
Traceback (most recent call last):
  File "C:\Python27\Scripts\aws.cmd", line 59, in <module>
    sys.exit(main())
  File "C:\Python27\Scripts\aws.cmd", line 55, in main
    return awscli.clidriver.main()
  File "C:\Users\Michael\AppData\Roaming\Python\Python27\site-packages\awscli\clidriver.py", line 58, in main
    driver = create_clidriver()
  File "C:\Users\Michael\AppData\Roaming\Python\Python27\site-packages\awscli\clidriver.py", line 68, in create_clidriver
    load_plugins(session.full_config.get('plugins', {}),
  File "C:\Users\Michael\AppData\Roaming\Python\Python27\site-packages\botocore\session.py", line 400, in full_config
    self._config = botocore.configloader.load_config(config_file)
  File "C:\Users\Michael\AppData\Roaming\Python\Python27\site-packages\botocore\configloader.py", line 106, in load_config
    parsed = raw_config_parse(config_filename)
  File "C:\Users\Michael\AppData\Roaming\Python\Python27\site-packages\botocore\configloader.py", line 152, in raw_config_parse
    path=_unicode_path(path))
botocore.exceptions.ConfigParseError: Unable to parse config file: C:\Users\Michael/.aws/config
```

Works as expected when using the same file with UTF-8 encoding, without byte order mark.

### Expected Result:
aws-cli works regularly, and handles UTF-8-BOM encoded files.

Also likely the cause of issue #1778

**Comment by JordonPhillips** [comment]
Traditionally what you would need to do is read the file using `utf-8-sig` as the encoding, but this wouldn't be a safe assumption for us to make as we would then be skipping out on the web of default encoding paths that python takes when you just call plain `open`. While we can't change the default encoding, we might be able to try it as a backup if normal reading fails.
