### ISSUE TITLE
AWS cli explicit --profile not overriding the environment variable AWS_DEFAULT_PROFILE

### ISSUE THREAD

**Issue by surajpokhriyal25** [aws/aws-cli#3431]
**What is the Issue ?**
Command switch passed to AWS cli at runtime is not overriding the AWS_DEFAULT_PROFILE environment variable set in my environment.

**Issues Reproduced at my end :** 
My environment shows:
AWS_DEFAULT_PROFILE=test
AWS_PROFILE=default
AWS_REGION=us-west-2

When I explicitly pass the profile it still tries to pick the test profile, But in AWS cli I am explicitly mentioning --profile default. 

```
aws s3 ls --profile default                                                                                                                                                                         Fri Jul  6 15:06:30 2018
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/local/aws/lib/python3.6/site-packages/awscli/clidriver.py", line 59, in main
    rc = driver.main()
  File "/usr/local/aws/lib/python3.6/site-packages/awscli/clidriver.py", line 194, in main
    command_table = self._get_command_table()
  File "/usr/local/aws/lib/python3.6/site-packages/awscli/clidriver.py", line 103, in _get_command_table
    self._command_table = self._build_command_table()
  File "/usr/local/aws/lib/python3.6/site-packages/awscli/clidriver.py", line 123, in _build_command_table
    command_object=self)
  File "/usr/local/aws/lib/python3.6/site-packages/botocore/session.py", line 719, in emit
    return self._events.emit(event_name, **kwargs)
  File "/usr/local/aws/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/aws/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/aws/lib/python3.6/site-packages/awscli/customizations/preview.py", line 69, in mark_as_preview
    service_name=original_command.service_model.service_name,
  File "/usr/local/aws/lib/python3.6/site-packages/awscli/clidriver.py", line 315, in service_model
    return self._get_service_model()
  File "/usr/local/aws/lib/python3.6/site-packages/awscli/clidriver.py", line 332, in _get_service_model
    api_version = self.session.get_config_variable('api_versions').get(
  File "/usr/local/aws/lib/python3.6/site-packages/botocore/session.py", line 279, in get_config_variable
    elif self._found_in_config_file(methods, var_config):
  File "/usr/local/aws/lib/python3.6/site-packages/botocore/session.py", line 306, in _found_in_config_file
    return var_config[0] in self.get_scoped_config()
  File "/usr/local/aws/lib/python3.6/site-packages/botocore/session.py", line 383, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (test) could not be found
```
**What was expected:**
The AWS cli should have overridden the AWS_DEFAULT_PROFILE environment variable. when I pass --profile explicitly.

**Comment by ianbamforth** [comment]
AWS cli is correctly overriding the `AWS_DEFAULT_PROFILE` when it's making calls.  However it looks like it is doing _something_ with `AWS_DEFAULT_PROFILE` first - the error above only occurs when the `AWS_DEFAULT_PROFILE` doesn't exist - if it does exist. it gets overridden correctly.

**Comment by surajpokhriyal25** [comment]
Actually error occurs when AWS_DEFAULT_PROFILE exist but with different profile name value than AWS_PROFILE.
I am using, aws-cli/1.15.52 Python/3.6.5 Darwin/17.6.0 botocore/1.10.51
 
To get rid of the error I have to set AWS_DEFAULT_PROFILE to value of AWS_PROFILE, until then aws command does not work.

**Comment by justnance** [comment]
@surajpokhriyal25 - Thank you for reaching out and your patience. @ianbamforth thank you for adding feedback.  I was not able to reproduce this issue in a test environment and need more information to understand the root cause:
 
 - Are the AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID set as environment variables either as global environment variables or shell variables?
 - Compare and anlayze contents of the following files: 
    - The AWS credentials file – located at ~/.aws/credentials on Linux, macOS, or Unix, or at C:\Users\USERNAME \.aws\credentials on Windows.
    - The CLI configuration file – typically located at ~/.aws/config on Linux, macOS, or Unix, or at C:\Users\USERNAME \.aws\config on Windows. 
-  provide the sanitized output of `aws configure list`
-  is MFA enabled?
-  check if there are two environment variables in the PATH

Initially, it appears the behavior is as expected.  Please check to see if there are two environment variables in the PATH.  I'm looking forward to your reply.

Thanks.

## related resources: 
[Environment Variables - AWS Command Line Interface](https://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html)
[Configuring the AWS CLI - AWS Command Line Interface](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html)
[Configuring the AWS CLI - AWS Command Line Interface - settings and precedence](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#config-settings-and-precedence)
[AWS CLI Configuration Variables — AWS CLI 1.16.10 Command Reference](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html)
[Client is not using AWS_PROFILE correctly · Issue #3304 · aws/aws-cli · GitHub](https://github.com/aws/aws-cli/issues/3304)
