### ISSUE TITLE
CLI picks endpoint regardless of what I set as region

### ISSUE THREAD

**Issue by hbielenia** [aws/aws-cli#3510]
I'm trying to create S3 bucket in `us-east-1` region. [Docs](https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html#examples) say it doesn't need `LocationConstraint` specified. However, CLI appears to pick endpoint for `us-west-2`, resulting in an error.

```
$ aws --version
aws-cli/1.15.81 Python/3.7.0 Linux/4.17.0-1-amd64 botocore/1.10.80

$ aws configure list
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
access_key     ****************A3RQ              env    
secret_key     ****************BCNr              env    
    region                us-east-1              env    AWS_DEFAULT_REGION

$ aws s3api create-bucket --bucket staging-k8s-local-state-store --region us-east-1 --debug                                                                                      
2018-08-17 22:03:20,923 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.15.81 Python/3.7.0 Linux/4.17.0-1-amd64 botocore/1.10.80
2018-08-17 22:03:20,924 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3api', 'create-bucket', '--bucket', 'staging-k8s-local-state-store', '--region', 'us-east-1', '--debug']
2018-08-17 22:03:20,924 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7f060a9beae8>
2018-08-17 22:03:20,924 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-08-17 22:03:20,924 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7f060ae1d268>
2018-08-17 22:03:20,924 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-08-17 22:03:20,924 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f060adcf7b8>
2018-08-17 22:03:20,925 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-08-17 22:03:20,925 - MainThread - botocore.session - DEBUG - Loading variable credentials_file from defaults.
2018-08-17 22:03:20,925 - MainThread - botocore.session - DEBUG - Loading variable config_file from defaults.
2018-08-17 22:03:20,925 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-08-17 22:03:20,925 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_timeout from defaults.
2018-08-17 22:03:20,925 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-08-17 22:03:20,925 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_num_attempts from defaults.
2018-08-17 22:03:20,926 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-08-17 22:03:20,926 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f060abf07b8>
2018-08-17 22:03:20,926 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-08-17 22:03:20,926 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-08-17 22:03:20,926 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2018-08-17 22:03:20,927 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python3.7/site-packages/botocore/data/s3/2006-03-01/service-2.json
2018-08-17 22:03:20,932 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.s3: calling handler <function register_retries_for_service at 0x7f060be9fae8>
2018-08-17 22:03:20,932 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: s3
2018-08-17 22:03:20,934 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3api: calling handler <function add_waiters at 0x7f060a9c4d90>
2018-08-17 22:03:20,940 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python3.7/site-packages/botocore/data/s3/2006-03-01/waiters-2.json
2018-08-17 22:03:20,941 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('acl', <awscli.arguments.CLIArgument object at 0x7f060a6fc5c0>), ('bucket', <awscli.arguments.CLIArgument object at 0x7f060a6fc668>), ('create-bucket-configuration', <awscli.arguments.CLIArgument object at 0x7f060a6fc6a0>), ('grant-full-control', <awscli.arguments.CLIArgument object at 0x7f060a6fc6d8>), ('grant-read', <awscli.arguments.CLIArgument object at 0x7f060a6fc748>), ('grant-read-acp', <awscli.arguments.CLIArgument object at 0x7f060a6fc710>), ('grant-write', <awscli.arguments.CLIArgument object at 0x7f060a6fc780>), ('grant-write-acp', <awscli.arguments.CLIArgument object at 0x7f060a6fc7b8>)])
2018-08-17 22:03:20,942 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.create-bucket: calling handler <function add_streaming_output_arg at 0x7f060a9c40d0>
2018-08-17 22:03:20,942 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.create-bucket: calling handler <function add_cli_input_json at 0x7f060adcfd08>
2018-08-17 22:03:20,942 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.create-bucket: calling handler <function unify_paging_params at 0x7f060cbc9d90>
2018-08-17 22:03:20,948 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python3.7/site-packages/botocore/data/s3/2006-03-01/paginators-1.json
2018-08-17 22:03:20,949 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.create-bucket: calling handler <function add_generate_skeleton at 0x7f060cc2cbf8>
2018-08-17 22:03:20,949 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.create-bucket: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7f060a6fc828>>
2018-08-17 22:03:20,949 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.create-bucket: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f060a6fc860>>
2018-08-17 22:03:20,950 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.acl: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f060a88edd8>
2018-08-17 22:03:20,950 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.bucket: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f060a88edd8>
2018-08-17 22:03:20,950 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.s3.create-bucket: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f060ae76be0>
2018-08-17 22:03:20,951 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'staging-k8s-local-state-store' for parameter "bucket": 'staging-k8s-local-state-store'
2018-08-17 22:03:20,951 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.create-bucket-configuration: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f060a88edd8>
2018-08-17 22:03:20,951 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.grant-full-control: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f060a88edd8>
2018-08-17 22:03:20,951 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.grant-read: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f060a88edd8>
2018-08-17 22:03:20,951 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.grant-read-acp: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f060a88edd8>
2018-08-17 22:03:20,951 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.grant-write: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f060a88edd8>
2018-08-17 22:03:20,951 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.grant-write-acp: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f060a88edd8>
2018-08-17 22:03:20,952 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f060a88edd8>
2018-08-17 22:03:20,952 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f060a88edd8>
2018-08-17 22:03:20,952 - MainThread - botocore.hooks - DEBUG - Event calling-command.s3api.create-bucket: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7f060a6fc828>>
2018-08-17 22:03:20,952 - MainThread - botocore.hooks - DEBUG - Event calling-command.s3api.create-bucket: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f060a6fc860>>
2018-08-17 22:03:20,952 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-08-17 22:03:20,952 - MainThread - botocore.session - DEBUG - Loading variable ca_bundle from defaults.
2018-08-17 22:03:20,952 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-08-17 22:03:20,952 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2018-08-17 22:03:20,953 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2018-08-17 22:03:20,953 - MainThread - botocore.credentials - INFO - Found credentials in environment variables.
2018-08-17 22:03:20,953 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python3.7/site-packages/botocore/data/endpoints.json
2018-08-17 22:03:20,956 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-08-17 22:03:20,957 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f060bf08f28>
2018-08-17 22:03:20,960 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f060becea60>
2018-08-17 22:03:20,960 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f060bece840>
2018-08-17 22:03:20,961 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2018-08-17 22:03:20,964 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2018-08-17 22:03:20,965 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2018-08-17 22:03:20,965 - MainThread - botocore.client - DEBUG - Defaulting to S3 virtual host style addressing with path style addressing fallback.
2018-08-17 22:03:20,966 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.CreateBucket: calling handler <function validate_bucket_name at 0x7f060be9f840>
2018-08-17 22:03:20,966 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.CreateBucket: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x7f060a67ad30>>
2018-08-17 22:03:20,966 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.CreateBucket: calling handler <function generate_idempotent_uuid at 0x7f060be9f488>
2018-08-17 22:03:20,966 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.CreateBucket: calling handler <function add_expect_header at 0x7f060be9fd08>
2018-08-17 22:03:20,967 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.CreateBucket: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x7f060a67ad30>>
2018-08-17 22:03:20,967 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=CreateBucket) (verify_ssl=True) with params: {'url_path': '/staging-k8s-local-state-store', 'query_string': {}, 'method': 'PUT', 'headers': {'User-Agent': 'aws-cli/1.15.81 Python/3.7.0 Linux/4.17.0-1-amd64 botocore/1.10.80'}, 'body': b'', 'url': 'https://s3.amazonaws.com/staging-k8s-local-state-store', 'context': {'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x7f060a67ab00>, 'has_streaming_input': False, 'auth_type': None, 'signing': {'bucket': 'staging-k8s-local-state-store'}}}
2018-08-17 22:03:20,967 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.CreateBucket: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f060a67aa90>>
2018-08-17 22:03:20,967 - MainThread - botocore.hooks - DEBUG - Event choose-signer.s3.CreateBucket: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x7f060a716128>>
2018-08-17 22:03:20,967 - MainThread - botocore.hooks - DEBUG - Event choose-signer.s3.CreateBucket: calling handler <function set_operation_specific_signer at 0x7f060be9f378>
2018-08-17 22:03:20,967 - MainThread - botocore.hooks - DEBUG - Event before-sign.s3.CreateBucket: calling handler <function fix_s3_host at 0x7f060c044d08>
2018-08-17 22:03:20,967 - MainThread - botocore.utils - DEBUG - Checking for DNS compatible bucket for: https://s3.amazonaws.com/staging-k8s-local-state-store
2018-08-17 22:03:20,967 - MainThread - botocore.utils - DEBUG - URI updated to: https://staging-k8s-local-state-store.s3.amazonaws.com/
2018-08-17 22:03:20,968 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2018-08-17 22:03:20,968 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
PUT
/

host:staging-k8s-local-state-store.s3.amazonaws.com
x-amz-content-sha256:<redacted>
x-amz-date:20180817T220320Z

host;x-amz-content-sha256;x-amz-date
<redacted>
2018-08-17 22:03:20,968 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20180817T220320Z
20180817/us-east-1/s3/aws4_request
<redacted>
2018-08-17 22:03:20,968 - MainThread - botocore.auth - DEBUG - Signature:
<redacted>
2018-08-17 22:03:20,972 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [PUT]>
2018-08-17 22:03:20,973 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): staging-k8s-local-state-store.s3.amazonaws.com
2018-08-17 22:03:21,854 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "PUT / HTTP/1.1" 400 None
2018-08-17 22:03:21,856 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amz-request-id': 'CC9E4752E882A517', 'x-amz-id-2': '<redacted>', 'content-type': 'application/xml', 'transfer-encoding': 'chunked', 'date': 'Fri, 17 Aug 2018 22:03:21 GMT', 'connection': 'close', 'server': 'AmazonS3'}
2018-08-17 22:03:21,856 - MainThread - botocore.parsers - DEBUG - Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region \'us-east-1\' is wrong; expecting \'us-west-2\'</Message><Region>us-west-2</Region><RequestId>CC9E4752E882A517</RequestId><HostId><redacted></HostId></Error>'
2018-08-17 22:03:21,857 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.CreateBucket: calling handler <botocore.retryhandler.RetryHandler object at 0x7f060a88e550>
2018-08-17 22:03:21,857 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2018-08-17 22:03:21,857 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.CreateBucket: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x7f060a67ad30>>
2018-08-17 22:03:21,857 - MainThread - botocore.utils - DEBUG - S3 client configured for region us-east-1 but the bucket staging-k8s-local-state-store is in region us-west-2; Please configure the proper region to avoid multiple unnecessary redirects and signing attempts.
2018-08-17 22:03:21,858 - MainThread - botocore.utils - DEBUG - Updating URI from https://s3.amazonaws.com/staging-k8s-local-state-store to https://s3.us-west-2.amazonaws.com/staging-k8s-local-state-store
2018-08-17 22:03:21,858 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0 seconds
2018-08-17 22:03:21,858 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.CreateBucket: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f060a67aa90>>
2018-08-17 22:03:21,858 - MainThread - botocore.hooks - DEBUG - Event choose-signer.s3.CreateBucket: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x7f060a716128>>
2018-08-17 22:03:21,858 - MainThread - botocore.hooks - DEBUG - Event choose-signer.s3.CreateBucket: calling handler <function set_operation_specific_signer at 0x7f060be9f378>
2018-08-17 22:03:21,859 - MainThread - botocore.hooks - DEBUG - Event before-sign.s3.CreateBucket: calling handler <function fix_s3_host at 0x7f060c044d08>
2018-08-17 22:03:21,859 - MainThread - botocore.utils - DEBUG - Checking for DNS compatible bucket for: https://s3.us-west-2.amazonaws.com/staging-k8s-local-state-store
2018-08-17 22:03:21,859 - MainThread - botocore.utils - DEBUG - URI updated to: https://staging-k8s-local-state-store.s3.us-west-2.amazonaws.com/
2018-08-17 22:03:21,859 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2018-08-17 22:03:21,860 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
PUT
/

host:staging-k8s-local-state-store.s3.us-west-2.amazonaws.com
x-amz-content-sha256:<redacted>
x-amz-date:20180817T220321Z

host;x-amz-content-sha256;x-amz-date
<redacted>
2018-08-17 22:03:21,860 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20180817T220321Z
20180817/us-west-2/s3/aws4_request
<redacted>
2018-08-17 22:03:21,860 - MainThread - botocore.auth - DEBUG - Signature:
<redacted>
2018-08-17 22:03:21,861 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [PUT]>
2018-08-17 22:03:21,861 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): staging-k8s-local-state-store.s3.us-west-2.amazonaws.com
2018-08-17 22:03:22,750 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "PUT / HTTP/1.1" 400 None
2018-08-17 22:03:22,754 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amz-request-id': '<redacted>', 'x-amz-id-2': '<redacted>', 'content-type': 'application/xml', 'transfer-encoding': 'chunked', 'date': 'Fri, 17 Aug 2018 22:03:22 GMT', 'connection': 'close', 'server': 'AmazonS3'}
2018-08-17 22:03:22,755 - MainThread - botocore.parsers - DEBUG - Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>IllegalLocationConstraintException</Code><Message>The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.</Message><RequestId>2FBF129CD364EF87</RequestId><HostId><redacted></HostId></Error>'
2018-08-17 22:03:22,756 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.CreateBucket: calling handler <botocore.retryhandler.RetryHandler object at 0x7f060a88e550>
2018-08-17 22:03:22,756 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2018-08-17 22:03:22,756 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.CreateBucket: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x7f060a67ad30>>
2018-08-17 22:03:22,757 - MainThread - botocore.utils - DEBUG - S3 request was previously redirected, not redirecting.
2018-08-17 22:03:22,757 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.CreateBucket: calling handler <function enhance_error_msg at 0x7f060a9be6a8>
2018-08-17 22:03:22,762 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/awscli/clidriver.py", line 208, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python3.7/site-packages/awscli/clidriver.py", line 345, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python3.7/site-packages/awscli/clidriver.py", line 517, in __call__
    call_parameters, parsed_globals)
  File "/usr/local/lib/python3.7/site-packages/awscli/clidriver.py", line 637, in invoke
    client, operation_name, parameters, parsed_globals)
  File "/usr/local/lib/python3.7/site-packages/awscli/clidriver.py", line 649, in _make_client_call
    **parameters)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.
2018-08-17 22:03:22,764 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.
```

**Comment by hbielenia** [comment]
Actually this was due to too generic name I picked. Though the error totally didn't point to that.
