### ISSUE TITLE
ImportError: No module named concurrent.futures

### ISSUE THREAD

**Issue by rene00** [aws/aws-cli#3517]
awscli raises `ImportError: No module named concurrent.futures` when `pip` installed on Ubuntu 14.04 with python 2.7.

```
# lsb_release -d
Description:    Ubuntu 14.04.5 LTS

# python --version
Python 2.7.6

# pip install awscli
Downloading/unpacking awscli
  Downloading awscli-1.15.84-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.10,<=3.13 in /usr/lib/python2.7/dist-packages (from awscli)
Requirement already satisfied (use --upgrade to upgrade): docutils>=0.10 in /usr/local/lib/python2.7/dist-packages (from awscli)
Requirement already satisfied (use --upgrade to upgrade): rsa>=3.1.2,<=3.5.0 in /usr/local/lib/python2.7/dist-packages (from awscli)
Requirement already satisfied (use --upgrade to upgrade): s3transfer>=0.1.12,<0.2.0 in /usr/local/lib/python2.7/dist-packages (from awscli)
Downloading/unpacking botocore==1.10.83 (from awscli)
  Downloading botocore-1.10.83-py2.py3-none-any.whl (4.5MB): 4.5MB downloaded
Requirement already satisfied (use --upgrade to upgrade): colorama>=0.2.5,<=0.3.9 in /usr/lib/python2.7/dist-packages (from awscli)
Requirement already satisfied (use --upgrade to upgrade): jmespath>=0.7.1,<1.0.0 in /usr/local/lib/python2.7/dist-packages (from botocore==1.10.83->awscli)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil>=2.1,<3.0.0 in /usr/local/lib/python2.7/dist-packages (from botocore==1.10.83->awscli)
Installing collected packages: awscli, botocore
  Found existing installation: botocore 1.10.81
    Uninstalling botocore:
      Successfully uninstalled botocore
Successfully installed awscli botocore
Cleaning up...

# aws
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 58, in main
    driver = create_clidriver()
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 69, in create_clidriver
    event_hooks=emitter)
  File "/usr/local/lib/python2.7/dist-packages/awscli/plugin.py", line 45, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/usr/local/lib/python2.7/dist-packages/awscli/plugin.py", line 62, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "/usr/local/lib/python2.7/dist-packages/awscli/handlers.py", line 27, in <module>
    from awscli.customizations.cloudformation import initialize as cloudformation_init
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/cloudformation/__init__.py", line 13, in <module>
    from awscli.customizations.cloudformation.package import PackageCommand
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/cloudformation/package.py", line 26, in <module>
    from awscli.customizations.s3uploader import S3Uploader
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/s3uploader.py", line 22, in <module>
    from s3transfer.manager import TransferManager
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/__init__.py", line 134, in <module>
    import concurrent.futures
ImportError: No module named concurrent.futures
```

I can confirm `s3transfer==0.1.13` is installed though `futures` is not.

```
# pip freeze | egrep "(s3transfer)|(futures)"
s3transfer==0.1.13
# 
```

Looking at https://github.com/boto/s3transfer/blob/0.1.13/setup.py#L18-L21, why doesn't `futures` get installed?

A temporary solution on trusty is to install the `python-concurrent.futures` package with `apt`.

**Comment by rene00** [comment]
The fact I'm seeing this:

```
Requirement already satisfied (use --upgrade to upgrade): s3transfer>=0.1.12,<0.2.0 in /usr/local/lib/python2.7/dist-packages (from awscli)
```

suggests to me that our build process is doing something funky with s3transfer which isn't installing futures.

I'm going to close this issue, sorry for the noise.

**Comment by jorgeorpinel** [comment]
This is happening today on macOS built-in Python 2.7.10
