### ISSUE TITLE
Unable to run awsebcli because of outdated botocore on python 3.7.0

### ISSUE THREAD

**Issue by mronoffon** [aws/aws-cli#3557]
I just installed a fix for the "requests 2.18.4 has requirement urllib3<1.23,>=1.21.1, but you'll have urllib3 1.23 which is incompatible.", but now can't run awsebcli because of outdated 'botocore<1.12" dependency. Downgrade, at this point, is not an option.

root@dev:/usr/local/lib/python3.7/site-packages# eb
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
ws.require(__requires__)
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 892, in require
needed = self.resolve(parse_requirements(requirements))
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (botocore 1.12.1 (/usr/local/lib/python3.7/site-packages), Requirement.parse('botocore<1.12'), {'awsebcli'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/bin/eb", line 6, in <module>
from pkg_resources import load_entry_point
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3088, in <module>
@_call_aside
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
f(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 576, in _build_master
return cls._build_from_requirements(__requires__)
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
dists = ws.resolve(reqs, Environment())
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 778, in resolve
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'botocore<1.12' distribution was not found and is required by awsebcli

specs --

FreeBSD 11.2-RELEASE-p2
Python 3.7.0

Thanks in advance

**Comment by rahulrajaram** [comment]
@mronoffon Which version of `awsebcli` are you using? `awsebcli==3.14.6` (which was released on the night of the 10th) permits `botocore>=1.12`, so upgrading the EBCLI should solve your problem.

**Comment by justnance** [comment]
Also closely related to [Broken elastic beasntalk deploy in latest update · Issue #3550 · aws/aws-cli · GitHub](https://github.com/aws/aws-cli/issues/3550).

**Comment by matschaffer** [comment]
I opened https://github.com/aws/aws-cli/issues/5457 as the latest version of this issue
