### ISSUE TITLE
JSON Output from console cannot be used as input for cli

### ISSUE THREAD

**Issue by FredeJ** [aws/aws-cli#3622]
As new user learning ECS and AWS in general, I started playing around with the console first, to get a feel for how things worked. I got my application up and running in ECS and all is well.

Now I would like to automate the deployment within my deployment pipeline. My immediate thought would be, that I could simply take my current task definitions and select the JSON tab to get the JSON representation of the task. I would then expect to feed this JSON representation directly into the cli to automate my deployment.

However it seems that the generated JSON from the console is not in the expected format of the CLI. I'm not sure who shoulders that responsibility, so I'm just posting it here for now - maybe I've misunderstood something :)

I've boiled my task definition down to this:
```
{
    "executionRoleArn": "",
    "containerDefinitions": [
      {
        "dnsSearchDomains": null,
        "logConfiguration": null,
        "entryPoint": [
          "./docker-entrypoint.sh"
        ],
        "portMappings": [
          {
            "hostPort": 80,
            "protocol": "tcp",
            "containerPort": 8000
          }
        ],
        "command": [],
        "linuxParameters": null,
        "cpu": 0,
        "ulimits": null,
        "dnsServers": null,
        "mountPoints": [],
        "workingDirectory": null,
        "dockerSecurityOptions": null,
        "memory": 500,
        "memoryReservation": null,
        "volumesFrom": [],
        "disableNetworking": null,
        "interactive": null,
        "healthCheck": null,
        "essential": true,
        "links": null,
        "hostname": null,
        "extraHosts": null,
        "pseudoTerminal": null,
        "user": null,
        "readonlyRootFilesystem": null,
        "dockerLabels": null,
        "systemControls": null,
        "privileged": null,
        "name": "aws cli"
      }
    ],
    "placementConstraints": [],
    "memory": "500",
    "taskRoleArn": "arn:aws:iam::0987654321:role/ecsTaskExecutionRole",
    "compatibilities": [
      "EC2"
    ],
    "taskDefinitionArn": "",
    "family": "aws cli",
    "requiresAttributes": [
      {
        "targetId": null,
        "targetType": null,
        "value": null,
        "name": "com.amazonaws.ecs.capability.task-iam-role"
      }
    ],
    "requiresCompatibilities": [
      "EC2"
    ],
    "networkMode": null,
    "cpu": null,
    "revision": 24,
    "status": "ACTIVE",
    "volumes": []
  }
```

The output of the register-task-definition function with debug is this:
```
$ aws ecs register-task-definition --cli-input-json file://aws-cli-json.json --debug
2018-10-02 23:48:39,216 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.16.18 Python/3.6.4 Darwin/18.0.0 botocore/1.12.8
2018-10-02 23:48:39,217 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['ecs', 'register-task-definition', '--cli-input-json', 'file://aws-cli-json.json', '--debug']
2018-10-02 23:48:39,218 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x103612e18>
2018-10-02 23:48:39,218 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-10-02 23:48:39,218 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x1030c0d08>
2018-10-02 23:48:39,218 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-10-02 23:48:39,219 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x103114bf8>
2018-10-02 23:48:39,220 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-10-02 23:48:39,220 - MainThread - botocore.session - DEBUG - Loading variable credentials_file from defaults.
2018-10-02 23:48:39,220 - MainThread - botocore.session - DEBUG - Loading variable config_file from defaults.
2018-10-02 23:48:39,220 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-10-02 23:48:39,220 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_timeout from defaults.
2018-10-02 23:48:39,220 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-10-02 23:48:39,221 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_num_attempts from defaults.
2018-10-02 23:48:39,237 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-10-02 23:48:39,238 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x103507048>
2018-10-02 23:48:39,238 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-10-02 23:48:39,238 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-10-02 23:48:39,238 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2018-10-02 23:48:39,240 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/frederik/Library/Python/3.6/lib/python/site-packages/botocore/data/ecs/2014-11-13/service-2.json
2018-10-02 23:48:39,246 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.ecs: calling handler <function register_retries_for_service at 0x102cbe488>
2018-10-02 23:48:39,247 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: ecs
2018-10-02 23:48:39,248 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ecs: calling handler <function add_waiters at 0x1036420d0>
2018-10-02 23:48:39,262 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/frederik/Library/Python/3.6/lib/python/site-packages/botocore/data/ecs/2014-11-13/waiters-2.json
2018-10-02 23:48:39,265 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('family', <awscli.arguments.CLIArgument object at 0x10409a748>), ('task-role-arn', <awscli.arguments.CLIArgument object at 0x10409a780>), ('execution-role-arn', <awscli.arguments.CLIArgument object at 0x10409a7b8>), ('network-mode', <awscli.arguments.CLIArgument object at 0x10409a7f0>), ('container-definitions', <awscli.arguments.ListArgument object at 0x10409a828>), ('volumes', <awscli.arguments.ListArgument object at 0x10409a898>), ('placement-constraints', <awscli.arguments.ListArgument object at 0x10409a8d0>), ('requires-compatibilities', <awscli.arguments.ListArgument object at 0x10409a908>), ('cpu', <awscli.arguments.CLIArgument object at 0x10409a978>), ('memory', <awscli.arguments.CLIArgument object at 0x10409a9e8>)])
2018-10-02 23:48:39,265 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ecs.register-task-definition: calling handler <function add_streaming_output_arg at 0x103637158>
2018-10-02 23:48:39,265 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ecs.register-task-definition: calling handler <function add_cli_input_json at 0x10311b158>
2018-10-02 23:48:39,266 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ecs.register-task-definition: calling handler <function unify_paging_params at 0x1035b6378>
2018-10-02 23:48:39,279 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/frederik/Library/Python/3.6/lib/python/site-packages/botocore/data/ecs/2014-11-13/paginators-1.json
2018-10-02 23:48:39,279 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ecs.register-task-definition: calling handler <function add_generate_skeleton at 0x103598268>
2018-10-02 23:48:39,281 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ecs.register-task-definition: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x10409aa20>>
2018-10-02 23:48:39,281 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ecs.register-task-definition: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x10409aa90>>
2018-10-02 23:48:39,283 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.family: calling handler <awscli.paramfile.URIArgumentHandler object at 0x101f80cc0>
2018-10-02 23:48:39,283 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.task-role-arn: calling handler <awscli.paramfile.URIArgumentHandler object at 0x101f80cc0>
2018-10-02 23:48:39,284 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.execution-role-arn: calling handler <awscli.paramfile.URIArgumentHandler object at 0x101f80cc0>
2018-10-02 23:48:39,284 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.network-mode: calling handler <awscli.paramfile.URIArgumentHandler object at 0x101f80cc0>
2018-10-02 23:48:39,284 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.container-definitions: calling handler <awscli.paramfile.URIArgumentHandler object at 0x101f80cc0>
2018-10-02 23:48:39,285 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.volumes: calling handler <awscli.paramfile.URIArgumentHandler object at 0x101f80cc0>
2018-10-02 23:48:39,285 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.placement-constraints: calling handler <awscli.paramfile.URIArgumentHandler object at 0x101f80cc0>
2018-10-02 23:48:39,285 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.requires-compatibilities: calling handler <awscli.paramfile.URIArgumentHandler object at 0x101f80cc0>
2018-10-02 23:48:39,285 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.cpu: calling handler <awscli.paramfile.URIArgumentHandler object at 0x101f80cc0>
2018-10-02 23:48:39,286 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.memory: calling handler <awscli.paramfile.URIArgumentHandler object at 0x101f80cc0>
2018-10-02 23:48:39,286 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x101f80cc0>
2018-10-02 23:48:39,287 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x101f80cc0>
2018-10-02 23:48:39,287 - MainThread - botocore.hooks - DEBUG - Event calling-command.ecs.register-task-definition: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x10409aa20>>
2018-10-02 23:48:39,288 - MainThread - botocore.hooks - DEBUG - Event calling-command.ecs.register-task-definition: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x10409aa90>>
2018-10-02 23:48:39,288 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-10-02 23:48:39,289 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-10-02 23:48:39,289 - MainThread - botocore.session - DEBUG - Loading variable region from config file with value 'eu-central-1'.
2018-10-02 23:48:39,289 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-10-02 23:48:39,289 - MainThread - botocore.session - DEBUG - Loading variable ca_bundle from defaults.
2018-10-02 23:48:39,289 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-10-02 23:48:39,289 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2018-10-02 23:48:39,289 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2018-10-02 23:48:39,290 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2018-10-02 23:48:39,290 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2018-10-02 23:48:39,291 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2018-10-02 23:48:39,292 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/frederik/Library/Python/3.6/lib/python/site-packages/botocore/data/endpoints.json
2018-10-02 23:48:39,299 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-10-02 23:48:39,299 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x102ca5950>
2018-10-02 23:48:39,301 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.ecs: calling handler <function add_generate_presigned_url at 0x102c73048>
2018-10-02 23:48:39,301 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2018-10-02 23:48:39,392 - MainThread - botocore.endpoint - DEBUG - Setting ecs timeout as (60, 60)
2018-10-02 23:48:39,394 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: ecs
2018-10-02 23:48:39,396 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.ecs.RegisterTaskDefinition: calling handler <function generate_idempotent_uuid at 0x102cbcd90>
2018-10-02 23:48:39,423 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/Users/frederik/Library/Python/3.6/lib/python/site-packages/awscli/clidriver.py", line 207, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/Users/frederik/Library/Python/3.6/lib/python/site-packages/awscli/clidriver.py", line 344, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/Users/frederik/Library/Python/3.6/lib/python/site-packages/awscli/clidriver.py", line 516, in __call__
    call_parameters, parsed_globals)
  File "/Users/frederik/Library/Python/3.6/lib/python/site-packages/awscli/clidriver.py", line 636, in invoke
    client, operation_name, parameters, parsed_globals)
  File "/Users/frederik/Library/Python/3.6/lib/python/site-packages/awscli/clidriver.py", line 648, in _make_client_call
    **parameters)
  File "/Users/frederik/Library/Python/3.6/lib/python/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/frederik/Library/Python/3.6/lib/python/site-packages/botocore/client.py", line 596, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Users/frederik/Library/Python/3.6/lib/python/site-packages/botocore/client.py", line 632, in _convert_to_request_dict
    api_params, operation_model)
  File "/Users/frederik/Library/Python/3.6/lib/python/site-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "compatibilities", must be one of: family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory
Unknown parameter in input: "taskDefinitionArn", must be one of: family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory
Unknown parameter in input: "requiresAttributes", must be one of: family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory
Unknown parameter in input: "revision", must be one of: family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory
Unknown parameter in input: "status", must be one of: family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory
Invalid type for parameter containerDefinitions[0].dnsSearchDomains, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
Invalid type for parameter containerDefinitions[0].logConfiguration, value: None, type: <class 'NoneType'>, valid types: <class 'dict'>
Invalid type for parameter containerDefinitions[0].linuxParameters, value: None, type: <class 'NoneType'>, valid types: <class 'dict'>
Invalid type for parameter containerDefinitions[0].ulimits, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
Invalid type for parameter containerDefinitions[0].dnsServers, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
Invalid type for parameter containerDefinitions[0].workingDirectory, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
Invalid type for parameter containerDefinitions[0].dockerSecurityOptions, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
Invalid type for parameter containerDefinitions[0].memoryReservation, value: None, type: <class 'NoneType'>, valid types: <class 'int'>
Invalid type for parameter containerDefinitions[0].disableNetworking, value: None, type: <class 'NoneType'>, valid types: <class 'bool'>
Invalid type for parameter containerDefinitions[0].interactive, value: None, type: <class 'NoneType'>, valid types: <class 'bool'>
Invalid type for parameter containerDefinitions[0].healthCheck, value: None, type: <class 'NoneType'>, valid types: <class 'dict'>
Invalid type for parameter containerDefinitions[0].links, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
Invalid type for parameter containerDefinitions[0].hostname, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
Invalid type for parameter containerDefinitions[0].extraHosts, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
Invalid type for parameter containerDefinitions[0].pseudoTerminal, value: None, type: <class 'NoneType'>, valid types: <class 'bool'>
Invalid type for parameter containerDefinitions[0].user, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
Invalid type for parameter containerDefinitions[0].readonlyRootFilesystem, value: None, type: <class 'NoneType'>, valid types: <class 'bool'>
Invalid type for parameter containerDefinitions[0].dockerLabels, value: None, type: <class 'NoneType'>, valid types: <class 'dict'>
Invalid type for parameter containerDefinitions[0].systemControls, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
Invalid type for parameter containerDefinitions[0].privileged, value: None, type: <class 'NoneType'>, valid types: <class 'bool'>
Invalid type for parameter networkMode, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
Invalid type for parameter cpu, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
2018-10-02 23:48:39,430 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Parameter validation failed:
Unknown parameter in input: "compatibilities", must be one of: family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory
Unknown parameter in input: "taskDefinitionArn", must be one of: family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory
Unknown parameter in input: "requiresAttributes", must be one of: family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory
Unknown parameter in input: "revision", must be one of: family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory
Unknown parameter in input: "status", must be one of: family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory
Invalid type for parameter containerDefinitions[0].dnsSearchDomains, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
Invalid type for parameter containerDefinitions[0].logConfiguration, value: None, type: <class 'NoneType'>, valid types: <class 'dict'>
Invalid type for parameter containerDefinitions[0].linuxParameters, value: None, type: <class 'NoneType'>, valid types: <class 'dict'>
Invalid type for parameter containerDefinitions[0].ulimits, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
Invalid type for parameter containerDefinitions[0].dnsServers, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
Invalid type for parameter containerDefinitions[0].workingDirectory, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
Invalid type for parameter containerDefinitions[0].dockerSecurityOptions, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
Invalid type for parameter containerDefinitions[0].memoryReservation, value: None, type: <class 'NoneType'>, valid types: <class 'int'>
Invalid type for parameter containerDefinitions[0].disableNetworking, value: None, type: <class 'NoneType'>, valid types: <class 'bool'>
Invalid type for parameter containerDefinitions[0].interactive, value: None, type: <class 'NoneType'>, valid types: <class 'bool'>
Invalid type for parameter containerDefinitions[0].healthCheck, value: None, type: <class 'NoneType'>, valid types: <class 'dict'>
Invalid type for parameter containerDefinitions[0].links, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
Invalid type for parameter containerDefinitions[0].hostname, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
Invalid type for parameter containerDefinitions[0].extraHosts, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
Invalid type for parameter containerDefinitions[0].pseudoTerminal, value: None, type: <class 'NoneType'>, valid types: <class 'bool'>
Invalid type for parameter containerDefinitions[0].user, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
Invalid type for parameter containerDefinitions[0].readonlyRootFilesystem, value: None, type: <class 'NoneType'>, valid types: <class 'bool'>
Invalid type for parameter containerDefinitions[0].dockerLabels, value: None, type: <class 'NoneType'>, valid types: <class 'dict'>
Invalid type for parameter containerDefinitions[0].systemControls, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
Invalid type for parameter containerDefinitions[0].privileged, value: None, type: <class 'NoneType'>, valid types: <class 'bool'>
Invalid type for parameter networkMode, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
Invalid type for parameter cpu, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```

i'm unsure if my assumption is incorrect and there - for reasons I don't know, as I'm still new at this - cannot be enough information in the JSON output from the console to recreate the task through the CLI, or if it's simply an oversight.

**Comment by justnance** [comment]
@FredeJ - Thank you for reaching out.  Providing both the --debug results and the contents of file://aws-cli-json.json was really helpful.  It appears the output values are not allowed as input parameters by the service.  The CLI is only displaying the error returned by the service and does not have any control over this behavior.  Once this information is exposed from the API then it should be automatically picked up and displayed by the CLI.  As such, I have notified our internal service team of this issue.  

To follow up on this issue, it is recommended to reach out on the [ECS forums](https://forums.aws.amazon.com/forum.jspa?forumID=187) or contact [AWS Support](https://console.aws.amazon.com/support/home#/) as we try to reserve GitHub issues to CLI bugs and feature requests.

**Comment by aledalgrande** [comment]
Still an issue in 2021.

**Comment by kirschem** [comment]
Have the same issue. Is there any way/workaround to export a json definition of a task created via the web ui which is a valid input for `aws ecs register-task-definition`?

**Comment by wpater** [comment]
> Having the same issue. Is there any way/workaround to export a json definition of a task created via the web ui which is a valid input for `aws ecs register-task-definition`?

I had the same issue - I removed all parameters with `null` as value from the task definition and it is working.

**Comment by geinarm** [comment]
I had this issue. I think the best solution is to get the task definition from the CLI.
```
aws ecs describe-task-definition
```
