### ISSUE TITLE
Windows MSI installer AWSCLI64PY3 install error

### ISSUE THREAD

**Issue by calebickler** [aws/aws-cli#3623]
Installer is AWSCLI64PY3
```
Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\__main__.py", line 20, in <module>
    sys.exit(main())
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\clidriver.py", line 58, in main
    driver = create_clidriver()
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\clidriver.py", line 68, in create_clidriver
    event_hooks=session.get_component('event_emitter'))
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\handlers.py", line 20, in <module>
    from awscli.paramfile import register_uri_param_handler
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\paramfile.py", line 18, in <module>
    from botocore.httpsession import URLLib3Session
ModuleNotFoundError: No module named 'botocore.httpsession'
```

**Comment by JordonPhillips** [comment]
Interesting. It looks like you somehow don't have an upgraded version of botocore. If you run this in powershell you should be able to see the version:

```powershell
> type 'C:\Program Files\Amazon\AWSCLI\runtime\Lib\site-packages\botocore\__init__.py'
[...]
__version__ = '1.12.16'
[...]
```

Similarly for the CLI:

```powershell
> type 'C:\Program Files\Amazon\AWSCLI\runtime\Lib\site-packages\awscli\__init__.py'
[...]
__version__ = '1.16.26'
[...]
```

If you're using the latest version of the installer you should see those versions. You can get a very specific version like so:

```powershell
> Invoke-WebRequest -OutFile AWSCLI64PY3.msi https://s3.amazonaws.com/aws-cli/AWSCLI64PY3-1.16.26.msi
```

I'm not entirely sure why you might have a mismatched version. It could be due to a bad upgrade. Could you give me the versions you see? And do you recall if you used that same installer last time, or a different one?

**Comment by calebickler** [comment]
wow only got alerted once the issue is closed, wonder if there is a setting in github where I can see if responses are added

**Comment by calebickler** [comment]
Here are the values:
'C:\Program Files\Amazon\AWSCLI\runtime\Lib\site-packages\botocore\__init__.py'
`__version__ = '1.12.20'`
'C:\Program Files\Amazon\AWSCLI\runtime\Lib\site-packages\awscli\__init__.py'
`__version__ = '1.16.30'`

I can't remember if I used the installer last time, I might have used pip. I think my old version was 1.13 or something like that

I tried uninstalling from windows apps & features, no luck. I also can't find any amazon related files in Program File (x86), is there a specific path I should check?

Still getting:
````
Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\__main__.py", line 20, in <module>
    sys.exit(main())
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\clidriver.py", line 58, in main
    driver = create_clidriver()
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\clidriver.py", line 68, in create_clidriver
    event_hooks=session.get_component('event_emitter'))
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\handlers.py", line 20, in <module>
    from awscli.paramfile import register_uri_param_handler
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\paramfile.py", line 18, in <module>
    from botocore.httpsession import URLLib3Session
ModuleNotFoundError: No module named 'botocore.httpsession'
````

**Comment by justnance** [comment]
@calebickler - Thank you for your feedback and patience.  I could not reproduce this issue.  The problem appears to be due to a mismatch in the CLI and the botocore version.  This usually happens when the install was not done with the MSI.  I would suggest uninstalling again and remove the directory `C:\Program Files\Amazon\AWSCLI` completely then reinstall using the latest [MSI](https://docs.aws.amazon.com/cli/latest/userguide/awscli-install-windows.html).

**Comment by justnance** [comment]
@calebickler - Thanks for your feedback and patience. I have been unable to reproduce the same issue.  I would recommend uninstalling the ECSCLI and remove or rename the C:\Program Files\Amazon directory followed by a reinstall.  

I also want to reference #3662 as we are working on improving the AWSCLI64PY3 MSI install.

**Comment by calebickler** [comment]
uninstalled awscli again, renamed the Amazon folder under `C:\Program Files\Amazon` this just contained a folder with the ecs-cli exe in it. Then I reinstalled and ran `aws` in powershell:

````
File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\__main__.py", line 20, in <module>
    sys.exit(main())
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\clidriver.py", line 58, in main
    driver = create_clidriver()
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\clidriver.py", line 68, in create_clidriver
    event_hooks=session.get_component('event_emitter'))
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\handlers.py", line 20, in <module>
    from awscli.paramfile import register_uri_param_handler
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\paramfile.py", line 18, in <module>
    from botocore.httpsession import URLLib3Session
ModuleNotFoundError: No module named 'botocore.httpsession'
````

**Comment by justnance** [comment]
@calebickler - Thank you for your feedback and details.  When we see the following output, it indicates there is a mismatch in the CLI and the botocore version:

`import URLLib3Session
ModuleNotFoundError: No module named 'botocore.httpsession'

This usually happens when the install was not done with the MSI.  Please repeat the following steps so I can see what version:

```powershell
> type 'C:\Program Files\Amazon\AWSCLI\runtime\Lib\site-packages\botocore\__init__.py'
[...]
__version__ = '1.12.16'
[...]
```

Similarly for the CLI:

```powershell
> type 'C:\Program Files\Amazon\AWSCLI\runtime\Lib\site-packages\awscli\__init__.py'
[...]
__version__ = '1.16.26'
[...]
```

**Comment by joguSD** [comment]
Sorry, it looks like this fell off of our radar. Are you still having troubles with this? 

My hunch is that you have `botocore` installed somewhere outside of the AWS CLI.
Would it be possible to uninstall the MSI installation of the CLI and ensure that no other installation is present?
It sounds like you also have a Python installation on your system, would it be possible to run the following (with the MSI uninstalled):
```
python -c "import botocore; print(botocore.__version__)"
```
It might be possible that libraries in your Python installation are somehow leaking into the MSI install. Perhaps your environment has `PYTHONPATH` set?
