### ISSUE TITLE
[CLI V2] awscli cannot be run via pipenv on windows

### ISSUE THREAD

**Issue by troyready** [aws/aws-cli#3627]
On a fresh Python (tested in 2.7 and 3.6.6) install on windows with pipenv, attempting to run the cli generates a stacktrace:
```
PS C:\Users\Administrator\myprojectwithpipenv> pipenv run aws s3 ls
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\Scripts\pipenv.exe\__main__.py", line 9, in <module>
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\click\core.py", line 722, in
__call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\click\core.py", line 697, in
main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\click\core.py", line 1066, in
 invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\click\core.py", line 895, in
invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\click\core.py", line 535, in
invoke
    return callback(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\pipenv\cli.py", line 701, in run
    do_run(command=command, args=args, three=three, python=python, pypi_mirror=pypi_mirror)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\pipenv\core.py", line 2253, in do_run
    do_run_nt(script)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\pipenv\core.py", line 2201, in do_run_nt
    p = subprocess.Popen([command] + script.args, **options)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application
```

The CLI can be manually instantiated in the pipenv venv:
```
pipenv run python -c "import sys;import awscli.clidriver;sys.argv = ['aws', 's3', 'ls'];sys.exit(awscli.clidriver.main())"
<buckets are successfully listed here>
```

**Comment by joguSD** [comment]
The changes required to our packaging to get this working could potentially cause issues in the current major version so we're targeting addressing this in V2.

**Comment by tim-finnigan** [comment]
Checking in as there hasn't been any activity on this issue in a while. Are you still unable to run the AWS CLI via pipenv on Windows? And has anyone tried alternatives such as virtualenv? If you're still running into this issue please let us know which OS/CLI/Python versions you're using.
