### ISSUE TITLE
TranslateText operation: Invalid UTF-8 encoded text

### ISSUE THREAD

**Issue by barlog-m** [aws/aws-cli#3799]
command
```
aws translate translate-text --source-language-code ru --target-language-code en --text "Тест"
```

error
```
An error occurred (InvalidRequestException) when calling the TranslateText operation: Invalid UTF-8 encoded text.
```

version (stable from snapcraft.io)
```
aws-cli/1.15.71 Python/3.5.2 Linux/4.19.8-arch1-1-ARCH botocore/1.10.70
```

locale: `LANG=en_GB.UTF-8`

**Comment by justnance** [comment]
@Barlog-M - Thanks for reporting this behavior.  I was not able to reproduce this issue.  The CLI is only displaying the error that is returning from the service as the CLI does not have any control over this behavior.  If you can use the  [--debug option](https://docs.aws.amazon.com/cli/latest/reference/) and upload the sanitized results so I can report this issue our Translate service team.  

Example:
```
aws translate translate-text --source-language-code ru --target-language-code en --text "Тест" --debug
```

Another recommendation is to reach out to [AWS Support](https://console.aws.amazon.com/support/home#/) or the [AWS Discussion Forums for Amazon Translate](https://forums.aws.amazon.com/forum.jspa?forumID=267) for follow up.

Thank you for choosing AWS.

**Comment by barlog-m** [comment]
Thanks for your response. Here is same request with debug option.

```
> aws translate translate-text --source-language-code ru --target-language-code en --text "Тест" --debug
2018-12-27 11:49:21,432 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.15.71 Python/3.5.2 Linux/4.19.12-arch1-1-ARCH botocore/1.10.70
2018-12-27 11:49:21,433 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['translate', 'translate-text', '--source-language-code', 'ru', '--target-language-code', 'en', '--text', '\udcd0\udca2\udcd0\udcb5\udcd1\udc81\udcd1\udc82', '--debug']
2018-12-27 11:49:21,433 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7fe7555d19d8>
2018-12-27 11:49:21,433 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-12-27 11:49:21,433 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7fe758dc40d0>
2018-12-27 11:49:21,433 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-12-27 11:49:21,433 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7fe756e8f9d8>
2018-12-27 11:49:21,434 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-12-27 11:49:21,434 - MainThread - botocore.session - DEBUG - Loading variable credentials_file from defaults.
2018-12-27 11:49:21,434 - MainThread - botocore.session - DEBUG - Loading variable config_file from defaults.
2018-12-27 11:49:21,434 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-12-27 11:49:21,434 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_timeout from defaults.
2018-12-27 11:49:21,434 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-12-27 11:49:21,434 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_num_attempts from defaults.
2018-12-27 11:49:21,435 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-12-27 11:49:21,435 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7fe7555602f0>
2018-12-27 11:49:21,435 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-12-27 11:49:21,435 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-12-27 11:49:21,435 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2018-12-27 11:49:21,435 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /snap/aws-cli/135/lib/python3.5/site-packages/botocore/data/translate/2017-07-01/service-2.json
2018-12-27 11:49:21,436 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.translate: calling handler <function register_retries_for_service at 0x7fe758b190d0>
2018-12-27 11:49:21,436 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: translate
2018-12-27 11:49:21,436 - MainThread - botocore.hooks - DEBUG - Event building-command-table.translate: calling handler <function add_waiters at 0x7fe7555d7d90>
2018-12-27 11:49:21,440 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('text', <awscli.arguments.CLIArgument object at 0x7fe7557e0390>), ('source-language-code', <awscli.arguments.CLIArgument object at 0x7fe7557e03c8>), ('target-language-code', <awscli.arguments.CLIArgument object at 0x7fe7557e0278>)])
2018-12-27 11:49:21,440 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.translate.translate-text: calling handler <function add_streaming_output_arg at 0x7fe7555d1c80>
2018-12-27 11:49:21,440 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.translate.translate-text: calling handler <function add_cli_input_json at 0x7fe756e6a2f0>
2018-12-27 11:49:21,440 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.translate.translate-text: calling handler <function unify_paging_params at 0x7fe757ac1378>
2018-12-27 11:49:21,443 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /snap/aws-cli/135/lib/python3.5/site-packages/botocore/data/translate/2017-07-01/paginators-1.json
2018-12-27 11:49:21,443 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.translate.translate-text: calling handler <function add_generate_skeleton at 0x7fe755b7ed08>
2018-12-27 11:49:21,443 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.translate.translate-text: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7fe7557e0208>>
2018-12-27 11:49:21,443 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.translate.translate-text: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fe7557e02b0>>
2018-12-27 11:49:21,444 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.translate.translate-text.text: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fe75a4de358>
2018-12-27 11:49:21,444 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.translate.translate-text: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fe758db8390>
2018-12-27 11:49:21,445 - MainThread - awscli.arguments - DEBUG - Unpacked value of '\udcd0\udca2\udcd0\udcb5\udcd1\udc81\udcd1\udc82' for parameter "text": '\udcd0\udca2\udcd0\udcb5\udcd1\udc81\udcd1\udc82'
2018-12-27 11:49:21,445 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.translate.translate-text.source-language-code: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fe75a4de358>
2018-12-27 11:49:21,445 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.translate.translate-text: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fe758db8390>
2018-12-27 11:49:21,445 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'ru' for parameter "source_language_code": 'ru'
2018-12-27 11:49:21,445 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.translate.translate-text.target-language-code: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fe75a4de358>
2018-12-27 11:49:21,445 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.translate.translate-text: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fe758db8390>
2018-12-27 11:49:21,445 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'en' for parameter "target_language_code": 'en'
2018-12-27 11:49:21,445 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.translate.translate-text.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fe75a4de358>
2018-12-27 11:49:21,445 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.translate.translate-text.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fe75a4de358>
2018-12-27 11:49:21,445 - MainThread - botocore.hooks - DEBUG - Event calling-command.translate.translate-text: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7fe7557e0208>>
2018-12-27 11:49:21,445 - MainThread - botocore.hooks - DEBUG - Event calling-command.translate.translate-text: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fe7557e02b0>>
2018-12-27 11:49:21,445 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-12-27 11:49:21,445 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-12-27 11:49:21,445 - MainThread - botocore.session - DEBUG - Loading variable region from config file with value 'us-east-1'.
2018-12-27 11:49:21,446 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-12-27 11:49:21,446 - MainThread - botocore.session - DEBUG - Loading variable ca_bundle from defaults.
2018-12-27 11:49:21,446 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-12-27 11:49:21,446 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2018-12-27 11:49:21,446 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2018-12-27 11:49:21,446 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2018-12-27 11:49:21,446 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2018-12-27 11:49:21,446 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2018-12-27 11:49:21,446 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /snap/aws-cli/135/lib/python3.5/site-packages/botocore/data/endpoints.json
2018-12-27 11:49:21,450 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-12-27 11:49:21,450 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7fe758af8730>
2018-12-27 11:49:21,450 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.translate: calling handler <function add_generate_presigned_url at 0x7fe756b71bf8>
2018-12-27 11:49:21,450 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2018-12-27 11:49:21,453 - MainThread - botocore.endpoint - DEBUG - Setting translate timeout as (60, 60)
2018-12-27 11:49:21,454 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: translate
2018-12-27 11:49:21,454 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.translate.TranslateText: calling handler <function generate_idempotent_uuid at 0x7fe758b129d8>
2018-12-27 11:49:21,455 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=TranslateText) (verify_ssl=True) with params: {'headers': {'X-Amz-Target': 'AWSShineFrontendService_20170701.TranslateText', 'User-Agent': 'aws-cli/1.15.71 Python/3.5.2 Linux/4.19.12-arch1-1-ARCH botocore/1.10.70', 'Content-Type': 'application/x-amz-json-1.1'}, 'url': 'https://translate.us-east-1.amazonaws.com/', 'context': {'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x7fe755863898>, 'auth_type': None, 'has_streaming_input': False}, 'url_path': '/', 'query_string': '', 'body': b'{"SourceLanguageCode": "ru", "Text": "\\udcd0\\udca2\\udcd0\\udcb5\\udcd1\\udc81\\udcd1\\udc82", "TargetLanguageCode": "en"}', 'method': 'POST'}
2018-12-27 11:49:21,455 - MainThread - botocore.hooks - DEBUG - Event request-created.translate.TranslateText: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fe7558636d8>>
2018-12-27 11:49:21,455 - MainThread - botocore.hooks - DEBUG - Event choose-signer.translate.TranslateText: calling handler <function set_operation_specific_signer at 0x7fe758b128c8>
2018-12-27 11:49:21,456 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2018-12-27 11:49:21,456 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-amz-json-1.1
host:translate.us-east-1.amazonaws.com
x-amz-date:20181227T084921Z
x-amz-target:AWSShineFrontendService_20170701.TranslateText

content-type;host;x-amz-date;x-amz-target
d8f1b009ecf00b076e4f0bb960edb610d143350276c907a79bd0e606c3221727
2018-12-27 11:49:21,456 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20181227T084921Z
20181227/us-east-1/translate/aws4_request
b33191d7202696ad298c116d2502632cc7a48549b5a7cf24dddff910419b8f07
2018-12-27 11:49:21,456 - MainThread - botocore.auth - DEBUG - Signature:
95543b612a1bb518f6825a6ff7a575884b4f7b23b4346df908cc623551caa1ff
2018-12-27 11:49:21,462 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2018-12-27 11:49:21,463 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): translate.us-east-1.amazonaws.com
2018-12-27 11:49:22,082 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "POST / HTTP/1.1" 400 76
2018-12-27 11:49:22,098 - MainThread - botocore.parsers - DEBUG - Response headers: {'content-type': 'application/x-amz-json-1.1', 'date': 'Thu, 27 Dec 2018 08:49:21 GMT', 'connection': 'keep-alive', 'x-amzn-requestid': '4e0e16cc-09b4-11e9-8805-cd197cc3918d', 'content-length': '76'}
2018-12-27 11:49:22,098 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"__type":"InvalidRequestException","Message":"Invalid UTF-8 encoded text."}'
2018-12-27 11:49:22,098 - MainThread - botocore.hooks - DEBUG - Event needs-retry.translate.TranslateText: calling handler <botocore.retryhandler.RetryHandler object at 0x7fe7557e0ac8>
2018-12-27 11:49:22,098 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2018-12-27 11:49:22,098 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/snap/aws-cli/135/lib/python3.5/site-packages/awscli/clidriver.py", line 208, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/snap/aws-cli/135/lib/python3.5/site-packages/awscli/clidriver.py", line 345, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/snap/aws-cli/135/lib/python3.5/site-packages/awscli/clidriver.py", line 517, in __call__
    call_parameters, parsed_globals)
  File "/snap/aws-cli/135/lib/python3.5/site-packages/awscli/clidriver.py", line 637, in invoke
    client, operation_name, parameters, parsed_globals)
  File "/snap/aws-cli/135/lib/python3.5/site-packages/awscli/clidriver.py", line 649, in _make_client_call
    **parameters)
  File "/snap/aws-cli/135/lib/python3.5/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/snap/aws-cli/135/lib/python3.5/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the TranslateText operation: Invalid UTF-8 encoded text.
2018-12-27 11:49:22,099 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255
```

**Comment by justnance** [comment]
@barlog-m - Thanks for the debug logs. They are really helpful.  I have forwarded this issue to our service team for review.  It is recommended to follow up with [AWS Support](https://console.aws.amazon.com/support/home#/) or the [AWS Translate forums](https://forums.aws.amazon.com/forum.jspa?forumID=267)

**Comment by justnance** [comment]
@barlog-m - Just a quick update from our service team.  We were not able to reproduce the same results however our internal logs detected a null character in the input that appears to be getting dropped when the content is being copied to github or other system.
