### ISSUE TITLE
Invalid AWS_PROFILE (or AWS_DEFAULT_PROFILE) will cause traceback

### ISSUE THREAD

**Issue by kallu** [aws/aws-cli#3834]
When AWS_PROFILE (or AWS_DEFAULT_PROFILE) is set to invalid (non-existing) value, aws cli will fail instead of graceful exit with error msg.

```
$ aws --version
aws-cli/1.16.84 Python/2.7.10 Darwin/18.2.0 botocore/1.12.74

$ export AWS_PROFILE=foobar
$ aws sts get-caller-identity
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 59, in main
    rc = driver.main()
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 193, in main
    command_table = self._get_command_table()
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 102, in _get_command_table
    self._command_table = self._build_command_table()
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 122, in _build_command_table
    command_object=self)
  File "/Library/Python/2.7/site-packages/botocore/session.py", line 671, in emit
    return self._events.emit(event_name, **kwargs)
  File "/Library/Python/2.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/Library/Python/2.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/Library/Python/2.7/site-packages/awscli/customizations/preview.py", line 69, in mark_as_preview
    service_name=original_command.service_model.service_name,
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 318, in service_model
    return self._get_service_model()
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 335, in _get_service_model
    api_version = self.session.get_config_variable('api_versions').get(
  File "/Library/Python/2.7/site-packages/botocore/session.py", line 233, in get_config_variable
    logical_name)
  File "/Library/Python/2.7/site-packages/botocore/configprovider.py", line 226, in get_config_variable
    return provider.provide()
  File "/Library/Python/2.7/site-packages/botocore/configprovider.py", line 323, in provide
    value = provider.provide()
  File "/Library/Python/2.7/site-packages/botocore/configprovider.py", line 382, in provide
    config = self._session.get_scoped_config()
  File "/Library/Python/2.7/site-packages/botocore/session.py", line 334, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (foobar) could not be found
```

Expected behaviour would be graceful exit, similar to --profile with non-existing profile

```
$ unset AWS_PROFILE
$ aws --profile foobar sts get-caller-identity

The config profile (foobar) could not be found
```

**Comment by kyleknap** [comment]
Makes sense to me. We would need to dig a little more into it, but I suspect we should be able to move [these lines](https://github.com/aws/aws-cli/blob/3cd51418b89b6c5188fbca898f374642071636ff/awscli/clidriver.py#L193-L196) into the try/except statement that hides tracebacks.

**Comment by stobrien89** [comment]
Confirmed issue is no longer present in V1 or V2.  Closing.
