### ISSUE TITLE
EB create throws 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by serchserch** [aws/aws-cli#3981]
```shell
eb create my-app --cfg node --verbose

INFO: Traceback (most recent call last):
  File "/Users/user/Library/Python/3.7/lib/python/site-packages/ebcli/core/ebrun.py", line 62, in run_app
    app.run()
  File "/Users/user/Library/Python/3.7/lib/python/site-packages/cement/core/foundation.py", line 797, in run
    return_val = self.controller._dispatch()
  File "/Users/user/Library/Python/3.7/lib/python/site-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/Users/user/Library/Python/3.7/lib/python/site-packages/cement/core/controller.py", line 478, in _dispatch
    return func()
  File "/Users/user/Library/Python/3.7/lib/python/site-packages/ebcli/core/abstractcontroller.py", line 89, in default
    self.do_command()
  File "/Users/user/Library/Python/3.7/lib/python/site-packages/ebcli/controllers/create.py", line 180, in do_command
    platform = get_platform(solution_string, iprofile)
  File "/Users/user/Library/Python/3.7/lib/python/site-packages/ebcli/controllers/create.py", line 412, in get_platform
    solution = solution_stack_ops.find_solution_stack_from_string(solution_string)
  File "/Users/user/Library/Python/3.7/lib/python/site-packages/ebcli/operations/solution_stack_ops.py", line 77, in find_solution_stack_from_string
    match = SolutionStack.match_with_complete_solution_string(available_solution_stacks, solution_string)
  File "/Users/user/Library/Python/3.7/lib/python/site-packages/ebcli/objects/solutionstack.py", line 359, in match_with_complete_solution_string
    if solution_stack.name.lower() == complete_solution_stack_name.lower():
AttributeError: 'NoneType' object has no attribute 'lower'

INFO: AttributeError - 'NoneType' object has no attribute 'lower'

```

```shell
aws --version
aws-cli/1.16.115 Python/3.7.2 Darwin/18.2.0 botocore/1.12.105
```

```shell
eb --version
EB CLI 3.14.13 (Python 3.7.2)
```

**Comment by JordonPhillips** [comment]
This looks like an issue in the eb cli. You will need to contact the elastic beanstalk team on [their forum](https://forums.aws.amazon.com/forum.jspa?forumID=86) for help with this.

**Comment by NguyenDuyToan** [comment]
I got similar problem after deleting `default_platform` from  `.elasticbeanstalk/config.yml` file:
```
...
2019-03-11 10:23:01,670 (DEBUG) ebcli.lib.elasticbeanstalk : Solution Stack result size = 69
INFO: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ebcli/core/ebrun.py", line 41, in run_app
    app.run()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/foundation.py", line 797, in run
    return_val = self.controller._dispatch()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/controller.py", line 478, in _dispatch
    return func()
  File "/usr/local/lib/python3.6/dist-packages/ebcli/core/abstractcontroller.py", line 85, in default
    self.do_command()
  File "/usr/local/lib/python3.6/dist-packages/ebcli/controllers/create.py", line 172, in do_command
    platform = get_platform(solution_string, iprofile)
  File "/usr/local/lib/python3.6/dist-packages/ebcli/controllers/create.py", line 423, in get_platform
    solution = solution_stack_ops.find_solution_stack_from_string(solution_string)
  File "/usr/local/lib/python3.6/dist-packages/ebcli/operations/solution_stack_ops.py", line 76, in find_solution_stack_from_string
    match = SolutionStack.match_with_complete_solution_string(available_solution_stacks, solution_string)
  File "/usr/local/lib/python3.6/dist-packages/ebcli/objects/solutionstack.py", line 359, in match_with_complete_solution_string
    if solution_stack.name.lower() == complete_solution_stack_name.lower():
AttributeError: 'NoneType' object has no attribute 'lower'
```
After add back `default_platform: Multi-container Docker 18.06.1-ce (Generic)`, EB create works fine.
Hope this helps!

**Comment by teragrid** [comment]
> I got similar problem after deleting `default_platform` from `.elasticbeanstalk/config.yml` file:
> 
> ```
> ...
> 2019-03-11 10:23:01,670 (DEBUG) ebcli.lib.elasticbeanstalk : Solution Stack result size = 69
> INFO: Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/ebcli/core/ebrun.py", line 41, in run_app
>     app.run()
>   File "/usr/local/lib/python3.6/dist-packages/cement/core/foundation.py", line 797, in run
>     return_val = self.controller._dispatch()
>   File "/usr/local/lib/python3.6/dist-packages/cement/core/controller.py", line 472, in _dispatch
>     return func()
>   File "/usr/local/lib/python3.6/dist-packages/cement/core/controller.py", line 478, in _dispatch
>     return func()
>   File "/usr/local/lib/python3.6/dist-packages/ebcli/core/abstractcontroller.py", line 85, in default
>     self.do_command()
>   File "/usr/local/lib/python3.6/dist-packages/ebcli/controllers/create.py", line 172, in do_command
>     platform = get_platform(solution_string, iprofile)
>   File "/usr/local/lib/python3.6/dist-packages/ebcli/controllers/create.py", line 423, in get_platform
>     solution = solution_stack_ops.find_solution_stack_from_string(solution_string)
>   File "/usr/local/lib/python3.6/dist-packages/ebcli/operations/solution_stack_ops.py", line 76, in find_solution_stack_from_string
>     match = SolutionStack.match_with_complete_solution_string(available_solution_stacks, solution_string)
>   File "/usr/local/lib/python3.6/dist-packages/ebcli/objects/solutionstack.py", line 359, in match_with_complete_solution_string
>     if solution_stack.name.lower() == complete_solution_stack_name.lower():
> AttributeError: 'NoneType' object has no attribute 'lower'
> ```
> 
> After add back `default_platform: Multi-container Docker 18.06.1-ce (Generic)`, EB create works fine.
> Hope this helps!

It works! Thanks! :P
