### ISSUE TITLE
Unable to use admin-update-user-attributes with special characters

### ISSUE THREAD

**Issue by gpazo** [aws/aws-cli#4063]
I ran the command with debug below: 

`aws cognito-idp admin-update-user-attributes --user-pool-id us-west-2_4nH0edkAp --username testuser --user-attributes Name="custom:Brand",Value="Cameron's Coffee" --debug`

Output: 
```
Gregs-MacBook-Pro:omni-platform gpazo$ aws cognito-idp admin-update-user-attributes --user-pool-id us-west-2_4nH0edkAp --username testuser --user-attributes Name="custom:Brand",Value="Cameron's Coffee" --debug
2019-04-08 12:57:26,891 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.16.130 Python/3.7.3 Darwin/17.5.0 botocore/1.12.120
2019-04-08 12:57:26,891 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['cognito-idp', 'admin-update-user-attributes', '--user-pool-id', 'us-west-2_4nH0edkAp', '--username', 'testuser', '--user-attributes', "Name=custom:Brand,Value=Cameron's Coffee", '--debug']
2019-04-08 12:57:26,892 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x104f637b8>
2019-04-08 12:57:26,892 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x1049c8488>
2019-04-08 12:57:26,892 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x104a01400>
2019-04-08 12:57:26,898 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x104e2c950>
2019-04-08 12:57:26,899 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/1.16.130/libexec/lib/python3.7/site-packages/botocore/data/cognito-idp/2016-04-18/service-2.json
2019-04-08 12:57:26,903 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.cognito-identity-provider: calling handler <function register_retries_for_service at 0x1044fe510>
2019-04-08 12:57:26,904 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: cognito-idp
2019-04-08 12:57:26,906 - MainThread - botocore.hooks - DEBUG - Changing event name from building-command-table.cognito-idp to building-command-table.cognito-identity-provider
2019-04-08 12:57:26,906 - MainThread - botocore.hooks - DEBUG - Event building-command-table.cognito-identity-provider: calling handler <function add_waiters at 0x104f69c80>
2019-04-08 12:57:26,913 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('user-pool-id', <awscli.arguments.CLIArgument object at 0x105b3e048>), ('username', <awscli.arguments.CLIArgument object at 0x105b42278>), ('user-attributes', <awscli.arguments.ListArgument object at 0x105b422e8>)])
2019-04-08 12:57:26,913 - MainThread - botocore.hooks - DEBUG - Changing event name from building-argument-table.cognito-idp.admin-update-user-attributes to building-argument-table.cognito-identity-provider.admin-update-user-attributes
2019-04-08 12:57:26,914 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cognito-identity-provider.admin-update-user-attributes: calling handler <function add_streaming_output_arg at 0x104f63a60>
2019-04-08 12:57:26,914 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cognito-identity-provider.admin-update-user-attributes: calling handler <function add_cli_input_json at 0x104a01ae8>
2019-04-08 12:57:26,914 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cognito-identity-provider.admin-update-user-attributes: calling handler <function unify_paging_params at 0x104ee1d08>
2019-04-08 12:57:26,921 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/1.16.130/libexec/lib/python3.7/site-packages/botocore/data/cognito-idp/2016-04-18/paginators-1.json
2019-04-08 12:57:26,921 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cognito-identity-provider.admin-update-user-attributes: calling handler <function add_generate_skeleton at 0x104ec4ae8>
2019-04-08 12:57:26,922 - MainThread - botocore.hooks - DEBUG - Changing event name from before-building-argument-table-parser.cognito-idp.admin-update-user-attributes to before-building-argument-table-parser.cognito-identity-provider.admin-update-user-attributes
2019-04-08 12:57:26,922 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cognito-identity-provider.admin-update-user-attributes: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x105b42390>>
2019-04-08 12:57:26,922 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cognito-identity-provider.admin-update-user-attributes: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x105b423c8>>
2019-04-08 12:57:26,923 - MainThread - botocore.hooks - DEBUG - Changing event name from operation-args-parsed.cognito-idp.admin-update-user-attributes to operation-args-parsed.cognito-identity-provider.admin-update-user-attributes
2019-04-08 12:57:26,923 - MainThread - botocore.hooks - DEBUG - Changing event name from load-cli-arg.cognito-idp.admin-update-user-attributes.user-pool-id to load-cli-arg.cognito-identity-provider.admin-update-user-attributes.user-pool-id
2019-04-08 12:57:26,923 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cognito-identity-provider.admin-update-user-attributes.user-pool-id: calling handler <awscli.paramfile.URIArgumentHandler object at 0x104b03048>
2019-04-08 12:57:26,923 - MainThread - botocore.hooks - DEBUG - Changing event name from process-cli-arg.cognito-idp.admin-update-user-attributes to process-cli-arg.cognito-identity-provider.admin-update-user-attributes
2019-04-08 12:57:26,923 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.cognito-identity-provider.admin-update-user-attributes: calling handler <awscli.argprocess.ParamShorthandParser object at 0x1049c6b70>
2019-04-08 12:57:26,923 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'us-west-2_4nH0edkAp' for parameter "user_pool_id": 'us-west-2_4nH0edkAp'
2019-04-08 12:57:26,923 - MainThread - botocore.hooks - DEBUG - Changing event name from load-cli-arg.cognito-idp.admin-update-user-attributes.username to load-cli-arg.cognito-identity-provider.admin-update-user-attributes.username
2019-04-08 12:57:26,924 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cognito-identity-provider.admin-update-user-attributes.username: calling handler <awscli.paramfile.URIArgumentHandler object at 0x104b03048>
2019-04-08 12:57:26,924 - MainThread - botocore.hooks - DEBUG - Changing event name from process-cli-arg.cognito-idp.admin-update-user-attributes to process-cli-arg.cognito-identity-provider.admin-update-user-attributes
2019-04-08 12:57:26,924 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.cognito-identity-provider.admin-update-user-attributes: calling handler <awscli.argprocess.ParamShorthandParser object at 0x1049c6b70>
2019-04-08 12:57:26,924 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'testuser' for parameter "username": 'testuser'
2019-04-08 12:57:26,924 - MainThread - botocore.hooks - DEBUG - Changing event name from load-cli-arg.cognito-idp.admin-update-user-attributes.user-attributes to load-cli-arg.cognito-identity-provider.admin-update-user-attributes.user-attributes
2019-04-08 12:57:26,924 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cognito-identity-provider.admin-update-user-attributes.user-attributes: calling handler <awscli.paramfile.URIArgumentHandler object at 0x104b03048>
2019-04-08 12:57:26,924 - MainThread - botocore.hooks - DEBUG - Changing event name from process-cli-arg.cognito-idp.admin-update-user-attributes to process-cli-arg.cognito-identity-provider.admin-update-user-attributes
2019-04-08 12:57:26,924 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.cognito-identity-provider.admin-update-user-attributes: calling handler <awscli.argprocess.ParamShorthandParser object at 0x1049c6b70>
2019-04-08 12:57:26,924 - MainThread - awscli.argprocess - DEBUG - Parsing param --user-attributes as shorthand
2019-04-08 12:57:26,925 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/Cellar/awscli/1.16.130/libexec/lib/python3.7/site-packages/awscli/argprocess.py", line 331, in _parse_as_shorthand
    parsed = [self._parser.parse(v) for v in value]
  File "/usr/local/Cellar/awscli/1.16.130/libexec/lib/python3.7/site-packages/awscli/argprocess.py", line 331, in <listcomp>
    parsed = [self._parser.parse(v) for v in value]
  File "/usr/local/Cellar/awscli/1.16.130/libexec/lib/python3.7/site-packages/awscli/shorthand.py", line 146, in parse
    return self._parameter()
  File "/usr/local/Cellar/awscli/1.16.130/libexec/lib/python3.7/site-packages/awscli/shorthand.py", line 153, in _parameter
    self._expect(',', consume_whitespace=True)
  File "/usr/local/Cellar/awscli/1.16.130/libexec/lib/python3.7/site-packages/awscli/shorthand.py", line 320, in _expect
    actual, self._index)
awscli.shorthand.ShorthandParseError: Expected: ',', received: ''' for input:
Name=custom:Brand,Value=Cameron's Coffee
                               ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/awscli/1.16.130/libexec/lib/python3.7/site-packages/awscli/clidriver.py", line 207, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/Cellar/awscli/1.16.130/libexec/lib/python3.7/site-packages/awscli/clidriver.py", line 348, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/Cellar/awscli/1.16.130/libexec/lib/python3.7/site-packages/awscli/clidriver.py", line 491, in __call__
    parsed_args, self.arg_table)
  File "/usr/local/Cellar/awscli/1.16.130/libexec/lib/python3.7/site-packages/awscli/clidriver.py", line 547, in _build_call_parameters
    arg_object.add_to_params(service_params, value)
  File "/usr/local/Cellar/awscli/1.16.130/libexec/lib/python3.7/site-packages/awscli/arguments.py", line 453, in add_to_params
    unpacked = self._unpack_argument(value)
  File "/usr/local/Cellar/awscli/1.16.130/libexec/lib/python3.7/site-packages/awscli/arguments.py", line 463, in _unpack_argument
    cli_argument=self, value=value)
  File "/usr/local/Cellar/awscli/1.16.130/libexec/lib/python3.7/site-packages/awscli/arguments.py", line 476, in _emit_first_response
    responses = self._emit(name, **kwargs)
  File "/usr/local/Cellar/awscli/1.16.130/libexec/lib/python3.7/site-packages/awscli/arguments.py", line 473, in _emit
    return self._event_emitter.emit(name, **kwargs)
  File "/usr/local/Cellar/awscli/1.16.130/libexec/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/Cellar/awscli/1.16.130/libexec/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/Cellar/awscli/1.16.130/libexec/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/Cellar/awscli/1.16.130/libexec/lib/python3.7/site-packages/awscli/argprocess.py", line 314, in __call__
    cli_argument, value, service_id, operation_name)
  File "/usr/local/Cellar/awscli/1.16.130/libexec/lib/python3.7/site-packages/awscli/argprocess.py", line 338, in _parse_as_shorthand
    raise ParamError(cli_argument.cli_name, str(e))
awscli.argprocess.ParamError: Error parsing parameter '--user-attributes': Expected: ',', received: ''' for input:
Name=custom:Brand,Value=Cameron's Coffee
                               ^
2019-04-08 12:57:26,926 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Error parsing parameter '--user-attributes': Expected: ',', received: ''' for input:
Name=custom:Brand,Value=Cameron's Coffee
```

I've had similar results with escaping the `'` character with a `\` what is the correct way to pass this value to the cli?

**Comment by gpazo** [comment]
I figured this one out, I was able to run it with the parameters in a separate JSON file with the syntax `file://test.json` as in below if anyone else runs into this:

```aws cognito-idp admin-update-user-attributes --user-pool-id myUserPool --username testuser --user-attributes file://test.json --debug```
