### ISSUE TITLE
EMR error when creating from CLI Export

### ISSUE THREAD

**Issue by Dickmcmanus** [aws/aws-cli#4069]
I've created a cluster using the AWS Console but now would like to set things up to launch it using CLI. When I attempt to take the code generated from the CLI Exporter (see below), receive the following error:

```
Error parsing parameter '--instance-groups': Expected: '=', received: ':' for input:
=[{InstanceCount:4,BidPrice:1.000,EbsConfiguration:{EbsBlockDeviceConfigs:[{VolumeSpecification:{SizeInGB:32,VolumeType:gp2},VolumesPerInstance:1}]},InstanceGroupType:CORE,InstanceType:m2.4xlarge,Name:CORE},{InstanceCount:1,BidPrice:1.000,EbsConfiguration:{EbsBlockDeviceConfigs:[{VolumeSpecification:{SizeInGB:32,VolumeType:gp2},VolumesPerInstance:1}]},InstanceGroupType:MASTER,InstanceType:m2.4xlarge,Name:MASTER}]
```

I've attempted playing around with how the --instance-groups config is formatted but to no avail. From the documentation on the --instance-groups, this appears to be the correct format (https://docs.aws.amazon.com/cli/latest/reference/emr/create-cluster.html).

`aws emr create-cluster --auto-scaling-role EMR_AutoScaling_DefaultRole --applications Name=Spark Name=Hadoop --tags 'Role=Analytics' 'Owner=dom' 'Program=Analytics' 'Environment=PROD' 'Purpose=Analytics' 'Team=Analytics SDK' 'Application=Analytics' 'user=Dick' 'Name=DickCluster' 'Stack=EMRSpark' --ebs-root-volume-size 10 --ec2-attributes '{"KeyName":"DickAnalytics","InstanceProfile":"EMR_EC2_DefaultRole","SubnetId":"subnet-a8a640cd","EmrManagedSlaveSecurityGroup":"sg-ef73f68a","EmrManagedMasterSecurityGroup":"sg-ec73f689"}' --service-role EMR_DefaultRole --release-label emr-5.11.0 --name 'mya-Dick' --instance-groups '[{"InstanceCount":4,"BidPrice":"1.000","EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":32,"VolumeType":"gp2"},"VolumesPerInstance":1}]},"InstanceGroupType":"CORE","InstanceType":"m2.4xlarge","Name":"CORE"},{"InstanceCount":1,"BidPrice":"1.000","EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":32,"VolumeType":"gp2"},"VolumesPerInstance":1}]},"InstanceGroupType":"MASTER","InstanceType":"m2.4xlarge","Name":"MASTER"}]' --configurations '[{"Classification":"emrfs-site","Properties":{"fs.s3.enableServerSideEncryption":"true"}},{"Classification":"hive-site","Properties":{"apkudo.issue_info.param1":"*********","apkudo.issue_info.param2":"***********","javax.jdo.option.ConnectionUserName":"##MYSQLUSER##","javax.jdo.option.ConnectionDriverName":"org.mariadb.jdbc.Driver","javax.jdo.option.ConnectionPassword":"********","javax.jdo.option.ConnectionURL":"jdbc:mysql://reportingmetastore.citkvbrpfzo2.us-west-2.rds.amazonaws.com:3306/hive?createDatabaseIfNotExist=true"}},{"Classification":"spark","Properties":{"maximizeResourceAllocation":"true"}},{"Classification":"core-site","Properties":{"fs.s3n.awsAccessKeyId":"********","fs.s3.awsAccessKeyId":"********","fs.s3.awsSecretAccessKey":"********","fs.s3.maxConnections":"50000","fs.s3n.awsSecretAccessKey":"********"}}]' --scale-down-behavior TERMINATE_AT_TASK_COMPLETION --region us-west-2`

**Comment by swetashre** [comment]
@Dickmcmanus - Thank you for your post . When i run your command directly in the terminal i don't get that error. 
```
$ aws emr create-cluster --auto-scaling-role EMR_AutoScaling_DefaultRole --applications Name=Spark Name=Hadoop --tags 'Role=Analytics' 'Owner=dom' 'Program=Analytics' 'Environment=PROD' 'Purpose=Analytics' 'Team=Analytics SDK' 'Application=Analytics' 'user=Dick' 'Name=DickCluster' 'Stack=EMRSpark' --ebs-root-volume-size 10 --ec2-attributes '{"KeyName":"DickAnalytics","InstanceProfile":"EMR_EC2_DefaultRole","SubnetId":"subnet-a8a640cd","EmrManagedSlaveSecurityGroup":"sg-ef73f68a","EmrManagedMasterSecurityGroup":"sg-ec73f689"}' --service-role EMR_DefaultRole --release-label emr-5.11.0 --name 'mya-Dick' --instance-groups '[{"InstanceCount":4,"BidPrice":"1.000","EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":32,"VolumeType":"gp2"},"VolumesPerInstance":1}]},"InstanceGroupType":"CORE","InstanceType":"m2.4xlarge","Name":"CORE"},{"InstanceCount":1,"BidPrice":"1.000","EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":32,"VolumeType":"gp2"},"VolumesPerInstance":1}]},"InstanceGroupType":"MASTER","InstanceType":"m2.4xlarge","Name":"MASTER"}]' --configurations '[{"Classification":"emrfs-site","Properties":{"fs.s3.enableServerSideEncryption":"true"}},{"Classification":"hive-site","Properties":{"apkudo.issue_info.param1":"*********","apkudo.issue_info.param2":"***********","javax.jdo.option.ConnectionUserName":"##MYSQLUSER##","javax.jdo.option.ConnectionDriverName":"org.mariadb.jdbc.Driver","javax.jdo.option.ConnectionPassword":"********","javax.jdo.option.ConnectionURL":"jdbc:mysql://reportingmetastore.citkvbrpfzo2.us-west-2.rds.amazonaws.com:3306/hive?createDatabaseIfNotExist=true"}},{"Classification":"spark","Properties":{"maximizeResourceAllocation":"true"}},{"Classification":"core-site","Properties":{"fs.s3n.awsAccessKeyId":"********","fs.s3.awsAccessKeyId":"********","fs.s3.awsSecretAccessKey":"********","fs.s3.maxConnections":"50000","fs.s3n.awsSecretAccessKey":"********"}}]' --scale-down-behavior TERMINATE_AT_TASK_COMPLETION --region us-west-2
{
    "ClusterId": "j-1ZRL5ENS72YNQ"
}
```
Please run the command with ```--debug``` and post the output so that we can know what the exact string CLI is receiving.

**Comment by Dickmcmanus** [comment]
Odd, this is what I got:

`aws emr create-cluster --auto-scaling-role EMR_AutoScaling_DefaultRole --applications Name=Spark Name=Hadoop --tags 'Role=Analytics' 'Owner=dom' 'Program=Analytics' 'Environment=PROD' 'Purpose=Analytics' 'Team=Analy
tics SDK' 'Application=Analytics' 'user=Dick' 'Name=DickCluster' 'Stack=EMRSpark' --ebs-root-volume-size 10 --ec2-attributes '{"KeyName":"DickAnalytics","InstanceProfile":"EMR_EC2_DefaultRole","SubnetId":"subnet-a8a640cd","EmrManagedSlav
eSecurityGroup":"sg-ef73f68a","EmrManagedMasterSecurityGroup":"sg-ec73f689"}' --service-role EMR_DefaultRole --release-label emr-5.11.0 --name 'mya-Dick' --instance-groups '[{"InstanceCount":1,"BidPrice":"1.000","EbsConfiguration":{"EbsB
lockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":32,"VolumeType":"gp2"},"VolumesPerInstance":1}]},"InstanceGroupType":"MASTER","InstanceType":"m2.4xlarge","Name":"MASTER"},{"InstanceCount":4,"BidPrice":"1.000","EbsConfiguration":{"
EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":32,"VolumeType":"gp2"},"VolumesPerInstance":1}]},"InstanceGroupType":"CORE","InstanceType":"m2.4xlarge","Name":"CORE"}]' --configurations '[{"Classification":"emrfs-site","Proper
ties":{"fs.s3.enableServerSideEncryption":"true"}},{"Classification":"hive-site","Properties":{"apkudo.issue_info.param1":"*********","apkudo.issue_info.param2":"***********","javax.jdo.option.ConnectionUserName":"##MYSQLUSER##","javax.j
do.option.ConnectionDriverName":"org.mariadb.jdbc.Driver","javax.jdo.option.ConnectionPassword":"********","javax.jdo.option.ConnectionURL":"jdbc:mysql://reportingmetastore.citkvbrpfzo2.us-west-2.rds.amazonaws.com:3306/hive?createDatabas
eIfNotExist=true"}},{"Classification":"spark","Properties":{"maximizeResourceAllocation":"true"}},{"Classification":"core-site","Properties":{"fs.s3n.awsAccessKeyId":"********","fs.s3.awsAccessKeyId":"********","fs.s3.awsSecretAccessKey"
:"********","fs.s3.maxConnections":"50000","fs.s3n.awsSecretAccessKey":"********"}}]' --scale-down-behavior TERMINATE_AT_TASK_COMPLETION --region us-west-2 --debug
2019-04-12 10:44:08,521 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.16.140 Python/3.6.0 Windows/10 botocore/1.12.130
2019-04-12 10:44:08,522 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['emr', 'create-cluster', '--auto-scaling-role', 'EMR_AutoScaling_DefaultRole', '--applications', 'Name=Spark', 'Name=Hadoop', '--tags', 'Role=Analytics', 'Owner=dom', 'Program=Analytics', 'Environment=PROD', 'Purpose=Analytics', 'Team=Analytics SDK', 'Application=Analytics', 'user=Dick', 'Name=DickCluster', 'Stack=EMRSpark', '--ebs-root-volume-size', '10', '--ec2-attributes', '{KeyName:DickAnalytics,InstanceProfile:EMR_EC2_DefaultRole,SubnetId:subnet-a8a640cd,EmrManagedSlaveSecurityGroup:sg-ef73f68a,EmrManagedMasterSecurityGroup:sg-ec73f689}', '--service-role', 'EMR_DefaultRole', '--release-label', 'emr-5.11.0', '--name', 'mya-Dick', '--instance-groups', '[{InstanceCount:1,BidPrice:1.000,EbsConfiguration:{EbsBlockDeviceConfigs:[{VolumeSpecification:{SizeInGB:32,VolumeType:gp2},VolumesPerInstance:1}]},InstanceGroupType:MASTER,InstanceType:m2.4xlarge,Name:MASTER},{InstanceCount:4,BidPrice:1.000,EbsConfiguration:{EbsBlockDeviceConfigs:[{VolumeSpecification:{SizeInGB:32,VolumeType:gp2},VolumesPerInstance:1}]},InstanceGroupType:CORE,InstanceType:m2.4xlarge,Name:CORE}]', '--configurations', '[{Classification:emrfs-site,Properties:{fs.s3.enableServerSideEncryption:true}},{Classification:hive-site,Properties:{apkudo.issue_info.param1:*********,apkudo.issue_info.param2:***********,javax.jdo.option.ConnectionUserName:##MYSQLUSER##,javax.jdo.option.ConnectionDriverName:org.mariadb.jdbc.Driver,javax.jdo.option.ConnectionPassword:********,javax.jdo.option.ConnectionURL:jdbc:mysql://reportingmetastore.citkvbrpfzo2.us-west-2.rds.amazonaws.com:3306/hive?createDatabaseIfNotExist=true}},{Classification:spark,Properties:{maximizeResourceAllocation:true}},{Classification:core-site,Properties:{fs.s3n.awsAccessKeyId:********,fs.s3.awsAccessKeyId:********,fs.s3.awsSecretAccessKey:********,fs.s3.maxConnections:50000,fs.s3n.awsSecretAccessKey:********}}]', '--scale-down-behavior', 'TERMINATE_AT_TASK_COMPLETION', '--region', 'us-west-2', '--debug']
2019-04-12 10:44:08,522 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x00000246E7600F28>
2019-04-12 10:44:08,522 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x00000246E7150598>
2019-04-12 10:44:08,523 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x00000246E6F5B950>
2019-04-12 10:44:08,686 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x00000246E7455A60>
2019-04-12 10:44:08,687 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\botocore\data\emr\2009-03-31\service-2.json
2019-04-12 10:44:08,701 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.emr: calling handler <function register_retries_for_service at 0x00000246E6E118C8>
2019-04-12 10:44:08,701 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: emr
2019-04-12 10:44:08,702 - MainThread - botocore.hooks - DEBUG - Event building-command-table.emr: calling handler functools.partial(<function _remove_commands at 0x00000246E75D0620>, commands_to_remove=['run-job-flow', 'describe-job-flows', 'add-job-flow-steps', 'terminate-job-flows', 'list-bootstrap-actions', 'list-instance-groups', 'set-termination-protection', 'set-visible-to-all-users'])
2019-04-12 10:44:08,711 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: run-job-flow
2019-04-12 10:44:08,713 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: describe-job-flows
2019-04-12 10:44:08,714 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: add-job-flow-steps
2019-04-12 10:44:08,721 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: terminate-job-flows
2019-04-12 10:44:08,721 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: list-bootstrap-actions
2019-04-12 10:44:08,722 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: list-instance-groups
2019-04-12 10:44:08,725 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: set-termination-protection
2019-04-12 10:44:08,725 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: set-visible-to-all-users
2019-04-12 10:44:08,732 - MainThread - botocore.hooks - DEBUG - Event building-command-table.emr: calling handler <function register_commands at 0x00000246E74FA6A8>
2019-04-12 10:44:08,733 - MainThread - botocore.hooks - DEBUG - Event building-command-table.emr: calling handler <function add_waiters at 0x00000246E760B488>
2019-04-12 10:44:08,798 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\botocore\data\emr\2009-03-31\waiters-2.json
2019-04-12 10:44:08,800 - MainThread - botocore.hooks - DEBUG - Event building-command-table.create-cluster: calling handler <function add_waiters at 0x00000246E760B488>
2019-04-12 10:44:08,801 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.emr.create-cluster: calling handler <function override_args_required_option at 0x00000246E737C048>
2019-04-12 10:44:08,810 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.create-cluster.release-label: calling handler <awscli.paramfile.URIArgumentHandler object at 0x00000246E6050D68>
2019-04-12 10:44:08,811 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.create-cluster: calling handler <awscli.argprocess.ParamShorthandParser object at 0x00000246E71738D0>
2019-04-12 10:44:08,811 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.create-cluster.ami-version: calling handler <awscli.paramfile.URIArgumentHandler object at 0x00000246E6050D68>
2019-04-12 10:44:08,819 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.create-cluster.instance-groups: calling handler <awscli.paramfile.URIArgumentHandler object at 0x00000246E6050D68>
2019-04-12 10:44:08,823 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.create-cluster: calling handler <awscli.argprocess.ParamShorthandParser object at 0x00000246E71738D0>
2019-04-12 10:44:08,831 - MainThread - awscli.argprocess - DEBUG - Param instance_groups looks like JSON, not considered for param shorthand.
2019-04-12 10:44:08,835 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\clidriver.py", line 207, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\clidriver.py", line 348, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\customizations\commands.py", line 174, in __call__
    value = unpack_cli_arg(cli_argument, value)
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\argprocess.py", line 143, in unpack_cli_arg
    cli_argument.cli_name)
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\argprocess.py", line 163, in _unpack_cli_arg
    argument_model, value, cli_name)
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\argprocess.py", line 195, in _unpack_complex_cli_arg
    return json.loads(value[0], object_pairs_hook=OrderedDict)
  File "json\__init__.py", line 367, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
2019-04-12 10:44:08,844 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Expecting property name enclosed in double quotes: line 1 column 3 (char 2)`

**Comment by swetashre** [comment]
@Dickmcmanus - Thank you for your reply. I was executing the command in mac OS that's why i was not getting that error. When running CLI commands on windows please follow these steps.
1. Replace all ```"``` inside json string with ```\"``` while passing json value as parameter.
2. For windows cmd shell Replace all ```'``` with ```"```.  

Note: Step 2 is not required for Powershell.

This is the final command after applying the above steps and this fixes the issue.

`
aws emr create-cluster --auto-scaling-role EMR_AutoScaling_DefaultRole --applications Name=Spark Name=Hadoop --tags "Role=Analytics" "Owner=dom" "Program=Analytics" "Environment=PROD" "Purpose=Analytics" "Team=Analytics SDK" "Application=Analytics" "user=Dick" "Name=DickCluster" "Stack=EMRSpark" --ebs-root-volume-size 10 --ec2-attributes "{\"KeyName\":\"DickAnalytics\",\"InstanceProfile\":\"EMR_EC2_DefaultRole\",\"SubnetId\":\"subnet-a8a640cd\",\"EmrManagedSlaveSecurityGroup\":\"sg-ef73f68a\",\"EmrManagedMasterSecurityGroup\":\"sg-ec73f689\"}" --service-role EMR_DefaultRole --release-label emr-5.11.0 --name "mya-Dick" --instance-groups "[{\"InstanceCount\":4,\"BidPrice\":\"1.000\",\"EbsConfiguration\":{\"EbsBlockDeviceConfigs\":[{\"VolumeSpecification\":{\"SizeInGB\":32,\"VolumeType\":\"gp2\"},\"VolumesPerInstance\":1}]},\"InstanceGroupType\":\"CORE\",\"InstanceType\":\"m2.4xlarge\",\"Name\":\"CORE\"},{\"InstanceCount\":1,\"BidPrice\":\"1.000\",\"EbsConfiguration\":{\"EbsBlockDeviceConfigs\":[{\"VolumeSpecification\":{\"SizeInGB\":32,\"VolumeType\":\"gp2\"},\"VolumesPerInstance\":1}]},\"InstanceGroupType\":\"MASTER\",\"InstanceType\":\"m2.4xlarge\",\"Name\":\"MASTER\"}]" --configurations "[{\"Classification\":\"emrfs-site\",\"Properties\":{\"fs.s3.enableServerSideEncryption\":\"true\"}},{\"Classification\":\"hive-site\",\"Properties\":{\"apkudo.issue_info.param1\":\"*********\",\"apkudo.issue_info.param2\":\"***********\",\"javax.jdo.option.ConnectionUserName\":\"##MYSQLUSER##\",\"javax.jdo.option.ConnectionDriverName\":\"org.mariadb.jdbc.Driver\",\"javax.jdo.option.ConnectionPassword\":\"********\",\"javax.jdo.option.ConnectionURL\":\"jdbc:mysql://reportingmetastore.citkvbrpfzo2.us-west-2.rds.amazonaws.com:3306/hive?createDatabaseIfNotExist=true\"}},{\"Classification\":\"spark\",\"Properties\":{\"maximizeResourceAllocation\":\"true\"}},{\"Classification\":\"core-site\",\"Properties\":{\"fs.s3n.awsAccessKeyId\":\"********\",\"fs.s3.awsAccessKeyId\":\"********\",\"fs.s3.awsSecretAccessKey\":\"********\",\"fs.s3.maxConnections\":\"50000\",\"fs.s3n.awsSecretAccessKey\":\"********\"}}]" --scale-down-behavior TERMINATE_AT_TASK_COMPLETION --region us-west-2
`

**Comment by Dickmcmanus** [comment]
That is terrifying, but unsurprising, and more importantly works.

Thank you.
