### ISSUE TITLE
'dict' object has no attribute 'startswith' in cloudformation package

### ISSUE THREAD

**Issue by jimcatts** [aws/aws-cli#4087]
After updating to the latest version of the aws cli (1.16.144), CI/CD processes that had been stable for over a year are now consistently failing with the following error:

'dict' object has no attribute 'startswith'

when running:

aws cloudformation package --template-file ./foo.yaml --output-template-file ./bar.yaml --s3-bucket foo --s3-prefix bar --region us-east-1

**Comment by tedweb** [comment]
I have recently run into this issue too.  Any ideas?

**Comment by KarlGrear** [comment]
Temporary work around:

pip install awscli==1.16.141"  instead of "- pip install --upgrade awscli"

**Comment by tedweb** [comment]
Thanks KarlGrear!

**Comment by danPudwellUK** [comment]
Having a similar issue and looks like I can use 1.16.143.  Stack trace if it helps:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/awscli/clidriver.py", line 207, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python3.7/site-packages/awscli/clidriver.py", line 348, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python3.7/site-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/usr/local/lib/python3.7/site-packages/awscli/customizations/cloudformation/package.py", line 151, in _run_main
    exported_str = self._export(template_path, use_json)
  File "/usr/local/lib/python3.7/site-packages/awscli/customizations/cloudformation/package.py", line 167, in _export
    exported_template = template.export()
  File "/usr/local/lib/python3.7/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 604, in export
    self.template_dict = self.export_global_artifacts(self.template_dict)
  File "/usr/local/lib/python3.7/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 563, in export_global_artifacts
    self.export_global_artifacts(val)
  File "/usr/local/lib/python3.7/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 563, in export_global_artifacts
    self.export_global_artifacts(val)
  File "/usr/local/lib/python3.7/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 563, in export_global_artifacts
    self.export_global_artifacts(val)
  File "/usr/local/lib/python3.7/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 561, in export_global_artifacts
    template_dict[key] = GLOBAL_EXPORT_DICT[key](val, self.uploader, self.template_dir)
  File "/usr/local/lib/python3.7/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 506, in include_transform_export_handler
    abs_include_location = os.path.join(parent_dir, include_location)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'OrderedDict'
2019-04-23 15:36:45,172 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255
```
Will this be fixed for 1.16.145?

**Comment by justasitsounds** [comment]
I'm also seeing the same issue. Unfortunately my CI provider doesn't make it easy to target specific AWS CLI versions and this is proving really unfortunate

**Comment by justnance** [comment]
Cross referencing #4099 and looping in @sanathkr.

**Comment by sanathkr** [comment]
Working on a fix for this now..

**Comment by spitzzz** [comment]
Having this same issue, using the latest version of the AWS CLI, and the latest version of the SAM CLI. Running on this docker image `lambci/lambda:build-dotnetcore2.1`

```
bash-4.2# aws --version
aws-cli/1.16.158 Python/2.7.16 Linux/4.9.125-linuxkit exec-env/AWS_Lambda_dotnetcore2.1 botocore/1.12.148
bash-4.2# sam --version
SAM CLI, version 0.16.0
```

Getting this error when using `sam package` or `aws cloudformation package`
```
'OrderedDict' object has no attribute 'startswith'
```

**Comment by binli0114** [comment]
aws-cli/1.16.144 Python/2.7.15 Darwin/18.5.0 botocore/1.12.134
SAM CLI, version 0.15.0

@KarlGrear workaround also works for me

**Comment by SamBrick** [comment]
Hello, any idea of a timeframe for fixing this? We're in a situation where we are only able to use the latest version of the cli provided by AWS. This is blocking our ability to deploy.
