### ISSUE TITLE
'TypeError: > not supported' prior to sam local invoke

### ISSUE THREAD

**Issue by ronaldwidha** [aws/aws-cli#4129]
I am getting an error prior to container execution `sam local invoke`. The function itself executed fine.

Error message is
```
2019-05-04 20:40:07 Found credentials in shared credentials file: ~/.aws/credentials
2019-05-04 20:40:07 Invoking index.handler (nodejs8.10)

Fetching lambci/lambda:nodejs8.10 Docker container image......
2019-05-04 20:40:07 Mounting /***/web/amplify/backend/function/LambdaFunction/src as /var/task:ro,delegated inside runtime container
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1164, in run
    self.finished.wait(self.interval)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 299, in wait
    if timeout > 0:
TypeError: '>' not supported between instances of 'str' and 'int'
```

Worth noting that I don't have Python 2 installed, nor virtualenv. Also, I'm not using SAM, since the function was created and is managed by AWS Amplify.

**Comment by justnance** [comment]
@ronaldwidha - Thanks for reporting this is issue.  It looks like this command is used under the [SAM CLI](https://github.com/awslabs/aws-sam-cli) which is a different repository than the AWS CLI.  After doing a search in the [SAM CLI repo for this error](https://github.com/awslabs/aws-sam-cli/issues?utf8=%E2%9C%93&q=is%3Aissue+%22TypeError%3A+%27%3E%27+not+supported+between+instances+of+%27str%27+and+%22), I found the error might be related to SAM CLI issues [#1116](https://github.com/awslabs/aws-sam-cli/issues/1116) and [#925](https://github.com/awslabs/aws-sam-cli/issues/925).  

I am closing this issue and recommend posting this error in the SAM CLI repo.
