### ISSUE TITLE
When attempting to use the cli in python, cannot use --include

### ISSUE THREAD

**Issue by queglay** [aws/aws-cli#4131]
I am able to succesfully sync a folder in python with the cli, but when I use --include, it fails with
```
Traceback (most recent call last):
  File "s3_cli_sync.py", line 26, in <module>
    aws_cli(['s3', 'sync', '/prod/debug/debug/0230/houdini', 's3://test.testdomain.com/testdir', '--include debug_debug_0230_wrk_dynamicworkrecook_v007.000_ag_wedge_object_tests.hip'])
  File "s3_cli_sync.py", line 20, in aws_cli
    raise RuntimeError('AWS CLI exited with code {}'.format(exit_code))
RuntimeError: AWS CLI exited with code 255
```
Here is the example code in Python 2.7.5

```
import os
from awscli.clidriver import create_clidriver


def aws_cli(*cmd):
    old_env = dict(os.environ)
    try:

        # Environment
        env = os.environ.copy()
        env['LC_CTYPE'] = u'en_US.UTF'
        os.environ.update(env)

        # Run awscli in the same process
        exit_code = create_clidriver().main(*cmd)

        # Deal with problems
        if exit_code > 0:
            raise RuntimeError('AWS CLI exited with code {}'.format(exit_code))
    finally:
        os.environ.clear()
        os.environ.update(old_env)


aws_cli(['s3', 'sync', '/prod/debug/debug/0230/houdini', 's3://test.testdomain.com/testdir', '--include debug_debug_0230_wrk_dynamicworkrecook_v007.000_ag_wedge_object_tests.hip'])
```

**Comment by queglay** [comment]
I realised '--include debug_debug_0230_wrk_dynamicworkrecook_v007.000_ag_wedge_object_tests.hip'

needed to be '--include', 'debug_debug_0230_wrk_dynamicworkrecook_v007.000_ag_wedge_object_tests.hip'
