### ISSUE TITLE
Unable to parse text file on Windows if text file has UTF-8 unicode

### ISSUE THREAD

**Issue by shenlong** [aws/aws-cli#4134]
Trying to synthesize with Amazon Polly:
`
aws polly synthesize-speech --text-type ssml --text file://example.xml --output-format mp3 --voice-id Zhiyu speech.mp3
`

example.xml contents:
```
<?xml version="1.0" ?>
<speak version="1.1" 
    xmlns="http://www.w3.org/2001/10/synthesis"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.w3.org/2001/10/synthesis http://www.w3.org/TR/speech-synthesis11/synthesis.xsd" 
    xml:lang="cmn-CN">
	<prosody rate="85%">东南1</prosody>
</speak>
```

Got the error:
```
Error parsing parameter '--text': Unable to load paramfile (Pg32_20170602.xml), text contents could not be decoded.  If this is a binary file, please use the fileb:// prefix instead of the file:// prefix.
```
This works though: 
`
aws polly synthesize-speech --text-type ssml --text "<speak><prosody rate='85%'>东南1</prosody></speak>" --output-format mp3 --voice-id Zhiyu speech.mp3
`

Any idea on this?

**Comment by justnance** [comment]
@shenlong -  Thank you for reporting this issue.  I have tried to reproduce the same results under the following versions of the CLI:  
```
aws-cli/1.16.146 Python/3.7.0 Darwin/16.7.0 botocore/1.12.136
```
and
```
aws-cli/1.16.173 Python/3.7.0 Darwin/16.7.0 botocore/1.12.163
```
I used the following commands:

```
aws polly synthesize-speech --text-type ssml --text file://example.xml --output-format mp3 --voice-id Zhiyu speech.mp3
```
```
aws polly synthesize-speech --text-type ssml --text "<speak><prosody rate='85%'>东南1</prosody></speak>" --output-format mp3 --voice-id Zhiyu speech.mp3
```

Both commands under different versions of the CLI returns expected results.  Please reply with a sanitized output of the `--debug` option so I can take a look at what is happening. 

```
aws polly synthesize-speech --text-type ssml --text file://example.xml --output-format mp3 --voice-id Zhiyu speech.mp3 --debug
```

**Comment by shenlong** [comment]
I still having issue:
![image](https://user-images.githubusercontent.com/953106/59083428-eaf37900-8929-11e9-9a11-0ee546a88671.png)

I wonder if it is because I am using Windows?

**Comment by shenlong** [comment]
Debug trace as follows:

```
C:\test>aws polly synthesize-speech --text-type ssml --text file://example.xml --output-format mp3 --voice-id Zhiyu speech.mp3 --debug
2019-06-07 13:42:24,016 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.16.39 Python/3.6.0 Windows/10 botocore/1.12.29
2019-06-07 13:42:24,017 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['polly', 'synthesize-speech', '--text-type', 'ssml', '--text', 'file://example.xml', '--output-format', 'mp3', '--voice-id', 'Zhiyu', 'speech.mp3', '--debug']
2019-06-07 13:42:24,018 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x000002A0D6FEEA60>
2019-06-07 13:42:24,019 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2019-06-07 13:42:24,019 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x000002A0D6BBCD08>
2019-06-07 13:42:24,019 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2019-06-07 13:42:24,020 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x000002A0D6C0ED08>
2019-06-07 13:42:24,020 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2019-06-07 13:42:24,021 - MainThread - botocore.session - DEBUG - Loading variable credentials_file from defaults.
2019-06-07 13:42:24,022 - MainThread - botocore.session - DEBUG - Loading variable config_file from defaults.
2019-06-07 13:42:24,023 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2019-06-07 13:42:24,024 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_timeout from defaults.
2019-06-07 13:42:24,024 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2019-06-07 13:42:24,025 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_num_attempts from defaults.
2019-06-07 13:42:24,719 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2019-06-07 13:42:24,719 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x000002A0D6EC0620>
2019-06-07 13:42:24,722 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2019-06-07 13:42:24,723 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2019-06-07 13:42:24,725 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2019-06-07 13:42:24,728 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\botocore\data\polly\2016-06-10\service-2.json
2019-06-07 13:42:24,732 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.polly: calling handler <function register_retries_for_service at 0x000002A0D67F1F28>
2019-06-07 13:42:24,734 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: polly
2019-06-07 13:42:24,735 - MainThread - botocore.hooks - DEBUG - Event building-command-table.polly: calling handler <function add_waiters at 0x000002A0D6FF4C80>
2019-06-07 13:42:24,811 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('lexicon-names', <awscli.arguments.ListArgument object at 0x000002A0D710DB38>), ('output-format', <awscli.arguments.CLIArgument object at 0x000002A0D710DBA8>), ('sample-rate', <awscli.arguments.CLIArgument object at 0x000002A0D710DC18>), ('speech-mark-types', <awscli.arguments.ListArgument object at 0x000002A0D710DC88>), ('text', <awscli.arguments.CLIArgument object at 0x000002A0D710DCC0>), ('text-type', <awscli.arguments.CLIArgument object at 0x000002A0D710DCF8>), ('voice-id', <awscli.arguments.CLIArgument object at 0x000002A0D710DD30>), ('language-code', <awscli.arguments.CLIArgument object at 0x000002A0D710DD68>)])
2019-06-07 13:42:24,812 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.polly.synthesize-speech: calling handler <function add_streaming_output_arg at 0x000002A0D6FEED08>
2019-06-07 13:42:24,815 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.polly.synthesize-speech: calling handler <function add_cli_input_json at 0x000002A0D6C182F0>
2019-06-07 13:42:24,816 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.polly.synthesize-speech: calling handler <function unify_paging_params at 0x000002A0D6F68D08>
2019-06-07 13:42:24,910 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\botocore\data\polly\2016-06-10\paginators-1.json
2019-06-07 13:42:24,912 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.polly.synthesize-speech: calling handler <function add_generate_skeleton at 0x000002A0D6F44950>
2019-06-07 13:42:24,915 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.polly.synthesize-speech.lexicon-names: calling handler <awscli.paramfile.URIArgumentHandler object at 0x000002A0D5D9A4E0>
2019-06-07 13:42:24,916 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.polly.synthesize-speech.output-format: calling handler <awscli.paramfile.URIArgumentHandler object at 0x000002A0D5D9A4E0>
2019-06-07 13:42:24,917 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.polly.synthesize-speech: calling handler <awscli.argprocess.ParamShorthandParser object at 0x000002A0D6BDF4A8>
2019-06-07 13:42:24,917 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'mp3' for parameter "output_format": 'mp3'
2019-06-07 13:42:24,918 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.polly.synthesize-speech.sample-rate: calling handler <awscli.paramfile.URIArgumentHandler object at 0x000002A0D5D9A4E0>
2019-06-07 13:42:24,919 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.polly.synthesize-speech.speech-mark-types: calling handler <awscli.paramfile.URIArgumentHandler object at 0x000002A0D5D9A4E0>
2019-06-07 13:42:24,920 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.polly.synthesize-speech.text: calling handler <awscli.paramfile.URIArgumentHandler object at 0x000002A0D5D9A4E0>
2019-06-07 13:42:24,922 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\paramfile.py", line 216, in get_file
    return f.read()
  File "encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 321: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\paramfile.py", line 175, in _check_for_uri_param
    return get_paramfile(value, self._prefixes)
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\paramfile.py", line 208, in get_paramfile
    data = function(prefix, path, **kwargs)
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\paramfile.py", line 221, in get_file
    'fileb:// prefix instead of the file:// prefix.' % file_path)
awscli.paramfile.ResourceLoadingError: Unable to load paramfile (example.xml), text contents could not be decoded.  If this is a binary file, please use the fileb:// prefix instead of the file:// prefix.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\clidriver.py", line 207, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\clidriver.py", line 344, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\clidriver.py", line 487, in __call__
    parsed_args, self.arg_table)
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\clidriver.py", line 542, in _build_call_parameters
    value = self._unpack_arg(arg_object, value)
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\clidriver.py", line 554, in _unpack_arg
    cli_argument, value)
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\argprocess.py", line 81, in unpack_argument
    operation_name=operation_name)
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\botocore\session.py", line 728, in emit_first_non_none_response
    responses = self._events.emit(event_name, **kwargs)
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\botocore\hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\botocore\hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\paramfile.py", line 169, in __call__
    return self._check_for_uri_param(cli_argument, value)
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\paramfile.py", line 177, in _check_for_uri_param
    raise ParamError(param.cli_name, six.text_type(e))
awscli.argprocess.ParamError: Error parsing parameter '--text': Unable to load paramfile (example.xml), text contents could not be decoded.  If this is a binary file, please use the fileb:// prefix instead of the file:// prefix.
2019-06-07 13:42:24,977 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Error parsing parameter '--text': Unable to load paramfile (example.xml), text contents could not be decoded.  If this is a binary file, please use the fileb:// prefix instead of the file:// prefix.
```

**Comment by methane** [comment]
@justnance This is because `get_file` doesn't specify encoding option.
The default encoding is based on locale.  It is UTF-8 on mac, but it is not UTF-8 on most Windows.

@shenlong If you are using Python 3.7, you can override the default encoding by UTF-8 mode.
Try `set PYTHONUTF8=1` before using awscli.

**Comment by joguSD** [comment]
@methane's suggestion is spot on. We don't specify the default encoding and instead allow it to be inferred from the host. Did his suggestion work?

**Comment by methane** [comment]
@joguSD I think it's a bad idea that using environment encoding for text files downloaded from the internet.  UTF-8 is the standard encoding for the internet.

**Comment by mhosseinab** [comment]
The problem still persists.
```
python -c 'import sys; print(sys.getdefaultencoding())'
utf-8
```
```
aws --version
aws-cli/1.17.7 Python/3.8.1 Windows/10 botocore/1.14.7
```
```
aws ses create-template --cli-input-json file://template.json
Error parsing parameter '--cli-input-json': Unable to load paramfile (template.json), text contents could not be decoded.  If this is a binary file, please use the fileb:// prefix instead of the file:// prefix.
```

**Comment by methane** [comment]
`sys.getdefaultencoding()` is not default encoding forr text files.  `locale.getpreferredencoding()` is used.
Try `set PYTHONUTF8=1`.  It enables UTF-8 mode and it changes the `locale.getpreferredencoding()`.

**Comment by ivancho1707** [comment]
I had the same problem i two different situations using aws client both in Linux, one was developing in my local machine, in which case the problem solved by setting the `PYTHONUTF8` envar to `1`, and in other occasion running a Jenkins job that executed a build script in python in which case the solution was setting `LANG` envvar to one of the available (`locale -a`) installed locales that support `UTF-8`, there is more than one way to do it, for session, for user, for all users. Check the docs and pick the one that suits you the best.

**Comment by Zeeeeta** [comment]
I got the following error when doing `aws dynamodb batch-write-item --request-items file://xxx.json` in a windows .bat where the json file contains unicode char.
```
Error parsing parameter '--request-items': Unable to load paramfile (xxx.json), text contents could not be decoded.  If this is a binary file, please use the fileb:// prefix instead of the file:// prefix.
```

Adding --debug shows the following
```
2020-03-27 12:23:08,369 - MainThread - awscli.clidriver - DEBUG - Client side parameter validation failed
Traceback (most recent call last):
  File "lib\site-packages\awscli\paramfile.py", line 86, in get_file
UnicodeDecodeError: 'cp950' codec can't decode byte 0x96 in position 218: illegal multibyte sequence
```
Tried adding the following but none of them helps
```
CHCP 65001
set PYTHONUTF8=1
set PYTHONIOENCODING=UTF-8
```

Obviously I should **NOT** try to modify the python script and add ```, encoding='utf8'``` to the params of open()

I could only save the json as ANSI to get it works currently.
Any help would be much appreciated, thanks.

I am on Win10 with latest AWSCLI2
aws-cli/2.0.5 Python/3.7.5 Windows/10 botocore/2.0.0dev9

**Comment by methane** [comment]
It seems `PYTHONUTF8` doesn't work since aws-cli v2.
