### ISSUE TITLE
Unable to run local invoke - HTTPError: 400

### ISSUE THREAD

**Issue by peppekristen** [aws/aws-cli#4184]
Hi guys, when trying to using the command sam local invoke i got the following output and error. I installed docker, created and added my user to the group, I am able to run example with the command start-api but when trying to invoke it doesn't work.

giuseppe@giuseppe-pc:~/Downloads/Lubuntu/AWS-SAM-CLI/helloWorld$ sam local invoke --no-event --debug
2019-05-23 14:44:46 Using SAM Template at /home/giuseppe/Downloads/Lubuntu/AWS-SAM-CLI/helloWorld/template.yaml
2019-05-23 14:44:46 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2019-05-23 14:44:46 Changing event name from before-call.apigateway to before-call.api-gateway
2019-05-23 14:44:46 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2019-05-23 14:44:46 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2019-05-23 14:44:46 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2019-05-23 14:44:46 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2019-05-23 14:44:46 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2019-05-23 14:44:46 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2019-05-23 14:44:46 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2019-05-23 14:44:46 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2019-05-23 14:44:46 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2019-05-23 14:44:46 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2019-05-23 14:44:46 Changing event name from before-call.apigateway to before-call.api-gateway
2019-05-23 14:44:46 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2019-05-23 14:44:46 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2019-05-23 14:44:46 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2019-05-23 14:44:46 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2019-05-23 14:44:46 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2019-05-23 14:44:46 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2019-05-23 14:44:46 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2019-05-23 14:44:46 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2019-05-23 14:44:46 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2019-05-23 14:44:46 local invoke command is called
2019-05-23 14:44:46 No Parameters detected in the template
2019-05-23 14:44:46 1 resources found in the template
2019-05-23 14:44:46 Found Serverless function with name='HelloWorldFunction' and CodeUri='hello-world/'
2019-05-23 14:44:46 Trying paths: ['/home/giuseppe/.docker/config.json', '/home/giuseppe/.dockercfg']
2019-05-23 14:44:46 No config file found
2019-05-23 14:44:46 Trying paths: ['/home/giuseppe/.docker/config.json', '/home/giuseppe/.dockercfg']
2019-05-23 14:44:46 No config file found
2019-05-23 14:44:46 http://localhost:None "GET /v1.35/_ping HTTP/1.1" 200 2
2019-05-23 14:44:46 Looking for credentials via: env
2019-05-23 14:44:46 Looking for credentials via: assume-role
2019-05-23 14:44:46 Looking for credentials via: shared-credentials-file
2019-05-23 14:44:46 Found credentials in shared credentials file: ~/.aws/credentials
2019-05-23 14:44:46 Loading JSON file: /home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/botocore/data/endpoints.json
2019-05-23 14:44:46 Event choose-service-name: calling handler <function handle_service_name_alias at 0x7ff45bd52048>
2019-05-23 14:44:46 Loading JSON file: /home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/botocore/data/lambda/2015-03-31/service-2.json
2019-05-23 14:44:46 Event creating-client-class.lambda: calling handler <function add_generate_presigned_url at 0x7ff45be0bae8>
2019-05-23 14:44:46 The s3 config key is not a dictionary type, ignoring its value of: None
2019-05-23 14:44:46 Setting lambda timeout as (60, 60)
2019-05-23 14:44:46 Loading JSON file: /home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/botocore/data/_retry.json
2019-05-23 14:44:46 Registering retry handlers for service: lambda
2019-05-23 14:44:46 Trying paths: ['/home/giuseppe/.docker/config.json', '/home/giuseppe/.dockercfg']
2019-05-23 14:44:46 No config file found
2019-05-23 14:44:46 Trying paths: ['/home/giuseppe/.docker/config.json', '/home/giuseppe/.dockercfg']
2019-05-23 14:44:46 No config file found
2019-05-23 14:44:46 Found one Lambda function with name 'HelloWorldFunction'
2019-05-23 14:44:46 Invoking app.handler (nodejs8.10)
2019-05-23 14:44:46 No environment variables found for function 'HelloWorldFunction'
2019-05-23 14:44:46 Environment variables overrides data is standard format
2019-05-23 14:44:46 Loading AWS credentials from session with profile 'default'
2019-05-23 14:44:46 Resolving code path. Cwd=/home/giuseppe/Downloads/Lubuntu/AWS-SAM-CLI/helloWorld, CodeUri=hello-world/
2019-05-23 14:44:46 Resolved absolute path to code is /home/giuseppe/Downloads/Lubuntu/AWS-SAM-CLI/helloWorld/hello-world
2019-05-23 14:44:46 Code /home/giuseppe/Downloads/Lubuntu/AWS-SAM-CLI/helloWorld/hello-world is not a zip/jar file
2019-05-23 14:44:46 Skipping building an image since no layers were defined
2019-05-23 14:44:46 Trying paths: ['/home/giuseppe/.docker/config.json', '/home/giuseppe/.dockercfg']
2019-05-23 14:44:46 No config file found
2019-05-23 14:44:46 Trying paths: ['/home/giuseppe/.docker/config.json', '/home/giuseppe/.dockercfg']
2019-05-23 14:44:46 No config file found
2019-05-23 14:44:46 http://localhost:None "GET /v1.35/images/lambci/lambda:nodejs8.10/json HTTP/1.1" 200 None
2019-05-23 14:44:46 Looking for auth config
2019-05-23 14:44:46 No auth config in memory - loading from filesystem
2019-05-23 14:44:46 Trying paths: ['/home/giuseppe/.docker/config.json', '/home/giuseppe/.dockercfg']
2019-05-23 14:44:46 No config file found
2019-05-23 14:44:46 Looking for auth entry for 'docker.io'
2019-05-23 14:44:46 No entry found
2019-05-23 14:44:46 No auth config found
2019-05-23 14:44:47 http://localhost:None "POST /v1.35/images/create?tag=nodejs8.10&fromImage=lambci%2Flambda HTTP/1.1" 200 None

Fetching lambci/lambda:nodejs8.10 Docker container image......
2019-05-23 14:44:47 Mounting /home/giuseppe/Downloads/Lubuntu/AWS-SAM-CLI/helloWorld/hello-world as /var/task:ro,delegated inside runtime container
2019-05-23 14:44:47 http://localhost:None "POST /v1.35/containers/create HTTP/1.1" 201 201
2019-05-23 14:44:47 http://localhost:None "GET /v1.35/containers/cce3a486eb0c951e582060b7c33d3db74697bc3a8c0a311d20364ebe6bdd373a/json HTTP/1.1" 200 None
2019-05-23 14:44:47 http://localhost:None "GET /v1.35/containers/cce3a486eb0c951e582060b7c33d3db74697bc3a8c0a311d20364ebe6bdd373a/json HTTP/1.1" 200 None
2019-05-23 14:44:48 http://localhost:None "POST /v1.35/containers/cce3a486eb0c951e582060b7c33d3db74697bc3a8c0a311d20364ebe6bdd373a/start HTTP/1.1" 400 190
2019-05-23 14:44:48 http://localhost:None "GET /v1.35/containers/cce3a486eb0c951e582060b7c33d3db74697bc3a8c0a311d20364ebe6bdd373a/json HTTP/1.1" 200 None
2019-05-23 14:44:48 http://localhost:None "DELETE /v1.35/containers/cce3a486eb0c951e582060b7c33d3db74697bc3a8c0a311d20364ebe6bdd373a?v=False&link=False&force=True HTTP/1.1" 204 0
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.35/containers/cce3a486eb0c951e582060b7c33d3db74697bc3a8c0a311d20364ebe6bdd373a/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/sam", line 11, in <module>
    load_entry_point('aws-sam-cli==0.16.1', 'console_scripts', 'sam')()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/samcli/commands/local/invoke/cli.py", line 56, in cli
    parameter_overrides)  # pragma: no cover
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/samcli/commands/local/invoke/cli.py", line 99, in do_cli
    stderr=context.stderr)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/samcli/commands/local/lib/local_lambda.py", line 89, in invoke
    self.local_runtime.invoke(config, event, debug_context=self.debug_context, stdout=stdout, stderr=stderr)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/samcli/local/lambdafn/runtime.py", line 86, in invoke
    self._container_manager.run(container)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/samcli/local/docker/manager.py", line 98, in run
    container.start(input_data=input_data)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/samcli/local/docker/container.py", line 187, in start
    real_container.start()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/docker/models/containers.py", line 400, in start
    return self.client.api.start(self.id, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/docker/api/container.py", line 1093, in start
    self._raise_for_status(res)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.16.1/libexec/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:345: starting container process caused "chdir to cwd (\"/var/task\") set in config.json failed: permission denied": unknown")

**Comment by jamesls** [comment]
Hi, looks like this is an issue with SAM CLI which is in a separate repo (https://github.com/awslabs/aws-sam-cli).  If you open it over in their repo they'll be able to help you out.
