### ISSUE TITLE
Unable to run awsebcli because of outdated botocore on python 3.7.0 #3357

### ISSUE THREAD

**Issue by Ujjala** [aws/aws-cli#4368]
I am facing the following issue while running awscli
C:\Users\admin>eb init -p python-3.7
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Python\Python37\Scripts\eb-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\program files\python37\lib\site-packages\pkg_resources\__init__.py", line 3191, in <module>
    @_call_aside
  File "c:\program files\python37\lib\site-packages\pkg_resources\__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "c:\program files\python37\lib\site-packages\pkg_resources\__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\program files\python37\lib\site-packages\pkg_resources\__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "c:\program files\python37\lib\site-packages\pkg_resources\__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\program files\python37\lib\site-packages\pkg_resources\__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'botocore<1.13,>=1.12.29' distribution was not found and is required by awsebcli

I have added the reference number of the similar issue which shows it has closed

**Comment by Ujjala** [comment]
Opened this under aws repository
