### ISSUE TITLE
Rekognition list-stream-processors failing

### ISSUE THREAD

**Issue by melbit-tomcuddihy** [aws/aws-cli#4409]
`aws rekognition list-stream-processors --region ap-southeast-2`
gives output (in ap-southeast-2):
`An error occurred (AccessDeniedException) when calling the ListStreamProcessors operation:`
With no further information as to the exact details of the access issue.

The lack of output is similar to [this issue](https://github.com/awsdocs/amazon-rekognition-developer-guide/issues/18) in the rekognition dev guide repo but the service is listed as available in my region (see [here](https://aws.amazon.com/rekognition/pricing/?nc=sn&loc=4))

Running `aws rekognition list-stream-processors --region ap-southeast-2 --debug` ends with the following:
```
2019-08-15 18:42:32,440 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"__type":"AccessDeniedException"}'
2019-08-15 18:42:32,441 - MainThread - botocore.hooks - DEBUG - Event needs-retry.rekognition.ListStreamProcessors: calling handler <botocore.retryhandler.RetryHandler object at 0x10b4807f0>
2019-08-15 18:42:32,441 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2019-08-15 18:42:32,443 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/Users/thomascuddihy/.pyenv/versions/3.7.0/lib/python3.7/site-packages/awscli/clidriver.py", line 217, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/Users/thomascuddihy/.pyenv/versions/3.7.0/lib/python3.7/site-packages/awscli/clidriver.py", line 358, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/Users/thomascuddihy/.pyenv/versions/3.7.0/lib/python3.7/site-packages/awscli/clidriver.py", line 530, in __call__
    call_parameters, parsed_globals)
  File "/Users/thomascuddihy/.pyenv/versions/3.7.0/lib/python3.7/site-packages/awscli/clidriver.py", line 651, in invoke
    self._display_response(operation_name, response, parsed_globals)
  File "/Users/thomascuddihy/.pyenv/versions/3.7.0/lib/python3.7/site-packages/awscli/clidriver.py", line 671, in _display_response
    formatter(command_name, response)
  File "/Users/thomascuddihy/.pyenv/versions/3.7.0/lib/python3.7/site-packages/awscli/formatter.py", line 234, in __call__
    for i, page in enumerate(response):
  File "/Users/thomascuddihy/.pyenv/versions/3.7.0/lib/python3.7/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/Users/thomascuddihy/.pyenv/versions/3.7.0/lib/python3.7/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/Users/thomascuddihy/.pyenv/versions/3.7.0/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/thomascuddihy/.pyenv/versions/3.7.0/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the ListStreamProcessors operation: 
2019-08-15 18:42:32,444 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

An error occurred (AccessDeniedException) when calling the ListStreamProcessors operation: 
```
(full debug available off of public channel)

I'm able to use many other `aws rekognition` commands, e.g. `list-collections`, `create-collection` etc.

`aws --version == aws-cli/1.16.218 Python/3.7.0 Darwin/18.7.0 botocore/1.12.208`

The IAM user has full access to the rekognition service. Any tips for how to track down where my issue may be?

**Comment by melbit-tomcuddihy** [comment]
To expand:
I'm working through [this](https://aws.amazon.com/blogs/machine-learning/easily-perform-facial-analysis-on-live-feeds-by-creating-a-serverless-video-analytics-environment-with-amazon-rekognition-video-and-amazon-kinesis-video-streams/) example and I first noticed the AccessDeniedException when doing `aws rekognition create-stream-processor --region us-west-2 --cli-input-json file://<PATH_TO_JSON_FILE_ABOVE>` using my version of the json file.

**Comment by melbit-tomcuddihy** [comment]
Hmm, further adding to the mystery:
`aws rekognition list-stream-processors --region us-east-1`
gives me
`None`

So this seems to be a region issue... Does awscli/boto3 do any checks for rekognition streams being available in the region? [Apparently](https://aws.amazon.com/rekognition/pricing/?nc=sn&loc=4) it's available in ap-southeast-2...

**Comment by melbit-tomcuddihy** [comment]
I'm going to close this issue as not related to awscli.
A response from support lists rekognition streaming video as not available in ap-southeast-2, only: 
`us-east-1, eu-west-1 , eu-central-1, ap-northeast-1, us-west-2`

Apologies for the noisy issue, though maybe someone else will find it useful if they see the same error.
