### ISSUE TITLE
Running cloudformation template fails when using custom Transform in CodeBuild 

### ISSUE THREAD

**Issue by psmith6** [aws/aws-cli#4432]
This relates to issue https://github.com/aws/aws-codebuild-docker-images/issues/246#issue-484141563.

One of my build steps runs a cloudformation template which has a custom transform. The transform is available in us-east-1 which is the same region in which code build is running. This same cloudformation template works when I run it with my local cli. Could you provide how to get this transform working in the code build container.

My local cli is `aws-cli/1.16.223 Python/3.6.0 Windows/10 botocore/1.12.213`

```
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
  File "/usr/local/lib/python3.6/dist-packages/awscli/clidriver.py", line 207, in main 
    return command_table[parsed_args.command](remaining, parsed_args) 
  File "/usr/local/lib/python3.6/dist-packages/awscli/clidriver.py", line 348, in __call__ 
    return command_table[parsed_args.operation](remaining, parsed_globals) 

  File "/usr/local/lib/python3.6/dist-packages/awscli/customizations/commands.py", line 187, in __call__ 
    return self._run_main(parsed_args, parsed_globals) 
  File "/usr/local/lib/python3.6/dist-packages/awscli/customizations/cloudformation/deploy.py", line 295, in _run_main 
    parsed_args.fail_on_empty_changeset) 
  File "/usr/local/lib/python3.6/dist-packages/awscli/customizations/cloudformation/deploy.py", line 310, in deploy 
    tags=tags 
  File "/usr/local/lib/python3.6/dist-packages/awscli/customizations/cloudformation/deployer.py", line 227, in create_and_wait_for_changeset 
    self.wait_for_changeset(result.changeset_id, stack_name) 
  File "/usr/local/lib/python3.6/dist-packages/awscli/customizations/cloudformation/deployer.py", line 178, in wait_for_changeset 
    .format(ex, status, reason)) 
RuntimeError: Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Failed to execute transform REDACTED::ALKSify 
2019-08-21 17:03:42,717 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255 
 
Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Failed to execute transform REDACTED::ALKSify 
```

**Comment by kyleknap** [comment]
I'd recommend opening a ticket with AWS Support. As stated in our [README](https://github.com/aws/aws-cli#getting-help), we try to reserve GitHub issues for feature requests and bug for the AWS CLI. The error coming back is coming directly from the service and the CLI is just propagating the service error. So Support should have better insight on why that may be happening.
