### ISSUE TITLE
Having issue executing some aws resources. 'unexpected keyword argument 'cert_file'

### ISSUE THREAD

**Issue by Uponn** [aws/aws-cli#4444]
Upon using aws s3 mb s3://bucketname or aws cloudformation describe-stacks --stack-name aws-sam-getting-started --region us-east-2 --query "Stacks[].Outputs" I get the following error --> "__init__() got an unexpected keyword argument 'cert_file'"
Traceback:
2019-08-27 16:09:40,628 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.14.44 Python/3.6.8 Linux/5.0.0-25-generic botocore/1.8.48
2019-08-27 16:09:40,628 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3', 'mb', 's3://bucket', '--debug']
2019-08-27 16:09:40,629 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7f94e1e22840>
2019-08-27 16:09:40,629 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2019-08-27 16:09:40,629 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f94e2921e18>
2019-08-27 16:09:40,629 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2019-08-27 16:09:40,629 - MainThread - botocore.session - DEBUG - Loading variable credentials_file from defaults.
2019-08-27 16:09:40,629 - MainThread - botocore.session - DEBUG - Loading variable config_file from defaults.
2019-08-27 16:09:40,629 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2019-08-27 16:09:40,629 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_timeout from defaults.
2019-08-27 16:09:40,629 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2019-08-27 16:09:40,629 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_num_attempts from defaults.
2019-08-27 16:09:40,629 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2019-08-27 16:09:40,629 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f94e1f952f0>
2019-08-27 16:09:40,629 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2019-08-27 16:09:40,630 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3: calling handler <function add_waiters at 0x7f94e1e28ae8>
2019-08-27 16:09:40,630 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.s3.anonymous: calling handler <function uri_param at 0x7f94e29b92f0>
2019-08-27 16:09:40,630 - MainThread - botocore.hooks - DEBUG - Event building-command-table.mb: calling handler <function add_waiters at 0x7f94e1e28ae8>
2019-08-27 16:09:40,630 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mb.path: calling handler <function uri_param at 0x7f94e29b92f0>
2019-08-27 16:09:40,630 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.mb: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f94e2956d30>
2019-08-27 16:09:40,631 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2019-08-27 16:09:40,631 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2019-08-27 16:09:40,631 - MainThread - botocore.session - DEBUG - Loading variable region from config file with value 'us-east-2'.
2019-08-27 16:09:40,631 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2019-08-27 16:09:40,631 - MainThread - botocore.session - DEBUG - Loading variable ca_bundle from defaults.
2019-08-27 16:09:40,631 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2019-08-27 16:09:40,631 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2019-08-27 16:09:40,631 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2019-08-27 16:09:40,631 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2019-08-27 16:09:40,631 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2019-08-27 16:09:40,631 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2019-08-27 16:09:40,631 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3/dist-packages/botocore/data/endpoints.json
2019-08-27 16:09:40,633 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2019-08-27 16:09:40,633 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f94e3945a60>
2019-08-27 16:09:40,634 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3/dist-packages/botocore/data/s3/2006-03-01/service-2.json
2019-08-27 16:09:40,639 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f94e39239d8>
2019-08-27 16:09:40,639 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f94e39237b8>
2019-08-27 16:09:40,640 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2019-08-27 16:09:40,644 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2019-08-27 16:09:40,644 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2019-08-27 16:09:40,644 - MainThread - botocore.client - DEBUG - Defaulting to S3 virtual host style addressing with path style addressing fallback.
2019-08-27 16:09:40,645 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.CreateBucket: calling handler <function validate_bucket_name at 0x7f94e3908d90>
2019-08-27 16:09:40,645 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.CreateBucket: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x7f94e1b72e80>>
2019-08-27 16:09:40,645 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.CreateBucket: calling handler <function generate_idempotent_uuid at 0x7f94e39089d8>
2019-08-27 16:09:40,659 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.CreateBucket: calling handler <function add_expect_header at 0x7f94e390b2f0>
2019-08-27 16:09:40,659 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.CreateBucket: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x7f94e1b72e80>>
2019-08-27 16:09:40,659 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=CreateBucket) (verify_ssl=True) with params: {'url_path': '/bucket', 'query_string': {}, 'method': 'PUT', 'headers': {'User-Agent': 'aws-cli/1.14.44 Python/3.6.8 Linux/5.0.0-25-generic botocore/1.8.48'}, 'body': b'<CreateBucketConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><LocationConstraint>us-east-2</LocationConstraint></CreateBucketConfiguration>', 'url': 'https://s3.us-east-2.amazonaws.com/bucket', 'context': {'client_region': 'us-east-2', 'client_config': <botocore.config.Config object at 0x7f94e1dbb908>, 'has_streaming_input': False, 'auth_type': None, 'signing': {'bucket': 'bucket'}}}
2019-08-27 16:09:40,659 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.CreateBucket: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f94e1dbb8d0>>
2019-08-27 16:09:40,659 - MainThread - botocore.hooks - DEBUG - Event choose-signer.s3.CreateBucket: calling handler <function set_operation_specific_signer at 0x7f94e39088c8>
2019-08-27 16:09:40,659 - MainThread - botocore.hooks - DEBUG - Event before-sign.s3.CreateBucket: calling handler <function fix_s3_host at 0x7f94e3acfea0>
2019-08-27 16:09:40,659 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2019-08-27 16:09:40,659 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
PUT
/bucket

host:s3.us-east-2.amazonaws.com
x-amz-content-sha256:70cae86320841ea73b0bdc759f99920c7caa405e61af2742575750c6586272c9
x-amz-date:20190827T130940Z

host;x-amz-content-sha256;x-amz-date
70cae86320841ea73b0bdc759f99920c7caa405e61af2742575750c6586272c9
2019-08-27 16:09:40,659 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20190827T130940Z
20190827/us-east-2/s3/aws4_request
52c18f90b544da4dd68d3f4aacee3147ac57d0b14ed918b91dd84a531388eb4c
2019-08-27 16:09:40,659 - MainThread - botocore.auth - DEBUG - Signature:
e128040e2927136fc3a0316fce1346f49578814e4085ecb75c4fc278ec95fd89
2019-08-27 16:09:40,660 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [PUT]>
2019-08-27 16:09:40,660 - MainThread - botocore.endpoint - DEBUG - Exception received when sending HTTP request.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/botocore/endpoint.py", line 213, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/home/snedev/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/snedev/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/snedev/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 591, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/home/snedev/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 249, in _get_conn
    return conn or self._new_conn()
  File "/home/snedev/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 831, in _new_conn
    **self.conn_kw)
  File "/usr/lib/python3/dist-packages/botocore/awsrequest.py", line 70, in __init__
    HTTPConnection.__init__(self, *args, **kwargs)
  File "/home/snedev/.local/lib/python3.6/site-packages/urllib3/connection.py", line 115, in __init__
    _HTTPConnection.__init__(self, *args, **kw)
TypeError: __init__() got an unexpected keyword argument 'cert_file'
2019-08-27 16:09:40,661 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.CreateBucket: calling handler <botocore.retryhandler.RetryHandler object at 0x7f94e1b72b38>
make_bucket failed: s3://bucket __init__() got an unexpected keyword argument 'cert_file'

**Comment by joguSD** [comment]
How did you install the CLI? My hunch is that this is an unsupported version of `urllib3`.

**Comment by Uponn** [comment]
@joguSD if I'm not mistaken, I installed it with pip -- pip3 install awscli.

**Comment by Uponn** [comment]
awscli==1.16.226 version and urllib3==1.25.3 version.

**Comment by jamesls** [comment]
I think it's an issue with how the CLI is installed.  You mentioned you have `awscli==1.16.226` but from your debug logs you have a fairly old version of the CLI installed:

```
2019-08-27 16:09:40,628 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.14.44 Python/3.6.8 Linux/5.0.0-25-generic botocore/1.8.48
```

In this case your stack trace is using `requests.session` which we no longer use in the AWS CLI.
