### ISSUE TITLE
ssm start-session error

### ISSUE THREAD

**Issue by tk0221** [aws/aws-cli#4557]
```
2019-10-03 01:28:48,330 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 217, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 358, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 530, in __call__
    call_parameters, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/customizations/sessionmanager.py", line 102, in invoke
    raise ValueError(''.join(ERROR_MESSAGE))
```

Followed instruction on `https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-manual-agent-install.html#agent-install-al`

I did `aws configure` and provide KEY and ID

loal user can run `  aws ssm start-session` command but for root (Amazon Linux) cant run   `aws ssm start-session`  I assume it used different python library.

**Comment by tk0221** [comment]
okay  https://stackoverflow.com/a/38056259


```
The problem is partly answered by your question. The Amazon AMI doesn't consider /usr/local/bin to be part of the root account's PATH. You can fix this by updating the root account's ~/.bashrc to include it.

Something like this...

export PATH=$PATH:/usr/local/bin
```
