### ISSUE TITLE
awscli-bundle 1.16.253 does not install with Python 2.6 (colorama dependency not met)

### ISSUE THREAD

**Issue by alewando** [aws/aws-cli#4563]
It looks like awscli-bundle-1.16.253 includes colorama-0.4.1, but this version cannot satisfy a dependency constraint, which has recently been changed to require colorama<0.3.9 (I think due to #4545).

```
Could not find a version that satisfies the requirement colorama<0.3.9,>=0.2.5 (from awscli==1.16.253) (from versions: 0.4.1)
```

More detailed log:
```
sudo awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
inflating: awscli-bundle/packages/setup/setuptools_scm-1.15.7.tar.gz
Running cmd: /usr/bin/python virtualenv.py --no-download --python /usr/bin/python /usr/local/aws
Traceback (most recent call last):
File "awscli-bundle/install", line 162, in <module>
Running cmd: /usr/local/aws/bin/pip install --no-cache-dir --no-index --find-links file:///home/centos/awscli-bundle/packages/setup setuptools_scm-1.15.7.tar.gz
Running cmd: /usr/local/aws/bin/pip install --no-cache-dir --no-index --find-links file:///home/centos/awscli-bundle/packages awscli-1.16.253.tar.gz
        main()
        File "awscli-bundle/install", line 151, in main
        pip_install_packages(opts.install_dir)
        File "awscli-bundle/install", line 119, in pip_install_packages
        pip_script, PACKAGES_DIR, cli_tarball))
        File "awscli-bundle/install", line 49, in run
        p.returncode, cmd, stdout + stderr))
        __main__.BadRCError: Bad rc (1) for cmd '/usr/local/aws/bin/pip install --no-cache-dir --no-index --find-links file:///home/centos/awscli-bundle/packages awscli-1.16.253.tar.gz': Processing ./awscli-1.16.253.tar.gz
...
Collecting colorama<0.3.9,>=0.2.5 (from awscli==1.16.253)
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
  Could not find a version that satisfies the requirement colorama<0.3.9,>=0.2.5 (from awscli==1.16.253) (from versions: 0.4.1)
No matching distribution found for colorama<0.3.9,>=0.2.5 (from awscli==1.16.253)
```

**Comment by joguSD** [comment]
Confirmed, open a PR for a fix in #4566

**Comment by alewando** [comment]
Still seeing this error in 1.16.254:
```
Collecting colorama<0.3.9,>=0.2.5 (from awscli==1.16.254)
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
  Could not find a version that satisfies the requirement colorama<0.3.9,>=0.2.5 (from awscli==1.16.254) (from versions: 0.4.1)
No matching distribution found for colorama<0.3.9,>=0.2.5 (from awscli==1.16.254)
```

**Comment by pbhosale87** [comment]
I am also facing same issue in 1.16.254
```

:Traceback (most recent call last):
  File "./awscli-bundle/install", line 162, in <module>
    main()
  File "./awscli-bundle/install", line 151, in main
    pip_install_packages(opts.install_dir)
  File "./awscli-bundle/install", line 119, in pip_install_packages
    pip_script, PACKAGES_DIR, cli_tarball))
  File "./awscli-bundle/install", line 49, in run
    p.returncode, cmd, stdout + stderr))
__main__.BadRCError: Bad rc (1) for cmd '/usr/local/aws/bin/pip install --no-cache-dir --no-index --find-links file:///awscli-bundle/packages awscli-1.16.254.tar.gz': Processing ./awscli-1.16.254.tar.gz
Collecting botocore==1.12.244 (from awscli==1.16.254)
Collecting docutils<0.16,>=0.10 (from awscli==1.16.254)
Collecting rsa<=3.5.0,>=3.1.2 (from awscli==1.16.254)
Collecting s3transfer<0.3.0,>=0.2.0 (from awscli==1.16.254)
Requirement already satisfied: argparse>=1.1 in /usr/local/aws/lib/python2.6/site-packages (from awscli==1.16.254)
Collecting PyYAML<=3.13,>=3.10 (from awscli==1.16.254)
Collecting colorama<0.3.9,>=0.2.5 (from awscli==1.16.254)
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
  Could not find a version that satisfies the requirement colorama<0.3.9,>=0.2.5 (from awscli==1.16.254) (from versions: 0.4.1)
No matching distribution found for colorama<0.3.9,>=0.2.5 (from awscli==1.16.254)
```

**Comment by pbhosale87** [comment]
Is there a way to download stable bundle version?
I am using below URL download bundle zip.
`
https://s3.amazonaws.com/aws-cli/awscli-bundle.zip`

**Comment by joguSD** [comment]
@alewando This was merged after 1.16.254 was released and will be fixed in today's release.
@pbhosale87 Version specific bundles are available at the same URL:
```
https://s3.amazonaws.com/aws-cli/awscli-bundle-X.Y.Z.zip
```
For example:
https://s3.amazonaws.com/aws-cli/awscli-bundle-1.16.252.zip

**Comment by pbhosale87** [comment]
@joguSD Thank you so much.

**Comment by stevenoneill-jmfamily** [comment]
Thank you @joguSD 👍

**Comment by Ellen-Zhang-NI** [comment]
Still see this issue in 1.16.255:
```
Could not find a version that satisfies the requirement colorama<0.3.9,>=0.2.5 (from awscli==1.16.255) (from versions: 0.3.9, 0.4.1)\n
	 No matching distribution found for colorama<0.3.9,>=0.2.5 (from awscli==1.16.255)", 
```
Call stack is the same

**Comment by DR-Lundy** [comment]
Continuing to get the same error in 1.16.255, also.

```
2019-10-09T14:21:28Z:  Traceback (most recent call last):
2019-10-09T14:21:28Z:    File "./awscli-bundle/install", line 162, in <module>
2019-10-09T14:21:28Z:      main()
2019-10-09T14:21:28Z:    File "./awscli-bundle/install", line 151, in main
2019-10-09T14:21:28Z:      pip_install_packages(opts.install_dir)
2019-10-09T14:21:28Z:    File "./awscli-bundle/install", line 119, in pip_install_packages
2019-10-09T14:21:28Z:      pip_script, PACKAGES_DIR, cli_tarball))
2019-10-09T14:21:28Z:    File "./awscli-bundle/install", line 49, in run
2019-10-09T14:21:28Z:      p.returncode, cmd, stdout + stderr))
2019-10-09T14:21:28Z:  __main__.BadRCError: Bad rc (1) for cmd '/usr/local/aws/bin/pip install --no-cache-dir --no-index --find-links file:///root/aws-install/awscli-bundle/packages awscli-1.16.255.tar.gz': Processing ./awscli-1.16.255.tar.gz
2019-10-09T14:21:28Z:  Collecting botocore==1.12.245 (from awscli==1.16.255)
2019-10-09T14:21:28Z:  Collecting docutils<0.16,>=0.10 (from awscli==1.16.255)
2019-10-09T14:21:28Z:  Collecting rsa<=3.5.0,>=3.1.2 (from awscli==1.16.255)
2019-10-09T14:21:28Z:  Collecting s3transfer<0.3.0,>=0.2.0 (from awscli==1.16.255)
2019-10-09T14:21:28Z:  Requirement already satisfied: argparse>=1.1 in /usr/local/aws/lib/python2.6/site-packages (from awscli==1.16.255)
2019-10-09T14:21:28Z:  Collecting PyYAML<=3.13,>=3.10 (from awscli==1.16.255)
2019-10-09T14:21:28Z:  Collecting colorama<0.3.9,>=0.2.5 (from awscli==1.16.255)
2019-10-09T14:21:28Z:  DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
2019-10-09T14:21:28Z:    Could not find a version that satisfies the requirement colorama<0.3.9,>=0.2.5 (from awscli==1.16.255) (from versions: 0.3.9, 0.4.1)
2019-10-09T14:21:28Z:  No matching distribution found for colorama<0.3.9,>=0.2.5 (from awscli==1.16.255)
```
