### ISSUE TITLE
awscli-bundle 1.6.256 does not install with Python 2.6 (colorama dependency not met)

### ISSUE THREAD

**Issue by DRLDoom** [aws/aws-cli#4577]
On-going issue with colorama dependency.

previous closed issue: https://github.com/aws/aws-cli/issues/4563

```
sudo awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
...
Running cmd: /usr/bin/python virtualenv.py --no-download --python /usr/bin/python /usr/local/aws
Running cmd: /usr/local/aws/bin/pip install --no-cache-dir --no-index --find-links file:///root/aws-install/awscli-bundle/packages/setup setuptools_scm-1.15.7.tar.gz
Running cmd: /usr/local/aws/bin/pip install --no-cache-dir --no-index --find-links file:///root/aws-install/awscli-bundle/packages awscli-1.16.256.tar.gz
Running cmd: /usr/bin/python virtualenv.py --no-download --python /usr/bin/python /usr/local/aws
Running cmd: /usr/local/aws/bin/pip install --no-cache-dir --no-index --find-links file:///root/aws-install/awscli-bundle/packages/setup setuptools_scm-1.15.7.tar.gz
Running cmd: /usr/local/aws/bin/pip install --no-cache-dir --no-index --find-links file:///root/aws-install/awscli-bundle/packages awscli-1.16.256.tar.gz
STDERR: Traceback (most recent call last):
  File "./awscli-bundle/install", line 162, in <module>
    main()
  File "./awscli-bundle/install", line 151, in main
    pip_install_packages(opts.install_dir)
  File "./awscli-bundle/install", line 119, in pip_install_packages
    pip_script, PACKAGES_DIR, cli_tarball))
  File "./awscli-bundle/install", line 49, in run
    p.returncode, cmd, stdout + stderr))
__main__.BadRCError: Bad rc (1) for cmd '/usr/local/aws/bin/pip install --no-cache-dir --no-index --find-links file:///root/aws-install/awscli-bundle/packages awscli-1.16.256.tar.gz': Processing ./awscli-1.16.256.tar.gz
Collecting botocore==1.12.246 (from awscli==1.16.256)
Collecting docutils<0.16,>=0.10 (from awscli==1.16.256)
Collecting rsa<=3.5.0,>=3.1.2 (from awscli==1.16.256)
Collecting s3transfer<0.3.0,>=0.2.0 (from awscli==1.16.256)
Requirement already satisfied: argparse>=1.1 in /usr/local/aws/lib/python2.6/site-packages (from awscli==1.16.256)
Collecting PyYAML<=3.13,>=3.10 (from awscli==1.16.256)
Collecting colorama<0.3.9,>=0.2.5 (from awscli==1.16.256)
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
  Could not find a version that satisfies the requirement colorama<0.3.9,>=0.2.5 (from awscli==1.16.256) (from versions: 0.3.9, 0.4.1)
No matching distribution found for colorama<0.3.9,>=0.2.5 (from awscli==1.16.256)
```

**Comment by jamesls** [comment]
Confirmed.  Looking into this now.

**Comment by jamesls** [comment]
Looks like the wrong version was specified in https://github.com/aws/aws-cli/commit/b9a62ad07789bad35b6a0c114c451084c3de8efc#diff-2eeaed663bd0d25b7e608891384b7298.

We pull in 0.3.9 in our bundled installer (which is support on py26) but our setup.py requires a previous version.  We should just update our setup.py to be `<=0.3.9`.

I'll get this fixed.
