### ISSUE TITLE
AWS CLI v2 cannot load v1 plugins

### ISSUE THREAD

**Issue by n1t1nv3rma** [aws/aws-cli#4650]
$ sudo ./install
Password:
Traceback (most recent call last):
  File "aws", line 27, in <module>
  File "aws", line 23, in main
  File "site-packages/awscli/clidriver.py", line 73, in main
  File "site-packages/awscli/clidriver.py", line 83, in create_clidriver
  File "site-packages/awscli/plugin.py", line 44, in load_plugins
  File "site-packages/awscli/plugin.py", line 58, in _import_plugins
ModuleNotFoundError: No module named 'botocore_amazon'
[94393] Failed to execute script aws
You can now run: /usr/local/bin/aws2 --version

$ sudo ./install
Traceback (most recent call last):
  File "aws", line 27, in <module>
  File "aws", line 23, in main
  File "site-packages/awscli/clidriver.py", line 73, in main
  File "site-packages/awscli/clidriver.py", line 83, in create_clidriver
  File "site-packages/awscli/plugin.py", line 44, in load_plugins
  File "site-packages/awscli/plugin.py", line 58, in _import_plugins
ModuleNotFoundError: No module named 'botocore_amazon'
[94498] Failed to execute script aws
Found preexisting AWS CLI installation: /usr/local/aws-cli/v2/current. Please rerun install script with --update flag.
 
$ sudo ./install --update
Traceback (most recent call last):
  File "aws", line 27, in <module>
  File "aws", line 23, in main
  File "site-packages/awscli/clidriver.py", line 73, in main
  File "site-packages/awscli/clidriver.py", line 83, in create_clidriver
  File "site-packages/awscli/plugin.py", line 44, in load_plugins
  File "site-packages/awscli/plugin.py", line 58, in _import_plugins
ModuleNotFoundError: No module named 'botocore_amazon'
[94552] Failed to execute script aws
Found same AWS CLI version: /usr/local/aws-cli/v2/. Skipping install.

**Comment by joguSD** [comment]
This is related to the `[plugins]` section of your config. Currently, the V2 preview builds cannot load plugins from this section as the python installation is completely isolated in the new executable and there's no way to install additional python modules to be loaded as plugins. We should fix this in the V2 branch to ignore any plugins until we can address this more properly. As a workaround for now you can remove or rename the `plugins` section so that the V2 of the CLI doesn't pick up on it.

**Comment by kyleknap** [comment]
This should be fixed now. We also merged a PR that allows you to use the plugins that you may have defined in your `[plugins]` section: https://github.com/aws/aws-cli/pull/4854. Closing issue.
