### ISSUE TITLE
can't start new thread on cp command

### ISSUE THREAD

**Issue by Michaelc1-aon** [aws/aws-cli#4732]
Hi, 
the LS command works fine but when I try the cp or sync command I get: 
"can't start new thread"
Anyone encountered this? 

Config settings: 
s3 =                               
    max_concurrent_requests = 20   
    max_queue_size = 10000         
    multipart_threshold = 64MB     
    multipart_chunksize = 16MB     
    max_bandwidth = 50MB/s         
    use_accelerate_endpoint = true 

Here's the debug: 
$
/usr/local/bin/aws s3 cp s3://mysite/myfolder/myfile.tsv   /targetfolder
             --profile MYPROFILE   --debug
2019-12-03 10:14:56,834 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.16.277 Python/3.4.10 OS400/3 botocore/1.13.
13
2019-12-03 10:14:56,837 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3', 'cp', 's3://mysite/myfolder/myfile.tsv', '/apps', '--profile', 'MYPROFILE', '--debug']
2019-12-03 10:14:56,838 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_pars
ers at 0x309f36a4>
2019-12-03 10:14:56,838 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_pa
ram_handler at 0x307474f4>
2019-12-03 10:14:56,841 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_r
ole_provider_cache at 0x30760584>
2019-12-03 10:14:56,849 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile
 name was explicitly set.
2019-12-03 10:14:56,849 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_
handler at 0x309292fc>
2019-12-03 10:14:56,851 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3: calling handler <function add_waite
rs at 0x309fb41c>
2019-12-03 10:14:56,858 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.s3.anonymous: calling handler <awscli.para
mfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,859 - MainThread - botocore.hooks - DEBUG - Event building-command-table.cp: calling handler <function add_waite
rs at 0x309fb41c>
2019-12-03 10:14:56,878 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.anonymous: calling handler <awscli.para
mfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,879 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.source-region: calling handler <awscli.
paramfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,881 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.content-disposition: calling handler <a
wscli.paramfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,882 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.anonymous: calling handler <awscli.para
mfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,883 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.paths: calling handler <awscli.paramfil
e.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,885 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.website-redirect: calling handler <awsc
li.paramfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,886 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse-kms-key-id: calling handler <awscli
.paramfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,887 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse: calling handler <awscli.paramfile.
URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,889 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse-c: calling handler <awscli.paramfil
e.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,890 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.ignore-glacier-warnings: calling handle
r <awscli.paramfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,891 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.
ParamShorthandParser object at 0x3073c9cc>
2019-12-03 10:14:56,893 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.dryrun: calling handler <awscli.paramfi
le.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,895 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.
ParamShorthandParser object at 0x3073c9cc>
2019-12-03 10:14:56,896 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.only-show-errors: calling handler <awsc
li.paramfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,897 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.
ParamShorthandParser object at 0x3073c9cc>
2019-12-03 10:14:56,899 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.follow-symlinks: calling handler <awscl
i.paramfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,900 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.
ParamShorthandParser object at 0x3073c9cc>
2019-12-03 10:14:56,902 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse-c-copy-source: calling handler <aws
cli.paramfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,903 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse-c-copy-source-key: calling handler
<awscli.paramfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,904 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.expires: calling handler <awscli.paramf
ile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,906 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.page-size: calling handler <awscli.para
mfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,907 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.content-encoding: calling handler <awsc
li.paramfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,909 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.metadata-directive: calling handler <aw
scli.paramfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,910 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.content-type: calling handler <awscli.p
aramfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,911 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.cache-control: calling handler <awscli.
paramfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,913 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.force-glacier-transfer: calling handler
 <awscli.paramfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,914 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.
ParamShorthandParser object at 0x3073c9cc>
2019-12-03 10:14:56,915 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.acl: calling handler <awscli.paramfile.
URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,917 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.request-payer: calling handler <awscli.
paramfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,918 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.anonymous: calling handler <awscli.para
mfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,920 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.anonymous: calling handler <awscli.para
mfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,921 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse-c-key: calling handler <awscli.para
mfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,922 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.quiet: calling handler <awscli.paramfil
e.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,924 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.
ParamShorthandParser object at 0x3073c9cc>
2019-12-03 10:14:56,925 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.metadata: calling handler <awscli.param
file.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,926 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.grants: calling handler <awscli.paramfi
le.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,928 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.expected-size: calling handler <awscli.
paramfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,929 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.content-language: calling handler <awsc
li.paramfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,931 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.storage-class: calling handler <awscli.
paramfile.URIArgumentHandler object at 0x30a6686c>
2019-12-03 10:14:56,932 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2019-12-03 10:14:56,932 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2019-12-03 10:14:56,932 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2019-12-03 10:14:56,935 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credential
s
2019-12-03 10:14:56,938 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws/lib/python3.4/site-packages/boto
core/data/endpoints.json
2019-12-03 10:14:57,332 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_
name_alias at 0x3058a6a4>
2019-12-03 10:14:57,340 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws/lib/python3.4/site-packages/boto
core/data/s3/2006-03-01/service-2.json
2019-12-03 10:14:57,645 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_genera
te_presigned_post at 0x30579614>
2019-12-03 10:14:57,645 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_genera
te_presigned_url at 0x305794f4>
2019-12-03 10:14:57,647 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: No
ne
2019-12-03 10:14:57,687 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2019-12-03 10:14:57,691 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws/lib/python3.4/site-packages/boto
core/data/_retry.json
2019-12-03 10:14:57,709 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2019-12-03 10:14:57,715 - MainThread - botocore.client - DEBUG - Defaulting to S3 virtual host style addressing with path style addr
essing fallback.
2019-12-03 10:14:57,722 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_
name_alias at 0x3058a6a4>
2019-12-03 10:14:57,732 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_genera
te_presigned_post at 0x30579614>
2019-12-03 10:14:57,733 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_genera
te_presigned_url at 0x305794f4>
2019-12-03 10:14:57,733 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: No
ne
2019-12-03 10:14:57,764 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2019-12-03 10:14:57,772 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2019-12-03 10:14:57,778 - MainThread - botocore.client - DEBUG - Defaulting to S3 virtual host style addressing with path style addr
essing fallback.
2019-12-03 10:14:57,784 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_
name_alias at 0x3058a6a4>
2019-12-03 10:14:57,794 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_genera
te_presigned_post at 0x30579614>
2019-12-03 10:14:57,794 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_genera
te_presigned_url at 0x305794f4>
2019-12-03 10:14:57,795 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: No
ne
2019-12-03 10:14:57,821 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2019-12-03 10:14:57,828 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2019-12-03 10:14:57,835 - MainThread - botocore.client - DEBUG - Defaulting to S3 virtual host style addressing with path style addr
essing fallback.
2019-12-03 10:14:57,843 - MainThread - awscli.customizations.s3.s3handler - DEBUG - Using a multipart threshold of 8388608 and a par
t size of 8388608
2019-12-03 10:14:57,845 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/aws/lib/python3.4/site-packages/awscli/clidriver.py", line 217, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/aws/lib/python3.4/site-packages/awscli/customizations/commands.py", line 190, in __call__
    parsed_globals)
  File "/usr/local/aws/lib/python3.4/site-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/usr/local/aws/lib/python3.4/site-packages/awscli/customizations/s3/subcommands.py", line 701, in _run_main
    return cmd.run()
  File "/usr/local/aws/lib/python3.4/site-packages/awscli/customizations/s3/subcommands.py", line 1064, in run
    file_list.append(components[i].call(files[i]))
  File "/usr/local/aws/lib/python3.4/site-packages/awscli/customizations/s3/s3handler.py", line 170, in call
    with self._result_command_recorder:
  File "/usr/local/aws/lib/python3.4/site-packages/awscli/customizations/s3/results.py", line 666, in __enter__
    self.start()
  File "/usr/local/aws/lib/python3.4/site-packages/awscli/customizations/s3/results.py", line 644, in start
    self._result_processor.start()
  File "/QOpenSys/QIBM/ProdData/OPS/Python3.4/lib/python3.4/threading.py", line 841, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
2019-12-03 10:14:57,872 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255
can't start new thread
$

**Comment by Michaelc1-aon** [comment]
I found the issue. I was calling aws from QSH but needed to go into QP2TERM.

**Comment by jamesls** [comment]
Awesome, glad you were able to resolve this!
