### ISSUE TITLE
--cli-input-json doesn't work with "http://" and "https://" protocol

### ISSUE THREAD

**Issue by shobull** [aws/aws-cli#4792]
From what I learned in `aws ... --from-input-cli <value>` \<value\> requires protocol (usually `file://`) but when I try to use `http://` it doesn't work. I find it usefull to fetch json from remote server. When I enter incorrect URL it fails with correct HTTP error (e.g. `received non 200 status code of 403`) but when when correct URL is filled this happens:

- AWS CLI version: `aws-cli/1.16.300 Python/3.7.5 Darwin/19.2.0 botocore/1.13.36`

- Command executed: `aws ecs --region eu-west-1 register-task-definition --cli-input-json http://localhost:8080/taskdef --debug`

- Output:

```
2019-12-25 11:17:10,655 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.16.300 Python/3.7.5 Darwin/19.2.0 botocore/1.13.36
2019-12-25 11:17:10,655 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['ecs', '--region', 'eu-west-1', 'register-task-definition', '--cli-input-json', 'localhost:8080/taskdef', '--debug']
2019-12-25 11:17:10,656 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x1034dca70>
2019-12-25 11:17:10,656 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x102ef0050>
2019-12-25 11:17:10,656 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x102f1c440>
2019-12-25 11:17:10,664 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x103384950>
2019-12-25 11:17:10,665 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/1.16.300/libexec/lib/python3.7/site-packages/botocore/data/ecs/2014-11-13/service-2.json
2019-12-25 11:17:10,672 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ecs: calling handler <function inject_commands at 0x1034254d0>
2019-12-25 11:17:10,672 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ecs: calling handler <function add_waiters at 0x1034ec680>
2019-12-25 11:17:10,685 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/1.16.300/libexec/lib/python3.7/site-packages/botocore/data/ecs/2014-11-13/waiters-2.json
2019-12-25 11:17:10,686 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('family', <awscli.arguments.CLIArgument object at 0x1047a4b90>), ('task-role-arn', <awscli.arguments.CLIArgument object at 0x1047a4d50>), ('execution-role-arn', <awscli.arguments.CLIArgument object at 0x1047a4d90>), ('network-mode', <awscli.arguments.CLIArgument object at 0x1047a4dd0>), ('container-definitions', <awscli.arguments.ListArgument object at 0x1047a4c90>), ('volumes', <awscli.arguments.ListArgument object at 0x1047a4e10>), ('placement-constraints', <awscli.arguments.ListArgument object at 0x1047a4c10>), ('requires-compatibilities', <awscli.arguments.ListArgument object at 0x1047a4e50>), ('cpu', <awscli.arguments.CLIArgument object at 0x1047a4f50>), ('memory', <awscli.arguments.CLIArgument object at 0x1047a4fd0>), ('tags', <awscli.arguments.ListArgument object at 0x1047aa810>), ('pid-mode', <awscli.arguments.CLIArgument object at 0x1047aa850>), ('ipc-mode', <awscli.arguments.CLIArgument object at 0x1047aa950>), ('proxy-configuration', <awscli.arguments.CLIArgument object at 0x1047aa690>), ('inference-accelerators', <awscli.arguments.ListArgument object at 0x1047aa890>)])
2019-12-25 11:17:10,686 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ecs.register-task-definition: calling handler <function add_streaming_output_arg at 0x1034dce60>
2019-12-25 11:17:10,686 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ecs.register-task-definition: calling handler <function add_cli_input_json at 0x102f25b00>
2019-12-25 11:17:10,687 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ecs.register-task-definition: calling handler <function unify_paging_params at 0x10345bef0>
2019-12-25 11:17:10,704 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/1.16.300/libexec/lib/python3.7/site-packages/botocore/data/ecs/2014-11-13/paginators-1.json
2019-12-25 11:17:10,704 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ecs.register-task-definition: calling handler <function add_generate_skeleton at 0x10343b710>
2019-12-25 11:17:10,705 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ecs.register-task-definition: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x1047aa9d0>>
2019-12-25 11:17:10,705 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ecs.register-task-definition: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x1047aaf50>>
2019-12-25 11:17:10,706 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.family: calling handler <awscli.paramfile.URIArgumentHandler object at 0x102ee3850>
2019-12-25 11:17:10,706 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.task-role-arn: calling handler <awscli.paramfile.URIArgumentHandler object at 0x102ee3850>
2019-12-25 11:17:10,707 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.execution-role-arn: calling handler <awscli.paramfile.URIArgumentHandler object at 0x102ee3850>
2019-12-25 11:17:10,707 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.network-mode: calling handler <awscli.paramfile.URIArgumentHandler object at 0x102ee3850>
2019-12-25 11:17:10,707 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.container-definitions: calling handler <awscli.paramfile.URIArgumentHandler object at 0x102ee3850>
2019-12-25 11:17:10,707 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.volumes: calling handler <awscli.paramfile.URIArgumentHandler object at 0x102ee3850>
2019-12-25 11:17:10,707 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.placement-constraints: calling handler <awscli.paramfile.URIArgumentHandler object at 0x102ee3850>
2019-12-25 11:17:10,708 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.requires-compatibilities: calling handler <awscli.paramfile.URIArgumentHandler object at 0x102ee3850>
2019-12-25 11:17:10,708 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.cpu: calling handler <awscli.paramfile.URIArgumentHandler object at 0x102ee3850>
2019-12-25 11:17:10,708 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.memory: calling handler <awscli.paramfile.URIArgumentHandler object at 0x102ee3850>
2019-12-25 11:17:10,708 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.tags: calling handler <awscli.paramfile.URIArgumentHandler object at 0x102ee3850>
2019-12-25 11:17:10,708 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.pid-mode: calling handler <awscli.paramfile.URIArgumentHandler object at 0x102ee3850>
2019-12-25 11:17:10,708 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.ipc-mode: calling handler <awscli.paramfile.URIArgumentHandler object at 0x102ee3850>
2019-12-25 11:17:10,709 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.proxy-configuration: calling handler <awscli.paramfile.URIArgumentHandler object at 0x102ee3850>
2019-12-25 11:17:10,709 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.inference-accelerators: calling handler <awscli.paramfile.URIArgumentHandler object at 0x102ee3850>
2019-12-25 11:17:10,709 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x102ee3850>
2019-12-25 11:17:10,710 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): localhost:8080
2019-12-25 11:17:11,033 - MainThread - urllib3.connectionpool - DEBUG - http:localhost:8080 "GET /taskdef HTTP/1.1" 200 1068
2019-12-25 11:17:11,038 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ecs.register-task-definition.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x102ee3850>
2019-12-25 11:17:11,039 - MainThread - botocore.hooks - DEBUG - Event calling-command.ecs.register-task-definition: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x1047aa9d0>>
2019-12-25 11:17:11,039 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/Cellar/awscli/1.16.300/libexec/lib/python3.7/site-packages/awscli/customizations/cliinputjson.py", line 72, in add_to_call_parameters
    input_data = json.loads(retrieved_json)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/awscli/1.16.300/libexec/lib/python3.7/site-packages/awscli/clidriver.py", line 217, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/Cellar/awscli/1.16.300/libexec/lib/python3.7/site-packages/awscli/clidriver.py", line 358, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/Cellar/awscli/1.16.300/libexec/lib/python3.7/site-packages/awscli/clidriver.py", line 509, in __call__
    parsed_globals=parsed_globals
  File "/usr/local/Cellar/awscli/1.16.300/libexec/lib/python3.7/site-packages/awscli/clidriver.py", line 607, in _emit_first_non_none_response
    name, **kwargs)
  File "/usr/local/Cellar/awscli/1.16.300/libexec/lib/python3.7/site-packages/botocore/session.py", line 677, in emit_first_non_none_response
    responses = self._events.emit(event_name, **kwargs)
  File "/usr/local/Cellar/awscli/1.16.300/libexec/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/Cellar/awscli/1.16.300/libexec/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/Cellar/awscli/1.16.300/libexec/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/Cellar/awscli/1.16.300/libexec/lib/python3.7/site-packages/awscli/customizations/cliinputjson.py", line 76, in add_to_call_parameters
    % (e, retrieved_json))
awscli.argprocess.ParamError: Error parsing parameter 'cli-input-json': Invalid JSON: Expecting value: line 1 column 1 (char 0)
JSON received: http://localhost:8080/taskdef
2019-12-25 11:17:11,046 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Error parsing parameter 'cli-input-json': Invalid JSON: Expecting value: line 1 column 1 (char 0)
JSON received: http://localhost:8080/taskdef
```

**Comment by shobull** [comment]
My guess is wrong call in `cliinputjson.py:65` - `retrieved_json = get_paramfile(input_json, LOCAL_PREFIX_MAP)`.

**Comment by kyleknap** [comment]
It looks like we used to support `http` and `https://` as protocols for `--cli-input-json`, but around two years ago, we removed that ability in this PR: https://github.com/aws/aws-cli/pull/3402. I'm still looking as to whether this was intentional. But in the meantime, could you elaborate on how you were planning to use the remote protocol with `--cli-input-json`?

**Comment by shobull** [comment]
From my point of view #3402 introduced this behaviour and it is a bug. User is supposed to be able to disable resolving strings including http protocol intentionally but by default it should work. part of `cliinputjson.py` is able to resolve http procol when it is enabled by `cli_follow_urlparam` (validation part) but when it gets to `get_paramfile` this function is ignoring `cli_follow_urlparam` and consider only `LOCAL_PREFIX_MAP` from parameter (i think remote prefixes should be added inside this function in a same way based on `cli_follow_urlparam`.

Our usecase for consuming input json from http is generating of ECS task definitions. We have implemented AWS lambda which is able to generate ready-to-use task definitions for all our services with only few override parameters. Currently we have to fetch JSON using `curl` and send it to `--cli-input-json`. If this bug will be fixed we will use similar AWS lambda JSON generators for other usecases.

**Comment by kdaily** [comment]
Hi @shobull,

I see that you are experiencing this with the v1 client. I should note that this behavior goes away in the v2 client:

https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-paramfile

So, the pattern of fetching the file with `curl` or `wget` is the preferred approach.

**Comment by shobull** [comment]
Thanks @kdaily I missed that. I'm closing this issue then.
