### ISSUE TITLE
Python 3.5 or later is required

### ISSUE THREAD

**Issue by thepont** [aws/aws-cli#4868]
## Description

I encountered an error while the aws-cli and also noticed that the contributing guidelines stated that code should work on python 3.4.

## Dockerfile

The following Dockerfile can be used to reproduce the issue (create a file with the contents Dockerfile, then run `docker build .` while in the directory with the Dockerfile)

```
FROM buildpack-deps:jessie

RUN apt-get update \
    && apt-get install -y 
# AWS CLI Install
RUN apt-get install -y python3-pip python3-dev build-essential  
RUN pip3 install --upgrade pip 
RUN pip3 install awscli --upgrade --ignore-installed six

CMD /bin/bash
```

## Trace

```
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.4/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/python3.4/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/python3.4/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/local/lib/python3.4/dist-packages/pip/_internal/cli/cmdoptions.py", line 28, in <module>
    from pip._internal.models.target_python import TargetPython
  File "/usr/local/lib/python3.4/dist-packages/pip/_internal/models/target_python.py", line 4, in <module>
    from pip._internal.utils.misc import normalize_version_info
  File "/usr/local/lib/python3.4/dist-packages/pip/_internal/utils/misc.py", line 20, in <module>
    from pip._vendor import pkg_resources
  File "/usr/local/lib/python3.4/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 92, in <module>
    raise RuntimeError("Python 3.5 or later is required")
```

**Comment by thepont** [comment]
Closing, after further testing this seems to be something funky to do with the version of pip or python installed by apt in the docker file

**Comment by liron-strattic** [comment]
@thepont Did you figure out what was going wrong with the python install? Having the same issue.

**Comment by thepont** [comment]
Hey @liron-strattic, I looked back at my changes to the docker file after this issue and it seems I resolved it by not upgrading `pip` during installation.

Although looking around the internet for why this happens, it seems that people have also managed to fix this while upgrading `pip`

https://github.com/jupyterhub/jupyterhub/issues/1037
