### ISSUE TITLE
Precedence of --profile CLI argument vs AWS_PROFILE broken

### ISSUE THREAD

**Issue by mvallaly-rally** [aws/aws-cli#4895]
According to the docs (and in accordance with most unix tools) command line arguments generally override environment variables.  https://amzn.to/2tglZeS

This seems to be broken or the docs are wrong.

aws --version
aws-cli/1.17.9 Python/3.8.1 Darwin/19.2.0 botocore/1.14.9

You can easily confirm this behavior via:

``AWS_PROFILE=foo aws --profile bar --version``

**Comment by klaytaybai** [comment]
Hi @mvallaly-rally, I wasn't able to reproduce this issue using the same version.  If this still seems to be an issue for you, could you please provide obfuscated screenshot evidence or further reproduction steps?

My OS version is earlier.  Maybe that's an issue, but I don't think so.

**Comment by pikeas** [comment]
@mvallaly-rally You might be running into https://github.com/aws/aws-cli/issues/3304.

**Comment by mvallaly-rally** [comment]
`AWS_PROFILE=foo aws --profile bar --version
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/local/Cellar/awscli/1.17.9/libexec/lib/python3.8/site-packages/awscli/clidriver.py", line 69, in main
    rc = driver.main()
  File "/usr/local/Cellar/awscli/1.17.9/libexec/lib/python3.8/site-packages/awscli/clidriver.py", line 203, in main
    command_table = self._get_command_table()
  File "/usr/local/Cellar/awscli/1.17.9/libexec/lib/python3.8/site-packages/awscli/clidriver.py", line 112, in _get_command_table
    self._command_table = self._build_command_table()
  File "/usr/local/Cellar/awscli/1.17.9/libexec/lib/python3.8/site-packages/awscli/clidriver.py", line 129, in _build_command_table
    self.session.emit('building-command-table.main',
  File "/usr/local/Cellar/awscli/1.17.9/libexec/lib/python3.8/site-packages/botocore/session.py", line 674, in emit
    return self._events.emit(event_name, **kwargs)
  File "/usr/local/Cellar/awscli/1.17.9/libexec/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/Cellar/awscli/1.17.9/libexec/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/Cellar/awscli/1.17.9/libexec/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/Cellar/awscli/1.17.9/libexec/lib/python3.8/site-packages/awscli/customizations/preview.py", line 69, in mark_as_preview
    service_name=original_command.service_model.service_name,
  File "/usr/local/Cellar/awscli/1.17.9/libexec/lib/python3.8/site-packages/awscli/clidriver.py", line 328, in service_model
    return self._get_service_model()
  File "/usr/local/Cellar/awscli/1.17.9/libexec/lib/python3.8/site-packages/awscli/clidriver.py", line 345, in _get_service_model
    api_version = self.session.get_config_variable('api_versions').get(
  File "/usr/local/Cellar/awscli/1.17.9/libexec/lib/python3.8/site-packages/botocore/session.py", line 237, in get_config_variable
    return self.get_component('config_store').get_config_variable(
  File "/usr/local/Cellar/awscli/1.17.9/libexec/lib/python3.8/site-packages/botocore/configprovider.py", line 290, in get_config_variable
    return provider.provide()
  File "/usr/local/Cellar/awscli/1.17.9/libexec/lib/python3.8/site-packages/botocore/configprovider.py", line 387, in provide
    value = provider.provide()
  File "/usr/local/Cellar/awscli/1.17.9/libexec/lib/python3.8/site-packages/botocore/configprovider.py", line 448, in provide
    scoped_config = self._session.get_scoped_config()
  File "/usr/local/Cellar/awscli/1.17.9/libexec/lib/python3.8/site-packages/botocore/session.py", line 337, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (foo) could not be found`
