### ISSUE TITLE
aws help fails with no such file or directory

### ISSUE THREAD

**Issue by vkivinie** [aws/aws-cli#510]
Hi,

I just did a clean install of latest Debian 7.1, python 2.7.3 and aws-cli 1.2.5 (installed via pip). Problem is that I cannot get the "aws help" command working. Just to be sure I installed the aws-cli to another Debian server straight from Github without using pip but the problem is exactly the same.

Below is the debug log from the command:

root@stacy:/home/valtteri# aws help --debug
2013-11-25 21:25:11,292 - botocore.hooks - DEBUG - Event doc-title.Provider.aws: calling handler <bound method ProviderDocumentEventHandler.doc_title of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,293 - botocore.hooks - DEBUG - Event doc-description.Provider.aws: calling handler <bound method ProviderDocumentEventHandler.doc_description of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,318 - botocore.hooks - DEBUG - Event doc-synopsis-start.Provider.aws: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_start of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,319 - botocore.hooks - DEBUG - Event doc-synopsis-option.Provider.aws.debug: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_option of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,319 - botocore.hooks - DEBUG - Event doc-synopsis-option.Provider.aws.endpoint-url: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_option of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,320 - botocore.hooks - DEBUG - Event doc-synopsis-option.Provider.aws.no-verify-ssl: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_option of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,320 - botocore.hooks - DEBUG - Event doc-synopsis-option.Provider.aws.no-paginate: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_option of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,321 - botocore.hooks - DEBUG - Event doc-synopsis-option.Provider.aws.output: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_option of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,321 - botocore.hooks - DEBUG - Event doc-synopsis-option.Provider.aws.query: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_option of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,321 - botocore.hooks - DEBUG - Event doc-synopsis-option.Provider.aws.profile: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_option of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,322 - botocore.hooks - DEBUG - Event doc-synopsis-option.Provider.aws.region: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_option of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,322 - botocore.hooks - DEBUG - Event doc-synopsis-option.Provider.aws.version: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_option of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,323 - botocore.hooks - DEBUG - Event doc-synopsis-option.Provider.aws.color: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_option of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,323 - botocore.hooks - DEBUG - Event doc-synopsis-end.Provider.aws: calling handler <bound method ProviderDocumentEventHandler.doc_synopsis_end of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,323 - botocore.hooks - DEBUG - Event doc-options-start.Provider.aws: calling handler <bound method ProviderDocumentEventHandler.doc_options_start of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,324 - botocore.hooks - DEBUG - Event doc-option.Provider.aws.debug: calling handler <bound method ProviderDocumentEventHandler.doc_option of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,324 - botocore.hooks - DEBUG - Event doc-option-example.Provider.aws.debug: calling handler <bound method ParamShorthand.add_example_fn of <awscli.argprocess.ParamShorthand object at 0x1482e10>>
2013-11-25 21:25:11,325 - botocore.hooks - DEBUG - Event doc-option.Provider.aws.endpoint-url: calling handler <bound method ProviderDocumentEventHandler.doc_option of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,325 - botocore.hooks - DEBUG - Event doc-option-example.Provider.aws.endpoint-url: calling handler <bound method ParamShorthand.add_example_fn of <awscli.argprocess.ParamShorthand object at 0x1482e10>>
2013-11-25 21:25:11,325 - botocore.hooks - DEBUG - Event doc-option.Provider.aws.no-verify-ssl: calling handler <bound method ProviderDocumentEventHandler.doc_option of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,326 - botocore.hooks - DEBUG - Event doc-option-example.Provider.aws.no-verify-ssl: calling handler <bound method ParamShorthand.add_example_fn of <awscli.argprocess.ParamShorthand object at 0x1482e10>>
2013-11-25 21:25:11,326 - botocore.hooks - DEBUG - Event doc-option.Provider.aws.no-paginate: calling handler <bound method ProviderDocumentEventHandler.doc_option of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,326 - botocore.hooks - DEBUG - Event doc-option-example.Provider.aws.no-paginate: calling handler <bound method ParamShorthand.add_example_fn of <awscli.argprocess.ParamShorthand object at 0x1482e10>>
2013-11-25 21:25:11,327 - botocore.hooks - DEBUG - Event doc-option.Provider.aws.output: calling handler <bound method ProviderDocumentEventHandler.doc_option of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,327 - botocore.hooks - DEBUG - Event doc-option-example.Provider.aws.output: calling handler <bound method ParamShorthand.add_example_fn of <awscli.argprocess.ParamShorthand object at 0x1482e10>>
2013-11-25 21:25:11,327 - botocore.hooks - DEBUG - Event doc-option.Provider.aws.query: calling handler <bound method ProviderDocumentEventHandler.doc_option of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,328 - botocore.hooks - DEBUG - Event doc-option-example.Provider.aws.query: calling handler <bound method ParamShorthand.add_example_fn of <awscli.argprocess.ParamShorthand object at 0x1482e10>>
2013-11-25 21:25:11,328 - botocore.hooks - DEBUG - Event doc-option.Provider.aws.profile: calling handler <bound method ProviderDocumentEventHandler.doc_option of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,328 - botocore.hooks - DEBUG - Event doc-option-example.Provider.aws.profile: calling handler <bound method ParamShorthand.add_example_fn of <awscli.argprocess.ParamShorthand object at 0x1482e10>>
2013-11-25 21:25:11,329 - botocore.hooks - DEBUG - Event doc-option.Provider.aws.region: calling handler <bound method ProviderDocumentEventHandler.doc_option of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,329 - botocore.hooks - DEBUG - Event doc-option-example.Provider.aws.region: calling handler <bound method ParamShorthand.add_example_fn of <awscli.argprocess.ParamShorthand object at 0x1482e10>>
2013-11-25 21:25:11,329 - botocore.hooks - DEBUG - Event doc-option.Provider.aws.version: calling handler <bound method ProviderDocumentEventHandler.doc_option of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,330 - botocore.hooks - DEBUG - Event doc-option-example.Provider.aws.version: calling handler <bound method ParamShorthand.add_example_fn of <awscli.argprocess.ParamShorthand object at 0x1482e10>>
2013-11-25 21:25:11,330 - botocore.hooks - DEBUG - Event doc-option.Provider.aws.color: calling handler <bound method ProviderDocumentEventHandler.doc_option of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,330 - botocore.hooks - DEBUG - Event doc-option-example.Provider.aws.color: calling handler <bound method ParamShorthand.add_example_fn of <awscli.argprocess.ParamShorthand object at 0x1482e10>>
2013-11-25 21:25:11,331 - botocore.hooks - DEBUG - Event doc-options-end.Provider.aws: calling handler <bound method ProviderDocumentEventHandler.doc_options_end of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,331 - botocore.hooks - DEBUG - Event doc-subitems-start.Provider.aws: calling handler <bound method ProviderDocumentEventHandler.doc_subitems_start of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,331 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.autoscaling: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,332 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.cloudformation: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,332 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.cloudtrail: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,332 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.cloudwatch: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,332 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.configure: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,333 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.directconnect: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,333 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.dynamodb: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,333 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.ec2: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,333 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.elasticache: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,334 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.elasticbeanstalk: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,334 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.elastictranscoder: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,334 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.elb: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,334 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.help: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,335 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.iam: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,335 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.importexport: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,335 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.opsworks: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,335 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.rds: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,336 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.redshift: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,336 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.route53: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,336 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.s3: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,337 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.s3api: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,337 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.ses: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,337 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.sns: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,337 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.sqs: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,338 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.storagegateway: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,338 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.sts: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,338 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.support: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,338 - botocore.hooks - DEBUG - Event doc-subitem.Provider.aws.swf: calling handler <bound method ProviderDocumentEventHandler.doc_subitem of <bcdoc.clidocs.ProviderDocumentEventHandler object at 0x1515f50>>
2013-11-25 21:25:11,339 - botocore.hooks - DEBUG - Event doc-examples.Provider.aws: calling handler <function add_examples at 0x13c7c08>
2013-11-25 21:25:11,339 - awscli.customizations.addexamples - DEBUG - Looking for example file at: /usr/local/lib/python2.7/dist-packages/awscli/examples/Provider/aws.rst
2013-11-25 21:25:11,753 - awscli.help - DEBUG - Running command: ['groff', '-man', '-T', 'ascii']
2013-11-25 21:25:11,835 - awscli.help - DEBUG - Running command: ['less', '-R']
2013-11-25 21:25:11,853 - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 186, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/awscli/help.py", line 233, in **call**
    self.renderer.render(self.doc.getvalue())
  File "/usr/local/lib/python2.7/dist-packages/awscli/help.py", line 95, in render
    p4 = self._popen(cmdline, stdin=PIPE)
  File "/usr/local/lib/python2.7/dist-packages/awscli/help.py", line 120, in _popen
    return Popen(_args, *_kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2013-11-25 21:25:11,856 - awscli.clidriver - DEBUG - Exiting with rc 255
[Errno 2] No such file or directory

**Comment by jjkatusa** [comment]
@jamesls thanks for this post...after prolonged search i found this and aws cli is working for me now. I am getting a different error now as below, 
"The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256". I am running this inside a docker container. Please help on this issue.
