### ISSUE TITLE
When only IMDSV2 is enabled, aws cli not working without default region 

### ISSUE THREAD

**Issue by anilkun** [aws/aws-cli#5104]
Instance state:
- **IMDSV1 and IMDSV2 are running**
- No default region set in a given instance (no ~/.aws/config and no AWS_DEFAULT_REGION)

aws secretsmanager get-secret-value --secret-id <path> **works fine**

Instance state:
- **Only IMDSV2 is running**
- No default region set in a given instance (no ~/.aws/config and no AWS_DEFAULT_REGION)

aws secretsmanager get-secret-value --secret-id <path> **errors out**
aws secretsmanager get-secret-value --secret-id <path>
You must specify a region. You can also configure your region by running "aws configure".

**Comment by nydalal** [comment]
Adding some more details

If we disable, IMDSv2 by "--http-endpoint enabled --http-token optional", then `aws secretsmanager get-secret-value --secret-id` works without issue

When IMDSv2 is enabled, `aws secretsmanager get-secret-value --secret-id` fails withe error above

`MainThread - awscli.clidriver - DEBUG - You must specify a region. You can also configure your region by running "aws configure".
Traceback (most recent call last):
  File "site-packages/awscli/clidriver.py", line 335, in main
  File "site-packages/awscli/clidriver.py", line 507, in __call__
  File "site-packages/awscli/clidriver.py", line 685, in __call__
  File "site-packages/awscli/clidriver.py", line 804, in invoke
  File "site-packages/botocore/session.py", line 811, in create_client
  File "site-packages/botocore/client.py", line 81, in create_client
  File "site-packages/botocore/client.py", line 179, in _get_client_args
  File "site-packages/botocore/args.py", line 49, in get_client_args
  File "site-packages/botocore/args.py", line 129, in compute_client_args
  File "site-packages/botocore/args.py", line 192, in _compute_endpoint_config
  File "site-packages/botocore/args.py", line 215, in _resolve_endpoint
  File "site-packages/botocore/client.py", line 253, in resolve
  File "site-packages/botocore/regions.py", line 122, in construct_endpoint
  File "site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
botocore.exceptions.NoRegionError: You must specify a region.
You must specify a region. You can also configure your region by running "aws configure".`

When we explicitly mention region, it works on IMDSv2
`aws secretsmanager get-secret-value --secret-id --region us-east-1`

Versions being used
`aws --version
aws-cli/2.0.2 Python/3.7.3 Linux/4.15.0-1060-aws botocore/2.0.0dev6`

**Comment by kdaily** [comment]
Hi @anilkun,

This may have been taken care of by #5207. Can you retry?

There is also an open issue on documentation on controlling IMDS usage: #5623
