### ISSUE TITLE
amplify status returns error related to lastPushTimeStamp

### ISSUE THREAD

**Issue by chantlong** [aws/aws-cli#5116]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

I have been working on the `stg` env for a while.

When I do `amplify env checkout dev` to my existing `dev` env and run `amplify status`,
I get the following error in the **Logs/Output**

The error also happens when I do `amplify env add` a new `env` and check `amplify status`

This does not happen when I check back out to `stg` and check `amplify status`.

I tried the solution used in a related issue but it didn't work. (Deleting all lastPushTimeStamps in the amplify meta config)
[#1606](https://github.com/aws-amplify/amplify-cli/issues/1606)

**SDK version number**
Amplify Cli 4.17.2

**Platform/OS/Hardware/Device**
Mac OS Mojave 10.14.6
Node 12.13.0

**Expected behavior**
Just show my statuses

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

```
❯ amplify status

Current Environment: dev

Cannot read property 'lastPushTimeStamp' of undefined
TypeError: Cannot read property 'lastPushTimeStamp' of undefined
    at getResourcesToBeCreated (/Users/XXX/.nvm/versions/node/v12.13.1/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:96:76)
    at getResourceStatus (/Users/XXX/.nvm/versions/node/v12.13.1/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:175:32)
    at AmplifyToolkit.showResourceTable [as _showResourceTable] (/Users/XXX/.nvm/versions/node/v12.13.1/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:201:102)
    at Object.run (/Users/XXX/.nvm/versions/node/v12.13.1/lib/node_modules/@aws-amplify/cli/lib/commands/status.js:6:31)
    at Object.executeAmplifyCommand (/Users/XXX/.nvm/versions/node/v12.13.1/lib/node_modules/@aws-amplify/cli/lib/index.js:96:25)
    at executePluginModuleCommand (/Users/XXX/.nvm/versions/node/v12.13.1/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:131:32)
    at async Object.executeCommand (/Users/XXX/.nvm/versions/node/v12.13.1/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:16:9)
    at async Object.run (/Users/XXX/.nvm/versions/node/v12.13.1/lib/node_modules/@aws-amplify/cli/lib/index.js:43:9)
```

The content of a new env `amplify-meta.json`
```
{
  "providers": {
      "awscloudformation": {
          "AuthRoleName": "amplify-xxxxxx-xxx-XXXX-authRole",
          "UnauthRoleArn": "arn:aws:iam::XXX:role/amplify-xxxxxx-xxx-XXXX-unauthRole",
          "AuthRoleArn": "arn:aws:iam::XXX:role/amplify-xxxxxx-xxx-XXXX-authRole",
          "Region": "ap-northeast-1",
          "DeploymentBucketName": "amplify-xxxxxx-xxx-XXXX-deployment",
          "UnauthRoleName": "amplify-xxxxxx-xxx-XXXX-unauthRole",
          "StackName": "amplify-xxxxxx-xxx-XXXX",
          "StackId": "arn:aws:cloudformation:ap-northeast-1:XXX:stack/amplify-xxxxxx-xxx-XXXX/XXXXXX",
          "AmplifyAppId": "XXX"
      }
  },
  "auth": {
      "XXXXXXXXXXXXXX": {
          "service": "Cognito",
          "providerPlugin": "awscloudformation",
          "dependsOn": [
              {
                  "category": "function",
                  "resourceName": "XXXXXXXXXXXXXXPostConfirmation",
                  "triggerProvider": "Cognito",
                  "attributes": [
                      "Arn",
                      "Name"
                  ]
              }
          ]
      },
      "userPoolGroups": {
          "service": "Cognito-UserPool-Groups",
          "providerPlugin": "awscloudformation",
          "dependsOn": [
              {
                  "category": "auth",
                  "resourceName": "XXXXXXXXXXXXXX",
                  "attributes": [
                      "UserPoolId",
                      "AppClientIDWeb",
                      "AppClientID",
                      "IdentityPoolId"
                  ]
              }
          ]
      }
  },
  "api": {
      "api": {
          "service": "AppSync",
          "providerPlugin": "awscloudformation",
          "output": {
              "authConfig": {
                  "additionalAuthenticationProviders": [],
                  "defaultAuthentication": {
                      "authenticationType": "AMAZON_COGNITO_USER_POOLS",
                      "userPoolConfig": {
                          "userPoolId": "authXXXXXXXXXXXXXX"
                      }
                  }
              }
          }
      },
      "XXXX": {
          "service": "API Gateway",
          "providerPlugin": "awscloudformation",
          "dependsOn": [
              {
                  "category": "function",
                  "resourceName": "spotifyapi",
                  "attributes": [
                      "Name",
                      "Arn"
                  ]
              },
              {
                  "category": "auth",
                  "resourceName": "XXXXXXXXXXXXXX",
                  "attributes": [
                      "UserPoolId"
                  ]
              },
              {
                  "category": "auth",
                  "resourceName": "userPoolGroups",
                  "attributes": [
                      "usersGroupRole"
                  ]
              }
          ]
      },
      "XXXX": {
          "service": "API Gateway",
          "providerPlugin": "awscloudformation",
          "dependsOn": [
              {
                  "category": "function",
                  "resourceName": "XXXXXXXXXcb1fe917",
                  "attributes": [
                      "Name",
                      "Arn"
                  ]
              }
          ]
      }
  },
  "function": {
      "XXXXXXXXXXXXXXPostConfirmation": {
          "service": "Lambda",
          "providerPlugin": "awscloudformation",
          "build": true
      },
      "XXXXXXX": {
          "service": "Lambda",
          "providerPlugin": "awscloudformation",
          "build": true
      }
  },
  "storage": {
      "XXXXXXXXX": {
          "service": "S3",
          "providerPlugin": "awscloudformation",
          "dependsOn": [
              {
                  "category": "auth",
                  "resourceName": "XXXXXXXXXXXXXX",
                  "attributes": [
                      "UserPoolId"
                  ]
              },
              {
                  "category": "auth",
                  "resourceName": "userPoolGroups",
                  "attributes": [
                      "usersGroupRole"
                  ]
              }
          ]
      }
  }
}
```
**Additional context**

**Comment by KaibaLopez** [comment]
Hi @chantlong ,
Are you maybe on the wrong repo?Shouldn't this issue be on the [aplify-cli](https://github.com/aws-amplify/amplify-cli/issues) or am I missing something?

**Comment by chantlong** [comment]
@KaibaLopez 
Sorry, I was meant to post this in the amplify cli repo! Will close!
