### ISSUE TITLE
Not able to run aws-mfa. `ImportError: cannot import name 'ssl'`

### ISSUE THREAD

**Issue by joedspin** [aws/aws-cli#5182]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Getting an error at the command prompt when running `aws-mfa`

**SDK version number**
version: aws-cli/2.0.10 Python/3.8.2 Darwin/18.7.0 botocore/2.0.0dev14

**Platform/OS/Hardware/Device**
What are you running the cli on?
MacBook Pro with Mojave 10.14.6

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

**Expected behavior**

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.
`Traceback (most recent call last):
  File "/Users/joe.despinosa/.pyenv/versions/3.6.5/bin/aws-mfa", line 7, in <module>
    from awsmfa import main
  File "/Users/joe.despinosa/.pyenv/versions/3.6.5/lib/python3.6/site-packages/awsmfa/__init__.py", line 13, in <module>
    import boto3
  File "/Users/joe.despinosa/.pyenv/versions/3.6.5/lib/python3.6/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/Users/joe.despinosa/.pyenv/versions/3.6.5/lib/python3.6/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/Users/joe.despinosa/.pyenv/versions/3.6.5/lib/python3.6/site-packages/botocore/session.py", line 30, in <module>
    import botocore.credentials
  File "/Users/joe.despinosa/.pyenv/versions/3.6.5/lib/python3.6/site-packages/botocore/credentials.py", line 34, in <module>
    from botocore.config import Config
  File "/Users/joe.despinosa/.pyenv/versions/3.6.5/lib/python3.6/site-packages/botocore/config.py", line 16, in <module>
    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/Users/joe.despinosa/.pyenv/versions/3.6.5/lib/python3.6/site-packages/botocore/endpoint.py", line 22, in <module>
    from botocore.awsrequest import create_request_object
  File "/Users/joe.despinosa/.pyenv/versions/3.6.5/lib/python3.6/site-packages/botocore/awsrequest.py", line 26, in <module>
    import botocore.utils
  File "/Users/joe.despinosa/.pyenv/versions/3.6.5/lib/python3.6/site-packages/botocore/utils.py", line 31, in <module>
    import botocore.httpsession
  File "/Users/joe.despinosa/.pyenv/versions/3.6.5/lib/python3.6/site-packages/botocore/httpsession.py", line 8, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'ssl'
`
**Additional context**

**Comment by KaibaLopez** [comment]
Hi @joedspin ,
Can you give me some info on how to reproduce this issue?  what are you trying to do on which type of resource and what commands are you using?

**Comment by joedspin** [comment]
SOLVED: Reinstalled python 2.7.15 with `pyenv install -f 2.7.15`

Answer came from this post: https://stackoverflow.com/questions/59123154/importerror-cannot-import-name-md5

**Comment by joeeeeey** [comment]
I had the same issue when invoking `aws-cli` and my python version was 3.6.0.

`pyenv install -f 3.6.0` worked for me.
