### ISSUE TITLE
get-domain-statistics-report Unable to find a dashboard

### ISSUE THREAD

**Issue by shqear-mawdoo3** [aws/aws-cli#5210]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [x] Service API : I want to do get-domain-statistics-report using sesv2 service, what should I do?
- [ ] CLI : passing arguments or cli configurations.
- [x] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
```
No LSB modules are available.
Distributor ID:	Deepin
Description:	Deepin 15.11
Release:	15.11
Codename:	stable
```
```
pip -V
pip 19.0.3 from /usr/local/lib/python3.5/dist-packages/pip-19.0.3-py3.5.egg/pip (python 3.5)
```
```
aws --version
aws-cli/1.18.58 Python/3.5.3 Linux/4.15.0-30deepin-generic botocore/1.15.49
```

**Describe the question**
I'm trying to get the detailed statistics for SES (# of emails sent.. etc)
running this command : 
```
aws2 --profile mydomain sesv2 get-domain-statistics-report --domain 'mydomain.com' --start-date 1588338678 --end-date 1589807503
```
it give me this weird message : 
```
An error occurred (NotFoundException) when calling the GetDomainStatisticsReport operation: Unable to find a dashboard account for <xxxx>.
```

**Logs/output**
```
2020-05-18 18:03:27,342 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.0.0dev3 Python/3.7.3 Linux/4.15.0-30deepin-generic botocore/2.0.0dev2
2020-05-18 18:03:27,342 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--profile', 'mydomain', 'sesv2', 'get-domain-statistics-report', '--domain', 'mydomain.com', '--start-date', '1588338678', '--end-date', '1589807503', '--debug']
2020-05-18 18:03:27,342 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7f7acaedd950>
2020-05-18 18:03:27,342 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7f7acb828378>
2020-05-18 18:03:27,343 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7f7acae27158>
2020-05-18 18:03:27,343 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f7acb7cdbf8>
2020-05-18 18:03:27,344 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2020-05-18 18:03:27,344 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f7acb04ad08>
2020-05-18 18:03:27,344 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7f7acb086620>
2020-05-18 18:03:27,348 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.0.0dev3/dist/botocore/data/sesv2/2019-09-27/service-2.json
2020-05-18 18:03:27,356 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sesv2: calling handler <function add_waiters at 0x7f7acae64ea0>
2020-05-18 18:03:27,360 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('domain', <awscli.arguments.CLIArgument object at 0x7f7acac67f98>), ('start-date', <awscli.arguments.CLIArgument object at 0x7f7acac67fd0>), ('end-date', <awscli.arguments.CLIArgument object at 0x7f7acacfa048>)])
2020-05-18 18:03:27,360 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sesv2.get-domain-statistics-report: calling handler <function add_streaming_output_arg at 0x7f7acaeddea0>
2020-05-18 18:03:27,360 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sesv2.get-domain-statistics-report: calling handler <function add_cli_input_json at 0x7f7acb7d6268>
2020-05-18 18:03:27,361 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sesv2.get-domain-statistics-report: calling handler <function add_cli_input_yaml at 0x7f7acb7d6488>
2020-05-18 18:03:27,361 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sesv2.get-domain-statistics-report: calling handler <function unify_paging_params at 0x7f7acb08ae18>
2020-05-18 18:03:27,365 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.0.0dev3/dist/botocore/data/sesv2/2019-09-27/paginators-1.json
2020-05-18 18:03:27,365 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sesv2.get-domain-statistics-report: calling handler <function add_generate_skeleton at 0x7f7acaf52620>
2020-05-18 18:03:27,366 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sesv2.get-domain-statistics-report: calling handler <function add_auto_prompt at 0x7f7acae270d0>
2020-05-18 18:03:27,366 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sesv2.get-domain-statistics-report: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7f7acac6d080>>
2020-05-18 18:03:27,366 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sesv2.get-domain-statistics-report: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7f7ad124c7b8>>
2020-05-18 18:03:27,366 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sesv2.get-domain-statistics-report: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f7acac6d0b8>>
2020-05-18 18:03:27,366 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sesv2.get-domain-statistics-report: calling handler <bound method AutoPromptArgument.override_required_args of <awscli.customizations.autoprompt.AutoPromptArgument object at 0x7f7acac75668>>
2020-05-18 18:03:27,367 - MainThread - botocore.hooks - DEBUG - Changing event name from load-cli-arg.email.get-domain-statistics-report.domain to load-cli-arg.ses.get-domain-statistics-report.domain
2020-05-18 18:03:27,367 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ses.get-domain-statistics-report.domain: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f7ad124c550>
2020-05-18 18:03:27,367 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.sesv2.get-domain-statistics-report: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f7acb817c88>
2020-05-18 18:03:27,367 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'mydomain.com' for parameter "domain": 'mydomain.com'
2020-05-18 18:03:27,367 - MainThread - botocore.hooks - DEBUG - Changing event name from load-cli-arg.email.get-domain-statistics-report.start-date to load-cli-arg.ses.get-domain-statistics-report.start-date
2020-05-18 18:03:27,367 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ses.get-domain-statistics-report.start-date: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f7ad124c550>
2020-05-18 18:03:27,368 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.sesv2.get-domain-statistics-report: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f7acb817c88>
2020-05-18 18:03:27,368 - MainThread - awscli.arguments - DEBUG - Unpacked value of '1588338678' for parameter "start_date": '1588338678'
2020-05-18 18:03:27,368 - MainThread - botocore.hooks - DEBUG - Changing event name from load-cli-arg.email.get-domain-statistics-report.end-date to load-cli-arg.ses.get-domain-statistics-report.end-date
2020-05-18 18:03:27,368 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ses.get-domain-statistics-report.end-date: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f7ad124c550>
2020-05-18 18:03:27,368 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.sesv2.get-domain-statistics-report: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f7acb817c88>
2020-05-18 18:03:27,368 - MainThread - awscli.arguments - DEBUG - Unpacked value of '1589807503' for parameter "end_date": '1589807503'
2020-05-18 18:03:27,368 - MainThread - botocore.hooks - DEBUG - Changing event name from load-cli-arg.email.get-domain-statistics-report.cli-input-json to load-cli-arg.ses.get-domain-statistics-report.cli-input-json
2020-05-18 18:03:27,368 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ses.get-domain-statistics-report.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f7ad124c550>
2020-05-18 18:03:27,368 - MainThread - botocore.hooks - DEBUG - Changing event name from load-cli-arg.email.get-domain-statistics-report.cli-input-yaml to load-cli-arg.ses.get-domain-statistics-report.cli-input-yaml
2020-05-18 18:03:27,368 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ses.get-domain-statistics-report.cli-input-yaml: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f7ad124c550>
2020-05-18 18:03:27,368 - MainThread - botocore.hooks - DEBUG - Changing event name from load-cli-arg.email.get-domain-statistics-report.generate-cli-skeleton to load-cli-arg.ses.get-domain-statistics-report.generate-cli-skeleton
2020-05-18 18:03:27,368 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ses.get-domain-statistics-report.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f7ad124c550>
2020-05-18 18:03:27,368 - MainThread - botocore.hooks - DEBUG - Changing event name from load-cli-arg.email.get-domain-statistics-report.cli-auto-prompt to load-cli-arg.ses.get-domain-statistics-report.cli-auto-prompt
2020-05-18 18:03:27,368 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ses.get-domain-statistics-report.cli-auto-prompt: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f7ad124c550>
2020-05-18 18:03:27,369 - MainThread - botocore.hooks - DEBUG - Event calling-command.sesv2.get-domain-statistics-report: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7f7acac6d080>>
2020-05-18 18:03:27,369 - MainThread - botocore.hooks - DEBUG - Event calling-command.sesv2.get-domain-statistics-report: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7f7ad124c7b8>>
2020-05-18 18:03:27,369 - MainThread - botocore.hooks - DEBUG - Event calling-command.sesv2.get-domain-statistics-report: calling handler <bound method GenerateCliSkeletonArgument.generate_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f7acac6d0b8>>
2020-05-18 18:03:27,369 - MainThread - botocore.hooks - DEBUG - Event calling-command.sesv2.get-domain-statistics-report: calling handler <bound method AutoPromptArgument.auto_prompt_arguments of <awscli.customizations.autoprompt.AutoPromptArgument object at 0x7f7acac75668>>
2020-05-18 18:03:27,369 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2020-05-18 18:03:27,369 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2020-05-18 18:03:27,369 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2020-05-18 18:03:27,369 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2020-05-18 18:03:27,369 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2020-05-18 18:03:27,370 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.0.0dev3/dist/botocore/data/endpoints.json
2020-05-18 18:03:27,373 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f7acc830510>
2020-05-18 18:03:27,375 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.sesv2: calling handler <function add_generate_presigned_url at 0x7f7acc816d90>
2020-05-18 18:03:27,378 - MainThread - botocore.endpoint - DEBUG - Setting email timeout as (60, 60)
2020-05-18 18:03:27,378 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.0.0dev3/dist/botocore/data/_retry.json
2020-05-18 18:03:27,379 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: sesv2
2020-05-18 18:03:27,379 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.sesv2.GetDomainStatisticsReport: calling handler <function base64_decode_input_blobs at 0x7f7acae27950>
2020-05-18 18:03:27,380 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.sesv2.GetDomainStatisticsReport: calling handler <function generate_idempotent_uuid at 0x7f7acc7dd400>
2020-05-18 18:03:27,381 - MainThread - botocore.hooks - DEBUG - Event before-call.sesv2.GetDomainStatisticsReport: calling handler <function inject_api_version_header_if_needed at 0x7f7acc7d1d90>
2020-05-18 18:03:27,381 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=GetDomainStatisticsReport) with params: {'url_path': '/v2/email/deliverability-dashboard/statistics-report/mydomain.com', 'query_string': {'StartDate': '2020-05-01T13:11:18Z', 'EndDate': '2020-05-18T13:11:43Z'}, 'method': 'GET', 'headers': {'User-Agent': 'aws-cli/2.0.0dev3 Python/3.7.3 Linux/4.15.0-30deepin-generic botocore/2.0.0dev2'}, 'body': b'', 'url': 'https://email.eu-west-1.amazonaws.com/v2/email/deliverability-dashboard/statistics-report/mydomain.com?StartDate=2020-05-01T13%3A11%3A18Z&EndDate=2020-05-18T13%3A11%3A43Z', 'context': {'client_region': 'eu-west-1', 'client_config': <botocore.config.Config object at 0x7f7acaaf5550>, 'has_streaming_input': False, 'auth_type': None}}
2020-05-18 18:03:27,381 - MainThread - botocore.hooks - DEBUG - Event request-created.sesv2.GetDomainStatisticsReport: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f7acaaf5518>>
2020-05-18 18:03:27,381 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sesv2.GetDomainStatisticsReport: calling handler <function set_operation_specific_signer at 0x7f7acc7dd2f0>
2020-05-18 18:03:27,381 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2020-05-18 18:03:27,381 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
GET
/v2/email/deliverability-dashboard/statistics-report/mydomain.com
EndDate=2020-05-18T13%3A11%3A43Z&StartDate=2020-05-01T13%3A11%3A18Z
host:email.eu-west-1.amazonaws.com
x-amz-date:20200518T150327Z

host;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2020-05-18 18:03:27,382 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20200518T150327Z
20200518/eu-west-1/ses/aws4_request
xxxx
2020-05-18 18:03:27,382 - MainThread - botocore.auth - DEBUG - Signature:
xxxx
2020-05-18 18:03:27,382 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=GET, url=https://email.eu-west-1.amazonaws.com/v2/email/deliverability-dashboard/statistics-report/mydomain.com?StartDate=2020-05-01T13%3A11%3A18Z&EndDate=2020-05-18T13%3A11%3A43Z, headers={'User-Agent': b'aws-cli/2.0.0dev3 Python/3.7.3 Linux/4.15.0-30deepin-generic botocore/2.0.0dev2', 'X-Amz-Date': b'20200518T150327Z', 'Authorization': xxx Credential=xxx/20200518/eu-west-1/ses/aws4_request, SignedHeaders=host;x-amz-date, Signature=xxx'}>
2020-05-18 18:03:27,382 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): email.eu-west-1.amazonaws.com:443
2020-05-18 18:03:27,932 - MainThread - urllib3.connectionpool - DEBUG - https://email.eu-west-1.amazonaws.com:443 "GET /v2/email/deliverability-dashboard/statistics-report/mydomain.com?StartDate=2020-05-01T13%3A11%3A18Z&EndDate=2020-05-18T13%3A11%3A43Z HTTP/1.1" 404 68
2020-05-18 18:03:27,933 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-RequestId': 'b6a04310-6f1a-45c3-85ef-d711660759a3', 'x-amzn-ErrorType': 'NotFoundException', 'Content-Type': 'application/x-amz-json-1.1', 'Content-Length': '68', 'Date': 'Mon, 18 May 2020 15:03:27 GMT'}
2020-05-18 18:03:27,933 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"message":"Unable to find a dashboard account for <xxx>."}'
2020-05-18 18:03:27,933 - MainThread - botocore.hooks - DEBUG - Event needs-retry.sesv2.GetDomainStatisticsReport: calling handler <botocore.retryhandler.RetryHandler object at 0x7f7acaaf59e8>
2020-05-18 18:03:27,933 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2020-05-18 18:03:27,934 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "site-packages/awscli/clidriver.py", line 327, in main
  File "site-packages/awscli/clidriver.py", line 476, in __call__
  File "site-packages/awscli/clidriver.py", line 654, in __call__
  File "site-packages/awscli/clidriver.py", line 775, in invoke
  File "site-packages/awscli/clidriver.py", line 787, in _make_client_call
  File "site-packages/botocore/client.py", line 274, in _api_call
  File "site-packages/botocore/client.py", line 584, in _make_api_call
botocore.errorfactory.NotFoundException: An error occurred (NotFoundException) when calling the GetDomainStatisticsReport operation: Unable to find a dashboard account for <775006283147>.
2020-05-18 18:03:27,934 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

An error occurred (NotFoundException) when calling the GetDomainStatisticsReport operation: Unable to find a dashboard account for <775006283147>.
```

**Comment by KaibaLopez** [comment]
Hi @shqear-mawdoo3 ,
I'll take a closer look at this but in the mean time can you please remove the logs or edit them to hide you private information.

**Comment by shqear-mawdoo3** [comment]
@KaibaLopez thanks for your support
please let me know is that a bug or something wrong with my command?
