### ISSUE TITLE
ec2-instance-connect send-ssh-public-key does not support ed25519 public keys

### ISSUE THREAD

**Issue by bcatubig** [aws/aws-cli#5243]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Using an `ed25519` public key causes a validation error

**SDK version number**

`aws-cli/2.0.16 Python/3.8.2 Darwin/19.4.0 botocore/2.0.0dev20`

**Platform/OS/Hardware/Device**

```
Darwin laptop 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
```

**To Reproduce (observed behavior)**

```
aws ec2-instance-connect send-ssh-public-key --instance-id <instance_id> --availability-zone us-east-1a --instance-os-user <ec2_user> --ssh-public-key file://~/.ssh/id_ed25519.pub
```

**Expected behavior**
ed25519 public keys should be supported and not cause a validation error

**Logs/output**
```
2020-05-28 15:48:31,066 - MainThread - awscli.clidriver - DEBUG - Client side parameter validation failed
Traceback (most recent call last):
  File "/usr/local/Cellar/awscli/2.0.16/libexec/lib/python3.8/site-packages/awscli/clidriver.py", line 335, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/Cellar/awscli/2.0.16/libexec/lib/python3.8/site-packages/awscli/clidriver.py", line 507, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/Cellar/awscli/2.0.16/libexec/lib/python3.8/site-packages/awscli/clidriver.py", line 682, in __call__
    return self._operation_caller.invoke(
  File "/usr/local/Cellar/awscli/2.0.16/libexec/lib/python3.8/site-packages/awscli/clidriver.py", line 805, in invoke
    response = self._make_client_call(
  File "/usr/local/Cellar/awscli/2.0.16/libexec/lib/python3.8/site-packages/awscli/clidriver.py", line 817, in _make_client_call
    response = getattr(client, xform_name(operation_name))(
  File "/usr/local/Cellar/awscli/2.0.16/libexec/lib/python3.8/site-packages/botocore/client.py", line 208, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/Cellar/awscli/2.0.16/libexec/lib/python3.8/site-packages/botocore/client.py", line 499, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/usr/local/Cellar/awscli/2.0.16/libexec/lib/python3.8/site-packages/botocore/client.py", line 547, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/usr/local/Cellar/awscli/2.0.16/libexec/lib/python3.8/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid length for parameter SSHPublicKey, value: 107, valid range: 256-inf

Parameter validation failed:
Invalid length for parameter SSHPublicKey, value: 107, valid range: 256-inf
```

**Additional context**

**Comment by kdaily** [comment]
Hi @bcatubig, thanks for reporting this behavior.

According to the documentation, only RSA keys are supported:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-methods.html#ec2-instance-connect-connecting-aws-cli

Would you be able to use and send an RSA public key?

**Comment by bcatubig** [comment]
Hi @kdaily, 

Yes, I am using RSA keys for the time being.

Thanks!

**Comment by kdaily** [comment]
Hi @bcatubig,

If you feel that you need this feature, please open a thread on the AWS Discussion Forum for EC2:

https://forums.aws.amazon.com/forum.jspa?forumID=30

**Comment by julian-alarcon** [comment]
There is already a forum/request open https://forums.aws.amazon.com/thread.jspa?threadID=250753

**Comment by kdaily** [comment]
Hi @julian-alarcon, thanks for posting that. I'm going to transfer this issue to the central AWS SDK tracking repository, and follow up with the EC2 team to see if I can get any further details.
