### ISSUE TITLE
Error when profile not found

### ISSUE THREAD

**Issue by leggiero** [aws/aws-cli#5248]
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
This issue is present in the latest AWS CLI v1 and didn't happen in the AWS CLI v2:
If `AWS_PROFILE` env var is set with an invalid profile (that doesn't exist in the `$HOME/.aws/credentials`), ANY cli command will produce an error and print a long stack trace, by raising `ProfileNotFound` python exception and and exit status code `1`.

In the AWS CLI v2 this is properly handled and a short descriptive message is shown:
`The config profile (the-invalid-profile-name) could not be found`
And the exit status code is `130`.

**SDK version number**
`aws-cli/1.18.69 Python/3.8.2 Linux/5.4.0-33-generic botocore/1.16.19`

The correct behaviour in AWS CLI v2 was tested:
`aws-cli/2.0.16 Python/3.7.3 Linux/5.4.0-33-generic botocore/2.0.0dev20`

**Platform/OS/Hardware/Device**
Ubuntu 20.04 - Python 3.8.2

**To Reproduce (observed behavior)**
Using AWS CLI v1 and also using AWS CLI v2 (where the issue is not present):
```
AWS_PROFILE=invalid aws s3 ls
```
**Expected behavior**
Display a short and descriptive error message (without a long stack trace) and the exit status code `130`.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.
```
$ AWS_PROFILE=invalid aws s3 ls
Traceback (most recent call last):
  File "/home/user/.local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/home/user/.local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/home/user/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 69, in main
    rc = driver.main()
  File "/home/user/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 203, in main
    command_table = self._get_command_table()
  File "/home/user/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 112, in _get_command_table
    self._command_table = self._build_command_table()
  File "/home/user/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 129, in _build_command_table
    self.session.emit('building-command-table.main',
  File "/home/user/.local/lib/python3.8/site-packages/botocore/session.py", line 674, in emit
    return self._events.emit(event_name, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/awscli/customizations/preview.py", line 69, in mark_as_preview
    service_name=original_command.service_model.service_name,
  File "/home/user/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 328, in service_model
    return self._get_service_model()
  File "/home/user/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 345, in _get_service_model
    api_version = self.session.get_config_variable('api_versions').get(
  File "/home/user/.local/lib/python3.8/site-packages/botocore/session.py", line 237, in get_config_variable
    return self.get_component('config_store').get_config_variable(
  File "/home/user/.local/lib/python3.8/site-packages/botocore/configprovider.py", line 293, in get_config_variable
    return provider.provide()
  File "/home/user/.local/lib/python3.8/site-packages/botocore/configprovider.py", line 390, in provide
    value = provider.provide()
  File "/home/user/.local/lib/python3.8/site-packages/botocore/configprovider.py", line 451, in provide
    scoped_config = self._session.get_scoped_config()
  File "/home/user/.local/lib/python3.8/site-packages/botocore/session.py", line 337, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (invalid) could not be found
```

**Additional context**
Note that when the profile is invalid, it is not possible even to show the version in the AWS CLI v1:
```
$ AWS_PROFILE=invalid aws --version
(the stack trace error occurs)
```
If you try to see the version with an invalid profile in AWS CLI v2, the version is displayed normally without even displaying the profile not found error message.

**Comment by kdaily** [comment]
Thanks for reporting, @leggiero! I can reproduce as well. I concur that while the error reported is correct, getting a long Python stack trace isn't the best experience on the command line.

**Comment by benkehoe** [comment]
I think this is probably related to https://github.com/boto/botocore/issues/1460

**Comment by kdaily** [comment]
I think this has been fixed with https://github.com/aws/aws-cli/pull/6066. With AWS CLI v1, I now get:

```
> AWS_PROFILE=invalid aws s3 ls

The config profile (invalid) could not be found
```

```
> AWS_PROFILE=invalid aws --version
aws-cli/1.20.8 Python/3.8.5 Darwin/19.6.0 botocore/1.21.8
```
