### ISSUE TITLE
Setting environment variable will mess up authorization

### ISSUE THREAD

**Issue by Kenblair1226** [aws/aws-cli#5267]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Trying to get auth token of specific role_arn with aws cli, everything is fine when configure with commands only. Once setting AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY, got AccessDeniedException back. I encountered this because I deploy my containers with kubectl with env (secrets in k8s) setup. I can avoid this by specifying those env with other names. My guess is with AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY being set, awscli ignores role_arn settings and use some default role instead.

**Platform/OS/Hardware/Device**
latest alpine docker image: 3.12.0
aws cli 1.18.72

**To Reproduce (observed behavior)**
> / # aws configure set source_profile default
/ # aws configure set region xxxxxxxx
/ # aws configure set aws_access_key_id XXXXXXXX
/ # aws configure set aws_secret_access_key YYYYYYYY
/ # aws configure set role_arn arn:aws:iam::1111111111111:role/sw-dev-cicd
/ # aws ecr get-login
docker login -u AWS -p XXXXXX .....

Which is correct behavior, but once setting env...
> / # export AWS_ACCESS_KEY_ID=XXXXXXXX
/ # export AWS_SECRET_ACCESS_KEY=YYYYYYYY
/ # aws ecr get-login
>
> An error occurred (AccessDeniedException) when calling the GetAuthorizationToken operation: arn:aws:iam::222222222222:user/sw_dev_cicd_user is not authorized to perform: ecr:GetAuthorizationToken on resource: *

**Expected behavior**
awscli should respect the role_arn setting even env AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are set.

**Logs/output**
> / # aws ecr get-login --debug
2020-06-05 03:18:24,337 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.18.72 Python/3.8.3 Linux/4.19.76-linuxkit botocore/1.16.22
2020-06-05 03:18:24,337 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['ecr', 'get-login', '--debug']
2020-06-05 03:18:24,340 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7f55ac4e5160>
2020-06-05 03:18:24,341 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7f55aca9c310>
2020-06-05 03:18:24,343 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f55aca61280>
2020-06-05 03:18:24,349 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f55ac623940>
2020-06-05 03:18:24,350 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3.8/site-packages/botocore/data/ecr/2015-09-21/service-2.json
2020-06-05 03:18:24,355 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ecr: calling handler <function _inject_commands at 0x7f55ac63e3a0>
2020-06-05 03:18:24,355 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ecr: calling handler <function add_waiters at 0x7f55ac4eba60>
2020-06-05 03:18:24,369 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3.8/site-packages/botocore/data/ecr/2015-09-21/waiters-2.json
2020-06-05 03:18:24,372 - MainThread - botocore.hooks - DEBUG - Event building-command-table.get-login: calling handler <function add_waiters at 0x7f55ac4eba60>
2020-06-05 03:18:24,376 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.get-login.registry-ids: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f55ac4343a0>
2020-06-05 03:18:24,378 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.get-login.include-email: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f55ac4343a0>
2020-06-05 03:18:24,380 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.get-login: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f55aca72fd0>
2020-06-05 03:18:24,380 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2020-06-05 03:18:24,381 - MainThread - botocore.credentials - INFO - Found credentials in environment variables.
2020-06-05 03:18:24,382 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3.8/site-packages/botocore/data/endpoints.json
2020-06-05 03:18:24,392 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f55acf8fe50>
2020-06-05 03:18:24,395 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.ecr: calling handler <function add_generate_presigned_url at 0x7f55acfe1790>
2020-06-05 03:18:24,401 - MainThread - botocore.endpoint - DEBUG - Setting api.ecr timeout as (60, 60)
2020-06-05 03:18:24,402 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3.8/site-packages/botocore/data/_retry.json
2020-06-05 03:18:24,403 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: ecr
2020-06-05 03:18:24,404 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.ecr.GetAuthorizationToken: calling handler <function generate_idempotent_uuid at 0x7f55acf3df70>
2020-06-05 03:18:24,405 - MainThread - botocore.hooks - DEBUG - Event before-call.ecr.GetAuthorizationToken: calling handler <function inject_api_version_header_if_needed at 0x7f55acf43820>
2020-06-05 03:18:24,406 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=GetAuthorizationToken) with params: {'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'X-Amz-Target': 'AmazonEC2ContainerRegistry_V20150921.GetAuthorizationToken', 'Content-Type': 'application/x-amz-json-1.1', 'User-Agent': 'aws-cli/1.18.72 Python/3.8.3 Linux/4.19.76-linuxkit botocore/1.16.22'}, 'body': b'{}', 'url': 'https://api.ecr.ap-northeast-1.amazonaws.com/', 'context': {'client_region': 'ap-northeast-1', 'client_config': <botocore.config.Config object at 0x7f55ac14aee0>, 'has_streaming_input': False, 'auth_type': None}}
2020-06-05 03:18:24,408 - MainThread - botocore.hooks - DEBUG - Event request-created.ecr.GetAuthorizationToken: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f55ac14ad00>>
2020-06-05 03:18:24,408 - MainThread - botocore.hooks - DEBUG - Event choose-signer.ecr.GetAuthorizationToken: calling handler <function set_operation_specific_signer at 0x7f55acf3de50>
2020-06-05 03:18:24,409 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2020-06-05 03:18:24,410 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

> content-type:application/x-amz-json-1.1
host:api.ecr.ap-northeast-1.amazonaws.com
x-amz-date:20200605T031824Z
x-amz-target:AmazonEC2ContainerRegistry_V20150921.GetAuthorizationToken

> content-type;host;x-amz-date;x-amz-target
44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
2020-06-05 03:18:24,410 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20200605T031824Z
20200605/ap-northeast-1/ecr/aws4_request
22d5111e36fbc7bb4323a1c9b534bb433f8c77de5345b2a7de20efd8ad9ae520
2020-06-05 03:18:24,410 - MainThread - botocore.auth - DEBUG - Signature:
21bb04f57ea67e7cddd86b83f862b4118fc29ec48c1aa6c43bbe55c03c5738bd
2020-06-05 03:18:24,410 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://api.ecr.ap-northeast-1.amazonaws.com/, headers={'X-Amz-Target': b'AmazonEC2ContainerRegistry_V20150921.GetAuthorizationToken', 'Content-Type': b'application/x-amz-json-1.1', 'User-Agent': b'aws-cli/1.18.72 Python/3.8.3 Linux/4.19.76-linuxkit botocore/1.16.22', 'X-Amz-Date': b'20200605T031824Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=AXXXXXXA/20200605/ap-northeast-1/ecr/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=21bb04f57ea67e7cddd86b83f862b4118fc29ec48c1aa6c43bbe55c03c5738bd', 'Content-Length': '2'}>
2020-06-05 03:18:24,412 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.ecr.ap-northeast-1.amazonaws.com:443
2020-06-05 03:18:24,663 - MainThread - urllib3.connectionpool - DEBUG - https://api.ecr.ap-northeast-1.amazonaws.com:443 "POST / HTTP/1.1" 400 171
2020-06-05 03:18:24,663 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-RequestId': 'f31f277f-fb8b-4cba-ac93-71623eaeb84f', 'Date': 'Fri, 5 Jun 2020 03:18:24 GMT', 'Content-Type': 'application/x-amz-json-1.1', 'Content-Length': '171'}
2020-06-05 03:18:24,664 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"__type":"AccessDeniedException","Message":"User: arn:aws:iam::2222222222:user/sw_dev_cicd_user is not authorized to perform: ecr:GetAuthorizationToken on resource: *"}'
2020-06-05 03:18:24,668 - MainThread - botocore.hooks - DEBUG - Event needs-retry.ecr.GetAuthorizationToken: calling handler <botocore.retryhandler.RetryHandler object at 0x7f55ac3848e0>
2020-06-05 03:18:24,668 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2020-06-05 03:18:24,670 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/awscli/clidriver.py", line 217, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/lib/python3.8/site-packages/awscli/clidriver.py", line 358, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/lib/python3.8/site-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/usr/lib/python3.8/site-packages/awscli/customizations/ecr.py", line 73, in _run_main
    result = ecr_client.get_authorization_token()
  File "/usr/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3.8/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the GetAuthorizationToken operation: User: arn:aws:iam::222222222:user/sw_dev_cicd_user is not authorized to perform: ecr:GetAuthorizationToken on resource: *
2020-06-05 03:18:24,672 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

> An error occurred (AccessDeniedException) when calling the GetAuthorizationToken operation: User: arn:aws:iam::2222222222:user/sw_dev_cicd_user is not authorized to perform: ecr:GetAuthorizationToken on resource: *

**Additional context**

**Comment by kdaily** [comment]
Hi @Kenblair1226, 

There is a defined credentials and configuration precedence described here:

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-precedence

In your case, the presence of the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` would take precedence over a profile with a role ARN set in the configuration file.

If you set as part of the command the parameter for the profile you want to use (`aws --profile default ecr get-login`), this would take precedence over the environment variables. Let me know if this works for you!

**Comment by Kenblair1226** [comment]
Hi @kdaily 

Thanks for the explanation and I confirm the behavior. It's just I thought the default profile will always be the fallback setting since there is no env variable for role_arn. Took me some time to figure out what's going on. I will go ahead closing this. Thanks!
