### ISSUE TITLE
[V2]Unable to run aws configure sso get error 'str' object has no attribute 'get

### ISSUE THREAD

**Issue by pcanham** [aws/aws-cli#5334]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
I am trying to enable AWS SSO within my cli client and having issues that the process fails with error
```
'str' object has no attribute 'get
```

**Platform/OS/Hardware/Device**
What are you running the cli on?
```
macOS 10.15.5
aws-cli/2.0.27 Python/3.7.4 Darwin/19.5.0 botocore/2.0.0dev31
```

**To Reproduce (observed behavior)**
```
aws configure sso
```

**Expected behavior**
Be able to configure CLI to use AWS SSO

**Logs/output**
```
$ aws configure sso --debug
2020-07-02 14:29:40,023 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.0.27 Python/3.7.4 Darwin/19.5.0 botocore/2.0.0dev31
2020-07-02 14:29:40,023 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['configure', 'sso', '--debug']
2020-07-02 14:29:40,024 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7f9ffec15710>
2020-07-02 14:29:40,024 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7f9ffe3feb00>
2020-07-02 14:29:40,024 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7f9ffec65320>
2020-07-02 14:29:40,024 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f9ffe435a70>
2020-07-02 14:29:40,033 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f9ffeac8830>
2020-07-02 14:29:40,033 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7f9ffea6cdd0>
2020-07-02 14:29:40,033 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure: calling handler <function _add_wizard_command at 0x7f9ffec5bc20>
2020-07-02 14:29:40,033 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure: calling handler <function add_waiters at 0x7f9ffec253b0>
2020-07-02 14:29:40,034 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.configure.anonymous: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9ffe947f10>
2020-07-02 14:29:40,034 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sso: calling handler <function add_sso_commands at 0x7f9ffea62b00>
2020-07-02 14:29:40,034 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sso: calling handler <function add_waiters at 0x7f9ffec253b0>
2020-07-02 14:29:40,034 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sso.anonymous: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9ffe947f10>
SSO start URL [None]: https://thinkside.awsapps.com/start
2020-07-02 14:29:46,365 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/botocore/data/endpoints.json
2020-07-02 14:29:46,385 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/botocore/data/sso-oidc/2019-06-10/service-2.json
SSO Region [None]: eu-west-1
2020-07-02 14:29:49,532 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f9ffdf0c170>
2020-07-02 14:29:49,532 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.sso-oidc: calling handler <function add_generate_presigned_url at 0x7f9ffdebc170>
2020-07-02 14:29:49,534 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/clidriver.py", line 335, in main
  File "awscli/customizations/commands.py", line 197, in __call__
  File "awscli/customizations/commands.py", line 190, in __call__
  File "awscli/customizations/configure/sso.py", line 302, in _run_main
  File "awscli/customizations/sso/utils.py", line 47, in do_sso_login
  File "botocore/utils.py", line 1852, in fetch_token
  File "botocore/utils.py", line 1847, in _token
  File "botocore/utils.py", line 1801, in _poll_for_token
  File "botocore/utils.py", line 1775, in _registration
  File "botocore/utils.py", line 1750, in _register_client
  File "botocore/utils.py", line 719, in __get__
  File "botocore/utils.py", line 1746, in _client
  File "botocore/session.py", line 811, in create_client
  File "botocore/client.py", line 81, in create_client
  File "botocore/client.py", line 179, in _get_client_args
  File "botocore/args.py", line 72, in get_client_args
  File "botocore/config.py", line 162, in __init__
  File "botocore/config.py", line 201, in _validate_s3_configuration
AttributeError: 'str' object has no attribute 'get'
2020-07-02 14:29:49,535 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

'str' object has no attribute 'get'
```

**Additional context**

**Comment by kdaily** [comment]
Hi @pcanham,

This error is coming when trying to read in the S3 configuration present in your `config` file, as described here:

https://awscli.amazonaws.com/v2/documentation/api/latest/topic/s3-config.html

Can you check to make sure that it's formatted properly? Thanks!
