### ISSUE TITLE
SignatureDoesNotMatch error report

### ISSUE THREAD

**Issue by marcidy** [aws/aws-cli#5341]
If you have encountered an error message like the following, you're in the right place! If not, please file a standard bug report (https://github.com/aws/aws-cli/issues/new/choose).

> `A client error (SignatureDoesNotMatch) occurred when calling the <ApiCall> operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.`

where `<ApiCall>` changes depending on what command you ran.

## Do this first!

If you have encountered this error, please do the following FIRST (change the [] boxes to [x]):

- [x] Read the user guide troubleshooting chapter (https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-troubleshooting.html) to check for known issues like clock skew.
No skew
- [x] Confirm that the error occurs even if you use one of the supported installation methods (https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html).
Installed on an aws ubuntu instance

If possible, try using the credentials with another non-Python SDK, like Javascript (http://aws.amazon.com/javascript).

## Required information

If you have done these things, please fill out the following sections:

### Command line version

*You can get this by running `aws --version`.*

`aws-cli/1.17.14 Python/3.8.2 Linux/5.4.0-1015-aws botocore/1.14.14`

### Operating system

*Please include the OS version (e.g., Fedora 32 or Windows 10).*

`Linux xxxxxxxx #15-Ubuntu SMP Thu Jun 4 22:47:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

### Installation method

*Describe how you installed the client, e.g. pip, Windows installer, etc. Also, if different, describe which of the supported installation methods (https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html) you used to test.*

```
$ sudo apt-get install awscli
```

### Command being run and output

*Important!!! Be sure to redact sensitive information like account numbers, ARNs, etc.*

```
$ aws iam list-users

An error occurred (SignatureDoesNotMatch) when calling the ListUsers operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
Please provide the full command the output with debug mode on (`aws --debug ...`)
```

```
$ aws --debug iam list-users
2020-07-03 21:12:23,331 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.17.14 Python/3.8.2 Linux/5.4.0-1015-aws botocore/1.14.14
2020-07-03 21:12:23,332 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', 'iam', 'list-users']
2020-07-03 21:12:23,332 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7f72b72b0430>
2020-07-03 21:12:23,332 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7f72b77b5ee0>
2020-07-03 21:12:23,333 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f72b778ac10>
2020-07-03 21:12:23,335 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f72b73f0940>
2020-07-03 21:12:23,336 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3/dist-packages/botocore/data/iam/2010-05-08/service-2.json
2020-07-03 21:12:23,357 - MainThread - botocore.hooks - DEBUG - Event building-command-table.iam: calling handler <function add_waiters at 0x7f72b72b6d30>
2020-07-03 21:12:23,362 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3/dist-packages/botocore/data/iam/2010-05-08/waiters-2.json
2020-07-03 21:12:23,363 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('path-prefix', <awscli.arguments.CLIArgument object at 0x7f72b6f40a00>), ('marker', <awscli.arguments.CLIArgument object at 0x7f72b6f40a30>), ('max-items', <awscli.arguments.CLIArgument object at 0x7f72b6f40a60>)])
2020-07-03 21:12:23,363 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.iam.list-users: calling handler <function add_streaming_output_arg at 0x7f72b72b0a60>
2020-07-03 21:12:23,363 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.iam.list-users: calling handler <function add_cli_input_json at 0x7f72b7714670>
2020-07-03 21:12:23,364 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.iam.list-users: calling handler <function unify_paging_params at 0x7f72b73349d0>
2020-07-03 21:12:23,368 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3/dist-packages/botocore/data/iam/2010-05-08/paginators-1.json
2020-07-03 21:12:23,369 - MainThread - awscli.customizations.paginate - DEBUG - Modifying paging parameters for operation: ListUsers
2020-07-03 21:12:23,369 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.iam.list-users: calling handler <function add_generate_skeleton at 0x7f72b7392c10>
2020-07-03 21:12:23,369 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.iam.list-users: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7f72b6f40b80>>
2020-07-03 21:12:23,370 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.iam.list-users: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f72b6f40ee0>>
2020-07-03 21:12:23,371 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.iam.list-users: calling handler functools.partial(<function check_should_enable_pagination at 0x7f72b7334af0>, ['marker', 'max-items'], {'max-items': <awscli.arguments.CLIArgument object at 0x7f72b6f40a60>}, OrderedDict([('path-prefix', <awscli.arguments.CLIArgument object at 0x7f72b6f40a00>), ('marker', <awscli.arguments.CLIArgument object at 0x7f72b6f40a30>), ('max-items', <awscli.customizations.paginate.PageArgument object at 0x7f72b6f40c10>), ('cli-input-json', <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7f72b6f40b80>), ('starting-token', <awscli.customizations.paginate.PageArgument object at 0x7f72b6f40d90>), ('page-size', <awscli.customizations.paginate.PageArgument object at 0x7f72b6f40d30>), ('generate-cli-skeleton', <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f72b6f40ee0>)]))
2020-07-03 21:12:23,371 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.iam.list-users.path-prefix: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f72b71ff4c0>
2020-07-03 21:12:23,371 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.iam.list-users.marker: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f72b71ff4c0>
2020-07-03 21:12:23,371 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.iam.list-users.max-items: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f72b71ff4c0>
2020-07-03 21:12:23,371 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.iam.list-users.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f72b71ff4c0>
2020-07-03 21:12:23,372 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.iam.list-users.starting-token: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f72b71ff4c0>
2020-07-03 21:12:23,372 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.iam.list-users.page-size: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f72b71ff4c0>
2020-07-03 21:12:23,372 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.iam.list-users.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f72b71ff4c0>
2020-07-03 21:12:23,372 - MainThread - botocore.hooks - DEBUG - Event calling-command.iam.list-users: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7f72b6f40b80>>
2020-07-03 21:12:23,372 - MainThread - botocore.hooks - DEBUG - Event calling-command.iam.list-users: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f72b6f40ee0>>
2020-07-03 21:12:23,372 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2020-07-03 21:12:23,373 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2020-07-03 21:12:23,373 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2020-07-03 21:12:23,373 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2020-07-03 21:12:23,373 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2020-07-03 21:12:23,373 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3/dist-packages/botocore/data/endpoints.json
2020-07-03 21:12:23,377 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f72b7c6e5e0>
2020-07-03 21:12:23,382 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.iam: calling handler <function add_generate_presigned_url at 0x7f72b7c5b430>
2020-07-03 21:12:23,382 - MainThread - botocore.regions - DEBUG - Using partition endpoint for iam, us-east-2: aws-global
2020-07-03 21:12:23,385 - MainThread - botocore.endpoint - DEBUG - Setting iam timeout as (60, 60)
2020-07-03 21:12:23,385 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3/dist-packages/botocore/data/_retry.json
2020-07-03 21:12:23,386 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: iam
2020-07-03 21:12:23,387 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.iam.ListUsers: calling handler <function generate_idempotent_uuid at 0x7f72b7c1e5e0>
2020-07-03 21:12:23,387 - MainThread - botocore.hooks - DEBUG - Event before-call.iam.ListUsers: calling handler <function inject_api_version_header_if_needed at 0x7f72b7c220d0>
2020-07-03 21:12:23,387 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=ListUsers) with params: {'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': 'aws-cli/1.17.14 Python/3.8.2 Linux/5.4.0-1015-aws botocore/1.14.14'}, 'body': {'Action': 'ListUsers', 'Version': '2010-05-08'}, 'url': 'https://iam.amazonaws.com/', 'context': {'client_region': 'aws-global', 'client_config': <botocore.config.Config object at 0x7f72b6e7d610>, 'has_streaming_input': False, 'auth_type': None}}
2020-07-03 21:12:23,388 - MainThread - botocore.hooks - DEBUG - Event request-created.iam.ListUsers: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f72b6e7d430>>
2020-07-03 21:12:23,388 - MainThread - botocore.hooks - DEBUG - Event choose-signer.iam.ListUsers: calling handler <function set_operation_specific_signer at 0x7f72b7c1e4c0>
2020-07-03 21:12:23,388 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2020-07-03 21:12:23,388 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-www-form-urlencoded; charset=utf-8
host:iam.amazonaws.com
x-amz-date:20200703T211223Z

content-type;host;x-amz-date
b6359072c78d70ebee1e81adcbab4f01bf2c23245fa365ef83fe8f1f955085e2
2020-07-03 21:12:23,389 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20200703T211223Z
20200703/us-east-1/iam/aws4_request
efd071096220828938b720d7877f5888d349a9f8dd6abcf41ab86dbf0a08750c
2020-07-03 21:12:23,389 - MainThread - botocore.auth - DEBUG - Signature:
2d47d39b409ffbd887c5d666046e5d6f389e525f9da5cdbca34b312e6fa2b7f0
2020-07-03 21:12:23,389 - MainThread - botocore.auth - DEBUG - Signature:
2d47d39b409ffbd887c5d666046e5d6f389e525f9da5cdbca34b312e6fa2b7f0
2020-07-03 21:12:23,389 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://iam.amazonaws.com/, headers={'Content-Type': b'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': b'aws-cli/1.17.14 Python/3.8.2 Linux/5.4.0-1015-aws botocore/1.14.14', 'X-Amz-Date': b'20200703T211223Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=XXXX__REMOVED___XXXX, SignedHeaders=content-type;host;x-amz-date, Signature=XXXX__REMOVED__XXXX, 'Content-Length': '35'}>
2020-07-03 21:12:23,390 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): iam.amazonaws.com:443
2020-07-03 21:12:23,461 - MainThread - urllib3.connectionpool - DEBUG - https://iam.amazonaws.com:443 "POST / HTTP/1.1" 403 431
2020-07-03 21:12:23,462 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-RequestId': 'f24947fd-c0c2-4fbc-9a00-ded97211a8f2', 'Content-Type': 'text/xml', 'Content-Length': '431', 'Date': 'Fri, 03 Jul 2020 21:12:23 GMT'}
2020-07-03 21:12:23,462 - MainThread - botocore.parsers - DEBUG - Response body:
b'<ErrorResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>SignatureDoesNotMatch</Code>\n    <Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.</Message>\n  </Error>\n  <RequestId>f24947fd-c0c2-4fbc-9a00-ded97211a8f2</RequestId>\n</ErrorResponse>\n'
2020-07-03 21:12:23,462 - MainThread - botocore.hooks - DEBUG - Event needs-retry.iam.ListUsers: calling handler <botocore.retryhandler.RetryHandler object at 0x7f72b6e7df40>
2020-07-03 21:12:23,463 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2020-07-03 21:12:23,463 - MainThread - botocore.hooks - DEBUG - Event after-call.iam.ListUsers: calling handler <function json_decode_policies at 0x7f72b7c213a0>
2020-07-03 21:12:23,465 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 217, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 358, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 527, in __call__
    return self._operation_caller.invoke(
  File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 651, in invoke
    self._display_response(operation_name, response, parsed_globals)
  File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 671, in _display_response
    formatter(command_name, response)
  File "/usr/lib/python3/dist-packages/awscli/formatter.py", line 69, in __call__
    response_data = response.build_full_result()
  File "/usr/lib/python3/dist-packages/botocore/paginate.py", line 449, in build_full_result
    for response in self:
  File "/usr/lib/python3/dist-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/lib/python3/dist-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 276, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 586, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the ListUsers operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
2020-07-03 21:12:23,466 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

An error occurred (SignatureDoesNotMatch) when calling the ListUsers operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```

### Other environment details

*This might include a container image (like Docker), CI/CD suite (like Travis), or a cloud instance (an EC2).*
EC2 Ubuntu instance.

The instance was created yesterday (7/2/2020) and the issue has persisted to today (7/3/2020).  The information was gathered today (7/3/2020).  This everything is on AWS and occurring on AWS with the stock ubuntu image, everything installed with the stock apt sources.

While the info above was collected with the `$ aws iam list` i get the same with other commands such as `$ aws sqs list-queue` which is what I'm actually after.  Boto3 also fails with these credentials attempting to list sqs queues, where the command was fine with other credentials.

### Does the secret key you are using have special characters, like ‘+’ or ‘/’, in it?
Yes

*If possible, do not delete the credentials that are failing so that we can follow up with further debugging commands.*

I can sit on this for a few days.  I realize this is now a holiday so perhaps nothing can be done till Monday.  If there's senstive info above, whoops, doesn't really matter, I'll delete the instance and start fresh once this issue is resolved.

**Comment by kdaily** [comment]
Hi @marcidy,

Thanks for being the first report of this using our new template! 🎉 🎉 🎉 🎉  And thanks for the detailed report. If you have the instance still up, could you try and reproduce after installing the AWS CLI from one of the following methods, instead of the system package manager?

- Using the bundled installer or `pip`: https://docs.aws.amazon.com/cli/latest/userguide/install-linux.html
- In a Python virtual environment: https://docs.aws.amazon.com/cli/latest/userguide/install-virtualenv.html

Thank you!

**Comment by marcidy** [comment]
Sure!

The instance was restarted but is still running and available.  

I removed (but didn't purge) the version from the system package manager.  
```
$ sudo apt-get remove aws-cli
```

I can give you more details on the instance or access to the instance if that helps, I'm also happy to continue following instructions as we narrow this down.

If sensitive details help, feel free to reach out via [my github user name] at gmail.com

details on each method below with debug output attached.


## Method 1 (Bundled installer):
```
$ which aws
/usr/local/bin/aws

$ /usr/local/bin/aws --version
aws-cli/1.18.94 Python/3.8.2 Linux/5.4.0-1018-aws botocore/1.17.17
```

```$ aws sqs list-queues

An error occurred (SignatureDoesNotMatch) when calling the ListQueues operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/

content-type:application/x-www-form-urlencoded; charset=utf-8
host:us-east-2.queue.amazonaws.com
x-amz-date:20200706T223211Z

content-type;host;x-amz-date
48a38266faf90970d6c7fea9b15e6ba366e5f6397c2970fc893f8a7b5e207bd0'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20200706T223211Z
20200706/us-east-2/sqs/aws4_request
05d1b631423215d0e3344b6c0f22a54462b650c0e3f29d8b88b7a0df531b49b6'
```
### debug log for method 1
[method-1-debug.log](https://github.com/aws/aws-cli/files/4881534/method-1-debug.log)


## Method 2 (Virtual env)
```
$ . venv/bin/activate
(venv) $ which aws
/home/ubuntu/aws-cli-teset/venv/bin/aws
(venv) $ aws sqs list-queues

An error occurred (SignatureDoesNotMatch) when calling the ListQueues operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/

content-type:application/x-www-form-urlencoded; charset=utf-8
host:us-east-2.queue.amazonaws.com
x-amz-date:20200706T223657Z

content-type;host;x-amz-date
48a38266faf90970d6c7fea9b15e6ba366e5f6397c2970fc893f8a7b5e207bd0'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20200706T223657Z
20200706/us-east-2/sqs/aws4_request
bbc31ac59144b5619a151ad25db08edc152dbb0f45dbd061f2e4ba2b09f91a98

```
### debug log for method 2
[method-2-debug.log](https://github.com/aws/aws-cli/files/4881533/method-2-debug.log)

**Comment by kdaily** [comment]
Thanks @marcidy - would you be able to test this using another language AWS SDK (besides Python) with these same credentials?

**Comment by marcidy** [comment]
@kdaily 

I used `$ npm install aws-sdk` to install the sdk, and received a similar result.  Apologies for lack of additional info, i don't use node/javascript so not clear what would be useful.


```
$ node listqueue.js 
{ SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/

host:sqs.us-east-2.amazonaws.com
x-amz-content-sha256:48a38266faf90970d6c7fea9b15e6ba366e5f6397c2970fc893f8a7b5e207bd0
x-amz-date:20200708T203231Z

host;x-amz-content-sha256;x-amz-date
48a38266faf90970d6c7fea9b15e6ba366e5f6397c2970fc893f8a7b5e207bd0'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20200708T203231Z
20200708/us-east-2/sqs/aws4_request
5df91ef18175156826cddb0f3c6519dcb884ff9649eecdf6a76705ad3ddd244e'

    at Request.extractError (/home/ubuntu/aws-javascript-sdk/aws-nodejs-sample/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/ubuntu/aws-javascript-sdk/aws-nodejs-sample/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ubuntu/aws-javascript-sdk/aws-nodejs-sample/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ubuntu/aws-javascript-sdk/aws-nodejs-sample/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/ubuntu/aws-javascript-sdk/aws-nodejs-sample/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ubuntu/aws-javascript-sdk/aws-nodejs-sample/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ubuntu/aws-javascript-sdk/aws-nodejs-sample/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ubuntu/aws-javascript-sdk/aws-nodejs-sample/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ubuntu/aws-javascript-sdk/aws-nodejs-sample/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/ubuntu/aws-javascript-sdk/aws-nodejs-sample/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message:
   'The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n\'POST\n/\n\nhost:sqs.us-east-2.amazonaws.com\nx-amz-content-sha256:48a38266faf90970d6c7fea9b15e6ba366e5f6397c2970fc893f8a7b5e207bd0\nx-amz-date:20200708T203231Z\n\nhost;x-amz-content-sha256;x-amz-date\n48a38266faf90970d6c7fea9b15e6ba366e5f6397c2970fc893f8a7b5e207bd0\'\n\nThe String-to-Sign should have been\n\'AWS4-HMAC-SHA256\n20200708T203231Z\n20200708/us-east-2/sqs/aws4_request\n5df91ef18175156826cddb0f3c6519dcb884ff9649eecdf6a76705ad3ddd244e\'\n',
  code: 'SignatureDoesNotMatch',
  time: 2020-07-08T20:32:31.552Z,
  requestId: '27fcb2ee-ae93-56ac-93a6-e56e810c2b2a',
  statusCode: 403,
  retryable: false,
  retryDelay: 59.685133476838345 } 'SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n\'POST\n/\n\nhost:sqs.us-east-2.amazonaws.com\nx-amz-content-sha256:48a38266faf90970d6c7fea9b15e6ba366e5f6397c2970fc893f8a7b5e207bd0\nx-amz-date:20200708T203231Z\n\nhost;x-amz-content-sha256;x-amz-date\n48a38266faf90970d6c7fea9b15e6ba366e5f6397c2970fc893f8a7b5e207bd0\'\n\nThe String-to-Sign should have been\n\'AWS4-HMAC-SHA256\n20200708T203231Z\n20200708/us-east-2/sqs/aws4_request\n5df91ef18175156826cddb0f3c6519dcb884ff9649eecdf6a76705ad3ddd244e\'\n\n    at Request.extractError (/home/ubuntu/aws-javascript-sdk/aws-nodejs-sample/node_modules/aws-sdk/lib/protocol/query.js:50:29)\n    at Request.callListeners (/home/ubuntu/aws-javascript-sdk/aws-nodejs-sample/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/home/ubuntu/aws-javascript-sdk/aws-nodejs-sample/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/home/ubuntu/aws-javascript-sdk/aws-nodejs-sample/node_modules/aws-sdk/lib/request.js:688:14)\n    at Request.transition (/home/ubuntu/aws-javascript-sdk/aws-nodejs-sample/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/home/ubuntu/aws-javascript-sdk/aws-nodejs-sample/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /home/ubuntu/aws-javascript-sdk/aws-nodejs-sample/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/home/ubuntu/aws-javascript-sdk/aws-nodejs-sample/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/home/ubuntu/aws-javascript-sdk/aws-nodejs-sample/node_modules/aws-sdk/lib/request.js:690:12)\n    at Request.callListeners (/home/ubuntu/aws-javascript-sdk/aws-nodejs-sample/node_modules/aws-sdk/lib/sequential_executor.js:116:18)'
```

**Comment by kdaily** [comment]
Making some notes and pulling out some things of interest. Here's the request sent:

```
2020-07-06 22:42:01,344 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-www-form-urlencoded; charset=utf-8
host:us-east-2.queue.amazonaws.com
x-amz-date:20200706T224201Z

content-type;host;x-amz-date
48a38266faf90970d6c7fea9b15e6ba366e5f6397c2970fc893f8a7b5e207bd0
2020-07-06 22:42:01,344 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20200706T224201Z
20200706/us-east-2/sqs/aws4_request
b8d1999436aba270c7634b269383d1426b76dba6162eece1573039056e7fcfc4

2020-07-06 22:42:01,344 - MainThread - botocore.auth - DEBUG - Signature:
efb5c5e1b5488a67cae125c9a9a76d35dab47063800da993b4e0e5497fe303d6
```

Here's what the error says the request should have been:

```
botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the ListQueues operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/

content-type:application/x-www-form-urlencoded; charset=utf-8
host:us-east-2.queue.amazonaws.com
x-amz-date:20200706T224201Z

content-type;host;x-amz-date
48a38266faf90970d6c7fea9b15e6ba366e5f6397c2970fc893f8a7b5e207bd0'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20200706T224201Z
20200706/us-east-2/sqs/aws4_request
b8d1999436aba270c7634b269383d1426b76dba6162eece1573039056e7fcfc4'
```

**Comment by marcidy** [comment]
Hi,

What are the next steps here?  Do you want this test case to persist, and if so, can you prioritize what you need to do with it?  

Thanks

**Comment by kdaily** [comment]
Hi @marcidy,

At this time you can go ahead and terminate any resources you have. I'm unfortunately not able to get any of the credential information or connect to any of your instances, but the information and detail you have provided has helped us nonetheless, as you have confirmed that the error persists across SDKs.

If this does re-occur, I would appreciate your time for opening another issue to help document re-occurrence.

Thanks again!
