### ISSUE TITLE
Issue trying to get login token for AWS ECR with aws-cli version 1.18.101

### ISSUE THREAD

**Issue by arlind87** [aws/aws-cli#5394]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
We observed that in the latest version of aws-cli python package (1.18.101), execution of command ```aws ecr get-login --region us-east-1 --no-include-email``` fails with error ```An error occurred (UnrecognizedClientException) when calling the GetAuthorizationToken operation: The security token included in the request is invalid.```. With version 1.18.100 the same command works well.

**SDK version number**
1.18.101

**Platform/OS/Hardware/Device**
Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-169-generic x86_64)

**To Reproduce (observed behavior)**
Every time you 2eecute the command with aws-cli version 1.18.101

**Expected behavior**
The command should provide the login token for ECR docker registry.

**Logs/output**
```(awscli) root@eu-jupyter2:~# aws ecr get-login --region us-east-1 --no-include-email --debug
2020-07-21 08:25:43,872 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.18.101 Python/3.5.2 Linux/4.4.0-169-generic botocore/1.17.24
2020-07-21 08:25:43,872 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['ecr', 'get-login', '--region', 'us-east-1', '--no-include-email', '--debug']
2020-07-21 08:25:43,872 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7fcc37cb9158>
2020-07-21 08:25:43,872 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7fcc387dbe18>
2020-07-21 08:25:43,873 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7fcc38726730>
2020-07-21 08:25:43,874 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7fcc3a8a6158>
2020-07-21 08:25:43,874 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /root/awscli/lib/python3.5/site-packages/botocore/data/ecr/2015-09-21/service-2.json
2020-07-21 08:25:43,877 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ecr: calling handler <function _inject_commands at 0x7fcc3a8b36a8>
2020-07-21 08:25:43,877 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ecr: calling handler <function add_waiters at 0x7fcc37c47730>
2020-07-21 08:25:43,881 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /root/awscli/lib/python3.5/site-packages/botocore/data/ecr/2015-09-21/waiters-2.json
2020-07-21 08:25:43,882 - MainThread - botocore.hooks - DEBUG - Event building-command-table.get-login: calling handler <function add_waiters at 0x7fcc37c47730>
2020-07-21 08:25:43,882 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.get-login.include-email: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc3b9a1be0>
2020-07-21 08:25:43,883 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.get-login: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fcc38773390>
2020-07-21 08:25:43,883 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.get-login.registry-ids: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc3b9a1be0>
2020-07-21 08:25:43,883 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2020-07-21 08:25:43,883 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2020-07-21 08:25:43,883 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2020-07-21 08:25:43,883 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2020-07-21 08:25:43,883 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2020-07-21 08:25:43,884 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2020-07-21 08:25:43,884 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /root/awscli/lib/python3.5/site-packages/botocore/data/endpoints.json
2020-07-21 08:25:43,904 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7fcc39573b70>
2020-07-21 08:25:43,905 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.ecr: calling handler <function add_generate_presigned_url at 0x7fcc3954e048>
2020-07-21 08:25:43,908 - MainThread - botocore.endpoint - DEBUG - Setting api.ecr timeout as (60, 60)
2020-07-21 08:25:43,909 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /root/awscli/lib/python3.5/site-packages/botocore/data/_retry.json
2020-07-21 08:25:43,909 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: ecr
2020-07-21 08:25:43,910 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.ecr.GetAuthorizationToken: calling handler <function generate_idempotent_uuid at 0x7fcc39534158>
2020-07-21 08:25:43,910 - MainThread - botocore.hooks - DEBUG - Event before-call.ecr.GetAuthorizationToken: calling handler <function inject_api_version_header_if_needed at 0x7fcc395358c8>
2020-07-21 08:25:43,911 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=GetAuthorizationToken) with params: {'url_path': '/', 'body': b'{}', 'context': {'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x7fcc37a44d68>, 'auth_type': None, 'has_streaming_input': False}, 'headers': {'User-Agent': 'aws-cli/1.18.101 Python/3.5.2 Linux/4.4.0-169-generic botocore/1.17.24', 'X-Amz-Target': 'AmazonEC2ContainerRegistry_V20150921.GetAuthorizationToken', 'Content-Type': 'application/x-amz-json-1.1'}, 'query_string': '', 'method': 'POST', 'url': 'https://api.ecr.us-east-1.amazonaws.com/'}
2020-07-21 08:25:43,911 - MainThread - botocore.hooks - DEBUG - Event request-created.ecr.GetAuthorizationToken: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fcc37a44d30>>
2020-07-21 08:25:43,911 - MainThread - botocore.hooks - DEBUG - Event choose-signer.ecr.GetAuthorizationToken: calling handler <function set_operation_specific_signer at 0x7fcc39534048>
2020-07-21 08:25:43,911 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2020-07-21 08:25:43,912 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/
content-type:application/x-amz-json-1.1
host:api.ecr.us-east-1.amazonaws.com
x-amz-date:20200721T082543Z
x-amz-target:AmazonEC2ContainerRegistry_V20150921.GetAuthorizationToken
content-type;host;x-amz-date;x-amz-target
44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
2020-07-21 08:25:43,912 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20200721T082543Z
20200721/us-east-1/ecr/aws4_request
af3b4e33ee16adf846871b6825b448a15c0396ff1d2a381e3840329c1e7399a2
2020-07-21 08:25:43,912 - MainThread - botocore.auth - DEBUG - Signature:
260d882d236bb6f5b8a7107a79e6a74f473804bfff9afce697bf29d422342ca0
2020-07-21 08:25:43,912 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://api.ecr.us-east-1.amazonaws.com/, headers={'Content-Type': b'application/x-amz-json-1.1', 'X-Amz-Target': b'AmazonEC2ContainerRegistry_V20150921.GetAuthorizationToken', 'Content-Length': '2', 'User-Agent': b'aws-cli/1.18.101 Python/3.5.2 Linux/4.4.0-169-generic botocore/1.17.24', 'X-Amz-Date': b'20200721T082543Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=<redacted>/20200721/us-east-1/ecr/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=260d882d236bb6f5b8a7107a79e6a74f473804bfff9afce697bf29d422342ca0'}>
2020-07-21 08:25:43,913 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.ecr.us-east-1.amazonaws.com:443
2020-07-21 08:25:44,223 - MainThread - urllib3.connectionpool - DEBUG - https://api.ecr.us-east-1.amazonaws.com:443 "POST / HTTP/1.1" 400 107
2020-07-21 08:25:44,224 - MainThread - botocore.parsers - DEBUG - Response headers: {'Content-Type': 'application/x-amz-json-1.1', 'x-amzn-RequestId': '98c8a4c7-a9f8-484e-b23b-25e83e03269a', 'Date': 'Tue, 21 Jul 2020 08:25:44 GMT', 'Content-Length': '107'}
2020-07-21 08:25:44,224 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"__type":"UnrecognizedClientException","message":"The security token included in the request is invalid."}'
2020-07-21 08:25:44,225 - MainThread - botocore.hooks - DEBUG - Event needs-retry.ecr.GetAuthorizationToken: calling handler <botocore.retryhandler.RetryHandler object at 0x7fcc37a4c780>
2020-07-21 08:25:44,226 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2020-07-21 08:25:44,226 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/root/awscli/lib/python3.5/site-packages/awscli/clidriver.py", line 217, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/root/awscli/lib/python3.5/site-packages/awscli/clidriver.py", line 358, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/root/awscli/lib/python3.5/site-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/root/awscli/lib/python3.5/site-packages/awscli/customizations/ecr.py", line 73, in _run_main
    result = ecr_client.get_authorization_token()
  File "/root/awscli/lib/python3.5/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/awscli/lib/python3.5/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the GetAuthorizationToken operation: The security token included in the request is invalid.
2020-07-21 08:25:44,228 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255
An error occurred (UnrecognizedClientException) when calling the GetAuthorizationToken operation: The security token included in the request is invalid.```

**Additional context**
The error is not indicative of the real issue since the same token works fine with aws-cli version 1.18.100 and has the right permissions to access ECR.

**Comment by arlind87** [comment]
As a workaround to this issue I have pinned my aws-cli installs to 1.18.100

**Comment by kdaily** [comment]
Hi @arlind87, sorry to hear of the issue. I just tested on `1.18.101` and it was successful:

```
$ aws --version
aws-cli/1.18.101 Python/3.8.3 Darwin/19.5.0 botocore/1.17.24
$ aws ecr get-login --region us-east-1 --no-include-email
docker login -u AWS -p ......
```

Are you able to run other `aws` commands successfully with these credentials?

**Comment by arlind87** [comment]
Hi, 
Thank you for your response.
I am able to run it successfully on env with python `3.8.3`. Can you try to run the same command on python virtualenv version `3.5.2`?

**Comment by kdaily** [comment]
All good for me on Python 3.5.2 as well:

```
$ aws --version
aws-cli/1.18.101 Python/3.5.2 Linux/4.4.0-1109-aws botocore/1.17.24

$ aws ecr get-login --region us-east-1 --no-include-email
docker login -u AWS -p ....

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

This error is very commonly associated with bad credentials. From the debug logs, I see you're using a credential file. I would double check that they are correct!

**Comment by arlind87** [comment]
I see. It is very strange indeed. For me, the same exact set of credentials works just fine with aws-cli version `1.18.100`. 
Seems though that no one else is experiencing this issue so you may close this ticket.

**Comment by arlind87** [comment]
Thanks for the assistance!

**Comment by kdaily** [comment]
I would also suggest:

1. Trying a different set of credentials, and
1. Trying other `aws` commands

Check out the [AWS CLI troubleshooting guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-troubleshooting.html) for invalid credential errors. It also suggests to check for clock skew (your local clock time is far off from standard time servers, but doesn't seem likely given the symptoms you're reporting).

If this persists through future AWS CLI releases, feel free to re-open and I'll check it out again!

**Comment by sheenilim08** [comment]
Looks like this is still a thing on 2.13.22.

I did what @flotwig suggested.

**Comment by qu1j0t3** [comment]
Am also having this issue on an EC2 instance with IAM role linked via instance role. 

Steps to reproduce:

```sh
[root@ip-172-31-32-125 ~]#  TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"`     && curl -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/iam/security-credentials/emy-magento-pull-ecr-image


{
  "Code" : "Success",
  "LastUpdated" : "2025-05-11T02:39:35Z",
  "Type" : "AWS-HMAC",
  "AccessKeyId" : "ASIA5Wxx772EE",
  "SecretAccessKey" : "LcnaXLtfFFxxD0dn9k",
  "Token" : "xx",
  "Expiration" : "2025-05-11T09:05:44Z"
}

$ aws configure
AWS Access Key ID [****************72EE]: ASIA5Wxx772EE
AWS Secret Access Key [****************dn9k]: LcnaXLtfFFxxD0dn9k
Default region name [us-east-1]: 
Default output format [json]: 

$ aws ecr get-login-password --region us-east-1

An error occurred (UnrecognizedClientException) when calling the GetAuthorizationToken operation: The security token included in the request is invalid.


$ sudo dnf install awscli
Last metadata expiration check: 1 day, 6:42:49 ago on Fri May  9 20:41:46 2025.
Package awscli-2-2.23.11-1.amzn2023.0.1.noarch is already installed.

```
