### ISSUE TITLE
elbv2: condition QueryStringConfig doesn't work

### ISSUE THREAD

**Issue by theMiddleBlue** [aws/aws-cli#5406]
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
when I try to modify an existing ELB rule, using a `query-string` condition I got the error: `Unknown parameter in Conditions[1]: "QueryStringConfig", must be one of: Field, Values`. By reading the documentation, I've created this json file for conditions:

```json
[
        {
                "Field": "host-header", 
                "Values": [
                        "paperino.xy"
                ]
        }, 
        {
                "Field": "query-string",
                "QueryStringConfig": {
                        "Values": [
                              {
                                 "Key": "foo", 
                                 "Value": "bar"
                              }
                        ]
                 }
        }, 
        {
                "Field": "path-pattern", 
                "Values": [
                        "/bar"
                ]
        }
]
```

**SDK version number**
aws-cli/1.16.102 Python/2.7.16 Linux/4.14.146-119.123.amzn2.x86_64 botocore/1.12.92

**Platform/OS/Hardware/Device**
ec2 instance

**To Reproduce (observed behavior)**
aws elbv2 modify-rule --rule-arn arn:aws:elasticloadbalancing:eu-central-1:.... --conditions file://conditions.json --actions file://actions.json

**Expected behavior**
update an ELB rule with the correct `query-string` condition

**Logs/output**
```
 aws elbv2 modify-rule --rule-arn arn:aws:elasticloadbalancing:eu-central-1:233113059701:listener-rule/app/waf-load-balancer/bdb9a12da7db54d5/957ee5981c32dc99/da4c407b2596c24b --conditions file://conditions.json --actions file://actions.json --debug
2020-07-24 10:54:17,290 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.16.102 Python/2.7.16 Linux/4.14.146-119.123.amzn2.x86_64 botocore/1.12.92
2020-07-24 10:54:17,293 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['elbv2', 'modify-rule', '--rule-arn', 'arn:aws:elasticloadbalancing:eu-central-1:233113059701:listener-rule/app/waf-load-balancer/bdb9a12da7db54d5/957ee5981c32dc99/da4c407b2596c24b', '--conditions', 'file://conditions.json', '--actions', 'file://actions.json', '--debug']
2020-07-24 10:54:17,293 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7f0e1a4c65f0>
2020-07-24 10:54:17,293 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7f0e1b12ec08>
2020-07-24 10:54:17,294 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f0e1b08e1b8>
2020-07-24 10:54:17,296 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f0e1a85fc80>
2020-07-24 10:54:17,297 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python2.7/site-packages/botocore/data/elbv2/2015-12-01/service-2.json
2020-07-24 10:54:17,316 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.elastic-load-balancing-v2: calling handler <function register_retries_for_service at 0x7f0e1c2aede8>
2020-07-24 10:54:17,318 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: elbv2
2020-07-24 10:54:17,320 - MainThread - botocore.hooks - DEBUG - Changing event name from building-command-table.elbv2 to building-command-table.elastic-load-balancing-v2
2020-07-24 10:54:17,320 - MainThread - botocore.hooks - DEBUG - Event building-command-table.elastic-load-balancing-v2: calling handler <function add_waiters at 0x7f0e1a4d9050>
2020-07-24 10:54:17,325 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python2.7/site-packages/botocore/data/elbv2/2015-12-01/waiters-2.json
2020-07-24 10:54:17,327 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'rule-arn', <awscli.arguments.CLIArgument object at 0x7f0e1a1b2550>), (u'conditions', <awscli.arguments.ListArgument object at 0x7f0e1a1b2590>), (u'actions', <awscli.arguments.ListArgument object at 0x7f0e1a1b2390>)])
2020-07-24 10:54:17,327 - MainThread - botocore.hooks - DEBUG - Changing event name from building-argument-table.elbv2.modify-rule to building-argument-table.elastic-load-balancing-v2.modify-rule
2020-07-24 10:54:17,327 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.elastic-load-balancing-v2.modify-rule: calling handler <function add_streaming_output_arg at 0x7f0e1a4cf230>
2020-07-24 10:54:17,327 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.elastic-load-balancing-v2.modify-rule: calling handler <function add_cli_input_json at 0x7f0e1b08ee60>
2020-07-24 10:54:17,328 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.elastic-load-balancing-v2.modify-rule: calling handler <function unify_paging_params at 0x7f0e1f6235f0>
2020-07-24 10:54:17,332 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python2.7/site-packages/botocore/data/elbv2/2015-12-01/paginators-1.json
2020-07-24 10:54:17,333 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.elastic-load-balancing-v2.modify-rule: calling handler <function add_generate_skeleton at 0x7f0e1f604ed8>
2020-07-24 10:54:17,334 - MainThread - botocore.hooks - DEBUG - Changing event name from before-building-argument-table-parser.elbv2.modify-rule to before-building-argument-table-parser.elastic-load-balancing-v2.modify-rule
2020-07-24 10:54:17,334 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.elastic-load-balancing-v2.modify-rule: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7f0e1a1b2650>>
2020-07-24 10:54:17,334 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.elastic-load-balancing-v2.modify-rule: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f0e1a1b27d0>>
2020-07-24 10:54:17,335 - MainThread - botocore.hooks - DEBUG - Changing event name from operation-args-parsed.elbv2.modify-rule to operation-args-parsed.elastic-load-balancing-v2.modify-rule
2020-07-24 10:54:17,336 - MainThread - botocore.hooks - DEBUG - Changing event name from load-cli-arg.elasticloadbalancing.modify-rule.rule-arn to load-cli-arg.elastic-load-balancing.modify-rule.rule-arn
2020-07-24 10:54:17,336 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.elastic-load-balancing.modify-rule.rule-arn: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f0e1a390f10>
2020-07-24 10:54:17,336 - MainThread - botocore.hooks - DEBUG - Changing event name from process-cli-arg.elbv2.modify-rule to process-cli-arg.elastic-load-balancing-v2.modify-rule
2020-07-24 10:54:17,336 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.elastic-load-balancing-v2.modify-rule: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f0e1b0e4910>
2020-07-24 10:54:17,336 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'arn:aws:elasticloadbalancing:eu-central-1:233113059701:listener-rule/app/waf-load-balancer/bdb9a12da7db54d5/957ee5981c32dc99/da4c407b2596c24b' for parameter "rule_arn": u'arn:aws:elasticloadbalancing:eu-central-1:233113059701:listener-rule/app/waf-load-balancer/bdb9a12da7db54d5/957ee5981c32dc99/da4c407b2596c24b'
2020-07-24 10:54:17,337 - MainThread - botocore.hooks - DEBUG - Changing event name from load-cli-arg.elasticloadbalancing.modify-rule.conditions to load-cli-arg.elastic-load-balancing.modify-rule.conditions
2020-07-24 10:54:17,337 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.elastic-load-balancing.modify-rule.conditions: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f0e1a390f10>
2020-07-24 10:54:17,337 - MainThread - botocore.hooks - DEBUG - Changing event name from process-cli-arg.elbv2.modify-rule to process-cli-arg.elastic-load-balancing-v2.modify-rule
2020-07-24 10:54:17,337 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.elastic-load-balancing-v2.modify-rule: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f0e1b0e4910>
2020-07-24 10:54:17,337 - MainThread - awscli.argprocess - DEBUG - Param conditions looks like JSON, not considered for param shorthand.
2020-07-24 10:54:17,338 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'[\n\t{\n\t\t"Field": "host-header", \n\t\t"Values": [\n\t\t\t"foo.xy"\n\t\t]\n\t}, \n\t{\n\t\t"Field": "query-string",\n\t\t"QueryStringConfig": {\n          "Values": [\n            {\n                "Key": "foo", \n                "Value": "bar"\n            }\n          ]\n      }\n\t}, \n\t{\n\t\t"Field": "path-pattern", \n\t\t"Values": [\n\t\t\t"/bar"\n\t\t]\n\t}\n]\n' for parameter "conditions": [OrderedDict([(u'Field', u'host-header'), (u'Values', [u'foo.xy'])]), OrderedDict([(u'Field', u'query-string'), (u'QueryStringConfig', OrderedDict([(u'Values', [OrderedDict([(u'Key', u'foo'), (u'Value', u'bar')])])]))]), OrderedDict([(u'Field', u'path-pattern'), (u'Values', [u'/bar'])])]
2020-07-24 10:54:17,338 - MainThread - botocore.hooks - DEBUG - Changing event name from load-cli-arg.elasticloadbalancing.modify-rule.actions to load-cli-arg.elastic-load-balancing.modify-rule.actions
2020-07-24 10:54:17,338 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.elastic-load-balancing.modify-rule.actions: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f0e1a390f10>
2020-07-24 10:54:17,338 - MainThread - botocore.hooks - DEBUG - Changing event name from process-cli-arg.elbv2.modify-rule to process-cli-arg.elastic-load-balancing-v2.modify-rule
2020-07-24 10:54:17,339 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.elastic-load-balancing-v2.modify-rule: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f0e1b0e4910>
2020-07-24 10:54:17,339 - MainThread - awscli.argprocess - DEBUG - Param actions looks like JSON, not considered for param shorthand.
2020-07-24 10:54:17,339 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'[\n\t{\n\t\t"TargetGroupArn": "arn:aws:elasticloadbalancing:eu-central-1:233113059701:targetgroup/http-aizoon-xl/6d6bbf6c13931551", \n\t\t"Type": "forward", \n\t\t"Order": 1\n\t}\n]\n' for parameter "actions": [OrderedDict([(u'TargetGroupArn', u'arn:aws:elasticloadbalancing:eu-central-1:233113059701:targetgroup/http-aizoon-xl/6d6bbf6c13931551'), (u'Type', u'forward'), (u'Order', 1)])]
2020-07-24 10:54:17,339 - MainThread - botocore.hooks - DEBUG - Changing event name from load-cli-arg.elasticloadbalancing.modify-rule.cli-input-json to load-cli-arg.elastic-load-balancing.modify-rule.cli-input-json
2020-07-24 10:54:17,339 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.elastic-load-balancing.modify-rule.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f0e1a390f10>
2020-07-24 10:54:17,339 - MainThread - botocore.hooks - DEBUG - Changing event name from load-cli-arg.elasticloadbalancing.modify-rule.generate-cli-skeleton to load-cli-arg.elastic-load-balancing.modify-rule.generate-cli-skeleton
2020-07-24 10:54:17,340 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.elastic-load-balancing.modify-rule.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f0e1a390f10>
2020-07-24 10:54:17,340 - MainThread - botocore.hooks - DEBUG - Changing event name from calling-command.elbv2.modify-rule to calling-command.elastic-load-balancing-v2.modify-rule
2020-07-24 10:54:17,340 - MainThread - botocore.hooks - DEBUG - Event calling-command.elastic-load-balancing-v2.modify-rule: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7f0e1a1b2650>>
2020-07-24 10:54:17,340 - MainThread - botocore.hooks - DEBUG - Event calling-command.elastic-load-balancing-v2.modify-rule: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f0e1a1b27d0>>
2020-07-24 10:54:17,340 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2020-07-24 10:54:17,340 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2020-07-24 10:54:17,341 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2020-07-24 10:54:17,341 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2020-07-24 10:54:17,342 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python2.7/site-packages/botocore/data/endpoints.json
2020-07-24 10:54:17,419 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f0e1c2ae5f0>
2020-07-24 10:54:17,421 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.elastic-load-balancing-v2: calling handler <function add_generate_presigned_url at 0x7f0e1c34cb18>
2020-07-24 10:54:17,422 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2020-07-24 10:54:17,426 - MainThread - botocore.endpoint - DEBUG - Setting elasticloadbalancing timeout as (60, 60)
2020-07-24 10:54:17,428 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: elbv2
2020-07-24 10:54:17,429 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.elastic-load-balancing-v2.ModifyRule: calling handler <function generate_idempotent_uuid at 0x7f0e1c2ae848>
2020-07-24 10:54:17,430 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 207, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 348, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 520, in __call__
    call_parameters, parsed_globals)
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 640, in invoke
    client, operation_name, parameters, parsed_globals)
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 652, in _make_client_call
    **parameters)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 634, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 682, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/lib/python2.7/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Unknown parameter in Conditions[1]: "QueryStringConfig", must be one of: Field, Values
2020-07-24 10:54:17,431 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Parameter validation failed:
Unknown parameter in Conditions[1]: "QueryStringConfig", must be one of: Field, Values
```

**Comment by kdaily** [comment]
Hi @theMiddleBlue ,

I'm looking into it, but it's quite an involved setup to try and reproduce. Could you try to use the `--generate-cli-skeleton` to create a JSON template, and then pass it to `--cli-input-json`, with the `Conditions` you have specified?

**Comment by kdaily** [comment]
Have you also tried to pass an empty list for `Values` in each of your structures? Like this (truncated your example for clarity):

```
...
{
                "Field": "query-string",
                "Values": [],
                "QueryStringConfig": {
                        "Values": [
                              {
                                 "Key": "foo", 
                                 "Value": "bar"
                              }
                        ]
                 }
        }, 
...
```

If you are able to, try to set a rule using the AWS console and then use `aws elbv2 describe-rules (<https://docs.aws.amazon.com/cli/latest/reference/elbv2/describe-rules.html>) to see what the rules look like.

**Comment by theMiddleBlue** [comment]
Hi @kdaily 

thank you for your reply. It was my first try to see how "describe-rules" define the JSON but the `query-string` part is empty:

```json
# aws elbv2 describe-rules --rule-arn arn:aws:elasticloadbalancing:eu-central-1:233113059701:listener-rule/app/waf
-load-balancer/bdb9a12da7db54d5/957ee5981c32dc99/da4c407b2596c24b
{
    "Rules": [
        {
            "Priority": "1", 
            "Conditions": [
                {
                    "Field": "path-pattern", 
                    "Values": [
                        "/pippopluto"
                    ]
                }, 
                {
                    "Field": "host-header", 
                    "Values": [
                        "paperino.xy"
                    ]
                }, 
                {
                    "Field": "query-string"
                }
            ], 
            "RuleArn": "arn:aws:elasticloadbalancing:eu-central-1:233113059701:listener-rule/app/waf-load-balancer/bdb9a12da7db54d5/957ee5981c32dc99/da4c407b2596c24b", 
            "IsDefault": false, 
            "Actions": [
                {
                    "TargetGroupArn": "arn:aws:elasticloadbalancing:eu-central-1:233113059701:targetgroup/http-aizoon-xl/6d6bbf6c13931551", 
                    "Type": "forward", 
                    "Order": 1
                }
            ]
        }
    ]
}
```

Tried with the empty value array too but I get always:
```
Parameter validation failed:
Unknown parameter in Conditions[1]: "QueryStringConfig", must be one of: Field, Values
```

I'm not super skilled with aws-cli, I didn't understand well how to use `--generate-cli-skeleton`, maybe I need to go deep with the documentation.

**Comment by theMiddleBlue** [comment]
Hi, have you got some news about this issue? I still have the same problem

**Comment by tim-finnigan** [comment]
Hi @theMiddleBlue, thanks for your patience. I found this post in the AWS forums where a similar error message was reported: https://forums.aws.amazon.com/thread.jspa?messageID=896895

There they mention that as of **v1.16.141** of the AWS CLI, this appears to have been fixed. It looks like you are using 1.16.102. Could you try updating your version of the CLI and let us know if you still see the issue? (For instructions on updating see here: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html)
