### ISSUE TITLE
Typo in Secrets Manager tag-resource Documentation with "--tags" Description

### ISSUE THREAD

**Issue by bwcwestlund** [aws/aws-cli#5458]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/secretsmanager/tag-resource.html
The documentation for `aws secretsmanager tag-resource` says that the --tags option may use the syntax `--Tags Key="Key1",Value="Value1",Key="Key2",Value="Value2"[,…]`. When used like that however it produces the following error:
`Error parsing parameter '--tags': Second instance of key "Key" encountered for input:
Key=Role,Value=A thing,Key=user:name,Value=12345
                       ^
This is often because there is a preceeding "," instead of a space.`

When a space instead of a comma is inserted between each key value pair the command works as expected:
`--Tags Key="Key1",Value="Value1" Key="Key2",Value="Value2"[,…]`

**SDK version number**
aws-cli/2.0.14 Python/3.7.3 Linux/4.4.0-18362-Microsoft botocore/2.0.0dev18

**Platform/OS/Hardware/Device**
Ubuntu 18.04 LTS via Windows Subsystem for Linux on Windows 10

**To Reproduce (observed behavior)**
`aws secretsmanager tag-resource --secret-id "myExampleSecret" --tags Key="Favorite Food",Value
="Cookie",Key="Favorite Color",Value="Gold"`

**Expected behavior**
Replacing the comma with a space between key value pairs correctly executes the tag-resource command and the documentation should reflect that.
`aws secretsmanager tag-resource --secret-id "myExampleSecret" --tags Key="Favorite Food",Value
="Cookie" Key="Favorite Color",Value="Gold"`

**Logs/output**
aws secretsmanager tag-resource --debug --secret-id "myExampleSecret" --tags Key="Favorite Foo
d",Value="Cookie",Key="Favorite Color",Value="Gold"
2020-08-07 10:08:09,110 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.0.14 Python/3.7.3 Linux/4.4.0-18362-Microsoft botocore/2.0.0dev18
2020-08-07 10:08:09,112 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['secretsmanager', 'tag-resource', '--debug', '--secret-id', 'myExampleSecret', '--tags', 'Key=Favorite Food,Value=Cookie,Key=Favorite Color,Value=Gold']
2020-08-07 10:08:09,114 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7f92bf15e488>
2020-08-07 10:08:09,115 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7f92bfa51158>
2020-08-07 10:08:09,116 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7f92bf11c950>
2020-08-07 10:08:09,117 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f92bfa7f730>
2020-08-07 10:08:09,121 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f92bf2a4f28>
2020-08-07 10:08:09,122 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7f92bf2de8c8>
2020-08-07 10:08:09,208 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.0.14/dist/botocore/data/secretsmanager/2017-10-17/service-2.json
2020-08-07 10:08:09,211 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.0.14/dist/botocore/data/secretsmanager/2017-10-17/service-2.sdk-extras.json
2020-08-07 10:08:09,214 - MainThread - botocore.hooks - DEBUG - Event building-command-table.secretsmanager: calling handler <function add_waiters at 0x7f92bf1648c8>
2020-08-07 10:08:09,287 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('secret-id', <awscli.arguments.CLIArgument object at 0x7f92bf013198>), ('tags', <awscli.arguments.ListArgument object at 0x7f92bf016828>)])
2020-08-07 10:08:09,289 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.secretsmanager.tag-resource: calling handler <function add_streaming_output_arg at 0x7f92bf15e730>
2020-08-07 10:08:09,290 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.secretsmanager.tag-resource: calling handler <function add_cli_input_json at 0x7f92bfa7ff28>
2020-08-07 10:08:09,292 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.secretsmanager.tag-resource: calling handler <function add_cli_input_yaml at 0x7f92bfa8a620>
2020-08-07 10:08:09,293 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.secretsmanager.tag-resource: calling handler <function unify_paging_params at 0x7f92bf2ed0d0>
2020-08-07 10:08:09,358 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.0.14/dist/botocore/data/secretsmanager/2017-10-17/paginators-1.json
2020-08-07 10:08:09,360 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.secretsmanager.tag-resource: calling handler <function add_generate_skeleton at 0x7f92bf1bed08>
2020-08-07 10:08:09,361 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.secretsmanager.tag-resource: calling handler <function add_auto_prompt at 0x7f92bf11c8c8>
2020-08-07 10:08:09,362 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.secretsmanager.tag-resource: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7f92bf016860>>
2020-08-07 10:08:09,363 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.secretsmanager.tag-resource: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7f92bf016898>>
2020-08-07 10:08:09,365 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.secretsmanager.tag-resource: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f92bf016940>>
2020-08-07 10:08:09,366 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.secretsmanager.tag-resource: calling handler <bound method AutoPromptArgument.override_required_args of <awscli.customizations.autoprompt.AutoPromptArgument object at 0x7f92bf021da0>>
2020-08-07 10:08:09,369 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.secretsmanager.tag-resource.secret-id: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f92bf091ba8>
2020-08-07 10:08:09,370 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.secretsmanager.tag-resource: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f92c01e5470>
2020-08-07 10:08:09,371 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'myExampleSecret' for parameter "secret_id": 'myExampleSecret'
2020-08-07 10:08:09,372 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.secretsmanager.tag-resource.tags: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f92bf091ba8>
2020-08-07 10:08:09,372 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.secretsmanager.tag-resource: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f92c01e5470>
2020-08-07 10:08:09,374 - MainThread - awscli.argprocess - DEBUG - Parsing param --tags as shorthand
2020-08-07 10:08:09,374 - MainThread - awscli.clidriver - DEBUG - Client side parameter validation failed
Traceback (most recent call last):
  File "awscli/argprocess.py", line 331, in _parse_as_shorthand
  File "awscli/argprocess.py", line 331, in <listcomp>
  File "awscli/shorthand.py", line 166, in parse
  File "awscli/shorthand.py", line 181, in _parameter
awscli.shorthand.DuplicateKeyInObjectError: Second instance of key "Key" encountered for input:
Key=Favorite Food,Value=Cookie,Key=Favorite Color,Value=Gold
                               ^
This is often because there is a preceeding "," instead of a space.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "awscli/clidriver.py", line 335, in main
  File "awscli/clidriver.py", line 507, in __call__
  File "awscli/clidriver.py", line 656, in __call__
  File "awscli/clidriver.py", line 712, in _build_call_parameters
  File "awscli/arguments.py", line 453, in add_to_params
  File "awscli/arguments.py", line 463, in _unpack_argument
  File "awscli/arguments.py", line 476, in _emit_first_response
  File "awscli/arguments.py", line 473, in _emit
  File "botocore/hooks.py", line 227, in emit
  File "botocore/hooks.py", line 210, in _emit
  File "awscli/argprocess.py", line 314, in __call__
  File "awscli/argprocess.py", line 338, in _parse_as_shorthand
awscli.argprocess.ParamError: Error parsing parameter '--tags': Second instance of key "Key" encountered for input:
Key=Favorite Food,Value=Cookie,Key=Favorite Color,Value=Gold
                               ^
This is often because there is a preceeding "," instead of a space.

Error parsing parameter '--tags': Second instance of key "Key" encountered for input:
Key=Favorite Food,Value=Cookie,Key=Favorite Color,Value=Gold
                               ^
This is often because there is a preceeding "," instead of a space.

**Additional context**
It would be helpful if an additional example command was added to the documentation showing the optional syntax style for --tags, like this:
`aws secretsmanager tag-resource --secret-id MyTestDatabaseSecret \
  --tags Key="FirstTag",Value="SomeValue" Key="SecondTag",Value="AnotherValue"`

**Comment by kdaily** [comment]
Thanks for catching this, I will pass on to the Secrets Manager team to fix.

**Comment by stobrien89** [comment]
Closing, as the [documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/secretsmanager/tag-resource.html) has been updated to reflect the appropriate format.  Thanks again @bwcwestlund for pointing this out!
