### ISSUE TITLE
PutObject does not accept base64 encoded strings

### ISSUE THREAD

**Issue by jdelman** [aws/aws-cli#5465]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

According to the documentation, a parameter with type `blob` can either be a reference to a file or a base64-encoded string. However, when passing in a base64-encoded string for the `body` parameter, the AWS CLI returns the following error:

```
Error parsing parameter '--body': Blob values must be a path to a file.
```

The docs I'm referencing are here: https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-parameters-types.html#parameter-type-blob

**SDK version number**
aws-cli/2.0.7 Python/3.7.4 Darwin/18.7.0 botocore/2.0.0dev11

**Platform/OS/Hardware/Device**
macOS Mojave 10.14.6

**To Reproduce (observed behavior)**

Command for `aws` cli:

```bash
aws s3api put-object --key simple-key-value.json --body "eyJ0ZXN0IjoidmFsdWUifQ==" --bucket [bucket]
```

Replace [bucket] with any bucket you have access to.

**Expected behavior**
The CLI writes the string to S3 without errors.

**Logs/output**
```
  $ aws s3api put-object --cli-binary-format base64 --key simple-key-value.json --body 'eyJ0ZXN0IjoidmFsdWUifQ==' --bucket snaps-development-dumps --debug
2020-08-10 17:24:50,575 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.0.7 Python/3.7.4 Darwin/18.7.0 botocore/2.0.0dev11
2020-08-10 17:24:50,575 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3api', 'put-object', '--cli-binary-format', 'base64', '--key', 'simple-key-value.json', '--body', 'eyJ0ZXN0IjoidmFsdWUifQ==', '--bucket', 'snaps-development-dumps', '--debug']
2020-08-10 17:24:50,575 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7f8f28fa5320>
2020-08-10 17:24:50,575 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7f8f285a08c0>
2020-08-10 17:24:50,576 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7f8f30288c20>
2020-08-10 17:24:50,576 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f8f30106290>
2020-08-10 17:24:50,583 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f8f38448440>
2020-08-10 17:24:50,583 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7f8f28f3ba70>
2020-08-10 17:24:50,593 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/botocore/data/s3/2006-03-01/service-2.json
2020-08-10 17:24:50,604 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3api: calling handler <function add_waiters at 0x7f8f384b5ef0>
2020-08-10 17:24:50,612 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/botocore/data/s3/2006-03-01/waiters-2.json
2020-08-10 17:24:50,614 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('acl', <awscli.arguments.CLIArgument object at 0x7f8f384fdf50>), ('body', <awscli.arguments.CLIArgument object at 0x7f8f182bbed0>), ('bucket', <awscli.arguments.CLIArgument object at 0x7f8f384fe050>), ('cache-control', <awscli.arguments.CLIArgument object at 0x7f8f384fe150>), ('content-disposition', <awscli.arguments.CLIArgument object at 0x7f8f384fe0d0>), ('content-encoding', <awscli.arguments.CLIArgument object at 0x7f8f384fe110>), ('content-language', <awscli.arguments.CLIArgument object at 0x7f8f384fdf90>), ('content-length', <awscli.arguments.CLIArgument object at 0x7f8f384fe250>), ('content-md5', <awscli.arguments.CLIArgument object at 0x7f8f384fe410>), ('content-type', <awscli.arguments.CLIArgument object at 0x7f8f384fe490>), ('expires', <awscli.arguments.CLIArgument object at 0x7f8f384fe350>), ('grant-full-control', <awscli.arguments.CLIArgument object at 0x7f8f384fe390>), ('grant-read', <awscli.arguments.CLIArgument object at 0x7f8f384fe5d0>), ('grant-read-acp', <awscli.arguments.CLIArgument object at 0x7f8f384fe690>), ('grant-write-acp', <awscli.arguments.CLIArgument object at 0x7f8f384fe710>), ('key', <awscli.arguments.CLIArgument object at 0x7f8f384fe590>), ('metadata', <awscli.arguments.CLIArgument object at 0x7f8f384fe650>), ('server-side-encryption', <awscli.arguments.CLIArgument object at 0x7f8f384fe790>), ('storage-class', <awscli.arguments.CLIArgument object at 0x7f8f384fe890>), ('website-redirect-location', <awscli.arguments.CLIArgument object at 0x7f8f384fe810>), ('sse-customer-algorithm', <awscli.arguments.CLIArgument object at 0x7f8f384fe850>), ('sse-customer-key', <awscli.arguments.CLIArgument object at 0x7f8f384fe9d0>), ('sse-customer-key-md5', <awscli.arguments.CLIArgument object at 0x7f8f384fe8d0>), ('ssekms-key-id', <awscli.arguments.CLIArgument object at 0x7f8f384fea10>), ('ssekms-encryption-context', <awscli.arguments.CLIArgument object at 0x7f8f384fe990>), ('request-payer', <awscli.arguments.CLIArgument object at 0x7f8f384fead0>), ('tagging', <awscli.arguments.CLIArgument object at 0x7f8f384fea90>), ('object-lock-mode', <awscli.arguments.CLIArgument object at 0x7f8f384fec10>), ('object-lock-retain-until-date', <awscli.arguments.CLIArgument object at 0x7f8f384feb10>), ('object-lock-legal-hold-status', <awscli.arguments.CLIArgument object at 0x7f8f384fec90>)])
2020-08-10 17:24:50,614 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-object: calling handler <function add_streaming_output_arg at 0x7f8f28fa74d0>
2020-08-10 17:24:50,614 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-object: calling handler <function add_cli_input_json at 0x7f8f30109cb0>
2020-08-10 17:24:50,614 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-object: calling handler <function add_cli_input_yaml at 0x7f8f30109ef0>
2020-08-10 17:24:50,614 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-object: calling handler <function unify_paging_params at 0x7f8f28f55710>
2020-08-10 17:24:50,622 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/botocore/data/s3/2006-03-01/paginators-1.json
2020-08-10 17:24:50,622 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-object: calling handler <function add_generate_skeleton at 0x7f8ee8018a70>
2020-08-10 17:24:50,622 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-object: calling handler <function add_auto_prompt at 0x7f8f384efdd0>
2020-08-10 17:24:50,622 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.put-object: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7f8f384fec50>>
2020-08-10 17:24:50,622 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.put-object: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7f8f384fecd0>>
2020-08-10 17:24:50,622 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.put-object: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f8f385158d0>>
2020-08-10 17:24:50,622 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.put-object: calling handler <bound method AutoPromptArgument.override_required_args of <awscli.customizations.autoprompt.AutoPromptArgument object at 0x7f8f38519610>>
2020-08-10 17:24:50,624 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.acl: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f8f28fd3e50>
2020-08-10 17:24:50,624 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.body: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f8f28fd3e50>
2020-08-10 17:24:50,624 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.s3.put-object: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f8f28eac550>
2020-08-10 17:24:50,624 - MainThread - awscli.clidriver - DEBUG - Client side parameter validation failed
Traceback (most recent call last):
  File "awscli/clidriver.py", line 335, in main
  File "awscli/clidriver.py", line 507, in __call__
  File "awscli/clidriver.py", line 656, in __call__
  File "awscli/clidriver.py", line 712, in _build_call_parameters
  File "awscli/arguments.py", line 453, in add_to_params
  File "awscli/arguments.py", line 470, in _unpack_argument
  File "awscli/argprocess.py", line 143, in unpack_cli_arg
  File "awscli/argprocess.py", line 160, in _unpack_cli_arg
  File "awscli/argprocess.py", line 227, in unpack_scalar_cli_arg
awscli.argprocess.ParamError: Error parsing parameter '--body': Blob values must be a path to a file.

Error parsing parameter '--body': Blob values must be a path to a file.
```

**Additional context**

**Comment by kdaily** [comment]
Hi @jdelman, I can reproduce. I get the same error if I specify a file path with the `file://` prefix, as documented, instead of a string. I can get it to work if I pass a file path without the `file://` prefix.

**Comment by kdaily** [comment]
Hi @jdelman, this is an issue with our documentation, and it fooled me too. This parameter needs to be a path to a file. I'm going to label this as a documentation issue for us to fix. Thanks!

**Comment by jdelman** [comment]
So there's no plan to support passing in data directly on the command line?

If not, PR to fix docs:
https://github.com/awsdocs/aws-cli-user-guide/compare/master...jdelman:patch-1

**Comment by kdaily** [comment]
Thanks for the PR, I'll take a look. What I noticed is that the docs around blob parameters and the use of `file://` and `fileb://` are inconsistent and scattered (e.g., see here <https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-binaryparam>). We'll need to make a pass through them to collate and update.

**Comment by kdaily** [comment]
I got to the bottom of this. The blob type for `PutObject` is a streaming blob, which must be provided as the direct path to a file, not prefixed with `file://`. This needs to get better documentation, both at the parameter level in the reference guide as well as the user guide.

**Comment by Brainiac-M** [comment]
Thanks

**Comment by Brainiac-M** [comment]
Can you kindly show me the update to the documentation?

**Comment by Brainiac-M** [comment]
Can you kindly show me the update to the documentation? I was also fooled by the same issue some minutes ago and I found this issue over here with the solution.
