### ISSUE TITLE
cli v2 resourcegroupstaggingapi help error/missing

### ISSUE THREAD

**Issue by cteodor** [aws/aws-cli#5466]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
broken help for resourcegroupstaggingapi

**SDK version number**
aws-cli/2.0.38 Python/3.8.5 Darwin/19.6.0 source/x86_64

**Platform/OS/Hardware/Device**
OSX 10.15.6 (19G73)

**To Reproduce (observed behavior)**
aws resourcegroupstaggingapi help

**Expected behavior**
show help

**Logs/output**
  AWS_Resources aws resourcegroupstaggingapi help --debug                                                                                                                                 <aws:cteodor>
2020-08-11 14:52:34,616 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.0.38 Python/3.8.5 Darwin/19.6.0 source/x86_64
2020-08-11 14:52:34,616 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['resourcegroupstaggingapi', 'help', '--debug']
2020-08-11 14:52:34,616 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x10b906160>
2020-08-11 14:52:34,616 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x10b18e550>
2020-08-11 14:52:34,616 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x10b948790>
2020-08-11 14:52:34,616 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x10b1e9e50>
2020-08-11 14:52:34,623 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x10b7bfee0>
2020-08-11 14:52:34,623 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x10b76d0d0>
2020-08-11 14:52:34,638 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.0.38/libexec/lib/python3.8/site-packages/botocore/data/resourcegroupstaggingapi/2017-01-26/service-2.json
2020-08-11 14:52:34,639 - MainThread - botocore.hooks - DEBUG - Event building-command-table.resourcegroupstaggingapi: calling handler <function add_waiters at 0x10b90e790>
2020-08-11 14:52:34,654 - MainThread - botocore.hooks - DEBUG - Event doc-breadcrumbs.resourcegroupstaggingapi: calling handler <bound method CLIDocumentEventHandler.doc_breadcrumbs of <awscli.clidocs.ServiceDocumentEventHandler object at 0x10ca1d5b0>>
2020-08-11 14:52:34,654 - MainThread - botocore.hooks - DEBUG - Event doc-title.resourcegroupstaggingapi: calling handler <bound method CLIDocumentEventHandler.doc_title of <awscli.clidocs.ServiceDocumentEventHandler object at 0x10ca1d5b0>>
2020-08-11 14:52:34,654 - MainThread - botocore.hooks - DEBUG - Event doc-description.resourcegroupstaggingapi: calling handler <bound method ServiceDocumentEventHandler.doc_description of <awscli.clidocs.ServiceDocumentEventHandler object at 0x10ca1d5b0>>
2020-08-11 14:52:34,667 - MainThread - botocore.hooks - DEBUG - Event doc-description.resourcegroupstaggingapi: calling handler <function add_paging_description at 0x10b771790>
2020-08-11 14:52:34,667 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-start.resourcegroupstaggingapi: calling handler <bound method ServiceDocumentEventHandler.doc_synopsis_start of <awscli.clidocs.ServiceDocumentEventHandler object at 0x10ca1d5b0>>
2020-08-11 14:52:34,667 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-end.resourcegroupstaggingapi: calling handler <bound method ServiceDocumentEventHandler.doc_synopsis_end of <awscli.clidocs.ServiceDocumentEventHandler object at 0x10ca1d5b0>>
2020-08-11 14:52:34,667 - MainThread - botocore.hooks - DEBUG - Event doc-options-start.resourcegroupstaggingapi: calling handler <bound method ServiceDocumentEventHandler.doc_options_start of <awscli.clidocs.ServiceDocumentEventHandler object at 0x10ca1d5b0>>
2020-08-11 14:52:34,667 - MainThread - botocore.hooks - DEBUG - Event doc-options-end.resourcegroupstaggingapi: calling handler <bound method ServiceDocumentEventHandler.doc_options_end of <awscli.clidocs.ServiceDocumentEventHandler object at 0x10ca1d5b0>>
2020-08-11 14:52:34,667 - MainThread - botocore.hooks - DEBUG - Event doc-subitems-start.resourcegroupstaggingapi: calling handler <bound method ServiceDocumentEventHandler.doc_subitems_start of <awscli.clidocs.ServiceDocumentEventHandler object at 0x10ca1d5b0>>
2020-08-11 14:52:34,667 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.resourcegroupstaggingapi.describe-report-creation: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x10ca1d5b0>>
2020-08-11 14:52:34,668 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.resourcegroupstaggingapi.get-compliance-summary: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x10ca1d5b0>>
2020-08-11 14:52:34,668 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.resourcegroupstaggingapi.get-resources: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x10ca1d5b0>>
2020-08-11 14:52:34,668 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.resourcegroupstaggingapi.get-tag-keys: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x10ca1d5b0>>
2020-08-11 14:52:34,668 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.resourcegroupstaggingapi.get-tag-values: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x10ca1d5b0>>
2020-08-11 14:52:34,668 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.resourcegroupstaggingapi.help: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x10ca1d5b0>>
2020-08-11 14:52:34,668 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.resourcegroupstaggingapi.start-report-creation: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x10ca1d5b0>>
2020-08-11 14:52:34,668 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.resourcegroupstaggingapi.tag-resources: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x10ca1d5b0>>
2020-08-11 14:52:34,668 - MainThread - botocore.hooks - DEBUG - Event doc-subitem.resourcegroupstaggingapi.untag-resources: calling handler <bound method ServiceDocumentEventHandler.doc_subitem of <awscli.clidocs.ServiceDocumentEventHandler object at 0x10ca1d5b0>>
2020-08-11 14:52:34,668 - MainThread - botocore.hooks - DEBUG - Event doc-relateditems-start.resourcegroupstaggingapi: calling handler <bound method CLIDocumentEventHandler.doc_relateditems_start of <awscli.clidocs.ServiceDocumentEventHandler object at 0x10ca1d5b0>>
2020-08-11 14:52:34,831 - MainThread - awscli.help - DEBUG - Running command: ['groff', '-m', 'man', '-T', 'ascii']
2020-08-11 14:52:34,865 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/Cellar/awscli/2.0.38/libexec/lib/python3.8/site-packages/awscli/clidriver.py", line 378, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/Cellar/awscli/2.0.38/libexec/lib/python3.8/site-packages/awscli/clidriver.py", line 550, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/Cellar/awscli/2.0.38/libexec/lib/python3.8/site-packages/awscli/help.py", line 273, in __call__
    self.renderer.render(self.doc.getvalue())
  File "/usr/local/Cellar/awscli/2.0.38/libexec/lib/python3.8/site-packages/awscli/help.py", line 85, in render
    self._send_output_to_pager(converted_content)
  File "/usr/local/Cellar/awscli/2.0.38/libexec/lib/python3.8/site-packages/awscli/help.py", line 120, in _send_output_to_pager
    if not self._exists_on_path(cmdline[0]):
IndexError: list index out of range
2020-08-11 14:52:34,867 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

**Comment by kdaily** [comment]
Hi @cteodor, I'm not able to reproduce. I tried on an older version on my Mac (2.0.21) and the most through the AWS CLI Docker container image (2.0.38). Can you try to reinstall?

**Comment by cteodor** [comment]
Could not longer reproduce after reinstall.
