### ISSUE TITLE
aws s3 sync --exclude & --include not working

### ISSUE THREAD

**Issue by kirosc** [aws/aws-cli#5614]
**Describe the bug**
The ``--include`` argument doesn't work on `aws s3`

**SDK version number**
aws-cli/2.0.55 Python/3.7.4 Darwin/19.6.0 exe/x86_64

**Platform/OS/Hardware/Device**
MacOS

**To Reproduce (observed behavior)**
`aws s3 cp ./foo/ s3://bucket-name --recursive --exclude "*" –-include "*.json"`

**Logs/output**
```
2020-10-08 16:24:58,963 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.0.55 Python/3.7.4 Darwin/19.6.0 exe/x86_64
2020-10-08 16:24:58,963 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3', 'cp', './foo/', 's3://bucket-name', '--recursive', '--exclude', '*', '–-include', '*.json', '--debug']
2020-10-08 16:24:58,963 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7f9f7dd93170>
2020-10-08 16:24:58,963 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7f9f7d69e830>
2020-10-08 16:24:58,963 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7f9f7df1cd40>
2020-10-08 16:24:58,963 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x7f9f7d653dd0>
2020-10-08 16:24:58,963 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f9f7d6ce440>
2020-10-08 16:24:58,968 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f9f7dc3fe60>
2020-10-08 16:24:58,968 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7f9f7dbe4f80>
2020-10-08 16:24:58,968 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3: calling handler <function add_waiters at 0x7f9f7dd9edd0>
2020-10-08 16:24:58,969 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.s3.anonymous: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,969 - MainThread - botocore.hooks - DEBUG - Event building-command-table.cp: calling handler <function add_waiters at 0x7f9f7dd9edd0>
2020-10-08 16:24:58,970 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.paths: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,970 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.dryrun: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,970 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f9f7d692e10>
2020-10-08 16:24:58,970 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.quiet: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f9f7d692e10>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.anonymous: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.acl: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.follow-symlinks: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f9f7d692e10>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.anonymous: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse-c: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse-c-key: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse-kms-key-id: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse-c-copy-source: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse-c-copy-source-key: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.storage-class: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.grants: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.website-redirect: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.content-type: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.cache-control: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.content-disposition: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.content-encoding: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.content-language: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.expires: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.source-region: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,971 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.only-show-errors: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,972 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f9f7d692e10>
2020-10-08 16:24:58,972 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.anonymous: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,972 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.page-size: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,972 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.ignore-glacier-warnings: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,972 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f9f7d692e10>
2020-10-08 16:24:58,972 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.force-glacier-transfer: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,972 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f9f7d692e10>
2020-10-08 16:24:58,972 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.request-payer: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,972 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.metadata: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,972 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.copy-props: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,972 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f9f7d692e10>
2020-10-08 16:24:58,972 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.metadata-directive: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,972 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.expected-size: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,972 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.anonymous: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f9f7dfa6cd0>
2020-10-08 16:24:58,972 - MainThread - awscli.clidriver - DEBUG - Client side parameter validation failed
Traceback (most recent call last):
  File "awscli/clidriver.py", line 386, in main
  File "awscli/customizations/commands.py", line 198, in __call__
  File "awscli/customizations/commands.py", line 189, in __call__
awscli.customizations.exceptions.ParamValidationError: Unknown options: –-include,*.json

Unknown options: –-include,*.json
```

**Comment by kdaily** [comment]
Hi @kirosc,

I think you have a typo (very subtle) in your command. I copy/pasted what you posted, and it also failed for me. But you have a strange dash/hyphen character in the `include` parameter: `–` versus `-`. Fixing that and the command works fine.

If you copy/pasted this command from AWS CLI documentation, let me know where and I can correct it.

**Comment by kirosc** [comment]
> Hi @kirosc,
> 
> I think you have a typo (very subtle) in your command. I copy/pasted what you posted, and it also failed for me. But you have a strange dash/hyphen character in the `include` parameter: `–` versus `-`. Fixing that and the command works fine.
> 
> If you copy/pasted this command from AWS CLI documentation, let me know where and I can correct it.

Thanks! I didn't notice that!
