### ISSUE TITLE
cloudformation package fails with 'Fn::Transform' in template

### ISSUE THREAD

**Issue by jpbarto** [aws/aws-cli#5619]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When calling `aws cloudformation package` on a template the includes an 'Fn::Transform' statement the CLI fails to package the cloudformation with an error that `'list' object has no attribute 'get'`.  A `List` object is being passed to `include_transform_export_handler` which is expecting a `Dict` object.

**SDK version number**

Tested with aws-cli/2.0.44 Python/3.8.5 Darwin/19.6.0 source/x86_64 and aws-cli/1.18.156 Python/3.8.5 Darwin/19.6.0 botocore/1.18.15

**Platform/OS/Hardware/Device**
OSX Macbook

**To Reproduce (observed behavior)**
Download the string_example.yaml file from the example macros repository: https://raw.githubusercontent.com/aws-cloudformation/aws-cloudformation-macros/master/StringFunctions/string_example.yaml
Now package the template using the CLI:

`aws cloudformation package --template-file string_example.yaml --s3-bucket my-acct-cloudformation --output-template-file /tmp/out.yaml  --debug`

**Expected behavior**
I expect a packaged template to be outputed to /tmp/out.yaml.

**Logs/output**
```
2020-10-08 23:50:32,288 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/Users/jasbarto/.local/share/virtualenvs/cfn_package-tG2JIMI1/lib/python3.8/site-packages/awscli/clidriver.py", line 217, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/Users/jasbarto/.local/share/virtualenvs/cfn_package-tG2JIMI1/lib/python3.8/site-packages/awscli/clidriver.py", line 358, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/Users/jasbarto/.local/share/virtualenvs/cfn_package-tG2JIMI1/lib/python3.8/site-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/Users/jasbarto/.local/share/virtualenvs/cfn_package-tG2JIMI1/lib/python3.8/site-packages/awscli/customizations/cloudformation/package.py", line 150, in _run_main
    exported_str = self._export(template_path, use_json)
  File "/Users/jasbarto/.local/share/virtualenvs/cfn_package-tG2JIMI1/lib/python3.8/site-packages/awscli/customizations/cloudformation/package.py", line 166, in _export
    exported_template = template.export()
  File "/Users/jasbarto/.local/share/virtualenvs/cfn_package-tG2JIMI1/lib/python3.8/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 647, in export
    self.template_dict = self.export_global_artifacts(self.template_dict)
  File "/Users/jasbarto/.local/share/virtualenvs/cfn_package-tG2JIMI1/lib/python3.8/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 606, in export_global_artifacts
    self.export_global_artifacts(val)
  File "/Users/jasbarto/.local/share/virtualenvs/cfn_package-tG2JIMI1/lib/python3.8/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 606, in export_global_artifacts
    self.export_global_artifacts(val)
  File "/Users/jasbarto/.local/share/virtualenvs/cfn_package-tG2JIMI1/lib/python3.8/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 606, in export_global_artifacts
    self.export_global_artifacts(val)
  File "/Users/jasbarto/.local/share/virtualenvs/cfn_package-tG2JIMI1/lib/python3.8/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 610, in export_global_artifacts
    self.export_global_artifacts(item)
  File "/Users/jasbarto/.local/share/virtualenvs/cfn_package-tG2JIMI1/lib/python3.8/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 606, in export_global_artifacts
    self.export_global_artifacts(val)
  File "/Users/jasbarto/.local/share/virtualenvs/cfn_package-tG2JIMI1/lib/python3.8/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 604, in export_global_artifacts
    template_dict[key] = GLOBAL_EXPORT_DICT[key](val, self.uploader, self.template_dir)
  File "/Users/jasbarto/.local/share/virtualenvs/cfn_package-tG2JIMI1/lib/python3.8/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 530, in include_transform_export_handler
    if template_dict.get("Name", None) != "AWS::Include":
AttributeError: 'list' object has no attribute 'get'
2020-10-08 23:50:32,294 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

'list' object has no attribute 'get'
```
**Additional context**

**Comment by jpbarto** [comment]
Please disregard.  The example code in the aws-cloudformation macro sample repository is in error.  Upon closer inspection the string_example.yaml defines the 'Fn::Transform' as a list containing a single object with `Name` and `Parameter` fields.  This is invalid and inconsistent with the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-transform.html) which clearly states to have a single object defining `Fn::Transform` not a `list` of object.  I will submit a PR to the aws-cloudformation repository.
