### ISSUE TITLE
Can AWS CLI support Forward proxy using SSL protocol? 

### ISSUE THREAD

**Issue by stanltam** [aws/aws-cli#5640]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Currently, I tried to connect AWS ECR endpoint through proxy. I am working fine for connecting with proxy using HTTP protocol. However, when I configure the proxy server to listen on 443, and trusted the proxy server cert. The AWS CLI client is not able to connect with following exception: botocore.exceptions.ProxyConnectionError: Failed to connect to proxy URL: "https://test-proxy:443". And I have tried to use curl command, it is working fine with proxy to the api.ecr.ap-east-1.amazonaws.com. 

**SDK version number**
aws-cli/2.0.35 Python/3.7.3 Linux/3.10.0-1062.12.1.el7.x86_64 botocore/2.0.0dev39

**Platform/OS/Hardware/Device**
What are you running the cli on?
CentOS 8.2

**To Reproduce (observed behavior)**

export HTTP_PROXY=https://test-proxy:443
export HTTPS_PROXY=https://test-proxy:443

aws ecr get-login-password  --region ap-east-1 --debug

**Expected behavior**
AWS CLI is working fine if connect through proxy using HTTPS protocol  in following command:
export HTTP_PROXY=https://test-proxy:443
export HTTPS_PROXY=https://test-proxy:443

aws ecr get-login-password  --region ap-east-1 --debug

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.
2020-10-12 10:09:19,704 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.0.35 Python/3.7.3 Linux/4.18.0-147.3.1.el8_1.x86_64 botocore/2.0.0dev39
2020-10-12 10:09:19,704 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['ecr', 'get-login-password', '--region', 'ap-east-1', '--debug']
2020-10-12 10:09:19,705 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7fb63f2e76a8>
2020-10-12 10:09:19,705 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7fb63fc10620>
2020-10-12 10:09:19,705 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7fb63f2abbf8>
2020-10-12 10:09:19,705 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7fb63fbe79d8>
2020-10-12 10:09:19,707 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7fb63f3b8158>
2020-10-12 10:09:19,707 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7fb63f46aa60>
2020-10-12 10:09:19,715 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.0.35/dist/botocore/data/ecr/2015-09-21/service-2.json
2020-10-12 10:09:19,721 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ecr: calling handler <function _inject_commands at 0x7fb63f3c6488>
2020-10-12 10:09:19,721 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ecr: calling handler <function add_waiters at 0x7fb63f2f0ae8>
2020-10-12 10:09:19,728 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.0.35/dist/botocore/data/ecr/2015-09-21/waiters-2.json
2020-10-12 10:09:19,729 - MainThread - botocore.hooks - DEBUG - Event building-command-table.get-login-password: calling handler <function add_waiters at 0x7fb63f2f0ae8>
2020-10-12 10:09:19,730 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2020-10-12 10:09:19,730 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2020-10-12 10:09:19,731 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2020-10-12 10:09:19,731 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2020-10-12 10:09:19,731 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2020-10-12 10:09:19,732 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2020-10-12 10:09:19,732 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.0.35/dist/botocore/data/endpoints.json
2020-10-12 10:09:19,741 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7fb640be4f28>
2020-10-12 10:09:19,742 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.ecr: calling handler <function add_generate_presigned_url at 0x7fb640c30d90>
2020-10-12 10:09:19,747 - MainThread - botocore.endpoint - DEBUG - Setting api.ecr timeout as (60, 60)
2020-10-12 10:09:19,748 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.ecr.GetAuthorizationToken: calling handler <function base64_decode_input_blobs at 0x7fb63f2b1488>
2020-10-12 10:09:19,748 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.ecr.GetAuthorizationToken: calling handler <function generate_idempotent_uuid at 0x7fb640c00e18>
2020-10-12 10:09:19,749 - MainThread - botocore.hooks - DEBUG - Event before-call.ecr.GetAuthorizationToken: calling handler <function inject_api_version_header_if_needed at 0x7fb640c05620>
2020-10-12 10:09:19,749 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=GetAuthorizationToken) with params: {'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'X-Amz-Target': 'AmazonEC2ContainerRegistry_V20150921.GetAuthorizationToken', 'Content-Type': 'application/x-amz-json-1.1', 'User-Agent': 'aws-cli/2.0.35 Python/3.7.3 Linux/4.18.0-147.3.1.el8_1.x86_64 botocore/2.0.0dev39'}, 'body': b'{}', 'url': 'https://api.ecr.ap-east-1.amazonaws.com/', 'context': {'client_region': 'ap-east-1', 'client_config': <botocore.config.Config object at 0x7fb63eef6390>, 'has_streaming_input': False, 'auth_type': None}}
2020-10-12 10:09:19,749 - MainThread - botocore.hooks - DEBUG - Event request-created.ecr.GetAuthorizationToken: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fb63eef6320>>
2020-10-12 10:09:19,749 - MainThread - botocore.hooks - DEBUG - Event choose-signer.ecr.GetAuthorizationToken: calling handler <function set_operation_specific_signer at 0x7fb640c00d08>
2020-10-12 10:09:19,750 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2020-10-12 10:09:19,750 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-amz-json-1.1
host:api.ecr.ap-east-1.amazonaws.com
x-amz-date:20201012T170919Z
x-amz-target:AmazonEC2ContainerRegistry_V20150921.GetAuthorizationToken

content-type;host;x-amz-date;x-amz-target
44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
2020-10-12 10:09:19,750 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20201012T170919Z
20201012/ap-east-1/ecr/aws4_request
7270de356aacced275b30ddf2ebf9bf6fd080fbf1f60772859c5a9d7ddc888ff
2020-10-12 10:09:19,750 - MainThread - botocore.auth - DEBUG - Signature:
b357c3f26a71ec8fb95cd155ed6f29d4bf6e40a10fdb819a0373ec4a1ee60feb
2020-10-12 10:09:19,750 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://api.ecr.ap-east-1.amazonaws.com/, headers={'X-Amz-Target': b'AmazonEC2ContainerRegistry_V20150921.GetAuthorizationToken', 'Content-Type': b'application/x-amz-json-1.1', 'User-Agent': b'aws-cli/2.0.35 Python/3.7.3 Linux/4.18.0-147.3.1.el8_1.x86_64 botocore/2.0.0dev39', 'X-Amz-Date': b'20201012T170919Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=xxxxxxxxxxxxxxxxxx/20201012/ap-east-1/ecr/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'Content-Length': '2'}>
2020-10-12 10:09:19,752 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.ecr.ap-east-1.amazonaws.com:443
2020-10-12 10:09:19,753 - MainThread - botocore.endpoint - DEBUG - Exception received when sending HTTP request.
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 667, in urlopen
  File "urllib3/connectionpool.py", line 932, in _prepare_proxy
  File "urllib3/connection.py", line 317, in connect
  File "http/client.py", line 906, in _tunnel
  File "http/client.py", line 265, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore/httpsession.py", line 263, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 379, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 667, in urlopen
  File "urllib3/connectionpool.py", line 932, in _prepare_proxy
  File "urllib3/connection.py", line 317, in connect
  File "http/client.py", line 906, in _tunnel
  File "http/client.py", line 265, in _read_status
urllib3.exceptions.ProxyError: ('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore/endpoint.py", line 200, in _do_get_response
  File "botocore/endpoint.py", line 269, in _send
  File "botocore/httpsession.py", line 285, in send
botocore.exceptions.ProxyConnectionError: Failed to connect to proxy URL: "https://test-proxy:443"

**Additional context**

**Comment by kdaily** [comment]
Hi @stanltam, I'll have to look into this. Thanks for the details.

**Comment by stanltam** [comment]
Hi @kdaily, just wonder if you encountered the same issue? This issue blocked me to proceed...

**Comment by kdaily** [comment]
Hi @stanltam ,

This is an underlying issue with `urllib3`, which does not support https through proxies:

https://github.com/urllib3/urllib3/issues/1520

We are aware of this limitation and are monitoring the fix needed by `urllib3`. Once this is addressed, `botocore` will be updated, and then the AWS CLI will get that update. I will leave this open for visibility here.

**Comment by yang5155324** [comment]
@kdaily   how  about this issue?  has been fixed ?   we have this issue too. 
we can not upload file via proxy with https and http

**Comment by maust** [comment]
looks like urllib3 fixed it in https://github.com/urllib3/urllib3/releases/tag/1.26.0

**Comment by kdaily** [comment]
Hi @stanltam and others,

This has been addressed via PR https://github.com/boto/botocore/pull/2240.

You can read about it here:

https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#configure-proxies
