### ISSUE TITLE
When calling redshift-data describe-statement on a failed query, exits with AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by dominics** [aws/aws-cli#5644]
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Description**

I issued a malformed SQL statement to my Redshift cluster using `aws redshift-data execute-statement`. When I then follow up with a `aws redshift-data describe-statement`, the command fails, throwing an uncaught `AttributeError: 'str' object has no attribute 'get'` from within `needs_retry`

**Version/Platform**

```
$ aws --version
aws-cli/2.0.56 Python/3.9.0 Darwin/19.6.0 source/x86_64
```

Mac OS, installed from homebrew

**Reproduction**

- `aws --profile foo redshift-data execute-statement  --database some_db --cluster-identifier some_cluster --db-user iam_user --sql "unload (select * from some_table) to 's3://some_bucket/key' iam_role 'arn:aws:sts::123456789:assumed-role/some-role/1234567890221684000';"`
  - NB: not a valid statement, will fail on Redshift
- `aws --profile foo redshift-data describe-statement --id <id from execute-statement output> --debug`

**Logs/output**

Some detail anonymized

```
[...]
2020-10-16 09:32:24,625 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): redshift-data.us-west-2.amazonaws.com:443
2020-10-16 09:32:25,327 - MainThread - urllib3.connectionpool - DEBUG - https://redshift-data.us-west-2.amazonaws.com:443 "POST / HTTP/1.1" 200 476
2020-10-16 09:32:25,328 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-RequestId': 'b4f6a7f4-d597-494a-9622-9f0fca555161', 'Content-Type': 'application/x-amz-json-1.1', 'Content-Length': '476', 'Date': 'Thu, 15 Oct 2020 20:32:25 GMT'}
2020-10-16 09:32:25,328 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"ClusterIdentifier":"some_cluster","CreatedAt":1.60279372614E9,"Duration":-1,"Error":"ERROR: syntax error at or near \\"select\\"\\n  Position: 9","Id":"b79e5383-47a1-4155-b7d8-abc950ca601b","QueryString":"unload (select * from some_table) to \'s3://some_bucket/file\' iam_role \'\';","RedshiftPid":10752,"RedshiftQueryId":-1,"ResultRows":-1,"ResultSize":-1,"Status":"FAILED","UpdatedAt":1.602793726954E9}'
2020-10-16 09:32:25,329 - MainThread - botocore.hooks - DEBUG - Event needs-retry.redshift-data.DescribeStatement: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x10f164550>>
2020-10-16 09:32:25,329 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/Cellar/awscli/2.0.56_1/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 386, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/Cellar/awscli/2.0.56_1/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 558, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/Cellar/awscli/2.0.56_1/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 735, in __call__
    return self._operation_caller.invoke(
  File "/usr/local/Cellar/awscli/2.0.56_1/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 866, in invoke
    response = self._make_client_call(
  File "/usr/local/Cellar/awscli/2.0.56_1/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 878, in _make_client_call
    response = getattr(client, xform_name(operation_name))(
  File "/usr/local/Cellar/awscli/2.0.56_1/libexec/lib/python3.9/site-packages/botocore/client.py", line 249, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/Cellar/awscli/2.0.56_1/libexec/lib/python3.9/site-packages/botocore/client.py", line 554, in _make_api_call
    http, parsed_response = self._make_request(
  File "/usr/local/Cellar/awscli/2.0.56_1/libexec/lib/python3.9/site-packages/botocore/client.py", line 574, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/Cellar/awscli/2.0.56_1/libexec/lib/python3.9/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/Cellar/awscli/2.0.56_1/libexec/lib/python3.9/site-packages/botocore/endpoint.py", line 136, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "/usr/local/Cellar/awscli/2.0.56_1/libexec/lib/python3.9/site-packages/botocore/endpoint.py", line 253, in _needs_retry
    responses = self._event_emitter.emit(
  File "/usr/local/Cellar/awscli/2.0.56_1/libexec/lib/python3.9/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/Cellar/awscli/2.0.56_1/libexec/lib/python3.9/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/Cellar/awscli/2.0.56_1/libexec/lib/python3.9/site-packages/botocore/retries/standard.py", line 79, in needs_retry
    if self._retry_policy.should_retry(context):
  File "/usr/local/Cellar/awscli/2.0.56_1/libexec/lib/python3.9/site-packages/botocore/retries/standard.py", line 224, in should_retry
    return self._retry_checker.is_retryable(context)
  File "/usr/local/Cellar/awscli/2.0.56_1/libexec/lib/python3.9/site-packages/botocore/retries/standard.py", line 431, in is_retryable
    self._additional_checkers.is_retryable(context))
  File "/usr/local/Cellar/awscli/2.0.56_1/libexec/lib/python3.9/site-packages/botocore/retries/standard.py", line 439, in is_retryable
    return any(checker.is_retryable(context) for checker in self._checkers)
  File "/usr/local/Cellar/awscli/2.0.56_1/libexec/lib/python3.9/site-packages/botocore/retries/standard.py", line 439, in <genexpr>
    return any(checker.is_retryable(context) for checker in self._checkers)
  File "/usr/local/Cellar/awscli/2.0.56_1/libexec/lib/python3.9/site-packages/botocore/retries/standard.py", line 298, in is_retryable
    if context.get_error_code() in self._transient_error_codes:
  File "/usr/local/Cellar/awscli/2.0.56_1/libexec/lib/python3.9/site-packages/botocore/retries/standard.py", line 201, in get_error_code
    return self.parsed_response.get('Error', {}).get('Code')
AttributeError: 'str' object has no attribute 'get'
2020-10-16 09:32:25,333 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

'str' object has no attribute 'get'
```

**Comment by kdaily** [comment]
Hi @dominics, can you confirm that this occurs with one of the approved installation methods for the v2 client? I think that it looks like a string quoting problem, but want to rule out the Homebrew installation, as well as using Python 3.9.

https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-mac.html

**Comment by kdaily** [comment]
The response body has a field of `Error`, which the retry code is seeing and expecting to find some more information about the error returned and why it should retry.
