### ISSUE TITLE
cloudtrail: create-trail for organizations w/ bucket in different account gives InternalFailure

### ISSUE THREAD

**Issue by anarsen** [aws/aws-cli#5678]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [x] Service API : I want to do X using Y service, what should I do?
- [ ] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
aws-cli/2.0.59 Python/3.9.0 Linux/5.4.0-52-generic source/x86_64.ubuntu.20

**Describe the question**
I'm trying to create an Organization-wide trail on the master account with a target S3 bucket residing in a **different** account:

```
aws cloudtrail create-trail \
  --name organization \
  --is-organization-trail \
  --s3-bucket-name foobucket \
  --enable-log-file-validation \
  --include-global-service-events
```

It ends up giving me

```
An error occurred (InternalFailure) when calling the CreateTrail operation (reached max retries: 2)
```

I'm authenticated with privileges corresponding to `AdministratorAccess`. Going through the same process from the Console in the master account works without problems.

It's probably not a bug with the AWS CLI, but this was the best place I could think of to start.

**Logs/output**

<details>
<pre>
2020-10-28 08:04:07,552 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.0.59 Python/3.9.0 Linux/5.4.0-52-generic source/x86_64.ubuntu.20
2020-10-28 08:04:07,552 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['cloudtrail', 'create-trail', '--name', 'organization23', '--s3-bucket-name', 'nuuday-cloudtrail-logs', '--enable-log-file-validation', '--is-organization-trail', '--include-global-service-events', '--debug']
2020-10-28 08:04:07,552 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7f3679377160>
2020-10-28 08:04:07,552 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7f367a3b2a60>
2020-10-28 08:04:07,553 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7f3679342790>
2020-10-28 08:04:07,553 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x7f367a3b3430>
2020-10-28 08:04:07,553 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f367a3194c0>
2020-10-28 08:04:07,556 - MainThread - botocore.utils - INFO - IMDS ENDPOINT: http://169.254.169.254/
2020-10-28 08:04:07,558 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f36794be160>
2020-10-28 08:04:07,559 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7f36794e9550>
2020-10-28 08:04:07,566 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /home/linuxbrew/.linuxbrew/Cellar/awscli/2.0.59/libexec/lib/python3.9/site-packages/botocore/data/cloudtrail/2013-11-01/service-2.json
2020-10-28 08:04:07,570 - MainThread - botocore.hooks - DEBUG - Event building-command-table.cloudtrail: calling handler <function inject_commands at 0x7f36798921f0>
2020-10-28 08:04:07,570 - MainThread - botocore.hooks - DEBUG - Event building-command-table.cloudtrail: calling handler <function add_waiters at 0x7f367937e700>
2020-10-28 08:04:07,576 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('name', <awscli.arguments.CLIArgument object at 0x7f36791f1220>), ('s3-bucket-name', <awscli.arguments.CLIArgument object at 0x7f36791f1250>), ('s3-key-prefix', <awscli.arguments.CLIArgument object at 0x7f36791f1280>), ('sns-topic-name', <awscli.arguments.CLIArgument object at 0x7f36791f12b0>), ('include-global-service-events', <awscli.arguments.BooleanArgument object at 0x7f36791f12e0>), ('no-include-global-service-events', <awscli.arguments.BooleanArgument object at 0x7f36791f1310>), ('is-multi-region-trail', <awscli.arguments.BooleanArgument object at 0x7f36791f1340>), ('no-is-multi-region-trail', <awscli.arguments.BooleanArgument object at 0x7f36791f1370>), ('enable-log-file-validation', <awscli.arguments.BooleanArgument object at 0x7f36791f13a0>), ('no-enable-log-file-validation', <awscli.arguments.BooleanArgument object at 0x7f36791f13d0>), ('cloud-watch-logs-log-group-arn', <awscli.arguments.CLIArgument object at 0x7f36791f1400>), ('cloud-watch-logs-role-arn', <awscli.arguments.CLIArgument object at 0x7f36791f1430>), ('kms-key-id', <awscli.arguments.CLIArgument object at 0x7f36791f1460>), ('is-organization-trail', <awscli.arguments.BooleanArgument object at 0x7f36791f1490>), ('no-is-organization-trail', <awscli.arguments.BooleanArgument object at 0x7f36791f14c0>), ('tags-list', <awscli.arguments.ListArgument object at 0x7f36791f14f0>)])
2020-10-28 08:04:07,577 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudtrail.create-trail: calling handler <function add_streaming_output_arg at 0x7f3679377430>
2020-10-28 08:04:07,577 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudtrail.create-trail: calling handler <function add_cli_input_json at 0x7f367a319ca0>
2020-10-28 08:04:07,577 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudtrail.create-trail: calling handler <function add_cli_input_yaml at 0x7f367a319ee0>
2020-10-28 08:04:07,577 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudtrail.create-trail: calling handler <function unify_paging_params at 0x7f36794eeca0>
2020-10-28 08:04:07,583 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /home/linuxbrew/.linuxbrew/Cellar/awscli/2.0.59/libexec/lib/python3.9/site-packages/botocore/data/cloudtrail/2013-11-01/paginators-1.json
2020-10-28 08:04:07,583 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudtrail.create-trail: calling handler <function add_generate_skeleton at 0x7f367cbaa280>
2020-10-28 08:04:07,583 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudtrail.create-trail: calling handler <function add_auto_prompt at 0x7f3679342700>
2020-10-28 08:04:07,584 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cloudtrail.create-trail: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7f36791f15e0>>
2020-10-28 08:04:07,584 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cloudtrail.create-trail: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7f36791f1610>>
2020-10-28 08:04:07,584 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cloudtrail.create-trail: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f36791f1760>>
2020-10-28 08:04:07,584 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cloudtrail.create-trail: calling handler <bound method AutoPromptArgument.override_required_args of <awscli.customizations.autoprompt.AutoPromptArgument object at 0x7f36791f1880>>
2020-10-28 08:04:07,585 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudtrail.create-trail.name: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f36792b0c70>
2020-10-28 08:04:07,585 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.cloudtrail.create-trail: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f367a355a90>
2020-10-28 08:04:07,585 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'organization23' for parameter "name": 'organization23'
2020-10-28 08:04:07,585 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudtrail.create-trail.s3-bucket-name: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f36792b0c70>
2020-10-28 08:04:07,585 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.cloudtrail.create-trail: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f367a355a90>
2020-10-28 08:04:07,585 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'nuuday-cloudtrail-logs' for parameter "s3_bucket_name": 'nuuday-cloudtrail-logs'
2020-10-28 08:04:07,585 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudtrail.create-trail.s3-key-prefix: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f36792b0c70>
2020-10-28 08:04:07,585 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudtrail.create-trail.sns-topic-name: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f36792b0c70>
2020-10-28 08:04:07,585 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudtrail.create-trail.include-global-service-events: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f36792b0c70>
2020-10-28 08:04:07,585 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudtrail.create-trail.is-multi-region-trail: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f36792b0c70>
2020-10-28 08:04:07,585 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudtrail.create-trail.enable-log-file-validation: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f36792b0c70>
2020-10-28 08:04:07,585 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudtrail.create-trail.cloud-watch-logs-log-group-arn: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f36792b0c70>
2020-10-28 08:04:07,585 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudtrail.create-trail.cloud-watch-logs-role-arn: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f36792b0c70>
2020-10-28 08:04:07,585 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudtrail.create-trail.kms-key-id: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f36792b0c70>
2020-10-28 08:04:07,585 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudtrail.create-trail.is-organization-trail: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f36792b0c70>
2020-10-28 08:04:07,585 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudtrail.create-trail.tags-list: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f36792b0c70>
2020-10-28 08:04:07,585 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudtrail.create-trail.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f36792b0c70>
2020-10-28 08:04:07,585 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudtrail.create-trail.cli-input-yaml: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f36792b0c70>
2020-10-28 08:04:07,586 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudtrail.create-trail.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f36792b0c70>
2020-10-28 08:04:07,586 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudtrail.create-trail.cli-auto-prompt: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f36792b0c70>
2020-10-28 08:04:07,586 - MainThread - botocore.hooks - DEBUG - Event calling-command.cloudtrail.create-trail: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7f36791f15e0>>
2020-10-28 08:04:07,586 - MainThread - botocore.hooks - DEBUG - Event calling-command.cloudtrail.create-trail: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7f36791f1610>>
2020-10-28 08:04:07,586 - MainThread - botocore.hooks - DEBUG - Event calling-command.cloudtrail.create-trail: calling handler <bound method GenerateCliSkeletonArgument.generate_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f36791f1760>>
2020-10-28 08:04:07,586 - MainThread - botocore.hooks - DEBUG - Event calling-command.cloudtrail.create-trail: calling handler <bound method AutoPromptArgument.auto_prompt_arguments of <awscli.customizations.autoprompt.AutoPromptArgument object at 0x7f36791f1880>>
2020-10-28 08:04:07,586 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2020-10-28 08:04:07,586 - MainThread - botocore.credentials - INFO - Found credentials in environment variables.
2020-10-28 08:04:07,587 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /home/linuxbrew/.linuxbrew/Cellar/awscli/2.0.59/libexec/lib/python3.9/site-packages/botocore/data/endpoints.json
2020-10-28 08:04:07,592 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f367b828160>
2020-10-28 08:04:07,592 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.cloudtrail: calling handler <function add_generate_presigned_url at 0x7f367b8485e0>
2020-10-28 08:04:07,595 - MainThread - botocore.endpoint - DEBUG - Setting cloudtrail timeout as (60, 60)
2020-10-28 08:04:07,596 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.cloudtrail.CreateTrail: calling handler <function base64_decode_input_blobs at 0x7f3679348040>
2020-10-28 08:04:07,596 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.cloudtrail.CreateTrail: calling handler <function generate_idempotent_uuid at 0x7f367b7b9280>
2020-10-28 08:04:07,596 - MainThread - botocore.hooks - DEBUG - Event before-call.cloudtrail.CreateTrail: calling handler <function inject_api_version_header_if_needed at 0x7f367b7beaf0>
2020-10-28 08:04:07,596 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=CreateTrail) with params: {'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'X-Amz-Target': 'com.amazonaws.cloudtrail.v20131101.CloudTrail_20131101.CreateTrail', 'Content-Type': 'application/x-amz-json-1.1', 'User-Agent': 'aws-cli/2.0.59 Python/3.9.0 Linux/5.4.0-52-generic source/x86_64.ubuntu.20 command/cloudtrail.create-trail'}, 'body': b'{"Name": "organization23", "S3BucketName": "nuuday-cloudtrail-logs", "IncludeGlobalServiceEvents": true, "EnableLogFileValidation": true, "IsOrganizationTrail": true}', 'url': 'https://cloudtrail.eu-central-1.amazonaws.com/', 'context': {'client_region': 'eu-central-1', 'client_config': <botocore.config.Config object at 0x7f36791fed60>, 'has_streaming_input': False, 'auth_type': None}}
2020-10-28 08:04:07,596 - MainThread - botocore.hooks - DEBUG - Event request-created.cloudtrail.CreateTrail: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f36791fed30>>
2020-10-28 08:04:07,596 - MainThread - botocore.hooks - DEBUG - Event choose-signer.cloudtrail.CreateTrail: calling handler <function set_operation_specific_signer at 0x7f367b7b9160>
2020-10-28 08:04:07,597 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2020-10-28 08:04:07,597 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-amz-json-1.1
host:cloudtrail.eu-central-1.amazonaws.com
x-amz-date:20201028T070407Z
x-amz-security-token:snip
x-amz-target:com.amazonaws.cloudtrail.v20131101.CloudTrail_20131101.CreateTrail

content-type;host;x-amz-date;x-amz-security-token;x-amz-target
fc7223f67d192fca639145c7eba1634cf04d277739e47a260e8567de4993e3de
2020-10-28 08:04:07,597 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20201028T070407Z
20201028/eu-central-1/cloudtrail/aws4_request
1e83999350193d09154cbcfbdf05ef1255f3b51ff0ee9478f2dc65e02438f59b
2020-10-28 08:04:07,597 - MainThread - botocore.auth - DEBUG - Signature:
abce53ab116a2344c0208ac2c7fd033350dbee9b9f7c2b92ed3275201e82679a
2020-10-28 08:04:07,597 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://cloudtrail.eu-central-1.amazonaws.com/, headers={'X-Amz-Target': b'com.amazonaws.cloudtrail.v20131101.CloudTrail_20131101.CreateTrail', 'Content-Type': b'application/x-amz-json-1.1', 'User-Agent': b'aws-cli/2.0.59 Python/3.9.0 Linux/5.4.0-52-generic source/x86_64.ubuntu.20 command/cloudtrail.create-trail', 'X-Amz-Date': b'20201028T070407Z',
'X-Amz-Security-Token': b'snip', 'Authorization': b'AWS4-HMAC-SHA256 Credential=snip/20201028/eu-central-1/cloudtrail/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-security-token;x-amz-target, Signature=snip', 'Content-Length': '166'}>
2020-10-28 08:04:07,597 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): cloudtrail.eu-central-1.amazonaws.com:443
2020-10-28 08:04:09,405 - MainThread - urllib3.connectionpool - DEBUG - https://cloudtrail.eu-central-1.amazonaws.com:443 "POST / HTTP/1.1" 500 28
2020-10-28 08:04:09,405 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-RequestId': '30bb0dc8-a787-499d-95cd-ba705d2bd116', 'Content-Type': 'application/x-amz-json-1.1', 'Content-Length': '28', 'Date': 'Wed, 28 Oct 2020 07:04:09 GMT', 'Connection': 'close'}
2020-10-28 08:04:09,405 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"__type":"InternalFailure"}'
2020-10-28 08:04:09,406 - MainThread - botocore.hooks - DEBUG - Event needs-retry.cloudtrail.CreateTrail: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x7f3678f5b6d0>>
2020-10-28 08:04:09,406 - MainThread - botocore.retries.standard - DEBUG - Retry needed, retrying request after delay of: 0.41055398210382055
2020-10-28 08:04:09,407 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.41055398210382055 seconds
2020-10-28 08:04:09,818 - MainThread - botocore.hooks - DEBUG - Event request-created.cloudtrail.CreateTrail: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f36791fed30>>
2020-10-28 08:04:09,818 - MainThread - botocore.hooks - DEBUG - Event choose-signer.cloudtrail.CreateTrail: calling handler <function set_operation_specific_signer at 0x7f367b7b9160>
2020-10-28 08:04:09,818 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2020-10-28 08:04:09,818 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-amz-json-1.1
host:cloudtrail.eu-central-1.amazonaws.com
x-amz-date:20201028T070409Z
x-amz-security-token:snip
x-amz-target:com.amazonaws.cloudtrail.v20131101.CloudTrail_20131101.CreateTrail

content-type;host;x-amz-date;x-amz-security-token;x-amz-target
fc7223f67d192fca639145c7eba1634cf04d277739e47a260e8567de4993e3de
2020-10-28 08:04:09,818 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20201028T070409Z
20201028/eu-central-1/cloudtrail/aws4_request
snip
2020-10-28 08:04:09,818 - MainThread - botocore.auth - DEBUG - Signature:
snip
2020-10-28 08:04:09,819 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://cloudtrail.eu-central-1.amazonaws.com/, headers={'X-Amz-Target': b'com.amazonaws.cloudtrail.v20131101.CloudTrail_20131101.CreateTrail', 'Content-Type': b'application/x-amz-json-1.1', 'User-Agent': b'aws-cli/2.0.59 Python/3.9.0 Linux/5.4.0-52-generic source/x86_64.ubuntu.20 command/cloudtrail.create-trail', 'X-Amz-Date': b'20201028T070409Z',
'X-Amz-Security-Token': b'snip', 'Authorization': b'AWS4-HMAC-SHA256 Credential=snip/20201028/eu-central-1/cloudtrail/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-security-token;x-amz-target, Signature=snip', 'Content-Length': '166'}>
2020-10-28 08:04:09,819 - MainThread - urllib3.connectionpool - DEBUG - Resetting dropped connection: cloudtrail.eu-central-1.amazonaws.com
2020-10-28 08:04:11,408 - MainThread - urllib3.connectionpool - DEBUG - https://cloudtrail.eu-central-1.amazonaws.com:443 "POST / HTTP/1.1" 500 28
2020-10-28 08:04:11,408 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-RequestId': '4990765e-f2d4-4cc2-a53d-ccebb9b59caa', 'Content-Type': 'application/x-amz-json-1.1', 'Content-Length': '28', 'Date': 'Wed, 28 Oct 2020 07:04:10 GMT', 'Connection': 'close'}
2020-10-28 08:04:11,408 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"__type":"InternalFailure"}'
2020-10-28 08:04:11,409 - MainThread - botocore.hooks - DEBUG - Event needs-retry.cloudtrail.CreateTrail: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x7f3678f5b6d0>>
2020-10-28 08:04:11,409 - MainThread - botocore.retries.standard - DEBUG - Retry needed, retrying request after delay of: 0.17090805719272284
2020-10-28 08:04:11,409 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.17090805719272284 seconds
2020-10-28 08:04:11,580 - MainThread - botocore.hooks - DEBUG - Event request-created.cloudtrail.CreateTrail: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f36791fed30>>
2020-10-28 08:04:11,580 - MainThread - botocore.hooks - DEBUG - Event choose-signer.cloudtrail.CreateTrail: calling handler <function set_operation_specific_signer at 0x7f367b7b9160>
2020-10-28 08:04:11,581 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2020-10-28 08:04:11,581 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-amz-json-1.1
host:cloudtrail.eu-central-1.amazonaws.com
x-amz-date:20201028T070411Z
x-amz-security-token:snip
x-amz-target:com.amazonaws.cloudtrail.v20131101.CloudTrail_20131101.CreateTrail

content-type;host;x-amz-date;x-amz-security-token;x-amz-target
snip
2020-10-28 08:04:11,581 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20201028T070411Z
20201028/eu-central-1/cloudtrail/aws4_request
snip
2020-10-28 08:04:11,581 - MainThread - botocore.auth - DEBUG - Signature:
9480ea70d60753d2932c72fc44f199223b58d1c02526b6f81af2c6b9c13fd427
2020-10-28 08:04:11,581 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://cloudtrail.eu-central-1.amazonaws.com/, headers={'X-Amz-Target': b'com.amazonaws.cloudtrail.v20131101.CloudTrail_20131101.CreateTrail', 'Content-Type': b'application/x-amz-json-1.1', 'User-Agent': b'aws-cli/2.0.59 Python/3.9.0 Linux/5.4.0-52-generic source/x86_64.ubuntu.20 command/cloudtrail.create-trail', 'X-Amz-Date': b'20201028T070411Z',
'X-Amz-Security-Token': b'snip', 'Authorization': b'AWS4-HMAC-SHA256 Credential=snip/20201028/eu-central-1/cloudtrail/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-security-token;x-amz-target, Signature=9480ea70d60753d2932c72fc44f199223b58d1c02526b6f81af2c6b9c13fd427', 'Content-Length': '166'}>
2020-10-28 08:04:11,581 - MainThread - urllib3.connectionpool - DEBUG - Resetting dropped connection: cloudtrail.eu-central-1.amazonaws.com
2020-10-28 08:04:12,246 - MainThread - urllib3.connectionpool - DEBUG - https://cloudtrail.eu-central-1.amazonaws.com:443 "POST / HTTP/1.1" 500 28
2020-10-28 08:04:12,246 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-RequestId': '21fbf6b6-985c-4a93-ba1b-97babfc626f1', 'Content-Type': 'application/x-amz-json-1.1', 'Content-Length': '28', 'Date': 'Wed, 28 Oct 2020 07:04:11 GMT', 'Connection': 'close'}
2020-10-28 08:04:12,247 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"__type":"InternalFailure"}'
2020-10-28 08:04:12,247 - MainThread - botocore.hooks - DEBUG - Event needs-retry.cloudtrail.CreateTrail: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x7f3678f5b6d0>>
2020-10-28 08:04:12,248 - MainThread - botocore.retries.standard - DEBUG - Max attempts of 3 reached.
2020-10-28 08:04:12,248 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2020-10-28 08:04:12,248 - MainThread - botocore.hooks - DEBUG - Event after-call.cloudtrail.CreateTrail: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x7f3678f5b250>>
2020-10-28 08:04:12,249 - MainThread - awscli.clidriver - DEBUG - Service returned an exception
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.0.59/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 386, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.0.59/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 558, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.0.59/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 735, in __call__
    return self._operation_caller.invoke(
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.0.59/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 866, in invoke
    response = self._make_client_call(
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.0.59/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 878, in _make_client_call
    response = getattr(client, xform_name(operation_name))(
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.0.59/libexec/lib/python3.9/site-packages/botocore/client.py", line 249, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.0.59/libexec/lib/python3.9/site-packages/botocore/client.py", line 568, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InternalFailure) when calling the CreateTrail operation (reached max retries: 2): 

An error occurred (InternalFailure) when calling the CreateTrail operation (reached max retries: 2): 
</pre>
</details>

**Comment by anarsen** [comment]
I solved the mystery.

I MFA'ed and then it went through. Probably worth looking into the `InternalFailure` error code on the AWS API side though. If anyone knows who would want to know this, please do comment.

**Comment by kdaily** [comment]
Hi @anarsen ,

Thanks for the report. I'll pass this information on to the CloudTrail team.

**Comment by tim-finnigan** [comment]
Checking in as this issue hasn't had any activity since 2020. @anarsen we generally now recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) for API-related issues. That way it is easier for directing requests to the appropriate team as well as for tracking on your end. Support teams could also help look into account-specific errors. It sounds like this was a permissions issue that was resolved so I don't know if there's anything here remaining for the CLI to track. But if there's anything you wanted to clarify or expand on please let us know and we can revisit this issue.
