### ISSUE TITLE
CLI error for QuickSight Dashboard with Japanese Sheet Names

### ISSUE THREAD

**Issue by tb102122** [aws/aws-cli#5800]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Create QuickSight Dashboard via the AWS Console with calling the AWS CLI with the command:
```aws quicksight describe-dashboard --aws-account-id <account-id> --dashboard-id <dashboard-id> --profile <profile>```

Results in the error: 
```'charmap' codec can't encode characters in position 1-2: character maps to <undefined>```

![image](https://user-images.githubusercontent.com/62531735/101572389-234aaa80-3a2c-11eb-90ed-4b3833db5749.png)

**SDK version number**
aws-cli/2.1.8 Python/3.7.9 Windows/10 exe/AMD64 prompt/off

**Comment by kdaily** [comment]
Hi @tb102122,

This is generally an issue with Unicode on windows in the command line, which is not well supported. You'll likely need to make an OS change. If you provide the output of running this command with the `--debug` parameter on, it would help confirm. Here's a comment on a similar issue in the past that could help:

https://github.com/aws/aws-cli/issues/4778#issuecomment-667439727

**Comment by tb102122** [comment]
Hey @kdaily,

find below the output of the debug log.

`2020-12-15 13:42:54,385 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.8 Python/3.7.9 Windows/10 exe/AMD64
2020-12-15 13:42:54,385 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['quicksight', 'describe-dashboard', '--aws-account-id', 'XXX', '--profile', 'XXX', '--dashboard-id', 'XXX', '--debug']
2020-12-15 13:42:54,454 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x0000022001E01A68>
2020-12-15 13:42:54,454 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x00000220014689D8>
2020-12-15 13:42:54,455 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2020-12-15 13:42:54,455 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x0000022001411798>
2020-12-15 13:42:54,455 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x0000022001415EE8>
2020-12-15 13:42:54,455 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x0000022001E0EB88>
2020-12-15 13:42:54,456 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x00000220014B4AF8>
2020-12-15 13:42:54,456 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2020-12-15 13:42:54,456 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x0000022001E12168>
2020-12-15 13:42:54,457 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\awscli\data\cli.json
2020-12-15 13:42:54,460 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x0000022001D6CD38>
2020-12-15 13:42:54,460 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x0000022001D71048>
2020-12-15 13:42:54,461 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x0000022001D6CF78>
2020-12-15 13:42:54,461 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x0000022001D71168>
2020-12-15 13:42:54,461 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x0000022001D710D8>
2020-12-15 13:42:54,461 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x0000022001E90F98>
2020-12-15 13:42:54,462 - MainThread - botocore.session - DEBUG - Setting config variable for profile to 'bmwjp-dev'
2020-12-15 13:42:54,462 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.8 Python/3.7.9 Windows/10 exe/AMD64 prompt/off
2020-12-15 13:42:54,463 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['quicksight', 'describe-dashboard', '--aws-account-id', 'XXX', '--profile', 'XXX', '--dashboard-id', 'XXX', '--debug']
2020-12-15 13:42:54,463 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x0000022001E05678>
2020-12-15 13:42:54,463 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x0000022001212948>
2020-12-15 13:42:54,464 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x0000022001E49B88>
2020-12-15 13:42:54,464 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x00000220011BE1F8>
2020-12-15 13:42:54,465 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x000002200123E048>
2020-12-15 13:42:54,468 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2020-12-15 13:42:54,476 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2020-12-15 13:42:54,477 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x00000220014B4B88>
2020-12-15 13:42:54,477 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x0000022001459CA8>
2020-12-15 13:42:54,544 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\botocore\data\quicksight\2018-04-01\service-2.json
2020-12-15 13:42:54,563 - MainThread - botocore.hooks - DEBUG - Event building-command-table.quicksight: calling handler <function add_waiters at 0x0000022001E12168>
2020-12-15 13:42:54,618 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('aws-account-id', <awscli.arguments.CLIArgument object at 0x000002200212DE88>), ('dashboard-id', <awscli.arguments.CLIArgument object at 0x000002200212DF08>), ('version-number', <awscli.arguments.CLIArgument object at 0x000002200212DF88>), ('alias-name', <awscli.arguments.CLIArgument object at 0x0000022002104D88>)])
2020-12-15 13:42:54,618 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.quicksight.describe-dashboard: calling handler <function add_streaming_output_arg at 0x0000022001E07828>
2020-12-15 13:42:54,621 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.quicksight.describe-dashboard: calling handler <function add_cli_input_json at 0x0000022001223A68>
2020-12-15 13:42:54,621 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.quicksight.describe-dashboard: calling handler <function add_cli_input_yaml at 0x0000022001223CA8>
2020-12-15 13:42:54,624 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.quicksight.describe-dashboard: calling handler <function unify_paging_params at 0x0000022001473CA8>
2020-12-15 13:42:54,690 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\botocore\data\quicksight\2018-04-01\paginators-1.json
2020-12-15 13:42:54,691 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.quicksight.describe-dashboard: calling handler <function add_generate_skeleton at 0x0000022001D65D38>
2020-12-15 13:42:54,692 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.quicksight.describe-dashboard: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x000002200212DFC8>>
2020-12-15 13:42:54,694 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.quicksight.describe-dashboard: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x0000022002128188>>
2020-12-15 13:42:54,695 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.quicksight.describe-dashboard: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x0000022002135D08>>
2020-12-15 13:42:54,697 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.describe-dashboard.aws-account-id: calling handler <awscli.paramfile.URIArgumentHandler object at 0x0000022001EE64C8>
2020-12-15 13:42:54,697 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.quicksight.describe-dashboard: calling handler <awscli.argprocess.ParamShorthandParser object at 0x00000220012138C8>
2020-12-15 13:42:54,698 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'XXX' for parameter "aws_account_id": 'XXX'
2020-12-15 13:42:54,698 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.describe-dashboard.dashboard-id: calling handler <awscli.paramfile.URIArgumentHandler object at 0x0000022001EE64C8>
2020-12-15 13:42:54,699 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.quicksight.describe-dashboard: calling handler <awscli.argprocess.ParamShorthandParser object at 0x00000220012138C8>
2020-12-15 13:42:54,700 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'XXX' for parameter "dashboard_id": 'XXX'
2020-12-15 13:42:54,700 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.describe-dashboard.version-number: calling handler <awscli.paramfile.URIArgumentHandler object at 0x0000022001EE64C8>
2020-12-15 13:42:54,701 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.describe-dashboard.alias-name: calling handler <awscli.paramfile.URIArgumentHandler object at 0x0000022001EE64C8>
2020-12-15 13:42:54,701 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.describe-dashboard.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x0000022001EE64C8>
2020-12-15 13:42:54,702 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.describe-dashboard.cli-input-yaml: calling handler <awscli.paramfile.URIArgumentHandler object at 0x0000022001EE64C8>
2020-12-15 13:42:54,703 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.describe-dashboard.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x0000022001EE64C8>
2020-12-15 13:42:54,708 - MainThread - botocore.hooks - DEBUG - Event calling-command.quicksight.describe-dashboard: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x000002200212DFC8>>
2020-12-15 13:42:54,710 - MainThread - botocore.hooks - DEBUG - Event calling-command.quicksight.describe-dashboard: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x0000022002128188>>
2020-12-15 13:42:54,710 - MainThread - botocore.hooks - DEBUG - Event calling-command.quicksight.describe-dashboard: calling handler <bound method GenerateCliSkeletonArgument.generate_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x0000022002135D08>>
2020-12-15 13:42:54,712 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2020-12-15 13:42:54,712 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2020-12-15 13:42:54,713 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2020-12-15 13:42:54,714 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2020-12-15 13:42:54,715 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2020-12-15 13:42:54,716 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\botocore\data\endpoints.json
2020-12-15 13:42:54,725 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x00000220009CEE58>
2020-12-15 13:42:54,728 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.quicksight: calling handler <function add_generate_presigned_url at 0x00000220009608B8>
2020-12-15 13:42:54,729 - MainThread - botocore.regions - DEBUG - Creating a regex based endpoint for quicksight, ap-northeast-1
2020-12-15 13:42:54,731 - MainThread - botocore.endpoint - DEBUG - Setting quicksight timeout as (60, 60)
2020-12-15 13:42:54,733 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.quicksight.DescribeDashboard: calling handler <function base64_decode_input_blobs at 0x0000022001E49C18>
2020-12-15 13:42:54,733 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.quicksight.DescribeDashboard: calling handler <function generate_idempotent_uuid at 0x00000220009D8AF8>
2020-12-15 13:42:54,734 - MainThread - botocore.hooks - DEBUG - Event before-call.quicksight.DescribeDashboard: calling handler <function inject_api_version_header_if_needed at 0x00000220009DD3A8>
2020-12-15 13:42:54,734 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=DescribeDashboard) with params: {'url_path': '/accounts/XXX/dashboards/XXX', 'query_string': {}, 'method': 'GET', 'headers': {'User-Agent': 'aws-cli/2.1.8 Python/3.7.9 Windows/10 exe/AMD64 prompt/off command/quicksight.describe-dashboard'}, 'body': b'', 'url': 'https://quicksight.ap-northeast-1.amazonaws.com/accounts/XXX/dashboards/XXX', 'context': {'client_region': 'ap-northeast-1', 'client_config': <botocore.config.Config object at 0x00000220023E28C8>, 'has_streaming_input': False, 'auth_type': None}}
2020-12-15 13:42:54,735 - MainThread - botocore.hooks - DEBUG - Event request-created.quicksight.DescribeDashboard: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x0000022002393D08>>
2020-12-15 13:42:54,739 - MainThread - botocore.hooks - DEBUG - Event choose-signer.quicksight.DescribeDashboard: calling handler <function set_operation_specific_signer at 0x00000220009CCB88>
2020-12-15 13:42:54,741 - MainThread - botocore.credentials - DEBUG - Credentials for role retrieved from cache.
2020-12-15 13:42:54,743 - MainThread - botocore.credentials - DEBUG - Retrieved credentials will expire at: 2020-12-15 03:42:27+00:00
2020-12-15 13:42:54,744 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2020-12-15 13:42:54,744 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
GET
/accounts/XXX/dashboards/XXX

host:quicksight.ap-northeast-1.amazonaws.com
x-amz-date:20201215T024254Z
x-amz-security-token:XXX

host;x-amz-date;x-amz-security-token
XXX
2020-12-15 13:42:54,745 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20201215T024254Z
20201215/ap-northeast-1/quicksight/aws4_request
4216165535a90d202fd8b2f51c78c247e7b4cca72c9a81993044b5f1ba3f5b8d
2020-12-15 13:42:54,746 - MainThread - botocore.auth - DEBUG - Signature:
df4890ed3a1e295daf4b51aa21fa9595cccaf3b2b7293ced63c1f2ca1c6517bd
2020-12-15 13:42:54,747 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=GET, url=https://quicksight.ap-northeast-1.amazonaws.com/accounts/XXX/dashboards/XXX, headers={'User-Agent': b'aws-cli/2.1.8 Python/3.7.9 Windows/10 exe/AMD64 prompt/off command/quicksight.describe-dashboard', 'X-Amz-Date': b'20201215T024254Z', 'X-Amz-Security-Token': b'XXX', 'Authorization': b'AWS4-HMAC-SHA256 Credential=XXX/20201215/ap-northeast-1/quicksight/aws4_request, SignedHeaders=host;x-amz-date;x-amz-security-token, Signature=XXX'}>
2020-12-15 13:42:54,748 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): quicksight.ap-northeast-1.amazonaws.com:443
2020-12-15 13:42:56,022 - MainThread - urllib3.connectionpool - DEBUG - https://quicksight.ap-northeast-1.amazonaws.com:443 "GET /accounts/XXX/dashboards/XXX HTTP/1.1" 200 1957
2020-12-15 13:42:56,023 - MainThread - botocore.parsers - DEBUG - Response headers: {'Date': 'Tue, 15 Dec 2020 02:42:55 GMT', 'Content-Type': 'application/json', 'Content-Length': '1957', 'Connection': 'keep-alive', 'x-amzn-RequestId': '51a4398e-1860-4584-a0fb-cc776ad760b4'}
2020-12-15 13:42:56,025 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"Dashboard":{"Arn":"arn:aws:quicksight:ap-northeast-1:XXX:dashboard/XXX","CreatedTime":1.607054943798E9,"DashboardId":"XXX","LastPublishedTime":1.607054943798E9,"LastUpdatedTime":1.608000080363E9,"Name":"XXX","Version":{"Arn":null,"CreatedTime":1.608000080363E9,"DataSetArns":["arn:aws:quicksight:ap-northeast-1:XXX:dataset/XXX","arn:aws:quicksight:ap-northeast-1:XXX:dataset/XXX","arn:aws:quicksight:ap-northeast-1:XXX:dataset/XXX"],"Description":null,"Errors":[],"Sheets":[{"Name":"\xe3\x83\xaa\xe3\x83\x9d\xe3\x83\xbc\xe3\x83\x88\xe7\x9b\xae\xe6\xac\xa1 / 00 - Start","SheetId":"XXX_6801bf88-c6e9-410e-ab71-b1297a064f30"},{"Name":"01 - Overview","SheetId":"XXX_efbdf483-29a2-449f-abe2-42e7fd34fa5e"},{"Name":"02 - Dealer Map","SheetId":"XXX_8c8f29d1-d904-452f-8149-aa3d5875c4bd"},{"Name":"03 - Dealer Overview","SheetId":"XXX_c31e88d4-d7a9-4414-a7e4-32e617586e80"},{"Name":"04 - Dealer Details","SheetId":"XXX_a02f71e7-dc0d-40cc-8592-8f48b6099387"},{"Name":"05 - Model Details","SheetId":"XXX_c5b54e71-dec5-461f-8d66-1e129dbd69a2"},{"Name":"06 - Case Details","SheetId":"XXX_957ee0a8-ea50-4495-aa7e-7d30114bf9dd"},{"Name":"07 - Campaign Models","SheetId":"XXX_6577f40c-946a-42a0-8850-6562ecac1afb"},{"Name":"08 - Trend","SheetId":"XXX_8916a355-98ca-44c2-9564-70fe0d03085f"}],"SourceEntityArn":"arn:aws:quicksight:ap-northeast-1:XXX:analysis/1ee427f3-8126-4bc5-9233-6abb413f27ee","Status":null,"ThemeArn":null,"VersionNumber":10}},"RequestId":"51a4398e-1860-4584-a0fb-cc776ad760b4"}'
2020-12-15 13:42:56,030 - MainThread - botocore.hooks - DEBUG - Event needs-retry.quicksight.DescribeDashboard: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x00000220023E9408>>
2020-12-15 13:42:56,030 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2020-12-15 13:42:56,031 - MainThread - botocore.hooks - DEBUG - Event after-call.quicksight.DescribeDashboard: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x00000220023E2D08>>
2020-12-15 13:42:56,038 - MainThread - awscli.formatter - DEBUG - RequestId: 51a4398e-1860-4584-a0fb-cc776ad760b4
{
    "Status": 200,
    "Dashboard": {
        "DashboardId": "XXX",
        "Arn": "arn:aws:quicksight:ap-northeast-1:XXX:dashboard/XXX",
        "Name": "bmwjp-si-case-analysis",
        "Version": {
            "CreatedTime": "2020-12-15T13:41:20.363000+11:00",
            "Errors": [],
            "VersionNumber": 10,
            "SourceEntityArn": "arn:aws:quicksight:ap-northeast-1:XXX:analysis/1ee427f3-8126-4bc5-9233-6abb413f27ee",
            "DataSetArns": [
                "arn:aws:quicksight:ap-northeast-1:XXX:dataset/XXX",
                "arn:aws:quicksight:ap-northeast-1:XXX:dataset/XXX",
                "arn:aws:quicksight:ap-northeast-1:XXX:dataset/XXX"
            ],
            "Sheets": [
                {
                    "SheetId": "XXX_6801bf88-c6e9-410e-ab71-b1297a064f30",
                    "Name":
2020-12-15 13:42:56,078 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "lib\site-packages\awscli\clidriver.py", line 457, in main
  File "lib\site-packages\awscli\clidriver.py", line 586, in __call__
  File "lib\site-packages\awscli\clidriver.py", line 765, in __call__
  File "lib\site-packages\awscli\clidriver.py", line 895, in invoke
  File "lib\site-packages\awscli\clidriver.py", line 917, in _display_response
  File "lib\site-packages\awscli\formatter.py", line 88, in __call__
  File "lib\site-packages\awscli\formatter.py", line 108, in _format_response
  File "json\__init__.py", line 180, in dump
  File "C:\Python\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1-6: character maps to <undefined>

'charmap' codec can't encode characters in position 1-6: character maps to <undefined>`

**Comment by tb102122** [comment]
Hey @kdaily ,

after updating the setting based on the following suggestion [https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window/57134096#57134096](https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window/57134096#57134096) the command can be executed without problem.

![image](https://user-images.githubusercontent.com/62531735/102162732-d0ff0300-3edd-11eb-88e8-89b9b49887b3.png)
