### ISSUE TITLE
cognito-idp list-resource-servers parameter --max-results is missing from output

### ISSUE THREAD

**Issue by mntlty** [aws/aws-cli#5843]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
The documentation for `aws cognito-idp list-resource-servers` is incorrect in both the `help` command and at https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cognito-idp/list-resource-servers.html

There is a required parameter called `max-results` which is not listed anywhere, and when this value is not provided the api call fails with InvalidParameterException. There is a parameter in the documentation called `max-items` which is not taken for `max-results`

**SDK version number**
aws-cli/2.0.0 Python/3.7.4 Darwin/19.6.0 botocore/2.0.0dev4

**Platform/OS/Hardware/Device**
OS X Catalina 10.15.7

**To Reproduce (observed behavior)**
 When executing the command without it `aws cognito-idp list-resource-servers --user-pool-id $POOL_ID` the following error is returned

> An error occurred (InvalidParameterException) when calling the ListResourceServers operation: 1 validation error detected: Value '0' at 'maxResults' failed to satisfy constraint: Member must have value greater than or equal to 1

Note also that the parameter here is `maxResults` however in the cli it must be `max-results` for the call to succeed.

**Expected behavior**
The api call should list the correct names for the parameters and specify that `max-results` is a required field.

**Logs/output**
```sh
2020-12-24 13:55:51,070 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.0.0 Python/3.7.4 Darwin/19.6.0 botocore/2.0.0dev4
2020-12-24 13:55:51,070 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['cognito-idp', 'list-resource-servers', '--user-pool-id', 'us-west-2_mcIMsC1b2', '--debug']
2020-12-24 13:55:51,070 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7f88021fecb0>
2020-12-24 13:55:51,070 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7f8800faa290>
2020-12-24 13:55:51,070 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7f880224b5f0>
2020-12-24 13:55:51,070 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f88011119e0>
2020-12-24 13:55:51,077 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f88020b3a70>
2020-12-24 13:55:51,077 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7f8802054710>
2020-12-24 13:55:51,093 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/botocore/data/cognito-idp/2016-04-18/service-2.json
2020-12-24 13:55:51,110 - MainThread - botocore.hooks - DEBUG - Event building-command-table.cognito-idp: calling handler <function add_waiters at 0x7f880220d8c0>
2020-12-24 13:55:51,124 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('user-pool-id', <awscli.arguments.CLIArgument object at 0x7f880274e310>), ('max-results', <awscli.arguments.CLIArgument object at 0x7f880274e850>), ('next-token', <awscli.arguments.CLIArgument object at 0x7f880274e910>)])
2020-12-24 13:55:51,124 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cognito-idp.list-resource-servers: calling handler <function add_streaming_output_arg at 0x7f8802204e60>
2020-12-24 13:55:51,124 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cognito-idp.list-resource-servers: calling handler <function add_cli_input_json at 0x7f8801117c20>
2020-12-24 13:55:51,124 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cognito-idp.list-resource-servers: calling handler <function add_cli_input_yaml at 0x7f8801117440>
2020-12-24 13:55:51,125 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cognito-idp.list-resource-servers: calling handler <function unify_paging_params at 0x7f8802073d40>
2020-12-24 13:55:51,150 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/botocore/data/cognito-idp/2016-04-18/paginators-1.json
2020-12-24 13:55:51,151 - MainThread - awscli.customizations.paginate - DEBUG - Modifying paging parameters for operation: ListResourceServers
2020-12-24 13:55:51,151 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cognito-idp.list-resource-servers: calling handler <function add_generate_skeleton at 0x7f880215eb90>
2020-12-24 13:55:51,151 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cognito-idp.list-resource-servers: calling handler <function add_auto_prompt at 0x7f88022497a0>
2020-12-24 13:55:51,151 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cognito-idp.list-resource-servers: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7f880274e3d0>>
2020-12-24 13:55:51,151 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cognito-idp.list-resource-servers: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7f880274e9d0>>
2020-12-24 13:55:51,151 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cognito-idp.list-resource-servers: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f880275f410>>
2020-12-24 13:55:51,151 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cognito-idp.list-resource-servers: calling handler <bound method AutoPromptArgument.override_required_args of <awscli.customizations.autoprompt.AutoPromptArgument object at 0x7f880275f310>>
2020-12-24 13:55:51,152 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.cognito-idp.list-resource-servers: calling handler functools.partial(<function check_should_enable_pagination at 0x7f8802073e60>, ['next-token', 'max-results'], {}, OrderedDict([('user-pool-id', <awscli.arguments.CLIArgument object at 0x7f880274e310>), ('max-results', <awscli.arguments.CLIArgument object at 0x7f880274e850>), ('next-token', <awscli.arguments.CLIArgument object at 0x7f880274e910>), ('cli-input-json', <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7f880274e3d0>), ('cli-input-yaml', <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7f880274e9d0>), ('starting-token', <awscli.customizations.paginate.PageArgument object at 0x7f8802751210>), ('page-size', <awscli.customizations.paginate.PageArgument object at 0x7f8801732d50>), ('max-items', <awscli.customizations.paginate.PageArgument object at 0x7f880275f150>), ('generate-cli-skeleton', <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f880275f410>), ('cli-auto-prompt', <awscli.customizations.autoprompt.AutoPromptArgument object at 0x7f880275f310>)]))
2020-12-24 13:55:51,153 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cognito-idp.list-resource-servers.user-pool-id: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f88022d5f10>
2020-12-24 13:55:51,153 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.cognito-idp.list-resource-servers: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f8800fa2190>
2020-12-24 13:55:51,153 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'us-west-2_mcIMsC1b2' for parameter "user_pool_id": 'us-west-2_mcIMsC1b2'
2020-12-24 13:55:51,153 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cognito-idp.list-resource-servers.max-results: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f88022d5f10>
2020-12-24 13:55:51,153 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cognito-idp.list-resource-servers.next-token: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f88022d5f10>
2020-12-24 13:55:51,153 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cognito-idp.list-resource-servers.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f88022d5f10>
2020-12-24 13:55:51,153 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cognito-idp.list-resource-servers.cli-input-yaml: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f88022d5f10>
2020-12-24 13:55:51,153 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cognito-idp.list-resource-servers.starting-token: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f88022d5f10>
2020-12-24 13:55:51,153 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cognito-idp.list-resource-servers.page-size: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f88022d5f10>
2020-12-24 13:55:51,153 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cognito-idp.list-resource-servers.max-items: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f88022d5f10>
2020-12-24 13:55:51,153 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cognito-idp.list-resource-servers.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f88022d5f10>
2020-12-24 13:55:51,153 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cognito-idp.list-resource-servers.cli-auto-prompt: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f88022d5f10>
2020-12-24 13:55:51,153 - MainThread - botocore.hooks - DEBUG - Event calling-command.cognito-idp.list-resource-servers: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7f880274e3d0>>
2020-12-24 13:55:51,153 - MainThread - botocore.hooks - DEBUG - Event calling-command.cognito-idp.list-resource-servers: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7f880274e9d0>>
2020-12-24 13:55:51,153 - MainThread - botocore.hooks - DEBUG - Event calling-command.cognito-idp.list-resource-servers: calling handler <bound method GenerateCliSkeletonArgument.generate_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f880275f410>>
2020-12-24 13:55:51,153 - MainThread - botocore.hooks - DEBUG - Event calling-command.cognito-idp.list-resource-servers: calling handler <bound method AutoPromptArgument.auto_prompt_arguments of <awscli.customizations.autoprompt.AutoPromptArgument object at 0x7f880275f310>>
2020-12-24 13:55:51,153 - MainThread - botocore.hooks - DEBUG - Event calling-command.cognito-idp.list-resource-servers: calling handler functools.partial(<function check_should_enable_pagination_call_parameters at 0x7f8802076290>, ['NextToken', 'MaxResults'])
2020-12-24 13:55:51,154 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2020-12-24 13:55:51,154 - MainThread - botocore.credentials - INFO - Found credentials in environment variables.
2020-12-24 13:55:51,155 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/botocore/data/endpoints.json
2020-12-24 13:55:51,159 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f8800a09170>
2020-12-24 13:55:51,161 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.cognito-identity-provider: calling handler <function add_generate_presigned_url at 0x7f88009bdef0>
2020-12-24 13:55:51,165 - MainThread - botocore.endpoint - DEBUG - Setting cognito-idp timeout as (60, 60)
2020-12-24 13:55:51,169 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.cognito-identity-provider.ListResourceServers: calling handler <function base64_decode_input_blobs at 0x7f880224b680>
2020-12-24 13:55:51,169 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.cognito-identity-provider.ListResourceServers: calling handler <function generate_idempotent_uuid at 0x7f8800a0ddd0>
2020-12-24 13:55:51,169 - MainThread - botocore.hooks - DEBUG - Event before-call.cognito-identity-provider.ListResourceServers: calling handler <function inject_api_version_header_if_needed at 0x7f8800a118c0>
2020-12-24 13:56:02,908 - MainThread - awscli.clidriver - DEBUG - Service returned an exception
Traceback (most recent call last):
  File "awscli/clidriver.py", line 335, in main
  File "awscli/clidriver.py", line 507, in __call__
  File "awscli/clidriver.py", line 685, in __call__
  File "awscli/clidriver.py", line 807, in invoke
  File "awscli/clidriver.py", line 829, in _display_response
  File "awscli/formatter.py", line 82, in __call__
  File "botocore/paginate.py", line 449, in build_full_result
  File "botocore/paginate.py", line 255, in __iter__
  File "botocore/paginate.py", line 332, in _make_request
  File "botocore/client.py", line 201, in _api_call
  File "botocore/client.py", line 511, in _make_api_call
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the ListResourceServers operation: 1 validation error detected: Value '0' at 'maxResults' failed to satisfy constraint: Member must have value greater than or equal to 1

An error occurred (InvalidParameterException) when calling the ListResourceServers operation: 1 validation error detected: Value '0' at 'maxResults' failed to satisfy constraint: Member must have value greater than or equal to 1
```

**Additional context**

**Comment by rrhodes** [comment]
Reading a [similar issue](https://github.com/aws/aws-cli/issues/3866) for Cognito IDP, it sounds like this requires escalations to an internal AWS team because the logic does not sit in the CLI. Until this is resolved, you can explicitly provide `--max-results` with a positive number.

**Comment by kdaily** [comment]
Hi @mntlty, 

@rrhodes is correct - marking this as a duplicate. I will check up on the status of the internal team request on #3866.

**Comment by mntlty** [comment]
@kdaily @rrhodes aside from the parameter being optional, there is the issue with how it is named in the documentation and the output of the cli.

according to https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cognito-idp/list-resource-servers.html there is a field called `--max-items`. the same name is given with `aws cognito-idp list-resource-servers help`

clicking on the link at the top for the aws documentation https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ListResourceServers.html the field is called `"MaxResults"` which would presumably be turned into `--max-results` but not `--max-items`

the documentation on the web and the cli cannot be updated to at least match the expected field name so that the error refers to a known field name? the words items and results may be similar but they are not the same.

**Comment by kdaily** [comment]
Hi @mntlty,

This is because the AWS CLI unifies pagination options across services. In order to provide the same experience for all APIs, the CLI provides the parameter `max-items` regardless of what the service names it. In this case, the service calls it `MaxResults` (which does get turned into a valid AWS CLI parameter of `max-results`, but is not displayed). When a user provides `max-items` to this call it gets mapped to the `max-results` when sent in the request. Pagination is modeled (and configured for the CLI to use) in the `botocore` package - you can see this particular one here:

https://github.com/boto/botocore/blob/develop/botocore/data/cognito-idp/2016-04-18/paginators-1.json#L27-L32

You should never even have to see or worry about `MaxResults` (or `max-results`). What it looks like is that it's not optional and has a minimum value of 1 - the CLI is now not able to handle all of the pagination for you.

Hope this makes sense! I'd be happy to follow up if you have any further comments or questions.

**Comment by mntlty** [comment]
@kdaily thanks for the context, it helps. If I understand what you wrote 
> When a user provides max-items to this call it gets mapped to the max-results when sent in the request

then `--max-items` or `--max-results` with a non-zero value would allow the call to succeed, which is not the case.

A non-zero value for `--max-items` still results in the error
`An error occurred (InvalidParameterException) when calling the ListResourceServers operation: 1 validation error detected: Value '0' at 'maxResults' failed to satisfy constraint: Member must have value greater than or equal to 1`
The same call with `--max-results` works as expected.

**Comment by kdaily** [comment]
@mntlty - thanks for the details, I'll look into it some more. It does appear that this is a client-side error, as no request is logged.

**Comment by kdaily** [comment]
Hi @mntlty - it looks like you might have redacted out the request logs - is there any way you can include a sanitized version of those? There should be some more statements between these two lines that would be useful to indicate the issue:

```
2020-12-24 13:55:51,169 - MainThread - botocore.hooks - DEBUG - Event before-call.cognito-identity-provider.ListResourceServers: calling handler <function inject_api_version_header_if_needed at 0x7f8800a118c0>
2020-12-24 13:56:02,908 - MainThread - awscli.clidriver - DEBUG - Service returned an exception
```
