### ISSUE TITLE
`executionRoleArn` and `secrets` do not work for `batch register-job-definition`

### ISSUE THREAD

**Issue by mfly** [aws/aws-cli#5846]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Setting `executionRoleArn` and secrets for AWS Batch JobDefinition only works through the web console and fails on `aws-cli`.

**SDK version number**
```
$ aws --version
aws-cli/2.0.9 Python/3.7.3 Linux/5.4.0-58-generic botocore/2.0.0dev13
```

**Platform/OS/Hardware/Device**
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
```

**To Reproduce (observed behavior)**
```
$ aws batch register-job-definition --job-definition-name test-env-cli --type container --container-properties '{"command":["env"],"image":"amazonlinux","vcpus":1,"memory":2048,"executionRoleArn":"arn:aws:iam::x:role/x","secrets":[{"name":"APP_HOST","valueFrom":"arn:aws:ssm:eu-central-1:x:parameter/x"}]}'

Parameter validation failed:
Unknown parameter in containerProperties: "executionRoleArn", must be one of: image, vcpus, memory, command, jobRoleArn, volumes, environment, mountPoints, readonlyRootFilesystem, privileged, ulimits, user, instanceType, resourceRequirements, linuxParameters
Unknown parameter in containerProperties: "secrets", must be one of: image, vcpus, memory, command, jobRoleArn, volumes, environment, mountPoints, readonlyRootFilesystem, privileged, ulimits, user, instanceType, resourceRequirements, linuxParameters

```
**Expected behavior**
Job definition is created with the provided `executionRole` and `secrets`

**Logs/output**
```
2020-12-29 13:21:46,384 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.0.9 Python/3.7.3 Linux/5.4.0-58-generic botocore/2.0.0dev13
2020-12-29 13:21:46,385 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['batch', 'register-job-definition', '--job-definition-name', 'test-env-cli', '--type', 'container', '--container-properties', '{"command":["env"],"image":"amazonlinux","vcpus":1,"memory":2048,"executionRoleArn":"arn:aws:iam::146902639458:role/route-optimizer-staging-batch-execution-2b9b889","secrets":[{"name":"APP_HOST","valueFrom":"arn:aws:ssm:eu-central-1:146902639458:parameter/route-optimizer/staging/env/APP_HOST"}]}', '--debug']
2020-12-29 13:21:46,385 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7fa7bf80dbf8>
2020-12-29 13:21:46,385 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7fa7c00f1268>
2020-12-29 13:21:46,385 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7fa7bf7d90d0>
2020-12-29 13:21:46,385 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7fa7c011b378>
2020-12-29 13:21:46,387 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7fa7bf958950>
2020-12-29 13:21:46,387 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7fa7bf993378>
2020-12-29 13:21:46,393 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.0.9/dist/botocore/data/batch/2016-08-10/service-2.json
2020-12-29 13:21:46,396 - MainThread - botocore.hooks - DEBUG - Event building-command-table.batch: calling handler <function add_waiters at 0x7fa7bf8190d0>
2020-12-29 13:21:46,399 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('job-definition-name', <awscli.arguments.CLIArgument object at 0x7fa7bf674c50>), ('type', <awscli.arguments.CLIArgument object at 0x7fa7bf674d68>), ('parameters', <awscli.arguments.CLIArgument object at 0x7fa7bf674da0>), ('container-properties', <awscli.arguments.CLIArgument object at 0x7fa7bf674dd8>), ('node-properties', <awscli.arguments.CLIArgument object at 0x7fa7bf674cc0>), ('retry-strategy', <awscli.arguments.CLIArgument object at 0x7fa7bf674ef0>), ('timeout', <awscli.arguments.CLIArgument object at 0x7fa7bf674e80>)])
2020-12-29 13:21:46,399 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.batch.register-job-definition: calling handler <function add_streaming_output_arg at 0x7fa7bf80dea0>
2020-12-29 13:21:46,399 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.batch.register-job-definition: calling handler <function add_cli_input_json at 0x7fa7c011bb70>
2020-12-29 13:21:46,399 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.batch.register-job-definition: calling handler <function add_cli_input_yaml at 0x7fa7c0123268>
2020-12-29 13:21:46,400 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.batch.register-job-definition: calling handler <function unify_paging_params at 0x7fa7bf988a60>
2020-12-29 13:21:46,403 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.0.9/dist/botocore/data/batch/2016-08-10/paginators-1.json
2020-12-29 13:21:46,403 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.batch.register-job-definition: calling handler <function add_generate_skeleton at 0x7fa7bf873598>
2020-12-29 13:21:46,403 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.batch.register-job-definition: calling handler <function add_auto_prompt at 0x7fa7bf7d9048>
2020-12-29 13:21:46,403 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.batch.register-job-definition: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7fa7bf674fd0>>
2020-12-29 13:21:46,403 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.batch.register-job-definition: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7fa7bf6c7400>>
2020-12-29 13:21:46,403 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.batch.register-job-definition: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fa7bf676048>>
2020-12-29 13:21:46,403 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.batch.register-job-definition: calling handler <bound method AutoPromptArgument.override_required_args of <awscli.customizations.autoprompt.AutoPromptArgument object at 0x7fa7bf684358>>
2020-12-29 13:21:46,404 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.batch.register-job-definition.job-definition-name: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fa7bf754be0>
2020-12-29 13:21:46,404 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.batch.register-job-definition: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fa7c0166cf8>
2020-12-29 13:21:46,404 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'test-env-cli' for parameter "job_definition_name": 'test-env-cli'
2020-12-29 13:21:46,404 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.batch.register-job-definition.type: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fa7bf754be0>
2020-12-29 13:21:46,404 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.batch.register-job-definition: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fa7c0166cf8>
2020-12-29 13:21:46,404 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'container' for parameter "type": 'container'
2020-12-29 13:21:46,404 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.batch.register-job-definition.parameters: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fa7bf754be0>
2020-12-29 13:21:46,404 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.batch.register-job-definition.container-properties: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fa7bf754be0>
2020-12-29 13:21:46,405 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.batch.register-job-definition: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fa7c0166cf8>
2020-12-29 13:21:46,405 - MainThread - awscli.argprocess - DEBUG - Param container_properties looks like JSON, not considered for param shorthand.
2020-12-29 13:21:46,405 - MainThread - awscli.arguments - DEBUG - Unpacked value of '{"command":["env"],"image":"amazonlinux","vcpus":1,"memory":2048,"executionRoleArn":"arn:aws:iam::146902639458:role/route-optimizer-staging-batch-execution-2b9b889","secrets":[{"name":"APP_HOST","valueFrom":"arn:aws:ssm:eu-central-1:146902639458:parameter/route-optimizer/staging/env/APP_HOST"}]}' for parameter "container_properties": OrderedDict([('command', ['env']), ('image', 'amazonlinux'), ('vcpus', 1), ('memory', 2048), ('executionRoleArn', 'arn:aws:iam::146902639458:role/route-optimizer-staging-batch-execution-2b9b889'), ('secrets', [OrderedDict([('name', 'APP_HOST'), ('valueFrom', 'arn:aws:ssm:eu-central-1:146902639458:parameter/route-optimizer/staging/env/APP_HOST')])])])
2020-12-29 13:21:46,405 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.batch.register-job-definition.node-properties: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fa7bf754be0>
2020-12-29 13:21:46,405 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.batch.register-job-definition.retry-strategy: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fa7bf754be0>
2020-12-29 13:21:46,405 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.batch.register-job-definition.timeout: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fa7bf754be0>
2020-12-29 13:21:46,405 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.batch.register-job-definition.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fa7bf754be0>
2020-12-29 13:21:46,405 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.batch.register-job-definition.cli-input-yaml: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fa7bf754be0>
2020-12-29 13:21:46,405 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.batch.register-job-definition.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fa7bf754be0>
2020-12-29 13:21:46,405 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.batch.register-job-definition.cli-auto-prompt: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fa7bf754be0>
2020-12-29 13:21:46,405 - MainThread - botocore.hooks - DEBUG - Event calling-command.batch.register-job-definition: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7fa7bf674fd0>>
2020-12-29 13:21:46,405 - MainThread - botocore.hooks - DEBUG - Event calling-command.batch.register-job-definition: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7fa7bf6c7400>>
2020-12-29 13:21:46,405 - MainThread - botocore.hooks - DEBUG - Event calling-command.batch.register-job-definition: calling handler <bound method GenerateCliSkeletonArgument.generate_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fa7bf676048>>
2020-12-29 13:21:46,405 - MainThread - botocore.hooks - DEBUG - Event calling-command.batch.register-job-definition: calling handler <bound method AutoPromptArgument.auto_prompt_arguments of <awscli.customizations.autoprompt.AutoPromptArgument object at 0x7fa7bf684358>>
2020-12-29 13:21:46,405 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2020-12-29 13:21:46,405 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2020-12-29 13:21:46,405 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2020-12-29 13:21:46,405 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2020-12-29 13:21:46,405 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2020-12-29 13:21:46,406 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2020-12-29 13:21:46,406 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.0.9/dist/botocore/data/endpoints.json
2020-12-29 13:21:46,410 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7fa7c110f730>
2020-12-29 13:21:46,410 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.batch: calling handler <function add_generate_presigned_url at 0x7fa7c1161620>
2020-12-29 13:21:46,413 - MainThread - botocore.endpoint - DEBUG - Setting batch timeout as (60, 60)
2020-12-29 13:21:46,414 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.batch.RegisterJobDefinition: calling handler <function base64_decode_input_blobs at 0x7fa7bf7d98c8>
2020-12-29 13:21:46,414 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.batch.RegisterJobDefinition: calling handler <function generate_idempotent_uuid at 0x7fa7c1132620>
2020-12-29 13:21:46,414 - MainThread - awscli.clidriver - DEBUG - Client side parameter validation failed
Traceback (most recent call last):
  File "awscli/clidriver.py", line 335, in main
  File "awscli/clidriver.py", line 507, in __call__
  File "awscli/clidriver.py", line 685, in __call__
  File "awscli/clidriver.py", line 806, in invoke
  File "awscli/clidriver.py", line 818, in _make_client_call
  File "botocore/client.py", line 208, in _api_call
  File "botocore/client.py", line 491, in _make_api_call
  File "botocore/client.py", line 539, in _convert_to_request_dict
  File "botocore/validate.py", line 297, in serialize_to_request
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in containerProperties: "executionRoleArn", must be one of: image, vcpus, memory, command, jobRoleArn, volumes, environment, mountPoints, readonlyRootFilesystem, privileged, ulimits, user, instanceType, resourceRequirements, linuxParameters
Unknown parameter in containerProperties: "secrets", must be one of: image, vcpus, memory, command, jobRoleArn, volumes, environment, mountPoints, readonlyRootFilesystem, privileged, ulimits, user, instanceType, resourceRequirements, linuxParameters

Parameter validation failed:
Unknown parameter in containerProperties: "executionRoleArn", must be one of: image, vcpus, memory, command, jobRoleArn, volumes, environment, mountPoints, readonlyRootFilesystem, privileged, ulimits, user, instanceType, resourceRequirements, linuxParameters
Unknown parameter in containerProperties: "secrets", must be one of: image, vcpus, memory, command, jobRoleArn, volumes, environment, mountPoints, readonlyRootFilesystem, privileged, ulimits, user, instanceType, resourceRequirements, linuxParameters
```
**Additional context**
Value for `containerProperties` was verified with documentation (https://docs.aws.amazon.com/batch/latest/APIReference/API_RegisterJobDefinition.html#API_RegisterJobDefinition_RequestSyntax and https://awscli.amazonaws.com/v2/documentation/api/latest/reference/batch/register-job-definition.html) and is identical with the value sent by the web console.

**Comment by kdaily** [comment]
Hi @mfly, you'll need to bump your CLI version up to 2.0.53 or later to get those API changes.

**Comment by mfly** [comment]
@kdaily I confirm it works on 2.1.14, sorry for the hassle
