### ISSUE TITLE
kinesis-video-signaling get-ice-server-config not working

### ISSUE THREAD

**Issue by cfiorillo** [aws/aws-cli#5857]
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Calling from AWS CLI the API method GetIceServerConfig should return the stun/turn servers to use; it returns an error.

**SDK version number**
aws-cli/2.1.16 Python/3.7.4 Darwin/19.6.0 exe/x86_64 prompt/off

**Platform/OS/Hardware/Device**
macOS Catalina 10.15.17

**To Reproduce (observed behavior)**
Define a profile test:
```
aws configure --profile test
AWS Access Key ID [None]: ******************
AWS Secret Access Key [None]: *****************
Default region name [None]: eu-west-1
Default output format [None]:

```
Create a signaling channel:
`aws kinesisvideo create-signaling-channel --channel-name test --profile test`
returns:
```
{
    "ChannelARN": "arn:aws:kinesisvideo:eu-west-1:607840532289:channel/test/1610186741230"
}
```

Get the ICE server configuration for the channel:
`aws kinesis-video-signaling get-ice-server-config --channel-arn "arn:aws:kinesisvideo:eu-west-1:607840532289:channel/test/1610186741230" --profile test`

It returns the following error:
An error occurred (403) when calling the GetIceServerConfig operation: <AccessDeniedException>
  <Message>Unable to determine service/operation name to be authorized</Message>
</AccessDeniedException>

**Expected behavior**
I expect the list of servers to use, like the following:
```
{
   "IceServerList": [ 
      { 
         "Password": "string",
         "Ttl": number,
         "Uris": [ "string" ],
         "Username": "string"
      }
   ]
}
```

**Logs/output**
```
2021-01-09 11:06:36,348 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.16 Python/3.7.4 Darwin/19.6.0 exe/x86_64
2021-01-09 11:06:36,348 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['kinesis-video-signaling', 'get-ice-server-config', '--debug', '--channel-arn', 'arn:aws:kinesisvideo:eu-west-1:607840532289:channel/test/1610186741230', '--profile', 'test']
2021-01-09 11:06:36,375 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x7fa4371865f0>
2021-01-09 11:06:36,375 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x7fa437041b00>
2021-01-09 11:06:36,375 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2021-01-09 11:06:36,375 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7fa4366e4320>
2021-01-09 11:06:36,375 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7fa4366e98c0>
2021-01-09 11:06:36,375 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x7fa4371f8560>
2021-01-09 11:06:36,376 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x7fa43708ea70>
2021-01-09 11:06:36,376 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2021-01-09 11:06:36,376 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x7fa4371f8c20>
2021-01-09 11:06:36,376 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/data/cli.json
2021-01-09 11:06:36,379 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x7fa437150710>
2021-01-09 11:06:36,379 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x7fa4371509e0>
2021-01-09 11:06:36,379 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x7fa437150950>
2021-01-09 11:06:36,380 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x7fa437150b00>
2021-01-09 11:06:36,380 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x7fa437150a70>
2021-01-09 11:06:36,380 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x7fa4372a75a0>
2021-01-09 11:06:36,380 - MainThread - botocore.session - DEBUG - Setting config variable for profile to 'test'
2021-01-09 11:06:36,380 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.16 Python/3.7.4 Darwin/19.6.0 exe/x86_64 prompt/off
2021-01-09 11:06:36,380 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['kinesis-video-signaling', 'get-ice-server-config', '--debug', '--channel-arn', 'arn:aws:kinesisvideo:eu-west-1:607840532289:channel/test/1610186741230', '--profile', 'test']
2021-01-09 11:06:36,380 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7fa4371e4f80>
2021-01-09 11:06:36,380 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7fa4363ea8c0>
2021-01-09 11:06:36,381 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7fa43721eb00>
2021-01-09 11:06:36,381 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x7fa436397440>
2021-01-09 11:06:36,381 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7fa436415050>
2021-01-09 11:06:36,381 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-01-09 11:06:36,387 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2021-01-09 11:06:36,387 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7fa43708eb00>
2021-01-09 11:06:36,387 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7fa437033830>
2021-01-09 11:06:36,415 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/botocore/data/kinesis-video-signaling/2019-12-04/service-2.json
2021-01-09 11:06:36,416 - MainThread - botocore.hooks - DEBUG - Event building-command-table.kinesis-video-signaling: calling handler <function add_waiters at 0x7fa4371f8c20>
2021-01-09 11:06:36,444 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('channel-arn', <awscli.arguments.CLIArgument object at 0x7fa437323750>), ('client-id', <awscli.arguments.CLIArgument object at 0x7fa437323810>), ('service', <awscli.arguments.CLIArgument object at 0x7fa437323490>), ('username', <awscli.arguments.CLIArgument object at 0x7fa4373238d0>)])
2021-01-09 11:06:36,444 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.kinesis-video-signaling.get-ice-server-config: calling handler <function add_streaming_output_arg at 0x7fa4371ec170>
2021-01-09 11:06:36,444 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.kinesis-video-signaling.get-ice-server-config: calling handler <function add_cli_input_json at 0x7fa43641ba70>
2021-01-09 11:06:36,444 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.kinesis-video-signaling.get-ice-server-config: calling handler <function add_cli_input_yaml at 0x7fa43641bcb0>
2021-01-09 11:06:36,444 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.kinesis-video-signaling.get-ice-server-config: calling handler <function unify_paging_params at 0x7fa43704cdd0>
2021-01-09 11:06:36,472 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/botocore/data/kinesis-video-signaling/2019-12-04/paginators-1.json
2021-01-09 11:06:36,472 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.kinesis-video-signaling.get-ice-server-config: calling handler <function add_generate_skeleton at 0x7fa4371467a0>
2021-01-09 11:06:36,473 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.kinesis-video-signaling.get-ice-server-config: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7fa437323910>>
2021-01-09 11:06:36,473 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.kinesis-video-signaling.get-ice-server-config: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7fa4372f2050>>
2021-01-09 11:06:36,473 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.kinesis-video-signaling.get-ice-server-config: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fa43732f610>>
2021-01-09 11:06:36,474 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.kinesisvideo.get-ice-server-config.channel-arn: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fa4372f2ed0>
2021-01-09 11:06:36,474 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.kinesis-video-signaling.get-ice-server-config: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fa4363e1550>
2021-01-09 11:06:36,474 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'arn:aws:kinesisvideo:eu-west-1:607840532289:channel/test/1610186741230' for parameter "channel_arn": 'arn:aws:kinesisvideo:eu-west-1:607840532289:channel/test/1610186741230'
2021-01-09 11:06:36,474 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.kinesisvideo.get-ice-server-config.client-id: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fa4372f2ed0>
2021-01-09 11:06:36,474 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.kinesisvideo.get-ice-server-config.service: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fa4372f2ed0>
2021-01-09 11:06:36,474 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.kinesisvideo.get-ice-server-config.username: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fa4372f2ed0>
2021-01-09 11:06:36,474 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.kinesisvideo.get-ice-server-config.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fa4372f2ed0>
2021-01-09 11:06:36,474 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.kinesisvideo.get-ice-server-config.cli-input-yaml: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fa4372f2ed0>
2021-01-09 11:06:36,475 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.kinesisvideo.get-ice-server-config.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fa4372f2ed0>
2021-01-09 11:06:36,475 - MainThread - botocore.hooks - DEBUG - Event calling-command.kinesis-video-signaling.get-ice-server-config: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7fa437323910>>
2021-01-09 11:06:36,475 - MainThread - botocore.hooks - DEBUG - Event calling-command.kinesis-video-signaling.get-ice-server-config: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7fa4372f2050>>
2021-01-09 11:06:36,475 - MainThread - botocore.hooks - DEBUG - Event calling-command.kinesis-video-signaling.get-ice-server-config: calling handler <bound method GenerateCliSkeletonArgument.generate_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fa43732f610>>
2021-01-09 11:06:36,475 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2021-01-09 11:06:36,475 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2021-01-09 11:06:36,475 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2021-01-09 11:06:36,475 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2021-01-09 11:06:36,476 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2021-01-09 11:06:36,476 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/botocore/data/endpoints.json
2021-01-09 11:06:36,483 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7fa435a77a70>
2021-01-09 11:06:36,483 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.kinesis-video-signaling: calling handler <function add_generate_presigned_url at 0x7fa4359f8170>
2021-01-09 11:06:36,487 - MainThread - botocore.endpoint - DEBUG - Setting kinesisvideo timeout as (60, 60)
2021-01-09 11:06:36,488 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.kinesis-video-signaling.GetIceServerConfig: calling handler <function base64_decode_input_blobs at 0x7fa43721eb90>
2021-01-09 11:06:36,488 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.kinesis-video-signaling.GetIceServerConfig: calling handler <function generate_idempotent_uuid at 0x7fa435a7f710>
2021-01-09 11:06:36,488 - MainThread - botocore.hooks - DEBUG - Event before-call.kinesis-video-signaling.GetIceServerConfig: calling handler <function inject_api_version_header_if_needed at 0x7fa435a84f80>
2021-01-09 11:06:36,488 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=GetIceServerConfig) with params: {'url_path': '/v1/get-ice-server-config', 'query_string': {}, 'method': 'POST', 'headers': {'User-Agent': 'aws-cli/2.1.16 Python/3.7.4 Darwin/19.6.0 exe/x86_64 prompt/off command/kinesis-video-signaling.get-ice-server-config'}, 'body': b'{"ChannelARN": "arn:aws:kinesisvideo:eu-west-1:607840532289:channel/test/1610186741230"}', 'url': 'https://kinesisvideo.eu-west-1.amazonaws.com/v1/get-ice-server-config', 'context': {'client_region': 'eu-west-1', 'client_config': <botocore.config.Config object at 0x7fa4375c7490>, 'has_streaming_input': False, 'auth_type': None}}
2021-01-09 11:06:36,488 - MainThread - botocore.hooks - DEBUG - Event request-created.kinesis-video-signaling.GetIceServerConfig: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fa4375c71d0>>
2021-01-09 11:06:36,489 - MainThread - botocore.hooks - DEBUG - Event choose-signer.kinesis-video-signaling.GetIceServerConfig: calling handler <function set_operation_specific_signer at 0x7fa435a717a0>
2021-01-09 11:06:36,489 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2021-01-09 11:06:36,489 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/v1/get-ice-server-config

host:kinesisvideo.eu-west-1.amazonaws.com
x-amz-date:20210109T100636Z

host;x-amz-date
c82998e41431c1c5ecf9044b7b8ddd666d27405608028e94a4335fecaeb1697d
2021-01-09 11:06:36,489 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20210109T100636Z
20210109/eu-west-1/kinesisvideo/aws4_request
c2f7c083457eca4bbd8f391f0166d47d1f99c869e9c3520a23d49a9fa29650b8
2021-01-09 11:06:36,489 - MainThread - botocore.auth - DEBUG - Signature:
53e5b28f8973561799c6a9a7422a57c5c7882cc485873b826682967687b3fca2
2021-01-09 11:06:36,489 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://kinesisvideo.eu-west-1.amazonaws.com/v1/get-ice-server-config, headers={'User-Agent': b'aws-cli/2.1.16 Python/3.7.4 Darwin/19.6.0 exe/x86_64 prompt/off command/kinesis-video-signaling.get-ice-server-config', 'X-Amz-Date': b'20210109T100636Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=####MASKED_ACCESS_KEY####/20210109/eu-west-1/kinesisvideo/aws4_request, SignedHeaders=host;x-amz-date, Signature=53e5b28f8973561799c6a9a7422a57c5c7882cc485873b826682967687b3fca2', 'Content-Length': '88'}>
2021-01-09 11:06:36,490 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): kinesisvideo.eu-west-1.amazonaws.com:443
2021-01-09 11:06:36,702 - MainThread - urllib3.connectionpool - DEBUG - https://kinesisvideo.eu-west-1.amazonaws.com:443 "POST /v1/get-ice-server-config HTTP/1.1" 403 130
2021-01-09 11:06:36,702 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-RequestId': '9a86845f-1d47-497e-9156-3150d09f5ad1', 'Content-Length': '130', 'Date': 'Sat, 09 Jan 2021 10:06:36 GMT'}
2021-01-09 11:06:36,702 - MainThread - botocore.parsers - DEBUG - Response body:
b'<AccessDeniedException>\n  <Message>Unable to determine service/operation name to be authorized</Message>\n</AccessDeniedException>\n'
2021-01-09 11:06:36,702 - MainThread - botocore.hooks - DEBUG - Event needs-retry.kinesis-video-signaling.GetIceServerConfig: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x7fa4375c7b90>>
2021-01-09 11:06:36,703 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2021-01-09 11:06:36,703 - MainThread - botocore.hooks - DEBUG - Event after-call.kinesis-video-signaling.GetIceServerConfig: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x7fa4375c7710>>
2021-01-09 11:06:36,703 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/clidriver.py", line 457, in main
  File "awscli/clidriver.py", line 586, in __call__
  File "awscli/clidriver.py", line 765, in __call__
  File "awscli/clidriver.py", line 894, in invoke
  File "awscli/clidriver.py", line 906, in _make_client_call
  File "botocore/client.py", line 249, in _api_call
  File "botocore/client.py", line 568, in _make_api_call
botocore.exceptions.ClientError: An error occurred (403) when calling the GetIceServerConfig operation: <AccessDeniedException>
  <Message>Unable to determine service/operation name to be authorized</Message>
</AccessDeniedException>


An error occurred (403) when calling the GetIceServerConfig operation: <AccessDeniedException>
  <Message>Unable to determine service/operation name to be authorized</Message>
</AccessDeniedException>
```

**Additional context**
The Javascript APIs, used from the [KVS WebRTC Test Page](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html), returns the correct data:

```
ICE servers:  [
  {
    "urls": "stun:stun.kinesisvideo.eu-west-1.amazonaws.com:443"
  },
  {
    "urls": [
      "turn:34-242-99-232.t-e22a89b9.kinesisvideo.eu-west-1.amazonaws.com:443?transport=udp",
      "turns:34-242-99-232.t-e22a89b9.kinesisvideo.eu-west-1.amazonaws.com:443?transport=udp",
      "turns:34-242-99-232.t-e22a89b9.kinesisvideo.eu-west-1.amazonaws.com:443?transport=tcp"
    ],
    "username": "1610187403:djE6YXJuOmF3czpraW5lc2lzdmlkZW86ZXUtd2VzdC0xOjYwNzg0MDUzMjI4OTpjaGFubmVsL3Rlc3QvMTYxMDE4Njc0MTIzMA==",
    "credential": "54En+vhZkmKvdMetphobdlP0WWkKdNKinIlIO7JGw1s="
  }
]
```

**Comment by kdaily** [comment]
Hi @cfiorillo,

Can you check this docs page that describes what could cause this issue?

https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/troubleshooting.html#troubleshooting-api-name-auth

Thanks!

**Comment by cfiorillo** [comment]
Hi @kdaily,
I checked the documentation link you suggested, that describes the same error generated when calling **GetMedia** API without (or improperly) specifying the value for the endpoint (got from a call to **GetDataEndpoint** API).

I found a strange note in the documentation for **GetIceServerConfig** API (the method I'm calling through the CLI). The documentation is available here: [https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_AWSAcuitySignalingService_GetIceServerConfig.html](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_AWSAcuitySignalingService_GetIceServerConfig.html)

and the note says:

> Before using this API, you must call the GetSignalingChannelEndpoint API to get an endpoint. You then specify the endpoint and region in your GetIceServerConfig API request.

But in the GetIceServerConfig API request an endpoint parameter is not requested/described in the documentation above; from the CLI I can pass the region, but I have no places to pass the endpoint.

Thanks

**Comment by kdaily** [comment]
@cfiorillo, that is definitely odd! I'll reach out to the Kinesis team to clarify.

**Comment by juanitosvq** [comment]
Any updates on this? We are experiencing the same issue. Thanks.

**Comment by cfiorillo** [comment]
Hi

> You have to specify an `endpoint-url` with the endpoint of your signalling channel (which should be obtained by calling `get_signaling_channel_endpoint` using the channel ARN) when trying to get the configuration for the ICE servers:

This was the answer I expected. Here is the call to get the endpoint (for others arriving here):

```
aws kinesisvideo get-signaling-channel-endpoint --channel-arn "arn:aws:kinesisvideo:eu-west-1:607840532289:channel/test/1610186741230" --single-master-channel-endpoint-configuration "Protocols=HTTPS,Role=MASTER" --profile test
```

You need to use the returned HTTPS endpoint in the call as @juanitosvq explained.

> Hope that helps (I am running aws v2.1.32)!

Yes, thanks. (I am on v2.1.33 and it works)
 
> The documentation will have to be updated:
> https://docs.aws.amazon.com/cli/latest/reference/kinesis-video-signaling/get-ice-server-config.html

(Y)

**Comment by stobrien89** [comment]
Hi all, 

Just reaching out to provide an update.  I've submitted an internal ticket the Kinesis team asking that they update the SDK documentation to reflect the note provided in their API reference.  

Apparently, the Golang and JS SDKs have logic which works around the need for a separate API call to retrieve the endpoint url, so I'm looking into how they're handling that as well.

**Comment by stobrien89** [comment]
P49088463

**Comment by stobrien89** [comment]
Hey all,

Just wanted to let you know that we haven't received any updates from the Kinesis docs team yet, but I just requested an update—we will let you know as soon as we hear back.

**Comment by rromanchuk** [comment]
this was actually a source of three different issues for me.  same required reconfiguration  via `AWSEndpoint`,  still easy to screw up because you need to carefully keep track of the context the same url is being used in, at this scope you may actually only have signed/manipulated url for web socket initialization 

```swift

    func iceServerConfig(httpUrl: URL) async throws -> [AWSKinesisVideoSignalingIceServer]? {

        let endpoint =
            AWSEndpoint(region: .USEast1,
                            service: .KinesisVideo,
                            url: httpUrl)
        
        
        let configuration =
        AWSServiceConfiguration(region: .USEast1,
                                    endpoint: endpoint,
                                    credentialsProvider: AWSServiceManager.default().defaultServiceConfiguration.credentialsProvider)
        
        AWSKinesisVideoSignaling.register(with: configuration!, forKey: awsKinesisVideoKey)
        let kvsSignalingClient = AWSKinesisVideoSignaling(forKey: awsKinesisVideoKey)

        let iceServerConfigRequest = AWSKinesisVideoSignalingGetIceServerConfigRequest.init()!

        iceServerConfigRequest.channelARN = channelARN
        iceServerConfigRequest.clientId = self.localSenderId
        iceServerConfigRequest.service = .turn
        
        log.info("AWSEndpoint", context: endpoint)
        return try await withCheckedThrowingContinuation { continuation in
            kvsSignalingClient.getIceServerConfig(iceServerConfigRequest).continueWith(block: { (task) -> Void in
                if let error = task.error {
                    log.error(error)
                    continuation.resume(throwing: error)
                } else {
                    log.info(task.result?.iceServerList)
                    continuation.resume(returning: task.result?.iceServerList)
                }
                return
            })

        }
    }
```
