### ISSUE TITLE
Sort order can't be specified when passing a nextToken

### ISSUE THREAD

**Issue by kerruba-milkman** [aws/aws-cli#5863]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
The CLI thorws an exception when listing projects builds providing a sort order.

**SDK version number**
aws-cli/2.1.16 

**Platform/OS/Hardware/Device**
Python/3.7.3 Linux/5.4.0-58-generic exe/x86_64.ubuntu.20 prompt/off

**To Reproduce (observed behavior)**
The command I've used is `aws --no-cli-pager codebuild list-builds-for-project --project-name <project> --sort-order DESCENDING --profile <profile>

**Expected behavior**
Results should be displayed using sorting 

**Logs/output**
```
2021-01-12 10:34:27,858 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.16 Python/3.7.3 Linux/5.4.0-58-generic exe/x86_64.ubuntu.20
2021-01-12 10:34:27,859 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', '--no-cli-pager', 'codebuild', 'list-builds-for-project', '--project-name', '<project-name>', '--sort-order', 'DESCENDING', '--profile', '<profile>']
2021-01-12 10:34:27,876 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x7f910da6cb70>
2021-01-12 10:34:27,876 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x7f910dc66a60>
2021-01-12 10:34:27,876 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2021-01-12 10:34:27,876 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7f910dc8e048>
2021-01-12 10:34:27,876 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7f910dc8ed08>
2021-01-12 10:34:27,876 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x7f910da812f0>
2021-01-12 10:34:27,876 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x7f910dbb3158>
2021-01-12 10:34:27,876 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2021-01-12 10:34:27,877 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x7f910da79598>
2021-01-12 10:34:27,877 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.1.16/dist/awscli/data/cli.json
2021-01-12 10:34:27,882 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x7f910db5bd08>
2021-01-12 10:34:27,882 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x7f910db5f048>
2021-01-12 10:34:27,882 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x7f910db5bf28>
2021-01-12 10:34:27,882 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x7f910db5f158>
2021-01-12 10:34:27,882 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x7f910db5f0d0>
2021-01-12 10:34:27,883 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x7f910da1cdc8>
2021-01-12 10:34:27,883 - MainThread - botocore.session - DEBUG - Setting config variable for profile to '<profile>'
2021-01-12 10:34:27,883 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.16 Python/3.7.3 Linux/5.4.0-58-generic exe/x86_64.ubuntu.20 prompt/off
2021-01-12 10:34:27,883 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', '--no-cli-pager', 'codebuild', 'list-builds-for-project', '--project-name', '<project-name>', '--sort-order', 'DESCENDING', '--profile', '<profile>']
2021-01-12 10:34:27,884 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7f910da71158>
2021-01-12 10:34:27,884 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7f910e0376a8>
2021-01-12 10:34:27,884 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7f910da59ae8>
2021-01-12 10:34:27,884 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x7f910e073f28>
2021-01-12 10:34:27,884 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f910e068510>
2021-01-12 10:34:27,885 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-01-12 10:34:27,889 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2021-01-12 10:34:27,890 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f910dbb3048>
2021-01-12 10:34:27,890 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7f910dc64950>
2021-01-12 10:34:27,905 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.1.16/dist/botocore/data/codebuild/2016-10-06/service-2.json
2021-01-12 10:34:27,922 - MainThread - botocore.hooks - DEBUG - Event building-command-table.codebuild: calling handler <function add_waiters at 0x7f910da79598>
2021-01-12 10:34:27,938 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('project-name', <awscli.arguments.CLIArgument object at 0x7f910d841cc0>), ('sort-order', <awscli.arguments.CLIArgument object at 0x7f910d841cf8>), ('next-token', <awscli.arguments.CLIArgument object at 0x7f910d841d68>)])
2021-01-12 10:34:27,939 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.codebuild.list-builds-for-project: calling handler <function add_streaming_output_arg at 0x7f910da71400>
2021-01-12 10:34:27,939 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.codebuild.list-builds-for-project: calling handler <function add_cli_input_json at 0x7f910e068d08>
2021-01-12 10:34:27,939 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.codebuild.list-builds-for-project: calling handler <function add_cli_input_yaml at 0x7f910dff5400>
2021-01-12 10:34:27,939 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.codebuild.list-builds-for-project: calling handler <function unify_paging_params at 0x7f910dbf4158>
2021-01-12 10:34:27,955 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.1.16/dist/botocore/data/codebuild/2016-10-06/paginators-1.json
2021-01-12 10:34:27,956 - MainThread - awscli.customizations.paginate - DEBUG - Modifying paging parameters for operation: ListBuildsForProject
2021-01-12 10:34:27,956 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.codebuild.list-builds-for-project: calling handler <function add_generate_skeleton at 0x7f910db4ba60>
2021-01-12 10:34:27,957 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.codebuild.list-builds-for-project: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7f910d841dd8>>
2021-01-12 10:34:27,957 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.codebuild.list-builds-for-project: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7f910d841ac8>>
2021-01-12 10:34:27,957 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.codebuild.list-builds-for-project: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f910d845828>>
2021-01-12 10:34:27,958 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.codebuild.list-builds-for-project: calling handler functools.partial(<function check_should_enable_pagination at 0x7f910dbf4268>, ['next-token'], {}, OrderedDict([('project-name', <awscli.arguments.CLIArgument object at 0x7f910d841cc0>), ('sort-order', <awscli.arguments.CLIArgument object at 0x7f910d841cf8>), ('next-token', <awscli.arguments.CLIArgument object at 0x7f910d841d68>), ('cli-input-json', <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7f910d841dd8>), ('cli-input-yaml', <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7f910d841ac8>), ('starting-token', <awscli.customizations.paginate.PageArgument object at 0x7f910d841f60>), ('max-items', <awscli.customizations.paginate.PageArgument object at 0x7f910d845780>), ('generate-cli-skeleton', <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f910d845828>)]))
2021-01-12 10:34:27,958 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.codebuild.list-builds-for-project.project-name: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f910d96c780>
2021-01-12 10:34:27,958 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.codebuild.list-builds-for-project: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f910e0a1dd8>
2021-01-12 10:34:27,959 - MainThread - awscli.arguments - DEBUG - Unpacked value of '<project-name>' for parameter "project_name": '<project-name>'
2021-01-12 10:34:27,959 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.codebuild.list-builds-for-project.sort-order: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f910d96c780>
2021-01-12 10:34:27,959 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.codebuild.list-builds-for-project: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f910e0a1dd8>
2021-01-12 10:34:27,959 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'DESCENDING' for parameter "sort_order": 'DESCENDING'
2021-01-12 10:34:27,959 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.codebuild.list-builds-for-project.next-token: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f910d96c780>
2021-01-12 10:34:27,959 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.codebuild.list-builds-for-project.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f910d96c780>
2021-01-12 10:34:27,959 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.codebuild.list-builds-for-project.cli-input-yaml: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f910d96c780>
2021-01-12 10:34:27,959 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.codebuild.list-builds-for-project.starting-token: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f910d96c780>
2021-01-12 10:34:27,959 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.codebuild.list-builds-for-project.max-items: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f910d96c780>
2021-01-12 10:34:27,960 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.codebuild.list-builds-for-project.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f910d96c780>
2021-01-12 10:34:27,960 - MainThread - botocore.hooks - DEBUG - Event calling-command.codebuild.list-builds-for-project: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7f910d841dd8>>
2021-01-12 10:34:27,960 - MainThread - botocore.hooks - DEBUG - Event calling-command.codebuild.list-builds-for-project: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7f910d841ac8>>
2021-01-12 10:34:27,960 - MainThread - botocore.hooks - DEBUG - Event calling-command.codebuild.list-builds-for-project: calling handler <bound method GenerateCliSkeletonArgument.generate_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f910d845828>>
2021-01-12 10:34:27,960 - MainThread - botocore.hooks - DEBUG - Event calling-command.codebuild.list-builds-for-project: calling handler functools.partial(<function check_should_enable_pagination_call_parameters at 0x7f910dbf4620>, ['nextToken'])
2021-01-12 10:34:27,960 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2021-01-12 10:34:27,961 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2021-01-12 10:34:27,961 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2021-01-12 10:34:27,961 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2021-01-12 10:34:27,962 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2021-01-12 10:34:27,963 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.1.16/dist/botocore/data/endpoints.json
2021-01-12 10:34:27,975 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f910f485840>
2021-01-12 10:34:27,978 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.codebuild: calling handler <function add_generate_presigned_url at 0x7f910f4b5c80>
2021-01-12 10:34:27,983 - MainThread - botocore.endpoint - DEBUG - Setting codebuild timeout as (60, 60)
2021-01-12 10:34:27,985 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.codebuild.ListBuildsForProject: calling handler <function base64_decode_input_blobs at 0x7f910da56268>
2021-01-12 10:34:27,986 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.codebuild.ListBuildsForProject: calling handler <function generate_idempotent_uuid at 0x7f910f4246a8>
2021-01-12 10:34:27,986 - MainThread - botocore.hooks - DEBUG - Event before-call.codebuild.ListBuildsForProject: calling handler <function inject_api_version_header_if_needed at 0x7f910f426e18>
2021-01-12 10:34:27,986 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=ListBuildsForProject) with params: {'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'X-Amz-Target': 'CodeBuild_20161006.ListBuildsForProject', 'Content-Type': 'application/x-amz-json-1.1', 'User-Agent': 'aws-cli/2.1.16 Python/3.7.3 Linux/5.4.0-58-generic exe/x86_64.ubuntu.20 prompt/off command/codebuild.list-builds-for-project'}, 'body': b'{"projectName": "<poject-name>", "sortOrder": "DESCENDING"}', 'url': 'https://codebuild.eu-central-1.amazonaws.com/', 'context': {'client_region': 'eu-central-1', 'client_config': <botocore.config.Config object at 0x7f910d617a58>, 'has_streaming_input': False, 'auth_type': None}}
2021-01-12 10:34:27,986 - MainThread - botocore.hooks - DEBUG - Event request-created.codebuild.ListBuildsForProject: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f910d6179b0>>
2021-01-12 10:34:27,986 - MainThread - botocore.hooks - DEBUG - Event choose-signer.codebuild.ListBuildsForProject: calling handler <function set_operation_specific_signer at 0x7f910f424598>
2021-01-12 10:34:27,987 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2021-01-12 10:34:27,987 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-amz-json-1.1
host:codebuild.eu-central-1.amazonaws.com
x-amz-date:20210112T093427Z
x-amz-target:CodeBuild_20161006.ListBuildsForProject

content-type;host;x-amz-date;x-amz-target
2ed7b11618aef44e8c7d9ead7b20d11639034ceb35c4e352471007cd251530a2
2021-01-12 10:34:27,987 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20210112T093427Z
20210112/eu-central-1/codebuild/aws4_request
634540626ea480f3944e6000cec9fcb910948b48eec98388e9125527725fb3a6
2021-01-12 10:34:27,987 - MainThread - botocore.auth - DEBUG - Signature:
2ecf2506f143a3e1d8a33535046f31c6d0feb94aed7e7b8287da3a68d4bcf897
2021-01-12 10:34:27,988 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://codebuild.eu-central-1.amazonaws.com/, headers={'X-Amz-Target': b'CodeBuild_20161006.ListBuildsForProject', 'Content-Type': b'application/x-amz-json-1.1', 'User-Agent': b'aws-cli/2.1.16 Python/3.7.3 Linux/5.4.0-58-generic exe/x86_64.ubuntu.20 prompt/off command/codebuild.list-builds-for-project', 'X-Amz-Date': b'20210112T093427Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=*******, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=2ecf2506f143a3e1d8a33535046f31c6d0feb94aed7e7b8287da3a68d4bcf897', 'Content-Length': '52'}>
2021-01-12 10:34:27,989 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): codebuild.eu-central-1.amazonaws.com:443
2021-01-12 10:34:28,200 - MainThread - urllib3.connectionpool - DEBUG - https://codebuild.eu-central-1.amazonaws.com:443 "POST / HTTP/1.1" 200 5192
2021-01-12 10:34:28,201 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-RequestId': '611f214d-d46c-4067-97d6-1ae39fecaea4', 'Content-Type': 'application/x-amz-json-1.1', 'Content-Length': '5192', 'Date': 'Tue, 12 Jan 2021 09:34:28 GMT'}
2021-01-12 10:34:28,202 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"ids":[<list-of- builds>],"nextToken":"AQICAHgpJdqbTVu13EH5JBfjFe07TZDY8VPD5iAD+nx/EBMd5QHbswaOt/jIAgiARB6JpXCaAAABbjCCAWoGCSqGSIb3DQEHBqCCAVswggFXAgEAMIIBUAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzsbNvTg6ZbCnz903wCARCAggEhOq7wIsnn7tvEpZnlWAUy+7ygNlrHnyMpjypfamO346SI2P3/8/qNLFyIb8N7nJg7pGR+OmJUYzXXFpctsUncEwdQhhee/FERB4/gWEWKMOl+abfoveyvjaISAs4gKnja4UIV9MI3rcqzb0UmSYFq20Hwn38xMBJe/XR8D5jR2Hsy2a/vX95jvsruguUR9eykiHj+ny/1LXEg01zIKOBCR6Srspd96b2xchRBD8BDkyFW6FmbzNAmqUYi4G2b8uGpUOvTKs74psUKvXi/SVGWHeZ1MjtVG7PzL/ZuQJFp1SV2eTierLpObsTjasourLElRfewb2cclW8Ssj3N9ZpSgM8BPjuYmu2cLDN3mJ7w07qpIEEpyjDtJWqjvimchJw32A=="}'
2021-01-12 10:34:28,202 - MainThread - botocore.hooks - DEBUG - Event needs-retry.codebuild.ListBuildsForProject: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x7f910d568160>>
2021-01-12 10:34:28,202 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2021-01-12 10:34:28,203 - MainThread - botocore.hooks - DEBUG - Event after-call.codebuild.ListBuildsForProject: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x7f910d617dd8>>
2021-01-12 10:34:28,203 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.codebuild.ListBuildsForProject: calling handler <function base64_decode_input_blobs at 0x7f910da56268>
2021-01-12 10:34:28,203 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.codebuild.ListBuildsForProject: calling handler <function generate_idempotent_uuid at 0x7f910f4246a8>
2021-01-12 10:34:28,203 - MainThread - botocore.hooks - DEBUG - Event before-call.codebuild.ListBuildsForProject: calling handler <function inject_api_version_header_if_needed at 0x7f910f426e18>
2021-01-12 10:34:28,203 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=ListBuildsForProject) with params: {'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'X-Amz-Target': 'CodeBuild_20161006.ListBuildsForProject', 'Content-Type': 'application/x-amz-json-1.1', 'User-Agent': 'aws-cli/2.1.16 Python/3.7.3 Linux/5.4.0-58-generic exe/x86_64.ubuntu.20 prompt/off command/codebuild.list-builds-for-project'}, 'body': b'{"projectName": "<project-name>", "sortOrder": "DESCENDING", "nextToken": "AQICAHgpJdqbTVu13EH5JBfjFe07TZDY8VPD5iAD+nx/EBMd5QHbswaOt/jIAgiARB6JpXCaAAABbjCCAWoGCSqGSIb3DQEHBqCCAVswggFXAgEAMIIBUAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzsbNvTg6ZbCnz903wCARCAggEhOq7wIsnn7tvEpZnlWAUy+7ygNlrHnyMpjypfamO346SI2P3/8/qNLFyIb8N7nJg7pGR+OmJUYzXXFpctsUncEwdQhhee/FERB4/gWEWKMOl+abfoveyvjaISAs4gKnja4UIV9MI3rcqzb0UmSYFq20Hwn38xMBJe/XR8D5jR2Hsy2a/vX95jvsruguUR9eykiHj+ny/1LXEg01zIKOBCR6Srspd96b2xchRBD8BDkyFW6FmbzNAmqUYi4G2b8uGpUOvTKs74psUKvXi/SVGWHeZ1MjtVG7PzL/ZuQJFp1SV2eTierLpObsTjasourLElRfewb2cclW8Ssj3N9ZpSgM8BPjuYmu2cLDN3mJ7w07qpIEEpyjDtJWqjvimchJw32A=="}', 'url': 'https://codebuild.eu-central-1.amazonaws.com/', 'context': {'client_region': 'eu-central-1', 'client_config': <botocore.config.Config object at 0x7f910d617a58>, 'has_streaming_input': False, 'auth_type': None}}
2021-01-12 10:34:28,204 - MainThread - botocore.hooks - DEBUG - Event request-created.codebuild.ListBuildsForProject: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f910d6179b0>>
2021-01-12 10:34:28,204 - MainThread - botocore.hooks - DEBUG - Event choose-signer.codebuild.ListBuildsForProject: calling handler <function set_operation_specific_signer at 0x7f910f424598>
2021-01-12 10:34:28,204 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2021-01-12 10:34:28,204 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-amz-json-1.1
host:codebuild.eu-central-1.amazonaws.com
x-amz-date:20210112T093428Z
x-amz-target:CodeBuild_20161006.ListBuildsForProject

content-type;host;x-amz-date;x-amz-target
dd67bc54124d37cbe980bfee5fcbf9dc30786e7d7f3858ce4b8696d6dff9ca86
2021-01-12 10:34:28,205 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20210112T093428Z
20210112/eu-central-1/codebuild/aws4_request
e86d13e14f51fcfcb832e904959c915b12874ef35b0ebe31562d813531708300
2021-01-12 10:34:28,205 - MainThread - botocore.auth - DEBUG - Signature:
983eb7cea628ce3642f9385eccaf0cc8f4884479508b7444b0fea694e55d102a
2021-01-12 10:34:28,205 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://codebuild.eu-central-1.amazonaws.com/, headers={'X-Amz-Target': b'CodeBuild_20161006.ListBuildsForProject', 'Content-Type': b'application/x-amz-json-1.1', 'User-Agent': b'aws-cli/2.1.16 Python/3.7.3 Linux/5.4.0-58-generic exe/x86_64.ubuntu.20 prompt/off command/codebuild.list-builds-for-project', 'X-Amz-Date': b'20210112T093428Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=******, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=983eb7cea628ce3642f9385eccaf0cc8f4884479508b7444b0fea694e55d102a', 'Content-Length': '637'}>
2021-01-12 10:34:28,267 - MainThread - urllib3.connectionpool - DEBUG - https://codebuild.eu-central-1.amazonaws.com:443 "POST / HTTP/1.1" 400 102
2021-01-12 10:34:28,267 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-RequestId': '5bec18d5-99ca-4cb7-b7c2-e4770264a718', 'Content-Type': 'application/x-amz-json-1.1', 'Content-Length': '102', 'Date': 'Tue, 12 Jan 2021 09:34:28 GMT', 'Connection': 'close'}
2021-01-12 10:34:28,267 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"__type":"InvalidInputException","message":"Sort order can\'t be specified when passing a nextToken."}'
2021-01-12 10:34:28,269 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-RequestId': '5bec18d5-99ca-4cb7-b7c2-e4770264a718', 'Content-Type': 'application/x-amz-json-1.1', 'Content-Length': '102', 'Date': 'Tue, 12 Jan 2021 09:34:28 GMT', 'Connection': 'close'}
2021-01-12 10:34:28,269 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"__type":"InvalidInputException","message":"Sort order can\'t be specified when passing a nextToken."}'
2021-01-12 10:34:28,269 - MainThread - botocore.hooks - DEBUG - Event needs-retry.codebuild.ListBuildsForProject: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x7f910d568160>>
2021-01-12 10:34:28,270 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2021-01-12 10:34:28,270 - MainThread - botocore.hooks - DEBUG - Event after-call.codebuild.ListBuildsForProject: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x7f910d617dd8>>
2021-01-12 10:34:28,270 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/clidriver.py", line 457, in main
  File "awscli/clidriver.py", line 586, in __call__
  File "awscli/clidriver.py", line 765, in __call__
  File "awscli/clidriver.py", line 895, in invoke
  File "awscli/clidriver.py", line 917, in _display_response
  File "awscli/formatter.py", line 82, in __call__
  File "botocore/paginate.py", line 449, in build_full_result
  File "botocore/paginate.py", line 255, in __iter__
  File "botocore/paginate.py", line 332, in _make_request
  File "botocore/client.py", line 249, in _api_call
  File "botocore/client.py", line 568, in _make_api_call
botocore.errorfactory.InvalidInputException: An error occurred (InvalidInputException) when calling the ListBuildsForProject operation: Sort order can't be specified when passing a nextToken.

An error occurred (InvalidInputException) when calling the ListBuildsForProject operation: Sort order can't be specified when passing a nextToken.
```

**Additional context**
No other comments

**Comment by kdaily** [comment]
Hi @kerruba-milkman,

Sorry to hear of the issue! Unfortunately it's a known limitation:

https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ListBuildsForProject.html#CodeBuild-ListBuildsForProject-request-sortOrder

> If the project has more than 100 builds, setting the sort order will result in an error.

I'm going to ask the Codebuild team to update the documentation that's pulled in to the CLI so that it is easier to diagnose. Thanks for bringing it to our attention.

**Comment by kdaily** [comment]
P43456911

**Comment by kdaily** [comment]
Hi @kerruba-milkman, this is known to the CodeBuild team, and they will update the documentation. I don't know of the ETA for the change. Closing this for now since it is documented at a higher level. Thanks again for bringing it to our attention.
