### ISSUE TITLE
aws-cli ecs register-task-definition fails in the new upgrade

### ISSUE THREAD

**Issue by abirdatta** [aws/aws-cli#5882]
Confirm by changing [2.1.20] to [2.1.19] below to ensure that it's a bug:
- [ ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
`aws ecs register-task-definition` fails when the cli-input-json of task definition has **registeredBy** and **registeredAt** parameters. 
actual error - 
```
Parameter validation failed:
Unknown parameter in input: "registeredAt", must be one of: family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory, tags, pidMode, ipcMode, proxyConfiguration, inferenceAccelerators
Unknown parameter in input: "registeredBy", must be one of: family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory, tags, pidMode, ipcMode, proxyConfiguration, inferenceAccelerators
```

Whereas the `aws ecs describe-task-definition` returns the task definition json with the registeredBy and registeredAt parameters

**SDK version number**

**Platform/OS/Hardware/Device**
Linux
MacOS

**To Reproduce (observed behavior)**
`TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "xyz:123" --region ap-southeast-1)`
`NEW_TASK_DEFINTIION=$(echo $TASK_DEFINITION | jq --arg IMAGE "image:tag" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities)')`
`NEW_TASK=$(aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEFINTIION" --region ap-southeast-1)`

**Expected behavior**
`aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEFINTIION"` should work when the task definition json has **registeredBy** and **registeredAt** parameters.

**Logs/output**
```
2021-01-20 13:39:53,987 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/clidriver.py", line 457, in main
  File "awscli/clidriver.py", line 586, in __call__
  File "awscli/clidriver.py", line 765, in __call__
  File "awscli/clidriver.py", line 894, in invoke
  File "awscli/clidriver.py", line 906, in _make_client_call
  File "botocore/client.py", line 249, in _api_call
  File "botocore/client.py", line 541, in _make_api_call
  File "botocore/client.py", line 589, in _convert_to_request_dict
  File "botocore/validate.py", line 297, in serialize_to_request
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "registeredAt", must be one of: family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory, tags, pidMode, ipcMode, proxyConfiguration, inferenceAccelerators
Unknown parameter in input: "registeredBy", must be one of: family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory, tags, pidMode, ipcMode, proxyConfiguration, inferenceAccelerators

Parameter validation failed:
Unknown parameter in input: "registeredAt", must be one of: family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory, tags, pidMode, ipcMode, proxyConfiguration, inferenceAccelerators
Unknown parameter in input: "registeredBy", must be one of: family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory, tags, pidMode, ipcMode, proxyConfiguration, inferenceAccelerators
```

**Additional context**

**Comment by tanmaycolaco** [comment]
Do check out this thread onces https://github.com/fabfuel/ecs-deploy/issues/154

**Comment by fabdouglas** [comment]
Workaround:
```
NEW_TASK_DEFINTIION=$(echo $TASK_DEFINITION | jq --arg IMAGE "image:tag" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) | del(.registeredAt) | del(.registeredBy)')
```

The same way we manually deleted `status`attribute (and many others), we have to handle `registeredAt` and `registeredBy` cases.
Sounds legitimate.

**Comment by abirdatta** [comment]
Thanks, we already are doing this in our deployment scripts, but we have many to change, so would like to know if we have to do this workaround or a fix is expected for this. Also requested this as the `register-task-definition` api documentation page has these attributes in the task definition json  input details.

**Comment by abirdatta** [comment]
> Workaround:
> `NEW_TASK_DEFINTIION=$(echo $TASK_DEFINITION | jq --arg IMAGE "image:tag" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) | del(.registeredAt) | del(.registeredBy)')`
> 
> The same way we manually deleted `status`attribute (and many others), we have to handle `registeredAt` and `registeredBy` cases.
> Sounds legitimate.

Thanks, we already are doing this in our deployment scripts, but we have many to change, so would like to know if we have to do this workaround or a fix is expected for this. Also requested this as the `register-task-definition` api documentation page has these attributes in the task definition json  input details.

**Comment by prmdeveloper** [comment]
Unbelievable, a change that leads to the breaking of the registration process without communication, thanks for the inconvenience AWS.

**Comment by prmdeveloper** [comment]
Unbelievable, a change that leads to the breaking of the registration process, thanks for the inconvenience AWS.

**Comment by kdaily** [comment]
Hi @abirdatta et al., looking into this.

These fields were added in `botocore` yesterday, commit https://github.com/boto/botocore/commit/e66253e60e6071fc3ca689b72e1e31cff7e1d69d.

**Comment by kdaily** [comment]
I can see that the definition for `DescribeTaskDefinition` and `RegisterTaskDefinition` are not the same, so it's expected that this will not work. However, I don't know if that was intentional or not. I will check in with ECS to find out.

**Comment by dev-head** [comment]
Perhaps this should be moved into a feature request to allow for parity between the describe and register json? it is far from ideal to have to manually delete attributes in order to register it again. 

This release highlights the burden this places on our CI/CD pipelines, where if we do need to delete newly added fields, we may be forced to go and update hundreds of repositories across different code bases and across different git vendors and across different CI/CD vendors...then test each one by forcing a deployment, costing time and money...where, if instead the api can just account for it on it's end and remove the fields it doesn't need for registering a task...boom everyone wins. 

/shrug my 2 cents

**Comment by kdaily** [comment]
@dev-head it's a fair suggestion! I'm not sure why the `RegisterTaskDefinition` doesn't use the same shape for the request as the `DescribeTaskDefinition` uses for the response:

https://github.com/boto/botocore/blob/develop/botocore/data/ecs/2014-11-13/service-2.json#L4841-L4934

**Comment by dtserekhman-starz** [comment]
I agree, there must be parity between the "get" and "set" type methods. For example, we initially call DescribeTaskDefinition method, dynamically clone the resulted structure and only change one attribute on the clone. Then, we turn around and call RegisterTaskDefinition by passing the cloned taskDefinition structure, and we are now getting the error reported on this thread because RegisterTaskDefinition does not take some of the arguments returned by the DescribeTaskDefinition.

On the other hand, I also agree that registeredAt and registeredBy represent system timestamps/footprints which probably should not be preserved on the new TaskDefinitions. And I don't like the idea of introducing extra arguments to the RegisterTaskDefinition which simply will be ignored or reset to some other values. It's bad programming. 

How about we introduce another DescribeTaskDefinition method (can't think of a good name for it yet) which will always guarantee parity of the returned arguments to the arguments taken by the RegisterTaskDefinition? This method will help out a lot for dynamic cloning and creation of the new TaskDefinition.

Or better yet, have a RegisterTaskDefinition() factory method which takes another TaskDefinition as an argument!

**Comment by dtserekhman-starz** [comment]
On the other note, getting down to the root cause of the issue here, it is my understanding this was a long-standing bug which just now got fixed and caused this "side effect"?

The reason why I say it was a long-standing bug is because in my code I lock-in the version of the ECS client upon its instantiation like so:

client = session.client('ecs', api_version = '2014-11-13')

So, I was really surprised when all of the sudden our code broke with a newer version of boto3. Should not the specification of specific api_version in the constructor above guarantee a certain API contract, which should not change?

I went ahead and found the API doc which states that very same API version on the cover page (2014-11-13):
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/ecs-api.pdf 

And sure enough, this "2014-11-13" versioned doc already lists registeredAt and registeredBy attributes on the DescribeTaskDefinition method. 

So, these attributes were a part of "2014-11-13" API contract and should have been returned by boto library all along but they were not. And only now this "bug" got fixed, but obviously started causing this other side effect problem where users "were trained" not to expect to see these attributes.

**Comment by aloysiustany** [comment]
Starting to see the same problem now reporting for `deregisteredAt`

**Comment by kdaily** [comment]
@dtserekhman-starz - the API version you're seeing there is not in use. The AWS CLI v2 (and `botocore` version 2) do not have this attribute required anymore. The SDKs are updated when the API models change, and the AWS CLI updates when the Python SDK updates.

**Comment by kdaily** [comment]
The service team is aware of the issue, and I have raised the point of improving the developer experience. I will update once I have an update from them.

**Comment by motawy** [comment]
> Workaround:
> `NEW_TASK_DEFINTIION=$(echo $TASK_DEFINITION | jq --arg IMAGE "image:tag" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) | del(.registeredAt) | del(.registeredBy)')`
> 
> The same way we manually deleted `status`attribute (and many others), we have to handle `registeredAt` and `registeredBy` cases.
> Sounds legitimate.

I have the same issue but when using this method now i receive this message:
```Missing required parameter in input: "family"```

Is there something i'm missing to make it work?

**Comment by motawy** [comment]
> Workaround:
> `NEW_TASK_DEFINTIION=$(echo $TASK_DEFINITION | jq --arg IMAGE "image:tag" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) | del(.registeredAt) | del(.registeredBy)')`
> 
> The same way we manually deleted `status`attribute (and many others), we have to handle `registeredAt` and `registeredBy` cases.
> Sounds legitimate.

@fabdouglas  
It seems I have the same problem mentioned but after changing my part of the deployment script as the one you suggested, it kept failing asking for more information like family, memory or memoryReservation and then it completely failed saying 
```An error occurred (InvalidParameterException) when calling the UpdateService operation: Task definition does not support launch_type FARGATE.```

Do you have any other suggestions?

**Comment by kdaily** [comment]
P43625635

**Comment by kdaily** [comment]
I'm moving this to our central aws-sdk repository for further tracking as this issue would affect other SDKs as well.
