### ISSUE TITLE
update-stack-set doesn't work with organization root ID

### ISSUE THREAD

**Issue by zoellner** [aws/aws-cli#5886]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
`update-stack-set` command doesn't allow organization root ID as deployment-targets/OrganizationalUnitIds parameter as mentioned in documentation

**SDK version number**
aws-cli/2.1.20 Python/3.9.1 Darwin/20.2.0 source/x86_64 prompt/off

**Platform/OS/Hardware/Device**
macOS 11.1
**To Reproduce (observed behavior)**
Run following command using an existing `stackset-name` and the organization's root ID in place of `o-xxxxxxxxxx`
```sh
aws cloudformation update-stack-set --stack-set-name stackset-name --use-previous-template --deployment-targets OrganizationalUnitIds=o-xxxxxxxxxx --regions us-east-1
```
**Expected behavior**
Stackset updates without error

**Logs/output**
```
An error occurred (ValidationError) when calling the UpdateStackSet operation: 1 validation error detected: Value '[o-xxxxxxxxxx]' at 'deploymentTargets.organizationalUnitIds' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 68, Member must have length greater than or equal to 6, Member must satisfy regular expression pattern: ^(ou-[a-z0-9]{4,32}-[a-z0-9]{8,32}|r-[a-z0-9]{4,32})$]
```
**Additional context**

Documentation https://docs.aws.amazon.com/cli/latest/reference/cloudformation/update-stack-set.html specifically mentions 

> OrganizationalUnitIds -> (list)
> The organization root ID or organizational unit (OU) IDs to which StackSets deploys.
>(string)

But the regex pattern returned in the error suggest otherwise

**Comment by kdaily** [comment]
Hi @zoellner,

I'm wondering if the regular expression is failing because it's expecting an array of strings, and you only passed a single string, and it's not getting set correctly in the request. Per the docs and shorthand syntax this should work!

I'll need to see complete debug logs that show the parameter parsing and request construction to look into it more, though! Please provide, and sanitize any account IDs or any other sensitive information.

Thanks!

**Comment by zoellner** [comment]
How would I pass a single id as an array with shorthand syntax?

**Comment by zoellner** [comment]
here's the sanitized debug output. from what I gather it does convert it to an array

```
% aws cloudformation update-stack-set --stack-set-name stackset-name --use-previous-template --deployment-targets OrganizationalUnitIds=o-xxxxxxxxxx --regions us-east-1 --debug
2021-01-21 12:52:44,169 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.20 Python/3.9.1 Darwin/20.2.0 source/x86_64
2021-01-21 12:52:44,170 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['cloudformation', 'update-stack-set', '--stack-set-name', 'stackset-name', '--use-previous-template', '--deployment-targets', 'OrganizationalUnitIds=o-xxxxxxxxxx', '--regions', 'us-east-1', '--debug']
2021-01-21 12:52:44,195 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x10950f040>
2021-01-21 12:52:44,195 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x109392dc0>
2021-01-21 12:52:44,195 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2021-01-21 12:52:44,195 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x109346430>
2021-01-21 12:52:44,195 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x109341160>
2021-01-21 12:52:44,195 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x1094f59d0>
2021-01-21 12:52:44,195 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x1093e58b0>
2021-01-21 12:52:44,195 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2021-01-21 12:52:44,195 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x10950bc10>
2021-01-21 12:52:44,195 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.1.20/libexec/lib/python3.9/site-packages/awscli/data/cli.json
2021-01-21 12:52:44,198 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x1094970d0>
2021-01-21 12:52:44,198 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x109497c10>
2021-01-21 12:52:44,198 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x109497b80>
2021-01-21 12:52:44,199 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x109497d30>
2021-01-21 12:52:44,199 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x109497ca0>
2021-01-21 12:52:44,199 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x1095d7800>
2021-01-21 12:52:44,199 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.20 Python/3.9.1 Darwin/20.2.0 source/x86_64 prompt/off
2021-01-21 12:52:44,199 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['cloudformation', 'update-stack-set', '--stack-set-name', 'stackset-name', '--use-previous-template', '--deployment-targets', 'OrganizationalUnitIds=o-xxxxxxxxxx', '--regions', 'us-east-1', '--debug']
2021-01-21 12:52:44,199 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x10950f670>
2021-01-21 12:52:44,199 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x1090a23a0>
2021-01-21 12:52:44,199 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x10959ef70>
2021-01-21 12:52:44,200 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x1090a9670>
2021-01-21 12:52:44,200 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x1090e0ca0>
2021-01-21 12:52:44,201 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-01-21 12:52:44,207 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x1093e5790>
2021-01-21 12:52:44,207 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x109393ca0>
2021-01-21 12:52:44,232 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.1.20/libexec/lib/python3.9/site-packages/botocore/data/cloudformation/2010-05-15/service-2.json
2021-01-21 12:52:44,240 - MainThread - botocore.hooks - DEBUG - Event building-command-table.cloudformation: calling handler <function inject_commands at 0x1092763a0>
2021-01-21 12:52:44,240 - MainThread - botocore.hooks - DEBUG - Event building-command-table.cloudformation: calling handler <function add_waiters at 0x10950bc10>
2021-01-21 12:52:44,264 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.1.20/libexec/lib/python3.9/site-packages/botocore/data/cloudformation/2010-05-15/waiters-2.json
2021-01-21 12:52:44,266 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('stack-set-name', <awscli.arguments.CLIArgument object at 0x10940ab80>), ('description', <awscli.arguments.CLIArgument object at 0x10940a4c0>), ('template-body', <awscli.arguments.CLIArgument object at 0x10940a4f0>), ('template-url', <awscli.arguments.CLIArgument object at 0x10940a520>), ('use-previous-template', <awscli.arguments.BooleanArgument object at 0x10940ad90>), ('no-use-previous-template', <awscli.arguments.BooleanArgument object at 0x10940adc0>), ('parameters', <awscli.arguments.ListArgument object at 0x10940adf0>), ('capabilities', <awscli.arguments.ListArgument object at 0x10940af40>), ('tags', <awscli.arguments.ListArgument object at 0x10940af10>), ('operation-preferences', <awscli.arguments.CLIArgument object at 0x10940a880>), ('administration-role-arn', <awscli.arguments.CLIArgument object at 0x10940a8b0>), ('execution-role-name', <awscli.arguments.CLIArgument object at 0x10940a8e0>), ('deployment-targets', <awscli.arguments.CLIArgument object at 0x10940a910>), ('permission-model', <awscli.arguments.CLIArgument object at 0x10940a940>), ('auto-deployment', <awscli.arguments.CLIArgument object at 0x10940a970>), ('operation-id', <awscli.arguments.CLIArgument object at 0x10940a9a0>), ('accounts', <awscli.arguments.ListArgument object at 0x10940a9d0>), ('regions', <awscli.arguments.ListArgument object at 0x10940aa00>)])
2021-01-21 12:52:44,266 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudformation.update-stack-set: calling handler <function add_streaming_output_arg at 0x10950f940>
2021-01-21 12:52:44,266 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudformation.update-stack-set: calling handler <function add_cli_input_json at 0x1090eb550>
2021-01-21 12:52:44,266 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudformation.update-stack-set: calling handler <function add_cli_input_yaml at 0x1090eb700>
2021-01-21 12:52:44,266 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudformation.update-stack-set: calling handler <function unify_paging_params at 0x10939d3a0>
2021-01-21 12:52:44,291 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.1.20/libexec/lib/python3.9/site-packages/botocore/data/cloudformation/2010-05-15/paginators-1.json
2021-01-21 12:52:44,291 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudformation.update-stack-set: calling handler <function add_generate_skeleton at 0x1094a74c0>
2021-01-21 12:52:44,291 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cloudformation.update-stack-set: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x10940a130>>
2021-01-21 12:52:44,291 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cloudformation.update-stack-set: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x10940a100>>
2021-01-21 12:52:44,291 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cloudformation.update-stack-set: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x10940a0d0>>
2021-01-21 12:52:44,293 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudformation.update-stack-set.stack-set-name: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1094dac40>
2021-01-21 12:52:44,293 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.cloudformation.update-stack-set: calling handler <awscli.argprocess.ParamShorthandParser object at 0x108f6e8e0>
2021-01-21 12:52:44,293 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'stackset-name' for parameter "stack_set_name": 'stackset-name'
2021-01-21 12:52:44,293 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudformation.update-stack-set.description: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1094dac40>
2021-01-21 12:52:44,293 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudformation.update-stack-set.template-body: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1094dac40>
2021-01-21 12:52:44,293 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudformation.update-stack-set.template-url: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1094dac40>
2021-01-21 12:52:44,293 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudformation.update-stack-set.use-previous-template: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1094dac40>
2021-01-21 12:52:44,293 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudformation.update-stack-set.parameters: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1094dac40>
2021-01-21 12:52:44,293 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudformation.update-stack-set.capabilities: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1094dac40>
2021-01-21 12:52:44,293 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudformation.update-stack-set.tags: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1094dac40>
2021-01-21 12:52:44,293 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudformation.update-stack-set.operation-preferences: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1094dac40>
2021-01-21 12:52:44,294 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudformation.update-stack-set.administration-role-arn: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1094dac40>
2021-01-21 12:52:44,294 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudformation.update-stack-set.execution-role-name: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1094dac40>
2021-01-21 12:52:44,294 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudformation.update-stack-set.deployment-targets: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1094dac40>
2021-01-21 12:52:44,294 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.cloudformation.update-stack-set: calling handler <awscli.argprocess.ParamShorthandParser object at 0x108f6e8e0>
2021-01-21 12:52:44,294 - MainThread - awscli.argprocess - DEBUG - Parsing param --deployment-targets as shorthand
2021-01-21 12:52:44,295 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'OrganizationalUnitIds=o-xxxxxxxxxx' for parameter "deployment_targets": {'OrganizationalUnitIds': ['o-xxxxxxxxxx']}
2021-01-21 12:52:44,295 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudformation.update-stack-set.permission-model: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1094dac40>
2021-01-21 12:52:44,295 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudformation.update-stack-set.auto-deployment: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1094dac40>
2021-01-21 12:52:44,295 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudformation.update-stack-set.operation-id: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1094dac40>
2021-01-21 12:52:44,295 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudformation.update-stack-set.accounts: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1094dac40>
2021-01-21 12:52:44,295 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudformation.update-stack-set.regions: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1094dac40>
2021-01-21 12:52:44,295 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.cloudformation.update-stack-set: calling handler <awscli.argprocess.ParamShorthandParser object at 0x108f6e8e0>
2021-01-21 12:52:44,295 - MainThread - awscli.arguments - DEBUG - Unpacked value of ['us-east-1'] for parameter "regions": ['us-east-1']
2021-01-21 12:52:44,295 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudformation.update-stack-set.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1094dac40>
2021-01-21 12:52:44,295 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudformation.update-stack-set.cli-input-yaml: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1094dac40>
2021-01-21 12:52:44,295 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudformation.update-stack-set.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1094dac40>
2021-01-21 12:52:44,295 - MainThread - botocore.hooks - DEBUG - Event calling-command.cloudformation.update-stack-set: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x10940a130>>
2021-01-21 12:52:44,296 - MainThread - botocore.hooks - DEBUG - Event calling-command.cloudformation.update-stack-set: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x10940a100>>
2021-01-21 12:52:44,296 - MainThread - botocore.hooks - DEBUG - Event calling-command.cloudformation.update-stack-set: calling handler <bound method GenerateCliSkeletonArgument.generate_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x10940a0d0>>
2021-01-21 12:52:44,296 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2021-01-21 12:52:44,296 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2021-01-21 12:52:44,296 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2021-01-21 12:52:44,296 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2021-01-21 12:52:44,296 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2021-01-21 12:52:44,298 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2021-01-21 12:52:44,298 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.1.20/libexec/lib/python3.9/site-packages/botocore/data/endpoints.json
2021-01-21 12:52:44,303 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x1085b9ee0>
2021-01-21 12:52:44,304 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.cloudformation: calling handler <function add_generate_presigned_url at 0x1085760d0>
2021-01-21 12:52:44,380 - MainThread - botocore.endpoint - DEBUG - Setting cloudformation timeout as (60, 60)
2021-01-21 12:52:44,381 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.cloudformation.UpdateStackSet: calling handler <function base64_decode_input_blobs at 0x10959f700>
2021-01-21 12:52:44,382 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.cloudformation.UpdateStackSet: calling handler <function generate_idempotent_uuid at 0x1085d40d0>
2021-01-21 12:52:44,382 - MainThread - botocore.handlers - DEBUG - injecting idempotency token (a4c85cbf-a260-44ac-a83d-ce4fe44f950a) into param 'OperationId'.
2021-01-21 12:52:44,382 - MainThread - botocore.hooks - DEBUG - Event before-call.cloudformation.UpdateStackSet: calling handler <function inject_api_version_header_if_needed at 0x1085d2940>
2021-01-21 12:52:44,382 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=UpdateStackSet) with params: {'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': 'aws-cli/2.1.20 Python/3.9.1 Darwin/20.2.0 source/x86_64 prompt/off command/cloudformation.update-stack-set'}, 'body': {'Action': 'UpdateStackSet', 'Version': '2010-05-15', 'StackSetName': 'stackset-name', 'UsePreviousTemplate': 'true', 'DeploymentTargets.OrganizationalUnitIds.member.1': 'o-xxxxxxxxxx', 'Regions.member.1': 'us-east-1', 'OperationId': 'a4c85cbf-a260-44ac-a83d-ce4fe44f950a'}, 'url': 'https://cloudformation.us-east-1.amazonaws.com/', 'context': {'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x1094c1400>, 'has_streaming_input': False, 'auth_type': None}}
2021-01-21 12:52:44,382 - MainThread - botocore.hooks - DEBUG - Event request-created.cloudformation.UpdateStackSet: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x1094c13d0>>
2021-01-21 12:52:44,383 - MainThread - botocore.hooks - DEBUG - Event choose-signer.cloudformation.UpdateStackSet: calling handler <function set_operation_specific_signer at 0x1085cff70>
2021-01-21 12:52:44,383 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2021-01-21 12:52:44,383 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-www-form-urlencoded; charset=utf-8
host:cloudformation.us-east-1.amazonaws.com
x-amz-date:20210121T125244Z
x-amz-security-token:xxxx//////////xxxxxxxxxxxx/xxxx+xxxxxx/xxxxx/xxxxxx/wQ+xxxx/xxxx+xxxx

content-type;host;x-amz-date;x-amz-security-token
xxxxxxxxxxxx
2021-01-21 12:52:44,383 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20210121T125244Z
20210121/us-east-1/cloudformation/aws4_request
xxxxxx
2021-01-21 12:52:44,383 - MainThread - botocore.auth - DEBUG - Signature:
xxxxxx
2021-01-21 12:52:44,383 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://cloudformation.us-east-1.amazonaws.com/, headers={'Content-Type': b'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': b'aws-cli/2.1.20 Python/3.9.1 Darwin/20.2.0 source/x86_64 prompt/off command/cloudformation.update-stack-set', 'X-Amz-Date': b'20210121T125244Z', 'X-Amz-Security-Token': b'xxx//////////xxxx/xxxx+xx/xx/xx/wQ+xx/xx+xx', 'Authorization': b'AWS4-HMAC-SHA256 Credential=xxxxxxx/20210121/us-east-1/cloudformation/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-security-token, Signature=xxxx', 'Content-Length': '242'}>
2021-01-21 12:52:44,384 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): cloudformation.us-east-1.amazonaws.com:443
2021-01-21 12:52:44,939 - MainThread - urllib3.connectionpool - DEBUG - https://cloudformation.us-east-1.amazonaws.com:443 "POST / HTTP/1.1" 400 643
2021-01-21 12:52:44,940 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-RequestId': '5d7ff4a1-e169-446e-bde4-ace73b070bd2', 'Content-Type': 'text/xml', 'Content-Length': '643', 'Date': 'Thu, 21 Jan 2021 12:52:44 GMT', 'Connection': 'close'}
2021-01-21 12:52:44,940 - MainThread - botocore.parsers - DEBUG - Response body:
b'<ErrorResponse xmlns="http://internal.amazon.com/coral/com.amazonaws.maestro.service.v20160713/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>1 validation error detected: Value \'[o-xxxxxxxxxx]\' at \'deploymentTargets.organizationalUnitIds\' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 68, Member must have length greater than or equal to 6, Member must satisfy regular expression pattern: ^(ou-[a-z0-9]{4,32}-[a-z0-9]{8,32}|r-[a-z0-9]{4,32})$]</Message>\n  </Error>\n  <RequestId>5d7ff4a1-e169-446e-bde4-ace73b070bd2</RequestId>\n</ErrorResponse>\n'
2021-01-21 12:52:44,942 - MainThread - botocore.hooks - DEBUG - Event needs-retry.cloudformation.UpdateStackSet: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x1090f4c10>>
2021-01-21 12:52:44,942 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2021-01-21 12:52:44,943 - MainThread - botocore.hooks - DEBUG - Event after-call.cloudformation.UpdateStackSet: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x10946f730>>
2021-01-21 12:52:44,943 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/Cellar/awscli/2.1.20/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 457, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/Cellar/awscli/2.1.20/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 586, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/Cellar/awscli/2.1.20/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 762, in __call__
    return self._operation_caller.invoke(
  File "/usr/local/Cellar/awscli/2.1.20/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 893, in invoke
    response = self._make_client_call(
  File "/usr/local/Cellar/awscli/2.1.20/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 905, in _make_client_call
    response = getattr(client, xform_name(operation_name))(
  File "/usr/local/Cellar/awscli/2.1.20/libexec/lib/python3.9/site-packages/botocore/client.py", line 249, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/Cellar/awscli/2.1.20/libexec/lib/python3.9/site-packages/botocore/client.py", line 568, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the UpdateStackSet operation: 1 validation error detected: Value '[o-xxxxxxxxxx]' at 'deploymentTargets.organizationalUnitIds' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 68, Member must have length greater than or equal to 6, Member must satisfy regular expression pattern: ^(ou-[a-z0-9]{4,32}-[a-z0-9]{8,32}|r-[a-z0-9]{4,32})$]

An error occurred (ValidationError) when calling the UpdateStackSet operation: 1 validation error detected: Value '[o-xxxxxxxxxx]' at 'deploymentTargets.organizationalUnitIds' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 68, Member must have length greater than or equal to 6, Member must satisfy regular expression pattern: ^(ou-[a-z0-9]{4,32}-[a-z0-9]{8,32}|r-[a-z0-9]{4,32})$]

```

**Comment by kdaily** [comment]
I think I missed a simple issue: the regex says the organizational unit should start with `ou-`, but yours starts with `o-`.

**Comment by zoellner** [comment]
I think you're missing the point of the issue:

> Documentation https://docs.aws.amazon.com/cli/latest/reference/cloudformation/update-stack-set.html specifically mentions
> 
>> OrganizationalUnitIds -> (list)
>> The organization root ID or organizational unit (OU) IDs to which StackSets deploys.
>> (string)
>> 

But - as you now noted as well - the regex pattern returned in the error suggest otherwise.

**Comment by kdaily** [comment]
Apologies @zoellner, I wasn't familiar with organizational IDs. 

After reviewing the documentation related to organizations, I think your ID is an [Organization ID](https://docs.aws.amazon.com/organizations/latest/APIReference/API_Organization.html), not an [Organization Root ID](https://docs.aws.amazon.com/organizations/latest/APIReference/API_Root.html). a Root ID should start with `r-`. Can you identify that ID and see if it works? It matches the second part of the regex.
