### ISSUE TITLE
Broken pipe error when piping "s3 ls" output to grep -q

### ISSUE THREAD

**Issue by haron** [aws/aws-cli#5899]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
`[Errno 32] Broken pipe` is raised when `aws s3 ls` output is piped to `grep -q` and the matching string is found; exit code is 255.

**SDK version number**
aws-cli/1.18.220 Python/2.7.17 botocore/1.19.60

**Platform/OS/Hardware/Device**
Linux/4.15.0-134-generic x86_64, Ubuntu 18.04.5 LTS

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

    set -o pipefail; aws s3 ls s3://SOME_S3_PATH | grep -q SOME_STR; echo $?
    [Errno 32] Broken pipe
    255

**Expected behavior**
No failure, just a clean exit with code 0.

**Additional context**
Command `grep -q` will stop immediately after the first match, and the program which is writing to the pipe will receive SIGPIPE. It is clear, that in case of `s3 ls` this signal can be ignored.

**Comment by kdaily** [comment]
Debug shows this:

```
2021-01-28 20:03:03,419 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/clidriver.py", line 457, in main
  File "awscli/customizations/commands.py", line 198, in __call__
  File "awscli/customizations/commands.py", line 191, in __call__
  File "awscli/customizations/s3/subcommands.py", line 509, in _run_main
  File "awscli/customizations/s3/subcommands.py", line 588, in _list_all_objects_recursive
  File "awscli/customizations/s3/subcommands.py", line 566, in _display_page
  File "awscli/customizations/utils.py", line 181, in uni_print
BrokenPipeError: [Errno 32] Broken pipe

[Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by kdaily** [comment]
I get an exit code of 120, not 255.

**Comment by kdaily** [comment]
Looks like we would need to do this to resolve this:

https://docs.python.org/3/library/signal.html#note-on-sigpipe

**Comment by bcap** [comment]
Fixed this in PR https://github.com/aws/aws-cli/pull/6303, please review :)

**Comment by bcap** [comment]
Activelly cc'ing @kdaily as this thread is a bit slow paced and somewhat quiet

**Comment by kdaily** [comment]
Hi @bcap,

Thanks for the PR, marking this issue to be reviewed.

**Comment by nhed** [comment]
![github waiting](https://github.githubassets.com/images/spinners/octocat-spinner-128.gif)

**Comment by FergusFettes** [comment]
`aws s3 ls s3://XXXX | head -n 1`

does the same

currently im buffering it via a tmp file

`aws s3 ls s3://XXXX > /tmp/aws-log.txt && cat /tmp/aws-log.txt | head -n 1`

but I'm sure this is a more elegant way

**Comment by MorayM** [comment]
I'm seeing the same behaviour piping to `head` as @FergusFettes. Also seeing it when piping to `grep` with `-m` to limit results, e.g:

```sh
aws s3 ls s3://my-bucket/ | grep -m 10 -e 'regex'
```

I assume the pipe is broken because `head` is completing before `aws s3 ls` does, and it's particularly noticeable if the number of items being listed is much greater than the number of items being filtered with `head`.

I don't know enough about Linux programming in Python to know how to fix it, but I think buffering it through a temp file is probably the simplest fix!

**Comment by gregoryb** [comment]
> I get an exit code of 120, not 255.

Got a similar issue with also exit code = 120. Unable to find an explanation.

**Comment by diego-oncoramedical** [comment]
My platform differs from the OP but the result seems to be the same.

This works:

```
aws s3 ls ... | grep ...
```

If I add `-q` to grep it crashes:

```
dargueta@ip-192-168-0-103 ~/Desktop % aws s3 ls s3://bucket/prefix/ | grep -q 'stuff'

[Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

My shell is zsh 5.9 and `aws --version` gives:

```
aws-cli/2.15.21 Python/3.11.7 Darwin/23.2.0 source/arm64 prompt/off
```

**Comment by jeffhung** [comment]
```
aws s3 ls s3://XXXX | head -n 1
```
can be mitigated by:
```
aws s3 ls s3://XXXX | sed -n 1p
```
`sed` will not make awscli produce Broken Pipe error.

```
$ aws --version
aws-cli/2.27.24 Python/3.13.3 Darwin/24.6.0 source/arm64
```

**Comment by ShiLiguo123** [comment]
## 🔧 Fix Proposal: Broken pipe error when piping s3 ls output

I've analyzed this issue and prepared a fix:

### 🔍 Root Cause
When `aws s3 ls` output is piped to `grep -q` (or `head`, `sed -i`), the early stdin close triggers `SIGPIPE`/`BrokenPipeError`. Python's default handling crashes with error trace and exit code 1, unlike standard Unix tools that exit 0 silently.

### 🛠️ Proposed Fix
Add SIGPIPE handling in `aws/clidriver.py` main entry: catch `BrokenPipeError`, close stdout/stderr cleanly, return exit code 0. Also handle `signal.SIGPIPE` at the signal level.

### 📄 Full Analysis
Complete with code diffs and test cases available. Happy to submit a PR.

**Comment by bcap** [comment]
Well

I submitted a fix 5y ago (above in the thread) but somehow it never got merged nor reviewed

Hopefully AWS internal processes for handling community contributions are different nowadays

**Comment by HenrikGharagyozyan** [comment]
Hi — I'd like to pick this up, targeting the `v2` branch.

**Root cause:** `s3 ls` writes each page through `_display_page()` → `uni_print()` → `sys.stdout` (`awscli/customizations/s3/subcommands.py`). When the downstream reader exits, the write raises `BrokenPipeError`, which reaches the blanket `except BaseException` in `CLIDriver.main()` and falls through to `GeneralExceptionHandler`, printing `[Errno 32] Broken pipe` and returning 255. Python's final stdout flush at interpreter shutdown then fails on the same closed pipe, which produces the `Exception ignored in: <_io.TextIOWrapper ...>` line and replaces the exit status with Python's own flush-failure code — which is why this thread has reports of both 255 and 120.

**Proposed approach**, following patterns already in the codebase rather than introducing a new one:

- Add a `BrokenPipeExceptionHandler` to the existing handler chains, shaped like the current `InterruptExceptionHandler` (`RC = 128 + signal.SIGINT`), returning `128 + SIGPIPE` = 141 — the same status `head` and `grep` themselves report for a closed pipe.
- Redirect the stdout fd to devnull before returning, per the note on SIGPIPE in the Python docs, so the shutdown flush can't fail.
- `awscli/customizations/logs/ui.py` already guards SIGPIPE with `if sys.platform != "win32"`, and `AWSCLIPagerManager.get_pager_stream()` already swallows `OSError` because "a pager is closed abruptly and causes a broken pipe" — the plain-stdout path just has no equivalent. This change extends that existing treatment rather than adding a new convention.

I chose catching `BrokenPipeError` over restoring `signal.SIG_DFL`: Python sets SIGPIPE to `SIG_IGN` at startup so socket writes surface as exceptions, and restoring the default would make broken socket writes fatal instead of retryable.

Happy to adjust the return code if maintainers would prefer 0 or 255 — 141 matches Unix convention but is a visible behaviour change, so I'd rather confirm before you spend review time on it.

I have the fix and tests working locally against a stubbed endpoint.
