### ISSUE TITLE
add_argument() keywords must be strings error on OS X 10.6.8

### ISSUE THREAD

**Issue by benhartley** [aws/aws-cli#59]
Just installed using `easy_install` on OS X 10.6.8 (with Python 2.6.1).

Running any command (e.g. `aws help`) returns the following error:

``` shell
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 5, in <module>
    pkg_resources.run_script('awscli==0.7.0', 'aws')
  File "/Library/Python/2.6/site-packages/setuptools-0.6c11-py2.6.egg/pkg_resources.py", line 489, in run_script

  File "/Library/Python/2.6/site-packages/setuptools-0.6c11-py2.6.egg/pkg_resources.py", line 1207, in run_script
    # we assume here that our metadata may be nested inside a "basket"
  File "/Library/Python/2.6/site-packages/awscli-0.7.0-py2.6.egg/EGG-INFO/scripts/aws", line 24, in <module>
    main()
  File "/Library/Python/2.6/site-packages/awscli-0.7.0-py2.6.egg/EGG-INFO/scripts/aws", line 20, in main
    driver.main()
  File "/Library/Python/2.6/site-packages/awscli-0.7.0-py2.6.egg/awscli/clidriver.py", line 315, in main
    self.create_main_parser()
  File "/Library/Python/2.6/site-packages/awscli-0.7.0-py2.6.egg/awscli/clidriver.py", line 108, in create_main_parser
    self.parser.add_argument(option_name, **option_data)
TypeError: add_argument() keywords must be strings
```

Looks like a [similar issue](https://forums.aws.amazon.com/thread.jspa?messageID=427242) has been reported on the AWS forum also.

**Comment by macetw** [comment]
I'm getting this error on OSX 10.6.8, Python 2.6.1, and AWS 1.10.52.
