### ISSUE TITLE
Problem parsing JSON with UTF-8 content

### ISSUE THREAD

**Issue by garnaat** [aws/aws-cli#593]
When parsing JSON values from the command line, either literal or from a file, we are using the default ASCII encoding.  If you try to specify any non-ASCII characters you will get an error like this:

```
'ascii' codec can't encode characters in position 0-2: ordinal not in range(128) 
```

I think UTF-8 would be a more reasonable default.  Also, we should document that so customers know what we are expecting.

**Comment by Amar-Chaudhari** [comment]
I still get the error on EC2 instance and OSX, heres the debug -

[ec2-user@ip-172-31-59-225 ~]$ aws ecs create-cluster —-cluster-name "Wordpress" --debug
2015-11-03 02:22:32,598 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.9.3 Python/2.7.10 Linux/4.1.10-17.31.amzn1.x86_64 botocore/1.3.3
2015-11-03 02:22:32,598 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['ecs', 'create-cluster', '\xe2\x80\x94-cluster-name', 'Wordpress', '--debug']
2015-11-03 02:22:32,598 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7f5c3d15db90>
2015-11-03 02:22:32,598 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider at 0x7f5c3d3b16e0>
2015-11-03 02:22:32,598 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2015-11-03 02:22:32,610 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.ecs: calling handler <function register_retries_for_service at 0x7f5c3dd9f758>
2015-11-03 02:22:32,610 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: ecs
2015-11-03 02:22:32,612 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ecs: calling handler <function add_waiters at 0x7f5c3d3c0500>
2015-11-03 02:22:32,613 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'cluster-name', <awscli.arguments.CLIArgument object at 0x7f5c3cd32f10>)])
2015-11-03 02:22:32,613 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ecs.create-cluster: calling handler <function add_streaming_output_arg at 0x7f5c3d4fd2a8>
2015-11-03 02:22:32,613 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ecs.create-cluster: calling handler <function add_cli_input_json at 0x7f5c3d3aaaa0>
2015-11-03 02:22:32,613 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ecs.create-cluster: calling handler <function unify_paging_params at 0x7f5c3d504488>
2015-11-03 02:22:32,614 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ecs.create-cluster: calling handler <function add_generate_skeleton at 0x7f5c3d3aade8>
2015-11-03 02:22:32,614 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ecs.create-cluster: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7f5c3cd32f50>>
2015-11-03 02:22:32,614 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ecs.create-cluster: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f5c3cd1d350>>
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Traceback (most recent call last):
  File "/usr/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 49, in main
    return driver.main()
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 187, in main
    sys.stderr.write(str(e))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 28: ordinal not in range(128)

**Comment by Rakesh201180** [comment]
I am try to update cloud front distribution using below cli command using powershell  and Windows OS

aws cloudfront update-distribution --id E***********G --if-match E*********R --distributi
on-config file://test1.json

I am getting same issue.  

Anybody can help..its uregnt..
