### ISSUE TITLE
SSO Configure using aws cli failing with eu-central-1

### ISSUE THREAD

**Issue by jacobneroth** [aws/aws-cli#5978]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Could not connect to the endpoint URL: "https://oidc.eu-central-1.amazonaws.com/client/register"

**SDK version number**

**Platform/OS/Hardware/Device**
Windows 10
CLI 2 
aws-cli/2.1.27 Python/3.7.9 Windows/10 exe/AMD64 prompt/off

**To Reproduce (observed behavior)**
a) Run aws configure sso --debug

**Expected behavior**
Opens browser and ability to choose account and profiles

**Logs/output**
2021-02-25 14:17:16,165 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.27 Python/3.7.9 Windows/10 exe/AMD64
2021-02-25 14:17:16,165 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['configure', 'sso', '--debug']
2021-02-25 14:17:16,204 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x000001F1AC7F7318>
2021-02-25 14:17:16,205 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x000001F1ABE3EEE8>
2021-02-25 14:17:16,206 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2021-02-25 14:17:16,207 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x000001F1ABE02E58>
2021-02-25 14:17:16,207 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x000001F1ABE0A5E8>
2021-02-25 14:17:16,207 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x000001F1AC808318>
2021-02-25 14:17:16,208 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x000001F1ABEAD438>
2021-02-25 14:17:16,208 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2021-02-25 14:17:16,208 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x000001F1AC8089D8>
2021-02-25 14:17:16,209 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\awscli\data\cli.json
2021-02-25 14:17:16,211 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x000001F1ABF66678>
2021-02-25 14:17:16,212 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x000001F1ABF66948>
2021-02-25 14:17:16,212 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x000001F1ABF668B8>
2021-02-25 14:17:16,213 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x000001F1ABF66A68>
2021-02-25 14:17:16,214 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x000001F1ABF669D8>
2021-02-25 14:17:16,214 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x000001F1AC8B39F8>
2021-02-25 14:17:16,217 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.27 Python/3.7.9 Windows/10 exe/AMD64 prompt/off
2021-02-25 14:17:16,217 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['configure', 'sso', '--debug']
2021-02-25 14:17:16,218 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x000001F1AC7F7EE8>
2021-02-25 14:17:16,218 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x000001F1ABBCA8B8>
2021-02-25 14:17:16,218 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x000001F1AC86B798>
2021-02-25 14:17:16,219 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x000001F1ABBADD38>
2021-02-25 14:17:16,219 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x000001F1ABC28AF8>
2021-02-25 14:17:16,221 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-02-25 14:17:16,222 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x000001F1ABEAD4C8>
2021-02-25 14:17:16,223 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x000001F1ABE54E58>
2021-02-25 14:17:16,223 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure: calling handler <function _add_wizard_command at 0x000001F1AC86A798>
2021-02-25 14:17:16,224 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure: calling handler <function add_waiters at 0x000001F1AC8089D8>
2021-02-25 14:17:16,225 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.configure.anonymous: calling handler <awscli.paramfile.URIArgumentHandler object at 0x000001F1AC8EAF48>
2021-02-25 14:17:16,225 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure_sso: calling handler <function add_waiters at 0x000001F1AC8089D8>
SSO start URL [None]: https://**Accountdetails**/start
2021-02-25 14:17:33,323 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\botocore\data\endpoints.json
2021-02-25 14:17:33,368 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\botocore\data\sso-oidc\2019-06-10\service-2.json
SSO Region [None]: eu-central-1
2021-02-25 14:17:44,457 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x000001F1AB3C4828>
2021-02-25 14:17:44,457 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.sso-oidc: calling handler <function add_generate_presigned_url at 0x000001F1AB3501F8>
2021-02-25 14:17:44,459 - MainThread - botocore.endpoint - DEBUG - Setting oidc timeout as (60, 60)
2021-02-25 14:17:44,460 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.sso-oidc.RegisterClient: calling handler <function base64_decode_input_blobs at 0x000001F1AC86B828>
2021-02-25 14:17:44,461 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.sso-oidc.RegisterClient: calling handler <function generate_idempotent_uuid at 0x000001F1AB3CA4C8>
2021-02-25 14:17:44,462 - MainThread - botocore.hooks - DEBUG - Event before-call.sso-oidc.RegisterClient: calling handler <function inject_api_version_header_if_needed at 0x000001F1AB3CFD38>
2021-02-25 14:17:44,463 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=RegisterClient) with params: {'url_path': '/client/register', 'query_string': {}, 'method': 'POST', 'headers': {'User-Agent': 'aws-cli/2.1.27 Python/3.7.9 Windows/10 exe/AMD64 prompt/off command/configure.sso'}, 'body': b'{"clientName": "botocore-client-1614259064", "clientType": "public"}', 'url': 'https://oidc.eu-central-1.amazonaws.com/client/register', 'context': {'client_region': 'eu-central-1', 'client_config': <botocore.config.Config object at 0x000001F1ACA5EDC8>, 'has_streaming_input': False, 'auth_type': 'none'}}
2021-02-25 14:17:44,465 - MainThread - botocore.hooks - DEBUG - Event request-created.sso-oidc.RegisterClient: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x000001F1ACA62208>>
2021-02-25 14:17:44,465 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sso-oidc.RegisterClient: calling handler <function set_operation_specific_signer at 0x000001F1AB3BF558>
2021-02-25 14:17:44,466 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://oidc.eu-central-1.amazonaws.com/client/register, headers={'User-Agent': b'aws-cli/2.1.27 Python/3.7.9 Windows/10 exe/AMD64 prompt/off command/configure.sso', 'Content-Length': '68'}>
2021-02-25 14:17:44,466 - MainThread - botocore.httpsession - DEBUG - Certificate path: C:\Program Files\Amazon\AWSCLIV2\botocore\cacert.pem
2021-02-25 14:17:44,467 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oidc.eu-central-1.amazonaws.com:443
2021-02-25 14:18:47,538 - MainThread - botocore.endpoint - DEBUG - Exception received when sending HTTP request.
Traceback (most recent call last):
  File "lib\site-packages\urllib3\connection.py", line 170, in _new_conn
  File "lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
  File "lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\botocore\httpsession.py", line 320, in send
  File "lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
  File "lib\site-packages\urllib3\util\retry.py", line 506, in increment
  File "lib\site-packages\urllib3\packages\six.py", line 735, in reraise
  File "lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
  File "lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
  File "lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
  File "lib\site-packages\urllib3\connection.py", line 353, in connect
  File "lib\site-packages\urllib3\connection.py", line 182, in _new_conn
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x000001F1AD131088>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\botocore\endpoint.py", line 200, in _do_get_response
  File "lib\site-packages\botocore\endpoint.py", line 269, in _send
  File "lib\site-packages\botocore\httpsession.py", line 340, in send
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://oidc.eu-central-1.amazonaws.com/client/register"
2021-02-25 14:18:47,540 - MainThread - botocore.hooks - DEBUG - Event needs-retry.sso-oidc.RegisterClient: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x000001F1AD118288>>
2021-02-25 14:18:47,542 - MainThread - botocore.retries.standard - DEBUG - Retry needed, retrying request after delay of: 0.3786081389079389
2021-02-25 14:18:47,543 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.3786081389079389 seconds
2021-02-25 14:18:47,923 - MainThread - botocore.hooks - DEBUG - Event request-created.sso-oidc.RegisterClient: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x000001F1ACA62208>>
2021-02-25 14:18:47,924 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sso-oidc.RegisterClient: calling handler <function set_operation_specific_signer at 0x000001F1AB3BF558>
2021-02-25 14:18:47,925 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://oidc.eu-central-1.amazonaws.com/client/register, headers={'User-Agent': b'aws-cli/2.1.27 Python/3.7.9 Windows/10 exe/AMD64 prompt/off command/configure.sso', 'Content-Length': '68'}>
2021-02-25 14:18:47,926 - MainThread - botocore.httpsession - DEBUG - Certificate path: C:\Program Files\Amazon\AWSCLIV2\botocore\cacert.pem
2021-02-25 14:18:47,927 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): oidc.eu-central-1.amazonaws.com:443
2021-02-25 14:19:50,978 - MainThread - botocore.endpoint - DEBUG - Exception received when sending HTTP request.
Traceback (most recent call last):
  File "lib\site-packages\urllib3\connection.py", line 170, in _new_conn
  File "lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
  File "lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\botocore\httpsession.py", line 320, in send
  File "lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
  File "lib\site-packages\urllib3\util\retry.py", line 506, in increment
  File "lib\site-packages\urllib3\packages\six.py", line 735, in reraise
  File "lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
  File "lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
  File "lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
  File "lib\site-packages\urllib3\connection.py", line 353, in connect
  File "lib\site-packages\urllib3\connection.py", line 182, in _new_conn
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x000001F1AD131608>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\botocore\endpoint.py", line 200, in _do_get_response
  File "lib\site-packages\botocore\endpoint.py", line 269, in _send
  File "lib\site-packages\botocore\httpsession.py", line 340, in send
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://oidc.eu-central-1.amazonaws.com/client/register"
2021-02-25 14:19:50,981 - MainThread - botocore.hooks - DEBUG - Event needs-retry.sso-oidc.RegisterClient: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x000001F1AD118288>>
2021-02-25 14:19:50,983 - MainThread - botocore.retries.standard - DEBUG - Retry needed, retrying request after delay of: 0.07694036458755504
2021-02-25 14:19:50,984 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.07694036458755504 seconds
2021-02-25 14:19:51,062 - MainThread - botocore.hooks - DEBUG - Event request-created.sso-oidc.RegisterClient: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x000001F1ACA62208>>
2021-02-25 14:19:51,062 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sso-oidc.RegisterClient: calling handler <function set_operation_specific_signer at 0x000001F1AB3BF558>
2021-02-25 14:19:51,065 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://oidc.eu-central-1.amazonaws.com/client/register, headers={'User-Agent': b'aws-cli/2.1.27 Python/3.7.9 Windows/10 exe/AMD64 prompt/off command/configure.sso', 'Content-Length': '68'}>
2021-02-25 14:19:51,066 - MainThread - botocore.httpsession - DEBUG - Certificate path: C:\Program Files\Amazon\AWSCLIV2\botocore\cacert.pem
2021-02-25 14:19:51,066 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): oidc.eu-central-1.amazonaws.com:443
2021-02-25 14:20:54,125 - MainThread - botocore.endpoint - DEBUG - Exception received when sending HTTP request.
Traceback (most recent call last):
  File "lib\site-packages\urllib3\connection.py", line 170, in _new_conn
  File "lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
  File "lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\botocore\httpsession.py", line 320, in send
  File "lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
  File "lib\site-packages\urllib3\util\retry.py", line 506, in increment
  File "lib\site-packages\urllib3\packages\six.py", line 735, in reraise
  File "lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
  File "lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
  File "lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
  File "lib\site-packages\urllib3\connection.py", line 353, in connect
  File "lib\site-packages\urllib3\connection.py", line 182, in _new_conn
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x000001F1ACE2F708>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\botocore\endpoint.py", line 200, in _do_get_response
  File "lib\site-packages\botocore\endpoint.py", line 269, in _send
  File "lib\site-packages\botocore\httpsession.py", line 340, in send
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://oidc.eu-central-1.amazonaws.com/client/register"
2021-02-25 14:20:54,127 - MainThread - botocore.hooks - DEBUG - Event needs-retry.sso-oidc.RegisterClient: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x000001F1AD118288>>
2021-02-25 14:20:54,129 - MainThread - botocore.retries.standard - DEBUG - Max attempts of 3 reached.
2021-02-25 14:20:54,130 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2021-02-25 14:20:54,130 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "lib\site-packages\urllib3\connection.py", line 170, in _new_conn
  File "lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
  File "lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\botocore\httpsession.py", line 320, in send
  File "lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
  File "lib\site-packages\urllib3\util\retry.py", line 506, in increment
  File "lib\site-packages\urllib3\packages\six.py", line 735, in reraise
  File "lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
  File "lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
  File "lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
  File "lib\site-packages\urllib3\connection.py", line 353, in connect
  File "lib\site-packages\urllib3\connection.py", line 182, in _new_conn
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x000001F1ACE2F708>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\awscli\clidriver.py", line 457, in main
  File "lib\site-packages\awscli\customizations\commands.py", line 198, in __call__
  File "lib\site-packages\awscli\customizations\commands.py", line 191, in __call__
  File "lib\site-packages\awscli\customizations\configure\sso.py", line 302, in _run_main
  File "lib\site-packages\awscli\customizations\sso\utils.py", line 59, in do_sso_login
  File "lib\site-packages\botocore\utils.py", line 2316, in fetch_token
  File "lib\site-packages\botocore\utils.py", line 2311, in _token
  File "lib\site-packages\botocore\utils.py", line 2265, in _poll_for_token
  File "lib\site-packages\botocore\utils.py", line 2239, in _registration
  File "lib\site-packages\botocore\utils.py", line 2218, in _register_client
  File "lib\site-packages\botocore\client.py", line 249, in _api_call
  File "lib\site-packages\botocore\client.py", line 555, in _make_api_call
  File "lib\site-packages\botocore\client.py", line 574, in _make_request
  File "lib\site-packages\botocore\endpoint.py", line 102, in make_request
  File "lib\site-packages\botocore\endpoint.py", line 156, in _send_request
  File "lib\site-packages\botocore\endpoint.py", line 200, in _do_get_response
  File "lib\site-packages\botocore\endpoint.py", line 269, in _send
  File "lib\site-packages\botocore\httpsession.py", line 340, in send
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://oidc.eu-central-1.amazonaws.com/client/register"

Could not connect to the endpoint URL: "https://oidc.eu-central-1.amazonaws.com/client/register"

**Additional context**
This works on the browser though Edge/Chrome

**Comment by jacobneroth** [comment]
this works when using docker
![image](https://user-images.githubusercontent.com/1866864/109172020-9d184780-7782-11eb-906b-67b92c128fd0.png)

**Comment by stobrien89** [comment]
Hi @jacobneroth,

Thanks for writing in! I'm thinking this may be more of an issue with OIDC than sso— have you [registered the CLI as a OIDC client](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sso-oidc/register-client.html)?

**Comment by jacobneroth** [comment]
I did experiment with few tools oidc and might have registered the cli by accident , any idea how I unregister? I could find any documentations on that

**Comment by jacobneroth** [comment]
aws sso-oidc register-client --client-name test --client-type public , this is what i tried.

**Comment by stobrien89** [comment]
Hi @jacobneroth,

You should be able to remove/unregister a client by using (iam) [remove-client-id-from-open-id-connect-provider](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/get-open-id-connect-provider.html) —the `open-id-connect-provider-arn` and `client-id` are required, but you can grab the arn by calling (iam) [list-open-id-connect-providers](https://docs.aws.amazon.com/cli/latest/reference/iam/list-open-id-connect-providers.html) and then grab the `client-id` by calling (iam) [get-open-id-connect-provider](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/get-open-id-connect-provider.html), if you don't happen to know it.  

Are you saying you didn't intend to enable oidc? If so, that should hopefully do the trick, but I would also check the IAM console to ensure you don't have any active identity providers.

**Comment by jacobneroth** [comment]
I dont have an IAM configured, using the company sso. Is there anyway to undo what i did ?

**Comment by jacobneroth** [comment]
Is there a cache file or something which i can delete in my PC to get it working :)

**Comment by jacobneroth** [comment]
Sigh, i send to my admin team, no response yet.
Now when i run my .net application locally for debugging , this change has inadvertently affected that as well
the .net appliication now thing my pc is an ec2.
"Unable to get IAM security credentials from EC2 Instance Metadata Service."

**Comment by stobrien89** [comment]
Hi @jacobneroth,

Thanks for the update!  I'll keep an eye out for your response.
