### ISSUE TITLE
Installation fails on fresh install of Windows via pipx

### ISSUE THREAD

**Issue by ericfrederich** [aws/aws-cli#5990]
# Reproduce
- Fresh install of Windows.
- Download and install latest python from [python.org](https://www.python.org/).
- Install [pipx](https://pipxproject.github.io/pipx/) via commands:
  - `py -m pip install --user pipx`
  - `py -m pipx ensurepath`
- Reboot
- Attempt to install `awscli` via:
  - `pipx install awscli`
- Try to run `aws`, nothing happens.

# Analysis
The file aws.cmd ends up getting called.  It tries (and succeeds in) finding a `python.exe` at `C:\Users\xxx\AppData\Local\Microsoft\WindowsApps\python.exe`.
This logic is no longer valid as Microsoft started shipping Windows 10 with a `python.exe` which simply opens up the app store.
Though, when running `aws` from a terminal nothing happens, the store doesn't even open.

**Comment by kdaily** [comment]
Hi @ericfrederich,

Thanks for the information. We don't officially support `pipx` as an installation mechanism. Does this still fail using the Windows `pip` installation instructions? I'll look into it some more as well.

https://docs.aws.amazon.com/cli/latest/userguide/install-windows.html#awscli-install-windows-pip

Are you able to use the AWS CLI V2, which installs via an MSI?

**Comment by ericfrederich** [comment]
@kdaily I have no doubt it works fine via `pip`.

`pipx` should have no problem installing Python packages.  If it can be installed via `pip`, then `pipx` should work as well.  The problem is this `awscli` is trying to be too smart for its own good.  Any other package I install via `pipx` I get a nice `.exe` file for each of the scripts it installs.

See all these `.exe` files in my `.local\bin` directory.  They all work just fine.

```
black-primer.exe
black.exe
blackd.exe
isort-identify-imports.exe
isort.exe
poetry.exe
pygmentize.exe
youtube-dl.exe
```

Then you install `awscli` and get all this stuff:

```
aws
aws.cmd
aws_bash_completer
aws_completer
aws_zsh_completer.sh
```

I just ran it on another Windows machine I have.

```
C:\Users\ericf>aws
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
```


Regarding AWS CLI V2, since you asked, I have no desire to use it until many issues are addressed.  It can't be installed via pip even if you clone the repo, doesn't work on Alpine Linux, can't be ran as a Python module, cannot be stepped through a debugger.  That thing is a giant mess.

**Comment by RoelantStegmann** [comment]
I have a very similar issue, just with the error 

```
File association not found for extension .py
Traceback (most recent call last):
  File "c:\Users\RoelantStegmann\.local\bin\aws.cmd", line 50, in <module>
    import awscli.clidriver
ModuleNotFoundError: No module named 'awscli'
```

I used to be able to install it via pipx so it's sad it no longer works!

**Comment by netsettler** [comment]
> File association not found for extension .py

This issue is separate from the no module named 'awscli' problem.

This is addressed in https://stackoverflow.com/questions/47459536/file-association-not-found-for-extension-py

> Traceback (most recent call last):
>   File "c:\Users\dd\.local\bin\aws.cmd", line 50, in <module>
>     import awscli.clidriver
> ModuleNotFoundError: No module named 'awscli'

This is a separate problem. I believe (and have [separately reported at Amazon's re:Post forum](https://repost.aws/questions/QU86sthXHcTxaGJ8oJSU1ATw/aws-command-installed-with-awscli-library-inside-a-python-venv-on-windows-invokes-a-python-outside-the-venv), where I offer additional detail) that this is because the python that the `aws.cmd` script installed by `awscli` (I'm using awscli 1.25.86) ends up looking around for a python to execute and finds one _outside_ the virtual environment when you've just installed awscli _inside_ the virtual environment. So until they issue a solution, my personal workaround recommendation is:
```
deactivate
pip install awscli
VENV\scripts\activate
```
to install the awscli library _also_ in your global environment. (You'll have to replace VENV with the name of your own virtual environment in that example.)

**Comment by adehad** [comment]
An alternative workaround to the `ModuleNotFoundError: No module named 'awscli'` I have is the following:

```bash
# For whatever reason this kept waiting for ages to find the package name
# pipx install git+https://github.com/aws/aws-cli.git@v2 

# This is a workaround
pipx install awscli
pipx runpip awscli install git+https://github.com/aws/aws-cli.git@v2 --force --upgrade   

# Then open the offending aws.cmd file
notepad "%USERPROFILE%\.local\bin\aws.cmd"
# notepad "$env:USERPROFILE\.local\bin\aws.cmd"
```

Then replace the contents of the `.cmd` with the following:

```bat
@echo OFF
%~dp0\..\pipx\venvs\awscli\Scripts\python.exe -c "import awscli.clidriver; import sys; sys.exit(awscli.clidriver.main())" %*
```

This relies on the pipx directory structure to use the awscli venv and then and then uses an equivalent python script to run, passing the command line arguments as appropriate.


@kdaily would strongly recommend you consider supporting pipx! Can make installation and upgrades trivial for such a simple cli without the need for managing executables.

**Comment by dmwyatt** [comment]
> The problem is this `awscli` is trying to be too smart for its own good. 

Yep!  This still isn't working correctly with pipx.
