### ISSUE TITLE
delete-item on powershell raises an Invalid JSON error regarding double quoted property name

### ISSUE THREAD

**Issue by dnarvaez27** [aws/aws-cli#6035]
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When executing the `delete-item` and passing a JSON string, despite of having the properties double quoted, the following error pop ups:

```
Error parsing parameter '--key': Invalid JSON: Expecting property name enclosed in double quotes: line 1 column 2 (char JSON received: {id1: {S:value1}, id2: {S:value2}}
```
Even though this is the command that is being executed
```
aws dynamodb delete-item --table-name TableName --key "{""id1"": {""S"": ""value1""}, ""id2"": {""S"":""value2""}}" --profile prod
```
When printing the key, the result is quoted

**SDK version number**

**Platform/OS/Hardware/Device**
What are you running the cli on?
Windoes/Powershell

**To Reproduce (observed behavior)**
Steps to reproduce the behavior  
Type the example of the AWS CLI for deleting an item with the key as a JSON string

**Expected behavior**
The item with the given key is deleted

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.
<details>
<summary>Traceback</summary>

<pre><code>
2021-03-23 14:51:52,175 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x0000012B3608BE58>
2021-03-23 14:51:52,176 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x0000012B35088288>
2021-03-23 14:51:52,176 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x0000012B360DD3A8>
2021-03-23 14:51:52,177 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x0000012B350AD8B8>
2021-03-23 14:51:52,181 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2021-03-23 14:51:52,182 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x0000012B35F47EE8>
2021-03-23 14:51:52,182 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x0000012B356F4EE8>
2021-03-23 14:51:52,230 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Software\AWSCLI\botocore\data\dynamodb\2012-08-10\service-2.json
2021-03-23 14:51:52,241 - MainThread - botocore.hooks - DEBUG - Event building-command-table.dynamodb: calling handler <function _add_wizard_command at 0x0000012B360D1DC8>
2021-03-23 14:51:52,242 - MainThread - botocore.hooks - DEBUG - Event building-command-table.dynamodb: calling handler <function add_waiters at 0x0000012B3609D8B8>
2021-03-23 14:51:52,287 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Software\AWSCLI\botocore\data\dynamodb\2012-08-10\waiters-2.json
2021-03-23 14:51:52,291 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('table-name', <awscli.arguments.CLIArgument object at 0x0000012B3628A308>), ('key', <awscli.arguments.CLIArgument object at 0x0000012B3628A4C8>), ('expected', <awscli.arguments.CLIArgument object at 0x0000012B3628A548>), ('conditional-operator', <awscli.arguments.CLIArgument object at 0x0000012B3628A588>), ('return-values', <awscli.arguments.CLIArgument object at 0x0000012B3628A688>), ('return-consumed-capacity', <awscli.arguments.CLIArgument object at 0x0000012B3628A608>), ('return-item-collection-metrics', <awscli.arguments.CLIArgument object at 0x0000012B3628A1C8>), ('condition-expression', <awscli.arguments.CLIArgument object at 0x0000012B3628A648>), ('expression-attribute-names', <awscli.arguments.CLIArgument object at 0x0000012B3628A6C8>), ('expression-attribute-values', <awscli.arguments.CLIArgument object at 0x0000012B36284988>)])
2021-03-23 14:51:52,292 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.dynamodb.delete-item: calling handler <function add_streaming_output_arg at 0x0000012B36093048>
2021-03-23 14:51:52,292 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.dynamodb.delete-item: calling handler <function add_cli_input_json at 0x0000012B350AFF78>
2021-03-23 14:51:52,293 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.dynamodb.delete-item: calling handler <function add_cli_input_yaml at 0x0000012B350B3AF8>
2021-03-23 14:51:52,293 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.dynamodb.delete-item: calling handler <function unify_paging_params at 0x0000012B3570A4C8>
2021-03-23 14:51:52,341 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Software\AWSCLI\botocore\data\dynamodb\2012-08-10\paginators-1.json
2021-03-23 14:51:52,341 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.dynamodb.delete-item: calling handler <function add_generate_skeleton at 0x0000012B35FF1828>
2021-03-23 14:51:52,342 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.dynamodb.delete-item: calling handler <function add_auto_prompt at 0x0000012B360D7558>
2021-03-23 14:51:52,343 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.dynamodb.delete-item: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x0000012B3628A788>>
2021-03-23 14:51:52,343 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.dynamodb.delete-item: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x0000012B3628A208>>
2021-03-23 14:51:52,343 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.dynamodb.delete-item: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x0000012B36296F08>>
2021-03-23 14:51:52,344 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.dynamodb.delete-item: calling handler <bound method AutoPromptArgument.override_required_args of <awscli.customizations.autoprompt.AutoPromptArgument object at 0x0000012B34E51C08>>
2021-03-23 14:51:52,346 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.dynamodb.delete-item.table-name: calling handler <awscli.paramfile.URIArgumentHandler object at 0x0000012B36169108>
2021-03-23 14:51:52,346 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.dynamodb.delete-item: calling handler <awscli.argprocess.ParamShorthandParser object at 0x0000012B3507AF48>
2021-03-23 14:51:52,347 - MainThread - awscli.arguments - DEBUG - Unpacked value of '\\TableName' for parameter "table_name": '\\TableName'
2021-03-23 14:51:52,347 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.dynamodb.delete-item.key: calling handler <awscli.paramfile.URIArgumentHandler object at 0x0000012B36169108>
2021-03-23 14:51:52,347 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.dynamodb.delete-item: calling handler <awscli.argprocess.ParamShorthandParser object at 0x0000012B3507AF48>
2021-03-23 14:51:52,348 - MainThread - awscli.argprocess - DEBUG - Param key looks like JSON, not considered for param shorthand.
2021-03-23 14:51:52,348 - MainThread - awscli.clidriver - DEBUG - Client side parameter validation failed
Traceback (most recent call last):
  File "site-packages\awscli\argprocess.py", line 182, in _unpack_complex_cli_arg
  File "json\__init__.py", line 361, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\awscli\clidriver.py", line 335, in main
  File "site-packages\awscli\clidriver.py", line 507, in __call__
  File "site-packages\awscli\clidriver.py", line 656, in __call__
  File "site-packages\awscli\clidriver.py", line 712, in _build_call_parameters
  File "site-packages\awscli\arguments.py", line 453, in add_to_params
  File "site-packages\awscli\arguments.py", line 470, in _unpack_argument
  File "site-packages\awscli\argprocess.py", line 143, in unpack_cli_arg
  File "site-packages\awscli\argprocess.py", line 163, in _unpack_cli_arg
  File "site-packages\awscli\argprocess.py", line 186, in _unpack_complex_cli_arg
awscli.argprocess.ParamError: Error parsing parameter '--key': Invalid JSON: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
JSON received: {id1: {S:value1}, id2: {S:value2}}

</code></pre>
</details>

**Additional context**
This worked well on CMD, but not sure if this is a powershell issue

**Comment by nateprewitt** [comment]
Hey @dnarvaez27,

Thanks for reaching out. The user guide provides a [section](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-parameters-quoting-strings.html#powershell) on "Using quotation marks inside strings". You'll see under the Powershell section that double quoting inside of a double quoted string won't work in this case.

You'll need to backtick (`) escape the double quotes, or more simply use a single quote to begin and end the string. We've also included a reference guide from Microsoft in this section for further clarity.

**Comment by dnarvaez27** [comment]
I also tried with a single quoted string (but forgot to mention) and just to be more clear this is what it is being executed with the single quoted one.
```
aws dynamodb delete-item --table-name TableName --key '{"id1": {"S": "value1"}, "id2": {"S": "value2"}}'
```

Just tested it and returned the same error.

This is the version of the CLI: `aws-cli/2.0.1 Python/3.7.5 Windows/10 botocore/2.0.0dev5`

**Comment by stobrien89** [comment]
Hi @dnarvaez27, 

Thanks for the additional info! I was able to reproduce on cli version `2.1.27` using both the single quoted and double-quoted/ escaped quote variants.  Going to mark this as a bug for now.  

I did test file input and that appears to be working.  If you create a json file with your key information and provide it like `--key file://key.json`, that should suffice as a workaround for the time being.

**Comment by nateprewitt** [comment]
So I took a deeper look at what's going on here and this appears to be a documentation issue rather than a bug. If we look at the debug logs, the parameters being handed to the CLI from the terminal have already had all double quotes stripped by Powershell.

```
2021-03-25 10:13:48,188 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['dynamodb', 'delete-item', '--table-name', 'TableName', '--key', '{id1: {S: value1}, id2: {S: value2}}', '--debug']
```

We don't have control over input prior to reaching the CLI, so we'll need to provide better guidance here. The recommendation for single quotes seems to only work on *nix style shells. For windows, you'll either need to pass the file directly or escape the double quotes with backticks (`) or backslash (\\).

**Comment by stobrien89** [comment]
After doing some more testing this morning, I found that while escaping quotes using backticks did not work on either a single-quoted or double-quoted string, escaping the quotes using a backslash in a single-quoted string works: 

`--key '{\"id1\": {\"S\": \"value1\"}, \"id2\": {\"S\": \"value2\"}}'`

This does not appear to work with a double-quoted string. I tested on both Powershell 5.1 and 7.1, but behavior _may_ vary depending on the version you're using.

**Comment by stobrien89** [comment]
Closing, as our [documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-parameters-quoting-strings.html#powershell) in reference to Powershell string escaping has been updated to reflect the possibility of this behavior.
