### ISSUE TITLE
`configure list` command slow on Windows

### ISSUE THREAD

**Issue by llamafilm** [aws/aws-cli#6127]
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [x] CLI : passing arguments or cli configurations.

**Platform/OS/Hardware/Device**
Windows 10 local workstation

**Describe the question**
I use a third party software which calls `aws configure list` often to see what any credentials are available.  This command takes about 5 seconds, even if I delete the credentials file.  Same problem observed in Powershell and git bash.  This happens because it tries to reach the EC2 instance metadata IP even though I am running on prem.

macOS does not have this problem

```
PS C:\> (Measure-Command {aws configure list}).TotalSeconds
4.8309963
```

**Logs/output**
```
PS C:\> aws configure list --debug
2021-04-28 11:00:34,085 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.39 Python/3.8.8 Windows/10 exe/AMD64
2021-04-28 11:00:34,085 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['configure', 'list', '--debug']
2021-04-28 11:00:34,179 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x000001E44785BCA0>
2021-04-28 11:00:34,179 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x000001E4476C8D30>
2021-04-28 11:00:34,179 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2021-04-28 11:00:34,179 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x000001E4476724C0>
2021-04-28 11:00:34,179 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x000001E44767B5E0>
2021-04-28 11:00:34,179 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x000001E44786E700>
2021-04-28 11:00:34,179 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x000001E447718B80>
2021-04-28 11:00:34,179 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2021-04-28 11:00:34,179 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x000001E447865940>
2021-04-28 11:00:34,194 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\awscli\data\cli.json
2021-04-28 11:00:34,194 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x000001E4477C7B80>
2021-04-28 11:00:34,194 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x000001E4477CB700>
2021-04-28 11:00:34,194 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x000001E4477CB670>
2021-04-28 11:00:34,194 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x000001E4477CB820>
2021-04-28 11:00:34,194 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x000001E4477CB790>
2021-04-28 11:00:34,194 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x000001E447900D80>
2021-04-28 11:00:34,194 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.39 Python/3.8.8 Windows/10 exe/AMD64 prompt/off
2021-04-28 11:00:34,194 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['configure', 'list', '--debug']
2021-04-28 11:00:34,194 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x000001E44785E310>
2021-04-28 11:00:34,194 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x000001E446C18EE0>
2021-04-28 11:00:34,194 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x000001E4478CA160>
2021-04-28 11:00:34,194 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x000001E446C15310>
2021-04-28 11:00:34,194 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x000001E446C6FA60>
2021-04-28 11:00:34,194 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-04-28 11:00:34,194 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x000001E447718A60>
2021-04-28 11:00:34,194 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x000001E4476CBC10>
2021-04-28 11:00:34,194 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure: calling handler <function _add_wizard_command at 0x000001E4478CA0D0>
2021-04-28 11:00:34,194 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure: calling handler <function add_waiters at 0x000001E447865940>
2021-04-28 11:00:34,194 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.configure.anonymous: calling handler <awscli.paramfile.URIArgumentHandler object at 0x000001E447944220>
2021-04-28 11:00:34,194 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure_list: calling handler <function add_waiters at 0x000001E447865940>
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
2021-04-28 11:00:34,194 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2021-04-28 11:00:34,194 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2021-04-28 11:00:34,194 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2021-04-28 11:00:34,194 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2021-04-28 11:00:34,194 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2021-04-28 11:00:34,194 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: custom-process
2021-04-28 11:00:34,194 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: config-file
2021-04-28 11:00:34,194 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: ec2-credentials-file
2021-04-28 11:00:34,194 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: boto-config
2021-04-28 11:00:34,194 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: container-role
2021-04-28 11:00:34,194 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: iam-role
2021-04-28 11:00:34,194 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 169.254.169.254:80
2021-04-28 11:00:35,195 - MainThread - botocore.utils - DEBUG - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/api/token: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
Traceback (most recent call last):
  File "urllib3\connection.py", line 169, in _new_conn
  File "urllib3\util\connection.py", line 96, in create_connection
  File "urllib3\util\connection.py", line 86, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore\httpsession.py", line 314, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 507, in increment
  File "urllib3\packages\six.py", line 735, in reraise
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 394, in _make_request
  File "urllib3\connection.py", line 234, in request
  File "http\client.py", line 1255, in request
  File "botocore\awsrequest.py", line 92, in _send_request
  File "http\client.py", line 1301, in _send_request
  File "http\client.py", line 1250, in endheaders
  File "botocore\awsrequest.py", line 120, in _send_output
  File "botocore\awsrequest.py", line 204, in send
  File "http\client.py", line 950, in send
  File "urllib3\connection.py", line 200, in connect
  File "urllib3\connection.py", line 174, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x000001E447944D30>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore\utils.py", line 302, in _fetch_metadata_token
  File "botocore\httpsession.py", line 347, in send
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
2021-04-28 11:00:35,195 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): 169.254.169.254:80
2021-04-28 11:00:36,199 - MainThread - botocore.utils - DEBUG - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/meta-data/iam/security-credentials/: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/iam/security-credentials/"
Traceback (most recent call last):
  File "urllib3\connection.py", line 169, in _new_conn
  File "urllib3\util\connection.py", line 96, in create_connection
  File "urllib3\util\connection.py", line 86, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore\httpsession.py", line 314, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 507, in increment
  File "urllib3\packages\six.py", line 735, in reraise
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 394, in _make_request
  File "urllib3\connection.py", line 234, in request
  File "http\client.py", line 1255, in request
  File "botocore\awsrequest.py", line 92, in _send_request
  File "http\client.py", line 1301, in _send_request
  File "http\client.py", line 1250, in endheaders
  File "botocore\awsrequest.py", line 120, in _send_output
  File "botocore\awsrequest.py", line 204, in send
  File "http\client.py", line 950, in send
  File "urllib3\connection.py", line 200, in connect
  File "urllib3\connection.py", line 174, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x000001E44797F1F0>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore\utils.py", line 350, in _get_request
  File "botocore\httpsession.py", line 347, in send
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/iam/security-credentials/"
2021-04-28 11:00:36,199 - MainThread - botocore.utils - DEBUG - Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
access_key                <not set>             None    None
secret_key                <not set>             None    None
2021-04-28 11:00:36,199 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-04-28 11:00:36,215 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 169.254.169.254:80
2021-04-28 11:00:37,228 - MainThread - botocore.utils - DEBUG - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/api/token: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
Traceback (most recent call last):
  File "urllib3\connection.py", line 169, in _new_conn
  File "urllib3\util\connection.py", line 96, in create_connection
  File "urllib3\util\connection.py", line 86, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore\httpsession.py", line 314, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 507, in increment
  File "urllib3\packages\six.py", line 735, in reraise
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 394, in _make_request
  File "urllib3\connection.py", line 234, in request
  File "http\client.py", line 1255, in request
  File "botocore\awsrequest.py", line 92, in _send_request
  File "http\client.py", line 1301, in _send_request
  File "http\client.py", line 1250, in endheaders
  File "botocore\awsrequest.py", line 120, in _send_output
  File "botocore\awsrequest.py", line 204, in send
  File "http\client.py", line 950, in send
  File "urllib3\connection.py", line 200, in connect
  File "urllib3\connection.py", line 174, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x000001E44797F3A0>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore\utils.py", line 302, in _fetch_metadata_token
  File "botocore\httpsession.py", line 347, in send
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
2021-04-28 11:00:37,228 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): 169.254.169.254:80
2021-04-28 11:00:38,244 - MainThread - botocore.utils - DEBUG - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/meta-data/placement/availability-zone/: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/placement/availability-zone/"
Traceback (most recent call last):
  File "urllib3\connection.py", line 169, in _new_conn
  File "urllib3\util\connection.py", line 96, in create_connection
  File "urllib3\util\connection.py", line 86, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore\httpsession.py", line 314, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 507, in increment
  File "urllib3\packages\six.py", line 735, in reraise
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 394, in _make_request
  File "urllib3\connection.py", line 234, in request
  File "http\client.py", line 1255, in request
  File "botocore\awsrequest.py", line 92, in _send_request
  File "http\client.py", line 1301, in _send_request
  File "http\client.py", line 1250, in endheaders
  File "botocore\awsrequest.py", line 120, in _send_output
  File "botocore\awsrequest.py", line 204, in send
  File "http\client.py", line 950, in send
  File "urllib3\connection.py", line 200, in connect
  File "urllib3\connection.py", line 174, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x000001E44798A190>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore\utils.py", line 350, in _get_request
  File "botocore\httpsession.py", line 347, in send
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/placement/availability-zone/"
2021-04-28 11:00:38,244 - MainThread - awscli.utils - DEBUG - Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
    region                <not set>             None    None
PS C:\>
```

**Comment by stobrien89** [comment]
Hi @llamafilm,

Thanks for the report— Looking further into this.  Out of curiosity, what software are you using to call `configure list`?

**Comment by llamafilm** [comment]
I don't think that's relevant but thank you for looking into this.

**Comment by stobrien89** [comment]
Hi @llamafilm,

I'm thinking the disparity you're seeing between MacOS and Windows could just be the system defaults for connection timeouts. Does setting `AWS_EC2_METADATA_DISABLED` to `true` resolve this for you?

**Comment by llamafilm** [comment]
On macOS it does not try to connect to that IP at all, it only looks in these places:
```
2021-04-29 16:37:12,980 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2021-04-29 16:37:12,981 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2021-04-29 16:37:12,981 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2021-04-29 16:37:12,981 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2021-04-29 16:37:12,981 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
```

Notice how on Windows it looks in more places.  I think it's supposed to do that when running in EC2, but I have no idea why it's doing this on my local workstation.

I tried setting that variable but it didn't make a difference.

**Comment by stobrien89** [comment]
Hi @llamafilm, 

My apologies for leading you astray with the env var. I took another look at your debug logs and how the credential chain works and was able to reproduce this on my mac after wiping all credential sources from my machine. This is expected behavior.

```
~ % time aws configure list --debug
2021-04-30 13:22:16,745 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.38 Python/3.8.8 Darwin/19.6.0 exe/x86_64
2021-04-30 13:22:16,745 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['configure', 'list', '--debug']
2021-04-30 13:22:16,769 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x7fbbf37e8940>
2021-04-30 13:22:16,769 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x7fbbf365a310>
2021-04-30 13:22:16,769 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2021-04-30 13:22:16,770 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7fbbf35fda60>
2021-04-30 13:22:16,770 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7fbbf3608a60>
2021-04-30 13:22:16,770 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x7fbbf37fd3a0>
2021-04-30 13:22:16,770 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x7fbbf36a70d0>
2021-04-30 13:22:16,770 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2021-04-30 13:22:16,770 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x7fbbf37f45e0>
2021-04-30 13:22:16,770 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/data/cli.json
2021-04-30 13:22:16,773 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x7fbbf3755b80>
2021-04-30 13:22:16,773 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x7fbbf3759700>
2021-04-30 13:22:16,773 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x7fbbf3759670>
2021-04-30 13:22:16,773 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x7fbbf3759820>
2021-04-30 13:22:16,773 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x7fbbf3759790>
2021-04-30 13:22:16,773 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x7fbbf39912c0>
2021-04-30 13:22:16,773 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.38 Python/3.8.8 Darwin/19.6.0 exe/x86_64 prompt/off
2021-04-30 13:22:16,773 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['configure', 'list', '--debug']
2021-04-30 13:22:16,773 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7fbbf37e8f70>
2021-04-30 13:22:16,773 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7fbbf32e40d0>
2021-04-30 13:22:16,773 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7fbbf3956a60>
2021-04-30 13:22:16,773 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x7fbbf32b1550>
2021-04-30 13:22:16,774 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7fbbf340c940>
2021-04-30 13:22:16,775 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-04-30 13:22:16,781 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7fbbf36a5f70>
2021-04-30 13:22:16,781 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7fbbf36571f0>
2021-04-30 13:22:16,781 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure: calling handler <function _add_wizard_command at 0x7fbbf39569d0>
2021-04-30 13:22:16,781 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure: calling handler <function add_waiters at 0x7fbbf37f45e0>
2021-04-30 13:22:16,782 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.configure.anonymous: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fbbf39ce550>
2021-04-30 13:22:16,782 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure_list: calling handler <function add_waiters at 0x7fbbf37f45e0>
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
2021-04-30 13:22:16,783 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2021-04-30 13:22:16,783 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2021-04-30 13:22:16,783 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2021-04-30 13:22:16,783 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2021-04-30 13:22:16,783 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2021-04-30 13:22:16,783 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: custom-process
2021-04-30 13:22:16,783 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: config-file
2021-04-30 13:22:16,783 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: ec2-credentials-file
2021-04-30 13:22:16,784 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: boto-config
2021-04-30 13:22:16,784 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: container-role
2021-04-30 13:22:16,784 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: iam-role
2021-04-30 13:22:16,784 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 169.254.169.254:80
2021-04-30 13:22:17,789 - MainThread - botocore.utils - DEBUG - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/api/token: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
Traceback (most recent call last):
  File "urllib3/connection.py", line 169, in _new_conn
  File "urllib3/util/connection.py", line 96, in create_connection
  File "urllib3/util/connection.py", line 86, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore/httpsession.py", line 314, in send
  File "urllib3/connectionpool.py", line 755, in urlopen
  File "urllib3/util/retry.py", line 507, in increment
  File "urllib3/packages/six.py", line 735, in reraise
  File "urllib3/connectionpool.py", line 699, in urlopen
  File "urllib3/connectionpool.py", line 394, in _make_request
  File "urllib3/connection.py", line 234, in request
  File "http/client.py", line 1255, in request
  File "botocore/awsrequest.py", line 92, in _send_request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "botocore/awsrequest.py", line 120, in _send_output
  File "botocore/awsrequest.py", line 204, in send
  File "http/client.py", line 950, in send
  File "urllib3/connection.py", line 200, in connect
  File "urllib3/connection.py", line 174, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x7fbbf39f0fd0>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore/utils.py", line 302, in _fetch_metadata_token
  File "botocore/httpsession.py", line 347, in send
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
2021-04-30 13:22:17,790 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): 169.254.169.254:80
2021-04-30 13:22:18,795 - MainThread - botocore.utils - DEBUG - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/meta-data/iam/security-credentials/: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/iam/security-credentials/"
Traceback (most recent call last):
  File "urllib3/connection.py", line 169, in _new_conn
  File "urllib3/util/connection.py", line 96, in create_connection
  File "urllib3/util/connection.py", line 86, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore/httpsession.py", line 314, in send
  File "urllib3/connectionpool.py", line 755, in urlopen
  File "urllib3/util/retry.py", line 507, in increment
  File "urllib3/packages/six.py", line 735, in reraise
  File "urllib3/connectionpool.py", line 699, in urlopen
  File "urllib3/connectionpool.py", line 394, in _make_request
  File "urllib3/connection.py", line 234, in request
  File "http/client.py", line 1255, in request
  File "botocore/awsrequest.py", line 92, in _send_request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "botocore/awsrequest.py", line 120, in _send_output
  File "botocore/awsrequest.py", line 204, in send
  File "http/client.py", line 950, in send
  File "urllib3/connection.py", line 200, in connect
  File "urllib3/connection.py", line 174, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x7fbbf3b094f0>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore/utils.py", line 350, in _get_request
  File "botocore/httpsession.py", line 347, in send
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/iam/security-credentials/"
2021-04-30 13:22:18,796 - MainThread - botocore.utils - DEBUG - Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
access_key                <not set>             None    None
secret_key                <not set>             None    None
2021-04-30 13:22:18,796 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-04-30 13:22:18,797 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 169.254.169.254:80
2021-04-30 13:22:19,803 - MainThread - botocore.utils - DEBUG - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/api/token: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
Traceback (most recent call last):
  File "urllib3/connection.py", line 169, in _new_conn
  File "urllib3/util/connection.py", line 96, in create_connection
  File "urllib3/util/connection.py", line 86, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore/httpsession.py", line 314, in send
  File "urllib3/connectionpool.py", line 755, in urlopen
  File "urllib3/util/retry.py", line 507, in increment
  File "urllib3/packages/six.py", line 735, in reraise
  File "urllib3/connectionpool.py", line 699, in urlopen
  File "urllib3/connectionpool.py", line 394, in _make_request
  File "urllib3/connection.py", line 234, in request
  File "http/client.py", line 1255, in request
  File "botocore/awsrequest.py", line 92, in _send_request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "botocore/awsrequest.py", line 120, in _send_output
  File "botocore/awsrequest.py", line 204, in send
  File "http/client.py", line 950, in send
  File "urllib3/connection.py", line 200, in connect
  File "urllib3/connection.py", line 174, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x7fbbf3b098e0>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore/utils.py", line 302, in _fetch_metadata_token
  File "botocore/httpsession.py", line 347, in send
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
2021-04-30 13:22:19,804 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): 169.254.169.254:80
2021-04-30 13:22:20,808 - MainThread - botocore.utils - DEBUG - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/meta-data/placement/availability-zone/: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/placement/availability-zone/"
Traceback (most recent call last):
  File "urllib3/connection.py", line 169, in _new_conn
  File "urllib3/util/connection.py", line 96, in create_connection
  File "urllib3/util/connection.py", line 86, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore/httpsession.py", line 314, in send
  File "urllib3/connectionpool.py", line 755, in urlopen
  File "urllib3/util/retry.py", line 507, in increment
  File "urllib3/packages/six.py", line 735, in reraise
  File "urllib3/connectionpool.py", line 699, in urlopen
  File "urllib3/connectionpool.py", line 394, in _make_request
  File "urllib3/connection.py", line 234, in request
  File "http/client.py", line 1255, in request
  File "botocore/awsrequest.py", line 92, in _send_request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "botocore/awsrequest.py", line 120, in _send_output
  File "botocore/awsrequest.py", line 204, in send
  File "http/client.py", line 950, in send
  File "urllib3/connection.py", line 200, in connect
  File "urllib3/connection.py", line 174, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x7fbbf3b12850>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore/utils.py", line 350, in _get_request
  File "botocore/httpsession.py", line 347, in send
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/placement/availability-zone/"
2021-04-30 13:22:20,808 - MainThread - awscli.utils - DEBUG - Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
    region                <not set>             None    None
aws configure list --debug  0.47s user 0.16s system 13% cpu 4.739 total
```

If no credentials are found in a given source, botocore will continue searching through the list of possible credential sources.  In your case, since there are no credentials found on the machine or elsewhere, you'll run into a series of timeouts/retries, each of which last about 1 second.  Hope this helps!

**Comment by llamafilm** [comment]
Oh I get it now, thanks!  I misunderstood how the command worked before.  On my Windows machine I have only named profiles.  If I create a default profile then it works as expected.

**Comment by stobrien89** [comment]
@llamafilm, of course!  I didn't even think to ask if you had a default profile configured, but I'm glad this helped.  Let us know if anything else comes up!
