### ISSUE TITLE
aws  --cli-input-json error

### ISSUE THREAD

**Issue by UnixGeek83** [aws/aws-cli#6168]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [https://docs.aws.amazon.com/cli/latest/reference/cloudwatch/put-metric-alarm.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [x] Service API : I want to use the CLI to build out my CloudWatch metric alarms
- [x] CLI : aws cloudwatch put-metric-alarm --cli-input-json file://CloudWatch-alarm-config.json
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
RHEL 7?

**Describe the question**
I am running the following command "aws cloudwatch put-metric-alarm --cli-input-json file://CloudWatch-alarm-config.json"
and am receiving the following error "Error parsing parameter '--cli-input-json': Invalid type: expecting map, received <class 'list'>"
**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.
Below is the actual json file.  I want to expand it out using the same (proper) format:
[{
        "AlarmName": "VerifyS3Archival_Errors_Above-aevdngpalvan311",
        "AlarmDescription": "The VerifyS3Archival process has generated abnormal log entries in the past hour. Consult logs at: /van_logs/backend/AWS/VerifyS3Archival/",
        "ActionsEnabled": true,
        "OKActions": [
                "arn:aws:sns:us-east-1:318261208716:P-VAN-Application"
        ],
        "AlarmActions": [
                "arn:aws:sns:us-east-1:318261208716:P-VAN-Application"
        ],
        "InsufficientDataActions": [
                "arn:aws:sns:us-east-1:318261208716:P-VAN-Application"
        ],
        "MetricName": "verifys3archival_errors",
        "Namespace": "custom/aevdngpalvan311/verifys3archival_errors",
        "Statistic": "Maximum",
        "Period": 120,
        "EvaluationPeriods": 3,
        "DatapointsToAlarm": 3,
        "Threshold": 0,
        "ComparisonOperator": "GreaterThanThreshold",
        "TreatMissingData": "notBreaching"
}, {
        "AlarmName": "VerifyS3Archival_Activity_Below-aevdngpalvan311",
        "AlarmDescription": "VerifyS3Archival generates daily archiving checks of all files ingested into CLASS. An alarm indicates that this process is not running on cronjob or is erroring when doing so. Consult logs at: van_logs/backend/AWS/VerifyS3Archival/",
        "ActionsEnabled": true,
        "OKActions": [
                "arn:aws:sns:us-east-1:318261208716:P-VAN-Application"
        ],
        "AlarmActions": [
                "arn:aws:sns:us-east-1:318261208716:P-VAN-Application"
        ],
        "InsufficientDataActions": [
                "arn:aws:sns:us-east-1:318261208716:P-VAN-Application"
        ],
        "MetricName": "verifys3archival_activity",
        "Namespace": "custom/aevdngpalvan311/verifys3archival_activity",
        "Statistic": "Minimum",
        "Period": 120,
        "EvaluationPeriods": 3,
        "DatapointsToAlarm": 3,
        "Threshold": 1,
        "ComparisonOperator": "LessThanThreshold",
        "TreatMissingData": "notBreaching"
}, {
        "AlarmName": "CPU_Utilization-aevdngpalvan311",
        "AlarmDescription": "CPU Utilization exceeds 80% on aevdngpalvan311",
        "ActionsEnabled": true,
        "OKActions": [
                "arn:aws:sns:us-east-1:318261208716:P-VAN-Infrastructure"
        ],
        "AlarmActions": [
                "arn:aws:sns:us-east-1:318261208716:P-VAN-Infrastructure"
        ],
        "InsufficientDataActions": [
                "arn:aws:sns:us-east-1:318261208716:P-VAN-Infrastructure"
        ],
        "MetricName": "CPUUtilization",
        "Namespace": "AWS/EC2",
        "Dimensions": [{
                "Name": "InstanceId",
                "Value": "i-07a76130f073acae4"
        }],
        "Statistic": "Maximum",
        "Period": 120,
        "EvaluationPeriods": 3,
        "DatapointsToAlarm": 3,
        "Threshold": 80,
        "ComparisonOperator": "GreaterThanThreshold",
        "TreatMissingData": "notBreaching"
}]

 Below is the debug output:
$ aws cloudwatch put-metric-alarm --cli-input-json file://CloudWatch-aevdngpalvan311.json --debug
2021-05-13 16:27:49,827 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.0.54 Python/3.7.3 Linux/3.10.0-327.36.3.el7.x86_64 exe/x86_64.rhel.7
2021-05-13 16:27:49,827 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['cloudwatch', 'put-metric-alarm', '--cli-input-json', 'file://CloudWatch-aevdngpalvan311.json', '--debug']
2021-05-13 16:27:49,828 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7fcc9734d378>
2021-05-13 16:27:49,828 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7fcc97ae90d0>
2021-05-13 16:27:49,828 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7fcc9730e8c8>
2021-05-13 16:27:49,828 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x7fcc97b27598>
2021-05-13 16:27:49,828 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7fcc97b0c048>
2021-05-13 16:27:49,830 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7fcc97414d90>
2021-05-13 16:27:49,830 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7fcc974cc730>
2021-05-13 16:27:49,841 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.0.54/dist/botocore/data/cloudwatch/2010-08-01/service-2.json
2021-05-13 16:27:49,848 - MainThread - botocore.hooks - DEBUG - Event building-command-table.cloudwatch: calling handler <function add_waiters at 0x7fcc972d57b8>
2021-05-13 16:27:49,859 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.0.54/dist/botocore/data/cloudwatch/2010-08-01/waiters-2.json
2021-05-13 16:27:49,861 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('alarm-name', <awscli.arguments.CLIArgument object at 0x7fcc9717f160>), ('alarm-description', <awscli.arguments.CLIArgument object at 0x7fcc97186860>), ('actions-enabled', <awscli.arguments.BooleanArgument object at 0x7fcc97186898>), ('no-actions-enabled', <awscli.arguments.BooleanArgument object at 0x7fcc971868d0>), ('ok-actions', <awscli.arguments.ListArgument object at 0x7fcc97186940>), ('alarm-actions', <awscli.arguments.ListArgument object at 0x7fcc97186908>), ('insufficient-data-actions', <awscli.arguments.ListArgument object at 0x7fcc97186828>), ('metric-name', <awscli.arguments.CLIArgument object at 0x7fcc97186b00>), ('namespace', <awscli.arguments.CLIArgument object at 0x7fcc97186a20>), ('statistic', <awscli.arguments.CLIArgument object at 0x7fcc97186c18>), ('extended-statistic', <awscli.arguments.CLIArgument object at 0x7fcc97186c50>), ('dimensions', <awscli.arguments.ListArgument object at 0x7fcc97186c88>), ('period', <awscli.arguments.CLIArgument object at 0x7fcc97186d30>), ('unit', <awscli.arguments.CLIArgument object at 0x7fcc97186dd8>), ('evaluation-periods', <awscli.arguments.CLIArgument object at 0x7fcc97186e10>), ('datapoints-to-alarm', <awscli.arguments.CLIArgument object at 0x7fcc97186e48>), ('threshold', <awscli.arguments.CLIArgument object at 0x7fcc971869e8>), ('comparison-operator', <awscli.arguments.CLIArgument object at 0x7fcc97186ef0>), ('treat-missing-data', <awscli.arguments.CLIArgument object at 0x7fcc97186f60>), ('evaluate-low-sample-count-percentile', <awscli.arguments.CLIArgument object at 0x7fcc97186f98>), ('metrics', <awscli.arguments.ListArgument object at 0x7fcc97186fd0>), ('tags', <awscli.arguments.ListArgument object at 0x7fcc97186080>), ('threshold-metric-id', <awscli.arguments.CLIArgument object at 0x7fcc971860b8>)])
2021-05-13 16:27:49,861 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudwatch.put-metric-alarm: calling handler <function add_streaming_output_arg at 0x7fcc9734d620>
2021-05-13 16:27:49,861 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudwatch.put-metric-alarm: calling handler <function add_cli_input_json at 0x7fcc97b0c840>
2021-05-13 16:27:49,861 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudwatch.put-metric-alarm: calling handler <function add_cli_input_yaml at 0x7fcc97b0cea0>
2021-05-13 16:27:49,862 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudwatch.put-metric-alarm: calling handler <function unify_paging_params at 0x7fcc974d1ea0>
2021-05-13 16:27:49,873 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.0.54/dist/botocore/data/cloudwatch/2010-08-01/paginators-1.json
2021-05-13 16:27:49,873 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudwatch.put-metric-alarm: calling handler <function add_generate_skeleton at 0x7fcc973b1bf8>
2021-05-13 16:27:49,873 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudwatch.put-metric-alarm: calling handler <function add_auto_prompt at 0x7fcc9730e840>
2021-05-13 16:27:49,873 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cloudwatch.put-metric-alarm: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7fcc971860f0>>
2021-05-13 16:27:49,873 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cloudwatch.put-metric-alarm: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7fcc97183d68>>
2021-05-13 16:27:49,874 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cloudwatch.put-metric-alarm: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fcc97183c88>>
2021-05-13 16:27:49,874 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cloudwatch.put-metric-alarm: calling handler <bound method AutoPromptArgument.override_required_args of <awscli.customizations.autoprompt.AutoPromptArgument object at 0x7fcc97186208>>
2021-05-13 16:27:49,875 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.alarm-name: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,875 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.alarm-description: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,875 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.actions-enabled: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,875 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.ok-actions: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,876 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.alarm-actions: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,876 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.insufficient-data-actions: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,876 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.metric-name: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,876 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.namespace: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,876 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.statistic: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,876 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.extended-statistic: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,876 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.dimensions: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,876 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.period: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,876 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.unit: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,876 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.evaluation-periods: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,876 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.datapoints-to-alarm: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,876 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.threshold: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,876 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.comparison-operator: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,876 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.treat-missing-data: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,877 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.evaluate-low-sample-count-percentile: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,877 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.metrics: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,877 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.tags: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,877 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.threshold-metric-id: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,877 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,877 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.cli-input-yaml: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,877 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,877 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.monitoring.put-metric-alarm.cli-auto-prompt: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fcc97290438>
2021-05-13 16:27:49,877 - MainThread - botocore.hooks - DEBUG - Event calling-command.cloudwatch.put-metric-alarm: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7fcc971860f0>>
2021-05-13 16:27:49,878 - MainThread - awscli.clidriver - DEBUG - Client side parameter validation failed
Traceback (most recent call last):
  File "awscli/clidriver.py", line 386, in main
  File "awscli/clidriver.py", line 558, in __call__
  File "awscli/clidriver.py", line 715, in __call__
  File "awscli/clidriver.py", line 815, in _emit_first_non_none_response
  File "botocore/session.py", line 667, in emit_first_non_none_response
  File "botocore/hooks.py", line 227, in emit
  File "botocore/hooks.py", line 210, in _emit
  File "awscli/customizations/cliinput.py", line 68, in add_to_call_parameters
awscli.argprocess.ParamError: Error parsing parameter '--cli-input-json': Invalid type: expecting map, received <class 'list'>

Error parsing parameter '--cli-input-json': Invalid type: expecting map, received <class 'list'>

**Comment by stobrien89** [comment]
Hi @UnixGeek83,

Thanks for all of the info!  `put-metric-alarm` only supports creating/updating one alarm at a time, so multiple calls would be needed here.  Hope this helps!

**Comment by UnixGeek83** [comment]
Thank you very much.  That is a strange limitation.  It would be extremely useful if we could have a couple of json files to build out our alarms:
standard_fs - I could setup monitoring for /, /usr, /home, /tmp, /var, etc.  
instance_checks - I could setup memory, CPU, and instance health 

Then I could just modify the json files to change the system and instance id information...

**Comment by stobrien89** [comment]
Hi @UnixGeek83,

Of course!  I can definitely see how having the ability to create/update multiple alarms would be useful.  We could potentially submit a feature request (to the Cloudwatch team) for an additional Cloudwatch operation just due to semantics (`PutMetricAlarm` vs `PutMetricAlarms`), although I can't make any guarantees on their behalf as to when/if they would implement something like that.
