### ISSUE TITLE
Expected header "User Name" not found

### ISSUE THREAD

**Issue by anamorph** [aws/aws-cli#6174]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Credential import does not work as it is not matching the headers CaSe of the downloaded CSV file from the IAM console

**SDK version number**

**Platform/OS/Hardware/Device**
What are you running the cli on?
MacOS Catalina - 10.15.7 (19H1030)

**To Reproduce (observed behavior)**
`aws configure import --csv new_user_credentials.csv`

**Expected behavior**
Import CSV credentials generated from the AWS web console.

**Logs/output**
```
2021-05-17 00:52:01,707 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.32 Python/3.8.8 Darwin/19.6.0 exe/x86_64
2021-05-17 00:52:01,707 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['configure', 'import', '--csv', 'new_user_credentials.csv', '--debug']
2021-05-17 00:52:01,753 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x7f85d7e883a0>
2021-05-17 00:52:01,753 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x7f85d7cfbd30>
2021-05-17 00:52:01,753 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2021-05-17 00:52:01,753 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7f85d7ca0550>
2021-05-17 00:52:01,753 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7f85d7cab550>
2021-05-17 00:52:01,753 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x7f85d7e9adc0>
2021-05-17 00:52:01,754 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x7f85d7d43af0>
2021-05-17 00:52:01,754 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2021-05-17 00:52:01,754 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x7f85d7e9a040>
2021-05-17 00:52:01,755 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/data/cli.json
2021-05-17 00:52:01,760 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x7f85d7df85e0>
2021-05-17 00:52:01,761 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x7f85d7df9160>
2021-05-17 00:52:01,761 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x7f85d7df90d0>
2021-05-17 00:52:01,761 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x7f85d7df9280>
2021-05-17 00:52:01,762 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x7f85d7df91f0>
2021-05-17 00:52:01,762 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x7f85d8032480>
2021-05-17 00:52:01,762 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.32 Python/3.8.8 Darwin/19.6.0 exe/x86_64 prompt/off
2021-05-17 00:52:01,763 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['configure', 'import', '--csv', 'new_user_credentials.csv', '--debug']
2021-05-17 00:52:01,763 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7f85d7e889d0>
2021-05-17 00:52:01,763 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7f85d7a71d30>
2021-05-17 00:52:01,763 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7f85d7ef54c0>
2021-05-17 00:52:01,764 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x7f85d7a5f1f0>
2021-05-17 00:52:01,764 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f85d7af75e0>
2021-05-17 00:52:01,769 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-05-17 00:52:01,775 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f85d7d439d0>
2021-05-17 00:52:01,775 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7f85d7cfac10>
2021-05-17 00:52:01,775 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure: calling handler <function _add_wizard_command at 0x7f85d7ef5430>
2021-05-17 00:52:01,775 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure: calling handler <function add_waiters at 0x7f85d7e9a040>
2021-05-17 00:52:01,776 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.configure.anonymous: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f85d8062400>
2021-05-17 00:52:01,776 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure_import: calling handler <function add_waiters at 0x7f85d7e9a040>
2021-05-17 00:52:01,776 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.import.csv: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f85d8062400>
2021-05-17 00:52:01,777 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.import: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f85d7a95fa0>
2021-05-17 00:52:01,777 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.import.skip-invalid: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f85d8062400>
2021-05-17 00:52:01,777 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.import: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f85d7a95fa0>
2021-05-17 00:52:01,777 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.import.profile-prefix: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f85d8062400>
2021-05-17 00:52:01,777 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.import: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f85d7a95fa0>
2021-05-17 00:52:01,777 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/clidriver.py", line 457, in main
  File "awscli/customizations/commands.py", line 197, in __call__
  File "awscli/customizations/commands.py", line 191, in __call__
  File "awscli/customizations/configure/importer.py", line 95, in _run_main
  File "awscli/customizations/configure/importer.py", line 83, in _import_csv
  File "awscli/customizations/configure/importer.py", line 181, in parse_credentials
  File "awscli/customizations/configure/importer.py", line 164, in _parse_csv
  File "awscli/customizations/configure/importer.py", line 128, in _extract_expected_header_indices
awscli.customizations.configure.importer.CredentialParserError: Expected header "User Name" not found

Expected header "User Name" not found
```

**Additional context**
header "User Name" should read "User name" (as currently generated from AWS IAM Console)

**Comment by anamorph** [comment]
It may be a bit more complex than a case
