### ISSUE TITLE
Invalid choice: 'list-policy-tags' for AWS IAM CLI

### ISSUE THREAD

**Issue by fagiani** [aws/aws-cli#6182]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
According to https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/list-policy-tags.html describes the `aws iam list-policy-tags` command.

When running it returns:
```
Invalid choice: 'list-policy-tags', maybe you meant:

  * list-role-tags
```

**SDK version number**
aws-cli/2.1.16 Python/3.7.3 Linux/4.19.128-microsoft-standard exe/x86_64.ubuntu.20 prompt/off

**Platform/OS/Hardware/Device**
What are you running the cli on? Ubuntu Linux on WSL2

**To Reproduce (observed behavior)**
`aws iam list-policy-tags --policy-arn arn:aws:iam::123****453:policy/my-policy`

**Expected behavior**
List tags of the provided role.

**Logs/output**
```
2021-05-23 12:57:44,898 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.16 Python/3.7.3 Linux/4.19.128-microsoft-standard exe/x86_64.ubuntu.20
2021-05-23 12:57:44,899 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['iam', 'list-policy-tags', '--policy-arn', 'arn:aws:iam::12345678910:policy/my-policy', '--debug']
2021-05-23 12:57:44,907 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x7f43320beae8>
2021-05-23 12:57:44,907 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x7f43322b59d8>
2021-05-23 12:57:44,907 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2021-05-23 12:57:44,907 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7f43322d5f28>
2021-05-23 12:57:44,907 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7f43322ddc80>
2021-05-23 12:57:44,907 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x7f43320d2268>
2021-05-23 12:57:44,907 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x7f43322020d0>
2021-05-23 12:57:44,907 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2021-05-23 12:57:44,907 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x7f43320c9510>
2021-05-23 12:57:44,907 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.1.16/dist/awscli/data/cli.json
2021-05-23 12:57:44,910 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x7f43321abc80>
2021-05-23 12:57:44,910 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x7f43321abf28>
2021-05-23 12:57:44,910 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x7f43321abea0>
2021-05-23 12:57:44,910 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x7f43321af0d0>
2021-05-23 12:57:44,910 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x7f43321af048>
2021-05-23 12:57:44,911 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x7f433206e8b8>
2021-05-23 12:57:44,911 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.16 Python/3.7.3 Linux/4.19.128-microsoft-standard exe/x86_64.ubuntu.20 prompt/off
2021-05-23 12:57:44,911 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['iam', 'list-policy-tags', '--policy-arn', 'arn:aws:iam::12345678910:policy/my-policy', '--debug']
2021-05-23 12:57:44,912 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7f43320c20d0>
2021-05-23 12:57:44,912 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7f43326900d0>
2021-05-23 12:57:44,912 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7f43320aba60>
2021-05-23 12:57:44,912 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x7f43326c5ea0>
2021-05-23 12:57:44,912 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f43326b6268>
2021-05-23 12:57:44,913 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-05-23 12:57:44,914 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f4332200f28>
2021-05-23 12:57:44,915 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7f43322b28c8>
2021-05-23 12:57:44,921 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.1.16/dist/botocore/data/iam/2010-05-08/service-2.json
2021-05-23 12:57:44,933 - MainThread - botocore.hooks - DEBUG - Event building-command-table.iam: calling handler <function _add_wizard_command at 0x7f43320ab9d8>
2021-05-23 12:57:44,933 - MainThread - botocore.hooks - DEBUG - Event building-command-table.iam: calling handler <function add_waiters at 0x7f43320c9510>
2021-05-23 12:57:44,939 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.1.16/dist/botocore/data/iam/2010-05-08/waiters-2.json
2021-05-23 12:57:44,941 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "argparse.py", line 1781, in parse_known_args
  File "argparse.py", line 1969, in _parse_known_args
  File "argparse.py", line 1946, in consume_positionals
  File "argparse.py", line 1839, in take_action
  File "argparse.py", line 2370, in _get_values
  File "awscli/argparser.py", line 92, in _check_value
argparse.ArgumentError: argument operation: Invalid choice, valid choices are:

add-client-id-to-open-id-connect-provider | add-role-to-instance-profile
add-user-to-group                        | attach-group-policy
attach-role-policy                       | attach-user-policy
change-password                          | create-access-key
create-account-alias                     | create-group
create-instance-profile                  | create-login-profile
create-open-id-connect-provider          | create-policy
create-policy-version                    | create-role
create-saml-provider                     | create-service-linked-role
create-service-specific-credential       | create-user
create-virtual-mfa-device                | deactivate-mfa-device
delete-access-key                        | delete-account-alias
delete-account-password-policy           | delete-group
delete-group-policy                      | delete-instance-profile
delete-login-profile                     | delete-open-id-connect-provider
delete-policy                            | delete-policy-version
delete-role                              | delete-role-permissions-boundary
delete-role-policy                       | delete-saml-provider
delete-ssh-public-key                    | delete-server-certificate
delete-service-linked-role               | delete-service-specific-credential
delete-signing-certificate               | delete-user
delete-user-permissions-boundary         | delete-user-policy
delete-virtual-mfa-device                | detach-group-policy
detach-role-policy                       | detach-user-policy
enable-mfa-device                        | generate-credential-report
generate-organizations-access-report     | generate-service-last-accessed-details
get-access-key-last-used                 | get-account-authorization-details
get-account-password-policy              | get-account-summary
get-context-keys-for-custom-policy       | get-context-keys-for-principal-policy
get-credential-report                    | get-group
get-group-policy                         | get-instance-profile
get-login-profile                        | get-open-id-connect-provider
get-organizations-access-report          | get-policy
get-policy-version                       | get-role
get-role-policy                          | get-saml-provider
get-ssh-public-key                       | get-server-certificate
get-service-last-accessed-details        | get-service-last-accessed-details-with-entities
get-service-linked-role-deletion-status  | get-user
get-user-policy                          | list-access-keys
list-account-aliases                     | list-attached-group-policies
list-attached-role-policies              | list-attached-user-policies
list-entities-for-policy                 | list-group-policies
list-groups                              | list-groups-for-user
list-instance-profiles                   | list-instance-profiles-for-role
list-mfa-devices                         | list-open-id-connect-providers
list-policies                            | list-policies-granting-service-access
list-policy-versions                     | list-role-policies
list-role-tags                           | list-roles
list-saml-providers                      | list-ssh-public-keys
list-server-certificates                 | list-service-specific-credentials
list-signing-certificates                | list-user-policies
list-user-tags                           | list-users
list-virtual-mfa-devices                 | put-group-policy
put-role-permissions-boundary            | put-role-policy
put-user-permissions-boundary            | put-user-policy
remove-client-id-from-open-id-connect-provider | remove-role-from-instance-profile
remove-user-from-group                   | reset-service-specific-credential
resync-mfa-device                        | set-default-policy-version
set-security-token-service-preferences   | simulate-custom-policy
simulate-principal-policy                | tag-role
tag-user                                 | untag-role
untag-user                               | update-access-key
update-account-password-policy           | update-assume-role-policy
update-group                             | update-login-profile
update-open-id-connect-provider-thumbprint | update-role
update-role-description                  | update-saml-provider
update-ssh-public-key                    | update-server-certificate
update-service-specific-credential       | update-signing-certificate
update-user                              | upload-ssh-public-key
upload-server-certificate                | upload-signing-certificate
wizard                                   | wait
help


Invalid choice: 'list-policy-tags', maybe you meant:

  * list-role-tags

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "awscli/clidriver.py", line 457, in main
  File "awscli/clidriver.py", line 584, in __call__
  File "awscli/argparser.py", line 95, in parse_known_args
  File "argparse.py", line 1788, in parse_known_args
  File "awscli/argparser.py", line 128, in error
awscli.argparser.ArgParseException: usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: argument operation: Invalid choice, valid choices are:

add-client-id-to-open-id-connect-provider | add-role-to-instance-profile
add-user-to-group                        | attach-group-policy
attach-role-policy                       | attach-user-policy
change-password                          | create-access-key
create-account-alias                     | create-group
create-instance-profile                  | create-login-profile
create-open-id-connect-provider          | create-policy
create-policy-version                    | create-role
create-saml-provider                     | create-service-linked-role
create-service-specific-credential       | create-user
create-virtual-mfa-device                | deactivate-mfa-device
delete-access-key                        | delete-account-alias
delete-account-password-policy           | delete-group
delete-group-policy                      | delete-instance-profile
delete-login-profile                     | delete-open-id-connect-provider
delete-policy                            | delete-policy-version
delete-role                              | delete-role-permissions-boundary
delete-role-policy                       | delete-saml-provider
delete-ssh-public-key                    | delete-server-certificate
delete-service-linked-role               | delete-service-specific-credential
delete-signing-certificate               | delete-user
delete-user-permissions-boundary         | delete-user-policy
delete-virtual-mfa-device                | detach-group-policy
detach-role-policy                       | detach-user-policy
enable-mfa-device                        | generate-credential-report
generate-organizations-access-report     | generate-service-last-accessed-details
get-access-key-last-used                 | get-account-authorization-details
get-account-password-policy              | get-account-summary
get-context-keys-for-custom-policy       | get-context-keys-for-principal-policy
get-credential-report                    | get-group
get-group-policy                         | get-instance-profile
get-login-profile                        | get-open-id-connect-provider
get-organizations-access-report          | get-policy
get-policy-version                       | get-role
get-role-policy                          | get-saml-provider
get-ssh-public-key                       | get-server-certificate
get-service-last-accessed-details        | get-service-last-accessed-details-with-entities
get-service-linked-role-deletion-status  | get-user
get-user-policy                          | list-access-keys
list-account-aliases                     | list-attached-group-policies
list-attached-role-policies              | list-attached-user-policies
list-entities-for-policy                 | list-group-policies
list-groups                              | list-groups-for-user
list-instance-profiles                   | list-instance-profiles-for-role
list-mfa-devices                         | list-open-id-connect-providers
list-policies                            | list-policies-granting-service-access
list-policy-versions                     | list-role-policies
list-role-tags                           | list-roles
list-saml-providers                      | list-ssh-public-keys
list-server-certificates                 | list-service-specific-credentials
list-signing-certificates                | list-user-policies
list-user-tags                           | list-users
list-virtual-mfa-devices                 | put-group-policy
put-role-permissions-boundary            | put-role-policy
put-user-permissions-boundary            | put-user-policy
remove-client-id-from-open-id-connect-provider | remove-role-from-instance-profile
remove-user-from-group                   | reset-service-specific-credential
resync-mfa-device                        | set-default-policy-version
set-security-token-service-preferences   | simulate-custom-policy
simulate-principal-policy                | tag-role
tag-user                                 | untag-role
untag-user                               | update-access-key
update-account-password-policy           | update-assume-role-policy
update-group                             | update-login-profile
update-open-id-connect-provider-thumbprint | update-role
update-role-description                  | update-saml-provider
update-ssh-public-key                    | update-server-certificate
update-service-specific-credential       | update-signing-certificate
update-user                              | upload-ssh-public-key
upload-server-certificate                | upload-signing-certificate
wizard                                   | wait
help


Invalid choice: 'list-policy-tags', maybe you meant:

  * list-role-tags


usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: argument operation: Invalid choice, valid choices are:

add-client-id-to-open-id-connect-provider | add-role-to-instance-profile
add-user-to-group                        | attach-group-policy
attach-role-policy                       | attach-user-policy
change-password                          | create-access-key
create-account-alias                     | create-group
create-instance-profile                  | create-login-profile
create-open-id-connect-provider          | create-policy
create-policy-version                    | create-role
create-saml-provider                     | create-service-linked-role
create-service-specific-credential       | create-user
create-virtual-mfa-device                | deactivate-mfa-device
delete-access-key                        | delete-account-alias
delete-account-password-policy           | delete-group
delete-group-policy                      | delete-instance-profile
delete-login-profile                     | delete-open-id-connect-provider
delete-policy                            | delete-policy-version
delete-role                              | delete-role-permissions-boundary
delete-role-policy                       | delete-saml-provider
delete-ssh-public-key                    | delete-server-certificate
delete-service-linked-role               | delete-service-specific-credential
delete-signing-certificate               | delete-user
delete-user-permissions-boundary         | delete-user-policy
delete-virtual-mfa-device                | detach-group-policy
detach-role-policy                       | detach-user-policy
enable-mfa-device                        | generate-credential-report
generate-organizations-access-report     | generate-service-last-accessed-details
get-access-key-last-used                 | get-account-authorization-details
get-account-password-policy              | get-account-summary
get-context-keys-for-custom-policy       | get-context-keys-for-principal-policy
get-credential-report                    | get-group
get-group-policy                         | get-instance-profile
get-login-profile                        | get-open-id-connect-provider
get-organizations-access-report          | get-policy
get-policy-version                       | get-role
get-role-policy                          | get-saml-provider
get-ssh-public-key                       | get-server-certificate
get-service-last-accessed-details        | get-service-last-accessed-details-with-entities
get-service-linked-role-deletion-status  | get-user
get-user-policy                          | list-access-keys
list-account-aliases                     | list-attached-group-policies
list-attached-role-policies              | list-attached-user-policies
list-entities-for-policy                 | list-group-policies
list-groups                              | list-groups-for-user
list-instance-profiles                   | list-instance-profiles-for-role
list-mfa-devices                         | list-open-id-connect-providers
list-policies                            | list-policies-granting-service-access
list-policy-versions                     | list-role-policies
list-role-tags                           | list-roles
list-saml-providers                      | list-ssh-public-keys
list-server-certificates                 | list-service-specific-credentials
list-signing-certificates                | list-user-policies
list-user-tags                           | list-users
list-virtual-mfa-devices                 | put-group-policy
put-role-permissions-boundary            | put-role-policy
put-user-permissions-boundary            | put-user-policy
remove-client-id-from-open-id-connect-provider | remove-role-from-instance-profile
remove-user-from-group                   | reset-service-specific-credential
resync-mfa-device                        | set-default-policy-version
set-security-token-service-preferences   | simulate-custom-policy
simulate-principal-policy                | tag-role
tag-user                                 | untag-role
untag-user                               | update-access-key
update-account-password-policy           | update-assume-role-policy
update-group                             | update-login-profile
update-open-id-connect-provider-thumbprint | update-role
update-role-description                  | update-saml-provider
update-ssh-public-key                    | update-server-certificate
update-service-specific-credential       | update-signing-certificate
update-user                              | upload-ssh-public-key
upload-server-certificate                | upload-signing-certificate
wizard                                   | wait
help


Invalid choice: 'list-policy-tags', maybe you meant:

  * list-role-tags
```

**Additional context**
No additional context to provide.

**Comment by stobrien89** [comment]
Hi @fagiani,

Thanks for writing in!  It looks like `list-policy-tags` is a relatively new operation (added to botocore on 2/12/2021), meaning you'll need CLI version 2.1.27 or higher to have access to it.  Hope this helps!
