### ISSUE TITLE
Error when retrieving credentials from custom-process: aws-vault: error: exec: Can't use --server with --json

### ISSUE THREAD

**Issue by scalp42** [aws/aws-cli#6200]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Cannot obtain credentials through `custom-process` anymore. It used to work fine but upgraded CLI through Homebrew.

**SDK version number**
aws-cli/2.2.7 Python/3.9.5 Darwin/18.7.0 source/x86_64 prompt/off

**Platform/OS/Hardware/Device**
MacOS Mojave `10.14.6`

**To Reproduce (observed behavior)**

```
aws --debug sts get-caller-identity --profile prod
```

```
# ~/.aws/config
[profile prod]
include_profile = anthony
role_arn = arn:aws:iam::xxxxx:role/admin
role_session_name = anthony
source_profile = bridge

[profile bridge]
include_profile = anthony
credential_process = aws-vault exec bridge --mfa-token=$(ykman oath accounts code -s anthony@wbridge) --duration=1h --json
```

**Expected behavior**
It should just work 😅

**Logs/output**

```
2021-06-01 14:56:40,106 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.2.7 Python/3.9.5 Darwin/18.7.0 source/x86_64
2021-06-01 14:56:40,106 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', 'sts', 'get-caller-identity', '--profile', 'prod']
2021-06-01 14:56:40,124 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x10b384310>
2021-06-01 14:56:40,124 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x10b1b2ee0>
2021-06-01 14:56:40,124 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2021-06-01 14:56:40,124 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x10b14f430>
2021-06-01 14:56:40,124 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x10b1563a0>
2021-06-01 14:56:40,124 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x10b391ca0>
2021-06-01 14:56:40,124 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x10b1fdaf0>
2021-06-01 14:56:40,124 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2021-06-01 14:56:40,124 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x10b38eee0>
2021-06-01 14:56:40,124 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.2.7/libexec/lib/python3.9/site-packages/awscli/data/cli.json
2021-06-01 14:56:40,127 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x10b2bb8b0>
2021-06-01 14:56:40,127 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x10b2bc430>
2021-06-01 14:56:40,127 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x10b2bc3a0>
2021-06-01 14:56:40,127 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x10b2bc550>
2021-06-01 14:56:40,127 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x10b2bc4c0>
2021-06-01 14:56:40,127 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x10b4354c0>
2021-06-01 14:56:40,127 - MainThread - botocore.session - DEBUG - Setting config variable for profile to 'prod'
2021-06-01 14:56:40,128 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.2.7 Python/3.9.5 Darwin/18.7.0 source/x86_64 prompt/off
2021-06-01 14:56:40,128 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', 'sts', 'get-caller-identity', '--profile', 'prod']
2021-06-01 14:56:40,128 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x10b384940>
2021-06-01 14:56:40,128 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x10ae40dc0>
2021-06-01 14:56:40,128 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x10b3fb3a0>
2021-06-01 14:56:40,128 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x10ae3bf70>
2021-06-01 14:56:40,128 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x10aedb8b0>
2021-06-01 14:56:40,130 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-06-01 14:56:40,136 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2021-06-01 14:56:40,136 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x10b1fd9d0>
2021-06-01 14:56:40,136 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x10b1b0dc0>
2021-06-01 14:56:40,155 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.2.7/libexec/lib/python3.9/site-packages/botocore/data/sts/2011-06-15/service-2.json
2021-06-01 14:56:40,157 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sts: calling handler <function add_waiters at 0x10b38eee0>
2021-06-01 14:56:40,174 - MainThread - awscli.clidriver - DEBUG - OrderedDict()
2021-06-01 14:56:40,174 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function add_streaming_output_arg at 0x10b384c10>
2021-06-01 14:56:40,174 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function add_cli_input_json at 0x10aee60d0>
2021-06-01 14:56:40,174 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function add_cli_input_yaml at 0x10aee6310>
2021-06-01 14:56:40,174 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function unify_paging_params at 0x10b1ba550>
2021-06-01 14:56:40,193 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.2.7/libexec/lib/python3.9/site-packages/botocore/data/sts/2011-06-15/paginators-1.json
2021-06-01 14:56:40,193 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function add_generate_skeleton at 0x10b2aee50>
2021-06-01 14:56:40,193 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sts.get-caller-identity: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x10b548280>>
2021-06-01 14:56:40,193 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sts.get-caller-identity: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x10b5482b0>>
2021-06-01 14:56:40,193 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sts.get-caller-identity: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x10b548340>>
2021-06-01 14:56:40,194 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sts.get-caller-identity.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10b46e1c0>
2021-06-01 14:56:40,194 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sts.get-caller-identity.cli-input-yaml: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10b46e1c0>
2021-06-01 14:56:40,194 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sts.get-caller-identity.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10b46e1c0>
2021-06-01 14:56:40,194 - MainThread - botocore.hooks - DEBUG - Event calling-command.sts.get-caller-identity: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x10b548280>>
2021-06-01 14:56:40,194 - MainThread - botocore.hooks - DEBUG - Event calling-command.sts.get-caller-identity: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x10b5482b0>>
2021-06-01 14:56:40,194 - MainThread - botocore.hooks - DEBUG - Event calling-command.sts.get-caller-identity: calling handler <bound method GenerateCliSkeletonArgument.generate_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x10b548340>>
2021-06-01 14:56:40,194 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2021-06-01 14:56:40,194 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2021-06-01 14:56:40,194 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2021-06-01 14:56:40,194 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2021-06-01 14:56:40,195 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: custom-process
2021-06-01 14:56:40,214 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/Cellar/awscli/2.2.7/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 459, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/Cellar/awscli/2.2.7/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 594, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/Cellar/awscli/2.2.7/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 770, in __call__
    return self._operation_caller.invoke(
  File "/usr/local/Cellar/awscli/2.2.7/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 897, in invoke
    client = self._session.create_client(
  File "/usr/local/Cellar/awscli/2.2.7/libexec/lib/python3.9/site-packages/botocore/session.py", line 808, in create_client
    credentials = self.get_credentials()
  File "/usr/local/Cellar/awscli/2.2.7/libexec/lib/python3.9/site-packages/botocore/session.py", line 426, in get_credentials
    self._credentials = self._components.get_component(
  File "/usr/local/Cellar/awscli/2.2.7/libexec/lib/python3.9/site-packages/botocore/credentials.py", line 1977, in load_credentials
    creds = provider.load()
  File "/usr/local/Cellar/awscli/2.2.7/libexec/lib/python3.9/site-packages/botocore/credentials.py", line 1410, in load
    return self._load_creds_via_assume_role(self._profile_name)
  File "/usr/local/Cellar/awscli/2.2.7/libexec/lib/python3.9/site-packages/botocore/credentials.py", line 1424, in _load_creds_via_assume_role
    source_credentials = self._resolve_source_credentials(
  File "/usr/local/Cellar/awscli/2.2.7/libexec/lib/python3.9/site-packages/botocore/credentials.py", line 1586, in _resolve_source_credentials
    return self._resolve_credentials_from_profile(source_profile)
  File "/usr/local/Cellar/awscli/2.2.7/libexec/lib/python3.9/site-packages/botocore/credentials.py", line 1606, in _resolve_credentials_from_profile
    credentials = profile_chain.load_credentials()
  File "/usr/local/Cellar/awscli/2.2.7/libexec/lib/python3.9/site-packages/botocore/credentials.py", line 1977, in load_credentials
    creds = provider.load()
  File "/usr/local/Cellar/awscli/2.2.7/libexec/lib/python3.9/site-packages/botocore/credentials.py", line 962, in load
    creds_dict = self._retrieve_credentials_using(credential_process)
  File "/usr/local/Cellar/awscli/2.2.7/libexec/lib/python3.9/site-packages/botocore/credentials.py", line 987, in _retrieve_credentials_using
    raise CredentialRetrievalError(
botocore.exceptions.CredentialRetrievalError: Error when retrieving credentials from custom-process: aws-vault: error: exec: Can't use --server with --json


Error when retrieving credentials from custom-process: aws-vault: error: exec: Can't use --server with --json
```

I have tested the `aws-vault` command by hand as well and it works fine:

```
#> aws-vault exec bridge --mfa-token=$(ykman oath accounts code -s anthony@bridge) --duration=1h --json
{"Version":1,"AccessKeyId":"xxxxx","SecretAccessKey":"xxxx/xxxx/Jk","SessionToken":"xxxx+cJClE5d4eU4KVK/xeFPBnshMPe7R8wuDVgssqLrouChr0XfqjaiIvG034+oRW4v8wkjXdLAWOBL1cTxWhYaET615+RglwoCp26Ozt/xxxx/L1trWlqV1mzs4+xxxxxx/xxx=","Expiration":"2021-06-01T22:46:24Z"}%

```

**Comment by stobrien89** [comment]
Hi @scalp42,

Thanks for the report!  We don't officially support homebrew installations, but I'd be curious to see if this works when you uninstall/upgrade via one of our [supported installation methods](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-mac.html).  Let me know how it goes!

**Comment by scalp42** [comment]
Closing, fixed with: 

```
credential_process = aws-vault exec bridge --mfa-token=$(ykman oath accounts code -s anthony@wbridge) --duration=1h --json
```

vs

```
credential_process = sh -c 'aws-vault exec bridge --mfa-token=$(ykman oath accounts code -s anthony@wbridge) --duration=1h --json'
```

**Comment by stobrien89** [comment]
Thanks for the update!  Glad you were able to get it resolved.
