### ISSUE TITLE
aws sso login does not complete

### ISSUE THREAD

**Issue by riponbanik** [aws/aws-cli#6212]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Use the following command which asks to open the browser and set it code. After it is done browser says "You have been successfully signed in to the AWS CLI. You can now close this browser." But cli hangs. 

aws sso login --profile myprofile --debug

Debug log shows 

2021-06-10 10:25:21,634 - MainThread - botocore.hooks - DEBUG - Event needs-retry.sso-oidc.StartDeviceAuthorization: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x7f376e7c4340>>
2021-06-10 10:25:21,634 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2021-06-10 10:25:21,634 - MainThread - botocore.hooks - DEBUG - Event after-call.sso-oidc.StartDeviceAuthorization: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x7f376e7a2040>>
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

**SDK version number**
2.2.10

**Platform/OS/Hardware/Device**
What are you running the cli on?
WSL 2

**To Reproduce (observed behavior)**
Steps to reproduce the behavior
N/A

**Expected behavior**
The login should show error that what is failing.

**Logs/output**
2021-06-10 10:25:21,514 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sso-oidc.StartDeviceAuthorization: calling handler <function set_operation_specific_signer at 0x7f3771454550>
2021-06-10 10:25:21,514 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://oidc.ap-southeast-2.amazonaws.com/device_authorization, headers={'User-Agent': b'aws-cli/2.2.10 Python/3.8.8 Linux/5.4.72-microsoft-standard-WSL2 exe/x86_64.ubuntu.20 prompt/off command/sso.login', 'Content-Length': '987'}>
2021-06-10 10:25:21,515 - MainThread - botocore.httpsession - DEBUG - Certificate path: /usr/local/aws-cli/v2/2.2.10/dist/botocore/cacert.pem
2021-06-10 10:25:21,517 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oidc.ap-southeast-2.amazonaws.com:443
2021-06-10 10:25:21,632 - MainThread - urllib3.connectionpool - DEBUG - https://oidc.ap-southeast-2.amazonaws.com:443 "POST /device_authorization HTTP/1.1" 200 321
2021-06-10 10:25:21,633 - MainThread - botocore.parsers - DEBUG - Response headers: {'Date': 'Thu, 10 Jun 2021 00:25:22 GMT', 'Content-Type': 'application/json', 'Content-Length': '321', 'Connection': 'keep-alive', 'x-amzn-RequestId': '340e07d8-2c35-4050-bbe3-558c789683ee'}
2021-06-10 10:25:21,633 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"deviceCode":"opO8yiBhPEhwFECZM04T9Z6ft409MJIq2z_NoFr74WG1E_hE9BRdPM77XzmsKcl9Kg9hopElwRgQefkmNAIuqg","expiresIn":600,"interval":1,"userCode":"RFNQ-LBNF","verificationUri":"https://device.sso.ap-southeast-2.amazonaws.com/","verificationUriComplete":"https://device.sso.ap-southeast-2.amazonaws.com/?user_code=xxxxx"}'
2021-06-10 10:25:21,634 - MainThread - botocore.hooks - DEBUG - Event needs-retry.sso-oidc.StartDeviceAuthorization: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x7f376e7c4340>>
2021-06-10 10:25:21,634 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2021-06-10 10:25:21,634 - MainThread - botocore.hooks - DEBUG - Event after-call.sso-oidc.StartDeviceAuthorization: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x7f376e7a2040>>
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

**Additional context**
N/A

**Comment by stobrien89** [comment]
Hi @riponbanik,

Sorry to hear you're having issues—  I'm currently attempting to reproduce this, but running into some hangups with getting the Ubuntu distribution to work on my virtual machine.  Do you see any output when you attempt to escape (`ctrl` + `c`) the SSO prompts?

**Comment by riponbanik** [comment]
@stobrien89  Following is the output - C2021-06-17 11:50:46,093 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "subprocess.py", line 495, in run
  File "subprocess.py", line 1015, in communicate
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "awscli/clidriver.py", line 459, in main
  File "awscli/clidriver.py", line 594, in __call__
  File "awscli/customizations/commands.py", line 191, in __call__
  File "awscli/customizations/sso/login.py", line 41, in _run_main
  File "awscli/customizations/sso/utils.py", line 57, in do_sso_login
  File "botocore/utils.py", line 2425, in fetch_token
  File "botocore/utils.py", line 2420, in _token
  File "botocore/utils.py", line 2381, in _poll_for_token
  File "awscli/customizations/sso/utils.py", line 89, in __call__
  File "awscli/customizations/sso/utils.py", line 65, in open_browser_with_original_ld_path
  File "webbrowser.py", line 102, in open_new_tab
  File "webbrowser.py", line 83, in open
  File "webbrowser.py", line 551, in register_standard_browsers
  File "subprocess.py", line 415, in check_output
  File "subprocess.py", line 495, in run
KeyboardInterrupt

**Comment by stobrien89** [comment]
Hi @riponbanik,

Thank you for the additional information!  I did some testing with WSL on Windows 10 and noticed this happens when the CLI is waiting for the browser to be launched on the host system. Which version of Windows are you using? And what is your default browser set to?

**Comment by riponbanik** [comment]
@stobrien89 I am using Windows 10 pro and default browser is Chrome.

**Comment by stobrien89** [comment]
@riponbanik,

Thanks for confirming.  Out of curiosity, does the issue still occur if you revert to WSL1 by running `wsl.exe --set-default-version 1` ?

**Comment by riponbanik** [comment]
@stobrien89 set default version does not change to version 1, needs to convert to version 1 which I am unwilling to do since it will break some of my works. I have tested it on another computer, it works. But do not know what happened here, since cli does not report any issue.

**Comment by stobrien89** [comment]
Hi @riponbanik,

That's understandable.  Would it be possible for you to change your default browser to something else (preferably firefox) to see if this behavior changes?

**Comment by rissanssi** [comment]
I was able to solve this problem with changing the default 1500 MTU to 1200 by running:
`sudo ip link set dev eth0 mtu 1200`

**Comment by riponbanik** [comment]
@stobrien89 I do not open browser automatically, so I can use any browser I like. It seems that CLI is not receiving response from upstream. @rissanssi It did not resolve my issue. thanks

**Comment by stobrien89** [comment]
Hi @riponbanik,

Pardon me if I'm missing something, but what do you mean when you say you "do not open browser automatically"? I suspect the sso login extension needs a registered browser to "attempt" to open.  

I've seen [wslu](https://github.com/wslutilities/wslu) reccomended for similar issues.  Specifically, `wslview --register`, which essentially registers a "fake" browser that points to your default windows browser.

**Comment by riponbanik** [comment]
@stobrien89  using BROWSER=/usr/bin/true aws, will allow you to open the authentication endpoint (http://device.sso.ap-southeast-2.amazonaws.com/) to any browser where you already logged in to AWS Console using your aws credentials.

**Comment by nirnanaaa** [comment]
in my case unsetting the `DISPLAY` and setting browser to `/usr/bin/true` as suggested by @riponbanik  solved the issue.

**Comment by stobrien89** [comment]
Thanks for the update @riponbanik and @nirnanaaa,

Marking this as a bug for now, as we should at least fail with an error in this scenario.  Thanks again for reporting @riponbanik!

**Comment by HUN220** [comment]
I also had this issue after having awscliv2 working for ages so I'll include my findings in the hope it helps someone else. For me I had recently set up X11 forwarding within WSL2 so that I could use GUI programs by running an X server (VcXsrv) on the Windows host. That involves setting the `DISPLAY` environment variable inside WSL2 to point to the host OS. If that's set but you haven't got X11 server running then awscliv2 will silently fail to open the browser. Interestingly if I try and open the browser from WSL2 using `wslview https://ww.github.com` that will actually work.

**Comment by nmiculinic** [comment]
I have the same issue running Manjaro Linux. Sometimes it works, most of the time it does not. I click allow in the browser, yet it's like CLI hasn't received some event or something.

<details>
  <summary>debug output</summary>
  
```
[nmiculinic@atlas ~]$ aws sso login --profile byoc-sandbox
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://device.sso.us-east-2.amazonaws.com/

Then enter the code:

PRNW-SJLJ

(google-chrome:4303): Gtk-WARNING **: 08:25:36.160: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
[4348:4348:1105/082536.244243:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[4303:4368:1105/082538.382078:ERROR:chrome_browser_main_extra_parts_metrics.cc(228)] crbug.com/1216328: Checking Bluetooth availability started. Please report if there is no report that this ends.
[4303:4368:1105/082538.382092:ERROR:chrome_browser_main_extra_parts_metrics.cc(231)] crbug.com/1216328: Checking Bluetooth availability ended.
[4303:4368:1105/082538.382097:ERROR:chrome_browser_main_extra_parts_metrics.cc(234)] crbug.com/1216328: Checking default browser status started. Please report if there is no report that this ends.
[4303:4368:1105/082538.426735:ERROR:chrome_browser_main_extra_parts_metrics.cc(238)] crbug.com/1216328: Checking default browser status ended.
^C
[nmiculinic@atlas ~]$ aws sso login --profile byoc-sandbox --debug
2021-11-05 08:25:49,926 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.2.39 Python/3.8.8 Linux/5.10.70-1-MANJARO exe/x86_64.manjaro.21
2021-11-05 08:25:49,926 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['sso', 'login', '--profile', 'byoc-sandbox', '--debug']
2021-11-05 08:25:49,932 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x7f776fe37040>
2021-11-05 08:25:49,932 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x7f777000ca60>
2021-11-05 08:25:49,932 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2021-11-05 08:25:49,932 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7f7770037430>
2021-11-05 08:25:49,932 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7f7770040280>
2021-11-05 08:25:49,932 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x7f776fe46a60>
2021-11-05 08:25:49,932 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x7f776ffd58b0>
2021-11-05 08:25:49,932 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2021-11-05 08:25:49,932 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x7f776fe3eca0>
2021-11-05 08:25:49,933 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/share/aws-cli/v2/2.2.39/dist/awscli/data/cli.json
2021-11-05 08:25:49,934 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x7f776ff0baf0>
2021-11-05 08:25:49,934 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x7f776ff0d670>
2021-11-05 08:25:49,935 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x7f776ff0d5e0>
2021-11-05 08:25:49,935 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x7f776ff0d790>
2021-11-05 08:25:49,935 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x7f776ff0d700>
2021-11-05 08:25:49,935 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x7f776fdddf00>
2021-11-05 08:25:49,935 - MainThread - botocore.session - DEBUG - Setting config variable for profile to 'byoc-sandbox'
2021-11-05 08:25:49,935 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.2.39 Python/3.8.8 Linux/5.10.70-1-MANJARO exe/x86_64.manjaro.21 prompt/off
2021-11-05 08:25:49,935 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['sso', 'login', '--profile', 'byoc-sandbox', '--debug']
2021-11-05 08:25:49,935 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7f776fe37670>
2021-11-05 08:25:49,935 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7f77708fb670>
2021-11-05 08:25:49,935 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7f776fe224c0>
2021-11-05 08:25:49,935 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x7f77708e8af0>
2021-11-05 08:25:49,935 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f777086a310>
2021-11-05 08:25:49,936 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-11-05 08:25:49,937 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2021-11-05 08:25:49,937 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f776ffd5790>
2021-11-05 08:25:49,937 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7f777000b8b0>
2021-11-05 08:25:49,942 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/share/aws-cli/v2/2.2.39/dist/botocore/data/sso/2019-06-10/service-2.json
2021-11-05 08:25:49,943 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sso: calling handler <function add_sso_commands at 0x7f777000b310>
2021-11-05 08:25:49,943 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sso: calling handler <function add_waiters at 0x7f776fe3eca0>
2021-11-05 08:25:49,949 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sso_login: calling handler <function add_waiters at 0x7f776fe3eca0>
2021-11-05 08:25:49,949 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/share/aws-cli/v2/2.2.39/dist/botocore/data/endpoints.json
2021-11-05 08:25:49,953 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f7771c8a8b0>
2021-11-05 08:25:49,953 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/share/aws-cli/v2/2.2.39/dist/botocore/data/sso-oidc/2019-06-10/service-2.json
2021-11-05 08:25:49,954 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.sso-oidc: calling handler <function add_generate_presigned_url at 0x7f7772280e50>
2021-11-05 08:25:49,955 - MainThread - botocore.endpoint - DEBUG - Setting oidc timeout as (60, 60)
2021-11-05 08:25:49,956 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.sso-oidc.StartDeviceAuthorization: calling handler <function base64_decode_input_blobs at 0x7f776fe22c10>
2021-11-05 08:25:49,956 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.sso-oidc.StartDeviceAuthorization: calling handler <function generate_idempotent_uuid at 0x7f7771c2e940>
2021-11-05 08:25:49,956 - MainThread - botocore.hooks - DEBUG - Event before-call.sso-oidc.StartDeviceAuthorization: calling handler <function inject_api_version_header_if_needed at 0x7f7771c341f0>
2021-11-05 08:25:49,956 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=StartDeviceAuthorization) with params: {'url_path': '/device_authorization', 'query_string': {}, 'method': 'POST', 'headers': {'User-Agent': 'aws-cli/2.2.39 Python/3.8.8 Linux/5.10.70-1-MANJARO exe/x86_64.manjaro.21 prompt/off command/sso.login'}, 'body': b'{"clientId": "SqWlk6Trod-XyYdQ3--ejnVzLWVhc3QtMg", "clientSecret": "eyJraWQiOiJrZXktMTU2Njk2ODA4OCIsImFsZyI6IkhTMzg0In0.eyJzZXJpYWxpemVkIjoie1wiZXhwaXJlZFwiOmZhbHNlLFwiY2xpZW50SWRcIjp7XCJ2YWx1ZVwiOlwiU3FXbGs2VHJvZC1YeVlkUTMtLWVqblZ6TFdWaGMzUXRNZ1wifSxcImlkZW1wb3RlbnRLZXlcIjpudWxsLFwidGVuYW50SWRcIjpudWxsLFwiY2xpZW50TmFtZVwiOlwiYm90b2NvcmUtY2xpZW50LTE2MzQwNDk1MDNcIixcImNsaWVudFR5cGVcIjpcIlBVQkxJQ1wiLFwidGVtcGxhdGVBcm5cIjpudWxsLFwidGVtcGxhdGVDb250ZXh0XCI6bnVsbCxcImV4cGlyYXRpb25UaW1lc3RhbXBcIjoxNjQxODI1NTAzLjkwODAwMDAwMCxcImNyZWF0ZWRUaW1lc3RhbXBcIjoxNjM0MDQ5NTAzLjkwODAwMDAwMCxcInVwZGF0ZWRUaW1lc3RhbXBcIjoxNjM0MDQ5NTAzLjkwODAwMDAwMCxcImNyZWF0ZWRCeVwiOm51bGwsXCJ1cGRhdGVkQnlcIjpudWxsLFwic3RhdHVzXCI6bnVsbCxcImluaXRpYXRlTG9naW5VcmlcIjpudWxsLFwiZW50aXRsZWRSZXNvdXJjZUlkXCI6bnVsbCxcImVudGl0bGVkUmVzb3VyY2VDb250YWluZXJJZFwiOm51bGwsXCJleHRlcm5hbElkXCI6bnVsbH0ifQ.4EPTRWLdzpfosOF1KjEZD35NXbAWykHYlde84M73afhzMfb34Rlh4zki5ZP8hWA-", "startUrl": "https://d-9a6727c009.awsapps.com/start"}', 'url': 'https://oidc.us-east-2.amazonaws.com/device_authorization', 'context': {'client_region': 'us-east-2', 'client_config': <botocore.config.Config object at 0x7f776f5a4d90>, 'has_streaming_input': False, 'auth_type': 'none'}}
2021-11-05 08:25:49,956 - MainThread - botocore.hooks - DEBUG - Event request-created.sso-oidc.StartDeviceAuthorization: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f776f5a4eb0>>
2021-11-05 08:25:49,956 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sso-oidc.StartDeviceAuthorization: calling handler <function set_operation_specific_signer at 0x7f7771c2e820>
2021-11-05 08:25:49,956 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://oidc.us-east-2.amazonaws.com/device_authorization, headers={'User-Agent': b'aws-cli/2.2.39 Python/3.8.8 Linux/5.10.70-1-MANJARO exe/x86_64.manjaro.21 prompt/off command/sso.login', 'Content-Length': '979'}>
2021-11-05 08:25:49,957 - MainThread - botocore.httpsession - DEBUG - Certificate path: /usr/share/aws-cli/v2/2.2.39/dist/botocore/cacert.pem
2021-11-05 08:25:49,957 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oidc.us-east-2.amazonaws.com:443
2021-11-05 08:25:50,485 - MainThread - urllib3.connectionpool - DEBUG - https://oidc.us-east-2.amazonaws.com:443 "POST /device_authorization HTTP/1.1" 200 311
2021-11-05 08:25:50,486 - MainThread - botocore.parsers - DEBUG - Response headers: {'Date': 'Fri, 05 Nov 2021 07:25:50 GMT', 'Content-Type': 'application/json', 'Content-Length': '311', 'Connection': 'keep-alive', 'x-amzn-RequestId': '469686dc-f5cd-4c0d-90a5-12634702507d'}
2021-11-05 08:25:50,486 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"deviceCode":"IiXrWybefqAO78PJlDs4VGLY6Oivz0psLM-z-m_SviWn-4mvIvMVwu28jPBaDiN8wZuaAygjVocvGZIsf9FdzQ","expiresIn":600,"interval":1,"userCode":"PCTQ-SGXX","verificationUri":"https://device.sso.us-east-2.amazonaws.com/","verificationUriComplete":"https://device.sso.us-east-2.amazonaws.com/?user_code=PCTQ-SGXX"}'
2021-11-05 08:25:50,487 - MainThread - botocore.hooks - DEBUG - Event needs-retry.sso-oidc.StartDeviceAuthorization: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x7f776f599ee0>>
2021-11-05 08:25:50,487 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2021-11-05 08:25:50,488 - MainThread - botocore.hooks - DEBUG - Event after-call.sso-oidc.StartDeviceAuthorization: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x7f776f5a4400>>
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://device.sso.us-east-2.amazonaws.com/

Then enter the code:

PCTQ-SGXX

(google-chrome:4938): Gtk-WARNING **: 08:25:50.572: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
[4980:4980:1105/082550.658159:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[4938:4989:1105/082552.802930:ERROR:chrome_browser_main_extra_parts_metrics.cc(228)] crbug.com/1216328: Checking Bluetooth availability started. Please report if there is no report that this ends.
[4938:4989:1105/082552.802943:ERROR:chrome_browser_main_extra_parts_metrics.cc(231)] crbug.com/1216328: Checking Bluetooth availability ended.
[4938:4989:1105/082552.802947:ERROR:chrome_browser_main_extra_parts_metrics.cc(234)] crbug.com/1216328: Checking default browser status started. Please report if there is no report that this ends.
[4938:4989:1105/082552.844793:ERROR:chrome_browser_main_extra_parts_metrics.cc(238)] crbug.com/1216328: Checking default browser status ended.

```

</details>

**Comment by tairosonloa** [comment]
Any news on this?

**Comment by tim-finnigan** [comment]
Checking in on this - it seems like the problem is due to some local configuration issues. Maybe you could also try using the `--no-browser` parameter to circumvent this?

**Comment by esimonov** [comment]
None of the workarounds above worked for me, but rebooting a laptop did.

**Comment by jemrpo** [comment]
Had a similar issue today, checked the `/etc/wsl.conf` file and found I had a comment on the automount section.
```
[automount]
enabled = true
root = /winfolder #Acomment
options = "metadata,umask=22,fmask=11"
mountFsTab = false
``` 
Once I removed the comment it worked fine. Hope it helps someone.

**Comment by stanzhouAtEncompass** [comment]
None of the workarounds above worked for me. wsl2 ubuntu using NAT network, the ubuntu machine could not get the packages send from aws. The workaround for me right now is to copy and paste the keys from console to cred file.

**Comment by jamesoff** [comment]
> Checking in on this - it seems like the problem is due to some local configuration issues. Maybe you could also try using the `--no-browser` parameter to circumvent this?

This worked for me; I also note that my Firefox is waiting for me to restart it for an upgrade, so maybe that's related (maybe Python doesn't think it successfully launched it?)

**Comment by tim-finnigan** [comment]
Checking in as there haven't been any reports or +1s on this issue in over a year. Please try updating to a recent version of the AWS CLI (the latest is [2.17.28](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1)) if you're still seeing this issue, or try using `--no-browser` as suggested [here](https://github.com/aws/aws-cli/issues/6212#issuecomment-1311921262).
