### ISSUE TITLE
ImportError: cannot import name ProxySchemeUnsupported

### ISSUE THREAD

**Issue by amopportunities** [aws/aws-cli#6258]
Just logged into my cloud9 env today and now I get this error when trying to run AWS.

$ aws
Traceback (most recent call last):
  File "/usr/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 17, in <module>
    import botocore.session
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 29, in <module>
    import botocore.configloader
  File "/usr/lib/python2.7/site-packages/botocore/configloader.py", line 19, in <module>
    from botocore.compat import six
  File "/usr/lib/python2.7/site-packages/botocore/compat.py", line 27, in <module>
    from urllib3 import exceptions
  File "/usr/lib/python2.7/site-packages/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/usr/lib/python2.7/site-packages/urllib3/connection.py", line 41, in <module>
    from .util.ssl_ import (
  File "/usr/lib/python2.7/site-packages/urllib3/util/__init__.py", line 8, in <module>
    from .ssl_ import (
  File "/usr/lib/python2.7/site-packages/urllib3/util/ssl_.py", line 10, in <module>
    from ..exceptions import (
ImportError: cannot import name ProxySchemeUnsupported

**Comment by stobrien89** [comment]
Hi @amopportunities,

Sorry to hear you're having issues.  This looks to be an issue with the urllib3 package installation.  Have you tried uninstalling and reinstalling either the CLI or urllib3?

**Comment by chriscasto** [comment]
This is due to urllib3 being installed via pip after having been originally installed via yum.  Just run `sudo pip uninstall urllib3` followed by `sudo yum update` to fix this.
