### ISSUE TITLE
Honeycode list-table-rows pagination doesn't work with --starting-token

### ISSUE THREAD

**Issue by voldyman** [aws/aws-cli#6273]
**Describe the bug**
Using pagination tokens from AWS CLI & Honeycode throws error.

```
$ aws honeycode list-table-rows  --workbook-id ... --table-id ...  --starting-token "xxyyzz"
⮑  works

$ aws honeycode list-table-rows  --workbook-id ... --table-id ...  --starting-token "xxyyzz" --max-items 10
⮑  works

$ aws honeycode list-table-rows  --workbook-id ... --table-id ...  --starting-token "xxyyzz" --max-results 10
⮑  error
Error during pagination: Cannot specify --no-paginate along with pagination arguments: --starting-token

$ aws honeycode list-table-rows  --workbook-id ... --table-id ...  --next-token "xxyyzz" --max-results 10
⮑  works

```

the failing command and the successful command only differ in max-**items** & max-**results**

**SDK version number**: `aws-cli/2.2.16 Python/3.9.6 Darwin/20.5.0 source/x86_64 prompt/off`

**Platform/OS/Hardware/Device**
Mac, Big Sur 11.4

**To Reproduce (observed behavior)**
Mix pagination parameters between service & cli vended args

**Expected behavior**
To pagination args to work regardless of their source

**Logs/output**
```
╰─➤  aws --debug --profile default --region us-west-2 honeycode list-table-rows --workbook-id 3578B9F9-FCD6-449A-ADD2-EF3B62C9BC2A --table-id 3578B9F9-FCD6-449A-ADD2-EF3B62C9BC2A --starting-token abc --max-results 10
2021-07-13 09:57:35,824 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.2.16 Python/3.9.6 Darwin/20.5.0 source/x86_64
2021-07-13 09:57:35,824 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', '--profile', 'default', '--region', 'us-west-2', 'honeycode', 'list-table-rows', '--workbook-id', '3578B9F9-FCD6-449A-ADD2-EF3B62C9BC2A', '--table-id', '3578B9F9-FCD6-449A-ADD2-EF3B62C9BC2A', '--starting-token', 'abc', '--max-results', '10']
2021-07-13 09:57:35,857 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x1026c9160>
2021-07-13 09:57:35,858 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x1024f60d0>
2021-07-13 09:57:35,858 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2021-07-13 09:57:35,858 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x102490670>
2021-07-13 09:57:35,858 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x1024995e0>
2021-07-13 09:57:35,858 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x1026dbaf0>
2021-07-13 09:57:35,858 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x102541ca0>
2021-07-13 09:57:35,858 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2021-07-13 09:57:35,858 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x1026d3d30>
2021-07-13 09:57:35,858 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.2.16/libexec/lib/python3.9/site-packages/awscli/data/cli.json
2021-07-13 09:57:35,860 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x102603940>
2021-07-13 09:57:35,861 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x1026044c0>
2021-07-13 09:57:35,861 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x102604430>
2021-07-13 09:57:35,861 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x1026045e0>
2021-07-13 09:57:35,861 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x102604550>
2021-07-13 09:57:35,861 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x102777040>
2021-07-13 09:57:35,861 - MainThread - botocore.session - DEBUG - Setting config variable for profile to 'default'
2021-07-13 09:57:35,861 - MainThread - botocore.session - DEBUG - Setting config variable for region to 'us-west-2'
2021-07-13 09:57:35,861 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.2.16 Python/3.9.6 Darwin/20.5.0 source/x86_64 prompt/off
2021-07-13 09:57:35,861 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', '--profile', 'default', '--region', 'us-west-2', 'honeycode', 'list-table-rows', '--workbook-id', '3578B9F9-FCD6-449A-ADD2-EF3B62C9BC2A', '--table-id', '3578B9F9-FCD6-449A-ADD2-EF3B62C9BC2A', '--starting-token', 'abc', '--max-results', '10']
2021-07-13 09:57:35,861 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x1026c9790>
2021-07-13 09:57:35,861 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x1021c4040>
2021-07-13 09:57:35,861 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x10273d1f0>
2021-07-13 09:57:35,861 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x10218b280>
2021-07-13 09:57:35,862 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x1021ebaf0>
2021-07-13 09:57:35,863 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-07-13 09:57:35,869 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2021-07-13 09:57:35,870 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x102541b80>
2021-07-13 09:57:35,870 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x1024f1f70>
2021-07-13 09:57:35,902 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.2.16/libexec/lib/python3.9/site-packages/botocore/data/honeycode/2020-03-01/service-2.json
2021-07-13 09:57:35,904 - MainThread - botocore.hooks - DEBUG - Event building-command-table.honeycode: calling handler <function add_waiters at 0x1026d3d30>
2021-07-13 09:57:35,939 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('workbook-id', <awscli.arguments.CLIArgument object at 0x10288f5b0>), ('table-id', <awscli.arguments.CLIArgument object at 0x10288f4f0>), ('row-ids', <awscli.arguments.ListArgument object at 0x10288f4c0>), ('max-results', <awscli.arguments.CLIArgument object at 0x10288f460>), ('next-token', <awscli.arguments.CLIArgument object at 0x10288f430>)])
2021-07-13 09:57:35,939 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.honeycode.list-table-rows: calling handler <function add_streaming_output_arg at 0x1026c9a60>
2021-07-13 09:57:35,939 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.honeycode.list-table-rows: calling handler <function add_cli_input_json at 0x1021f1310>
2021-07-13 09:57:35,940 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.honeycode.list-table-rows: calling handler <function add_cli_input_yaml at 0x1021f1550>
2021-07-13 09:57:35,940 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.honeycode.list-table-rows: calling handler <function unify_paging_params at 0x1024f6700>
2021-07-13 09:57:35,979 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.2.16/libexec/lib/python3.9/site-packages/botocore/data/honeycode/2020-03-01/paginators-1.json
2021-07-13 09:57:35,979 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.2.16/libexec/lib/python3.9/site-packages/botocore/data/honeycode/2020-03-01/paginators-1.sdk-extras.json
2021-07-13 09:57:35,979 - MainThread - awscli.customizations.paginate - DEBUG - Modifying paging parameters for operation: ListTableRows
2021-07-13 09:57:35,980 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.honeycode.list-table-rows: calling handler <function add_generate_skeleton at 0x1025f0ee0>
2021-07-13 09:57:35,980 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.honeycode.list-table-rows: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x10288f6d0>>
2021-07-13 09:57:35,980 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.honeycode.list-table-rows: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x10288f670>>
2021-07-13 09:57:35,980 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.honeycode.list-table-rows: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x10288fa00>>
2021-07-13 09:57:35,981 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.honeycode.list-table-rows: calling handler functools.partial(<function check_should_enable_pagination at 0x1024f6820>, ['next-token', 'max-results'], {}, OrderedDict([('workbook-id', <awscli.arguments.CLIArgument object at 0x10288f5b0>), ('table-id', <awscli.arguments.CLIArgument object at 0x10288f4f0>), ('row-ids', <awscli.arguments.ListArgument object at 0x10288f4c0>), ('max-results', <awscli.arguments.CLIArgument object at 0x10288f460>), ('next-token', <awscli.arguments.CLIArgument object at 0x10288f430>), ('cli-input-json', <awscli.customizations.cliinput.CliInputJSONArgument object at 0x10288f6d0>), ('cli-input-yaml', <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x10288f670>), ('starting-token', <awscli.customizations.paginate.PageArgument object at 0x10288f730>), ('page-size', <awscli.customizations.paginate.PageArgument object at 0x10288f970>), ('max-items', <awscli.customizations.paginate.PageArgument object at 0x10288f8e0>), ('generate-cli-skeleton', <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x10288fa00>)]))
2021-07-13 09:57:35,981 - MainThread - awscli.customizations.paginate - DEBUG - User has specified a manual pagination arg. Automatically setting --no-paginate.
2021-07-13 09:57:35,981 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/Cellar/awscli/2.2.16/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 459, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/Cellar/awscli/2.2.16/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 594, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/Cellar/awscli/2.2.16/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 740, in __call__
    self._emit(event, parsed_args=parsed_args,
  File "/usr/local/Cellar/awscli/2.2.16/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 846, in _emit
    return self._session.emit(name, **kwargs)
  File "/usr/local/Cellar/awscli/2.2.16/libexec/lib/python3.9/site-packages/botocore/session.py", line 669, in emit
    return self._events.emit(event_name, **kwargs)
  File "/usr/local/Cellar/awscli/2.2.16/libexec/lib/python3.9/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/Cellar/awscli/2.2.16/libexec/lib/python3.9/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/Cellar/awscli/2.2.16/libexec/lib/python3.9/site-packages/awscli/customizations/paginate.py", line 215, in check_should_enable_pagination
    ensure_paging_params_not_set(parsed_args, shadowed_args)
  File "/usr/local/Cellar/awscli/2.2.16/libexec/lib/python3.9/site-packages/awscli/customizations/paginate.py", line 237, in ensure_paging_params_not_set
    raise ParamValidationError(
awscli.customizations.exceptions.ParamValidationError: Cannot specify --no-paginate along with pagination arguments: --starting-token

Cannot specify --no-paginate along with pagination arguments: --starting-token
```

**Comment by stobrien89** [comment]
Hi @voldyman,

Thanks for reaching out!  We hide service-specific pagination params, because they can vary from service to service— `--max-items` and `--starting-token` were introduced to provide consistent params for paginated operations.  While strange, this is expected behavior.  The service-vended params will still work if used together, but mixing cli and service-vended params will result in undesirable behavior, like you've shown.  We recommend sticking with documented parameters.
