### ISSUE TITLE
AWS CLI: Two different SSL certificate issues

### ISSUE THREAD

**Issue by FenryrMKIII** [aws/aws-cli#6384]
I am running on windows and am executing AWS CLI commands using Cmder. My organization is using SSO for logging into our AWS accounts.

I was previously having a `SSL validation failed [...] self signed certificate in certificate chain` error when issuing AWS CLI commands e.g. `aws s3 ls`. 

I was able to solve this issue by adding the ROOT certificate of my organization (we run behind Zscaler) to my AWS config file like this : 
```
[profile my-profile]
sso_start_url = https://xxx/yyy
sso_region = eu-west-1
sso_account_id = ZZZZZZZZ
sso_role_name = AdministratorAccess
region = eu-west-1
ca_bundle = PATH_TO_CERT\CERT.pem
```
And this indeed solves my issue for issuing commands like `aws s3 ls`. However, now, I have issues when I want to login. So the following command : 
```
aws sso login --profile my-profile
```
issues the following error : 

```
SSL validation failed [...]  unable to get local issuer certificate
```

If I remove the `ca_bundle` line in the config, it works. But then that means I have to remove/add this line every time I log in and then want to issue AWS CLI commands. This is cumbersome. 

How can I solve both errors at the same time without having to comment in and out the `ca_bundle` line ?

Thanks for your support

**Comment by stobrien89** [comment]
Hi @FenryrMKIII,

Sorry to hear you're having issues.  I can only think of one slightly better workaround for this in the meantime (while we're troubleshooting this issue) and that would be to toggle the `AWS_CA_BUNDLE` environment variable.  That could be slightly less cumbersome than constantly making edits to the config file.  

One thing I would check for is whether or not `https://oidc.eu-west-1.amazonaws.com:443/` is being blocked by Zscaler, but we'll need debug logs in order to further investigate this.   Please provide us the full output after appending `--debug` to your `sso login` attempt (with the `ca_bundle` set) and obscure any sensitive information, such as keys and account numbers.  Thanks!

**Comment by FenryrMKIII** [comment]
Hello thanks for the support.

Please find the debug herebelow : 

```Bash
2021-09-08 08:18:45,074 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.2.11 Python/3.8.8 Windows/10 exe/AMD64
2021-09-08 08:18:45,075 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['sso', 'login', '--debug', '--profile', 'XXXXXX']
2021-09-08 08:18:45,193 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x0000019A6D1A1F70>
2021-09-08 08:18:45,194 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x0000019A6CFE1D30>
2021-09-08 08:18:45,194 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2021-09-08 08:18:45,204 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x0000019A6CF884C0>
2021-09-08 08:18:45,204 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x0000019A6CF8E5E0>
2021-09-08 08:18:45,204 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x0000019A6D1B39D0>
2021-09-08 08:18:45,204 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x0000019A6D029B80>
2021-09-08 08:18:45,204 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2021-09-08 08:18:45,204 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x0000019A6D1A9C10>
2021-09-08 08:18:45,204 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\awscli\data\cli.json
2021-09-08 08:18:45,208 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x0000019A6D0DAB80>
2021-09-08 08:18:45,208 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x0000019A6D0DD700>
2021-09-08 08:18:45,208 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x0000019A6D0DD670>
2021-09-08 08:18:45,208 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x0000019A6D0DD820>
2021-09-08 08:18:45,208 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x0000019A6D0DD790>
2021-09-08 08:18:45,208 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x0000019A6D247FC0>
2021-09-08 08:18:45,209 - MainThread - botocore.session - DEBUG - Setting config variable for profile to 'XXXXXX'
2021-09-08 08:18:45,209 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.2.11 Python/3.8.8 Windows/10 exe/AMD64 prompt/off
2021-09-08 08:18:45,209 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['sso', 'login', '--debug', '--profile', 'XXXXXX']
2021-09-08 08:18:45,209 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x0000019A6D1A25E0>
2021-09-08 08:18:45,209 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x0000019A6C523DC0>
2021-09-08 08:18:45,210 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x0000019A6D20A430>
2021-09-08 08:18:45,210 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x0000019A6C5201F0>
2021-09-08 08:18:45,210 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x0000019A6C580A60>
2021-09-08 08:18:45,211 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-09-08 08:18:45,213 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2021-09-08 08:18:45,213 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x0000019A6D029A60>
2021-09-08 08:18:45,213 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x0000019A6CFE0C10>
2021-09-08 08:18:45,294 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\botocore\data\sso\2019-06-10\service-2.json
2021-09-08 08:18:45,295 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sso: calling handler <function add_sso_commands at 0x0000019A6CFE0670>
2021-09-08 08:18:45,295 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sso: calling handler <function add_waiters at 0x0000019A6D1A9C10>
2021-09-08 08:18:45,375 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sso_login: calling handler <function add_waiters at 0x0000019A6D1A9C10>
2021-09-08 08:18:45,377 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\botocore\data\endpoints.json
2021-09-08 08:18:45,381 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x0000019A6BD38AF0>
2021-09-08 08:18:45,382 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\botocore\data\sso-oidc\2019-06-10\service-2.json
2021-09-08 08:18:45,383 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.sso-oidc: calling handler <function add_generate_presigned_url at 0x0000019A6BCE6D30>
2021-09-08 08:18:45,385 - MainThread - botocore.endpoint - DEBUG - Setting oidc timeout as (60, 60)
2021-09-08 08:18:45,386 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.sso-oidc.StartDeviceAuthorization: calling handler <function base64_decode_input_blobs at 0x0000019A6D20AB80>
2021-09-08 08:18:45,386 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.sso-oidc.StartDeviceAuthorization: calling handler <function generate_idempotent_uuid at 0x0000019A6BD55AF0>
2021-09-08 08:18:45,387 - MainThread - botocore.hooks - DEBUG - Event before-call.sso-oidc.StartDeviceAuthorization: calling handler <function inject_api_version_header_if_needed at 0x0000019A6BD5B3A0>
2021-09-08 08:18:45,387 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=StartDeviceAuthorization) with params: {'url_path': '/device_authorization', 'query_string': {}, 'method': 'POST', 'headers': {'User-Agent': 'aws-cli/2.2.11 Python/3.8.8 Windows/10 exe/AMD64 prompt/off command/sso.login'}, 'body': b'{"clientId": "YYYYYYYYYYYYYYYYY", "clientSecret": "ZZZZZZZZZZZ.WWWW", "startUrl": "https://fliflaflu.awsapps.com/start"}', 'url': 'https://oidc.eu-west-1.amazonaws.com/device_authorization', 'context': {'client_region': 'eu-west-1', 'client_config': <botocore.config.Config object at 0x0000019A6D289C10>, 'has_streaming_input': False, 'auth_type': 'none'}}
2021-09-08 08:18:45,387 - MainThread - botocore.hooks - DEBUG - Event request-created.sso-oidc.StartDeviceAuthorization: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x0000019A6D289550>>
2021-09-08 08:18:45,387 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sso-oidc.StartDeviceAuthorization: calling handler <function set_operation_specific_signer at 0x0000019A6BD559D0>
2021-09-08 08:18:45,387 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://oidc.eu-west-1.amazonaws.com/device_authorization, headers={'User-Agent': b'aws-cli/2.2.11 Python/3.8.8 Windows/10 exe/AMD64 prompt/off command/sso.login', 'Content-Length': '972'}>
2021-09-08 08:18:45,388 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oidc.eu-west-1.amazonaws.com:443
2021-09-08 08:18:45,521 - MainThread - botocore.endpoint - DEBUG - Exception received when sending HTTP request.
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 411, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore\httpsession.py", line 323, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 507, in increment
  File "urllib3\packages\six.py", line 769, in reraise
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 411, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore\endpoint.py", line 200, in _do_get_response
  File "botocore\endpoint.py", line 269, in _send
  File "botocore\httpsession.py", line 350, in send
botocore.exceptions.SSLError: SSL validation failed for https://oidc.eu-west-1.amazonaws.com/device_authorization [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)
2021-09-08 08:18:45,522 - MainThread - botocore.hooks - DEBUG - Event needs-retry.sso-oidc.StartDeviceAuthorization: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x0000019A6D2C3520>>
2021-09-08 08:18:45,522 - MainThread - botocore.retries.standard - DEBUG - Retry needed, retrying request after delay of: 0.1122129417644615
2021-09-08 08:18:45,523 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.1122129417644615 seconds
2021-09-08 08:18:45,636 - MainThread - botocore.hooks - DEBUG - Event request-created.sso-oidc.StartDeviceAuthorization: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x0000019A6D289550>>
2021-09-08 08:18:45,636 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sso-oidc.StartDeviceAuthorization: calling handler <function set_operation_specific_signer at 0x0000019A6BD559D0>
2021-09-08 08:18:45,636 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://oidc.eu-west-1.amazonaws.com/device_authorization, headers={'User-Agent': b'aws-cli/2.2.11 Python/3.8.8 Windows/10 exe/AMD64 prompt/off command/sso.login', 'Content-Length': '972'}>
2021-09-08 08:18:45,637 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): oidc.eu-west-1.amazonaws.com:443
2021-09-08 08:18:45,750 - MainThread - botocore.endpoint - DEBUG - Exception received when sending HTTP request.
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 411, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore\httpsession.py", line 323, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 507, in increment
  File "urllib3\packages\six.py", line 769, in reraise
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 411, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore\endpoint.py", line 200, in _do_get_response
  File "botocore\endpoint.py", line 269, in _send
  File "botocore\httpsession.py", line 350, in send
botocore.exceptions.SSLError: SSL validation failed for https://oidc.eu-west-1.amazonaws.com/device_authorization [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)
2021-09-08 08:18:45,751 - MainThread - botocore.hooks - DEBUG - Event needs-retry.sso-oidc.StartDeviceAuthorization: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x0000019A6D2C3520>>
2021-09-08 08:18:45,751 - MainThread - botocore.retries.standard - DEBUG - Retry needed, retrying request after delay of: 0.702127195668147
2021-09-08 08:18:45,751 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.702127195668147 seconds
2021-09-08 08:18:46,456 - MainThread - botocore.hooks - DEBUG - Event request-created.sso-oidc.StartDeviceAuthorization: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x0000019A6D289550>>
2021-09-08 08:18:46,456 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sso-oidc.StartDeviceAuthorization: calling handler <function set_operation_specific_signer at 0x0000019A6BD559D0>
2021-09-08 08:18:46,456 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://oidc.eu-west-1.amazonaws.com/device_authorization, headers={'User-Agent': b'aws-cli/2.2.11 Python/3.8.8 Windows/10 exe/AMD64 prompt/off command/sso.login', 'Content-Length': '972'}>
2021-09-08 08:18:46,456 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): oidc.eu-west-1.amazonaws.com:443
2021-09-08 08:18:46,570 - MainThread - botocore.endpoint - DEBUG - Exception received when sending HTTP request.
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 411, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore\httpsession.py", line 323, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 507, in increment
  File "urllib3\packages\six.py", line 769, in reraise
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 411, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore\endpoint.py", line 200, in _do_get_response
  File "botocore\endpoint.py", line 269, in _send
  File "botocore\httpsession.py", line 350, in send
botocore.exceptions.SSLError: SSL validation failed for https://oidc.eu-west-1.amazonaws.com/device_authorization [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)
2021-09-08 08:18:46,571 - MainThread - botocore.hooks - DEBUG - Event needs-retry.sso-oidc.StartDeviceAuthorization: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x0000019A6D2C3520>>
2021-09-08 08:18:46,571 - MainThread - botocore.retries.standard - DEBUG - Max attempts of 3 reached.
2021-09-08 08:18:46,571 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2021-09-08 08:18:46,571 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 411, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore\httpsession.py", line 323, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 507, in increment
  File "urllib3\packages\six.py", line 769, in reraise
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 411, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "awscli\clidriver.py", line 459, in main
  File "awscli\clidriver.py", line 594, in __call__
  File "awscli\customizations\commands.py", line 191, in __call__
  File "awscli\customizations\sso\login.py", line 41, in _run_main
  File "awscli\customizations\sso\utils.py", line 57, in do_sso_login
  File "botocore\utils.py", line 2425, in fetch_token
  File "botocore\utils.py", line 2420, in _token
  File "botocore\utils.py", line 2375, in _poll_for_token
  File "botocore\utils.py", line 2356, in _authorize_client
  File "botocore\client.py", line 278, in _api_call
  File "botocore\client.py", line 583, in _make_api_call
  File "botocore\client.py", line 603, in _make_request
  File "botocore\endpoint.py", line 102, in make_request
  File "botocore\endpoint.py", line 156, in _send_request
  File "botocore\endpoint.py", line 200, in _do_get_response
  File "botocore\endpoint.py", line 269, in _send
  File "botocore\httpsession.py", line 350, in send
botocore.exceptions.SSLError: SSL validation failed for https://oidc.eu-west-1.amazonaws.com/device_authorization [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)

SSL validation failed for https://oidc.eu-west-1.amazonaws.com/device_authorization [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)

```

**Comment by stobrien89** [comment]
Hi @FenryrMKIII, 

Thanks for the additional information!  I'm not seeing anything here that stands out— Did you have a chance to check if your ZScaler configuration is blocking connections to `https://oidc.eu-west-1.amazonaws.com:443/` by chance?  I've seen other service-specific errors like this with ZScaler and that is usually the culprit.

**Comment by FenryrMKIII** [comment]
I checked with my IT department. They confirmed the email is not blocked.

**Comment by stobrien89** [comment]
Hi @FenryrMKIII,

Thanks for the update.  I'm at a loss for what this could be, but I'll review this with the team to get their thoughts.  In the meantime, you may want to also check to see your `sso_start_url` is getting blocked, if you haven't already.

**Comment by stobrien89** [comment]
Hi @FenryrMKIII,

Thanks for your patience.  I was able to review this with the team and it's looking like this is an issue with the certificate bundle— I'd double check with your IT department to see if there's anything they can do (i.e. check to see if they extend to the `oidc` subdomain).  

Another thing you could do to work around this in the meantime is create a separate profile specifically for sso login with all of the same information from `my-profile` above, just without the ca_bundle info.  Your other profile will still have access to the temporary credentials/token generated from `sso login`.

**Comment by stobrien89** [comment]
Hi @FenryrMKIII,

Just checking in— were you able to find a solution?

**Comment by hahastudio** [comment]
For me, I add env `REQUESTS_CA_BUNDLE` and it works.

```
REQUESTS_CA_BUNDLE=/path/to/ZscalerRootCertificate.crt
```
