### ISSUE TITLE
S3 Listing - SSL validation failed for https://XXXX .s3.us-west-2 ... EOF occurred in violation of protocol (_ssl.c:1125)

### ISSUE THREAD

**Issue by hijm** [aws/aws-cli#6403]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
During two "aws s3api list-objects-v2 --bucket XXXX --no-cli-page > file.json" executions against two different s3 buckets I received a message 

SSL validation failed for https://XXXX .s3.us-west-2.amazonaws.com/?list-type=2&continuation-token=YYYYYYYYY&encoding-type=url EOF occurred in violation of protocol (_ssl.c:1125)

After hours running the command, the file doesn't have nothing. File created with size 0.

**SDK version number**
aws-cli/2.2.37 Python/3.8.8 Linux/3.10.0-1160.el7.x86_64 exe/x86_64.centos.7 prompt/off

**Platform/OS/Hardware/Device**
Centos 7.9 VMware Workstation VM 
4GB RAM
4 vCPUs

**To Reproduce (observed behavior)**
It happens with buckets with +39M objects. Both errors were running against buckets with+39M and +200M objects.

**Expected behavior**
A list of objects as was created with other S3 buckets with less number of objects.

**Logs/output**

2021-09-15 21:23:42,405 - MainThread - botocore.endpoint - DEBUG - Exception received when sending HTTP request.
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 699, in urlopen
  File "urllib3/connectionpool.py", line 382, in _make_request
  File "urllib3/connectionpool.py", line 1010, in _validate_conn
  File "urllib3/connection.py", line 411, in connect
  File "urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore/httpsession.py", line 344, in send
  File "urllib3/connectionpool.py", line 755, in urlopen
  File "urllib3/util/retry.py", line 507, in increment
  File "urllib3/packages/six.py", line 769, in reraise
  File "urllib3/connectionpool.py", line 699, in urlopen
  File "urllib3/connectionpool.py", line 382, in _make_request
  File "urllib3/connectionpool.py", line 1010, in _validate_conn
  File "urllib3/connection.py", line 411, in connect
  File "urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore/endpoint.py", line 200, in _do_get_response
  File "botocore/endpoint.py", line 269, in _send
  File "botocore/httpsession.py", line 371, in send
botocore.exceptions.SSLError: SSL validation failed for https://XXXX .s3.us-west-2.amazonaws.com/?list-type=2&continuation-token=YYYYYYYYY&encoding-type=url EOF occurred in violation of protocol (_ssl.c:1125)
2021-09-15 21:23:48,493 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListObjectsV2: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x7efd219e2d00>>
2021-09-15 21:23:49,147 - MainThread - botocore.retries.standard - DEBUG - Max attempts of 3 reached.
2021-09-15 21:23:49,747 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2021-09-15 21:23:50,322 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListObjectsV2: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x7efd219e2d60>>
2021-09-15 21:23:51,179 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 699, in urlopen
  File "urllib3/connectionpool.py", line 382, in _make_request
  File "urllib3/connectionpool.py", line 1010, in _validate_conn
  File "urllib3/connection.py", line 411, in connect
  File "urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botocore/httpsession.py", line 344, in send
  File "urllib3/connectionpool.py", line 755, in urlopen
  File "urllib3/util/retry.py", line 507, in increment
  File "urllib3/packages/six.py", line 769, in reraise
  File "urllib3/connectionpool.py", line 699, in urlopen
  File "urllib3/connectionpool.py", line 382, in _make_request
  File "urllib3/connectionpool.py", line 1010, in _validate_conn
  File "urllib3/connection.py", line 411, in connect
  File "urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "awscli/clidriver.py", line 459, in main
  File "awscli/clidriver.py", line 594, in __call__
  File "awscli/clidriver.py", line 770, in __call__
  File "awscli/clidriver.py", line 903, in invoke
  File "awscli/clidriver.py", line 925, in _display_response
  File "awscli/formatter.py", line 82, in __call__
  File "botocore/paginate.py", line 449, in build_full_result
  File "botocore/paginate.py", line 255, in __iter__
  File "botocore/paginate.py", line 332, in _make_request
  File "botocore/client.py", line 278, in _api_call
  File "botocore/client.py", line 583, in _make_api_call
  File "botocore/client.py", line 603, in _make_request
  File "botocore/endpoint.py", line 102, in make_request
  File "botocore/endpoint.py", line 156, in _send_request
  File "botocore/endpoint.py", line 200, in _do_get_response
  File "botocore/endpoint.py", line 269, in _send
  File "botocore/httpsession.py", line 371, in send
botocore.exceptions.SSLError: SSL validation failed for https://XXXX .s3.us-west-2.amazonaws.com/?list-type=2&continuation-token=YYYYYYYYYYYYY&encoding-type=url EOF occurred in violation of protocol (_ssl.c:1125)

SSL validation failed for https://XXXX .s3.us-west-2.amazonaws.com/?list-type=2&continuation-token=YYYYYYYYYYYYY&encoding-type=url EOF occurred in violation of protocol (_ssl.c:1125)

**Additional context**
The default output format is json
Access configured with KEYs

**Comment by stobrien89** [comment]
Hi @hijm,

Sorry to hear you're having issues.  Can you confirm whether or not you're running behind a proxy?  If so, are you using a custom ca bundle? Are any other AWS CLI operations completing successfully?  Thanks!

**Comment by hijm** [comment]
Hi @stobrien89,

There is no proxy between me and AWS. Also, there is no custom ca bundle. We have 61 buckets, only 2 of them I have this problem, the +39M objects.

**Comment by stobrien89** [comment]
Hi @hijm,

Thanks for confirming.  It's tough to say what could be causing this, but I'll review this with the team to get their thoughts.
