### ISSUE TITLE
`aws configure import --csv` failing with missing header error when header *is* in the CSV

### ISSUE THREAD

**Issue by TRiggAtGM** [aws/aws-cli#6428]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

When running `aws configure import --csv credentials.csv` the command fails with the error `Expected header "User Name" not found` despite the header "User Name" being present

**SDK version number**
aws-cli/2.2.41 Python/3.9.7 Darwin/20.4.0 source/x86_64 prompt/off

**Platform/OS/Hardware/Device**
What are you running the cli on?

macOS/Big Sur 11.3.1/6-Core Intel Core i7/MacBook Pro

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

1. Install aws cli v2
2. Download `credentials.csv` file from IAM
3. Update `credentials.csv` file to include "User Name"
4. Run

```zsh
aws configure import --csv credentials.csv
```

**Expected behavior**

Command succeeds and `~/.aws/credentials` is updated

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

```
2021-09-28 11:25:43,521 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.2.41 Python/3.9.7 Darwin/20.4.0 source/x86_64
2021-09-28 11:25:43,521 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['configure', 'import', '--csv', '/Users/Travis.Rigg/Downloads/travis.rigg_accessKeys.csv', '--debug']
2021-09-28 11:25:43,583 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x11199cee0>
2021-09-28 11:25:43,583 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x1117e50d0>
2021-09-28 11:25:43,583 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2021-09-28 11:25:43,583 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x111781670>
2021-09-28 11:25:43,583 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x1117875e0>
2021-09-28 11:25:43,583 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x1119b18b0>
2021-09-28 11:25:43,583 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x111831ca0>
2021-09-28 11:25:43,583 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2021-09-28 11:25:43,583 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x1119a5af0>
2021-09-28 11:25:43,584 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.2.41/libexec/lib/python3.9/site-packages/awscli/data/cli.json
2021-09-28 11:25:43,587 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x1118ef940>
2021-09-28 11:25:43,587 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x1118f04c0>
2021-09-28 11:25:43,587 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x1118f0430>
2021-09-28 11:25:43,587 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x1118f05e0>
2021-09-28 11:25:43,587 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x1118f0550>
2021-09-28 11:25:43,587 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x111a490c0>
2021-09-28 11:25:43,587 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.2.41 Python/3.9.7 Darwin/20.4.0 source/x86_64 prompt/off
2021-09-28 11:25:43,587 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['configure', 'import', '--csv', 'OBFUSCATED.csv', '--debug']
2021-09-28 11:25:43,587 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x1119a0550>
2021-09-28 11:25:43,588 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x1114c0160>
2021-09-28 11:25:43,588 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x111a0eee0>
2021-09-28 11:25:43,588 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x11148a3a0>
2021-09-28 11:25:43,588 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x1114ebc10>
2021-09-28 11:25:43,590 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-09-28 11:25:43,596 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x111831b80>
2021-09-28 11:25:43,596 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x1117e0f70>
2021-09-28 11:25:43,596 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure: calling handler <function _add_wizard_command at 0x111a0ee50>
2021-09-28 11:25:43,596 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure: calling handler <function add_waiters at 0x1119a5af0>
2021-09-28 11:25:43,597 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.configure.anonymous: calling handler <awscli.paramfile.URIArgumentHandler object at 0x111a871c0>
2021-09-28 11:25:43,597 - MainThread - botocore.hooks - DEBUG - Event building-command-table.configure_import: calling handler <function add_waiters at 0x1119a5af0>
2021-09-28 11:25:43,597 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.import.csv: calling handler <awscli.paramfile.
URIArgumentHandler object at 0x111a871c0>
2021-09-28 11:25:43,597 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.import: calling handler <awscli.argprocess.ParamShorthandParser object at 0x1114b6d00>
2021-09-28 11:25:43,597 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.import.skip-invalid: calling handler <awscli.paramfile.URIArgumentHandler object at 0x111a871c0>
2021-09-28 11:25:43,597 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.import: calling handler <awscli.argprocess.ParamShorthandParser object at 0x1114b6d00>
2021-09-28 11:25:43,598 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.import.profile-prefix: calling handler <awscli.paramfile.URIArgumentHandler object at 0x111a871c0>
2021-09-28 11:25:43,598 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.import: calling handler <awscli.argprocess.ParamShorthandParser object at 0x1114b6d00>
2021-09-28 11:25:43,598 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/Cellar/awscli/2.2.41/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 459, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/Cellar/awscli/2.2.41/libexec/lib/python3.9/site-packages/awscli/customizations/commands.py", line 197, in __call__
    return self.subcommand_table[parsed_args.subcommand](remaining,
  File "/usr/local/Cellar/awscli/2.2.41/libexec/lib/python3.9/site-packages/awscli/customizations/commands.py", line 191, in __call__
    rc = self._run_main(parsed_args, parsed_globals)
  File "/usr/local/Cellar/awscli/2.2.41/libexec/lib/python3.9/site-packages/awscli/customizations/configure/importer.py", line 95, in _run_main
    self._import_csv(parsed_args.csv)
  File "/usr/local/Cellar/awscli/2.2.41/libexec/lib/python3.9/site-packages/awscli/customizations/configure/importer.py", line 83, in _import_csv
    credentials = self._csv_parser.parse_credentials(contents)
  File "/usr/local/Cellar/awscli/2.2.41/libexec/lib/python3.9/site-packages/awscli/customizations/configure/importer.py", line 181, in parse_credentials
    parsed_rows = self._parse_csv(contents)
  File "/usr/local/Cellar/awscli/2.2.41/libexec/lib/python3.9/site-packages/awscli/customizations/configure/importer.py", line 164, in _parse_csv
    header_indices = self._extract_expected_header_indices(parsed_headers)
  File "/usr/local/Cellar/awscli/2.2.41/libexec/lib/python3.9/site-packages/awscli/customizations/configure/importer.py", line 128, in _extract_expected_header_indices
    raise CredentialParserError(self._HEADER_NOT_FOUND % header)
awscli.customizations.configure.importer.CredentialParserError: Expected header "User Name" not found

Expected header "User Name" not found
```

As you can see, I have obfuscated the file path as I felt it would pose issues with my company's security policies

**Additional context**

This is a brand new machine and a fresh install of the AWS cli v2

**Comment by TRiggAtGM** [comment]
It looks like my work filling out the info was lost. I will edit the issue and fill all of that out again

**Comment by kdaily** [comment]
Hi @TRiggAtGM,

Thanks for your post. You're missing the `file://` prefix when specifying the input CSV file. Your command should look like:

```
aws configure import –csv file://credentials.csv
```

I confirmed that if I specify a file name without this, I get the same error as you. See the documentation page and examples for more details on the command usage (note this is available only in the AWS CLI v2):

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/configure/import.html#examples
