### ISSUE TITLE
Missing get-vpn-connection-device-* commands

### ISSUE THREAD

**Issue by triggan** [aws/aws-cli#6432]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Both the `aws ec2 get-vpn-connection-device-sample-configuration` [1] and `aws ec2 get-vpn-connection-device-types` [2] commands are missing from the current AWS CLI 2.x release.

[1] https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/get-vpn-connection-device-sample-configuration.html
[2] https://docs.aws.amazon.com/cli/latest/reference/ec2/get-vpn-connection-device-types.html 

**SDK version number**
aws-cli/2.2.37

**Platform/OS/Hardware/Device**
Both MacOS and Amazon Linux 2

**To Reproduce (observed behavior)**
aws ec2 get-vpn-connection-device-sample-configuration  returns a command not found and list of all ec2 commands available (in which either of the get-vpn commands are listed).

**Expected behavior**
Expected both commands to be available for use, as both are included in the latest docs.

**Logs/output**
2021-09-28 17:13:43,503 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "argparse.py", line 1800, in parse_known_args
  File "argparse.py", line 2009, in _parse_known_args
  File "argparse.py", line 1965, in consume_positionals
  File "argparse.py", line 1858, in take_action
  File "argparse.py", line 2390, in _get_values
  File "awscli/argparser.py", line 92, in _check_value
argparse.ArgumentError: argument operation: Invalid choice, valid choices are:   (and then lists all of the available commands which does not include the get-vpn commands)

**Additional context**
N/A

**Comment by nateprewitt** [comment]
Hi @triggan,

I believe you're using a version of the AWS CLI v2 that was released prior to these APIs being available. The current release of the CLI v2 is 2.2.41 and these changes were added in 2.2.40 ([changelog entry](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst#L29)). Could you try upgrading and checking again? Thanks!

**Comment by triggan** [comment]
Ha! I guess I should never assume that the API for functionality that has been around for awhile would be there in a very recent version.  Good call.  I updated and it is there.  Closing the issue.
