### ISSUE TITLE
'aws elasticbeanstalk list-platform-versions' Filter flag failing on certain option combinations (InvalidParameterCombination)

### ISSUE THREAD

**Issue by MoG-AWS** [aws/aws-cli#6446]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
An issue with the 'aws elasticbeanstalk list-platform-versions' call.
Specifically the options of the --filter tag.
Certain combinations of Type & Operator field do not support 'contains' 'begins_with' and 'ends_with' and results in error as following
-----
An error occurred (InvalidParameterCombination) when calling the ListPlatformVersions operation: PlatformBranchName filter is invalid: PlatformBranchName.
-----

**Platform/OS/Hardware/Device**
What are you running the cli on?
Both versions of aws cli v1 and v2 have been tested on the platforms 
MacOS Catalina version: 10.15.7 
Has also been tested on: cpe:/o:fedoraproject:fedora:34

**To Reproduce (observed behavior)**
Steps to reproduce the behavior
   - run the following command 
   - aws elasticbeanstalk list-platform-versions --filters '[{"Type":"PlatformName","Operator":"contains","Values":["PHP"]},{"Type":"PlatformBranchName","Operator":"contains","Values":["PHP"]},{"Type":"ProgrammingLanguageName","Operator":"=","Values":["PHP"]},{"Type":"OperatingSystemName","Operator":"=","Values":["PHP"]}]'
   - on either version 1 or version 2 of the aws cli
   - thereafter toggle all available combinations of Type & Operator field to view additional errors

**Expected behavior**
Expected listed platform versions to be filtered by filter options as per docs https://awscli.amazonaws.com/v2/documentation/api/latest/reference/elasticbeanstalk/list-platform-versions.html#options.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.
-----
Traceback (most recent call last):
  File "awscli/clidriver.py", line 457, in main
  File "awscli/clidriver.py", line 586, in __call__
  File "awscli/clidriver.py", line 762, in __call__
  File "awscli/clidriver.py", line 895, in invoke
  File "awscli/clidriver.py", line 917, in _display_response
  File "awscli/formatter.py", line 82, in __call__
  File "botocore/paginate.py", line 449, in build_full_result
  File "botocore/paginate.py", line 255, in __iter__
  File "botocore/paginate.py", line 332, in _make_request
  File "botocore/client.py", line 249, in _api_call
  File "botocore/client.py", line 568, in _make_api_call
botocore.exceptions.ClientError: An error occurred (InvalidParameterCombination) when calling the ListPlatformVersions operation: PlatformBranchName filter is invalid: PlatformBranchName.

An error occurred (InvalidParameterCombination) when calling the ListPlatformVersions operation: PlatformBranchName filter is invalid: PlatformBranchName.
-----

**Additional context**

**Comment by tim-finnigan** [comment]
Hi @MoG-AWS, thanks for bringing this to our attention. I was able to reproduce this issue. 

I created a ticket for the Elastic Beanstalk team to review. I’m transferring this issue to our shared SDK repository since it appears to be a service issue that would affect each SDK. I will share updates here when we hear back from that team.

**Comment by tim-finnigan** [comment]
P53352913
