### ISSUE TITLE
DMS S3Settings doesn't support CannedAclForObjects

### ISSUE THREAD

**Issue by micah5** [aws/aws-cli#6454]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
According to the [API docs](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/dms/modify-endpoint.html), `dms modify-endpoint` supports an argument `s3-settings` that takes in a JSON formatted string with potential key `"CannedAclForObjects"`. However, when attempting to use this key the following error is given:

```
Unknown parameter in S3Settings: "CannedAclForObjects", must be one of: ServiceAccessRoleArn, ExternalTableDefinition, CsvRowDelimiter, CsvDelimiter, BucketFolder, BucketName, CompressionType, EncryptionMode, ServerSideEncryptionKmsKeyId, DataFormat, EncodingType, DictPageSizeLimit, RowGroupLength, DataPageSize, ParquetVersion, EnableStatistics, IncludeOpForFullLoad, CdcInsertsOnly, TimestampColumnName, ParquetTimestampInMillisecond, CdcInsertsAndUpdates, DatePartitionEnabled, DatePartitionSequence, DatePartitionDelimiter, UseCsvNoSupValue, CsvNoSupValue, PreserveTransactions, CdcPath
```

It also fails with the same error on `create-endpoint`

**SDK version number**
aws-cli/1.19.103 Python/3.9.1 Linux/5.11.0-37-generic botocore/1.20.105

**Platform/OS/Hardware/Device**
Ubuntu 20.04.2 LTS

**To Reproduce (observed behavior)**
First, create an s3 bucket `<bucket_name>` and an IAM role `<service_access_role>` with the permissions listed [here](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.S3.html#CHAP_Target.S3.Prerequisites).

Then, run either
```
aws dms create-endpoint --endpoint-identifier s3-test --endpoint-type target --engine-name s3 --s3-settings '{"BucketName":<bucket_name>, "ServiceAccessRoleArn": <service_access_role>}'
aws dms modify-endpoint --endpoint-arn <arn> --s3-settings '{"CannedAclForObjects":"bucket-owner-full-control"}'
```

or 
```
aws dms create-endpoint --endpoint-identifier s3-test --endpoint-type target --engine-name s3 --s3-settings '{"BucketName":<bucket_name>, "ServiceAccessRoleArn": <service_access_role>, "CannedAclForObjects":"bucket-owner-full-control"}'
```

**Expected behavior**
`CannedAclForObjects` should be added to the endpoint settings.

**Logs/output**
```
Traceback (most recent call last):
  File "/home/micah/miniconda3/lib/python3.9/site-packages/awscli/clidriver.py", line 218, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/home/micah/miniconda3/lib/python3.9/site-packages/awscli/clidriver.py", line 362, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/home/micah/miniconda3/lib/python3.9/site-packages/awscli/clidriver.py", line 531, in __call__
    return self._operation_caller.invoke(
  File "/home/micah/miniconda3/lib/python3.9/site-packages/awscli/clidriver.py", line 653, in invoke
    response = self._make_client_call(
  File "/home/micah/miniconda3/lib/python3.9/site-packages/awscli/clidriver.py", line 665, in _make_client_call
    response = getattr(client, xform_name(operation_name))(
  File "/home/micah/miniconda3/lib/python3.9/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/micah/miniconda3/lib/python3.9/site-packages/botocore/client.py", line 677, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/home/micah/miniconda3/lib/python3.9/site-packages/botocore/client.py", line 725, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/home/micah/miniconda3/lib/python3.9/site-packages/botocore/validate.py", line 319, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
```

**Comment by kdaily** [comment]
Hi @micah5,

It looks like this field was [introduced back in August](https://github.com/boto/botocore/commit/8ff9a5e3c8de6f86135fc9fc8db8f55c55e60d89) with `botocore==1.21.27`. You have `botocore==1.20.105`. You'll need to update your AWS CLI version to at least 1.20.27 to get this API change. Thanks!
