### ISSUE TITLE
honeycode list-table-rows returns invalid body request 

### ISSUE THREAD

**Issue by isaiahtaylor** [aws/aws-cli#6495]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
```bash
aws honeycode list-table-rows --profile <redacted... full admin access> --workbook-id <redacted> --table-id <redacted>
```
```
An error occurred (BadRequestException) when calling the ListTableRows operation: Invalid request body
```

**SDK version number**
```bash
>aws --version
aws-cli/2.2.47 Python/3.8.8 Linux/5.2.9-200.fc30.x86_64 exe/x86_64.fedora.32 prompt/off
```

**Platform/OS/Hardware/Device**
What are you running the cli on?
```
>cat /etc/os-release
NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

1. Create a honeycode account with a workbook and tables
2. Connect to your AWS account
3. Create CLI creds that can access honeycode
4. Run commands as described here: https://docs.aws.amazon.com/cli/latest/reference/honeycode/list-table-rows.html

**Expected behavior**
I expected it to list table rows.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

Redactions:
* \<redacted>
* \<my-workbook-id>
* \<my-table-id>
* \<profile... full access>

```
aws honeycode list-table-rows --profile <profile... full access> --workbook-id <my-workbook-id> --table-id <my-table-id> --debug
2021-10-21 09:44:04,445 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.2.47 Python/3.8.8 Linux/5.2.9-200.fc30.x86_64 exe/x86_64.fedora.32
2021-10-21 09:44:04,445 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['honeycode', 'list-table-rows', '--profile', '<profile... full access>', '--workbook-id', '<my-workbook-id>', '--table-id', '<my-table-id>', '--debug']
2021-10-21 09:44:04,454 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x7f86fb360af0>
2021-10-21 09:44:04,454 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x7f86fb4ba550>
2021-10-21 09:44:04,454 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2021-10-21 09:44:04,454 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7f86fb55cee0>
2021-10-21 09:44:04,454 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7f86fb567d30>
2021-10-21 09:44:04,454 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x7f86fb371550>
2021-10-21 09:44:04,454 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x7f86fb4843a0>
2021-10-21 09:44:04,454 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2021-10-21 09:44:04,454 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x7f86fb368790>
2021-10-21 09:44:04,455 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.2.47/dist/awscli/data/cli.json
2021-10-21 09:44:04,457 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x7f86fb3b75e0>
2021-10-21 09:44:04,457 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x7f86fb3bb160>
2021-10-21 09:44:04,457 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x7f86fb3bb0d0>
2021-10-21 09:44:04,457 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x7f86fb3bb280>
2021-10-21 09:44:04,457 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x7f86fb3bb1f0>
2021-10-21 09:44:04,458 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x7f86fb28b880>
2021-10-21 09:44:04,458 - MainThread - botocore.session - DEBUG - Setting config variable for profile to '<profile... full access>'
2021-10-21 09:44:04,458 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.2.47 Python/3.8.8 Linux/5.2.9-200.fc30.x86_64 exe/x86_64.fedora.32 prompt/off
2021-10-21 09:44:04,458 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['honeycode', 'list-table-rows', '--profile', '<profile... full access>', '--workbook-id', '<my-workbook-id>', '--table-id', '<my-table-id>', '--debug']
2021-10-21 09:44:04,458 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7f86fb363160>
2021-10-21 09:44:04,458 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7f86fbd55280>
2021-10-21 09:44:04,458 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7f86fb2ccf70>
2021-10-21 09:44:04,458 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x7f86fbda55e0>
2021-10-21 09:44:04,458 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f86fbd04e50>
2021-10-21 09:44:04,459 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-10-21 09:44:04,460 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2021-10-21 09:44:04,460 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f86fb484280>
2021-10-21 09:44:04,460 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7f86fb4b53a0>
2021-10-21 09:44:04,468 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.2.47/dist/botocore/data/honeycode/2020-03-01/service-2.json
2021-10-21 09:44:04,470 - MainThread - botocore.hooks - DEBUG - Event building-command-table.honeycode: calling handler <function add_waiters at 0x7f86fb368790>
2021-10-21 09:44:04,479 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('workbook-id', <awscli.arguments.CLIArgument object at 0x7f86fa9d1970>), ('table-id', <awscli.arguments.CLIArgument object at 0x7f86fa9d19a0>), ('row-ids', <awscli.arguments.ListArgument object at 0x7f86fa9d18e0>), ('max-results', <awscli.arguments.CLIArgument object at 0x7f86fa9d18b0>), ('next-token', <awscli.arguments.CLIArgument object at 0x7f86fa9d1850>)])
2021-10-21 09:44:04,479 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.honeycode.list-table-rows: calling handler <function add_streaming_output_arg at 0x7f86fb363700>
2021-10-21 09:44:04,479 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.honeycode.list-table-rows: calling handler <function add_cli_input_json at 0x7f86fbd10670>
2021-10-21 09:44:04,479 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.honeycode.list-table-rows: calling handler <function add_cli_input_yaml at 0x7f86fbd10940>
2021-10-21 09:44:04,479 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.honeycode.list-table-rows: calling handler <function unify_paging_params at 0x7f86fb4bab80>
2021-10-21 09:44:04,487 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.2.47/dist/botocore/data/honeycode/2020-03-01/paginators-1.json
2021-10-21 09:44:04,488 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.2.47/dist/botocore/data/honeycode/2020-03-01/paginators-1.sdk-extras.json
2021-10-21 09:44:04,488 - MainThread - awscli.customizations.paginate - DEBUG - Modifying paging parameters for operation: ListTableRows
2021-10-21 09:44:04,488 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.honeycode.list-table-rows: calling handler <function add_generate_skeleton at 0x7f86fb42db80>
2021-10-21 09:44:04,488 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.honeycode.list-table-rows: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7f86fa9d1a60>>
2021-10-21 09:44:04,488 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.honeycode.list-table-rows: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7f86fa9d1af0>>
2021-10-21 09:44:04,488 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.honeycode.list-table-rows: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f86fa9d1f10>>
2021-10-21 09:44:04,489 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.honeycode.list-table-rows: calling handler functools.partial(<function check_should_enable_pagination at 0x7f86fb4baca0>, ['next-token', 'max-results'], {}, OrderedDict([('workbook-id', <awscli.arguments.CLIArgument object at 0x7f86fa9d1970>), ('table-id', <awscli.arguments.CLIArgument object at 0x7f86fa9d19a0>), ('row-ids', <awscli.arguments.ListArgument object at 0x7f86fa9d18e0>), ('max-results', <awscli.arguments.CLIArgument object at 0x7f86fa9d18b0>), ('next-token', <awscli.arguments.CLIArgument object at 0x7f86fa9d1850>), ('cli-input-json', <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7f86fa9d1a60>), ('cli-input-yaml', <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7f86fa9d1af0>), ('starting-token', <awscli.customizations.paginate.PageArgument object at 0x7f86fa9d1d60>), ('page-size', <awscli.customizations.paginate.PageArgument object at 0x7f86fa9d1d90>), ('max-items', <awscli.customizations.paginate.PageArgument object at 0x7f86fa9d1d00>), ('generate-cli-skeleton', <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f86fa9d1f10>)]))
2021-10-21 09:44:04,489 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.honeycode.list-table-rows.workbook-id: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f86faa4b8e0>
2021-10-21 09:44:04,489 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.honeycode.list-table-rows: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f86fbd4fc40>
2021-10-21 09:44:04,489 - MainThread - awscli.arguments - DEBUG - Unpacked value of '<my-workbook-id>' for parameter "workbook_id": '<my-workbook-id>'
2021-10-21 09:44:04,489 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.honeycode.list-table-rows.table-id: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f86faa4b8e0>
2021-10-21 09:44:04,489 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.honeycode.list-table-rows: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f86fbd4fc40>
2021-10-21 09:44:04,489 - MainThread - awscli.arguments - DEBUG - Unpacked value of '<my-table-id>' for parameter "table_id": '<my-table-id>'
2021-10-21 09:44:04,489 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.honeycode.list-table-rows.row-ids: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f86faa4b8e0>
2021-10-21 09:44:04,489 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.honeycode.list-table-rows.max-results: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f86faa4b8e0>
2021-10-21 09:44:04,489 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.honeycode.list-table-rows.next-token: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f86faa4b8e0>
2021-10-21 09:44:04,489 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.honeycode.list-table-rows.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f86faa4b8e0>
2021-10-21 09:44:04,489 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.honeycode.list-table-rows.cli-input-yaml: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f86faa4b8e0>
2021-10-21 09:44:04,490 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.honeycode.list-table-rows.starting-token: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f86faa4b8e0>
2021-10-21 09:44:04,490 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.honeycode.list-table-rows.page-size: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f86faa4b8e0>
2021-10-21 09:44:04,490 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.honeycode.list-table-rows.max-items: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f86faa4b8e0>
2021-10-21 09:44:04,490 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.honeycode.list-table-rows.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f86faa4b8e0>
2021-10-21 09:44:04,490 - MainThread - botocore.hooks - DEBUG - Event calling-command.honeycode.list-table-rows: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7f86fa9d1a60>>
2021-10-21 09:44:04,490 - MainThread - botocore.hooks - DEBUG - Event calling-command.honeycode.list-table-rows: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7f86fa9d1af0>>
2021-10-21 09:44:04,490 - MainThread - botocore.hooks - DEBUG - Event calling-command.honeycode.list-table-rows: calling handler <bound method GenerateCliSkeletonArgument.generate_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f86fa9d1f10>>
2021-10-21 09:44:04,490 - MainThread - botocore.hooks - DEBUG - Event calling-command.honeycode.list-table-rows: calling handler functools.partial(<function check_should_enable_pagination_call_parameters at 0x7f86fb4c50d0>, ['nextToken', 'maxResults'])
2021-10-21 09:44:04,490 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2021-10-21 09:44:04,490 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2021-10-21 09:44:04,490 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2021-10-21 09:44:04,490 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2021-10-21 09:44:04,490 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2021-10-21 09:44:04,491 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.2.47/dist/botocore/data/endpoints.json
2021-10-21 09:44:04,496 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f86fd13b310>
2021-10-21 09:44:04,497 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.honeycode: calling handler <function add_generate_presigned_url at 0x7f86fd16c8b0>
2021-10-21 09:44:04,499 - MainThread - botocore.endpoint - DEBUG - Setting honeycode timeout as (60, 60)
2021-10-21 09:44:04,499 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.honeycode.ListTableRows: calling handler <function base64_decode_input_blobs at 0x7f86fb2d0700>
2021-10-21 09:44:04,499 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.honeycode.ListTableRows: calling handler <function generate_idempotent_uuid at 0x7f86fd15b430>
2021-10-21 09:44:04,500 - MainThread - botocore.hooks - DEBUG - Event before-call.honeycode.ListTableRows: calling handler <function inject_api_version_header_if_needed at 0x7f86fd0deca0>
2021-10-21 09:44:04,500 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=ListTableRows) with params: {'url_path': '/workbooks/<my-workbook-id>/tables/<my-table-id>/rows/list', 'query_string': {}, 'method': 'POST', 'headers': {'User-Agent': 'aws-cli/2.2.47 Python/3.8.8 Linux/5.2.9-200.fc30.x86_64 exe/x86_64.fedora.32 prompt/off command/honeycode.list-table-rows'}, 'body': b'', 'url': 'https://honeycode.us-west-2.amazonaws.com/workbooks/<my-workbook-id>/tables/<my-table-id>/rows/list', 'context': {'client_region': 'us-west-2', 'client_config': <botocore.config.Config object at 0x7f86fa971340>, 'has_streaming_input': False, 'auth_type': None}}
2021-10-21 09:44:04,500 - MainThread - botocore.hooks - DEBUG - Event request-created.honeycode.ListTableRows: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f86fa971310>>
2021-10-21 09:44:04,500 - MainThread - botocore.hooks - DEBUG - Event choose-signer.honeycode.ListTableRows: calling handler <function set_operation_specific_signer at 0x7f86fd15b310>
2021-10-21 09:44:04,500 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2021-10-21 09:44:04,500 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/workbooks/<my-workbook-id>/tables/<my-table-id>/rows/list

host:honeycode.us-west-2.amazonaws.com
x-amz-date:20211021T164404Z

host;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2021-10-21 09:44:04,500 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20211021T164404Z
20211022/us-west-2/honeycode/aws4_request
<redacted>
2021-10-21 09:44:04,500 - MainThread - botocore.auth - DEBUG - Signature:
<redacted>
2021-10-21 09:44:04,500 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://honeycode.us-west-2.amazonaws.com/workbooks/<my-workbook-id>/tables/<my-table-id>/rows/list, headers={'User-Agent': b'aws-cli/2.2.47 Python/3.8.8 Linux/5.2.9-200.fc30.x86_64 exe/x86_64.fedora.32 prompt/off command/honeycode.list-table-rows', 'X-Amz-Date': b'20211021T164404Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=<redacted>/20211021/us-west-2/honeycode/aws4_request, SignedHeaders=host;x-amz-date, Signature=<redacted>', 'Content-Length': '0'}>
2021-10-21 09:44:04,501 - MainThread - botocore.httpsession - DEBUG - Certificate path: /usr/local/aws-cli/v2/2.2.47/dist/botocore/cacert.pem
2021-10-21 09:44:04,501 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): honeycode.us-west-2.amazonaws.com:443
2021-10-21 09:44:04,891 - MainThread - urllib3.connectionpool - DEBUG - https://honeycode.us-west-2.amazonaws.com:443 "POST /workbooks/<my-workbook-id>/tables/<my-table-id>/rows/list HTTP/1.1" 400 35
2021-10-21 09:44:04,893 - MainThread - botocore.parsers - DEBUG - Response headers: {'Content-Type': 'application/json', 'Content-Length': '35', 'Connection': 'keep-alive', 'Date': 'Thu, 21 Oct 2021 16:44:04 GMT', 'x-amzn-RequestId': '105edf25-ce0e-48c5-92e4-dc186052133e', 'x-amzn-ErrorType': 'BadRequestException', 'x-amz-apigw-id': 'HkTRSF1JvHcFjVA=', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 d8792dbd3191bbe722eba5b536b979c8.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'SEA19-C2', 'X-Amz-Cf-Id': 'Zp4sctBUpnlADmaqeLFtLO8UWiIrFAmwCM4QnZWbEt4s6a0nKKBUwQ=='}
2021-10-21 09:44:04,893 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"message": "Invalid request body"}'
2021-10-21 09:44:04,893 - MainThread - botocore.hooks - DEBUG - Event needs-retry.honeycode.ListTableRows: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x7f86fa6dd130>>
2021-10-21 09:44:04,893 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2021-10-21 09:44:04,894 - MainThread - botocore.hooks - DEBUG - Event after-call.honeycode.ListTableRows: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x7f86fa971c70>>
2021-10-21 09:44:04,894 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/clidriver.py", line 459, in main
  File "awscli/clidriver.py", line 594, in __call__
  File "awscli/clidriver.py", line 770, in __call__
  File "awscli/clidriver.py", line 903, in invoke
  File "awscli/clidriver.py", line 925, in _display_response
  File "awscli/formatter.py", line 82, in __call__
  File "botocore/paginate.py", line 449, in build_full_result
  File "botocore/paginate.py", line 255, in __iter__
  File "botocore/paginate.py", line 332, in _make_request
  File "botocore/client.py", line 278, in _api_call
  File "botocore/client.py", line 597, in _make_api_call
botocore.exceptions.ClientError: An error occurred (BadRequestException) when calling the ListTableRows operation: Invalid request body

An error occurred (BadRequestException) when calling the ListTableRows operation: Invalid request body
```

**Additional context**

This JS snippet works perfectly on the same machine:

```ts
const listCommand = new ListTableRowsCommand({
      workbookId: workbookId,
      tableId: tableId
});

const res = await client.send(listCommand);

console.log(res)
```

The `workbookId` and `tableId` are the same as passed in on the CLI.

Also, this CLI command works perfectly:

```bash
aws honeycode list-tables --profile <profile... full access> --workbook-id <my-workbook-id>
```

**Comment by nateprewitt** [comment]
Hi @isaiahtaylor, this was addressed yesterday in boto/botocore#2511 yesterday with the release of Botocore 1.22.0. The issue is now resolved in Boto3 1.19.0+ and the AWS CLI 1.21.0+.

These changes will be available in the next release of the CLI v2 which is currently scheduled for today.
