### ISSUE TITLE
Failing test while setting up development environment: test_ctrl_c_does_not_print_traceback

### ISSUE THREAD

**Issue by santosh** [aws/aws-cli#6593]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [ ] CLI : passing arguments or cli configurations.
- [x] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?

Platform: AWS EC2
OS: Amazon Linux 2
Python: 3.7.10

**Describe the question**
Before I make any contribution, I wanted to setup my development environment completely. I have done so by:

* creating a virtual environment `python3 -m venv .venv` and getting inside it `. .venv/bin/activate`.
* installing the requirements `pip install -r requirements.txt -r requirements-docs.txt -r requirements-dev.txt`

Before I proceeded further, I wanted to run tests to make sure I'm starting with a clean board.

Although I ran `pytest -x`, I'll only show where the test failed:

```
$ pytest -x tests/integration/test_cli.py
================================================ test session starts =================================================
platform linux -- Python 3.7.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /efs/repos/oss/aws-cli, configfile: pyproject.toml
plugins: cov-2.12.1
collected 43 items

tests/integration/test_cli.py .F

====================================================== FAILURES ======================================================
_________________________ TestBasicCommandFunctionality.test_ctrl_c_does_not_print_traceback _________________________

self = <tests.integration.test_cli.TestBasicCommandFunctionality testMethod=test_ctrl_c_does_not_print_traceback>

    @skip_if_windows('Ctrl-C not supported on windows.')
    def test_ctrl_c_does_not_print_traceback(self):
        # Relying on the fact that this generally takes
        # more than 1 second to complete.
        process = aws('ec2 describe-images', wait_for_finish=False)
        time.sleep(1)
        process.send_signal(signal.SIGINT)
        stdout, stderr = process.communicate()
        self.assertNotIn(b'Traceback', stdout)
>       self.assertNotIn(b'Traceback', stderr)
E       AssertionError: b'Traceback' unexpectedly found in b'Traceback (most recent call last):\n  File "/efs/repos/oss/aws-cli/.venv/bin/aws", line 7, in <module>\n    exec(compile(f.read(), __file__, \'exec\'))\n  File "/efs/repos/oss/aws-cli/bin/aws", line 27, in <module>\n    sys.exit(main())\n  File "/efs/repos/oss/aws-cli/bin/aws", line 23, in main\n    return awscli.clidriver.main()\n  File "/efs/repos/oss/aws-cli/awscli/clidriver.py", line 69, in main\n    driver = create_clidriver()\n  File "/efs/repos/oss/aws-cli/awscli/clidriver.py", line 79, in create_clidriver\n    event_hooks=session.get_component(\'event_emitter\'))\n  File "/efs/repos/oss/aws-cli/awscli/plugin.py", line 44, in load_plugins\n    modules = _import_plugins(plugin_mapping)\n  File "/efs/repos/oss/aws-cli/awscli/plugin.py", line 61, in _import_plugins\n    module = __import__(path, fromlist=[module])\n  File "/efs/repos/oss/aws-cli/awscli/handlers.py", line 42, in <module>\n    from awscli.customizations.configure.configure import register_configure_cmd\n  File "/efs/repos/oss/aws-cli/awscli/customizations/configure/configure.py", line 20, in <module>\n    from awscli.customizations.configure.addmodel import AddModelCommand\n  File "<frozen importlib._bootstrap>", line 983, in _find_and_load\n  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked\n  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked\n  File "<frozen importlib._bootstrap_external>", line 724, in exec_module\n  File "<frozen importlib._bootstrap_external>", line 818, in get_code\n  File "<frozen importlib._bootstrap_external>", line 916, in get_data\nKeyboardInterrupt\n'

tests/integration/test_cli.py:324: AssertionError
============================================== short test summary info ===============================================
FAILED tests/integration/test_cli.py::TestBasicCommandFunctionality::test_ctrl_c_does_not_print_traceback - Asserti...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================ 1 failed, 1 passed in 5.62s =============================================
```

**Comment by kdaily** [comment]
Hi @santosh,

Thanks for your interest in developing on the AWS CLI. Looks like you didn't install the AWS CLI package. In addition to the requirements files, make sure you also install the currently checked out AWS CLI. We commonly install in 'editable' mode like such, from the current directory (where you checked out the AWS CLI Git repository):

```
pip install -e .
```

Our CONTRIBUTING guide is a bit out of date, there have been some changes to the requirements files that are not reflected there. We'll get those updated. Let us know if you have any further questions.

**Comment by santosh** [comment]
@kdaily okay, let me slow down a bit here.

How do I install currently checked out AWS CLI? With `pip install -e .`? Or with `python setup.py install`?

I have tried both, but this specific test is still failing.

**Comment by kdaily** [comment]
Either one will install the currently checked out AWS CLI.

We release a pip-compatible installation, so using pip is for convenience. Using 'editable' (`-e`) mode via pip means you can make code changes and then do not need to install again.

I tested both ways to be sure, and tests passed. I would confirm that you've installed everything into the same virtual environment and that you're using the correct `python` path to do so (`which python` will confirm that you're running the one for your virtual environment).

Just to clarify, I did the same as you:

1. Created a virtual environment with `venv` and activated it.
2. Ran `pip install -r requirements.txt -r requirements-docs.txt -r requirements-dev.txt`
3. Ran `pip install -e .` while in the directory containing the checked out AWS CLI Git repository.
4. Ran `pytest -x tests/integration/test_cli.py -k 'test_ctrl_c_does_not_print_traceback'`, and the tests pass.

**Comment by kdaily** [comment]
Quick update, though doesn't change the previous statements. The best way to install for development now is:

```
python -m pip install -r requirements.txt
python -m pip install  -r requirements-dev-lock.txt
pip install -e .
```

You might also try running without `-x`:

```
pytest tests/integration/test_cli.py -k 'test_ctrl_c_does_not_print_traceback'
```

**Comment by santosh** [comment]
Test still fails for me.

```
ec2-user at ip-10-2-1-250 in /efs/repos/oss/aws-cli (develop)
$ python3 -m venv .venv

ec2-user at ip-10-2-1-250 in /efs/repos/oss/aws-cli (develop)
$ . .venv/bin/activate

(.venv) ec2-user at ip-10-2-1-250 in /efs/repos/oss/aws-cli (develop)
$ python -m pip install -r requirements.txt
Obtaining botocore from git+https://github.com/boto/botocore.git@develop#egg=botocore (from -r requirements.txt (line 4))
  Cloning https://github.com/boto/botocore.git (to revision develop) to ./.venv/src/botocore
  Running command git clone -q https://github.com/boto/botocore.git /efs/repos/oss/aws-cli/.venv/src/botocore
  Installing build dependencies ... done
[...output skipped...]
Installing collected packages: jmespath, urllib3, six, python-dateutil, botocore, s3transfer
  Running setup.py develop for botocore
  Running setup.py develop for s3transfer
Successfully installed botocore jmespath-0.10.0 python-dateutil-2.8.2 s3transfer six-1.16.0 urllib3-1.26.7
WARNING: You are using pip version 20.1.1; however, version 21.3.1 is available.
You should consider upgrading via the '/efs/repos/oss/aws-cli/.venv/bin/python -m pip install --upgrade pip' command.

(.venv) ec2-user at ip-10-2-1-250 in /efs/repos/oss/aws-cli (develop)
$ python -m pip install  -r requirements-dev-lock.txt
Collecting atomicwrites==1.4.0
  Using cached atomicwrites-1.4.0-py2.py3-none-any.whl (6.8 kB)
[...output skipped...]
Installing collected packages: atomicwrites, attrs, colorama, coverage, typing-extensions, zipp, importlib-metadata, iniconfig, nose, pyparsing, packaging, pluggy, py, toml, pytest, pytest-cov, wheel
Successfully installed atomicwrites-1.4.0 attrs-21.2.0 colorama-0.4.4 coverage-5.5 importlib-metadata-4.8.1 iniconfig-1.1.1 nose-1.3.7 packaging-21.0 pluggy-1.0.0 py-1.10.0 pyparsing-2.4.7 pytest-6.2.5 pytest-cov-2.12.1 toml-0.10.2 typing-extensions-3.10.0.2 wheel-0.37.0 zipp-3.5.0
WARNING: You are using pip version 20.1.1; however, version 21.3.1 is available.
You should consider upgrading via the '/efs/repos/oss/aws-cli/.venv/bin/python -m pip install --upgrade pip' command.

(.venv) ec2-user at ip-10-2-1-250 in /efs/repos/oss/aws-cli (develop)
$ pip install -e .
Obtaining file:///efs/repos/oss/aws-cli
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: botocore==1.23.21 in ./.venv/src/botocore (from awscli==1.22.21) (1.23.21)
Requirement already satisfied: s3transfer<0.6.0,>=0.5.0 in ./.venv/src/s3transfer (from awscli==1.22.21) (0.5.0)
[...output skipped...]
Successfully installed PyYAML-5.4.1 awscli colorama-0.4.3 docutils-0.15.2 pyasn1-0.4.8 rsa-4.7.2
WARNING: You are using pip version 20.1.1; however, version 21.3.1 is available.
You should consider upgrading via the '/efs/repos/oss/aws-cli/.venv/bin/python3 -m pip install --upgrade pip' command.

(.venv) ec2-user at ip-10-2-1-250 in /efs/repos/oss/aws-cli (develop)
$ pytest tests/integration/test_cli.py -k 'test_ctrl_c_does_not_print_traceback'
=================================================================================== test session starts ====================================================================================
platform linux -- Python 3.7.10, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /efs/repos/oss/aws-cli, configfile: pyproject.toml
plugins: cov-2.12.1
collected 43 items / 42 deselected / 1 selected

tests/integration/test_cli.py F                                                                                                                                                      [100%]

========================================================================================= FAILURES =========================================================================================
____________________________________________________________ TestBasicCommandFunctionality.test_ctrl_c_does_not_print_traceback ____________________________________________________________

self = <tests.integration.test_cli.TestBasicCommandFunctionality testMethod=test_ctrl_c_does_not_print_traceback>

    @skip_if_windows('Ctrl-C not supported on windows.')
    def test_ctrl_c_does_not_print_traceback(self):
        # Relying on the fact that this generally takes
        # more than 1 second to complete.
        process = aws('ec2 describe-images', wait_for_finish=False)
        time.sleep(1)
        process.send_signal(signal.SIGINT)
        stdout, stderr = process.communicate()
        self.assertNotIn(b'Traceback', stdout)
>       self.assertNotIn(b'Traceback', stderr)
E       AssertionError: b'Traceback' unexpectedly found in b'Traceback (most recent call last):\n  File "/efs/repos/oss/aws-cli/.venv/bin/aws", line 7, in <module>\n    exec(compile(f.read(), __file__, \'exec\'))\n  File "/efs/repos/oss/aws-cli/bin/aws", line 27, in <module>\n    sys.exit(main())\n  File "/efs/repos/oss/aws-cli/bin/aws", line 23, in main\n    return awscli.clidriver.main()\n  File "/efs/repos/oss/aws-cli/awscli/clidriver.py", line 69, in main\n    driver = create_clidriver()\n  File "/efs/repos/oss/aws-cli/awscli/clidriver.py", line 79, in create_clidriver\n    event_hooks=session.get_component(\'event_emitter\'))\n  File "/efs/repos/oss/aws-cli/awscli/plugin.py", line 44, in load_plugins\n    modules = _import_plugins(plugin_mapping)\n  File "/efs/repos/oss/aws-cli/awscli/plugin.py", line 61, in _import_plugins\n    module = __import__(path, fromlist=[module])\n  File "/efs/repos/oss/aws-cli/awscli/handlers.py", line 27, in <module>\n    from awscli.customizations.cloudformation import initialize as cloudformation_init\n  File "/efs/repos/oss/aws-cli/awscli/customizations/cloudformation/__init__.py", line 13, in <module>\n    from awscli.customizations.cloudformation.package import PackageCommand\n  File "/efs/repos/oss/aws-cli/awscli/customizations/cloudformation/package.py", line 22, in <module>\n    from awscli.customizations.cloudformation.artifact_exporter import Template\n  File "/efs/repos/oss/aws-cli/awscli/customizations/cloudformation/artifact_exporter.py", line 27, in <module>\n    from awscli.customizations.cloudformation.yamlhelper import yaml_dump, \\\n  File "/efs/repos/oss/aws-cli/awscli/customizations/cloudformation/yamlhelper.py", line 16, in <module>\n    import yaml\n  File "/efs/repos/oss/aws-cli/.venv/lib64/python3.7/site-packages/yaml/__init__.py", line 8, in <module>\n    from .loader import *\n  File "/efs/repos/oss/aws-cli/.venv/lib64/python3.7/site-packages/yaml/loader.py", line 4, in <module>\n    from .reader import *\n  File "/efs/repos/oss/aws-cli/.venv/lib64/python3.7/site-packages/yaml/reader.py", line 45, in <module>\n    class Reader(object):\n  File "/efs/repos/oss/aws-cli/.venv/lib64/python3.7/site-packages/yaml/reader.py", line 137, in Reader\n    NON_PRINTABLE = re.compile(\'[^\\x09\\x0A\\x0D\\x20-\\x7E\\x85\\xA0-\\uD7FF\\uE000-\\uFFFD\\U00010000-\\U0010ffff]\')\n  File "/usr/lib64/python3.7/re.py", line 236, in compile\n    return _compile(pattern, flags)\n  File "/usr/lib64/python3.7/re.py", line 288, in _compile\n    p = sre_compile.compile(pattern, flags)\n  File "/usr/lib64/python3.7/sre_compile.py", line 768, in compile\n    code = _code(p, flags)\n  File "/usr/lib64/python3.7/sre_compile.py", line 607, in _code\n    _compile(code, p.data, flags)\n  File "/usr/lib64/python3.7/sre_compile.py", line 120, in _compile\n    charset, hascased = _optimize_charset(av, iscased, tolower, fixes)\n  File "/usr/lib64/python3.7/sre_compile.py", line 312, in _optimize_charset\n    charmap[i] = 1\nKeyboardInterrupt\n'

tests/integration/test_cli.py:324: AssertionError
================================================================================= short test summary info ==================================================================================
FAILED tests/integration/test_cli.py::TestBasicCommandFunctionality::test_ctrl_c_does_not_print_traceback - AssertionError: b'Traceback' unexpectedly found in b'Traceback (most recent c...
============================================================================= 1 failed, 42 deselected in 3.27s =============================================================================
```

**Comment by kdaily** [comment]
I'm still not able to reproduce. I thought it might be something strange due to the way you make the virtual environment inside the AWS CLI repository directory, but I tried it that way too and it works just fine as well. 

The only thing I can possibly think of is where you have the code at. The directory you have it in is named `/efs`. Is this a mounted EFS file system? Could you try to reproduce on a local filesystem?

Here's my successful attempt on an Amazon Linux EC2:

```
[ec2-user@ip-172-31-13-0 ~]$ uname -a
Linux ip-172-31-13-0.us-west-2.compute.internal 4.14.232-177.418.amzn2.x86_64 #1 SMP Tue Jun 15 20:57:50 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

[ec2-user@ip-172-31-13-0 aws-cli]$ python3 -m venv .venv
[ec2-user@ip-172-31-13-0 aws-cli]$ source .venv/bin/activate
(.venv) [ec2-user@ip-172-31-13-0 aws-cli]$ python -m pip install -r requirements.txt
Obtaining botocore from git+https://github.com/boto/botocore.git@develop#egg=botocore (from -r requirements.txt (line 4))
  Cloning https://github.com/boto/botocore.git (to revision develop) to ./.venv/src/botocore
  Running command git clone -q https://github.com/boto/botocore.git /home/ec2-user/aws-cli/.venv/src/botocore
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Obtaining s3transfer from git+https://github.com/boto/s3transfer.git@develop#egg=s3transfer (from -r requirements.txt (line 5))
  Cloning https://github.com/boto/s3transfer.git (to revision develop) to ./.venv/src/s3transfer
  Running command git clone -q https://github.com/boto/s3transfer.git /home/ec2-user/aws-cli/.venv/src/s3transfer
Collecting jmespath<1.0.0,>=0.7.1
  Using cached jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting python-dateutil<3.0.0,>=2.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting urllib3<1.27,>=1.25.4
  Using cached urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: jmespath, six, python-dateutil, urllib3, botocore, s3transfer
  Running setup.py develop for botocore
  Running setup.py develop for s3transfer
Successfully installed botocore jmespath-0.10.0 python-dateutil-2.8.2 s3transfer six-1.16.0 urllib3-1.26.7
WARNING: You are using pip version 20.1.1; however, version 21.3.1 is available.
You should consider upgrading via the '/home/ec2-user/aws-cli/.venv/bin/python -m pip install --upgrade pip' command.

(.venv) [ec2-user@ip-172-31-13-0 aws-cli]$ python -m pip install  -r requirements-dev-lock.txt
Collecting atomicwrites==1.4.0
  Using cached atomicwrites-1.4.0-py2.py3-none-any.whl (6.8 kB)
Collecting attrs==21.2.0
  Using cached attrs-21.2.0-py2.py3-none-any.whl (53 kB)
Collecting colorama==0.4.4
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting coverage==5.5
  Using cached coverage-5.5-cp37-cp37m-manylinux2010_x86_64.whl (242 kB)
Collecting importlib-metadata==4.8.1
  Using cached importlib_metadata-4.8.1-py3-none-any.whl (17 kB)
Collecting iniconfig==1.1.1
  Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting nose==1.3.7
  Using cached nose-1.3.7-py3-none-any.whl (154 kB)
Collecting packaging==21.0
  Using cached packaging-21.0-py3-none-any.whl (40 kB)
Collecting pluggy==1.0.0
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting py==1.10.0
  Using cached py-1.10.0-py2.py3-none-any.whl (97 kB)
Collecting pyparsing==2.4.7
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting pytest-cov==2.12.1
  Using cached pytest_cov-2.12.1-py2.py3-none-any.whl (20 kB)
Collecting pytest==6.2.5
  Using cached pytest-6.2.5-py3-none-any.whl (280 kB)
Collecting toml==0.10.2
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting typing-extensions==3.10.0.2
  Using cached typing_extensions-3.10.0.2-py3-none-any.whl (26 kB)
Collecting wheel==0.37.0
  Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB)
Collecting zipp==3.5.0
  Using cached zipp-3.5.0-py3-none-any.whl (5.7 kB)
Installing collected packages: atomicwrites, attrs, colorama, coverage, zipp, typing-extensions, importlib-metadata, iniconfig, nose, pyparsing, packaging, pluggy, py, toml, pytest, pytest-cov, wheel
Successfully installed atomicwrites-1.4.0 attrs-21.2.0 colorama-0.4.4 coverage-5.5 importlib-metadata-4.8.1 iniconfig-1.1.1 nose-1.3.7 packaging-21.0 pluggy-1.0.0 py-1.10.0 pyparsing-2.4.7 pytest-6.2.5 pytest-cov-2.12.1 toml-0.10.2 typing-extensions-3.10.0.2 wheel-0.37.0 zipp-3.5.0
WARNING: You are using pip version 20.1.1; however, version 21.3.1 is available.
You should consider upgrading via the '/home/ec2-user/aws-cli/.venv/bin/python -m pip install --upgrade pip' command.

(.venv) [ec2-user@ip-172-31-13-0 aws-cli]$ pip install -e .
Obtaining file:///home/ec2-user/aws-cli
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting docutils<0.16,>=0.10
  Using cached docutils-0.15.2-py3-none-any.whl (547 kB)
Collecting PyYAML<5.5,>=3.10
  Using cached PyYAML-5.4.1-cp37-cp37m-manylinux1_x86_64.whl (636 kB)
Requirement already satisfied: s3transfer<0.6.0,>=0.5.0 in ./.venv/src/s3transfer (from awscli==1.22.21) (0.5.0)
Collecting botocore==1.23.21
  Downloading botocore-1.23.21-py3-none-any.whl (8.4 MB)
     |████████████████████████████████| 8.4 MB 8.6 MB/s
Collecting colorama<0.4.4,>=0.2.5
  Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Collecting rsa<4.8,>=3.1.2
  Using cached rsa-4.7.2-py3-none-any.whl (34 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in ./.venv/lib/python3.7/site-packages (from botocore==1.23.21->awscli==1.22.21) (2.8.2)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in ./.venv/lib/python3.7/site-packages (from botocore==1.23.21->awscli==1.22.21) (0.10.0)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in ./.venv/lib/python3.7/site-packages (from botocore==1.23.21->awscli==1.22.21) (1.26.7)
Collecting pyasn1>=0.1.3
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.7/site-packages (from python-dateutil<3.0.0,>=2.1->botocore==1.23.21->awscli==1.22.21) (1.16.0)
Installing collected packages: docutils, PyYAML, botocore, colorama, pyasn1, rsa, awscli
  Attempting uninstall: botocore
    Found existing installation: botocore 1.23.23
    Uninstalling botocore-1.23.23:
      Successfully uninstalled botocore-1.23.23
  Attempting uninstall: colorama
    Found existing installation: colorama 0.4.4
    Uninstalling colorama-0.4.4:
      Successfully uninstalled colorama-0.4.4
  Running setup.py develop for awscli
Successfully installed PyYAML-5.4.1 awscli botocore-1.23.21 colorama-0.4.3 docutils-0.15.2 pyasn1-0.4.8 rsa-4.7.2
WARNING: You are using pip version 20.1.1; however, version 21.3.1 is available.
You should consider upgrading via the '/home/ec2-user/aws-cli/.venv/bin/python3 -m pip install --upgrade pip' command.

(.venv) [ec2-user@ip-172-31-13-0 aws-cli]$ pytest tests/integration/test_cli.py -k 'test_ctrl_c_does_not_print_traceback'
====================================================== test session starts ======================================================
platform linux -- Python 3.7.10, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /home/ec2-user/aws-cli, configfile: pyproject.toml
plugins: cov-2.12.1
collecting ...
collected 43 items / 42 deselected / 1 selected

tests/integration/test_cli.py .                                                                                           [100%]

=============================================== 1 passed, 42 deselected in 1.29s ================================================
```

**Comment by santosh** [comment]
> The only thing I can possibly think of is where you have the code at. The directory you have it in is named /efs. Is this a mounted EFS file system? Could you try to reproduce on a local filesystem?

@kdaily yeah, you are right. 

I don't know what makes this test fail on EFS. 
Not sure where the problem is, pytest? python?

Can this test be modified to pass on EFS? Because I have my dev environment on EC2. And I store data on EFS. I do that because I prefer to terminate the instances when my EBS is filling up.

**Comment by kdaily** [comment]
Thanks for confirming! I'm going to mark this as a bug for now and see if I can learn the underlying cause.

Just to clarify, which parts of the whole test suite did you run? We have functional, unit, and integration tests. I'm surprised this is the only one that fails!

**Comment by santosh** [comment]
Let me come to you with the test results.

**Comment by kdaily** [comment]
Adding reformatted traceback for debugging purposes:

```
AssertionError: b'Traceback' unexpectedly found in b'Traceback (most recent call last):
  File "/efs/repos/oss/aws-cli/.venv/bin/aws", line 7, in <module>
    exec(compile(f.read(), __file__, \'exec\'))
  File "/efs/repos/oss/aws-cli/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/efs/repos/oss/aws-cli/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/efs/repos/oss/aws-cli/awscli/clidriver.py", line 69, in main
    driver = create_clidriver()
  File "/efs/repos/oss/aws-cli/awscli/clidriver.py", line 79, in create_clidriver
    event_hooks=session.get_component(\'event_emitter\'))
  File "/efs/repos/oss/aws-cli/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/efs/repos/oss/aws-cli/awscli/plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "/efs/repos/oss/aws-cli/awscli/handlers.py", line 27, in <module>
    from awscli.customizations.cloudformation import initialize as cloudformation_init
  File "/efs/repos/oss/aws-cli/awscli/customizations/cloudformation/__init__.py", line 13, in <module>
    from awscli.customizations.cloudformation.package import PackageCommand
  File "/efs/repos/oss/aws-cli/awscli/customizations/cloudformation/package.py", line 22, in <module>
    from awscli.customizations.cloudformation.artifact_exporter import Template
  File "/efs/repos/oss/aws-cli/awscli/customizations/cloudformation/artifact_exporter.py", line 27, in <module>
    from awscli.customizations.cloudformation.yamlhelper import yaml_dump, \\
  File "/efs/repos/oss/aws-cli/awscli/customizations/cloudformation/yamlhelper.py", line 16, in <module>
    import yaml
  File "/efs/repos/oss/aws-cli/.venv/lib64/python3.7/site-packages/yaml/__init__.py", line 8, in <module>
    from .loader import *
  File "/efs/repos/oss/aws-cli/.venv/lib64/python3.7/site-packages/yaml/loader.py", line 4, in <module>
    from .reader import *
  File "/efs/repos/oss/aws-cli/.venv/lib64/python3.7/site-packages/yaml/reader.py", line 45, in <module>
    class Reader(object):
  File "/efs/repos/oss/aws-cli/.venv/lib64/python3.7/site-packages/yaml/reader.py", line 137, in Reader
    NON_PRINTABLE = re.compile(\'[^\\x09\\x0A\\x0D\\x20-\\x7E\\x85\\xA0-\\uD7FF\\uE000-\\uFFFD\\U00010000-\\U0010ffff]\')
  File "/usr/lib64/python3.7/re.py", line 236, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python3.7/re.py", line 288, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib64/python3.7/sre_compile.py", line 768, in compile
    code = _code(p, flags)
  File "/usr/lib64/python3.7/sre_compile.py", line 607, in _code
    _compile(code, p.data, flags)
  File "/usr/lib64/python3.7/sre_compile.py", line 120, in _compile
    charset, hascased = _optimize_charset(av, iscased, tolower, fixes)
  File "/usr/lib64/python3.7/sre_compile.py", line 312, in _optimize_charset
    charmap[i] = 1
KeyboardInterrupt
'```

**Comment by kdaily** [comment]
It's an odd place for this to fail, that's why I'm interested in if other tests fail. The traceback shows that this doesn't fail in the test, but while the package is still loading. The speculation is there may be some latency in reading from EFS. We wouldn't likely change a specific test because of this unless we can identify an underlying cause.

**Comment by santosh** [comment]
Okay, so functional and unit tests passes (with deprecation warning).

`test_ctrl_c_does_not_print_traceback` is the only test which is meaningful here. 

Other test which errors out for me is the s3 tests, which errors because of timeout. 

S3 errors are like this: 

     botocore.exceptions.WaiterError: Waiter BucketExists failed: Max attempts exceeded. Previously accepted state: Matched expected HTTP status code: 404

**Comment by santosh** [comment]
Closing this issue under a cleanup campaign.
