### ISSUE TITLE
Configure docker image for aws stepfunctions local.

### ISSUE THREAD

**Issue by austinben** [aws/aws-cli#6615]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [ ] CLI : passing arguments or cli configurations.
- [x] Other/Not sure.

**Platform/OS/Hardware/Device**
MacOS Big Sur 11.5.2

**Describe the question**
I am trying to configure a local execution of a step function composed of multiple Lambda functions. I have done the following so far:

1. Started step functions local via `docker run -p 8083:8083 --env-file stepfunctions-credentials.txt amazon/aws-stepfunctions-local`
2. Started AWS SAM CLI local via `sam local start-lambda -t template.json` to reference the cloudformation template.
3. Create a state machine via `aws stepfunctions --endpoint http://localhost:8083 create-state-machine --definition "[my definition]" --name localpipeline --role-arn "arn:aws:iam::012345678901:role/DummyRole"`
4. Started the state machine via `aws stepfunctions --endpoint http://localhost:8083 start-execution --state-machine arn:aws:states:us-east-1:094063233571:stateMachine:localpipeline --input "[my test.json event]"`

First three steps are successful, but the issue arrises with step 4. The docker image is built, and the innvocation is attempted to start (`START RequestId: a7ec8d1b-27b2-4295-ace4-1e28cb1eff67 Version: $LATEST`), but immediately fails due to a missing package.

`Unable to import module 'index': No module named 'packaging'`.

Previously, when testing individual lambda functions with the AWS SAM CLI, I was able to change the definition of the function from `"Type": "AWS::Lambda::Function"` to  `"Type": "AWS::Serverless::Function"`, remove the "Code" property, and provide a dockercontext, dockfile path, and dockertag under the `Metadata` field for that function. With this, I was able to configure the image via the Dockerfile, copying the lambda handler code, and related modules, along with installing dependencies from a requirements.txt via `pip install`. This setup uses the `amazon/aws-lambda-python:3.8` base image.

It seems as there is no option for this for local stepfunctions, or atleast it is not documented anywhere in https://docs.aws.amazon.com/step-functions/latest/dg/sfn-local-lambda.html#create-local-statemachine or related pages such as https://docs.aws.amazon.com/step-functions/latest/dg/sfn-local-config-options.html. Only the configuration of the environment variables is documented. 

Is it possible to achieve this functionality? It seemed to be the only way to get the AWS SAM CLI to work with `sam build` and `sam local invoke` previously, due to the Lambda functions in question requiring many local python modules, along with a considerable list of dependencies in a `requirements.txt`. 

**Logs/output**

Logs for `sam local start lambda`:

```
2021-12-13 15:42:55  * Running on http://127.0.0.1:3001/ (Press CTRL+C to quit)
2021-12-13 15:43:32,226 | Found one Lambda function with name 'PreprocessingLambdaFunction'
2021-12-13 15:43:32,226 | Invoking index.lambda_handler (python3.6)
2021-12-13 15:43:32,226 | Environment variables overrides data is standard format
2021-12-13 15:43:32,226 | Loading AWS credentials from session with profile 'None'
2021-12-13 15:43:32,232 | Resolving code path. Cwd=/Users/benaustin/Documents/marinelabs.nosync/ml-ows-cloud/infrastructure/lambdas/processor/pipeline, CodeUri=/Users/benaustin/Documents/marinelabs.nosync/ml-ows-cloud/infrastructure/lambdas/processor/pipeline
2021-12-13 15:43:32,232 | Resolved absolute path to code is /Users/benaustin/Documents/marinelabs.nosync/ml-ows-cloud/infrastructure/lambdas/processor/pipeline
2021-12-13 15:43:32,232 | Code /Users/benaustin/Documents/marinelabs.nosync/ml-ows-cloud/infrastructure/lambdas/processor/pipeline is not a zip/jar file
2021-12-13 15:43:32,235 | Image was not found.
2021-12-13 15:43:32,235 | Removing rapid images for repo public.ecr.aws/sam/emulation-python3.6
Building image..........................................................................................................................................................................................................................................................................................................................................................................................................
2021-12-13 15:44:08,305 | Skip pulling image and use local one: public.ecr.aws/sam/emulation-python3.6:rapid-1.31.0.

2021-12-13 15:44:08,305 | Mounting /Users/benaustin/Documents/marinelabs.nosync/ml-ows-cloud/infrastructure/lambdas/processor/pipeline as /var/task:ro,delegated inside runtime container
2021-12-13 15:44:08,563 | Starting a timer for 300 seconds for function 'PreprocessingLambdaFunction'
START RequestId: a7ec8d1b-27b2-4295-ace4-1e28cb1eff67 Version: $LATEST
Unable to import module 'index': No module named 'packaging'

time="2021-12-13T23:44:09.288" level=panic msg="ReplyStream not available"
2021/12/13 23:44:09 http: panic serving 127.0.0.1:45288: &{0xc0000f4000 map[] 2021-12-13 23:44:09.288271 +0000 UTC m=+0.694748001 panic <nil> ReplyStream not available <nil> <nil> }
goroutine 7 [running]:
net/http.(*conn).serve.func1(0xc00007a000)
	/usr/local/go/src/net/http/server.go:1800 +0x139
panic(0x866640, 0xc000292070)
	/usr/local/go/src/runtime/panic.go:975 +0x3e3
github.com/sirupsen/logrus.Entry.log(0xc0000f4000, 0xc00001e270, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x335
github.com/sirupsen/logrus.(*Entry).Log(0xc000292000, 0xc000000000, 0xc000207588, 0x1, 0x1)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xeb
github.com/sirupsen/logrus.(*Logger).Log(0xc0000f4000, 0xc000000000, 0xc000207588, 0x1, 0x1)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:193 +0x7d
github.com/sirupsen/logrus.(*Logger).Panic(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:234
github.com/sirupsen/logrus.Panic(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/exported.go:129
go.amzn.com/lambda/rapi/rendering.RenderInteropError(0x9097c0, 0xc000286000, 0xc000282200, 0x902b60, 0xc0000500c0)
	/LambdaRuntimeLocal/lambda/rapi/rendering/rendering.go:292 +0x9a
go.amzn.com/lambda/rapi/handler.(*initErrorHandler).ServeHTTP(0xc00011e0a0, 0x9097c0, 0xc000286000, 0xc000282200)
	/LambdaRuntimeLocal/lambda/rapi/handler/initerror.go:52 +0x519
net/http.HandlerFunc.ServeHTTP(0xc00010e380, 0x9097c0, 0xc000286000, 0xc000282200)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*Mux).routeHTTP(0xc00010c120, 0x9097c0, 0xc000286000, 0xc000282200)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x278
net/http.HandlerFunc.ServeHTTP(0xc00011e030, 0x9097c0, 0xc000286000, 0xc000282200)
	/usr/local/go/src/net/http/server.go:2041 +0x44
go.amzn.com/lambda/rapi/middleware.RuntimeReleaseMiddleware.func1.1(0x9097c0, 0xc000286000, 0xc000282200)
	/LambdaRuntimeLocal/lambda/rapi/middleware/middleware.go:100 +0xea
net/http.HandlerFunc.ServeHTTP(0xc00010e180, 0x9097c0, 0xc000286000, 0xc000282200)
	/usr/local/go/src/net/http/server.go:2041 +0x44
go.amzn.com/lambda/rapi/middleware.AccessLogMiddleware.func1.1(0x9097c0, 0xc000286000, 0xc000282200)
	/LambdaRuntimeLocal/lambda/rapi/middleware/middleware.go:77 +0x170
net/http.HandlerFunc.ServeHTTP(0xc00010e1a0, 0x9097c0, 0xc000286000, 0xc000282200)
	/usr/local/go/src/net/http/server.go:2041 +0x44
go.amzn.com/lambda/rapi/middleware.AppCtxMiddleware.func1.1(0x9097c0, 0xc000286000, 0xc000282100)
	/LambdaRuntimeLocal/lambda/rapi/middleware/middleware.go:66 +0x77
net/http.HandlerFunc.ServeHTTP(0xc00011c2d0, 0x9097c0, 0xc000286000, 0xc000282100)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00010c120, 0x9097c0, 0xc000286000, 0xc000282100)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:70 +0x513
github.com/go-chi/chi.(*Mux).Mount.func1(0x9097c0, 0xc000286000, 0xc000282100)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:298 +0x118
net/http.HandlerFunc.ServeHTTP(0xc00010e3e0, 0x9097c0, 0xc000286000, 0xc000282100)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*Mux).routeHTTP(0xc00010c0c0, 0x9097c0, 0xc000286000, 0xc000282100)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x278
net/http.HandlerFunc.ServeHTTP(0xc00011e0c0, 0x9097c0, 0xc000286000, 0xc000282100)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00010c0c0, 0x9097c0, 0xc000286000, 0xc000282000)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:86 +0x2b2
net/http.serverHandler.ServeHTTP(0xc00012c000, 0x9097c0, 0xc000286000, 0xc000282000)
	/usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc00007a000, 0x90a800, 0xc00007e000)
	/usr/local/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2962 +0x35c
Traceback (most recent call last):
  File "/var/runtime/awslambda/bootstrap.py", line 620, in <module>
    main()
  File "/var/runtime/awslambda/bootstrap.py", line 595, in main
    lambda_runtime.report_done(invokeid, None, None, 0)
```

Logs for `docker run -p 8083:8083 --env-file stepfunctions-credentials.txt amazon/aws-stepfunctions-local`: 

```
Step Functions Local
Version: 1.7.9
Build: 2021-06-24
2021-12-13 23:43:00.345: Configure [AWS_ACCOUNT_ID] to [094063233571]
2021-12-13 23:43:00.345: Configure [AWS_DEFAULT_REGION] to [us-east-1]
2021-12-13 23:43:00.345: Configure [LAMBDA_ENDPOINT] to [http://host.docker.internal:3001/]
2021-12-13 23:43:00.350: Loaded credentials from environment
2021-12-13 23:43:00.350: Starting server on port 8083 with account 094063233571, region us-east-1
Dec 13, 2021 11:43:00 PM com.amazonaws.internal.DefaultServiceEndpointBuilder getServiceEndpoint
INFO: {databrew, us-east-1} was not found in region metadata, trying to construct an endpoint using the standard pattern for this region: 'databrew.us-east-1.amazonaws.com'.
2021-12-13 23:43:05.219: CreateStateMachine => {"requestClientOptions":{"readLimit":131073,"skipAppendUriPath":false},"requestMetricCollector":null,"customRequestHeaders":null,"customQueryParameters":null,"cloneSource":null,"sdkRequestTimeout":null,"sdkClientExecutionTimeout":null,"name":"localpipeline","definition":"[my def]}","roleArn":"arn:aws:iam::012345678901:role/DummyRole","type":null,"loggingConfiguration":null,"tags":null,"tracingConfiguration":null,"requestCredentials":null,"requestCredentialsProvider":null,"generalProgressListener":{"syncCallSafe":true},"readLimit":131073,"cloneRoot":null}
2021-12-13 23:43:05.251: [200] CreateStateMachine <= {"sdkResponseMetadata":null,"sdkHttpMetadata":null,"stateMachineArn":"arn:aws:states:us-east-1:094063233571:stateMachine:localpipeline","creationDate":1639438985246}
2021-12-13 23:43:12.401: CreateStateMachine => {"requestClientOptions":{"readLimit":131073,"skipAppendUriPath":false},"requestMetricCollector":null,"customRequestHeaders":null,"customQueryParameters":null,"cloneSource":null,"sdkRequestTimeout":null,"sdkClientExecutionTimeout":null,"name":"localpipeline","definition":"[mydef]}","roleArn":"arn:aws:iam::012345678901:role/DummyRole","type":null,"loggingConfiguration":null,"tags":null,"tracingConfiguration":null,"requestCredentials":null,"requestCredentialsProvider":null,"generalProgressListener":{"syncCallSafe":true},"readLimit":131073,"cloneRoot":null}
2021-12-13 23:43:12.410: [200] CreateStateMachine <= {"sdkResponseMetadata":null,"sdkHttpMetadata":null,"stateMachineArn":"arn:aws:states:us-east-1:094063233571:stateMachine:localpipeline","creationDate":1639438985246}
2021-12-13 23:43:32.094: StartExecution => {"requestClientOptions":{"readLimit":131073,"skipAppendUriPath":false},"requestMetricCollector":null,"customRequestHeaders":null,"customQueryParameters":null,"cloneSource":null,"sdkRequestTimeout":null,"sdkClientExecutionTimeout":null,"stateMachineArn":"arn:aws:states:us-east-1:094063233571:stateMachine:localpipeline","name":null,"input":"[my input]","traceHeader":null,"requestCredentials":null,"requestCredentialsProvider":null,"generalProgressListener":{"syncCallSafe":true},"readLimit":131073,"cloneRoot":null}
2021-12-13 23:43:32.136: [200] StartExecution <= {"sdkResponseMetadata":null,"sdkHttpMetadata":null,"executionArn":"arn:aws:states:us-east-1:094063233571:execution:localpipeline:f6ff9ef3-36c1-4891-862b-cdb35cda8efc","startDate":1639439012128}
2021-12-13 23:43:32.144: arn:aws:states:us-east-1:094063233571:execution:localpipeline:f6ff9ef3-36c1-4891-862b-cdb35cda8efc : {"Type":"ExecutionStarted","PreviousEventId":0,"ExecutionStartedEventDetails":{"Input":"{[my input]}","RoleArn":"arn:aws:iam::012345678901:role/DummyRole"}}
2021-12-13 23:43:32.146: arn:aws:states:us-east-1:094063233571:execution:localpipeline:f6ff9ef3-36c1-4891-862b-cdb35cda8efc : {"Type":"TaskStateEntered","PreviousEventId":0,"StateEnteredEventDetails":{"Name":"Preprocessing","Input":"{[my input]}
2021-12-13 23:43:32.151: arn:aws:states:us-east-1:094063233571:execution:localpipeline:f6ff9ef3-36c1-4891-862b-cdb35cda8efc : {"Type":"LambdaFunctionScheduled","PreviousEventId":2,"LambdaFunctionScheduledEventDetails":{"Resource":"arn:aws:lambda:us-east-1:094063233571:function:PreprocessingLambdaFunction","Input":"{[my input]}
2021-12-13 23:43:32.151: arn:aws:states:us-east-1:094063233571:execution:localpipeline:f6ff9ef3-36c1-4891-862b-cdb35cda8efc : {"Type":"LambdaFunctionStarted","PreviousEventId":3}
2021-12-13 23:44:09.509: arn:aws:states:us-east-1:094063233571:execution:localpipeline:f6ff9ef3-36c1-4891-862b-cdb35cda8efc : {"Type":"LambdaFunctionSucceeded","PreviousEventId":4,"LambdaFunctionSucceededEventDetails":{"Output":""}}
2021-12-13 23:44:09.513: arn:aws:states:us-east-1:094063233571:execution:localpipeline:f6ff9ef3-36c1-4891-862b-cdb35cda8efc : {"Type":"TaskStateExited","PreviousEventId":5,"StateExitedEventDetails":{"Name":"Preprocessing","Output":"[output] \"preprocessing_step_output\":null}"}}
2021-12-13 23:44:09.514: arn:aws:states:us-east-1:094063233571:execution:localpipeline:f6ff9ef3-36c1-4891-862b-cdb35cda8efc : {"Type":"ChoiceStateEntered","PreviousEventId":6,"StateEnteredEventDetails":{"Name":"Heartbeat/Alert Only?","Input":"[my input] ,\"preprocessing_step_output\":null}"}}
2021-12-13 23:44:09.524: arn:aws:states:us-east-1:094063233571:execution:localpipeline:f6ff9ef3-36c1-4891-862b-cdb35cda8efc : {"Type":"ExecutionFailed","PreviousEventId":7,"ExecutionFailedEventDetails":{"Error":"States.Runtime","Cause":"An error occurred while executing the state 'Heartbeat/Alert Only?' (entered at the event id #7). Invalid path '$.preprocessing_step_output.heartbeat_or_alert_only': The choice state's condition path references an invalid value."}}

```

**Comment by tim-finnigan** [comment]
Hi @austinben I recommend creating a new issue in the AWS SAM CLI repository if you’re still experiencing this. I’m going to go ahead and close this issue but please let us know if there’s anything with the AWS CLI that we can help with!
