### ISSUE TITLE
s3api put-bucket-notification-configuration EventBridgeConfiguration should be allowed per doc

### ISSUE THREAD

**Issue by owlwalks** [aws/aws-cli#6616]
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
`EventBridgeConfiguration` in `s3api put-bucket-notification-configuration` is marked invalid

**SDK version number**
aws-cli/2.1.36 Python/3.8.8 Linux/4.19.0-18-amd64 exe/x86_64.debian.10 prompt/off

**Platform/OS/Hardware/Device**
Linux/Debian

**To Reproduce (observed behavior)**
```
cat ./config
{
  "EventBridgeConfiguration": {}
}
aws s3api put-bucket-notification-configuration --bucket my-bucket --notification-configuration file://config

Parameter validation failed:
Unknown parameter in NotificationConfiguration: "EventBridgeConfiguration", must be one of: TopicConfigurations, QueueConfigurations, LambdaFunctionConfigurations
```

**Expected behavior**
EventBridgeConfiguration should be allowed per documentation: https://docs.aws.amazon.com/cli/latest/reference/s3api/put-bucket-notification-configuration.html 

**Logs/output**
```
2021-12-16 09:41:17,668 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.36 Python/3.8.8 Linux/4.19.0-18-amd64 exe/x86_64.debian.10
2021-12-16 09:41:17,668 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--profile', 'REDACTED', 's3api', 'put-bucket-notification-configuration', '--bucket', 'REDACTED', '--notification-configuration', 'file://config', '--debug']
2021-12-16 09:41:17,678 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x7fef568445e0>
2021-12-16 09:41:17,678 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x7fef569633a0>
2021-12-16 09:41:17,678 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2021-12-16 09:41:17,678 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7fef56a09d30>
2021-12-16 09:41:17,678 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7fef56a0fb80>
2021-12-16 09:41:17,679 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x7fef56803040>
2021-12-16 09:41:17,679 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x7fef569311f0>
2021-12-16 09:41:17,679 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2021-12-16 09:41:17,679 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x7fef567fb280>
2021-12-16 09:41:17,680 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.1.36/dist/awscli/data/cli.json
2021-12-16 09:41:17,683 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x7fef5685b430>
2021-12-16 09:41:17,684 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x7fef5685bf70>
2021-12-16 09:41:17,684 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x7fef5685bee0>
2021-12-16 09:41:17,684 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x7fef568600d0>
2021-12-16 09:41:17,684 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x7fef56860040>
2021-12-16 09:41:17,684 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x7fef56715bc0>
2021-12-16 09:41:17,684 - MainThread - botocore.session - DEBUG - Setting config variable for profile to 'REDACTED'
2021-12-16 09:41:17,684 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.36 Python/3.8.8 Linux/4.19.0-18-amd64 exe/x86_64.debian.10 prompt/off
2021-12-16 09:41:17,685 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--profile', 'REDACTED', 's3api', 'put-bucket-notification-configuration', '--bucket', 'REDACTED', '--notification-configuration', 'file://config', '--debug']
2021-12-16 09:41:17,685 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7fef56844c10>
2021-12-16 09:41:17,685 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7fef57240e50>
2021-12-16 09:41:17,686 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7fef5675baf0>
2021-12-16 09:41:17,686 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x7fef5723e310>
2021-12-16 09:41:17,686 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7fef571b19d0>
2021-12-16 09:41:17,687 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-12-16 09:41:17,689 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2021-12-16 09:41:17,689 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7fef569310d0>
2021-12-16 09:41:17,689 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7fef569621f0>
2021-12-16 09:41:17,699 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.1.36/dist/botocore/data/s3/2006-03-01/service-2.json
2021-12-16 09:41:17,716 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3api: calling handler <function add_waiters at 0x7fef567fb280>
2021-12-16 09:41:17,727 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.1.36/dist/botocore/data/s3/2006-03-01/waiters-2.json
2021-12-16 09:41:17,728 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('bucket', <awscli.arguments.CLIArgument object at 0x7fef56544ca0>), ('notification-configuration', <awscli.arguments.CLIArgument object at 0x7fef56544cd0>), ('expected-bucket-owner', <awscli.arguments.CLIArgument object at 0x7fef56544d00>)])
2021-12-16 09:41:17,728 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-bucket-notification-configuration: calling handler <function add_streaming_output_arg at 0x7fef567f61f0>
2021-12-16 09:41:17,728 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-bucket-notification-configuration: calling handler <function add_cli_input_json at 0x7fef571b5280>
2021-12-16 09:41:17,728 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-bucket-notification-configuration: calling handler <function add_cli_input_yaml at 0x7fef571b5550>
2021-12-16 09:41:17,728 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-bucket-notification-configuration: calling handler <function unify_paging_params at 0x7fef569639d0>
2021-12-16 09:41:17,737 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.1.36/dist/botocore/data/s3/2006-03-01/paginators-1.json
2021-12-16 09:41:17,737 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-bucket-notification-configuration: calling handler <function add_generate_skeleton at 0x7fef568d19d0>
2021-12-16 09:41:17,737 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.put-bucket-notification-configuration: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7fef56544b80>>
2021-12-16 09:41:17,738 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.put-bucket-notification-configuration: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7fef56544d90>>
2021-12-16 09:41:17,738 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.put-bucket-notification-configuration: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fef56544ee0>>
2021-12-16 09:41:17,739 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-bucket-notification-configuration.bucket: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fef56749160>
2021-12-16 09:41:17,739 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.s3.put-bucket-notification-configuration: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fef571ee820>
2021-12-16 09:41:17,739 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'REDACTED' for parameter "bucket": 'REDACTED'
2021-12-16 09:41:17,739 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-bucket-notification-configuration.notification-configuration: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fef56749160>
2021-12-16 09:41:17,739 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.s3.put-bucket-notification-configuration: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fef571ee820>
2021-12-16 09:41:17,739 - MainThread - awscli.argprocess - DEBUG - Param notification_configuration looks like JSON, not considered for param shorthand.
2021-12-16 09:41:17,740 - MainThread - awscli.arguments - DEBUG - Unpacked value of '{\n  "EventBridgeConfiguration": {}\n}\n' for parameter "notification_configuration": OrderedDict([('EventBridgeConfiguration', OrderedDict())])
2021-12-16 09:41:17,740 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-bucket-notification-configuration.expected-bucket-owner: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fef56749160>
2021-12-16 09:41:17,740 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-bucket-notification-configuration.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fef56749160>
2021-12-16 09:41:17,740 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-bucket-notification-configuration.cli-input-yaml: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fef56749160>
2021-12-16 09:41:17,740 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-bucket-notification-configuration.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fef56749160>
2021-12-16 09:41:17,740 - MainThread - botocore.hooks - DEBUG - Event calling-command.s3api.put-bucket-notification-configuration: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7fef56544b80>>
2021-12-16 09:41:17,740 - MainThread - botocore.hooks - DEBUG - Event calling-command.s3api.put-bucket-notification-configuration: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7fef56544d90>>
2021-12-16 09:41:17,741 - MainThread - botocore.hooks - DEBUG - Event calling-command.s3api.put-bucket-notification-configuration: calling handler <bound method GenerateCliSkeletonArgument.generate_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fef56544ee0>>
2021-12-16 09:41:17,741 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2021-12-16 09:41:17,741 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2021-12-16 09:41:17,741 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2021-12-16 09:41:17,742 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2021-12-16 09:41:17,742 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2021-12-16 09:41:17,743 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.1.36/dist/botocore/data/endpoints.json
2021-12-16 09:41:17,748 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7fef585d2c10>
2021-12-16 09:41:17,750 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7fef585fe1f0>
2021-12-16 09:41:17,750 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7fef585fff70>
2021-12-16 09:41:17,760 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2021-12-16 09:41:17,761 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.s3.PutBucketNotificationConfiguration: calling handler <function base64_decode_input_blobs at 0x7fef5675f280>
2021-12-16 09:41:17,761 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutBucketNotificationConfiguration: calling handler <function validate_bucket_name at 0x7fef585f5e50>
2021-12-16 09:41:17,762 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutBucketNotificationConfiguration: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x7fef561d3880>>
2021-12-16 09:41:17,762 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutBucketNotificationConfiguration: calling handler <bound method S3ArnParamHandler.handle_arn of <botocore.utils.S3ArnParamHandler object at 0x7fef561d3940>>
2021-12-16 09:41:17,762 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutBucketNotificationConfiguration: calling handler <function generate_idempotent_uuid at 0x7fef585f5ca0>
2021-12-16 09:41:17,762 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/clidriver.py", line 457, in main
  File "awscli/clidriver.py", line 590, in __call__
  File "awscli/clidriver.py", line 766, in __call__
  File "awscli/clidriver.py", line 897, in invoke
  File "awscli/clidriver.py", line 909, in _make_client_call
  File "botocore/client.py", line 249, in _api_call
  File "botocore/client.py", line 540, in _make_api_call
  File "botocore/client.py", line 588, in _convert_to_request_dict
  File "botocore/validate.py", line 293, in serialize_to_request
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in NotificationConfiguration: "EventBridgeConfiguration", must be one of: TopicConfigurations, QueueConfigurations, LambdaFunctionConfigurations
```

**Comment by stobrien89** [comment]
Hi @owlwalks,

Thanks for reaching out!  It looks like this option was added to the [botocore S3 model](https://github.com/boto/botocore/blob/develop/botocore/data/s3/2006-03-01/service-2.json#L6427,L6430) on 11/29/2021, meaning you'll need AWS CLI (v2) version `2.4.1` in order to use it.  Hope this helps!
