### ISSUE TITLE
An error occurred (NoSuchResourceException) when calling the GetServiceQuota operation:

### ISSUE THREAD

**Issue by aakifshaikh** [aws/aws-cli#6629]
Confirm by changing [ ] to [x] below:
- [X ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [ ] CLI : passing arguments or cli configurations.
- [ X] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?  Mac OS Big Sur v 11.6.2

**Describe the question**
Running the command:  aws service-quotas get-service-quota --service-code events --quota-code L-244521F2
Response: An error occurred (NoSuchResourceException) when calling the GetServiceQuota operation:
AWS CLI Version: 2.4.7 Python 3.8.8

I am trying to get the quota value for specific quota-code L-244521F2 (CW Event Rule Numbers)
When I run other commands it works fine: aws service-quotas get-service-quota --service-code ec2 --quota-code L-1216C47A

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by kdaily** [comment]
Hi @aakifshaikh,

Thanks for your post and sorry to hear you're having an issue. Can you:

1. See this service code in the [AWS Console](https://docs.aws.amazon.com/servicequotas/latest/userguide/gs-request-quota.html)?
2. Tell me which region you're using with your CLI command? You can also provide the full debug output, redacted of any sensitive information, by adding the `--debug` flag to your command.

Thanks!

**Comment by aakifshaikh** [comment]
@kdaily - Thank you for your response. 1) I know how to navigate using the console. I have been doing this most of the time. We many several numbers of accounts. So I was thinking to write a script that can pull the service quota number (for cloudwatch event rule) and then as we see the threshold reaching we can submit the request to increase the quota. 
I tried this command in multiple accounts (us-east-1 region). First I thought its something related to that specific account so I tried in another account but was still unsuccessful. Here is the result of the command that I ran using the --debug flag.

`2021-12-28 17:42:05,224 - MainThread - botocore.httpsession - DEBUG - Certificate path: /usr/local/aws-cli/awscli/botocore/cacert.pem
2021-12-28 17:42:05,224 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): servicequotas.us-east-1.amazonaws.com:443
2021-12-28 17:42:05,573 - MainThread - urllib3.connectionpool - DEBUG - https://servicequotas.us-east-1.amazonaws.com:443 "POST / HTTP/1.1" 400 36
2021-12-28 17:42:05,574 - MainThread - botocore.parsers - DEBUG - Response headers: {'Date': 'Tue, 28 Dec 2021 23:42:05 GMT', 'Content-Type': 'application/x-amz-json-1.1', 'Content-Length': '36', 'Connection': 'keep-alive', 'x-amzn-RequestId': '044220f5-1e69-46c4-af78-32b5250f90a4'}
2021-12-28 17:42:05,575 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"__type":"NoSuchResourceException"}'
2021-12-28 17:42:05,575 - MainThread - botocore.parsers - DEBUG - Response headers: {'Date': 'Tue, 28 Dec 2021 23:42:05 GMT', 'Content-Type': 'application/x-amz-json-1.1', 'Content-Length': '36', 'Connection': 'keep-alive', 'x-amzn-RequestId': '044220f5-1e69-46c4-af78-32b5250f90a4'}
2021-12-28 17:42:05,576 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"__type":"NoSuchResourceException"}'
2021-12-28 17:42:05,576 - MainThread - botocore.hooks - DEBUG - Event needs-retry.service-quotas.GetServiceQuota: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x7fd4b06d1fd0>>
2021-12-28 17:42:05,576 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2021-12-28 17:42:05,576 - MainThread - botocore.hooks - DEBUG - Event after-call.service-quotas.GetServiceQuota: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x7fd4907dbd90>>
2021-12-28 17:42:05,577 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/clidriver.py", line 459, in main
  File "awscli/clidriver.py", line 594, in __call__
  File "awscli/clidriver.py", line 770, in __call__
  File "awscli/clidriver.py", line 901, in invoke
  File "awscli/clidriver.py", line 913, in _make_client_call
  File "awscli/botocore/client.py", line 281, in _api_call
  File "awscli/botocore/client.py", line 609, in _make_api_call
botocore.errorfactory.NoSuchResourceException: An error occurred (NoSuchResourceException) when calling the GetServiceQuota operation: 

An error occurred (NoSuchResourceException) when calling the GetServiceQuota operation: `

Following commands with debug and without debug flag works fine-
aws service-quotas get-service-quota --service-code ec2 --quota-code L-1216C47A
aws service-quotas get-aws-default-service-quota --service-code events --quota-code L-244521F2
aws service-quotas list-requested-service-quota-change-history-by-quota --service-code events --quota-code L-244521F2

**Comment by aakifshaikh** [comment]
any update?

**Comment by kdaily** [comment]
Thanks for confirming the region, `us-east-1`. I can reproduce. In addition, no quotas are listed for this service code - the following command returns an empty list:

```
> aws2 service-quotas list-service-quotas --service-code events --region us-east-1
{
    "Quotas": []
}
```

These quotas do not have an "applied quota value available", hence they are not queryable with this operation. The documentation for [`get-service-quota`](https://docs.aws.amazon.com/cli/latest/reference/service-quotas/get-service-quota.html) ([API documentation](https://docs.aws.amazon.com/servicequotas/2019-06-24/apireference/API_GetServiceQuota.html) as well, which are used to generate the CLI documentation) states this as such:

> If the applied quota value is not available for a quota, the quota is not retrieved.

You would need to use the [`get-aws-default-service-quota`](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/service-quotas/get-aws-default-service-quota.html) to get information about this quota, but it will not reflect any quota increases, only give the default value.

This troubleshooting article gives some more details:

https://aws.amazon.com/premiumsupport/knowledge-center/troubleshoot-service-quotas-cli-commands/

Unfortunately there isn't anything for the AWS CLI (or any AWS SDK) to do here as the service explicitly doesn't support returning these values.

**Comment by aakifshaikh** [comment]
That's really weird. I totally understand what you are saying here. But then how do we know that we are about to exceed our quota (which was increased previously). There has to be a way to find it. I am able to run a command to get the default quota value. I am also able to get the value for list-requested-service-quota-change-history. However, both the values are not useful to know what has been used and what's pending.

Can you submit the feature request to your internal team to look into this?

**Comment by mohamed-caylent** [comment]
i really do not understand why this is not query-able! Can you please make it available to query?

**Comment by jessicawyc** [comment]
I met the same situation in China region cn-north-1 and cn-northwest-1
