### ISSUE TITLE
AWS SSO login broken

### ISSUE THREAD

**Issue by danieloldberg** [aws/aws-cli#6663]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
MacOS Monterey 12.1, MacBook Pro (16-inch, 2019)
aws-cli/2.4.11 Python/3.9.10 Darwin/21.2.0 source/x86_64 prompt/off

**Describe the question**
After christmas leave, I'm not able to login to my SSO profiles using aws sso login --profile XXXX.
Troubleshooting so far has been upgrading OS, Python, awscli and dependencies to latest versions but the issue has gone unchanged. Also tried uninstall/reinstalling using brew.
AWSCLI seems to be working fine otherwise with normal profiles and the rest of the commands.

This is my profile:
```
[profile XXXXXX]
sso_start_url = https://XXXXXX.awsapps.com/start#/
sso_region = eu-west-1
sso_account_id = XXXXXX
sso_role_name = XXXXXX
output = json
```

**Logs/output**
```

$ aws sso login --profile XXXXXX --debug
2022-01-19 08:27:24,254 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.4.11 Python/3.9.10 Darwin/21.2.0 source/x86_64
2022-01-19 08:27:24,254 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['sso', 'login', '--profile', 'XXXXXX', '--debug']
2022-01-19 08:27:24,278 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x106633550>
2022-01-19 08:27:24,278 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x10647c700>
2022-01-19 08:27:24,279 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2022-01-19 08:27:24,279 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x106413ca0>
2022-01-19 08:27:24,279 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x10641fc10>
2022-01-19 08:27:24,279 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x106645ee0>
2022-01-19 08:27:24,279 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x1064cc310>
2022-01-19 08:27:24,279 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2022-01-19 08:27:24,279 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x106645160>
2022-01-19 08:27:24,279 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.4.11/libexec/lib/python3.9/site-packages/awscli/data/cli.json
2022-01-19 08:27:24,281 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x106583f70>
2022-01-19 08:27:24,281 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x10658baf0>
2022-01-19 08:27:24,285 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x10658ba60>
2022-01-19 08:27:24,285 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x10658bc10>
2022-01-19 08:27:24,285 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x10658bb80>
2022-01-19 08:27:24,285 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x1066e8d40>
2022-01-19 08:27:24,285 - MainThread - botocore.session - DEBUG - Setting config variable for profile to 'XXXXXX'
2022-01-19 08:27:24,285 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.4.11 Python/3.9.10 Darwin/21.2.0 source/x86_64 prompt/off
2022-01-19 08:27:24,285 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['sso', 'login', '--profile', 'XXXXXX', '--debug']
2022-01-19 08:27:24,285 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x106633b80>
2022-01-19 08:27:24,286 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x1061bcca0>
2022-01-19 08:27:24,286 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x1066af040>
2022-01-19 08:27:24,286 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x1061b5dc0>
2022-01-19 08:27:24,286 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x106228790>
2022-01-19 08:27:24,286 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2022-01-19 08:27:24,291 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2022-01-19 08:27:24,291 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x1064cc1f0>
2022-01-19 08:27:24,291 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x10647b5e0>
2022-01-19 08:27:24,316 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.4.11/libexec/lib/python3.9/site-packages/awscli/botocore/data/sso/2019-06-10/service-2.json
2022-01-19 08:27:24,316 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sso: calling handler <function add_sso_commands at 0x10647b040>
2022-01-19 08:27:24,316 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sso: calling handler <function add_waiters at 0x106645160>
2022-01-19 08:27:24,339 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sso_login: calling handler <function add_waiters at 0x106645160>
2022-01-19 08:27:24,394 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/Cellar/awscli/2.4.11/libexec/lib/python3.9/site-packages/awscli/botocore/credentials.py", line 307, in __getitem__
    return json.load(f)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/awscli/2.4.11/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 459, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/Cellar/awscli/2.4.11/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 594, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/Cellar/awscli/2.4.11/libexec/lib/python3.9/site-packages/awscli/customizations/commands.py", line 191, in __call__
    rc = self._run_main(parsed_args, parsed_globals)
  File "/usr/local/Cellar/awscli/2.4.11/libexec/lib/python3.9/site-packages/awscli/customizations/sso/login.py", line 41, in _run_main
    do_sso_login(
  File "/usr/local/Cellar/awscli/2.4.11/libexec/lib/python3.9/site-packages/awscli/customizations/sso/utils.py", line 57, in do_sso_login
    return token_fetcher.fetch_token(
  File "/usr/local/Cellar/awscli/2.4.11/libexec/lib/python3.9/site-packages/awscli/botocore/utils.py", line 2558, in fetch_token
    return self._token(start_url, force_refresh)
  File "/usr/local/Cellar/awscli/2.4.11/libexec/lib/python3.9/site-packages/awscli/botocore/utils.py", line 2553, in _token
    token = self._poll_for_token(start_url)
  File "/usr/local/Cellar/awscli/2.4.11/libexec/lib/python3.9/site-packages/awscli/botocore/utils.py", line 2507, in _poll_for_token
    registration = self._registration()
  File "/usr/local/Cellar/awscli/2.4.11/libexec/lib/python3.9/site-packages/awscli/botocore/utils.py", line 2477, in _registration
    registration = self._cache[cache_key]
  File "/usr/local/Cellar/awscli/2.4.11/libexec/lib/python3.9/site-packages/awscli/botocore/credentials.py", line 309, in __getitem__
    raise KeyError(cache_key)
KeyError: 'botocore-client-id-eu-west-1'

'botocore-client-id-eu-west-1'
```

**Comment by tim-finnigan** [comment]
Hi @danieloldberg, thanks for reaching out. For installing the CLI these are the recommended methods: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html. 

And these are the steps for configuring SSO: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html. Did you try following the steps mentioned in that documentation?

**Comment by danieloldberg** [comment]
Hi.

I uninstalled awscli and reinstalled using the "Command line installer - All users" but the issue persists.

Yes, when using the automatic configuration, I get this:
```
$ aws configure sso
SSO start URL [None]: https://XXXXX.awsapps.com/start#/
SSO Region [None]: eu-west-1

'b05bfc8680414c00546c32dd28d07f8401d3bc59'
```

**Comment by tim-finnigan** [comment]
Hi @danieloldberg, thanks for following up. Are you getting the same error in the debug logs as before?

You could try removing the `~/.aws/sso/` directory containing cached files and going through the config steps again.

**Comment by danieloldberg** [comment]
Hi again.

Thanks, deleting the `~/.aws/sso/` directory solved the issue. Is this documented anywhere?

**Comment by tim-finnigan** [comment]
Hi @danieloldberg, glad to hear that fixed your issue. I’m not sure if this is currently documented anywhere but it probably should be. I think [here](https://docs.aws.amazon.com/singlesignon/latest/userguide/troubleshooting.html) would be a good place to mention this. I can pass that feedback along to our documentation writers. Thanks!
