### ISSUE TITLE
put issue

### ISSUE THREAD

**Issue by qiopta** [aws/aws-cli#6691]
Hi I am trying to put a file from cloudshell present directory to S3:  

I am using:

aws s3api put-object --bucket praw2 --key praw_layer --body /home/cloudshell-user/praw_layer.zip

I get the following trace for the error:
Error parsing parameter '--body': Blob values must be a path to a file.
[cloudshell-user@ip-10-0-85-91 ~]$ aws s3api put-object --debug  --bucket praw2 --key python  --body praw_layer.zip
2022-02-03 12:19:51,897 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.4.6 Python/3.8.8 Linux/4.14.252-195.483.amzn2.x86_64 exec-env/CloudShell exe/x86_64.amzn.2
2022-02-03 12:19:51,897 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3api', 'put-object', '--debug', '--bucket', 'praw2', '--key', 'python', '--body', 'praw_layer.zip']
2022-02-03 12:19:51,910 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x7f1af4a86ca0>
2022-02-03 12:19:51,910 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x7f1af4be09d0>
2022-02-03 12:19:51,910 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2022-02-03 12:19:51,910 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7f1af4c881f0>
2022-02-03 12:19:51,910 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7f1af4c91310>
2022-02-03 12:19:51,910 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x7f1af4a17700>
2022-02-03 12:19:51,910 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x7f1af4bab820>
2022-02-03 12:19:51,910 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2022-02-03 12:19:51,910 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x7f1af4a8f940>
2022-02-03 12:19:51,910 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.4.6/dist/awscli/data/cli.json
2022-02-03 12:19:51,913 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x7f1af4ade820>
2022-02-03 12:19:51,913 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x7f1af4adf3a0>
2022-02-03 12:19:51,913 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x7f1af4adf310>
2022-02-03 12:19:51,913 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x7f1af4adf4c0>
2022-02-03 12:19:51,913 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x7f1af4adf430>
2022-02-03 12:19:51,914 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x7f1af49b7800>
2022-02-03 12:19:51,914 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.4.6 Python/3.8.8 Linux/4.14.252-195.483.amzn2.x86_64 exec-env/CloudShell exe/x86_64.amzn.2 prompt/off
2022-02-03 12:19:51,914 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3api', 'put-object', '--debug', '--bucket', 'praw2', '--key', 'python', '--body', 'praw_layer.zip']
2022-02-03 12:19:51,914 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7f1af4a89310>
2022-02-03 12:19:51,914 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7f1af54d4790>
2022-02-03 12:19:51,915 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7f1af49f8b80>
2022-02-03 12:19:51,915 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x7f1af54cec10>
2022-02-03 12:19:51,915 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f1af5432430>
2022-02-03 12:19:51,916 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2022-02-03 12:19:51,917 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f1af4bab700>
2022-02-03 12:19:51,917 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7f1af4bda8b0>
2022-02-03 12:19:51,930 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.4.6/dist/awscli/botocore/data/s3/2006-03-01/service-2.json
2022-02-03 12:19:51,942 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3api: calling handler <function add_waiters at 0x7f1af4a8f940>
2022-02-03 12:19:51,957 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.4.6/dist/awscli/botocore/data/s3/2006-03-01/waiters-2.json
2022-02-03 12:19:51,958 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('acl', <awscli.arguments.CLIArgument object at 0x7f1af3d8ca00>), ('body', <awscli.arguments.CLIArgument object at 0x7f1af3d8ca30>), ('bucket', <awscli.arguments.CLIArgument object at 0x7f1af3d8ca60>), ('cache-control', <awscli.arguments.CLIArgument object at 0x7f1af3d8ca90>), ('content-disposition', <awscli.arguments.CLIArgument object at 0x7f1af3d8cac0>), ('content-encoding', <awscli.arguments.CLIArgument object at 0x7f1af3d8caf0>), ('content-language', <awscli.arguments.CLIArgument object at 0x7f1af3d8cb20>), ('content-length', <awscli.arguments.CLIArgument object at 0x7f1af3d8cb50>), ('content-md5', <awscli.arguments.CLIArgument object at 0x7f1af3d8cb80>), ('content-type', <awscli.arguments.CLIArgument object at 0x7f1af3d8cbb0>), ('expires', <awscli.arguments.CLIArgument object at 0x7f1af3d8cbe0>), ('grant-full-control', <awscli.arguments.CLIArgument object at 0x7f1af3d8cc10>), ('grant-read', <awscli.arguments.CLIArgument object at 0x7f1af3d8cc40>), ('grant-read-acp', <awscli.arguments.CLIArgument object at 0x7f1af3d8cc70>), ('grant-write-acp', <awscli.arguments.CLIArgument object at 0x7f1af3d8cca0>), ('key', <awscli.arguments.CLIArgument object at 0x7f1af3d8ccd0>), ('metadata', <awscli.arguments.CLIArgument object at 0x7f1af3d8cd00>), ('server-side-encryption', <awscli.arguments.CLIArgument object at 0x7f1af3d8cd30>), ('storage-class', <awscli.arguments.CLIArgument object at 0x7f1af3d8cd60>), ('website-redirect-location', <awscli.arguments.CLIArgument object at 0x7f1af3d8cd90>), ('sse-customer-algorithm', <awscli.arguments.CLIArgument object at 0x7f1af3d8cdc0>), ('sse-customer-key', <awscli.arguments.CLIArgument object at 0x7f1af3d8cdf0>), ('sse-customer-key-md5', <awscli.arguments.CLIArgument object at 0x7f1af3d8ce20>), ('ssekms-key-id', <awscli.arguments.CLIArgument object at 0x7f1af3d8ce50>), ('ssekms-encryption-context', <awscli.arguments.CLIArgument object at 0x7f1af3d8ce80>), ('bucket-key-enabled', <awscli.arguments.BooleanArgument object at 0x7f1af3d8ceb0>), ('no-bucket-key-enabled', <awscli.arguments.BooleanArgument object at 0x7f1af3d8cee0>), ('request-payer', <awscli.arguments.CLIArgument object at 0x7f1af3d8cf10>), ('tagging', <awscli.arguments.CLIArgument object at 0x7f1af3d8cf40>), ('object-lock-mode', <awscli.arguments.CLIArgument object at 0x7f1af3d8cf70>), ('object-lock-retain-until-date', <awscli.arguments.CLIArgument object at 0x7f1af3d8cfa0>), ('object-lock-legal-hold-status', <awscli.arguments.CLIArgument object at 0x7f1af3d8cfd0>), ('expected-bucket-owner', <awscli.arguments.CLIArgument object at 0x7f1af3d1c040>)])
2022-02-03 12:19:51,959 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-object: calling handler <function add_streaming_output_arg at 0x7f1af4a898b0>
2022-02-03 12:19:51,959 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-object: calling handler <function add_cli_input_json at 0x7f1af5432ca0>
2022-02-03 12:19:51,959 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-object: calling handler <function add_cli_input_yaml at 0x7f1af5432f70>
2022-02-03 12:19:51,959 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-object: calling handler <function unify_paging_params at 0x7f1af4bec040>
2022-02-03 12:19:51,971 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.4.6/dist/awscli/botocore/data/s3/2006-03-01/paginators-1.json
2022-02-03 12:19:51,971 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.put-object: calling handler <function add_generate_skeleton at 0x7f1af4b51dc0>
2022-02-03 12:19:51,971 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.put-object: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7f1af3d1c190>>
2022-02-03 12:19:51,971 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.put-object: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7f1af3d8c340>>
2022-02-03 12:19:51,971 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.put-object: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f1af3d8c370>>
2022-02-03 12:19:51,973 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.acl: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f1af3f73250>
2022-02-03 12:19:51,973 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.put-object.body: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f1af3f73250>
2022-02-03 12:19:51,973 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.s3.put-object: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f1af88516d0>
2022-02-03 12:19:51,973 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/clidriver.py", line 459, in main
  File "awscli/clidriver.py", line 594, in __call__
  File "awscli/clidriver.py", line 742, in __call__
  File "awscli/clidriver.py", line 800, in _build_call_parameters
  File "awscli/arguments.py", line 453, in add_to_params
  File "awscli/arguments.py", line 470, in _unpack_argument
  File "awscli/argprocess.py", line 145, in unpack_cli_arg
  File "awscli/argprocess.py", line 163, in _unpack_cli_arg
  File "awscli/argprocess.py", line 226, in unpack_scalar_cli_arg
awscli.argprocess.ParamError: Error parsing parameter '--body': Blob values must be a path to a file.

I can confirm the path to my file is correct and the file does exist.  Can you advise please?

**Comment by qiopta** [comment]
Was in wrong DIR, please close
