### ISSUE TITLE
events put-targets desn't valid the JSON text input

### ISSUE THREAD

**Issue by guillain** [aws/aws-cli#6711]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/reference/events/put-targets.html)
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
_Input_ must be a string defining a JSON doc but no JSON text format is accepted 

**SDK version number**
aws-cli/1.19.94 Python/2.7.5 Linux/3.10.0-1160.31.1.el7.x86_64 botocore/1.20.94

**Platform/OS/Hardware/Device**
EC2 - Redhat 8

**To Reproduce (observed behavior)**
$ aws events put-targets --rule "rule_my_fct" --targets "Id"="1","Arn"="arn:aws:lambda:eu-west-1:x:function:my_fct","Input"="{\"env\":\"dev\"}"

Error parsing parameter '--targets': Expected: '=', received: '"' for input:
Id=1,Arn=arn:aws:lambda:eu-west-1:x:function:my_fct,Input={"env":"dev"}

$ aws events put-targets --rule "rule_my_fct" --targets "Id"="1","Arn"="arn:aws:lambda:eu-west-1:x:function:my_fct","Input"="env:dev"

An error occurred (ValidationException) when calling the PutTargets operation: JSON syntax error in input for target 1: [Source: (String)"env:dev"; line: 1, column: 4]

$ aws events put-targets --rule "rule_my_fct" --targets "Id"="1","Arn"="arn:aws:lambda:eu-west-1:x:function:my_fct","Input"="{'env':'dev'}"

Error parsing parameter '--targets': Expected: '=', received: ''' for input:
Id=1,Arn=arn:aws:lambda:eu-west-1:x:function:my_fct,Input={'env':'dev'}

$ aws events put-targets --rule "rule_my_fct" --targets "Id"="1","Arn"="arn:aws:lambda:eu-west-1:x:function:my_fct","Input"='{"env":"dev"}'

Error parsing parameter '--targets': Expected: '=', received: '"' for input:
Id=1,Arn=arn:aws:lambda:eu-west-1:x:function:my_fct,Input={"env":"dev"}
#

**Expected behavior**
The JSON doc define as string is never accepted.

**Logs/output**
$ aws events put-targets --rule "${APP_NAME}_stop" --targets "Id"="1","Arn"="arn:aws:lambda:eu-west-1:x:function:my_fct","Input"="{\"env\":\"dev\"}" --debug
2022-02-11 09:25:47,345 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.19.94 Python/2.7.5 Linux/3.10.0-1160.31.1.el7.x86_64 botocore/1.20.94
2022-02-11 09:25:47,346 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['events', 'put-targets', '--rule', 'my_fct', '--targets', 'Id=1,Arn=arn:aws:lambda:eu-west-1:x:function:my_fct,Input={"env":"dev"}', '--debug']
2022-02-11 09:25:47,346 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7f995c6fb6e0>
2022-02-11 09:25:47,346 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7f995d13eaa0>
2022-02-11 09:25:47,347 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f995d123488>
2022-02-11 09:25:47,348 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2022-02-11 09:25:47,350 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f995ca6f0c8>
2022-02-11 09:25:47,352 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws/lib/python2.7/site-packages/botocore/data/events/2015-10-07/service-2.json
2022-02-11 09:25:47,396 - MainThread - botocore.hooks - DEBUG - Changing event name from building-command-table.events to building-command-table.eventbridge
2022-02-11 09:25:47,397 - MainThread - botocore.hooks - DEBUG - Event building-command-table.eventbridge: calling handler <function add_waiters at 0x7f995c704758>
2022-02-11 09:25:47,414 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'rule', <awscli.arguments.CLIArgument object at 0x7f995c3ded90>), (u'event-bus-name', <awscli.arguments.CLIArgument object at 0x7f995c3dedd0>), (u'targets', <awscli.arguments.ListArgument object at 0x7f995c3dee50>)])
2022-02-11 09:25:47,414 - MainThread - botocore.hooks - DEBUG - Changing event name from building-argument-table.events.put-targets to building-argument-table.eventbridge.put-targets
2022-02-11 09:25:47,414 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.eventbridge.put-targets: calling handler <function add_streaming_output_arg at 0x7f995c6fb9b0>
2022-02-11 09:25:47,414 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.eventbridge.put-targets: calling handler <function add_cli_input_json at 0x7f995d128578>
2022-02-11 09:25:47,415 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.eventbridge.put-targets: calling handler <function unify_paging_params at 0x7f9960971c08>
2022-02-11 09:25:47,430 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws/lib/python2.7/site-packages/botocore/data/events/2015-10-07/paginators-1.json
2022-02-11 09:25:47,430 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.eventbridge.put-targets: calling handler <function add_generate_skeleton at 0x7f9960955578>
2022-02-11 09:25:47,431 - MainThread - botocore.hooks - DEBUG - Changing event name from before-building-argument-table-parser.events.put-targets to before-building-argument-table-parser.eventbridge.put-targets
2022-02-11 09:25:47,431 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.eventbridge.put-targets: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7f995c3dea90>>
2022-02-11 09:25:47,431 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.eventbridge.put-targets: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f995c3dee90>>
2022-02-11 09:25:47,433 - MainThread - botocore.hooks - DEBUG - Changing event name from operation-args-parsed.events.put-targets to operation-args-parsed.eventbridge.put-targets
2022-02-11 09:25:47,434 - MainThread - botocore.hooks - DEBUG - Changing event name from load-cli-arg.events.put-targets.rule to load-cli-arg.eventbridge.put-targets.rule
2022-02-11 09:25:47,434 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.eventbridge.put-targets.rule: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f995c5be090>
2022-02-11 09:25:47,434 - MainThread - botocore.hooks - DEBUG - Changing event name from process-cli-arg.events.put-targets to process-cli-arg.eventbridge.put-targets
2022-02-11 09:25:47,434 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.eventbridge.put-targets: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f995c710e90>
2022-02-11 09:25:47,434 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'my_fct' for parameter "rule": u'my_fct'
2022-02-11 09:25:47,434 - MainThread - botocore.hooks - DEBUG - Changing event name from load-cli-arg.events.put-targets.event-bus-name to load-cli-arg.eventbridge.put-targets.event-bus-name
2022-02-11 09:25:47,435 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.eventbridge.put-targets.event-bus-name: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f995c5be090>
2022-02-11 09:25:47,435 - MainThread - botocore.hooks - DEBUG - Changing event name from load-cli-arg.events.put-targets.targets to load-cli-arg.eventbridge.put-targets.targets
2022-02-11 09:25:47,435 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.eventbridge.put-targets.targets: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f995c5be090>
2022-02-11 09:25:47,436 - MainThread - botocore.hooks - DEBUG - Changing event name from process-cli-arg.events.put-targets to process-cli-arg.eventbridge.put-targets
2022-02-11 09:25:47,436 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.eventbridge.put-targets: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f995c710e90>
2022-02-11 09:25:47,436 - MainThread - awscli.argprocess - DEBUG - Parsing param --targets as shorthand
2022-02-11 09:25:47,438 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/aws/lib/python2.7/site-packages/awscli/clidriver.py", line 218, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/aws/lib/python2.7/site-packages/awscli/clidriver.py", line 362, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/aws/lib/python2.7/site-packages/awscli/clidriver.py", line 505, in __call__
    parsed_args, self.arg_table)
  File "/usr/local/aws/lib/python2.7/site-packages/awscli/clidriver.py", line 561, in _build_call_parameters
    arg_object.add_to_params(service_params, value)
  File "/usr/local/aws/lib/python2.7/site-packages/awscli/arguments.py", line 453, in add_to_params
    unpacked = self._unpack_argument(value)
  File "/usr/local/aws/lib/python2.7/site-packages/awscli/arguments.py", line 463, in _unpack_argument
    cli_argument=self, value=value)
  File "/usr/local/aws/lib/python2.7/site-packages/awscli/arguments.py", line 476, in _emit_first_response
    responses = self._emit(name, **kwargs)
  File "/usr/local/aws/lib/python2.7/site-packages/awscli/arguments.py", line 473, in _emit
    return self._event_emitter.emit(name, **kwargs)
  File "/usr/local/aws/lib/python2.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/aws/lib/python2.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/aws/lib/python2.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/aws/lib/python2.7/site-packages/awscli/argprocess.py", line 314, in __call__
    cli_argument, value, service_id, operation_name)
  File "/usr/local/aws/lib/python2.7/site-packages/awscli/argprocess.py", line 338, in _parse_as_shorthand
    raise ParamError(cli_argument.cli_name, str(e))
ParamError: Error parsing parameter '--targets': Expected: '=', received: '"' for input:
Id=1,Arn=arn:aws:lambda:eu-west-1:x:function:my_fct,Input={"env":"dev"}
                                                                                                ^
2022-02-11 09:25:47,439 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Error parsing parameter '--targets': Expected: '=', received: '"' for input:
Id=1,Arn=arn:aws:lambda:eu-west-1:x:function:my_fct,Input={"env":"dev"}
                                                                                                ^

**Additional context**
Nothing special

**Comment by tim-finnigan** [comment]
Hi @guillain thanks for reaching out. I think you may just need to add brackets and escape the quotes in the Input part of this command. Could you try this?

`aws events put-targets --rule "rule_my_fct" --targets '{"Id":"1","Arn":"arn:aws:lambda:eu-west-1❌function:my_fct","Input":"{\"env\":\"dev\"}"}'`

**Comment by guillain** [comment]
Sorry for the late reply.
Works like a charm with the JSON doc as target 👍 
Can be interesting to see that as example in the doc: https://docs.aws.amazon.com/cli/latest/reference/events/put-targets.html
Thanks ! and have a nice day!

**Comment by nouhab** [comment]
hello, do you resolve this problem . I face the some issue ?
