### ISSUE TITLE
IndexError with CodeArtifact Login on GHA Mac OS X

### ISSUE THREAD

**Issue by texastony** [aws/aws-cli#6813]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

**Describe the bug**

On Mac OS 11.6.5., with `aws --version` as:
```
aws-cli/2.4.27 Python/3.8.8 Darwin/20.6.0 exe/x86_64 prompt/off
```

Running the command 
```
aws codeartifact login --tool dotnet --domain github --domain-owner *** --repository **** --duration-seconds 900
```
Throws a `list index out of range` error with no context what so ever. 

This is running the command on a GitHub Action (running on `macos-latest`) so that we can pull our package from Code Artifact and test on Mac OSX.

**SDK version number**
Tried with:
```
aws-cli/2.4.27 Python/3.8.8 Darwin/20.6.0 exe/x86_64 prompt/off
```
and 
```
aws-cli/2.4.27 Python/3.9.10 Darwin/20.6.0 source/x86_64 prompt/off 
```

**Platform/OS/Hardware/Device**
On Mac OS 11.6.5 hosted by GitHub.

**To Reproduce (observed behavior)**
Create a GitHub workflow like the following:
```
name: reproduce-codeartifact-index-error

on: ["push"]

jobs:
  recreate-bug:
     runs-on: macos-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Configure AWS credentials for pulling from CA
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::587316601012:role/GitHub-DotNet-CA-Reader
        aws-region: us-west-2
    - name: fetch ca creds
      run: |
        aws codeartifact login --tool dotnet --domain github --domain-owner <your-account> --repository <your-repo> --duration-seconds 900 --debug
```

**Expected behavior**
Ideally, successful authorization of the local `dotnet` tool to pull from CodeArtifact. 

At minimum, an exception that informs me what is offensive about my request. Is the Nuget Config file missing? Or something of that matter.

This command succeeds on GitHub's `ubuntu-latest`. It only fails on their `macos-latest` hosts. But the exception is way too vague.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

The full trace back has events I do not want to share, so I am limiting it to the evidence that API request succeeded but parsing the response failed:
```
2022-03-24 20:46:14,212 - MainThread - botocore.hooks - DEBUG - Event needs-retry.codeartifact.GetRepositoryEndpoint: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x108690d00>>
2022-03-24 20:46:14,212 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2022-03-24 20:46:14,212 - MainThread - botocore.hooks - DEBUG - Event after-call.codeartifact.GetRepositoryEndpoint: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x1086907f0>>
2022-03-24 20:46:18,246 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/Cellar/awscli/2.4.27/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 459, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/Cellar/awscli/2.4.27/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 594, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/Cellar/awscli/2.4.27/libexec/lib/python3.9/site-packages/awscli/customizations/commands.py", line 191, in __call__
    rc = self._run_main(parsed_args, parsed_globals)
  File "/usr/local/Cellar/awscli/2.4.27/libexec/lib/python3.9/site-packages/awscli/customizations/codeartifact/login.py", line 663, in _run_main
    login.login(parsed_args.dry_run)
  File "/usr/local/Cellar/awscli/2.4.27/libexec/lib/python3.9/site-packages/awscli/customizations/codeartifact/login.py", line 122, in login
    source_to_url_dict = self._get_source_to_url_dict()
  File "/usr/local/Cellar/awscli/2.4.27/libexec/lib/python3.9/site-packages/awscli/customizations/codeartifact/login.py", line 200, in _get_source_to_url_dict
    source_to_url_dict[self._parse_source_name(lines[i])] = \
  File "/usr/local/Cellar/awscli/2.4.27/libexec/lib/python3.9/site-packages/awscli/customizations/codeartifact/login.py", line 213, in _parse_source_name
    return line_without_tag.split(None, 1)[1]
IndexError: list index out of range
```

**Additional context**
Here is the content of the default `~/.config/NuGet/NuGet.Config`:
```
﻿<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```

**Edited**
Forgot to include GitHub permission and runs-on sections.

**Comment by texastony** [comment]
This allows fails in the exact same way on GitHub's Windows host:
**SDK version number**
```
aws-cli/2.4.25 Python/3.8.8 Windows/10 exe/AMD64
```

**Platform/OS/Hardware/Device**
Microsoft Windows Server 2022
10.0.20348

**To Reproduce (observed behavior)**
Create a GitHub workflow like the following:
```
name: reproduce-codeartifact-index-error

on: ["push"]

jobs:
  recreate-bug:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Configure AWS credentials for pulling from CA
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::587316601012:role/GitHub-DotNet-CA-Reader
        aws-region: us-west-2
    - name: fetch ca creds
      run: |
        aws codeartifact login --tool dotnet --domain github --domain-owner <your-account> --repository <your-repo> --duration-seconds 900 --debug
```

**Logs/output**
```
022-03-24 21:25:27,553 - MainThread - botocore.parsers - DEBUG - Response headers: {'Date': 'Thu, 24 Mar 2022 21:25:27 GMT', 'Content-Type': 'application/json', 'Content-Length': '110', 'Connection': 'keep-alive', 'x-amzn-RequestId': '93c8b8c2-7889-416e-96b2-097582f93598'}
2022-03-24 21:25:27,553 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"repositoryEndpoint":"https://github-***.d.codeartifact.us-west-2.amazonaws.com/nuget/dotnet-esdk/"}'
2022-03-24 21:25:27,553 - MainThread - botocore.hooks - DEBUG - Event needs-retry.codeartifact.GetRepositoryEndpoint: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x000002BF8AE209D0>>
2022-03-24 21:25:27,553 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2022-03-24 21:25:27,554 - MainThread - botocore.hooks - DEBUG - Event after-call.codeartifact.GetRepositoryEndpoint: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x000002BF8AE20550>>
2022-03-24 21:25:34,818 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli\clidriver.py", line 459, in main
  File "awscli\clidriver.py", line 594, in __call__
  File "awscli\customizations\commands.py", line 191, in __call__
  File "awscli\customizations\codeartifact\login.py", line 663, in _run_main
  File "awscli\customizations\codeartifact\login.py", line 122, in login
  File "awscli\customizations\codeartifact\login.py", line 200, in _get_source_to_url_dict
  File "awscli\customizations\codeartifact\login.py", line 213, in _parse_source_name
IndexError: list index out of range
```

**Additional Content**

**Comment by tim-finnigan** [comment]
This looks similar to https://github.com/aws/aws-cli/issues/6197. Does running `dotnet nuget list source --format detailed` before `aws codeartifact login` resolve this as mentioned in that issue?

**Comment by texastony** [comment]
@tim-finnigan Nailed it. I am so annoyed at `dotnet` for logging junk. 

Closing in favor of https://github.com/aws/aws-cli/issues/6197
