### ISSUE TITLE
python 3.10 install error

### ISSUE THREAD

**Issue by tooptoop4** [aws/aws-cli#6886]
### Describe the bug

    Traceback (most recent call last):
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-req-build-0amb2boj/backends/pep517.py", line 50, in build_wheel
          _build_and_inject_ac_index(os.path.join(wheel_directory, whl_filename))
        File "/tmp/pip-req-build-0amb2boj/backends/pep517.py", line 84, in _build_and_inject_ac_index
          generate_index(ac_index_build_name)
        File "/tmp/pip-req-build-0amb2boj/awscli/autocomplete/generator.py", line 34, in generate_index
          _do_generate_index(temp_name)
        File "/tmp/pip-req-build-0amb2boj/awscli/autocomplete/generator.py", line 50, in _do_generate_index
          driver = clidriver.create_clidriver()
        File "/tmp/pip-req-build-0amb2boj/awscli/clidriver.py", line 95, in create_clidriver
          load_plugins(session.full_config.get('plugins', {}),
        File "/tmp/pip-req-build-0amb2boj/awscli/plugin.py", line 48, in load_plugins
          _load_plugins(BUILTIN_PLUGINS, event_hooks)
        File "/tmp/pip-req-build-0amb2boj/awscli/plugin.py", line 62, in _load_plugins
          modules = _import_plugins(plugin_mapping)
        File "/tmp/pip-req-build-0amb2boj/awscli/plugin.py", line 76, in _import_plugins
          module = __import__(path, fromlist=[module])
        File "/tmp/pip-req-build-0amb2boj/awscli/handlers.py", line 44, in <module>
          from awscli.customizations.dynamodb.ddb import register_ddb
        File "/tmp/pip-req-build-0amb2boj/awscli/customizations/dynamodb/ddb.py", line 14, in <module>
          from awscli.customizations.dynamodb.subcommands import (
        File "/tmp/pip-req-build-0amb2boj/awscli/customizations/dynamodb/subcommands.py", line 24, in <module>
          from awscli.customizations.dynamodb.extractor import AttributeExtractor
        File "/tmp/pip-req-build-0amb2boj/awscli/customizations/dynamodb/extractor.py", line 13, in <module>
          from .parser import Parser
        File "/tmp/pip-req-build-0amb2boj/awscli/customizations/dynamodb/parser.py", line 22, in <module>
          from .lexer import Lexer
        File "/tmp/pip-req-build-0amb2boj/awscli/customizations/dynamodb/lexer.py", line 21, in <module>
          from .types import Binary
        File "/tmp/pip-req-build-0amb2boj/awscli/customizations/dynamodb/types.py", line 13, in <module>
          from collections import Mapping, Set
      ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
      [end of output]

### Expected Behavior

aws cli installs on python 3.10

### Current Behavior

error in description

### Reproduction Steps

pip3 install --no-cache-dir https://github.com/aws/aws-cli/archive/refs/tags/2.5.7.tar.gz

### CLI version used

2.5.7

### Environment details (OS name and version, etc.)

 Python 3.10.4 (main, Apr 20 2022, 05:30:59) [GCC 10.2.1 20210110] on linux

**Comment by kdaily** [comment]
Hi @tooptoop4,

Thanks for writing in. As of now the AWS CLI does not have support for Python 3.10. This is a known change to the imports for the `collections` module. As for the ability to `pip` install the AWS CLI v2, follow along with this tracking issue to know when we'll officially be PEP 517 compliant, and this should work (albeit provisionally).

https://github.com/aws/aws-cli/issues/6785

Thanks!

**Comment by kdaily** [comment]
FYI, a PR has been posted that fixes the imports in #6889.

**Comment by Borda** [comment]
we still see this issue
