### ISSUE TITLE
Error in shorthand parsing of the --api-passthrough parameter in acm-pca

### ISSUE THREAD

**Issue by tomasclemente** [aws/aws-cli#7018]
### Describe the bug

I am following the instructions provide in the AWS Documentation [here](https://docs.aws.amazon.com/acm-pca/latest/userguide/PcaIssueCert.html#custom-subject-2) and use the CLI command aws acm-pca issue-certificate to create a certificate with custom extensions

Here is the command I am using

```
> aws acm-pca issue-certificate \
>       --validity Type=DAYS,Value=10 \
>       --signing-algorithm "SHA256WITHRSA" \
>       --csr fileb://csr.pem \
>       --api-passthrough fileb://extensions.txt \
>       --template-arn arn:aws:acm-pca:::template/EndEntityCertificate_APIPassthrough/V1 \
>       --certificate-authority-arn arn:aws:acm-pca:[REGION]:[ACCOUNT]:certificate-authority/[PCA_ID]
```

### Expected Behavior

I expect to receive a response by the acm-pca API with the ARN of the issued certificate. But it seems that the API call is never launched due to an error while parsing parameters

### Current Behavior

The execution of the issue-certificate command stops with a Python error:

```
$ aws acm-pca issue-certificate \
>    --validity Type=DAYS,Value=10 \
>    --signing-algorithm "SHA256WITHRSA" \
>    --csr fileb://csr.pem \
>    --api-passthrough fileb://extensions.txt \
>    --template-arn arn:aws:acm-pca:::template/EndEntityCertificate_APIPassthrough/V1 \
>    --certificate-authority-arn arn:aws:acm-pca:[REGION]:[ACCOUNT]:certificate-authority/[PCA_ID]

'in <string>' requires string as left operand, not int
```

Applying --debug, it seems that the execution stops during the shorthand parsing of the api-passthrough parameter.

```
2022-06-06 11:49:53,217 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.7.6 Python/3.9.11 Darwin/21.4.0 exe/x86_64
2022-06-06 11:49:53,218 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['acm-pca', 'issue-certificate', '--validity', 'Type=DAYS,Value=10', '--signing-algorithm', 'SHA256WITHRSA', '--csr', 'fileb://csr.pem', '--api-passthrough', 'fileb://extensions.txt', '--template-arn', 'arn:aws:acm-pca:::template/EndEntityCertificate_APIPassthrough/V1', '--certificate-authority-arn', 'arn:aws:acm-pca:[REGION]:[ACCOUNT]:certificate-authority/[PCA_ID]', '--debug']
2022-06-06 11:49:53,281 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x7ff675552940>
2022-06-06 11:49:53,281 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x7ff6753ae1f0>
2022-06-06 11:49:53,282 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2022-06-06 11:49:53,282 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7ff67534f550>
2022-06-06 11:49:53,282 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7ff675358550>
2022-06-06 11:49:53,282 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x7ff675565310>
2022-06-06 11:49:53,282 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x7ff6753f6ca0>
2022-06-06 11:49:53,282 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2022-06-06 11:49:53,282 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x7ff67555d550>
2022-06-06 11:49:53,283 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/data/cli.json
2022-06-06 11:49:53,285 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x7ff6754aa670>
2022-06-06 11:49:53,285 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x7ff6754b01f0>
2022-06-06 11:49:53,285 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x7ff6754b0160>
2022-06-06 11:49:53,285 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x7ff6754b0310>
2022-06-06 11:49:53,285 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x7ff6754b0280>
2022-06-06 11:49:53,285 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x7ff675600dc0>
2022-06-06 11:49:53,285 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.7.6 Python/3.9.11 Darwin/21.4.0 exe/x86_64 prompt/off
2022-06-06 11:49:53,286 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['acm-pca', 'issue-certificate', '--validity', 'Type=DAYS,Value=10', '--signing-algorithm', 'SHA256WITHRSA', '--csr', 'fileb://csr.pem', '--api-passthrough', 'fileb://extensions.txt', '--template-arn', 'arn:aws:acm-pca:::template/EndEntityCertificate_APIPassthrough/V1', '--certificate-authority-arn', 'arn:aws:acm-pca:[REGION]:[ACCOUNT]:certificate-authority/[PCA_ID]', '--debug']
2022-06-06 11:49:53,286 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7ff675552f70>
2022-06-06 11:49:53,286 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7ff6750d9700>
2022-06-06 11:49:53,286 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7ff6755c4430>
2022-06-06 11:49:53,286 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x7ff6750d3b80>
2022-06-06 11:49:53,286 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7ff675141280>
2022-06-06 11:49:53,295 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2022-06-06 11:49:53,300 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7ff6753f6b80>
2022-06-06 11:49:53,301 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7ff6753ac0d0>
2022-06-06 11:49:53,331 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/botocore/data/acm-pca/2017-08-22/service-2.json
2022-06-06 11:49:53,334 - MainThread - botocore.hooks - DEBUG - Event building-command-table.acm-pca: calling handler <function add_waiters at 0x7ff67555d550>
2022-06-06 11:49:53,362 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/botocore/data/acm-pca/2017-08-22/waiters-2.json
2022-06-06 11:49:53,364 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('api-passthrough', <awscli.arguments.CLIArgument object at 0x7ff675769550>), ('certificate-authority-arn', <awscli.arguments.CLIArgument object at 0x7ff675769520>), ('csr', <awscli.arguments.CLIArgument object at 0x7ff6757694f0>), ('signing-algorithm', <awscli.arguments.CLIArgument object at 0x7ff675769700>), ('template-arn', <awscli.arguments.CLIArgument object at 0x7ff675769730>), ('validity', <awscli.arguments.CLIArgument object at 0x7ff675769790>), ('validity-not-before', <awscli.arguments.CLIArgument object at 0x7ff6757697c0>), ('idempotency-token', <awscli.arguments.CLIArgument object at 0x7ff675769760>)])
2022-06-06 11:49:53,364 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.acm-pca.issue-certificate: calling handler <function add_streaming_output_arg at 0x7ff675557280>
2022-06-06 11:49:53,364 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.acm-pca.issue-certificate: calling handler <function add_cli_input_json at 0x7ff675141a60>
2022-06-06 11:49:53,364 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.acm-pca.issue-certificate: calling handler <function add_cli_input_yaml at 0x7ff675141ca0>
2022-06-06 11:49:53,364 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.acm-pca.issue-certificate: calling handler <function unify_paging_params at 0x7ff6753ae700>
2022-06-06 11:49:53,395 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/botocore/data/acm-pca/2017-08-22/paginators-1.json
2022-06-06 11:49:53,396 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.acm-pca.issue-certificate: calling handler <function add_generate_skeleton at 0x7ff67549cc10>
2022-06-06 11:49:53,396 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.acm-pca.issue-certificate: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7ff6757698b0>>
2022-06-06 11:49:53,396 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.acm-pca.issue-certificate: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7ff6757698e0>>
2022-06-06 11:49:53,396 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.acm-pca.issue-certificate: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7ff675769970>>
2022-06-06 11:49:53,397 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.acm-pca.issue-certificate.api-passthrough: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7ff67564c4c0>
2022-06-06 11:49:53,398 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.acm-pca.issue-certificate: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7ff67510b0d0>
2022-06-06 11:49:53,398 - MainThread - awscli.argprocess - DEBUG - Parsing param --api-passthrough as shorthand
2022-06-06 11:49:53,398 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/clidriver.py", line 458, in main
  File "awscli/clidriver.py", line 593, in __call__
  File "awscli/clidriver.py", line 741, in __call__
  File "awscli/clidriver.py", line 799, in _build_call_parameters
  File "awscli/arguments.py", line 453, in add_to_params
  File "awscli/arguments.py", line 461, in _unpack_argument
  File "awscli/arguments.py", line 476, in _emit_first_response
  File "awscli/arguments.py", line 473, in _emit
  File "awscli/botocore/hooks.py", line 228, in emit
  File "awscli/botocore/hooks.py", line 211, in _emit
  File "awscli/argprocess.py", line 327, in __call__
  File "awscli/argprocess.py", line 349, in _parse_as_shorthand
  File "awscli/shorthand.py", line 172, in parse
  File "awscli/shorthand.py", line 177, in _parameter
  File "awscli/shorthand.py", line 195, in _keyval
  File "awscli/shorthand.py", line 205, in _key
TypeError: 'in <string>' requires string as left operand, not int

'in <string>' requires string as left operand, not int
```

### Reproduction Steps

AWS Documentation [here](https://docs.aws.amazon.com/acm-pca/latest/userguide/PcaIssueCert.html#custom-subject-2) 

```
> aws acm-pca issue-certificate \
>       --validity Type=DAYS,Value=10 \
>       --signing-algorithm "SHA256WITHRSA" \
>       --csr fileb://csr.pem \
>       --api-passthrough fileb://extensions.txt \
>       --template-arn arn:aws:acm-pca:::template/EndEntityCertificate_APIPassthrough/V1 \
>       --certificate-authority-arn arn:aws:acm-pca:[REGION]:[ACCOUNT]:certificate-authority/[PCA_ID]
```

### CLI version used

2.7.6

### Environment details (OS name and version, etc.)

macOS 12.3.1 aws-cli/2.7.6 Python/3.9.11 Darwin/21.4.0 exe/x86_64 prompt/off

**Comment by tim-finnigan** [comment]
Hi @tomasclemente thanks for reaching out. Does it work if you use `file://extensions.txt` instead of `fileb://extensions.txt`? I wonder if it's an encoding issue causing the error here.

**Comment by tim-finnigan** [comment]
Since we haven't heard back in a few weeks I'm going to close this. If you're still experiencing this issue please let us know.
