### ISSUE TITLE
aws eks get-token doesn't work with --profile

### ISSUE THREAD

**Issue by DaazKu** [aws/aws-cli#7374]
### Describe the bug

After setting up `.kube/config` using `eks update-kubeconfig --profile` the profile is not honoured by `aws eks get-token`

### Expected Behavior

Everything should work without having to manually pass the profile.

### Current Behavior

We get the following error:
```
Unable to locate credentials. You can configure credentials by running "aws configure".
```

Logs with not `AWS_PROFILE={PROFILE}`
```
2022-10-27 13:21:11,686 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.8.5 Python/3.10.8 Darwin/21.6.0 source/arm64
2022-10-27 13:21:11,686 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['eks', 'get-token', '--debug', '--cluster-name', 'dev']
2022-10-27 13:21:11,694 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x104c45e10>
2022-10-27 13:21:11,694 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x104807a30>
2022-10-27 13:21:11,694 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2022-10-27 13:21:11,694 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x1047adcf0>
2022-10-27 13:21:11,694 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x1047aec20>
2022-10-27 13:21:11,694 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x104c5c790>
2022-10-27 13:21:11,694 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x104add510>
2022-10-27 13:21:11,694 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2022-10-27 13:21:11,694 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x104c479a0>
2022-10-27 13:21:11,694 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/data/cli.json
2022-10-27 13:21:11,695 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x104ba0d30>
2022-10-27 13:21:11,695 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x104ba1870>
2022-10-27 13:21:11,695 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x104ba17e0>
2022-10-27 13:21:11,695 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x104ba1990>
2022-10-27 13:21:11,695 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x104ba1900>
2022-10-27 13:21:11,695 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x104cfd900>
2022-10-27 13:21:11,696 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.8.5 Python/3.10.8 Darwin/21.6.0 source/arm64 prompt/off
2022-10-27 13:21:11,696 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['eks', 'get-token', '--debug', '--cluster-name', 'dev']
2022-10-27 13:21:11,696 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x104c46440>
2022-10-27 13:21:11,696 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x104511fc0>
2022-10-27 13:21:11,696 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x104cb6710>
2022-10-27 13:21:11,696 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x1044e7370>
2022-10-27 13:21:11,696 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x10455aa70>
2022-10-27 13:21:11,697 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2022-10-27 13:21:11,701 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x104add3f0>
2022-10-27 13:21:11,701 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x104806950>
2022-10-27 13:21:11,708 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/botocore/data/eks/2017-11-01/service-2.json
2022-10-27 13:21:11,709 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/botocore/data/eks/2017-11-01/service-2.sdk-extras.json
2022-10-27 13:21:11,711 - MainThread - botocore.hooks - DEBUG - Event building-command-table.eks: calling handler <function inject_commands at 0x104b61750>
2022-10-27 13:21:11,711 - MainThread - botocore.hooks - DEBUG - Event building-command-table.eks: calling handler <function add_waiters at 0x104c479a0>
2022-10-27 13:21:11,718 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/botocore/data/eks/2017-11-01/waiters-2.json
2022-10-27 13:21:11,718 - MainThread - botocore.hooks - DEBUG - Event building-command-table.eks_get-token: calling handler <function add_waiters at 0x104c479a0>
2022-10-27 13:21:11,719 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.get-token.cluster-name: calling handler <awscli.paramfile.URIArgumentHandler object at 0x104d23310>
2022-10-27 13:21:11,719 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.get-token: calling handler <awscli.argprocess.ParamShorthandParser object at 0x1044f7c70>
2022-10-27 13:21:11,719 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.get-token.role-arn: calling handler <awscli.paramfile.URIArgumentHandler object at 0x104d23310>
2022-10-27 13:21:11,719 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.get-token.cluster-id: calling handler <awscli.paramfile.URIArgumentHandler object at 0x104d23310>
2022-10-27 13:21:11,719 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2022-10-27 13:21:11,719 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2022-10-27 13:21:11,721 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2022-10-27 13:21:11,723 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2022-10-27 13:21:11,723 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2022-10-27 13:21:11,723 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: custom-process
2022-10-27 13:21:11,723 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: config-file
2022-10-27 13:21:11,723 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: ec2-credentials-file
2022-10-27 13:21:11,723 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: boto-config
2022-10-27 13:21:11,723 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: container-role
2022-10-27 13:21:11,723 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: iam-role
...
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://169.254.169.254/latest/meta-data/iam/security-credentials/"
2022-10-27 13:21:11,759 - MainThread - botocore.utils - DEBUG - Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
2022-10-27 13:21:11,759 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/botocore/data/endpoints.json
2022-10-27 13:21:11,764 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x10385c550>
2022-10-27 13:21:11,765 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/botocore/data/sts/2011-06-15/service-2.json
2022-10-27 13:21:11,765 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.sts: calling handler <function add_generate_presigned_url at 0x1037b3f40>
2022-10-27 13:21:11,769 - MainThread - botocore.endpoint - DEBUG - Setting sts timeout as (60, 60)
2022-10-27 13:21:11,770 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.sts.GetCallerIdentity: calling handler <bound method STSClientFactory._retrieve_k8s_aws_id of <awscli.customizations.eks.get_token.STSClientFactory object at 0x104e2a680>>
2022-10-27 13:21:11,770 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.sts.GetCallerIdentity: calling handler <function base64_decode_input_blobs at 0x104cb6e60>
2022-10-27 13:21:11,770 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.sts.GetCallerIdentity: calling handler <function generate_idempotent_uuid at 0x10385e5f0>
2022-10-27 13:21:11,771 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sts.GetCallerIdentity: calling handler <function set_operation_specific_signer at 0x10385e4d0>
2022-10-27 13:21:11,771 - MainThread - botocore.hooks - DEBUG - Event before-sign.sts.GetCallerIdentity: calling handler <bound method STSClientFactory._inject_k8s_aws_id_header of <awscli.customizations.eks.get_token.STSClientFactory object at 0x104e2a680>>
2022-10-27 13:21:11,771 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/clidriver.py", line 458, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/clidriver.py", line 593, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/customizations/commands.py", line 191, in __call__
    rc = self._run_main(parsed_args, parsed_globals)
  File "/opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/customizations/eks/get_token.py", line 128, in _run_main
    token = TokenGenerator(sts_client).get_token(identifier)
  File "/opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/customizations/eks/get_token.py", line 217, in get_token
    url = self._get_presigned_url(k8s_aws_id)
  File "/opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/customizations/eks/get_token.py", line 224, in _get_presigned_url
    return self._sts_client.generate_presigned_url(
  File "/opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/botocore/signers.py", line 610, in generate_presigned_url
    return request_signer.generate_presigned_url(
  File "/opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/botocore/signers.py", line 284, in generate_presigned_url
    self.sign(operation_name, request, region_name,
  File "/opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/botocore/signers.py", line 166, in sign
    auth.add_auth(request)
  File "/opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/botocore/auth.py", line 398, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

Logs with `AWS_PROFILE={PROFILE}`
```
2022-10-27 13:22:47,116 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.8.5 Python/3.10.8 Darwin/21.6.0 source/arm64
2022-10-27 13:22:47,116 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['eks', 'get-token', '--debug', '--cluster-name', 'dev']
2022-10-27 13:22:47,125 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x106fb5e10>
2022-10-27 13:22:47,125 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x106b77a30>
2022-10-27 13:22:47,125 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2022-10-27 13:22:47,126 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x106b1dcf0>
2022-10-27 13:22:47,126 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x106b1ec20>
2022-10-27 13:22:47,126 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x106fcc790>
2022-10-27 13:22:47,126 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x106e4d510>
2022-10-27 13:22:47,126 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2022-10-27 13:22:47,126 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x106fb79a0>
2022-10-27 13:22:47,126 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/data/cli.json
2022-10-27 13:22:47,127 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x106f10d30>
2022-10-27 13:22:47,127 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x106f11870>
2022-10-27 13:22:47,127 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x106f117e0>
2022-10-27 13:22:47,127 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x106f11990>
2022-10-27 13:22:47,127 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x106f11900>
2022-10-27 13:22:47,127 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x10706d580>
2022-10-27 13:22:47,127 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.8.5 Python/3.10.8 Darwin/21.6.0 source/arm64 prompt/off
2022-10-27 13:22:47,127 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['eks', 'get-token', '--debug', '--cluster-name', 'dev']
2022-10-27 13:22:47,127 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x106fb6440>
2022-10-27 13:22:47,127 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x106881fc0>
2022-10-27 13:22:47,127 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x107026710>
2022-10-27 13:22:47,127 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x106857370>
2022-10-27 13:22:47,127 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x1068caa70>
2022-10-27 13:22:47,128 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2022-10-27 13:22:47,132 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x106e4d3f0>
2022-10-27 13:22:47,132 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x106b76950>
2022-10-27 13:22:47,139 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/botocore/data/eks/2017-11-01/service-2.json
2022-10-27 13:22:47,140 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/botocore/data/eks/2017-11-01/service-2.sdk-extras.json
2022-10-27 13:22:47,142 - MainThread - botocore.hooks - DEBUG - Event building-command-table.eks: calling handler <function inject_commands at 0x106ed1750>
2022-10-27 13:22:47,142 - MainThread - botocore.hooks - DEBUG - Event building-command-table.eks: calling handler <function add_waiters at 0x106fb79a0>
2022-10-27 13:22:47,149 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/botocore/data/eks/2017-11-01/waiters-2.json
2022-10-27 13:22:47,150 - MainThread - botocore.hooks - DEBUG - Event building-command-table.eks_get-token: calling handler <function add_waiters at 0x106fb79a0>
2022-10-27 13:22:47,150 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.get-token.cluster-name: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1070932e0>
2022-10-27 13:22:47,150 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.get-token: calling handler <awscli.argprocess.ParamShorthandParser object at 0x1068a41f0>
2022-10-27 13:22:47,150 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.get-token.role-arn: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1070932e0>
2022-10-27 13:22:47,150 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.get-token.cluster-id: calling handler <awscli.paramfile.URIArgumentHandler object at 0x1070932e0>
2022-10-27 13:22:47,151 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2022-10-27 13:22:47,151 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2022-10-27 13:22:47,151 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2022-10-27 13:22:47,151 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2022-10-27 13:22:47,151 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/botocore/data/endpoints.json
2022-10-27 13:22:47,155 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x105bcc550>
2022-10-27 13:22:47,156 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/awscli/botocore/data/sts/2011-06-15/service-2.json
2022-10-27 13:22:47,156 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.sts: calling handler <function add_generate_presigned_url at 0x105b23f40>
2022-10-27 13:22:47,175 - MainThread - botocore.endpoint - DEBUG - Setting sts timeout as (60, 60)
2022-10-27 13:22:47,176 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.sts.GetCallerIdentity: calling handler <bound method STSClientFactory._retrieve_k8s_aws_id of <awscli.customizations.eks.get_token.STSClientFactory object at 0x1071926e0>>
2022-10-27 13:22:47,176 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.sts.GetCallerIdentity: calling handler <function base64_decode_input_blobs at 0x107026e60>
2022-10-27 13:22:47,176 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.sts.GetCallerIdentity: calling handler <function generate_idempotent_uuid at 0x105bce5f0>
2022-10-27 13:22:47,176 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sts.GetCallerIdentity: calling handler <function set_operation_specific_signer at 0x105bce4d0>
2022-10-27 13:22:47,176 - MainThread - botocore.hooks - DEBUG - Event before-sign.sts.GetCallerIdentity: calling handler <bound method STSClientFactory._inject_k8s_aws_id_header of <awscli.customizations.eks.get_token.STSClientFactory object at 0x1071926e0>>
2022-10-27 13:22:47,176 - MainThread - botocore.credentials - DEBUG - Credentials for role retrieved from cache.
2022-10-27 13:22:47,176 - MainThread - botocore.credentials - DEBUG - Retrieved credentials will expire at: 2022-10-27 20:59:14+00:00
2022-10-27 13:22:47,177 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2022-10-27 13:22:47,177 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
GET
/
Action=GetCallerIdentity&Version=2011-06-15&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-.....
...
{"kind": "ExecCredential", "apiVersion": "client.authentication.k8s.io/v1beta1", "spec": {}, "status": {"expirationTimestamp": "2022-10-27T17:36:47Z", "token": "k8s-aws-v1.aHR0cHM6Ly9zdHMuY2EtY...
```

### Reproduction Steps

```
# Setting it up
$ aws eks update-kubeconfig --name dev --profile dev_admin_user
Added new context arn:aws:eks:ca-central-1:{ACCOUNT_ID}:cluster/dev to /Users/alexandre/.kube/config

# Trying to use it
$ aws eks get-token --cluster-name dev                         
Unable to locate credentials. You can configure credentials by running "aws configure".

# Manually passing the profile
$ AWS_PROFILE="dev_admin_user" aws eks get-token --cluster-name dev                                                                 
{"kind": "ExecCredential", "apiVersion": "client.authentication.k8s.io/v1beta1", "spec": {}, "status": {"expirationTimestamp": "2022-10-27T17:27:23Z", "token": "k8s-aws-v1.aHR0cHM6Ly9..."}}
 ```

### Additional Information/Context

Basically same problem as https://github.com/aws/aws-cli/issues/4163 but it's on the newer version of `aws-cli`

Content of `~/.kube/config`
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CR...
  name: arn:aws:eks:ca-central-1:721246126555:cluster/dev
contexts:
- context:
    cluster: arn:aws:eks:ca-central-1:{ACCOUNT_ID}:cluster/dev
    user: arn:aws:eks:ca-central-1:{ACCOUNT_ID}:cluster/dev
  name: arn:aws:eks:ca-central-1:{ACCOUNT_ID}:cluster/dev
current-context: arn:aws:eks:ca-central-1:{ACCOUNT_ID}:cluster/dev
kind: Config
preferences: {}
users:
- name: arn:aws:eks:ca-central-1:{ACCOUNT_ID}:cluster/dev
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - ca-central-1
      - eks
      - get-token
      - --cluster-name
      - dev
      command: aws
      env:
      - name: AWS_PROFILE
        value: dev_admin_user
```

### CLI version used

aws-cli/2.8.5 Python/3.10.8 Darwin/21.6.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

MacOS 12.5 & Apple M1

**Comment by DaazKu** [comment]
Nvm got confused and thought we did not have to use --profile on the command :)
