### ISSUE TITLE
Could not connect to the [route53domains] endpoint URL

### ISSUE THREAD

**Issue by MRO60** [aws/aws-cli#7415]
### Describe the bug

Properly built requests, like: 
`aws route53domains update-domain-nameservers ...`
and 
`aws route53domains retrieve-domain-auth-code --domain ...`

Return no errors except:  Could not connect to the endpoint URL: ""https://route53domains.us-west-2.amazonaws.com/"

health.aws.amazonaws.com reports no issue for route53

### Expected Behavior

An execution of:
`aws route53domains update-domain-nameservers --region us-west-2 --cli-input-json file://my-file.json --generate-cli-skeleton output`

that returns

`{
    "OperationId": "OperationId"
}`

should execute when the --generate-cli-skeleton output is removed

### Current Behavior

Instead, the above command returns:

Outout:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 217, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 358, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 527, in __call__
    return self._operation_caller.invoke(
  File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 649, in invoke
    response = self._make_client_call(
  File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 661, in _make_client_call
    response = getattr(client, xform_name(operation_name))(
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 662, in _make_api_call
    http, parsed_response = self._make_request(
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 682, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/lib/python3/dist-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/lib/python3/dist-packages/botocore/endpoint.py", line 136, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "/usr/lib/python3/dist-packages/botocore/endpoint.py", line 253, in _needs_retry
    responses = self._event_emitter.emit(
  File "/usr/lib/python3/dist-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/lib/python3/dist-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/lib/python3/dist-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/lib/python3/dist-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/lib/python3/dist-packages/botocore/retryhandler.py", line 250, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "/usr/lib/python3/dist-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/lib/python3/dist-packages/botocore/retryhandler.py", line 316, in __call__
    checker_response = checker(attempt_number, response,
  File "/usr/lib/python3/dist-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(
  File "/usr/lib/python3/dist-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/usr/lib/python3/dist-packages/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/usr/lib/python3/dist-packages/botocore/endpoint.py", line 269, in _send
    return self.http_session.send(request)
  File "/usr/lib/python3/dist-packages/botocore/httpsession.py", line 337, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://route53domains.us-west-2.amazonaws.com/"
2022-11-08 13:45:14,642 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Could not connect to the endpoint URL: "https://route53domains.us-west-2.amazonaws.com/"

### Reproduction Steps

aws route53domains retrieve-domain-auth-code --domain  [your-domain-here]

Returns the same error.

In my `aws route53domains update-domain-nameservers --region us-west-2 --cli-input-json file://my-file.json` request the domain registrar is AWS Route53 and it is already being hosted. The my-file.json are glue records.

### CLI version used

1.19.1

### Environment details (OS name and version, etc.)

Debian Stretch Python/3.9.2 Linux/5.10.0-18-amd64 botocore/1.20.0

**Comment by tim-finnigan** [comment]
Hi @MRO60 thanks for reaching out. That error is likely occurring because the route53domains service requires you to use the `us-east-1` region and you're using `us-west-2` here. That requirement is documented [here](https://docs.aws.amazon.com/general/latest/gr/r53.html#r53_region_) in the service endpoints section as well as on documentation pages for commands such as the one you used ([retrieve-domain-auth-code](https://docs.aws.amazon.com/cli/latest/reference/route53domains/retrieve-domain-auth-code.html)). There is already another issue (https://github.com/aws/aws-cli/issues/5370) opened regarding confusion around this behavior. Please refer to that issue for updates going forward. And if using `us-east-1` does not resolve the issue for you please let us know here.

**Comment by MRO60** [comment]
Re-visited this today: Your solution did not change anything.

I replace the option value to: --region us-west-1 
I got the exact same results in my OP.

**Comment by MRO60** [comment]
Woops!!
My bad.  I changed us-west-1 to us-east-1 and it worked.  
THANKS!
Sorry I missed that in the docs.
