### ISSUE TITLE
Homebrew 2.9.7 generates exception about not finding the `docutils` Python package

### ISSUE THREAD

**Issue by asieira** [aws/aws-cli#7535]
### Describe the bug

When I install and try to run commands using AWS CLI v2.9.7 via homebrew on a Mac I get a ModuleNotFoundError related to `docutils`.

### Expected Behavior

No exceptions should happen. :)

### Current Behavior

An exception is thrown and the command is not executed.

### Reproduction Steps

```
| => uname -a
Darwin Alexandres-MBP 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64

| => brew reinstall awscli
==> Fetching awscli
==> Downloading https://ghcr.io/v2/homebrew/core/awscli/manifests/2.9.7
Already downloaded: /Users/asieira/Library/Caches/Homebrew/downloads/9db1303bfe04588bf8289afbb3c53454f8bb830401e63144719e7ca737061635--awscli-2.9.7.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/awscli/blobs/sha256:18bf522e5b92e1feab9f77393000a54813471614d951e269d546a9fdce081e6c
Already downloaded: /Users/asieira/Library/Caches/Homebrew/downloads/c007c3dbda50d3b7db39fd8eaf72f307cdbe07e69408a7244f7f314195eed1d7--awscli--2.9.7.ventura.bottle.tar.gz
==> Reinstalling awscli
==> Pouring awscli--2.9.7.ventura.bottle.tar.gz
==> Caveats
The "examples" directory has been installed to:
  /usr/local/share/awscli/examples

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/awscli/2.9.7: 12,993 files, 113.0MB
==> Running `brew cleanup awscli`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

| => aws --profile <REDACTED> --region us-east-2 rds describe-db-clusters --db-cluster-identifier <REDACTED>
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/Cellar/awscli/2.9.7/libexec/lib/python3.11/site-packages/awscli/clidriver.py", line 43, in <module>
    from awscli.help import ProviderHelpCommand
  File "/usr/local/Cellar/awscli/2.9.7/libexec/lib/python3.11/site-packages/awscli/help.py", line 20, in <module>
    from docutils.core import publish_string
ModuleNotFoundError: No module named 'docutils'
```

### Possible Solution

Seems like `docutils` is required but was not bundled with the homebrew bottle. Including it (and any other missing direct and indirect dependencies) should fix this.
```
| => pwd
/usr/local/Cellar/awscli/2.9.7/libexec/lib/python3.11/site-packages

| => ls -la
total 3296
drwxr-xr-x  42 asieira  admin     1344 Dec 19 09:37 .
drwxr-xr-x   3 asieira  admin       96 Dec 14 14:37 ..
drwxr-xr-x   3 asieira  admin       96 Dec 19 09:37 __pycache__
-rwxr-xr-x   1 asieira  admin  1116152 Dec 14 14:37 _awscrt.cpython-311-darwin.so
-rwxr-xr-x   1 asieira  admin   176776 Dec 14 14:37 _cffi_backend.cpython-311-darwin.so
drwxr-xr-x   5 asieira  admin      160 Dec 19 09:37 _distutils_hack
-rwxr-xr-x   1 asieira  admin   330512 Dec 14 14:37 _ruamel_yaml.cpython-311-darwin.so
drwxr-xr-x  37 asieira  admin     1184 Dec 19 09:37 awscli
drwxr-xr-x   9 asieira  admin      288 Dec 19 09:33 awscli-2.9.7.dist-info
drwxr-xr-x  15 asieira  admin      480 Dec 19 09:37 awscrt
drwxr-xr-x   7 asieira  admin      224 Dec 14 14:37 awscrt-0.14.0-py3.11.egg-info
drwxr-xr-x  22 asieira  admin      704 Dec 14 14:37 cffi
drwxr-xr-x  10 asieira  admin      320 Dec 14 14:37 cffi-1.15.1-py3.11.egg-info
drwxr-xr-x   9 asieira  admin      288 Dec 19 09:37 colorama
drwxr-xr-x   7 asieira  admin      224 Dec 14 14:37 colorama-0.4.3-py3.11.egg-info
drwxr-xr-x  10 asieira  admin      320 Dec 14 14:37 cryptography
drwxr-xr-x  13 asieira  admin      416 Dec 14 14:37 cryptography-38.0.1.dist-info
drwxr-xr-x  14 asieira  admin      448 Dec 19 09:37 dateutil
drwxr-xr-x   8 asieira  admin      256 Dec 14 14:37 distro-1.5.0-py3.11.egg-info
-rw-r--r--   1 asieira  admin    43628 Dec 14 14:37 distro.py
-rw-r--r--   1 asieira  admin      151 Dec 14 14:37 distutils-precedence.pth
-rw-r--r--   1 asieira  admin      165 Dec 19 09:33 homebrew_deps.pth
drwxr-xr-x  11 asieira  admin      352 Dec 19 09:37 jmespath
drwxr-xr-x   7 asieira  admin      224 Dec 14 14:37 jmespath-1.0.1-py3.11.egg-info
drwxr-xr-x   8 asieira  admin      256 Dec 14 14:37 pip
drwxr-xr-x  10 asieira  admin      320 Dec 14 14:37 pip-22.3.dist-info
drwxr-xr-x   5 asieira  admin      160 Dec 14 14:37 pkg_resources
drwxr-xr-x  38 asieira  admin     1216 Dec 14 14:37 prompt_toolkit
drwxr-xr-x  11 asieira  admin      352 Dec 14 14:37 prompt_toolkit-3.0.28.dist-info
drwxr-xr-x  15 asieira  admin      480 Dec 14 14:37 pycparser
drwxr-xr-x   7 asieira  admin      224 Dec 14 14:37 pycparser-2.21-py3.11.egg-info
drwxr-xr-x  11 asieira  admin      352 Dec 14 14:37 python_dateutil-2.8.2.dist-info
drwxr-xr-x   3 asieira  admin       96 Dec 14 14:37 ruamel
-rw-r--r--   1 asieira  admin      539 Dec 14 14:37 ruamel.yaml-0.17.21-py3.11-nspkg.pth
drwxr-xr-x   9 asieira  admin      288 Dec 14 14:37 ruamel.yaml-0.17.21-py3.11.egg-info
drwxr-xr-x   8 asieira  admin      256 Dec 14 14:37 ruamel.yaml.clib-0.2.7-py3.11.egg-info
drwxr-xr-x  47 asieira  admin     1504 Dec 14 14:37 setuptools
drwxr-xr-x  10 asieira  admin      320 Dec 14 14:37 setuptools-65.5.0.dist-info
drwxr-xr-x  17 asieira  admin      544 Dec 19 09:37 urllib3
drwxr-xr-x   8 asieira  admin      256 Dec 14 14:37 urllib3-1.26.12-py3.11.egg-info
drwxr-xr-x   7 asieira  admin      224 Dec 14 14:37 wcwidth
drwxr-xr-x   8 asieira  admin      256 Dec 14 14:37 wcwidth-0.1.9-py3.11.egg-info
```

### CLI version used

2.9.7

### Environment details (OS name and version, etc.)

Mac OS X Ventura 13.0.1 (Intel).

**Comment by asieira** [comment]
Was able to resolve it by running `brew reinstall docutils; brew link --overwrite docutils`.
