### ISSUE TITLE
SageMaker Exception on valid request parameters

### ISSUE THREAD

**Issue by ayberkhalacc** [aws/aws-cli#7592]
### Describe the bug

`Unknown parameter in AlgorithmSpecification: "ContainerEntrypoint", must be one of: TrainingImage, AlgorithmName, TrainingInputMode, MetricDefinitions, EnableSageMakerMetricsTimeSeries
Unknown parameter in AlgorithmSpecification: "ContainerArguments", must be one of: TrainingImage, AlgorithmName, TrainingInputMode, MetricDefinitions, EnableSageMakerMetricsTimeSeries`

https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateTrainingJob.html

### Expected Behavior

Run without failure

### Current Behavior

Exception:
`Unknown parameter in AlgorithmSpecification: "ContainerEntrypoint", must be one of: TrainingImage, AlgorithmName, TrainingInputMode, MetricDefinitions, EnableSageMakerMetricsTimeSeries
Unknown parameter in AlgorithmSpecification: "ContainerArguments", must be one of: TrainingImage, AlgorithmName, TrainingInputMode, MetricDefinitions, EnableSageMakerMetricsTimeSeries`

### Reproduction Steps

`aws sagemaker create-training-job --training-job-name red --resource-config '{"InstanceCount": 1,"InstanceType": "ml.m4.4xlarge","VolumeSizeInGB": 50}' --algorithm-specification '{"ContainerEntrypoint":"[\"sh\", \"-c\"]", "ContainerArguments":"[\"curl x"]","TrainingImage":"x.dkr.ecr.us-east-1.amazonaws.com/ayberk:latest", "TrainingInputMode": "Pipe"}' --role-arn arn:aws:iam::x:role/assumeroletest --output-data-confi '{"S3OutputPath":"s3://test"}' --stopping-condition '{"MaxRuntimeInSeconds": 600}'

Parameter validation failed:
Unknown parameter in AlgorithmSpecification: "ContainerEntrypoint", must be one of: TrainingImage, AlgorithmName, TrainingInputMode, MetricDefinitions, EnableSageMakerMetricsTimeSeries
Unknown parameter in AlgorithmSpecification: "ContainerArguments", must be one of: TrainingImage, AlgorithmName, TrainingInputMode, MetricDefinitions, EnableSageMakerMetricsTimeSeries`

### CLI version used

latest

### Environment details (OS name and version, etc.)

MACOS

**Comment by tim-finnigan** [comment]
Hi @ayberkhalacc thanks for reaching out. As mentioned [here](https://github.com/boto/boto3/issues/3560#issuecomment-1385781112), both boto3 and the AWS CLI share the same service models for APIs like [CreateTrainingJob](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateTrainingJob.html), so these issues are related. 

Can you share your debug logs (with any sensitive info redacted) by adding `--debug` to your command? That will help us confirm the issue and see if we need to escalate this to the SageMaker team.

**Comment by ayberkhalacc** [comment]
Hello @tim-finnigan,
`2023-01-18 10:06:31,747 - MainThread - botocore.hooks - DEBUG - Event calling-command.sagemaker.create-training-job: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7fdb82fbd310>>
2023-01-18 10:06:31,747 - MainThread - botocore.hooks - DEBUG - Event calling-command.sagemaker.create-training-job: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7fdb82fbd340>>
2023-01-18 10:06:31,748 - MainThread - botocore.hooks - DEBUG - Event calling-command.sagemaker.create-training-job: calling handler <bound method GenerateCliSkeletonArgument.generate_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fdb82fbd3d0>>
2023-01-18 10:06:31,748 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2023-01-18 10:06:31,748 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2023-01-18 10:06:31,748 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2023-01-18 10:06:31,748 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2023-01-18 10:06:31,748 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2023-01-18 10:06:31,749 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2023-01-18 10:06:31,750 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/botocore/data/endpoints.json
2023-01-18 10:06:31,760 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7fdb7fcb1550>
2023-01-18 10:06:31,766 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.sagemaker: calling handler <function add_generate_presigned_url at 0x7fdb7fc36d30>
2023-01-18 10:06:31,768 - MainThread - botocore.endpoint - DEBUG - Setting api.sagemaker timeout as (60, 60)
2023-01-18 10:06:31,769 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.sagemaker.CreateTrainingJob: calling handler <function base64_decode_input_blobs at 0x7fdb81d191f0>
2023-01-18 10:06:31,769 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.sagemaker.CreateTrainingJob: calling handler <function generate_idempotent_uuid at 0x7fdb7fccb550>
2023-01-18 10:06:31,769 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/clidriver.py", line 458, in main
  File "awscli/clidriver.py", line 593, in __call__
  File "awscli/clidriver.py", line 769, in __call__
  File "awscli/clidriver.py", line 900, in invoke
  File "awscli/clidriver.py", line 912, in _make_client_call
  File "awscli/botocore/client.py", line 304, in _api_call
  File "awscli/botocore/client.py", line 604, in _make_api_call
  File "awscli/botocore/client.py", line 654, in _convert_to_request_dict
  File "awscli/botocore/validate.py", line 336, in serialize_to_request
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in AlgorithmSpecification: "ContainerEntrypoint", must be one of: TrainingImage, AlgorithmName, TrainingInputMode, MetricDefinitions, EnableSageMakerMetricsTimeSeries
Unknown parameter in AlgorithmSpecification: "ContainerArguments", must be one of: TrainingImage, AlgorithmName, TrainingInputMode, MetricDefinitions, EnableSageMakerMetricsTimeSeries

Parameter validation failed:
Unknown parameter in AlgorithmSpecification: "ContainerEntrypoint", must be one of: TrainingImage, AlgorithmName, TrainingInputMode, MetricDefinitions, EnableSageMakerMetricsTimeSeries
Unknown parameter in AlgorithmSpecification: "ContainerArguments", must be one of: TrainingImage, AlgorithmName, TrainingInputMode, MetricDefinitions, EnableSageMakerMetricsTimeSeries`

**Comment by tim-finnigan** [comment]
Hi @ayberkhalacc thanks for following up. It looks like `ContainerEntrypoint` and `ContainerArguments` were just added 3 months ago in [this commit](https://github.com/boto/botocore/commit/07a03ec7cc953a9b2d95c5eb9f7972ebda6bb5dc). That would have been in version [1.28.3](https://github.com/boto/botocore/blob/develop/CHANGELOG.rst#1283) of botocore and 2.8.7 of the AWS CLI. Can you please confirm that you are using those versions or above and try running the command again?
