### ISSUE TITLE
Python error running ec2 describe-images command

### ISSUE THREAD

**Issue by rafaelpereyra** [aws/aws-cli#7698]
### Describe the bug

I'm having issues calling aws cli to describe a list of images in my account.

This simple command is failing and only returns `next-token`

```
❯ aws ec2 describe-images --owner amazon

'next-token'
```

### Expected Behavior

A list of images in my account.

### Current Behavior

```
# aws --version
aws-cli/2.10.1 Python/3.11.2 Darwin/22.3.0 source/x86_64 prompt/off

$ aws ec2 describe-images --owner amazon

'next-token'


$ aws ec2 describe-images --owner amazon --debug
2023-02-22 20:42:50,841 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.10.1 Python/3.11.2 Darwin/22.3.0 source/x86_64
2023-02-22 20:42:50,841 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['ec2', 'describe-images', '--owner', 'amazon', '--debug']
2023-02-22 20:42:50,881 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x10adb1da0>
2023-02-22 20:42:50,881 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x10a92d120>
2023-02-22 20:42:50,881 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2023-02-22 20:42:50,882 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x10a8a1c60>
2023-02-22 20:42:50,882 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x10a8a32e0>
2023-02-22 20:42:50,882 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x10adc1940>
2023-02-22 20:42:50,882 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x10ac30b80>
2023-02-22 20:42:50,882 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2023-02-22 20:42:50,882 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x10adc0900>
2023-02-22 20:42:50,882 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x10ae6dc50>>
2023-02-22 20:42:50,883 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.10.1/libexec/lib/python3.11/site-packages/awscli/data/cli.json
2023-02-22 20:42:50,885 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x10acf53a0>
2023-02-22 20:42:50,885 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x10acf56c0>
2023-02-22 20:42:50,885 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x10acf5620>
2023-02-22 20:42:50,885 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x10acf5800>
2023-02-22 20:42:50,885 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x10acf5760>
2023-02-22 20:42:50,885 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x10ae6af80>
2023-02-22 20:42:50,885 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.10.1 Python/3.11.2 Darwin/22.3.0 source/x86_64 prompt/off
2023-02-22 20:42:50,886 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['ec2', 'describe-images', '--owner', 'amazon', '--debug']
2023-02-22 20:42:50,886 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x10adb2980>
2023-02-22 20:42:50,886 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x10a5ddf80>
2023-02-22 20:42:50,886 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x10ae27600>
2023-02-22 20:42:50,886 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x10a5be7a0>
2023-02-22 20:42:50,886 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x10a623f60>
2023-02-22 20:42:50,893 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2023-02-22 20:42:50,901 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x10ac30360>
2023-02-22 20:42:50,901 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x10a91d120>
2023-02-22 20:42:50,942 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/rapg/.aws/models/ec2/2016-11-15/service-2.json
2023-02-22 20:42:50,998 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler functools.partial(<function _remove_commands at 0x10ad1de40>, commands_to_remove=['import-instance', 'import-volume'])
2023-02-22 20:42:50,998 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-instance
2023-02-22 20:42:50,998 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-volume
2023-02-22 20:42:50,998 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <function add_waiters at 0x10adc0900>
2023-02-22 20:42:51,033 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.10.1/libexec/lib/python3.11/site-packages/awscli/botocore/data/ec2/2016-11-15/waiters-2.json
2023-02-22 20:42:51,034 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x10ae6dc50>>
2023-02-22 20:42:51,035 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('executable-users', <awscli.arguments.ListArgument object at 0x10b87e8d0>), ('filters', <awscli.arguments.ListArgument object at 0x10b87e9d0>), ('image-ids', <awscli.arguments.ListArgument object at 0x10b87eb10>), ('owners', <awscli.arguments.ListArgument object at 0x10b87ec10>), ('dry-run', <awscli.arguments.BooleanArgument object at 0x10b87ed10>), ('no-dry-run', <awscli.arguments.BooleanArgument object at 0x10b5941d0>)])
2023-02-22 20:42:51,035 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-images: calling handler <function add_streaming_output_arg at 0x10adb2fc0>
2023-02-22 20:42:51,035 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-images: calling handler <function rename_arg.<locals>._rename_arg at 0x10ae3c360>
2023-02-22 20:42:51,035 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-images: calling handler <function rename_arg.<locals>._rename_arg at 0x10ae3c400>
2023-02-22 20:42:51,035 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-images: calling handler functools.partial(<function pull_up_bool at 0x10adc0040>, event_handler=<botocore.hooks.HierarchicalEmitter object at 0x10a5d3210>)
2023-02-22 20:42:51,036 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-images: calling handler <function add_cli_input_json at 0x10a640a40>
2023-02-22 20:42:51,038 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-images: calling handler <function add_cli_input_yaml at 0x10a640cc0>
2023-02-22 20:42:51,038 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-images: calling handler <function unify_paging_params at 0x10a92d9e0>
2023-02-22 20:42:51,080 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.10.1/libexec/lib/python3.11/site-packages/awscli/botocore/data/ec2/2016-11-15/paginators-1.json
2023-02-22 20:42:51,081 - MainThread - awscli.customizations.paginate - DEBUG - Modifying paging parameters for operation: DescribeImages
2023-02-22 20:42:51,081 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/Cellar/awscli/2.10.1/libexec/lib/python3.11/site-packages/awscli/clidriver.py", line 460, in main
    return command_table[parsed_args.command](remaining, parsed_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/awscli/2.10.1/libexec/lib/python3.11/site-packages/awscli/clidriver.py", line 595, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/awscli/2.10.1/libexec/lib/python3.11/site-packages/awscli/clidriver.py", line 746, in __call__
    self._emit(event, argument_table=self.arg_table, args=args,
                                     ^^^^^^^^^^^^^^
  File "/usr/local/Cellar/awscli/2.10.1/libexec/lib/python3.11/site-packages/awscli/clidriver.py", line 732, in arg_table
    self._arg_table = self._create_argument_table()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/awscli/2.10.1/libexec/lib/python3.11/site-packages/awscli/clidriver.py", line 865, in _create_argument_table
    self._emit('building-argument-table.%s.%s' % (self._parent_name,
  File "/usr/local/Cellar/awscli/2.10.1/libexec/lib/python3.11/site-packages/awscli/clidriver.py", line 874, in _emit
    return self._session.emit(name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/awscli/2.10.1/libexec/lib/python3.11/site-packages/awscli/botocore/session.py", line 699, in emit
    return self._events.emit(event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/awscli/2.10.1/libexec/lib/python3.11/site-packages/awscli/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/awscli/2.10.1/libexec/lib/python3.11/site-packages/awscli/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/awscli/2.10.1/libexec/lib/python3.11/site-packages/awscli/customizations/paginate.py", line 134, in unify_paging_params
    _remove_existing_paging_arguments(argument_table, paginator_config)
  File "/usr/local/Cellar/awscli/2.10.1/libexec/lib/python3.11/site-packages/awscli/customizations/paginate.py", line 245, in _remove_existing_paging_arguments
    argument_table[cli_name]._UNDOCUMENTED = True
    ~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'next-token'

'next-token'
```

### Reproduction Steps

Just running this command seems to be failing on the latest version of aws-cli.

I reverted to previous versions, installed via `installer` or `brew` with the same results.

### Possible Solution

N/A

### CLI version used

aws-cli/2.10.1 Python/3.11.2 Darwin/22.3.0 source/x86_64 prompt/off

### Environment details (OS name and version, etc.)

macOS 13.2.1 Build 22D68

**Comment by aBurmeseDev** [comment]
Hi @rafaelpereyra - thanks for reaching out. Could you confirm that you installed AWS CLI with one of these methods mentioned in the [installation](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) guide as we don't support third-party installation.

I noticed that you have a typo in `--owners` parameter, that may or may not be the cause. Also `owners` isn't mandatory, could you try running it without it? Here's docs for your reference: https://awscli.amazonaws.com/v2/documentation/api/2.4.19/reference/ec2/describe-images.html.

Best,
John

**Comment by rafaelpereyra** [comment]
Understood, the issue happens with and without the filter. 
I tested it from brew but also installing the bundle but I'll try again and report here. Thanks for the quick response!

**Comment by rafaelpereyra** [comment]
Reinstalled both Python and cli and issue is solved now.
