### ISSUE TITLE
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_'

### ISSUE THREAD

**Issue by GameBurrow** [aws/aws-cli#7905]
### Describe the bug

In the last 2-3 weeks we've been observing the following error with aws-cli s3 in Debian:
```
Traceback (most recent call last):
  File "/usr/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 17, in <module>
    import botocore.session
  File "/usr/lib/python3/dist-packages/botocore/session.py", line 30, in <module>
    import botocore.credentials
  File "/usr/lib/python3/dist-packages/botocore/credentials.py", line 34, in <module>
    from botocore.config import Config
  File "/usr/lib/python3/dist-packages/botocore/config.py", line 16, in <module>
    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/usr/lib/python3/dist-packages/botocore/endpoint.py", line 22, in <module>
    from botocore.awsrequest import create_request_object
  File "/usr/lib/python3/dist-packages/botocore/awsrequest.py", line 26, in <module>
    import botocore.utils
  File "/usr/lib/python3/dist-packages/botocore/utils.py", line 33, in <module>
    import botocore.httpsession
  File "/usr/lib/python3/dist-packages/botocore/httpsession.py", line 8, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/usr/local/lib/python3.9/dist-packages/urllib3/util/ssl_.py)
```

### Expected Behavior

```bash
$ apt-get update -y
$ apt-get install -y awscli
$ mkdir ~/.aws
# set up ~/.aws/config & ~/.aws/credentials between these
$ tar -czf ../something.tar.gz .
$ aws s3 cp ../something.tar.gz s3://bucket/
```

something.tar.gz file should exist in s3://bucket/

### Current Behavior

```bash
$ aws s3 cp ../something.tar.gz s3://something/
Traceback (most recent call last):
  File "/usr/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 17, in <module>
    import botocore.session
  File "/usr/lib/python3/dist-packages/botocore/session.py", line 30, in <module>
    import botocore.credentials
  File "/usr/lib/python3/dist-packages/botocore/credentials.py", line 34, in <module>
    from botocore.config import Config
  File "/usr/lib/python3/dist-packages/botocore/config.py", line 16, in <module>
    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/usr/lib/python3/dist-packages/botocore/endpoint.py", line 22, in <module>
    from botocore.awsrequest import create_request_object
  File "/usr/lib/python3/dist-packages/botocore/awsrequest.py", line 26, in <module>
    import botocore.utils
  File "/usr/lib/python3/dist-packages/botocore/utils.py", line 33, in <module>
    import botocore.httpsession
  File "/usr/lib/python3/dist-packages/botocore/httpsession.py", line 8, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/usr/local/lib/python3.9/dist-packages/urllib3/util/ssl_.py)
```

### Reproduction Steps

Install awscli on Debian 11, configure it and try to upload something.

### CLI version used

awscli (1.19.1-1)

### Environment details (OS name and version, etc.)

Debian 11

**Comment by tim-finnigan** [comment]
Hi @GameBurrow thanks for reaching out. This should already be addressed in https://github.com/boto/botocore/pull/2924 as mentioned in [this comment](https://github.com/boto/botocore/issues/2926#issuecomment-1535456104) on a related issue in the Botocore repository (Botocore underpins both Boto3 and the AWS CLI). As mentioned in that issue you'll likely want to ensure you're not upgrading to urllib3 2.0 for the time being or add a more recent version of Botocore. 

We recommend installing v2 of the AWS CLI ([documentation here](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html)) if possible. [This page](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration-changes.html) highlights the migration changes to v2. If you're unable to migrate to v2 at this time then I recommend [updating](https://docs.aws.amazon.com/cli/v1/userguide/cli-chap-install.html) to a more recent version of v1. The latest version of v1 is 1.27.138 per the [CHANGELOG](https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst?plain=1).

**Comment by GameBurrow** [comment]
Ah, didn't think of that, using the default debian package.
