### ISSUE TITLE
Please close

### ISSUE THREAD

**Issue by fellnase** [aws/aws-cli#7999]
### Describe the bug

I'm creating an access Token and configured it with aws configure

Running following command on Mac (I have two macs, one intel based and one M2):
aws ec2 describe-instances
==> An error occurred (AuthFailure) when calling the DescribeInstances operation: AWS was not able to validate the provided access credentials

Same command with docker (=> same access token !)
 docker run --rm -it -v ~/.aws:/root/.aws amazon/aws-cli ec2 describe-instances
{
    "Reservations": []
}

Starting a Parallels Desktop with windows 10 Instance and installed aws cli
 aws ec2 describe-instances
{
    "Reservations": []
}

Versions:
Mac (M2): aws --version
aws-cli/2.12.3 Python/3.11.4 Darwin/22.5.0 exe/x86_64 prompt/off

Mac(Itel): aws --version
aws-cli/2.4.7 Python/3.8.8 Darwin/22.5.0 exe/x86_64 prompt/off

Windows(Virtuell in parallels)
aws-cli/2.12.3 Python/3.11.4 Windows/10 exe/AMD64 prompt/off

### Expected Behavior

Command should give the same result as in docker or windows

### Current Behavior

getting error with mac cmd, (AuthFailure)

### Reproduction Steps

Call command as defined aboth

### Additional Information/Context

Same command in debug mode:

 aws ec2 describe-instances --debug
2023-06-25 13:55:10,983 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.12.3 Python/3.11.4 Darwin/22.5.0 exe/x86_64
2023-06-25 13:55:10,983 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['ec2', 'describe-instances', '--debug']
2023-06-25 13:55:11,027 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x1128a77e0>
2023-06-25 13:55:11,027 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x1126ed080>
2023-06-25 13:55:11,027 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2023-06-25 13:55:11,027 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x112653100>
2023-06-25 13:55:11,027 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x11266c720>
2023-06-25 13:55:11,027 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x1128ba2a0>
2023-06-25 13:55:11,027 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x112723a60>
2023-06-25 13:55:11,027 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2023-06-25 13:55:11,027 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x1128ba160>
2023-06-25 13:55:11,027 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x112966c90>>
2023-06-25 13:55:11,027 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/data/cli.json
2023-06-25 13:55:11,028 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x1127f9440>
2023-06-25 13:55:11,028 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x1127f9760>
2023-06-25 13:55:11,028 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x1127f96c0>
2023-06-25 13:55:11,028 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x1127f98a0>
2023-06-25 13:55:11,028 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x1127f9800>
2023-06-25 13:55:11,028 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x112963dc0>
2023-06-25 13:55:11,028 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.12.3 Python/3.11.4 Darwin/22.5.0 exe/x86_64 prompt/off
2023-06-25 13:55:11,028 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['ec2', 'describe-instances', '--debug']
2023-06-25 13:55:11,029 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x1128b8180>
2023-06-25 13:55:11,029 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x111f61c60>
2023-06-25 13:55:11,029 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x1129276a0>
2023-06-25 13:55:11,029 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x111e2bf60>
2023-06-25 13:55:11,029 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x111f79580>
2023-06-25 13:55:11,030 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://XXX.XXX.XXX.254/
2023-06-25 13:55:11,033 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x112720220>
2023-06-25 13:55:11,033 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x1126e1300>
2023-06-25 13:55:11,049 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/botocore/data/ec2/2016-11-15/service-2.json
2023-06-25 13:55:11,090 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler functools.partial(<function _remove_commands at 0x112810a40>, commands_to_remove=['import-instance', 'import-volume'])
2023-06-25 13:55:11,090 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-instance
2023-06-25 13:55:11,090 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-volume
2023-06-25 13:55:11,090 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <function add_waiters at 0x1128ba160>
2023-06-25 13:55:11,103 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/botocore/data/ec2/2016-11-15/waiters-2.json
2023-06-25 13:55:11,103 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x112966c90>>
2023-06-25 13:55:11,104 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('filters', <awscli.arguments.ListArgument object at 0x11335d3d0>), ('instance-ids', <awscli.arguments.ListArgument object at 0x113795e50>), ('dry-run', <awscli.arguments.BooleanArgument object at 0x113795f90>), ('no-dry-run', <awscli.arguments.BooleanArgument object at 0x113796010>), ('max-results', <awscli.arguments.CLIArgument object at 0x113796150>), ('next-token', <awscli.arguments.CLIArgument object at 0x113796250>)])
2023-06-25 13:55:11,104 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler <function add_streaming_output_arg at 0x1128b8680>
2023-06-25 13:55:11,104 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler <function rename_arg.<locals>._rename_arg at 0x11293c2c0>
2023-06-25 13:55:11,104 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler <function rename_arg.<locals>._rename_arg at 0x11293c360>
2023-06-25 13:55:11,104 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler functools.partial(<function pull_up_bool at 0x1128b99e0>, event_handler=<botocore.hooks.HierarchicalEmitter object at 0x111e59290>)
2023-06-25 13:55:11,104 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler <function add_cli_input_json at 0x111f79ee0>
2023-06-25 13:55:11,104 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler <function add_cli_input_yaml at 0x111f79f80>
2023-06-25 13:55:11,104 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler <function unify_paging_params at 0x1126ed6c0>
2023-06-25 13:55:11,120 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/botocore/data/ec2/2016-11-15/paginators-1.json
2023-06-25 13:55:11,120 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/botocore/data/ec2/2016-11-15/paginators-1.sdk-extras.json
2023-06-25 13:55:11,120 - MainThread - awscli.customizations.paginate - DEBUG - Modifying paging parameters for operation: DescribeInstances
2023-06-25 13:55:11,120 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler <function add_generate_skeleton at 0x1127d7c40>
2023-06-25 13:55:11,120 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.describe-instances: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x1137964d0>>
2023-06-25 13:55:11,120 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.describe-instances: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x111c1d450>>
2023-06-25 13:55:11,120 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.describe-instances: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x1137c5b10>>
2023-06-25 13:55:11,120 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2_describe-instances: calling handler <function add_waiters at 0x1128ba160>
2023-06-25 13:55:11,120 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2_describe-instances: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x112966c90>>
2023-06-25 13:55:11,121 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.ec2.describe-instances: calling handler functools.partial(<function validate_boolean_mutex_groups at 0x1128b9a80>, boolean_pairs=[])
2023-06-25 13:55:11,121 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.ec2.describe-instances: calling handler functools.partial(<function check_should_enable_pagination at 0x1126ed800>, ['next-token', 'max-results'], {}, OrderedDict([('filters', <awscli.arguments.ListArgument object at 0x11335d3d0>), ('instance-ids', <awscli.arguments.ListArgument object at 0x113795e50>), ('dry-run', <awscli.arguments.BooleanArgument object at 0x113795f90>), ('no-dry-run', <awscli.arguments.BooleanArgument object at 0x113796010>), ('max-results', <awscli.arguments.CLIArgument object at 0x113796150>), ('next-token', <awscli.arguments.CLIArgument object at 0x113796250>), ('cli-input-json', <awscli.customizations.cliinput.CliInputJSONArgument object at 0x1137964d0>), ('cli-input-yaml', <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x111c1d450>), ('starting-token', <awscli.customizations.paginate.PageArgument object at 0x11338a310>), ('page-size', <awscli.customizations.paginate.PageArgument object at 0x113797110>), ('max-items', <awscli.customizations.paginate.PageArgument object at 0x1137c5750>), ('generate-cli-skeleton', <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x1137c5b10>)]))
2023-06-25 13:55:11,121 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-instances.filters: calling handler <awscli.paramfile.URIArgumentHandler object at 0x112967a50>
2023-06-25 13:55:11,121 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-instances.instance-ids: calling handler <awscli.paramfile.URIArgumentHandler object at 0x112967a50>
2023-06-25 13:55:11,121 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-instances.dry-run: calling handler <awscli.paramfile.URIArgumentHandler object at 0x112967a50>
2023-06-25 13:55:11,121 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-instances.max-results: calling handler <awscli.paramfile.URIArgumentHandler object at 0x112967a50>
2023-06-25 13:55:11,121 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-instances.next-token: calling handler <awscli.paramfile.URIArgumentHandler object at 0x112967a50>
2023-06-25 13:55:11,121 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-instances.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x112967a50>
2023-06-25 13:55:11,121 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-instances.cli-input-yaml: calling handler <awscli.paramfile.URIArgumentHandler object at 0x112967a50>
2023-06-25 13:55:11,121 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-instances.starting-token: calling handler <awscli.paramfile.URIArgumentHandler object at 0x112967a50>
2023-06-25 13:55:11,121 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-instances.page-size: calling handler <awscli.paramfile.URIArgumentHandler object at 0x112967a50>
2023-06-25 13:55:11,121 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-instances.max-items: calling handler <awscli.paramfile.URIArgumentHandler object at 0x112967a50>
2023-06-25 13:55:11,121 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-instances.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x112967a50>
2023-06-25 13:55:11,121 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.describe-instances: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x1137964d0>>
2023-06-25 13:55:11,121 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.describe-instances: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x111c1d450>>
2023-06-25 13:55:11,121 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.describe-instances: calling handler <bound method GenerateCliSkeletonArgument.generate_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x1137c5b10>>
2023-06-25 13:55:11,121 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.describe-instances: calling handler functools.partial(<function check_should_enable_pagination_call_parameters at 0x1126edc60>, ['NextToken', 'MaxResults'])
2023-06-25 13:55:11,121 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2023-06-25 13:55:11,121 - MainThread - botocore.credentials - INFO - Found credentials in environment variables.
2023-06-25 13:55:11,122 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/botocore/data/endpoints.json
2023-06-25 13:55:11,129 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x110bb22a0>
2023-06-25 13:55:11,145 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/botocore/data/ec2/2016-11-15/endpoint-rule-set-1.json
2023-06-25 13:55:11,145 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/botocore/data/partitions.json
2023-06-25 13:55:11,152 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.ec2: calling handler <function add_generate_presigned_url at 0x110b0a980>
2023-06-25 13:55:11,153 - MainThread - botocore.endpoint - DEBUG - Setting ec2 timeout as (60, 60)
2023-06-25 13:55:11,154 - MainThread - botocore.regions - DEBUG - Calling endpoint provider with parameters: {'Region': 'eu-central-1', 'UseDualStack': False, 'UseFIPS': False}
2023-06-25 13:55:11,154 - MainThread - botocore.regions - DEBUG - Endpoint provider result: https://ec2.eu-central-1.amazonaws.com
2023-06-25 13:55:11,154 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.ec2.DescribeInstances: calling handler <function base64_decode_input_blobs at 0x112927740>
2023-06-25 13:55:11,154 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.ec2.DescribeInstances: calling handler <bound method ParameterAlias.alias_parameter_in_call of <botocore.handlers.ParameterAlias object at 0x110bcf890>>
2023-06-25 13:55:11,154 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.ec2.DescribeInstances: calling handler <function generate_idempotent_uuid at 0x110bc8540>
2023-06-25 13:55:11,154 - MainThread - botocore.hooks - DEBUG - Event before-call.ec2.DescribeInstances: calling handler <function inject_api_version_header_if_needed at 0x110bca020>
2023-06-25 13:55:11,154 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=DescribeInstances) with params: {'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': 'aws-cli/2.12.3 Python/3.11.4 Darwin/22.5.0 exe/x86_64 prompt/off command/ec2.describe-instances'}, 'body': {'Action': 'DescribeInstances', 'Version': '2016-11-15'}, 'url': 'https://ec2.eu-central-1.amazonaws.com/', 'context': {'client_region': 'eu-central-1', 'client_config': <botocore.config.Config object at 0x1136e4a90>, 'has_streaming_input': False, 'auth_type': None}}
2023-06-25 13:55:11,155 - MainThread - botocore.hooks - DEBUG - Event request-created.ec2.DescribeInstances: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x113c63690>>
2023-06-25 13:55:11,155 - MainThread - botocore.hooks - DEBUG - Event choose-signer.ec2.DescribeInstances: calling handler <function set_operation_specific_signer at 0x110bc8400>
2023-06-25 13:55:11,155 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2023-06-25 13:55:11,155 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-www-form-urlencoded; charset=utf-8
host:ec2.eu-central-1.amazonaws.com
x-amz-date:20230625T115511Z

content-type;host;x-amz-date
6171eb09865e32b0602af0f7957e26573a51f53caaedff02ff88883cb0275885
2023-06-25 13:55:11,155 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20230625T115511Z
20230625/eu-central-1/ec2/aws4_request
3a625216b0266f8058e30XXXXXXXx1945a1102a32e7ff1336ddd0746536XXXXX
2023-06-25 13:55:11,155 - MainThread - botocore.auth - DEBUG - Signature:
e34e7ed1d3ef63e9f0aeXXXXXXec35debd8bdc7b5faacd7XXXXXXXXXXXXX
2023-06-25 13:55:11,155 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://ec2.eu-central-1.amazonaws.com/, headers={'Content-Type': b'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': b'aws-cli/2.12.3 Python/3.11.4 Darwin/22.5.0 exe/x86_64 prompt/off command/ec2.describe-instances', 'X-Amz-Date': b'20230625T115511Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=N4JV9HXXXXXXXXXXXXXXXXX/eu-central-1/ec2/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=e34e7ed1d3ef63e9f0aec74c2a5a274ec35dxxxxxxxxxxxxxx', 'Content-Length': '43'}>
2023-06-25 13:55:11,156 - MainThread - botocore.httpsession - DEBUG - Certificate path: /usr/local/aws-cli/awscli/botocore/cacert.pem
2023-06-25 13:55:11,156 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): ec2.eu-central-1.amazonaws.com:443
2023-06-25 13:55:11,324 - MainThread - urllib3.connectionpool - DEBUG - https://ec2.eu-central-1.amazonaws.com:443 "POST / HTTP/1.1" 401 None
2023-06-25 13:55:11,324 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-RequestId': 'c652xxxxx-xxxxx-bbbbb-aaaa-XXXXXXXXXX', 'Cache-Control': 'no-cache, no-store', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'vary': 'accept-encoding', 'Content-Type': 'text/xml;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Date': 'Sun, 25 Jun 2023 11:55:11 GMT', 'Server': 'AmazonEC2'}
2023-06-25 13:55:11,325 - MainThread - botocore.parsers - DEBUG - Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>c652xxxxx-xxxxx-bbbbb-aaaa-XXXXXXXXXX</RequestID></Response>'
2023-06-25 13:55:11,329 - MainThread - botocore.hooks - DEBUG - Event needs-retry.ec2.DescribeInstances: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x113d1ce10>>
2023-06-25 13:55:11,329 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2023-06-25 13:55:11,329 - MainThread - botocore.hooks - DEBUG - Event after-call.ec2.DescribeInstances: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x11365ce10>>
2023-06-25 13:55:11,329 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/clidriver.py", line 460, in main
  File "awscli/clidriver.py", line 595, in __call__
  File "awscli/clidriver.py", line 798, in __call__
  File "awscli/clidriver.py", line 931, in invoke
  File "awscli/clidriver.py", line 953, in _display_response
  File "awscli/formatter.py", line 77, in __call__
  File "awscli/botocore/paginate.py", line 446, in build_full_result
  File "awscli/botocore/paginate.py", line 252, in __iter__
  File "awscli/botocore/paginate.py", line 329, in _make_request
  File "awscli/botocore/client.py", line 341, in _api_call
  File "awscli/botocore/client.py", line 697, in _make_api_call
botocore.exceptions.ClientError: An error occurred (AuthFailure) when calling the DescribeInstances operation: AWS was not able to validate the provided access credentials

An error occurred (AuthFailure) when calling the DescribeInstances operation: AWS was not able to validate the provided access credentials

### CLI version used

aws-cli/2.12.3 and aws-cli/2.4.7

### Environment details (OS name and version, etc.)

MacOS: 13.4.1

**Comment by fellnase** [comment]
Wrong configuration in shell, sorry. My fault
