### ISSUE TITLE
An error occurred (InternalFailure) when calling the ListDataSources operation (reached max retries: 2): None

### ISSUE THREAD

**Issue by ricomasgu** [aws/aws-cli#8024]
### Describe the bug

I have this error when executing:
`aws quicksight list-data-sources --aws-account-id AWS_ACCOUNT_ID`

### Expected Behavior

To list the data sources I have in quicksight.

### Current Behavior

Detailed Error:
```
2023-07-07 11:50:55,622 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.12.2 Python/3.11.4 Darwin/21.6.0 exe/x86_64
2023-07-07 11:50:55,622 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['quicksight', 'list-data-sources', '--aws-account-id', 'AWS_ACCOUNT_ID', '--debug']
2023-07-07 11:50:55,632 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x10fc2f7e0>
2023-07-07 11:50:55,632 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x10fa71080>
2023-07-07 11:50:55,632 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2023-07-07 11:50:55,632 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x10f9d3100>
2023-07-07 11:50:55,632 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x10f9ec720>
2023-07-07 11:50:55,632 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x10fc462a0>
2023-07-07 11:50:55,632 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x10faa7a60>
2023-07-07 11:50:55,632 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2023-07-07 11:50:55,632 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x10fc46160>
2023-07-07 11:50:55,632 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x10ef95250>>
2023-07-07 11:50:55,632 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/data/cli.json
2023-07-07 11:50:55,633 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x10fb81440>
2023-07-07 11:50:55,633 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x10fb81760>
2023-07-07 11:50:55,633 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x10fb816c0>
2023-07-07 11:50:55,633 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x10fb818a0>
2023-07-07 11:50:55,633 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x10fb81800>
2023-07-07 11:50:55,633 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x10fcef900>
2023-07-07 11:50:55,634 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.12.2 Python/3.11.4 Darwin/21.6.0 exe/x86_64 prompt/off
2023-07-07 11:50:55,634 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['quicksight', 'list-data-sources', '--aws-account-id', 'AWS_ACCOUNT_ID', '--debug']
2023-07-07 11:50:55,634 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x10fc44180>
2023-07-07 11:50:55,634 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x10f2ddc60>
2023-07-07 11:50:55,634 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x10fcb36a0>
2023-07-07 11:50:55,634 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x10f1abf60>
2023-07-07 11:50:55,634 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x10f2f5580>
2023-07-07 11:50:55,643 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2023-07-07 11:50:55,647 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x10faa4220>
2023-07-07 11:50:55,647 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x10fa65300>
2023-07-07 11:50:55,658 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/botocore/data/quicksight/2018-04-01/service-2.json
2023-07-07 11:50:55,676 - MainThread - botocore.hooks - DEBUG - Event building-command-table.quicksight: calling handler <function add_waiters at 0x10fc46160>
2023-07-07 11:50:55,685 - MainThread - botocore.hooks - DEBUG - Event building-command-table.quicksight: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x10ef95250>>
2023-07-07 11:50:55,685 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('aws-account-id', <awscli.arguments.CLIArgument object at 0x110357650>), ('next-token', <awscli.arguments.CLIArgument object at 0x1103576d0>), ('max-results', <awscli.arguments.CLIArgument object at 0x110357710>)])
2023-07-07 11:50:55,685 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.quicksight.list-data-sources: calling handler <function add_streaming_output_arg at 0x10fc44680>
2023-07-07 11:50:55,685 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.quicksight.list-data-sources: calling handler <function add_cli_input_json at 0x10f2f5ee0>
2023-07-07 11:50:55,685 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.quicksight.list-data-sources: calling handler <function add_cli_input_yaml at 0x10f2f5f80>
2023-07-07 11:50:55,685 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.quicksight.list-data-sources: calling handler <function unify_paging_params at 0x10fa716c0>
2023-07-07 11:50:55,695 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/botocore/data/quicksight/2018-04-01/paginators-1.json
2023-07-07 11:50:55,695 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/botocore/data/quicksight/2018-04-01/paginators-1.sdk-extras.json
2023-07-07 11:50:55,695 - MainThread - awscli.customizations.paginate - DEBUG - Modifying paging parameters for operation: ListDataSources
2023-07-07 11:50:55,695 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.quicksight.list-data-sources: calling handler <function add_generate_skeleton at 0x10fb5fc40>
2023-07-07 11:50:55,695 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.quicksight.list-data-sources: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x110357a50>>
2023-07-07 11:50:55,695 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.quicksight.list-data-sources: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x110357090>>
2023-07-07 11:50:55,695 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.quicksight.list-data-sources: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x110366390>>
2023-07-07 11:50:55,695 - MainThread - botocore.hooks - DEBUG - Event building-command-table.quicksight_list-data-sources: calling handler <function add_waiters at 0x10fc46160>
2023-07-07 11:50:55,695 - MainThread - botocore.hooks - DEBUG - Event building-command-table.quicksight_list-data-sources: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x10ef95250>>
2023-07-07 11:50:55,696 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.quicksight.list-data-sources: calling handler functools.partial(<function check_should_enable_pagination at 0x10fa71800>, ['next-token', 'max-results'], {}, OrderedDict([('aws-account-id', <awscli.arguments.CLIArgument object at 0x110357650>), ('next-token', <awscli.arguments.CLIArgument object at 0x1103576d0>), ('max-results', <awscli.arguments.CLIArgument object at 0x110357710>), ('cli-input-json', <awscli.customizations.cliinput.CliInputJSONArgument object at 0x110357a50>), ('cli-input-yaml', <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x110357090>), ('starting-token', <awscli.customizations.paginate.PageArgument object at 0x110303490>), ('page-size', <awscli.customizations.paginate.PageArgument object at 0x1102e8e50>), ('max-items', <awscli.customizations.paginate.PageArgument object at 0x110339b10>), ('generate-cli-skeleton', <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x110366390>)]))
2023-07-07 11:50:55,696 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.list-data-sources.aws-account-id: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10fd003d0>
2023-07-07 11:50:55,696 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.quicksight.list-data-sources: calling handler <awscli.argprocess.ParamShorthandParser object at 0x10f1f4d50>
2023-07-07 11:50:55,696 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'AWS_ACCOUNT_ID' for parameter "aws_account_id": 'AWS_ACCOUNT_ID'
2023-07-07 11:50:55,696 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.list-data-sources.next-token: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10fd003d0>
2023-07-07 11:50:55,696 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.list-data-sources.max-results: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10fd003d0>
2023-07-07 11:50:55,696 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.list-data-sources.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10fd003d0>
2023-07-07 11:50:55,696 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.list-data-sources.cli-input-yaml: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10fd003d0>
2023-07-07 11:50:55,696 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.list-data-sources.starting-token: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10fd003d0>
2023-07-07 11:50:55,696 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.list-data-sources.page-size: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10fd003d0>
2023-07-07 11:50:55,696 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.list-data-sources.max-items: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10fd003d0>
2023-07-07 11:50:55,696 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.list-data-sources.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10fd003d0>
2023-07-07 11:50:55,696 - MainThread - botocore.hooks - DEBUG - Event calling-command.quicksight.list-data-sources: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x110357a50>>
2023-07-07 11:50:55,696 - MainThread - botocore.hooks - DEBUG - Event calling-command.quicksight.list-data-sources: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x110357090>>
2023-07-07 11:50:55,696 - MainThread - botocore.hooks - DEBUG - Event calling-command.quicksight.list-data-sources: calling handler <bound method GenerateCliSkeletonArgument.generate_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x110366390>>
2023-07-07 11:50:55,696 - MainThread - botocore.hooks - DEBUG - Event calling-command.quicksight.list-data-sources: calling handler functools.partial(<function check_should_enable_pagination_call_parameters at 0x10fa71c60>, ['NextToken', 'MaxResults'])
2023-07-07 11:50:55,696 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2023-07-07 11:50:55,696 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2023-07-07 11:50:55,696 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2023-07-07 11:50:55,696 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2023-07-07 11:50:55,696 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2023-07-07 11:50:55,697 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2023-07-07 11:50:55,697 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/botocore/data/endpoints.json
2023-07-07 11:50:55,706 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x10df3a2a0>
2023-07-07 11:50:55,716 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/botocore/data/quicksight/2018-04-01/endpoint-rule-set-1.json
2023-07-07 11:50:55,716 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/awscli/botocore/data/partitions.json
2023-07-07 11:50:55,718 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.quicksight: calling handler <function add_generate_presigned_url at 0x10de8e980>
2023-07-07 11:50:55,721 - MainThread - botocore.endpoint - DEBUG - Setting quicksight timeout as (60, 60)
2023-07-07 11:50:55,722 - MainThread - botocore.regions - DEBUG - Calling endpoint provider with parameters: {'Region': 'eu-central-1', 'UseDualStack': False, 'UseFIPS': False}
2023-07-07 11:50:55,722 - MainThread - botocore.regions - DEBUG - Endpoint provider result: https://quicksight.eu-central-1.amazonaws.com
2023-07-07 11:50:55,723 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.quicksight.ListDataSources: calling handler <function base64_decode_input_blobs at 0x10fcb3740>
2023-07-07 11:50:55,723 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.quicksight.ListDataSources: calling handler <function generate_idempotent_uuid at 0x10df50540>
2023-07-07 11:50:55,723 - MainThread - botocore.hooks - DEBUG - Event before-call.quicksight.ListDataSources: calling handler <function inject_api_version_header_if_needed at 0x10df52020>
2023-07-07 11:50:55,723 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=ListDataSources) with params: {'url_path': '/accounts/AWS_ACCOUNT_ID/data-sources', 'query_string': {}, 'method': 'GET', 'headers': {'User-Agent': 'aws-cli/2.12.2 Python/3.11.4 Darwin/21.6.0 exe/x86_64 prompt/off command/quicksight.list-data-sources'}, 'body': b'', 'url': 'https://quicksight.eu-central-1.amazonaws.com/accounts/AWS_ACCOUNT_ID/data-sources', 'context': {'client_region': 'eu-central-1', 'client_config': <botocore.config.Config object at 0x1102f50d0>, 'has_streaming_input': False, 'auth_type': None}}
2023-07-07 11:50:55,723 - MainThread - botocore.hooks - DEBUG - Event request-created.quicksight.ListDataSources: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x10e991f50>>
2023-07-07 11:50:55,723 - MainThread - botocore.hooks - DEBUG - Event choose-signer.quicksight.ListDataSources: calling handler <function set_operation_specific_signer at 0x10df50400>
2023-07-07 11:50:55,723 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2023-07-07 11:50:55,723 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
GET
/accounts/AWS_ACCOUNT_ID/data-sources

host:quicksight.eu-central-1.amazonaws.com
x-amz-date:20230707T095055Z

host;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2023-07-07 11:50:55,724 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20230707T095055Z
20230707/eu-central-1/quicksight/aws4_request
91c24b2116393c187e1d25d0bc554fb758f6cbb79e698fb95b12c67b76e6d7b8
2023-07-07 11:50:55,724 - MainThread - botocore.auth - DEBUG - Signature:
264e88e450d460fdc56d72ac80c503ef2eaa8d1cc61840d61322eabd30e3f4bf
2023-07-07 11:50:55,724 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=GET, url=https://quicksight.eu-central-1.amazonaws.com/accounts/AWS_ACCOUNT_ID/data-sources, headers={'User-Agent': b'aws-cli/2.12.2 Python/3.11.4 Darwin/21.6.0 exe/x86_64 prompt/off command/quicksight.list-data-sources', 'X-Amz-Date': b'20230707T095055Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=CREDENTIAL_CODE/20230707/eu-central-1/quicksight/aws4_request, SignedHeaders=host;x-amz-date, Signature=264e88e450d460fdc56d72ac80c503ef2eaa8d1cc61840d61322eabd30e3f4bf'}>
2023-07-07 11:50:55,725 - MainThread - botocore.httpsession - DEBUG - Certificate path: /usr/local/aws-cli/awscli/botocore/cacert.pem
2023-07-07 11:50:55,725 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): quicksight.eu-central-1.amazonaws.com:443
2023-07-07 11:50:56,099 - MainThread - urllib3.connectionpool - DEBUG - https://quicksight.eu-central-1.amazonaws.com:443 "GET /accounts/AWS_ACCOUNT_ID/data-sources HTTP/1.1" 500 16
2023-07-07 11:50:56,100 - MainThread - botocore.parsers - DEBUG - Response headers: {'Date': 'Fri, 07 Jul 2023 09:50:56 GMT', 'Content-Type': 'application/json', 'Content-Length': '16', 'Connection': 'keep-alive', 'x-amzn-RequestId': '8dc218f1-e4e5-47f9-b786-6a347cbe1604', 'x-amzn-ErrorType': 'InternalFailure:http://internal.amazon.com/coral/com.amazon.coral.service/'}
2023-07-07 11:50:56,100 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"message":null}'
2023-07-07 11:50:56,109 - MainThread - botocore.hooks - DEBUG - Event needs-retry.quicksight.ListDataSources: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x1107fbb10>>
2023-07-07 11:50:56,109 - MainThread - botocore.retries.standard - DEBUG - Retry needed, retrying request after delay of: 0.7813869919700156
2023-07-07 11:50:56,110 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.7813869919700156 seconds
2023-07-07 11:50:56,895 - MainThread - botocore.hooks - DEBUG - Event request-created.quicksight.ListDataSources: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x10e991f50>>
2023-07-07 11:50:56,896 - MainThread - botocore.hooks - DEBUG - Event choose-signer.quicksight.ListDataSources: calling handler <function set_operation_specific_signer at 0x10df50400>
2023-07-07 11:50:56,897 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2023-07-07 11:50:56,897 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
GET
/accounts/AWS_ACCOUNT_ID/data-sources

host:quicksight.eu-central-1.amazonaws.com
x-amz-date:20230707T095056Z

host;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2023-07-07 11:50:56,897 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20230707T095056Z
20230707/eu-central-1/quicksight/aws4_request
5a366fef873f0da58f1a3ca377a970d199f62f50790898aa4abefea441879d79
2023-07-07 11:50:56,897 - MainThread - botocore.auth - DEBUG - Signature:
376cebead311e0f3fad321ffe04e4214e0f4df7e2e7bedde83b1b6f10377eb74
2023-07-07 11:50:56,897 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=GET, url=https://quicksight.eu-central-1.amazonaws.com/accounts/AWS_ACCOUNT_ID/data-sources, headers={'User-Agent': b'aws-cli/2.12.2 Python/3.11.4 Darwin/21.6.0 exe/x86_64 prompt/off command/quicksight.list-data-sources', 'X-Amz-Date': b'20230707T095056Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=CREDENTIAL_CODE/20230707/eu-central-1/quicksight/aws4_request, SignedHeaders=host;x-amz-date, Signature=376cebead311e0f3fad321ffe04e4214e0f4df7e2e7bedde83b1b6f10377eb74'}>
2023-07-07 11:50:56,898 - MainThread - botocore.httpsession - DEBUG - Certificate path: /usr/local/aws-cli/awscli/botocore/cacert.pem
2023-07-07 11:50:57,164 - MainThread - urllib3.connectionpool - DEBUG - https://quicksight.eu-central-1.amazonaws.com:443 "GET /accounts/AWS_ACCOUNT_ID/data-sources HTTP/1.1" 500 16
2023-07-07 11:50:57,165 - MainThread - botocore.parsers - DEBUG - Response headers: {'Date': 'Fri, 07 Jul 2023 09:50:57 GMT', 'Content-Type': 'application/json', 'Content-Length': '16', 'Connection': 'keep-alive', 'x-amzn-RequestId': '2b5fa760-24cf-4805-94bf-e08798c6169c', 'x-amzn-ErrorType': 'InternalFailure:http://internal.amazon.com/coral/com.amazon.coral.service/'}
2023-07-07 11:50:57,165 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"message":null}'
2023-07-07 11:50:57,165 - MainThread - botocore.hooks - DEBUG - Event needs-retry.quicksight.ListDataSources: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x1107fbb10>>
2023-07-07 11:50:57,166 - MainThread - botocore.retries.standard - DEBUG - Retry needed, retrying request after delay of: 0.8057758219967586
2023-07-07 11:50:57,166 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.8057758219967586 seconds
2023-07-07 11:50:57,972 - MainThread - botocore.hooks - DEBUG - Event request-created.quicksight.ListDataSources: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x10e991f50>>
2023-07-07 11:50:57,973 - MainThread - botocore.hooks - DEBUG - Event choose-signer.quicksight.ListDataSources: calling handler <function set_operation_specific_signer at 0x10df50400>
2023-07-07 11:50:57,976 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2023-07-07 11:50:57,976 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
GET
/accounts/AWS_ACCOUNT_ID/data-sources

host:quicksight.eu-central-1.amazonaws.com
x-amz-date:20230707T095057Z

host;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2023-07-07 11:50:57,976 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20230707T095057Z
20230707/eu-central-1/quicksight/aws4_request
5ac6209f169c1390903d47ad588030c2d96e6beec4a77f2766b6780d9e2e4f6c
2023-07-07 11:50:57,977 - MainThread - botocore.auth - DEBUG - Signature:
f6ef63ff622be7adf36bf3c8c4ff3fe8a15c2e7be528a76bf413f871ce99aa58
2023-07-07 11:50:57,977 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=GET, url=https://quicksight.eu-central-1.amazonaws.com/accounts/AWS_ACCOUNT_ID/data-sources, headers={'User-Agent': b'aws-cli/2.12.2 Python/3.11.4 Darwin/21.6.0 exe/x86_64 prompt/off command/quicksight.list-data-sources', 'X-Amz-Date': b'20230707T095057Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=CREDENTIAL_CODE/20230707/eu-central-1/quicksight/aws4_request, SignedHeaders=host;x-amz-date, Signature=f6ef63ff622be7adf36bf3c8c4ff3fe8a15c2e7be528a76bf413f871ce99aa58'}>
2023-07-07 11:50:57,978 - MainThread - botocore.httpsession - DEBUG - Certificate path: /usr/local/aws-cli/awscli/botocore/cacert.pem
2023-07-07 11:50:58,259 - MainThread - urllib3.connectionpool - DEBUG - https://quicksight.eu-central-1.amazonaws.com:443 "GET /accounts/AWS_ACCOUNT_ID/data-sources HTTP/1.1" 500 16
2023-07-07 11:50:58,260 - MainThread - botocore.parsers - DEBUG - Response headers: {'Date': 'Fri, 07 Jul 2023 09:50:58 GMT', 'Content-Type': 'application/json', 'Content-Length': '16', 'Connection': 'keep-alive', 'x-amzn-RequestId': '716471fe-1535-45c9-8e0f-4c4d7bde4b22', 'x-amzn-ErrorType': 'InternalFailure:http://internal.amazon.com/coral/com.amazon.coral.service/'}
2023-07-07 11:50:58,260 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"message":null}'
2023-07-07 11:50:58,261 - MainThread - botocore.hooks - DEBUG - Event needs-retry.quicksight.ListDataSources: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x1107fbb10>>
2023-07-07 11:50:58,261 - MainThread - botocore.retries.standard - DEBUG - Max attempts of 3 reached.
2023-07-07 11:50:58,262 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2023-07-07 11:50:58,262 - MainThread - botocore.hooks - DEBUG - Event after-call.quicksight.ListDataSources: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x1107fa910>>
2023-07-07 11:50:58,263 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/clidriver.py", line 460, in main
  File "awscli/clidriver.py", line 595, in __call__
  File "awscli/clidriver.py", line 798, in __call__
  File "awscli/clidriver.py", line 931, in invoke
  File "awscli/clidriver.py", line 953, in _display_response
  File "awscli/formatter.py", line 77, in __call__
  File "awscli/botocore/paginate.py", line 446, in build_full_result
  File "awscli/botocore/paginate.py", line 252, in __iter__
  File "awscli/botocore/paginate.py", line 329, in _make_request
  File "awscli/botocore/client.py", line 341, in _api_call
  File "awscli/botocore/client.py", line 697, in _make_api_call
botocore.exceptions.ClientError: An error occurred (InternalFailure) when calling the ListDataSources operation (reached max retries: 2): None

An error occurred (InternalFailure) when calling the ListDataSources operation (reached max retries: 2): None
```

### Reproduction Steps

You have to be signed in with aws cli and at least the versions aws-cli/2.12.2 Python/3.11.4. Then just execute the command `aws quicksight list-data-sources --aws-account-id AWS_ACCOUNT_ID`

### CLI version used

2.12.2

### Environment details (OS name and version, etc.)

Mac OS Monterrey 12.6 - Darwin/21.6.0 exe/x86_64

**Comment by ricomasgu** [comment]
I created the following script to try to get the info using boto3 instead. Now thinking if I am using the same API endpoint that aws cli uses, does not make a lot of sense.

```
import boto3
import json
import time
import sys
from awsglue.utils import getResolvedOptions

args = getResolvedOptions(sys.argv,
                          ['REGION',
                          'ACCOUNT_ID',
                          'ACCESS_KEY',
                          'SECRET_KEY'])

REGION=args["REGION"]
ACCOUNT_ID=args["ACCOUNT_ID"]
ACCESS_KEY=args["ACCESS_KEY"]
SECRET_KEY=args["SECRET_KEY"]

session = boto3.Session(
    aws_access_key_id=ACCESS_KEY,
    aws_secret_access_key=SECRET_KEY,
    region_name=REGION
)

quicksight = session.client('quicksight')

response = quicksight.list_data_sources(
    AwsAccountId=ACCOUNT_ID,
)

print(response)
```

Got the same error.

**Comment by ricomasgu** [comment]
Now it works, I asked support but they say they did nothing.
