### ISSUE TITLE
Failed to build on latest Python version: No matching distribution found for PyInstaller==5.12.0 (bump PyInstaller)

### ISSUE THREAD

**Issue by jgournet** [aws/aws-cli#8245]
### Describe the bug

```
13:04:32  + docker build --pull --no-cache --tag base/alpine-aws-cli:1002 .
13:04:32  #2 [internal] load .dockerignore
13:04:32  #2 sha256:cad3ab60be60e588c6e13f8cfa0782838eb0e5b10de607499c6e721a6e807618
13:04:32  #2 transferring context: 2B 0.0s done
13:04:32  #2 DONE 0.0s
13:04:32  

[...]

13:05:12  #9 [ 7/10] RUN scripts/installers/make-exe
13:05:12  #9 sha256:1b3a88c4515a1293ac2335f16837f0a22a45f3ab75d84aaa2413f0d80210e027
13:05:24  #9 10.87 Running cmd: pip install -r requirements.txt
13:05:24  #9 10.87 Traceback (most recent call last):
13:05:24  #9 10.87   File "/aws-cli/scripts/installers/make-exe", line 146, in <module>
13:05:24  #9 10.88     main()
13:05:24  #9 10.88   File "/aws-cli/scripts/installers/make-exe", line 139, in main
13:05:24  #9 10.88     run('pip install -r requirements.txt')
13:05:24  #9 10.88   File "/aws-cli/scripts/utils.py", line 34, in run
13:05:24  #9 10.88     raise BadRCError("Bad rc (%s) for cmd '%s': %s" % (
13:05:24  #9 10.88 utils.BadRCError: Bad rc (1) for cmd 'pip install -r requirements.txt': Collecting wheel==0.38.4 (from -r requirements-base.txt (line 1))
13:05:24  #9 10.88   Downloading wheel-0.38.4-py3-none-any.whl (36 kB)
13:05:24  #9 10.88 Collecting flit_core==3.8.0 (from -r requirements-base.txt (line 2))
13:05:24  #9 10.88   Downloading flit_core-3.8.0-py3-none-any.whl (62 kB)
13:05:24  #9 10.88      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 10.5 MB/s eta 0:00:00
13:05:24  #9 10.88 Collecting tox==4.4.12 (from -r requirements.txt (line 2))
13:05:24  #9 10.88   Downloading tox-4.4.12-py3-none-any.whl (148 kB)
13:05:24  #9 10.88      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.0/149.0 kB 20.3 MB/s eta 0:00:00
13:05:24  #9 10.88 Collecting build==0.7.0 (from -r requirements.txt (line 3))
13:05:24  #9 10.88   Downloading build-0.7.0-py3-none-any.whl (16 kB)
13:05:24  #9 10.88 Collecting jsonschema==4.7.2 (from -r requirements-test.txt (line 1))
13:05:24  #9 10.88   Downloading jsonschema-4.7.2-py3-none-any.whl (81 kB)
13:05:24  #9 10.88      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.1/81.1 kB 12.6 MB/s eta 0:00:00
13:05:24  #9 10.88 Collecting mock==1.3.0 (from -r requirements-test.txt (line 2))
13:05:24  #9 10.88   Downloading mock-1.3.0-py2.py3-none-any.whl (56 kB)
13:05:24  #9 10.88      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 kB 9.1 MB/s eta 0:00:00
13:05:24  #9 10.88 Collecting pytest==7.2.0 (from -r requirements-test.txt (line 3))
13:05:24  #9 10.88   Downloading pytest-7.2.0-py3-none-any.whl (316 kB)
13:05:24  #9 10.88      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.8/316.8 kB 32.2 MB/s eta 0:00:00
13:05:24  #9 10.88 Collecting coverage==7.0.1 (from -r requirements-test.txt (line 4))
13:05:24  #9 10.88   Downloading coverage-7.0.1.tar.gz (781 kB)
13:05:24  #9 10.88      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.2/781.2 kB 51.0 MB/s eta 0:00:00
13:05:24  #9 10.88   Installing build dependencies: started
13:05:24  #9 10.88   Installing build dependencies: finished with status 'done'
13:05:24  #9 10.88   Getting requirements to build wheel: started
13:05:24  #9 10.88   Getting requirements to build wheel: finished with status 'done'
13:05:24  #9 10.88   Installing backend dependencies: started
13:05:24  #9 10.88   Installing backend dependencies: finished with status 'done'
13:05:24  #9 10.88   Preparing metadata (pyproject.toml): started
13:05:24  #9 10.88   Preparing metadata (pyproject.toml): finished with status 'done'
13:05:24  #9 10.88 Collecting pytest-cov==4.0.0 (from -r requirements-test.txt (line 5))
13:05:24  #9 10.88   Downloading pytest_cov-4.0.0-py3-none-any.whl (21 kB)
13:05:24  #9 10.88 Collecting pytest-xdist==3.1.0 (from -r requirements-test.txt (line 6))
13:05:24  #9 10.88   Downloading pytest_xdist-3.1.0-py3-none-any.whl (36 kB)
13:05:24  #9 10.88 Collecting pip-tools==7.0.0 (from -r requirements-test.txt (line 7))
13:05:24  #9 10.88   Obtaining dependency information for pip-tools==7.0.0 from https://files.pythonhosted.org/packages/65/36/0447d5998a7cf8d017f0ed2361fd97cf68373ee3b4a18b646adbf8704fe3/pip_tools-7.0.0-py3-none-any.whl.metadata
13:05:24  #9 10.88   Downloading pip_tools-7.0.0-py3-none-any.whl.metadata (23 kB)
13:05:24  #9 10.88 ERROR: Ignored the following versions that require a different python version: 4.10 Requires-Python <3.11,>=3.6; 4.6 Requires-Python <3.11,>=3.6; 4.7 Requires-Python <3.11,>=3.6; 4.8 Requires-Python <3.11,>=3.6; 4.9 Requires-Python <3.11,>=3.6; 5.0 Requires-Python <3.11,>=3.7; 5.0.1 Requires-Python <3.11,>=3.7; 5.1 Requires-Python <3.11,>=3.7; 5.10.0 Requires-Python <3.12,>=3.7; 5.10.1 Requires-Python <3.12,>=3.7; 5.11.0 Requires-Python <3.12,>=3.7; 5.12.0 Requires-Python <3.12,>=3.7; 5.2 Requires-Python <3.11,>=3.7; 5.3 Requires-Python <3.11,>=3.7; 5.4 Requires-Python <3.11,>=3.7; 5.4.1 Requires-Python <3.11,>=3.7; 5.5 Requires-Python <3.12,>=3.7; 5.6 Requires-Python <3.12,>=3.7; 5.6.1 Requires-Python <3.12,>=3.7; 5.6.2 Requires-Python <3.12,>=3.7; 5.7.0 Requires-Python <3.12,>=3.7; 5.8.0 Requires-Python <3.12,>=3.7; 5.9.0 Requires-Python <3.12,>=3.7
13:05:24  #9 10.88 ERROR: Could not find a version that satisfies the requirement PyInstaller==5.12.0 (from versions: 2.0, 2.1, 3.0, 3.1, 3.1.1, 3.2, 3.2.1, 3.3, 3.3.1, 3.4, 3.5, 3.6, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.5.1, 5.13.0, 5.13.1, 5.13.2, 6.0.0, 6.1.0)
13:05:24  #9 10.88 ERROR: No matching distribution found for PyInstaller==5.12.0
13:05:24  #9 10.88 
13:05:24  #9 10.88 [notice] A new release of pip is available: 23.2.1 -> 23.3
13:05:24  #9 10.88 [notice] To update, run: pip install --upgrade pip
13:05:24  #9 10.88 
13:05:24  #9 ERROR: process "/bin/sh -c scripts/installers/make-exe" did not complete successfully: exit code: 1
13:05:24  ------
13:05:24   > [ 7/10] RUN scripts/installers/make-exe:
13:05:24  ------
13:05:24  process "/bin/sh -c scripts/installers/make-exe" did not complete successfully: exit code: 1
```

### Expected Behavior

no error

### Current Behavior

docker build failing

### Reproduction Steps

Using this Dockerfile:

```
FROM python:3-alpine

RUN apk add --no-cache git unzip groff build-base libffi-dev cmake
RUN git clone --recursive  --depth 1 --branch v2 --single-branch  https://github.com/aws/aws-cli.git

WORKDIR aws-cli
RUN python -m venv venv
RUN . venv/bin/activate
RUN scripts/installers/make-exe
RUN unzip -q dist/awscli-exe.zip
RUN aws/install --bin-dir /aws-cli-bin
RUN /aws-cli-bin/aws --version
```
and command:
```
docker build --no-cache .
```

### CLI version used

v2

### Environment details (OS name and version, etc.)

linux alpine docker

**Comment by tim-finnigan** [comment]
Hi @jgournet thanks for reaching out. `python:3-alpine` is using Python 3.12 which [pyInstaller 5.12.0](https://pypi.org/project/pyinstaller/5.12.0/) does not support. I confirmed this by running:
```
docker pull python:3-alpine
docker run --rm python:3-alpine python --version
Python 3.12.0
```
And updating your Dockerfile to use `FROM python:3.8-alpine` ran successfully. There is a dependabot PR (https://github.com/aws/aws-cli/pull/8240) for updating the pyinstaller version used. Please refer to that PR for updates. Hope that helps, let us know if you had any other questions.

**Comment by jgournet** [comment]
Hi @tim-finnigan 
Any chance https://github.com/aws/aws-cli/pull/8240 can be speeded up ?

Our pipeline to refresh aws-cli has been failing for a month now, and we would like it to work again (I know, we could set python to 3.8, but we actually need to stay on 3.10 or latest)

Thank you ;)

**Comment by tim-finnigan** [comment]
@jgournet have you tried using `python:3.10-alpine`? That also ran successfully for me when used in your Dockerfile. Also this documentation in the User Guide covers the official v2 image in case that is something you wanted to consider using: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-docker.html
