### ISSUE TITLE
aws dynamodb list-tables --endpoint-url https://localhost:8000 doesn't work in ubuntu 20.04

### ISSUE THREAD

**Issue by dallas1287** [aws/aws-cli#8363]
### Describe the bug

I'm trying to use dynamodb-local in a docker container on an ubuntu 20.04 machine. But it can't connect to the exposed port. I'm using the same setup on a windows machine and the same containers and the dynamodb list-tables command works just fine at the local endpoint. The aws dynmodb list-tables command works fine when pointed at actual tables in the cloud and that returns immediately but it can't connect to the local endpoint.

### Expected Behavior

 the local endpoint works the same as the cloud endpoint and the same behavior as my windows instnace

### Current Behavior

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/botocore/httpsession.py", line 254, in send
    urllib_response = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 376, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 330, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: AWSHTTPConnectionPool(host='localhost', port=8000): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/lib/python3/dist-packages/botocore/retryhandler.py", line 316, in __call__
    checker_response = checker(attempt_number, response,
  File "/usr/lib/python3/dist-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(
  File "/usr/lib/python3/dist-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/usr/lib/python3/dist-packages/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/usr/lib/python3/dist-packages/botocore/endpoint.py", line 269, in _send
    return self.http_session.send(request)
  File "/usr/lib/python3/dist-packages/botocore/httpsession.py", line 289, in send
    raise ReadTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "http://localhost:8000/"

### Reproduction Steps

spin up a standard docker container for dynamodb-local and then run
aws dynamodb list-tables --endpoint-url http://localhost:8000

### CLI version used

2.12.6

### Environment details (OS name and version, etc.)

Ubuntu 20.04 LTS

**Comment by tim-finnigan** [comment]
Hi @dallas1287 thanks for reaching out. I found a few related issues such as https://github.com/aws/aws-cli/issues/5531 and https://github.com/aws/aws-sdk-js-v3/issues/4294. Have you tried passing in fake credentials as described in https://github.com/aws/aws-cli/issues/5531#issuecomment-724814668, or changing `localhost` to `127.0.0.1` as suggested in https://github.com/aws/aws-sdk-js-v3/issues/4294#issuecomment-1541191147? Can you also confirm that no firewall configurations are preventing your connection?
