### ISSUE TITLE
Unable to load data for: aws/_regions

### ISSUE THREAD

**Issue by peschkaj** [aws/aws-cli#839]
When I attempt to run `aws cli configure` (or any other command) I get an error that aws-cli is unable to load data from aws/_regions.

System configuration
- Python 3.4.1
- Linux 3.15-3-1-ARCH
- aws-cli 1.3.13-1 (installed from [Arch User Repository](https://aur.archlinux.org/packages/aws-cli/))
- python-boto 2.30.0-1
- python-botocore 0.51.0-1

Full stack trace:

```
Traceback (most recent call last):
  File "/usr/bin/aws", line 23, in <module>
    sys.exit(main())
  File "/usr/bin/aws", line 19, in main
    return awscli.clidriver.main()
  File "/usr/lib/python3.4/site-packages/awscli/clidriver.py", line 46, in main
    return driver.main()
  File "/usr/lib/python3.4/site-packages/awscli/clidriver.py", line 183, in main
    parser = self._create_parser()
  File "/usr/lib/python3.4/site-packages/awscli/clidriver.py", line 164, in _create_parser
    command_table['help'] = self.create_help_command()
  File "/usr/lib/python3.4/site-packages/awscli/clidriver.py", line 156, in create_help_command
    self._get_argument_table(),
  File "/usr/lib/python3.4/site-packages/awscli/clidriver.py", line 91, in _get_argument_table
    self._argument_table = self._build_argument_table()
  File "/usr/lib/python3.4/site-packages/awscli/clidriver.py", line 134, in _build_argument_table
    choices = list(self.session.get_data(choices_path))
  File "/usr/lib/python3.4/site-packages/botocore/session.py", line 460, in get_data
    return self.get_component('data_loader').load_data(data_path)
  File "/usr/lib/python3.4/site-packages/botocore/loaders.py", line 43, in _wrapper
    data = func(self, orig_key, **kwargs)
  File "/usr/lib/python3.4/site-packages/botocore/loaders.py", line 202, in load_data
    return self._load_data(data_path)
  File "/usr/lib/python3.4/site-packages/botocore/loaders.py", line 221, in _load_data
    raise DataNotFoundError(data_path=data_path)
botocore.exceptions.DataNotFoundError: Unable to load data for: aws/_regions
```

**Comment by jeevankumar626** [comment]
Traceback (most recent call last):
  File "C:/Users/Jeevan/AppData/Local/Programs/Python/Python37-32/awsServics.py", line 3, in <module>
    s3 = boto3.resource("Amazon s3")
  File "C:\Users\Jeevan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\boto3\__init__.py", line 87, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "C:\Users\Jeevan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\boto3\session.py", line 257, in resource
    service_name, 'resources-1')
  File "C:\Users\Jeevan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\botocore\loaders.py", line 119, in _wrapper
    data = func(self, *args, **kwargs)
  File "C:\Users\Jeevan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\botocore\loaders.py", line 280, in determine_latest_version
    return max(self.list_api_versions(service_name, type_name))
  File "C:\Users\Jeevan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\botocore\loaders.py", line 119, in _wrapper
    data = func(self, *args, **kwargs)
  File "C:\Users\Jeevan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\botocore\loaders.py", line 309, in list_api_versions
    raise DataNotFoundError(data_path=service_name)
botocore.exceptions.DataNotFoundError: Unable to load data for: Amazon s3
>>> 




how can i fix this error
