### ISSUE TITLE
EC2::Client#describe_security_groups undocumented & unchecked options limitation.

### ISSUE THREAD

**Issue by NathanZookCH** [aws/aws-cli#8507]
### Describe the issue

group_names: option is incompatible with filters: { name: 'vpc-id', } option.

This looks pretty much like a bug, but I expect it is a lot easier to get a documentation fix than a change to the API.

Demonstration from the ruby api:
```ruby

vpc_id = LambdaFunction::WorkerLambda::VPC_ID.to_s
group_name = ec2.describe_security_groups(
  filters: [{name: 'vpc-id', values: [vpc_id]
}]).security_groups[4].group_name

ec2.describe_security_groups(
  filters: [{name: 'vpc-id', values: [vpc_id]}],
  group_names: [group_name]
)
```
```
/usr/local/bundle/gems/aws-sdk-core-3.190.2/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call':
The security group 'security-group' does not exist in default VPC 'vpc-12345678' (Aws::EC2::Errors::InvalidGroupNotFound)
```
So the options check does not fail.  This looks like a bug in the client, but since we're getting an exception anyway...

I also note that the API documentation indicates that group_ids is a required field if you are not in the default vpc.  If this were true, it would be a severe bug.  Thankfully, the API does not require this, at least for the case I observe.

### Links

https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-security-groups.html
https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EC2/Client.html#describe_security_groups-instance_method

**Comment by NathanZookCH** [comment]
After some noodling, I realized that there is a reasonable workaround:  tag the security group with it's name!  That is, 

```ruby
ec2.describe_security_groups(
  filters: [
    {name: 'vpc-id', values: [vpc_id]},
    {name: 'tag:name', values: [group_name]}
  ]
)
```

Works if you `#create_tags(resources: [group_id], tags: [{ key: name, value: group_name}])` first.

**Comment by akshat2203** [comment]
The error message you provided indicates that there is an issue with using both the group_names and filters options together when calling the describe_security_groups method in the AWS SDK for Ruby.

**Comment by Rameshk84** [comment]
> ### Describe the issue
> group_names: option is incompatible with filters: { name: 'vpc-id', } option.
> 
> This looks pretty much like a bug, but I expect it is a lot easier to get a documentation fix than a change to the API.
> 
> Demonstration from the ruby sdk:
> 
> ```ruby
> vpc_id = LambdaFunction::WorkerLambda::VPC_ID.to_s
> group_name = ec2.describe_security_groups(
>   filters: [{name: 'vpc-id', values: [vpc_id]
> }]).security_groups[4].group_name
> 
> ec2.describe_security_groups(
>   filters: [{name: 'vpc-id', values: [vpc_id]}],
>   group_names: [group_name]
> )
> ```
> 
> ```
> /usr/local/bundle/gems/aws-sdk-core-3.190.2/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call':
> The security group 'security-group' does not exist in default VPC 'vpc-12345678' (Aws::EC2::Errors::InvalidGroupNotFound)
> ```
> 
> So the options check does not fail. This looks like a bug in the client, but since we're getting an exception anyway...
> 
> I also note that the API documentation indicates that group_ids is a required field if you are not in the default vpc. If this were true, it would be a severe bug. Thankfully, the API does not require this, at least for the case I observe.
> 
> ### Links
> https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-security-groups.html https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EC2/Client.html#describe_security_groups-instance_method

This is my Answer for this documentation i tried this solution using some other Ai tools to leverage my work :

It seems like you're encountering an issue with the AWS SDK for Ruby when using the describe_security_groups method. The error message indicates an incompatibility between the group_names and filters options.

The issue appears to arise when you provide both group_names and filters options in the describe_security_groups call. The error message suggests that the provided security group name (group_name) does not exist in the default VPC.

It's important to note that the AWS API documentation indicates that group_ids is a required field if you are not in the default VPC. However, you've observed that this is not the case in your scenario.

This discrepancy between the documented behavior and the actual behavior you're experiencing could indeed indicate a bug in the AWS SDK for Ruby. It might be worth checking the AWS SDK for Ruby's issue tracker or forums to see if others have reported similar issues. Additionally, reaching out to AWS support could provide further insights or assistance in resolving this issue.

In the meantime, you might consider adjusting your code to either use group_ids instead of group_names or to remove the group_names option altogether if it's not necessary for your use case. This might help to work around the issue until a fix is available.

**Comment by RyanFitzSimmonsAK** [comment]
Hi @NathanZookCH, thanks for reaching out.  I'm having some issues reproducing this behavior.  Given that you did your testing in the Ruby SDK, unless you were able to reproduce this in the CLI as well, it might be more helpful for me to transfer this issue to the AWS SDK for Ruby repository.

I did my testing using the following syntax, and had no problems.

`aws ec2 describe-security-groups --filters Name=vpc-id,Values=myvpcid Name=group-name,Values=test`

Could you verify if you were able to reproduce the behavior in the CLI, or only Ruby?  If you were, debug logs might be beneficial.  You can get debug logs by adding `--debug` to your command, and redacting any sensitive information.  Thanks!

**Comment by NathanZookCH** [comment]
I only used the ruby sdk.  I believe I posted here because I expected the
documentation to be more likely to be updated than the code.

Sincerely,

Nathan Zook
Carrum Health
Senior Devops Engineer

**Comment by RyanFitzSimmonsAK** [comment]
Given that it appears to be an SDK for Ruby-exclusive bug, I'm going to transfer it to that repository for triage and reproduction.
