### ISSUE TITLE
InvalidGrantException while refresh auth token

### ISSUE THREAD

**Issue by Freewister** [aws/aws-cli#8561]
### Describe the bug

I try to use the command `aws s3 ls` to list all s3 buckets in my current profile. I am aware that my token has expired and the cli tries to refresh my token. The refresh failed.

### Expected Behavior

The aws cli refreshes the token automatically and I can request s3 buckets or use the cli with a different command.

### Current Behavior

 With `aws s3 ls --debug` I see the following exception:

```
2024-03-06 10:54:27,094 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oidc.eu-central-1.amazonaws.com:443
2024-03-06 10:54:27,185 - MainThread - urllib3.connectionpool - DEBUG - https://oidc.eu-central-1.amazonaws.com:443 "POST /token HTTP/1.1" 400 78
2024-03-06 10:54:27,185 - MainThread - botocore.parsers - DEBUG - Response headers: {'Date': 'Wed, 06 Mar 2024 09:54:27 GMT', 'Content-Type': 'application/json', 'Content-Length': '78', 'Connection': 'keep-alive', 'x-amzn-RequestId': '8506bebb-9eca-4771-9336-953ba378efb1', 'x-amzn-ErrorType': 'InvalidGrantException:http://internal.amazon.com/coral/com.amazonaws.sso.oidc/'}
2024-03-06 10:54:27,185 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"error":"invalid_grant","error_description":"Invalid refresh token provided"}'
2024-03-06 10:54:27,186 - MainThread - botocore.parsers - DEBUG - Response headers: {'Date': 'Wed, 06 Mar 2024 09:54:27 GMT', 'Content-Type': 'application/json', 'Content-Length': '78', 'Connection': 'keep-alive', 'x-amzn-RequestId': '8506bebb-9eca-4771-9336-953ba378efb1', 'x-amzn-ErrorType': 'InvalidGrantException:http://internal.amazon.com/coral/com.amazonaws.sso.oidc/'}
2024-03-06 10:54:27,186 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"error":"invalid_grant","error_description":"Invalid refresh token provided"}'
2024-03-06 10:54:27,186 - MainThread - botocore.hooks - DEBUG - Event needs-retry.sso-oidc.CreateToken: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x7f47f8bb2c90>>
2024-03-06 10:54:27,186 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2024-03-06 10:54:27,187 - MainThread - botocore.hooks - DEBUG - Event after-call.sso-oidc.CreateToken: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x7f47f8bb2690>>
2024-03-06 10:54:27,187 - MainThread - botocore.tokens - WARNING - SSO token refresh attempt failed
Traceback (most recent call last):
  File "awscli/botocore/tokens.py", line 299, in _refresh_access_token
  File "awscli/botocore/tokens.py", line 258, in _attempt_create_token
  File "awscli/botocore/client.py", line 357, in _api_call
  File "awscli/botocore/client.py", line 724, in _make_api_call
botocore.errorfactory.InvalidGrantException: An error occurred (InvalidGrantException) when calling the CreateToken operation: 
2024-03-06 10:54:27,188 - MainThread - botocore.credentials - WARNING - Refreshing temporary credentials failed during mandatory refresh period.
Traceback (most recent call last):
  File "awscli/botocore/credentials.py", line 518, in _protected_refresh
  File "awscli/botocore/credentials.py", line 659, in fetch_credentials
  File "awscli/botocore/credentials.py", line 669, in _get_cached_credentials
  File "awscli/botocore/credentials.py", line 2043, in _get_credentials
  File "awscli/botocore/tokens.py", line 84, in get_frozen_token
  File "awscli/botocore/tokens.py", line 97, in _refresh
  File "awscli/botocore/tokens.py", line 124, in _protected_refresh
botocore.exceptions.TokenRetrievalError: Error when retrieving token from sso: Token has expired and refresh failed
2024-03-06 10:54:27,188 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/clidriver.py", line 460, in main
  File "awscli/customizations/commands.py", line 151, in __call__
  File "awscli/customizations/commands.py", line 205, in __call__
  File "awscli/customizations/s3/subcommands.py", line 506, in _run_main
  File "awscli/customizations/s3/subcommands.py", line 571, in _list_all_buckets
  File "awscli/botocore/client.py", line 357, in _api_call
  File "awscli/botocore/client.py", line 710, in _make_api_call
  File "awscli/botocore/client.py", line 730, in _make_request
  File "awscli/botocore/endpoint.py", line 101, in make_request
  File "awscli/botocore/endpoint.py", line 131, in _send_request
  File "awscli/botocore/endpoint.py", line 114, in create_request
  File "awscli/botocore/hooks.py", line 228, in emit
  File "awscli/botocore/hooks.py", line 211, in _emit
  File "awscli/botocore/signers.py", line 94, in handler
  File "awscli/botocore/signers.py", line 164, in sign
  File "awscli/botocore/signers.py", line 270, in get_auth_instance
  File "awscli/botocore/credentials.py", line 607, in get_frozen_credentials
  File "awscli/botocore/credentials.py", line 502, in _refresh
  File "awscli/botocore/credentials.py", line 518, in _protected_refresh
  File "awscli/botocore/credentials.py", line 659, in fetch_credentials
  File "awscli/botocore/credentials.py", line 669, in _get_cached_credentials
  File "awscli/botocore/credentials.py", line 2043, in _get_credentials
  File "awscli/botocore/tokens.py", line 84, in get_frozen_token
  File "awscli/botocore/tokens.py", line 97, in _refresh
  File "awscli/botocore/tokens.py", line 124, in _protected_refresh
botocore.exceptions.TokenRetrievalError: Error when retrieving token from sso: Token has expired and refresh failed

Error when retrieving token from sso: Token has expired and refresh failed
```

The cli tries to refresh but provides an invalid grant.

### Reproduction Steps

Wait till the session or token expires and try to use the aws cli. E. g. `aws s3 ls`.

### Additional Information/Context

There was already a closed issue without more information about this behavior: 
https://github.com/aws/aws-cli/issues/7692

### CLI version used

aws-cli/2.15.25 Python/3.11.8 Linux/6.5.0-21-generic exe/x86_64.ubuntu.22 prompt/off

### Environment details (OS name and version, etc.)

Ubuntu 6.5.0-17.17~22.04.1-generic 6.5.8

**Comment by Freewister** [comment]
Okay the problem was the sso session expiration. In my case the sessione expires after 8 hours and therefore a refresh is no longer possible. This is intended behaviour from aws.
