### ISSUE TITLE
s3: Max retries exceeded with url

### ISSUE THREAD

**Issue by degtyarevalexey** [aws/aws-cli#928]
Uploading to s3 bucket in eu-west-1 region fails with:

```
2014-10-05 17:03:47,171 - Thread-9 - botocore.retryhandler - DEBUG - retry needed, retryable exception
caught: HTTPSConnectionPool(host='s3-eu-west-1.amazonaws.com', port=443): Max retries exceeded
with url: /hostname.backup/data.20141005.tar.gz.aes256?
partNumber=6&uploadId=UIqmKD4klVEuOzrZHaWolQ4vywXONM7iF4E_HIV0WvMlleEAaiQDchGTWG.wD5eLmHd3LDJCXfNm_7qC69iGoIcbOo36EoRsG.ONMHsXZcrSHGFMG6N3MzNpncvjkUgp 
(Caused by <class 'socket.error'>: [Errno 104] Connection reset by peer)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 262, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 310, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 219, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 352, in _check_caught_exception
    raise caught_exception
ConnectionError: HTTPSConnectionPool(host='s3-eu-west-1.amazonaws.com', port=443): 
Max retries exceeded with url: /hostname.backup/data.20141005.tar.gz.aes256?
partNumber=6&uploadId=UIqmKD4klVEuOzrZHaWolQ4vywXONM7iF4E_HIV0WvMlleEAaiQDchGTWG.wD5eLmHd3LDJCXfNm_7qC69iGoIcbOo36EoRsG.ONMHsXZcrSHGFMG6N3MzNpncvjkUgp 
(Caused by <class 'socket.error'>: [Errno 104] Connection reset by peer)
```

Upload to default US region works fine from the same host.

```
CLI version: aws-cli/1.4.4 Python/2.7.6 Linux/3.13.0-36-generic, botocore version: 0.63.0
```

**Comment by jamesls** [comment]
Consolidating issues.  Tracking this issue over here: https://github.com/aws/aws-cli/issues/1092 which allows for a customer to modify the number of retries.
