### ISSUE TITLE
Dynamodb get-item error: Codec can't decode byte

### ISSUE THREAD

**Issue by jmonson** [aws/aws-cli#950]
I have a similar problem with issue #853 and #593. This was working in the past and looks like it started failing around September 9, 2014.

Command:
aws dynamodb get-item --table-name XXX --key "{\"Id\":{\"N\":\"YYY\"}}" --debug

Output:
2014-10-15 13:04:25,934 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.5.1 Python/2.7.5 Windows/8, botocore version: 0.65.0
2014-10-15 13:04:25,934 - MainThread - botocore.service - DEBUG - Creating service object for: dynamodb
2014-10-15 13:04:25,944 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.dynamodb: calling handler <function signature_overrides at 0x0000000002869D68>
2014-10-15 13:04:25,946 - MainThread - botocore.hooks - DEBUG - Event service-created: calling handler <function register_retries_for_service at 0x0000000002869C18>
2014-10-15 13:04:25,947 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: Service(dynamodb)
2014-10-15 13:04:25,948 - MainThread - botocore.service - DEBUG - Creating operation objects for: Service(dynamodb)
2014-10-15 13:04:25,950 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'table-name', <awscli.arguments.CLIArgument object at 0x00000000033A8E10>), (u'key', <awscli.arguments.CLIArgument object at 0x00000000033A8E48>), (u'attributes-to-get', <awscli.arguments.ListArgument object at 0x00000000033A8E80>), (u'consistent-read', <awscli.arguments.BooleanArgument object at 0x00000000033A8EB8>), (u'no-consistent-read', <awscli.arguments.BooleanArgument object at 0x00000000033A8EF0>), (u'return-consumed-capacity', <awscli.arguments.CLIArgument object at 0x00000000033A8F28>), (u'projection-expression', <awscli.arguments.CLIArgument object at 0x00000000033A8F98>), (u'expression-attribute-names', <awscli.arguments.CLIArgument object at 0x00000000033A8FD0>)])
2014-10-15 13:04:25,951 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.dynamodb.get-item: calling handler <function unify_paging_params at 0x0000000002B5A208>
2014-10-15 13:04:25,956 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.dynamodb.get-item.table-name: calling handler <function uri_param at 0x0000000002B3F208>
2014-10-15 13:04:25,957 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.dynamodb.get-item: calling handler <awscli.argprocess.ParamShorthand object at 0x0000000002B510B8>
2014-10-15 13:04:25,960 - MainThread - awscli.argprocess - DEBUG - Detected structure: scalar
2014-10-15 13:04:25,963 - MainThread - awscli.arguments - DEBUG - Unpacked value of "XXX" for parameter "table_name": XXX
2014-10-15 13:04:25,964 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.dynamodb.get-item.key: calling handler <function uri_param at 0x0000000002B3F208>
2014-10-15 13:04:25,967 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.dynamodb.get-item: calling handler <awscli.argprocess.ParamShorthand object at 0x0000000002B510B8>
2014-10-15 13:04:25,970 - MainThread - awscli.argprocess - DEBUG - Param key looks like JSON, not considered for param shorthand.
2014-10-15 13:04:25,973 - MainThread - awscli.arguments - DEBUG - Unpacked value of "{"Id":{"N":"YYY"}}" for parameter "key": OrderedDict([(u'Id', OrderedDict([(u'N', u'YYY')]))])
2014-10-15 13:04:25,976 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.dynamodb.get-item.attributes-to-get: calling handler <function uri_param at 0x0000000002B3F208>
2014-10-15 13:04:25,977 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.dynamodb.get-item.consistent-read: calling handler <function uri_param at 0x0000000002B3F208>
2014-10-15 13:04:25,980 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.dynamodb.get-item.return-consumed-capacity: calling handler <function uri_param at 0x0000000002B3F208>
2014-10-15 13:04:25,983 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.dynamodb.get-item.projection-expression: calling handler<function uri_param at 0x0000000002B3F208>
2014-10-15 13:04:25,986 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.dynamodb.get-item.expression-attribute-names: calling handler <function uri_param at 0x0000000002B3F208>
2014-10-15 13:04:25,989 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2014-10-15 13:04:25,992 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2014-10-15 13:04:25,993 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: config-file
2014-10-15 13:04:25,996 - MainThread - botocore.credentials - INFO - Credentials found in config file: ~/.aws/config
2014-10-15 13:04:26,000 - MainThread - botocore.operation - DEBUG - Operation:GetItem called with kwargs: {u'TableName': u'XXX', u'Key': OrderedDict([(u'Id', OrderedDict([(u'N', u'YYY')]))])}
2014-10-15 13:04:26,038 - MainThread - botocore.endpoint - DEBUG - Making request for <botocore.model.OperationModel object at 0x00000000033A8160> (verify_ssl=True) with params: {'query_string': '', 'headers': {'Content-Type': u'application/x-amz-json-1.0', 'X-Amz-Target': u'DynamoDB_20120810.GetItem'}, 'url_path': '/', 'body': '{"TableName": "XXX", "Key": {"Id": {"N": "YYY"}}}', 'method': u'POST'}
2014-10-15 13:04:26,039 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2014-10-15 13:04:26,040 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-amz-json-1.0
host:dynamodb.us-east-1.amazonaws.com
user-agent:aws-cli/1.5.1 Python/2.7.5 Windows/8
x-amz-date:20141015T170426Z
x-amz-target:DynamoDB_20120810.GetItem

content-type;host;user-agent;x-amz-date;x-amz-target
ac452b7560e0b4c1ae5bd4393453894c9c33926f29c0340be2f89ca1f6d7a9c2
2014-10-15 13:04:26,043 - MainThread - botocore.auth - DEBUG - StringToSign:AWS4-HMAC-SHA25620141015T170426Z20141015/us-east-1/dynamodb/aws4_requesta61d5663b12934c6067cb703f354db2897028bb969ab50f3c6ccb9252863b1ca
2014-10-15 13:04:26,046 - MainThread - botocore.auth - DEBUG - Signature:20f52474ea6f4101cec267b03a3e7cece714e5326c87463c6eec566953f8a9cb
2014-10-15 13:04:26,056 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2014-10-15 13:04:26,056 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): dynamodb.us-east-1.amazonaws.com
2014-10-15 13:04:26,487 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "POST / HTTP/1.1" 200 6080
2014-10-15 13:04:26,489 - MainThread - botocore.parsers - DEBUG - Response body: {"Item":{"KeyId":{"N":"748"},"Version":{"S":"46ff6f90-2b53-423f-82ed-8868931d86eb"},"Id":{"N":"YYY"},"Item":{"B":"kXADOgp ... w=="},"LastUpdatedOn":{"S":"2014-09-24T19:40:54.495Z"}}}
2014-10-15 13:04:26,506 - MainThread - botocore.hooks - DEBUG - Event needs-retry.dynamodb.GetItem: calling handler <botocore.retryhandler.RetryHandler object at 0x0000000002C8CE48>
2014-10-15 13:04:26,506 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2014-10-15 13:04:26,509 - MainThread - botocore.hooks - DEBUG - Event after-call.dynamodb.GetItem: calling handler <awscli.errorhandler.ErrorHandler object at 0x0000000002C778D0>
2014-10-15 13:04:26,513 - MainThread - awscli.errorhandler - DEBUG - HTTP Response Code: 200
2014-10-15 13:04:26,516 - MainThread - awscli.formatter - DEBUG - RequestId: 2AFC0J95OQA5J86LKD5SBK8FSJVV4KQNSO5AEMVJF66Q9ASUAAJG
{
    "Item": {
        "Item": {
            "B": 2014-10-15 13:04:26,529 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli\clidriver.pyc", line 206, in main
  File "awscli\clidriver.pyc", line 354, in __call__
  File "awscli\clidriver.pyc", line 461, in __call__
  File "awscli\clidriver.pyc", line 566, in invoke
  File "awscli\clidriver.pyc", line 574, in _display_response
  File "awscli\formatter.pyc", line 72, in __call__
  File "awscli\formatter.pyc", line 87, in _format_response
  File "json\__init__.pyc", line 189, in dump
  File "json\encoder.pyc", line 434, in _iterencode
  File "json\encoder.pyc", line 408, in _iterencode_dict
  File "json\encoder.pyc", line 408, in _iterencode_dict
  File "json\encoder.pyc", line 390, in _iterencode_dict
UnicodeDecodeError: 'utf8' codec can't decode byte 0x91 in position 0: invalid start byte
2014-10-15 13:04:26,529 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

'utf8' codec can't decode byte 0x91 in position 0: invalid start byte

**Comment by jamesls** [comment]
Just wanted to follow up on this issue.  It looks like we didn't link to this issue from the PR that fixed it.  This should be fixed now.  If you are still seeing issues on the latest versions of the CLI let us know and we'll take another look.

**Comment by jmonson** [comment]
It works, thanks again!
