### ISSUE TITLE
Error in bash completion for "aws configure"

### ISSUE THREAD

**Issue by adamv** [aws/aws-cli#967]
On version 1.5.2, doing `aws configure <tab>` gives me:

```
$ aws configure Traceback (most recent call last):
  File "/usr/local/bin/aws_completer", line 23, in <module>
    awscli.completer.complete(cline, cpoint)
  File "/usr/local/lib/python2.7/dist-packages/awscli/completer.py", line 166, in complete
    choices = Completer().complete(cmdline, point)
  File "/usr/local/lib/python2.7/dist-packages/awscli/completer.py", line 155, in complete
    self._process_command_line()
  File "/usr/local/lib/python2.7/dist-packages/awscli/completer.py", line 138, in _process_command_line
    self.command_hc = cmd_obj.create_help_command()
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/commands.py", line 226, in create_help_command
    arg_table=self.arg_table)
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/commands.py", line 257, in arg_table
    if self._arg_table is None:
AttributeError: 'ConfigureCommand' object has no attribute '_arg_table'
```

**Comment by jamesls** [comment]
Looks like we didn't link the commit that fixed this with this issue.  Closing, this is now fixed.
